### PR TITLE
spacemacs buffer shortcuts and widget ui

### PR DESCRIPTION
**Pull request by CarlQLange**
OK, in accordance with #1022, this PR adds key shortcuts for the spacemacs buffer, and replaces the buttons with widgets.

To use:
`p`: Projects
`r`: Recent files
`b`: Bookmarks
`TAB`: Next button
`S-TAB`: Previous button

This also opens the door to a nicer-looking startup buffer (eg with a few colours with faces). However I didn't want to get into learning how faces work just yet.

I'm curious about adding the TAB and S-TAB keybindings - I have them in a hook for `spacemacs-mode`, using `local-set-key`. No clue if that's the right place to put them.

### CODE REVIEW

**Comment by danielwuz** [comment]
As a reference, I integrated `ace-link` and added the ability to jump to any links in spacemacs buffer with key `o` in this PR https://github.com/syl20bnr/spacemacs/pull/1073

**Comment by syl20bnr** [comment]
Works flawlessly. Great contribution :heart: 

Thank you !
Cherry-picked into `develop` branch, you can safely delete your branch.

**Comment by chrisbarrett** [comment]
@CarlQLange I know it's a bit late for this PR, but in general it's nicer practice to explicitly define the keymap variable for the major-mode and add key bindings there. That way, users can override the key bindings using `define-key`, `evil-define-key`, etc.

```elisp
(defvar spacemacs-mode-map
  (let ((keymap (make-sparse-keymap)))
    (define-key (kbd "TAB") 'widget-forward)
    (define-key (kbd "S-tab") 'widget-backward)
    keymap)
```

By setting key bindings in a hook, users need to add their own hook to override those keybindings. This creates an ordering dependency and can be difficult to debug.

For `spacemacs-mode` this isn't an issue because users are very unlikely to try to customise it, but just a thought. :)

**Comment by CarlQLange** [comment]
Aha! I shall do this, that's great to know. Only been writing elisp for the last two or three weeks so I'm sure there're a few other things like this :)

**Comment by chrisbarrett** [comment]
You're doing good :)

**Pull request closed without merging**
