### PR TITLE
Breaking Bug Fix ERC related errors

### PR DESCRIPTION
**Pull request by CestDiego**
Is there a change in the way things are loaded?

### CODE REVIEW

**Comment by syl20bnr** [comment]
I removed the quoted `erc`'s in `with-eval-after-load` and somehow it breaks. `with-eval-after-load` is a macro and it should not be quoted but maybe use-package does something with it.
I forgot to test the change, sorry.

**Comment by TheBB** [comment]
Just because it's a macro doesn't mean it shouldn't be quoted, really depends on what the macro does.

```
ELISP> (macroexpand '(with-eval-after-load erc (message "hi")))
(eval-after-load erc
  (lambda nil
    (message "hi")))
```

It shouldn't be quoted in `use-package-add-hook` but it should be quoted in `with-eval-after-load`.

**Comment by syl20bnr** [comment]
So the other `with-eval-after-load` in the code base are wrong since they are not quoted.

**Comment by syl20bnr** [comment]
wow seems my brain bugged last night, everything is quoted in the code base...

**Comment by syl20bnr** [comment]
OK... I understand what happened now, thank you guys.
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by CestDiego** [comment]
It's a pleasure. :)  I'm happy we found this soonish enough

**Pull request closed without merging**
