### PR TITLE
Add company-flx for flex matching in Company

### PR DESCRIPTION
**Pull request by lunaryorn**

### CODE REVIEW

**Comment by lunaryorn** [comment]
See https://github.com/PythonNut/company-flx

**Comment by lunaryorn** [comment]
That's just not yet there, and didn't feel so great when using it.

**Comment by mssun** [comment]
@lunaryorn Indeed. Did you successfully trigger the fuzzy matching feature? I tried your commit in my settings but still couldn't use any fuzzy matching to complete function typing in c-c++ layer.

**Comment by lunaryorn** [comment]
Yes, but I'm not sure if it was with this change (I had a copy of that in my layers, maybe that was different), and not with C++.

**Comment by mssun** [comment]
Can you share your settings? Cause I don't want to use ycm for fuzzy matching.

**Comment by lunaryorn** [comment]
@mssun [This was how it looked like](https://github.com/lunaryorn/dotfiles/commit/3f79b49d3290ce6fde77998b03e685ff1a8a8c3b) when I removed it again.  As I said, I'm not using it anymore, because it didn't feel that great.

**Pull request closed without merging**
