### PR TITLE
Add SPC-m-t-R keybinding for org-table-iterate

### PR DESCRIPTION
**Pull request by Dillonb**
This adds a keybinding for `org-table-iterate`, which recalculates the entire table by iterating over it re-evaluating rows until the table's content does not change.

Currently, Spacemacs only has a binding for org-table-recalculate, which recalculates one row at a time. I thought capital R made sense for this, but am open to suggestions.

### CODE REVIEW

**Comment by Dillonb** [comment]
I'm not sure why the tests are failing. They also fail locally for me, even on the `develop` branch, assuming I'm running them correctly.

```
cd tests/doc
make
```

Results in:

```
2 unexpected results:
FAILED  test-spacemacs-html-export
FAILED  test-toc-org-insert-toc
```

**Comment by JAremko** [comment]
@Dillonb  Travis failed because we're incrementally  improving documentation.
```
Link "../../+lang/bibtex/README.org" in "/home/travis/.emacs.d/layers/+emacs/org/README.org"  
 should target the org file at GitHub (GitHub style anchors are supported)
```
Replace  `../../+lang/bibtex/README.org`  in `/layers/+emacs/org/README.org` with `https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/bibtex/README.org` and it should be ok.

*You got this report because you modified org file with the link that needs fixing*

**Comment by Dillonb** [comment]
@JAremko This look good to you?

**Comment by JAremko** [comment]
@Dillonb  Great, thx :+1:

**Pull request closed without merging**
