### PR TITLE
remove redundant yasnippt submodule. use yasnippet-install-dir instead.

### PR DESCRIPTION
**Pull request by mkcode**
Cleanups yas-snippet-dirs to what they should be. The melpa yasnippet package includes https://github.com/AndreaCrotti/yasnippet-snippets as a submodule and sets it to ` yas-installed-snippets-dir` so we do not need to handle this in spacemacs.

`yas-snippet-dirs` before PR: 
```
("/Users/chris/.emacs.d/private/snippets" "/Users/chris/.emacs.d/spacemacs/extensions/yasnippet-snippets")
```

`yas-snippet-dirs` after PR: 
```
 ("~/.emacs.d/snippets" yas-installed-snippets-dir "/Users/chris/.emacs.d/private/snippets")
```

### CODE REVIEW

**Comment by mkcode** [comment]
Moved the (yas-global-mode 1) line to the top of `spacemacs/load-yasnippet` so the initial value of `yas-snippet-dirs` is always defined. Let me know if that is an issue.

Also, is there a reason why we don't just put the body of `spacemacs/load-yasnippet` into the yas-global-mode-hook` and just turn on yas-global-mode in prog-mode, markdown-mode, org-mode? At the moment `spacemacs/load-yasnippet` will not be evaluated if executed with the toggle `SPC t y`

**Comment by mkcode** [comment]
https://travis-ci.org/syl20bnr/spacemacs/builds/62001426#L90

Not sure why the CI server is trying grab the submodule still, since it was removed from the .gitmodules here: https://github.com/syl20bnr/spacemacs/pull/1566/files#diff-8903239df476d7401cf9e76af0252622L22

**Comment by syl20bnr** [comment]
Did you use `git rm` to remove the submodule ?

**Comment by mkcode** [comment]
@syl20bnr - thanks. I did not. Running `git submodule deinit` fixed this.

**Comment by louy2** [comment]
Do I have to remove the submodule manually on local or will it be removed upon pulling?

**Comment by mkcode** [comment]
@louy2 - You should not need to remove it, just pull. Although it is possible there that there will be a left over entry in your `.git/config` file, in which case you can delete that entry.

**Comment by syl20bnr** [comment]
Oh yeah, you know that removing a sub-module makes me very happy ? :-)
Thank you ! :heart: 
Cherry-picked into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
