### PR TITLE
Rename the idris-lang layer to idris

### PR DESCRIPTION
**Pull request by zmthy**
The idris-mode package has been updated to no longer use the `idris-packages` variable, which allows the Idris layer to safely be renamed to the standard for other languages (see https://github.com/idris-hackers/idris-mode/commit/5c8d0fd30f4e5e488362caad069faf1afa1649c6).

### CODE REVIEW

**Comment by robbyoconnor** [comment]
You should also rename the directories -- then rebase and force-push.

**Comment by zmthy** [comment]
What other directories are there to rename?

**Comment by robbyoconnor** [comment]
The directory which contains this layer...look at its name...the directory name should ideally match the layer name.

**Comment by robbyoconnor** [comment]
Oh you did -- disregard -- I didn't see it -- :+1: :100:

**Comment by TheBB** [comment]
Thank you! Cherry-picked in the develop branch. You can safely delete your branch.

**Pull request closed without merging**
