### PR TITLE
Add eshell goodies

### PR DESCRIPTION
**Pull request by ppold**
I just noticed the new 'shell' layer and thought that it would be nice to include these additions to have a better eshell experience!

### CODE REVIEW

**Comment by CestDiego** [comment]
^ this

**Comment by trishume** [comment]
Perhaps you may be interested in incorporating some of the fixes from #1287, which was not merged.
I would do it except I decided not to use eshell, but since you seem to want to use it you might want the fixes I made.

**Comment by syl20bnr** [comment]
@ppold do you see any useful bit from #1287 you want to integrate in this PR or can I merge it ?

**Comment by ralesi** [comment]
Correct me if I am wrong, but we shouldn't need a use-package declaration for eshell right?

**Comment by tuhdo** [comment]
@ralesi You need to. Otherwise, you either have to load `eshell` or you will have void symbols, both are undesirable.

**Comment by trishume** [comment]
For future reference the two things that I think are really nice that this PR doesn't include that were in #1287 are really nice company support and automatically entering insert mode when switching to a shell buffer.

**Comment by syl20bnr** [comment]
Thank you ! :+1: 

I heavily reformatted this PR to get rid of the useless nested use-package and enable lazy-loading of eshell, I also integrated the recommended feature by @trishume like auto-completion support and auto-jump to prompt (not enabled when em-smart is enabled for now). `em-smart` is pretty surprising so we cannot enable it by default (it would appear as a bug for any non-aware user) so I create a variable `shell-enable-smart-eshell` which defaults to nil. All this is documented in the REAMDE.
Related commit: https://github.com/syl20bnr/spacemacs/commit/f88bb0c

Cherry-picked in `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
