### PR TITLE
fix keybindings for helm-locate-library

### PR DESCRIPTION
**Pull request by zilongshanren**

### CODE REVIEW

**Comment by zilongshanren** [comment]
`SPC sl` is bind for `spacemacs/resume-last-search-buffer`

**Comment by robbyoconnor** [comment]
:+1:

**Comment by robbyoconnor** [comment]
This has been cherry-picked, you can delete your branch :tongue:

**Comment by syl20bnr** [comment]
Thank you !
I merged it but I changed it right away for `SPC f e l` as we decided in an issue.

**Pull request closed without merging**
