### PR TITLE
Update which-key for MELPA

### PR DESCRIPTION
**Pull request by justbur**
It's on MELPA now. I started on a config for it here (tried to come up with reasonable descriptions for the SPC x commands), but we probably want to add more key descriptions.

### CODE REVIEW

**Comment by seschwar** [comment]
I don't know how mature or feature rich `which-key` is, but maybe it could replace `guide-key` by default. Since it supports

> A different polling mechanism to make it lighter on resources than guide-key

and therefore might be more kitten friendly (see #1263).

**Comment by justbur** [comment]
That's the idea at least :-). I'm the author and @bmag has helped a lot. It's pretty new and there are probably bugs to be found, but it has been stable for me. 

Feature wise it is not equivalent to guide-key (I think it's better of course :-)). The core functionality is finished and I've been adding some nice to have features. Probably the worst part is the documentation at the moment. 

I'm happy to take suggestions or bug reports.

**Comment by robbyoconnor** [comment]
:+1:

**Comment by bmag** [comment]
@seschwar I also think that which-key should become the default at some point, but maybe not right now. Since there are probably still bugs we haven't found, and @justbur is adding new features, I don't know if which-key is stable enough to be the deafult. Feature-wise I'm sure that which-key is ready to become the default, and it definitely should be at some point in the near future.

**Comment by justbur** [comment]
Not that I disagree with you @bmag, but it's not like guide-key is bug free. That was part of the motivation to write a new one in the first place.

**Comment by syl20bnr** [comment]
Thank you ! 
Tremendous work on this high-quality package :+1:

I decided to replace guide-key right now to be able to gather more feedback from users on `develop` branch. In the worst case I can always revert back to guide-key, anyway I used `which-key` for a couple of hours now and it works great :heart: 

Cherry-picked into `develop` branch, you can safely delete your branch.

**Comment by justbur** [comment]
Thanks! That's great. I'll fix anything that comes up right away.

**Pull request closed without merging**
