### PR TITLE
Closes #616, syntax error in osx layer snippet

### LINKED ISSUE #616: Can't start spacemacs tutor (SPC h T)
I'm completely new to spacemacs, coming from sublime, and can't figure out how to run SPC commands. I alias'd `emacs=/usr/local/Cellar/emacs-mac/emacs-24.4-mac-5.2/bin/emacs` in my `bash_profile`, type `emacs` in iTerm 2 or Terminal.app, see "Spacemacs is ready" at the bottom, hit the spacebar, then 'h' and I see "h is undefined" on the bottom. If I do `emacs some/file.js` I find myself in insert mode. I just want to start the spacemacs tutor (SPC h T) but can't find anything anywhere as to the exact keys/steps and will add whatever I'm missing to the documentation.md or readme.

I'm on OS X 10.10 Yosemite, installed just as instructed, `git clone --recursive http://github.com/syl20bnr/spacemacs ~/.emacs.d` and then added the OS X configuration layer to my ~/.spacemacs file `((setq-default dotspacemacs-configuration-layers '(osx)
  "List of contribution to load."
)`

halp

### PR DESCRIPTION
**Pull request by devinrhode2**

### CODE REVIEW

**Comment by devinrhode2** [comment]
@syl20bnr should we open another issue to display "Spacemacs load failed" instead of "Spacemacs is ready" when that's the case?

**Comment by syl20bnr** [comment]
.... you found a BIG error in aaaaaaallll the code snippets of all layers... I fixed the all after merging your PR. Thank you ! :+1: :+1: 

Cherry-picked into `develop`, you can safely delete your branch.

**Comment by devinrhode2** [comment]
You betcha! Thanks for making spacemacs! Today I'm working through
evil-tutor (yesterday got way too distracted discovering oh-my-zsh) and
will be adapting tutor.txt to spacemacs as I go along.

What account should the spacemacs fork of evil-tutor live?

I think a spacemacs org would be cool (spacemacs/tutor). Or we can put the
spacemacs-tutor fork under either of our accounts, I'd give you admin
access if we put it under my account.

If we go the org route we of course don't to move other spacemacs repos to
the org immediately, but should do so quickly to avoid confusion.

-Devin <http://zerply.com/DevinRhode2>
<http://zerply.com/devinrhode2>

**Comment by syl20bnr** [comment]
Sorry for the late reply. I don't plan to open an organization for now but it is possible to host a package directly in spacemacs repo under an `extensions` directory. This is the case for `helm-spacemacs` for instance. When I open an organization these kind of packages closely related to spacemacs will have their own repo hosted there but I don't feel ready for it yet.

**Comment by devinrhode2** [comment]
Certainly. It's not a decision to just make on a whim. no worries.


-Devin <http://zerply.com/DevinRhode2>
<http://zerply.com/devinrhode2>

**Pull request closed without merging**
