### PR TITLE
[WIP] Add Grails Layer

### PR DESCRIPTION
**Pull request by robbyoconnor**
This is a WIP PR. Will update when ready for review.

### CODE REVIEW

**Comment by dcluna** [comment]
I have a [private layer](https://gist.github.com/e18c56c22e056a3e92e0) for Groovy code, hope it's useful.

**Comment by robbyoconnor** [comment]
Thanks -- right now I'm bogged down with other stuff...

**Comment by robbyoconnor** [comment]
I wanted to add support for grails as well. I was adding it primarily because it's useful but i don't do much groovy/grails coding.

**Comment by robbyoconnor** [comment]
Closing this and will reopen if I have time

**Comment by martinffx** [comment]
I see all the groovy / grails / gradle layers PR's have been closed, does this mean you're not taking any and we should do this via our own private layer?

**Comment by mijoharas** [comment]
Yeah, is anyone interested in adding this? @dcluna, do you want to add what you have as a layer? It seems like most of the basic functionality is there.

**Comment by robbyoconnor** [comment]
I dont do grails development so had no real stake in it

**Comment by mijoharas** [comment]
@robbyoconnor, me neither, just found myself having to edit a groovy file, so wanted a basic layer (I just installed the package for syntax highlighting, it's much nicer when it's spacemacs-ified though :smile: )

**Pull request closed without merging**
