### PR TITLE
colors layer: use nyan-mode from melpa

### PR DESCRIPTION
**Pull request by robbyoconnor**
We no longer need to use a local package for [nyan-mode](https://github.com/TeMPOraL/nyan-mode) now that it is [on melpa](https://melpa.org/#/nyan-mode).

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@syl20bnr @bmag @JAremko

**Comment by syl20bnr** [comment]
Is this in the MELPA repo ?

> -** Fork modifications
 -- the starting nyan cat image has no rainbow behind it,
 -- the starting rainbow image has zigzags,
 -- the animation loop is not endless and occurs only when nyan cat moves.

**Comment by robbyoconnor** [comment]
It is on melpa, yes.

**Comment by robbyoconnor** [comment]
I have been using it...

**Comment by robbyoconnor** [comment]
It is on melpa -- I linked to it :stuck_out_tongue_winking_eye:

**Comment by syl20bnr** [comment]
What I meant in https://github.com/syl20bnr/spacemacs/pull/9689#issuecomment-336713331 was if the `Fork modifications` were available in the MELPA package ?

**Comment by robbyoconnor** [comment]
@syl20bnr could you link me to the fork used so I can look?

**Comment by syl20bnr** [comment]
The original fork is here: https://github.com/syl20bnr/nyan-mode
Only one commit for the Spacemacs diff: https://github.com/syl20bnr/nyan-mode/commit/f3f7656dc8eb6301a9ea22ae8cc0b95bcfa245aa

**Comment by robbyoconnor** [comment]
@syl20bnr why not make a PR upstream with these changes and just use the melpa version?

**Comment by robbyoconnor** [comment]
I'm fine with this sitting until your PR is approved

**Comment by syl20bnr** [comment]
> why not make a PR upstream with these changes and just use the melpa version?

Indeed, I'll see if I can submit some of the modifications upstream.

**Comment by robbyoconnor** [comment]
Let's put this PR on hold until then :slightly_smiling_face:

**Comment by robbyoconnor** [comment]
Going to close this.

**Pull request closed without merging**
