### PR TITLE
Add check that *scratch* buffer exists

### PR DESCRIPTION
**Pull request by rommeswi**
Fix bug that setting the dotspacemacs-scratch-mode can break if no scratch buffer exists.

### CODE REVIEW

**Comment by rommeswi** [comment]
Fix for #15734

**Comment by lebensterben** [comment]
it can be fixed by `get-or-create-buffer`

**Comment by lebensterben** [comment]
I'm not yet sure whether skipping spacemacs-scratch-mode-hook is safe.

**Comment by lebensterben** [comment]
currently this hook seems to be used only here https://github.com/syl20bnr/spacemacs/blob/ba33309327e278a5fe7c12e095ed3a314523484f/layers/%2Bspacemacs/spacemacs-editing/packages.el#L636

If this commit doesn't break persistent scratch then it's okay.

**Comment by rommeswi** [comment]
I tested for whether persistent scratch mode still works.

If one does not kill the scratch buffer on startup, persistent scratch mode works just normally.

Whenever one kills the scratch buffer, it starts next time as an empty buffer. So if one kills the scratch buffer on startup and then opens the scratch buffer manually, it is empty and requires a persistent-scratch-restore.

I think this is expected behavior.

**Comment by sunlin7** [comment]
It's not a Spacemacs bug or Emacs bug. 
It should consider as a local configuration issue, wrong configuration create this issue, should change local configurations to fix the issue.

**Comment by rommeswi** [comment]
I am not sure I understand you correctly. Are you saying that
`dotspacemacs-scratch-mode nil` in `dotspacemacs/init` and
`(kill-buffer "*scratch*")` in `dotspacemacs/user-config`
is the intended way of configuring spacemacs to startup without `*scratch*`?

The fix allows that `(kill-buffer "*scratch*")` in the user configuration has the intended effect on startup. This also works in plain emacs.

**Comment by smile13241324** [comment]
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

**Pull request merged**
