### PR TITLE
Add keybinding for vagrant-reload

### PR DESCRIPTION
**Pull request by kostajh**
I use this fairly often, I imagine others do as well.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
This is missing documentation. Add documentation and then rebase.

**Comment by robbyoconnor** [comment]
@kostajh as a rule of thumb, ***ALWAYS*** document keybindings if you add them -

**Comment by kostajh** [comment]
@robbyoconnor thanks for the heads up, will do. I probably should have looked at the layer README...!

**Comment by robbyoconnor** [comment]
You did it against `develop` at least :)

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

I added the documentation myself.

**Pull request closed without merging**
