### PR TITLE
Changed hotkeys for processes and packages. Fixes #3507.

### LINKED ISSUE #3507: Key binding for list-processes?
Finding `list-processes` (list Emacs' sub-process) useful when running into problems with REPLs , if I need to find exact command line invocation when it was setup automatically, i.e. inferior haskell process in this example, which shows me that the option I've setup to prefer `ghci-ng` over stock `ghc` was not picked up (needs `stack exec ghci-ng`).

Right now we have `ap` for `proced` and `aP` for `paradox-list-packages`. 

Thought we might want to have:

`ap` `list-processes

`aP` `proced

`a\` 'pardox-list-packages   --- '\' or something else

```sh
ispell          run     --              --           aspell -a -m -B --encoding=utf-8
server        listen  --              --           (network server on /var/folders/c0/4fzwf9wx4qvdj10z6c52_s_m0000gn/T/emacs501/server)
demo         run     --              /dev/ttys001 stack ghci --ghc-options=-ferror-spans

```

### PR DESCRIPTION
**Pull request by calebmeyer**
This commit changes:
<leader> a p from proced to list-processes
<leader> a P from paradox-list-packages to proced
and <leader> a \ to paradox-list-packages.

### CODE REVIEW

**Comment by calebmeyer** [comment]
I'm unfamiliar with how to test changes to spacemacs. Do I need to clone my fork to .emacs.d?

**Comment by StreakyCobra** [comment]
Just linking issue/PR: #3507

**Comment by StreakyCobra** [comment]
@calebmeyer This is *one* typical workflow:

1. You fork Spacemacs.
2. You clone your fork of spacemacs to `.emacs.d`
3. You add the original repo as a remote: `git remote add upstream https://…`
4. You never, ever, do modifications on original branches, i.e. `master` and `develop. This allows you to easily get the changes made to the original repository back to your, by simply `git pull --rebase` upstream/develop`. Once pulled from upstream, you can push changes to your fork. All this will keep it up to date with the original one. You can do the same for `master` also.
5. When you want to work on features, you create a new branch by A) getting on develop `git co develop`; and B) create a branch `git checkout -b BRANCHNAME`.
6. Do you modifications on this BRANCHNAME, push it to your fork, go in github and create the pull request.

All this allows you to test your changes by simply running emacs when your `BRANCHNAME` is the active branch, and switching to `develop` to be again on official changes.

**Comment by nixmaniack** [comment]
@StreakyCobra This typical workflow should goto wiki for "Beginners Guide to Contributing to Spacemacs", I think there's video by @travisbhartwell as well for creating a PR for spacemacs which should be linked there.

**Comment by StreakyCobra** [comment]
Yeah, you're probably right, I already had to explain it twice this week :-)

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

I wasn't a huge fan of `\` so I changed it to `k`. Also, you forgot to update documentation: https://github.com/syl20bnr/spacemacs/commit/fa819a663473c079c1b5e0ee7957be1f8d46b373

**Pull request closed without merging**
