### PR TITLE
Update Documentation

### PR DESCRIPTION
**Pull request by Immortalin**
Better documentation.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
`git commit --amend` your commit msg to be more descriptive than "update documentation" -- perhaps, `git commit --amend -m "Update rust auto-completion documentation"` <- Exact command

**Comment by StreakyCobra** [comment]
This message would be more exact: "**Add** rust auto-completion documentation". Then you would also have to force the push.

The corresponding entry in the table of content is also missing. It should be added automagically when you save the file normally.

**Comment by robbyoconnor** [comment]
:point_up_2:  What @StreakyCobra said.

**Comment by StreakyCobra** [comment]
Thank you :+1: I updated your commit message to be more descriptive, and did some minor changes for markups and justification in 3e570d.
Cherry-picked into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
