### PR TITLE
set key "hdb" to describe-bindings

### PR DESCRIPTION
**Pull request by mkcode**
This has been missing for too long. Super useful! :smile:

### CODE REVIEW

**Comment by CestDiego** [comment]
It's on `SPC ?`

**Comment by mkcode** [comment]
@CestDiego - Yup! :smile: thanks to the great `spacemacs||set-helm-key` macro

**Comment by trishume** [comment]
I think he was trying to say that `helm-descbinds` is already bound to "`SPC ?`" (Space followed by typing ?). And in fact it is bound under every subcategory as well (try `SPC f ?`). He wasn't asking a question.

Thus this binding is redundant as there is already a more convenient well known binding for it.

**Comment by CestDiego** [comment]
@trishume though this makes some feedback on the fact that this keybinding might not be obvious to new users...perhaps a quickhelp button on the homepage would be like.. (Keybindings are a `SPC ?` away) or sth might be of good use? @syl20bnr

**Comment by mkcode** [comment]
@trishume, @CestDiego - Whoops! haha - funny misinterpretation. Yeah, I wasn't aware of this binding. I saw in gitter a few times that people were recommending running describe-bindings command, so spacers may not be very aware of it.

**Comment by syl20bnr** [comment]
We can add `hdb` to complete the mapping of the descibe functions under `SPC h d`.
For the `SPC ?` case, well, hum... https://github.com/syl20bnr/spacemacs#key-bindings-discovery :-)

**Comment by syl20bnr** [comment]
I was not aware for `SPC f ?` working, that's great, should be added to documentation.

**Comment by CestDiego** [comment]
@syl20bnr the thing is that most people don't really read the whole doc. Maybe as a first thing we should put it in the homepage ? spacemacs-buffer too :P

**Comment by syl20bnr** [comment]
@CestDiego It can be put in the quick help toggle.

@mkcode Thank you !
Cherry-picked into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
