### PR TITLE
EditorConfig: Set evil-shift-width in a buffer to match indent

### PR DESCRIPTION
**Pull request by jupl**

### CODE REVIEW

**Comment by trishume** [comment]
It would be awesome if this also set all the million variables for specific modes. I am constantly annoyed when I think I have set all my modes to 2 space (except python) and then *bam*, JSON mode insists on 4 spaces.

See my collection of variables set to 2:
https://github.com/trishume/dotfiles/blob/master/emacs%2B/spacemacs.symlink#L131

**Comment by jupl** [comment]
I was originally going to doit but the editorconfig package has a few declared.

https://github.com/editorconfig/editorconfig-emacs/blob/master/editorconfig.el#L68

**Comment by trishume** [comment]
Oooooh cool! :sunglasses: 

Will definitely use and recommend this then!

**Comment by jupl** [comment]
Now that I think about it I opened an issue on Editorconfig instead. Assuming they add it I'll close this.

**Pull request closed without merging**
