### PR TITLE
Add inverted Dogemacs banner for dark themes

### PR DESCRIPTION
**Pull request by vfinotti**
Hi,

Given that the current dogemacs banner doesn't look well in dark themes where the font is usually white (such as the default Spacemacs theme), I have create a negative version of the Dogemacs banner which looks nicer in darker themes.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
In addition to this -- why not do something like the following: 

```patch
diff --git a/core/core-spacemacs-buffer.el b/core/core-spacemacs-buffer.el
index d03c93aa5..14506f58b 100644
--- a/core/core-spacemacs-buffer.el
+++ b/core/core-spacemacs-buffer.el
@@ -160,6 +160,8 @@ Cate special text banner can de reachable via `998', `cat' o
            (spacemacs-buffer//choose-random-text-banner))
           ((eq 'random* dotspacemacs-startup-banner)
            (spacemacs-buffer//choose-random-text-banner t))
+          ((eq 'doge-inverted dotspacemacs-startup-banner)
+           (spacemacs-buffer//get-banner-path 997))
           ((eq 'doge dotspacemacs-startup-banner)
            (spacemacs-buffer//get-banner-path 999))
           ((eq 'cat dotspacemacs-startup-banner)
```

**Comment by robbyoconnor** [comment]
Please also consider the patch two comments up, I'm currently using it :)

**Comment by robbyoconnor** [comment]
@vfinotti https://github.com/vfinotti/spacemacs/pull/1

if you merge this into your fork -- it should contain the changes in the above patch and update this PR -- be sure to rebase and not merge -- it makes history a bit weird with merge commits in PRs.

**Comment by vfinotti** [comment]
@robbyoconnor, thanks for the suggestion, I really appreciate it! I have included it in the PR. I'm still getting familiar with the contribution guidelines: should I include you in the entry at ```CHANGELOG.develop```?

**Comment by robbyoconnor** [comment]
totally up to you.

**Comment by duianto** [comment]
Thank you for contributing to Spacemacs!
The PR has been cherry-picked into the `develop` branch, you can safely delete your branch.
Commit: https://github.com/syl20bnr/spacemacs/commit/ac17032009655383d0aff977730ced096be78fd8

**Pull request closed without merging**
