### PR TITLE
Fetch info+ via quelpa wiki recipe

### PR DESCRIPTION
**Pull request by dalanicolai**
Fixes #14525 and 8bcc42059b9990a383aef440d48a20cc6a08f07a.

[See list of Quelpa supported fetchers](https://github.com/quelpa/quelpa#overview)

### CODE REVIEW

**Comment by lebensterben** [comment]
is this PR complete? Looks like missing packages.el

**Comment by dalanicolai** [comment]
My god, committed the wrong file...

**Comment by dalanicolai** [comment]
Fixed

**Review by smile13241324 — APPROVED** [review]
Hi @dalanicolai,

This looks good, the initial tests runs pretty well.

Mfg
Maxi

**Comment by lebensterben** [comment]
There's a bug report about undefined symbol https://github.com/syl20bnr/spacemacs/issues/15010#issuecomment-904427195

It's strange that `quelpa` correctly downloads `info+`, and the once it downloaded is identical from the one we removed in this PR.

Please take a look.

**Pull request merged**
