### PR TITLE
Fix layer anatomy documentation

### PR DESCRIPTION
**Pull request by darkfeline**
Fix documentation per https://github.com/syl20bnr/spacemacs/issues/4980

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Looks good to me :+1:

**Comment by syl20bnr** [comment]
This is not right, see my answer in #4980 ;-)

**Comment by darkfeline** [comment]
Closing then, I'll point out that the plantuml layer needs fixing.

**Comment by robbyoconnor** [comment]
Why does it need fixing?

**Pull request closed without merging**
