### PR TITLE
Add majapahit-theme

### PR DESCRIPTION
**Pull request by kostajh**
This is a nice theme with light & dark versions.

### CODE REVIEW

**Comment by cpaulik** [comment]
You will also have to add the lookup from the theme name to the package to core theme support.

See [here](https://github.com/syl20bnr/spacemacs/blob/ef5a2ad5ee6362588244374364fe4ac2df066f37/core/core-themes-support.el#L116-L117) for an example

**Comment by kostajh** [comment]
@cpaulik thanks! I had looked at another PR adding support for a theme, and didn't see that. I'll do that and resubmit.

**Comment by cpaulik** [comment]
It depends on the theme. If the theme name is the same as the package name on MELPA then it works out of the box. This step is necessary if multiple variants like a dark and a light theme are in one MELPA package.

**Comment by kostajh** [comment]
That makes sense, thanks for explaining!


On Fri, Feb 12, 2016, at 10:24 AM, Christoph Paulik wrote:
> It depends on the theme. If the theme name is the same as the package
> name on MELPA then it works out of the box. This step is necessary if
> multiple variants like a dark and a light theme are in one MELPA
> package.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/syl20bnr/spacemacs/pull/5045#issuecomment-183372199

**Comment by kostajh** [comment]
OK, reworked & this works fine locally. Thanks again @cpaulik

**Comment by syl20bnr** [comment]
Thank you :+1: 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
