### PR TITLE
[core] Add :timeout/:idle for spacemacs|define-transient-state

### PR DESCRIPTION
**Pull request by chenyanming**
This adds a :timeout keyword for spacemacs|define-transient-state, it
make use of :timeout keyword defhydra according to
https://github.com/abo-abo/hydra/wiki/internals.

"The :timeout key starts a timer for the corresponding amount of seconds that disables the hydra. Calling any head will refresh the timer."

### CODE REVIEW

**Comment by lebensterben** [comment]
What's the use case for timeout?

**Comment by chenyanming** [comment]
By using timeout, I can made a self transient states that can automatically quit after the timeout without pressing q/C-g.

**Comment by chenyanming** [comment]
There are another keyword :idle, if should be better to add as well. It can hide the transient state if the commands complete before the idle timeout.

**Comment by lebensterben** [comment]
Do you have a concrete use case?

**Review by smile13241324 — CHANGES_REQUESTED** [review]
While I understand the need for more flexibility in declaring transient states, especially in private layers, your implementation is not complete. Up to now you have just added the new parameter to the description and the let expression however the value is never forwarded to `defhydra` thus it has no effect. Please adjust your impl so that the new values are actually passed to the respective macro.

Btw: feel free to also add the `idle` parameter if you need it for your private layer.

**Comment by lebensterben** [comment]
@smile13241324 
If we decide to allow more flexibility, it's better to redefine this macro by `cl-defmacro` with `&rest props &key :foo :bar &allow-other-keys`.

After we dealt with keyword arguments we explicitly support, we just need to simply forward `props` to `defhydra`, which contains all other keyword arguments.

**Comment by chenyanming** [comment]
Usecase: tabs transient state.
```
  (defvar spacemacs--tabs-ts-full-hint-toggle nil
    "Display window transient state documentation.")

  (defun spacemacs//tabs-ts-toggle-hint ()
    "Toggle the full hint docstring for the window transient state."
    (interactive)
    (setq spacemacs--tabs-ts-full-hint-toggle
          (not spacemacs--tabs-ts-full-hint-toggle)))

  (defun spacemacs//tabs-ts-hint ()
    "Return a condensed/full hint for the window transient state"
    (concat
     " "
     (if spacemacs--tabs-ts-full-hint-toggle
         spacemacs--tabs-ts-full-hint
       (concat "[" (propertize "?" 'face 'hydra-face-red) "] help"
               spacemacs--tabs-ts-minified-hint))))


    (spacemacs|transient-state-format-hint tabs
      spacemacs--tabs-ts-minified-hint "\n
  Fast Move: _h_ _l_ _n_ _p_ _b_ _0_.._9_ Tab: _C-a_ _C-e_ _t_/_T_ _C-h_ _C-l_ Search: _b_ _g_ Misc: _C-l_ _C-S-k_ _q_"
      )

    (spacemacs|transient-state-format-hint tabs
      spacemacs--tabs-ts-full-hint
      "\n[_?_] toggle help
 ^^^^Fast Move             ^^^^Tab                    ^^Search            ^^Misc
-^^^^--------------------+-^^^^---------------------+-^^----------------+-^^---------------------------
   ^_p_^   prev group    | _C-a_^^     select first | _b_ search buffer | _C-k_^^    kill buffer
 _h_   _l_  switch tab   | _C-e_^^     select last  | _g_ search group  | _C-S-k_^^  kill others in group
   ^_n_^   next group    | _t_/_T_^^   switch tab   | ^^                | _q_^^      quit
 ^^0 ~ 9^^ select window | _C-h_/_C-l_ move current | ^^                | ^^
-^^^^--------------------+-^^^^---------------------+-^^----------------+-^^---------------------------

")


(spacemacs|define-transient-state tabs
      :title "Tabs Transient State"
      :hint-is-doc t
      :dynamic-hint (spacemacs//tabs-ts-hint)
      :idle 3.0
      :timeout 6.0
      :foreign-keys nil
      :bindings
      ("?" spacemacs//tabs-ts-toggle-hint)
      ("h" centaur-tabs-backward :idle 3.0)
      ("n" centaur-tabs-forward-group :idle 3.0)
      ("p" centaur-tabs-backward-group :idle 3.0)
      ("l" centaur-tabs-forward :idle 3.0)
      ("t" centaur-tabs-forward)
      ("T" centaur-tabs-backward)
      ("C-a" centaur-tabs-select-beg-tab)
      ("C-e" centaur-tabs-select-end-tab)
      ("C-j" awesome-tab-ace-jump)
      ("C-h" centaur-tabs-move-current-tab-to-left)
      ("C-l" centaur-tabs-move-current-tab-to-right)
      ("b" ivy-switch-buffer)
      ("g" centaur-tabs-counsel-switch-group :exit t)
      ("C-k" kill-current-buffer)
      ("C-S-k" centaur-tabs-kill-other-buffers-in-current-group)
      ("q" nil "quit")
      ("escape" nil "quit")
      ("C-g" nil "quit"))

    (spacemacs/set-leader-keys "b." 'spacemacs/tabs-transient-state/body)
    (spacemacs/set-leader-keys "bh" 'spacemacs/tabs-transient-state/centaur-tabs-backward)
    (spacemacs/set-leader-keys "bl" 'spacemacs/tabs-transient-state/centaur-tabs-forward)
    (spacemacs/set-leader-keys "bn" 'spacemacs/tabs-transient-state/centaur-tabs-forward-group)
    (spacemacs/set-leader-keys "bp" 'spacemacs/tabs-transient-state/centaur-tabs-backward-group)
    (spacemacs/set-leader-keys "bg" 'centaur-tabs-counsel-switch-group)



```

**Review by smile13241324 — APPROVED** [review]
I think this is ok for now, we can still redefine this macro with `cl-defhydra` if there are more parameters needed or we find the time to do so.

**Comment by smile13241324** [comment]
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

**Pull request merged**
