### PR TITLE
Org babel keys

### PR DESCRIPTION
**Pull request by timor**
Added org-babel-* commands under sub-keymap "m v", along with a transient state that allows for easy source block navigation

### CODE REVIEW

**Comment by timor** [comment]
I created the transient state mainly for ease of navigating src blocks, if there are any other repetitive actions for these, they can easily be added.

**Comment by dvzubarev** [comment]
Why don't you use `m b` as a prefix? I think it is more mnemonic than `m v`.

**Comment by Somelauw** [comment]
Probably based on the C-c C-v prefix used by Emacs org-mode.

**Comment by joehillen** [comment]
A transient state for org-babel!? Yes please! 💯

**Comment by timor** [comment]
Yes, I chose `m v`  because of the C-C C-v bindings. `m b` is also a good choice, how to decide? I suspect there are may more org bindings that have not been made available yet?

**Comment by timor** [comment]
also, `m b` is already taken for `org-tree-to-indirect-buffer`

**Comment by syl20bnr** [comment]
+1 for `SPC m b` prefix which fits nicely with `block` and `babel`.
`SPC m b` is now free, it may have been used before but after the reorganization of key bindings `org-tree-to-indirect-buffer` is now on `SPC m s b`.

**Comment by timor** [comment]
Ok `m b` it is, then.  Which section of the Readme should be updated?

**Comment by syl20bnr** [comment]
Thank you ! 💜 
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by syl20bnr** [comment]
@timor would be wonderful to add the key bindings in the README.org: https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bemacs/org/README.org 👼

**Pull request closed without merging**
