### PR TITLE
Frame manipulation commands

### PR DESCRIPTION
**Pull request by oppenlander**
Added commands for creating and switching around frames.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1: <3 <3 <3 <3 <3

**Comment by syl20bnr** [comment]
That's great :+1: 
Can you try to make it work with helm ?

**Comment by oppenlander** [comment]
@syl20bnr I'll look in to this. 
It will probably involve creating a functions utilizing `completing-read`, which should automatically select between `ido` and `helm`.

**Comment by Devagamster** [comment]
I have also found frame-move to be greatly helpful. It makes it so that the window move commands move between frames if an error is thrown. This is brilliant for multi monitor setups because you don't have to use a separate command to switch between frames; you can just use the same evil-window-up etc.

Use this if you want to add this functionality. Seems to work very well on my machine but should be tested on macs/different versions.
``` elisp
(use-package framemove
  :init
  (setq framemove-hook-into-windmove t)))
```

**Comment by oppenlander** [comment]
@Devagamster I don't like it hooking in to windmove, but I do like the idea of including `framemove.el` for `SPC F [hjkl]`. 
Maybe compound this with documenting that `(setq framemove-hook-into-windmove t)` is available?

**Comment by Devagamster** [comment]
Sounds perfect :smile:

**Comment by StreakyCobra** [comment]
@oppenlander Can you rebase your work on `develop` ? :-)

**Comment by oppenlander** [comment]
@StreakyCobra Sorry for the late reply.
I'm in the middle of a move, and don't have much time to work on this, but will get back to it when I can.

There is a bit more work to be done on this.
Right now IDO and Helm override certain built in functions, so we need to specially handle some of the manipulation commands.

**Comment by shobute** [comment]
Sorry for bumping an extremely old MR, but I'd love to see this functionality. Just wondering what additional work would be needed to get this in? I'd be happy to pick it up.

**Comment by robbyoconnor** [comment]
Hey @shobute, 

1) Conflicts would need to be resolved. 
2) I'm not sure if @oppenlander was done yet...

**Comment by oppenlander** [comment]
Go ahead and use the PR by @shobute
I never found the time to add the Helm/windmove commands.

**Comment by TheBB** [comment]
Closing in favour of https://github.com/syl20bnr/spacemacs/pull/8302

**Pull request closed without merging**
