### PR TITLE
Add recommended brew method to install emacs

### PR DESCRIPTION
**Pull request by athersharif**
Seems like `brew linkapps emacs-plus` doesn't work anymore. This PR updates the README with the updated recommended method from brew in order to install emacs.

### CODE REVIEW

**Comment by fiveNinePlusR** [comment]
this needs to be rebased on develop. there are way too many commits here. 

as to your commit... why is this cask now the suggested way? i think emacs-mac is a better formula all around as it lets you install with a bunch of different versions and options.

**Comment by fiveNinePlusR** [comment]
I think the wiki is out of date. the better way to install the gui emacs for cocoa is through `emacs-mac` from homebrew proper instead of the binary blobs that have fewer options.

**Comment by syl20bnr** [comment]
But `emacs-plus` is still the superior/more comprehensive way to install
Emacs from `brew` no ? Or this is not the case anymore ?

No sure we should confuse people with another brew way to install Emacs
just because `brew linkapps emacs-plus` does not work anymore. Can we
just remove `brew linkapps emacs-plus` from the snippet and tell people
how to replace it or does it work only with `brew cask install emacs` ?

**Comment by athersharif** [comment]
@fiveNinePlusR @syl20bnr i'm fine either way but here are my two cents:

i think what makes spacemacs so awesome is that it's a one stop shop and has the documentation to start a newbie from start to finish. imo, removing the linkapps with something else would make things a little bit complex. how would you guys think about just linking to https://www.emacswiki.org/emacs/EmacsForMacOS#toc12 for emacs installation so users can pick whatever they're comfortable with, and may be adding your preferred choice from that list?

thoughts?

**Comment by athersharif** [comment]
@syl20bnr updated the PR. let me know if you guys want me to change it more. :)

**Comment by fiveNinePlusR** [comment]
looks good to me. I think the best one is the emacs-mac tap, but that's a tap and is (very) slightly more complex to install from homebrew. (one extra step). Linking to that page at that part gives the user all the info they really need.

**Comment by htc502** [comment]
As a user, I think this edition is not good enough. It makes me more confused:
1. I am redirected to another 'long list' (probably longer than spacemacs readme.) which I think is not quite user friendly.  
2. That wikipage also uses   'brew linkapps emacs' to 'finally link it to your Applications folder'. As I've tested, brew linkapps is already deprecated. This is the problem that the RP want to deal with. 

If you guys think emacs-mac is a good way to go, probably you can link the user to that specific part or just copy that part over here. 
To me, the following command saved me for linking the app to Application:
'ln -s /usr/local/Cellar/emacs/24.5/Emacs.app /Applications'
Not sure we can do this in readme or not.
Hope this is helpful. Thank you.

**Comment by athersharif** [comment]
@htc502 i can totally see the confusion there. and you're right, this might be too big a documentation to link to and the wiki not supporting navigation by id doesn't help either. before we had the conversation above, i was initially in the favor of the following:

```
Cask homebrew installation
Homebrew now recommends to use the cask version with the following message: “Please try the Cask for a better-supported Cocoa version”

To install the cask version:

brew cask install emacs
This installs a pre-built package from https://emacsformacosx.com/
```

also, the symlink you posted above is for `24.5`. this version would have to be kept like `[version]` or something similar if we were to add this to the readme, imo.

@fiveNinePlusR @syl20bnr - thoughts? are we inclining towards `emacs-plus` or `emacs-mac`?

**Comment by athersharif** [comment]
@fiveNinePlusR thanks for the great suggestion. really like it :).

i've updated the PR. thoughts?

**Comment by fiveNinePlusR** [comment]
looks good to me. might want to downcase the ln statement though.

**Comment by athersharif** [comment]
ah, sorry about that. updated.

**Comment by syl20bnr** [comment]
What are the advantages of cask over the `emacs-plus` tap ?

I have the feeling that `emacs-plus` is more complete than cask.

See the `emacs-plus` readme here: https://github.com/d12frosted/homebrew-emacs-plus

I was more for keeping `emacs-plus` in the README and just add a
reference to emacsformacosx

For `emacs-mac` it was the promoted way to install Emacs but starting
with Emacs 25 we had lots of report of performance issues with it.

cc @d12frosted

**Comment by athersharif** [comment]
@syl20bnr - added the emacs-plus instructions in there as well. also, probably should keep an eye on https://github.com/d12frosted/homebrew-emacs-plus/issues/41#issuecomment-311361453 and update the readme when this change is made in the future.

**Comment by athersharif** [comment]
also, @syl20bnr @fiveNinePlusR - any idea why the Emacs24 build is failing?

**Comment by syl20bnr** [comment]
What's the error ?

Also develop branch support Emacs 25+ only.

**Comment by syl20bnr** [comment]
Nice work 👍 
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by aaronjensen** [comment]
Until 26.1 is released (which should be soon) this change will encourage people to install 25.3 which lacks the vfork patch which means significantly slower magit. It's too bad, but hopefully 26.1 will be out soon.

**Comment by dijonkitchen** [comment]
When is the `develop` branch going to be merged into `master` for these new Readme changes? It's pretty confusing for a new user unless you've looked across a few issues.

**Comment by tkothe** [comment]
Just checking whether this will be merged to `master` soon as I also just came across the issue of the lack of the `brew linkapps` command. Cheers!

**Comment by cjoshmartin** [comment]
Brew suggested that I should run `brew link emacs-plus` and it work it!

**Pull request merged**
