### PR TITLE
add keybinding for write-file

### PR DESCRIPTION
**Pull request by cpaulik**
- allows for saving a file under a different name
- could reasonably also be bound to C for copy but
  this would be unlogical for new files

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1: :shipit:

**Comment by syl20bnr** [comment]
I'm OK to bind this command but I'm worried because the mnemonic way to bind `SPC f s` and `SPC f w` is somewhat the opposite as what we get now.
New people won't know the historical reason behind `SPC s w` = `save as` and `SPC f s` = `write`.

So I would prefer `SPC f C-s` exceptionally for `save as`

**Comment by cpaulik** [comment]
I'm fine with binding it to `SPC f C-s` but I think there might be a better solution:

- bind `SPC f s` to a custom command that asks for the filename if the buffer is not visiting a file. Basically instead of showing the message `user-error: Please specify a file name for the buffer` call `write-file`
- Also bind `write-file` to `SPC f C` for copy.

What do you think?

**Comment by syl20bnr** [comment]
Excellent :+1:

**Comment by cpaulik** [comment]
So i've made the changes. For some reason I had to write a function calling `write-file` interactively. Otherwise `ido` was used instead of `helm`

**Comment by robbyoconnor** [comment]
:+1:

**Comment by syl20bnr** [comment]
Cool ! The wrapper for `write-file` make sense to have a better naming for what we use the function (an alias would have been possible but maybe the helm thing would not work).

Since ` SPC f c`  is not used I moved the binding to it. If some people complain then we may put it back on `C`.
 
Thank you :+1: 

Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
