### PR TITLE
Fix RoR and Django layer naming

### LINKED ISSUE #2245: ruby-on-rails layer doesn't include haml-mode
Probably because it's got ruby-packages got redefined.
https://github.com/syl20bnr/spacemacs/blob/develop/contrib/!lang/ruby/packages.el#L13
https://github.com/syl20bnr/spacemacs/blob/develop/contrib/!frameworks/ruby-on-rails/packages.el#L13

### PR DESCRIPTION
**Pull request by TheBB**
Fixes #2245. ~~This should probably go in 103.3?~~ For some reason I thought this was in master.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
It's in the html layer. See comment in #2245

**Comment by robbyoconnor** [comment]
:+1:

**Comment by TheBB** [comment]
@syl20bnr I think this should be high pri. It's in master and broken.

**Comment by Eilie** [comment]
Why it still hasn't been merged? This is huge. Why didn't you create Spacemacs organization with +1 person merging PRs without having @syl20bnr as single point of failure(no offense) - we have 90 open PRs by now and it's clear that @syl20bnr just can't cut it alone. @syl20bnr Dude, create organization now and add trust people there!

**Comment by robbyoconnor** [comment]
Probably because @syl20bnr has a day job ;)

**Comment by syl20bnr** [comment]
Spacemacs should not grow too fast because it is not yet 1.0 ready, so for now it is a good thing that I'm the bottleneck.
@Eilie This is the develop branch so you should expect that things can break, when a PR is available you don't have to wait for me to merge it upstream, you can merge it temporarily in your local repo.
But I agree that this PR should have been merged sooner and I believe that I saw it two days ago but I don't know why I did not merge it, this is a mistake on my part.

Anyway, thank you @TheBB for the fix :+1: 
Cherry-picked in develop branch, you can safely delete your branch.

**Pull request closed without merging**
