### PR TITLE
Rspec mode in ruby layer

### PR DESCRIPTION
**Pull request by alexgirdler**
Addresses #2128

### CODE REVIEW

**Comment by alexgirdler** [comment]
I removed `ruby-test-mode` in favour of `rspec-mode` replacing existing keybinds with `rspec-mode` keybinds. Also note I just switched after using vim for 6 years this week so my knowledge of elisp is mediocre at best.

**Comment by StreakyCobra** [comment]
Thx for the contribution :-)

Note: it's "kind-of" duplicate of #3067

**Comment by alexgirdler** [comment]
I noticed that PR but saw that it didn't provide much documentation and just added the commands instead of replacing them.

**Comment by robbyoconnor** [comment]
This is also against `master`  -- so please close this and make it against `develop` since #3067 exists

**Pull request closed without merging**
