### PR TITLE
Don't use ido for sudo-edit of new files

### PR DESCRIPTION
**Pull request by cpaulik**
We should use the default here since this is then adviced by either helm or ido AFAIK.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Why not (jus curious):

**Comment by cpaulik** [comment]
Because invoking ido directly means we can not use helm. Also if we use the default `read-file-name` it could be adviced by any completion framework other than helm or ido if a user wishes to use a different one.

The real reason is that ido did not let me create a new file in sudo mode.

**Comment by robbyoconnor** [comment]
Just curious -- :heart:

**Comment by StreakyCobra** [comment]
It makes sense to not force `ido` in this particular case.

**Comment by TheBB** [comment]
We don't even have a binding for this function. As far as I can tell it's just defined and left to rot. I'm unsure what this fixes.

**Comment by StreakyCobra** [comment]
I have one :smiley:

**Comment by cpaulik** [comment]
I call this function when I need it and it uses ido instead of helm. This sets it to use the default file finder

**Comment by TheBB** [comment]
Just saying... we should have a binding for it. You can add one to this PR as far as I'm concerned.

**Comment by TheBB** [comment]
@StreakyCobra suggested calling this from `SPC f f` with a prefix argument.

Anyway I'm all :+1: for this PR as it is.

**Comment by StreakyCobra** [comment]
I just checked it's already used :-(

**Comment by cpaulik** [comment]
No Spc f f should not sudo edit. I'm on my mobile now but can look for a binding later

**Comment by StreakyCobra** [comment]
:+1: In `SPC f`,  `s`, `S`, `r` and `R` (for "sudo" and "root") are already taken, but we can imagine `p` for "privileged", or… as you wish :relaxed:.

**Comment by TheBB** [comment]
Or

- `A`: admin
- `E`: elevated

**Comment by syl20bnr** [comment]
I like `SPC f E`.

**Comment by cpaulik** [comment]
I've bound it to `SPC f E`.

**Comment by TheBB** [comment]
Thank you! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
