### PR TITLE
Highlight TODO keywords in all prog modes

### PR DESCRIPTION
**Pull request by TheBB**
Not just Python.

### CODE REVIEW

**Comment by calebmeyer** [comment]
+1

**Comment by TheBB** [comment]
I also made the colon optional.

**Comment by joehillen** [comment]
:+1:

**Comment by ralesi** [comment]
Will this work in comments or anywhere?

**Comment by TheBB** [comment]
It works anywhere, but we can perhaps use [fic-mode](https://github.com/lewang/fic-mode/blob/master/fic-mode.el) to make it more robust, if there's interest.

**Comment by ralesi** [comment]
I say fic-mode and define the same words we check here in the :init,  that way we only highlight in comments.  Or do people want highlighting everywhere?

**Comment by syl20bnr** [comment]
We can move to fic-mode if it brings a better support for this kind of stuff.
For now this fix is merged, thank you :+1: 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
