### PR TITLE
[pocket] Add pocket layer

### PR DESCRIPTION
**Pull request by bcc32**
Add a layer for[ pocket-reader.el](https://github.com/alphapapa/pocket-reader.el/), an Emacs client for the [Pocket](https://getpocket.com/) reading list service.

I wasn't sure whether this would be classified under "readers" or "web services", so I picked one arbitrarily.  Happy to change.

### CODE REVIEW

**Comment by lebensterben** [comment]
what's the license of the IMG file?

**Comment by bcc32** [comment]
Hmm, that's a good question.  I downloaded this one off the internet somewhere but there's an official press kit here: https://blog.getpocket.com/press/ that seems more appropriate to use.  That being said, I downloaded that zip file and didn't see a license file (although, clearly, there is *some* license granted to use it).

Is there a good place to record the license information somewhere?  Perhaps just the README file?

**Comment by lebensterben** [comment]
There's no convention for recording license information of non-code files currently.

Since there's no license, it's better not to use it.

**Comment by bcc32** [comment]
That seems reasonable, but there are plenty of other logos (`+web-services/twitter/img/twitter.png`, `+chat/slack/img/slack.png`, `+lang/go/img/go.png`) used without apparent license.  I searched through the commit history and found that logo images are never attributed or really mentioned.

We should probably add license files/attribution for all of the logos in a separate change.

**Comment by lebensterben** [comment]
good idea

**Comment by smile13241324** [comment]
Manually merged into develop, thank you for contributing to Spacemacs.
About the pictures lets do that in a separate PR.

**Pull request closed without merging**
