### PR TITLE
Add adaptive-wrap.

### PR DESCRIPTION
**Pull request by person808**
Equivalent of vim's `breakindent` option.

### CODE REVIEW

**Comment by syl20bnr** [comment]
Can you provide some screenshots to compare ?

**Comment by person808** [comment]
Without adaptive-wrap:

screenshot from 2015-04-01 19-01-34

With adaptive-wrap:
screenshot from 2015-04-01 19-02-31

**Comment by tuhdo** [comment]
I think it's redundant with `aggressive-indent` (which actually indents your code according to indentation rule, not just wrapping your text). If you want your Lisp code always indented, don't hesitate to add:

```elisp
(add-hook 'emacs-lisp-mode-hook #'aggressive-indent-mode)
```
It will vastly improve your Lisp coding experience, as you will never have to worry about indentation again. Also, enable `smartparens-strict-mode` to never accidentally delete a parenthesis. 

You should check the homepage for demos: https://github.com/Malabarba/aggressive-indent-mode

**Comment by person808** [comment]
@tuhdo I think you misunderstand what adaptive-wrap does. Adaptive-wrap is not for indenting code. It does not change the contents of the file, it only makes wrapped lines visually match the indentation of the line above.

**Comment by tuhdo** [comment]
I see. Since `visual-line-mode` is not enabled by default, having this is fine by me.

**Comment by trishume** [comment]
:+1: :+1: :+1: YES!

It has always annoyed me when lines wrap and start again at the beginning but it is impractical for me to wrap them manually. I've always wanted this functionality, I guess I should have checked to see if there was a package for it :P

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
Cherry-picked into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
