### PR TITLE
Basic support for hexl (a hex editor)

### PR DESCRIPTION
**Pull request by TheBB**

### CODE REVIEW

**Comment by StreakyCobra** [comment]
:+1:

**Comment by robbyoconnor** [comment]
Isn't hexl-mode built-in?

**Comment by robbyoconnor** [comment]
Isn't hexl-mode built-in?  I was gonna say this, but [nevermind](http://www.emacswiki.org/emacs-test/HexlMode).

**Comment by tuhdo** [comment]
You can open a file in `hexl` mode with `SPC f f` by pressing `f12`, or switch to action menu and type `hex`.

**Comment by robbyoconnor** [comment]
This seems to add more @tuhdo

**Comment by TheBB** [comment]
Thanks, I forgot the `:location built-in`.

**Comment by syl20bnr** [comment]
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
