### PR TITLE
Define a convention for message modes

### PR DESCRIPTION
**Pull request by StreakyCobra**
Following discussion on #4070

### CODE REVIEW

**Comment by justbur** [comment]
C-k is an emacs mnemonic which is fine for me, but this should probably pick something that vim users are familiar with.

**Comment by darkfeline** [comment]
@justbur I don't believe Vim has anything similar to this.

**Comment by StreakyCobra** [comment]
@darkfeline Thanks, updated.

We have three choices:

- We stay close to emacs and use `c` and `k`
- We give them a meaning, like `a` for `abort` and `v` for validate (or anything else)
- We do both, `c` and `k` for emacs users and additional one for the mnemonic.

**Comment by justbur** [comment]
Well there's :q! in vim and ESC but that doesn't seem right. Also x and d
which are analogous to C-k which doesn't really mean abort. I think given
that q is used throughout spacemacs ,q is probably the most natural. But
multiple options is great too.

,, is not mnemonic but it's super convenient and fits with the idea of C-c
C-c well.

**Comment by StreakyCobra** [comment]
I didn't mentioned it, but I'm :+1:  for adding `,,`, I like it.

`,q` doesn't imply a notion of `abort` or `cancel`, just `quit`. I prefer `,k` or `,a`, I find them more explicit.

**Comment by justbur** [comment]
I like the notion of abort best with ,a I think. That conveys the right
idea to me.

**Comment by StreakyCobra** [comment]
so `,,` and `,c` for the validation (`commit`) and `,a` and `,k` for the discard (`abort`, `kill`)?

**Comment by syl20bnr** [comment]
`,a` is not needed, I'm fine with `,,`. `,c` and `,k`.

**Comment by justbur** [comment]
`,,` is going to interfere with toggling lisp state btw

**Comment by syl20bnr** [comment]
I' fine with it, could be SPC k . to toggle the state

**Comment by StreakyCobra** [comment]
Do we need messages editing binding in lisp mode?

**Comment by justbur** [comment]
> Do we need messages editing binding in lisp mode?

I guess that's right, because `,,` only toggles in a lisp mode, so there won't be a conflict. Sorry

**Comment by justbur** [comment]
I was thinking that lisp state is bound globally, but the mode specific bindings are not global

**Comment by syl20bnr** [comment]
Excellent :+1: 
Finally I added the suggestion of @justbur for `, a`.
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
