### PR TITLE
Spacemacs Layouts Improvements [WIP]

### LINKED ISSUE #4579: spacemacs-layouts: Suppress warning, remove duplicate keys for layouts, leave micro state
Hi.

First, thanks for this great package.

Here are some suggestions:

1) Suppress warning
It think it would be better to have this warning in `*Messages*` instead of opening a new window.
I replaced it intentionally, after all.

screenshot 2016-01-12 18 34 14

2) Remove duplicate keys
So I redefined `e`. However, the builtin still shows up:
screenshot 2016-01-12 18 39 25

3) Leave micro state
It's not hard to notice that my workflow  heavily uses layouts.
One thing that bothers me a bit is that after using `SPC l o` the micro state is still active. So if I type `SPC l o e` and then `gg` to go to the beginning of the buffer, it will open the layout assigned to `g` instead. 
Of course, this is just a problem because I use a lot of layouts, but I think it's sensible to leave the micro state after choosing one, because generally we change precisely to do something.
So any change to either change the default or create an option that allows changing this behaviour?

4) Open layouts automatically on startup
How can I programatically open some layouts at startup?
I would like to execute
```
spacemacs//custom-layouts-spacemacs/custom-perspective-@Org-o
```

However, this command is not created by the macro until (I guess) I use `SPC l o`.
How do I get Spacemacs to generate all those functions?

Thanks again for the great package.

### LINKED ISSUE #4590: Updates on layouts UX
After using it for the last months and given some feeback of the community here are the updates I want to make to the layout UX, some of them were in the original design of @CestDiego:

_The main goal of the UX is to be able to make layouts transparents for people not using them, even if they are always available and activated under the hood, so we want a seamless experience for both kind of users (layouts users and no-layout users)_

- `SPC b b`, `SPC TAB`, `SPC b n` and `SPC b p` are restricted to the current layout
- New key bindings `SPC b a` and `SPC b r` to add/remove buffers to current layout
- `SPC b a` list all the opened buffers, `SPC b r` list only the buffers of the current layout
- New key binding `SPC f a` synonym to `SPC f f` to be symmetric with `SPC b a`.
- New key binding `SPC B b` `SPC B n` and `SPC B p` corresponding to the lower case bindings but they don't add buffers to the current layout, and _ideally they also switch to the first layout where the buffer belongs_. The latter part is important to be able to get a more WM like UX, this is also a powerful way to combo buffer switch and layout switch in one command.
- The helm/ivy sources should display the layouts for each buffer.

Users not using layouts will always be in the default layouts which has a global scope, so all restricted key bindings act like they're expected to.

### PR DESCRIPTION
**Pull request by CestDiego**
Fix #4579
This fixes:
1. Repeated bindings
2. Leave micro-state when `SPC l <number>` 
3. nope
4. Exit micro-state after opening custom-layout

-----
Fix #4590 
1. SPC b b, SPC TAB, SPC b n and SPC b p are restricted to the current layout
2. New key bindings SPC b a and SPC b r to add/remove buffers to current layout

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1:

**Comment by CestDiego** [comment]
@syl20bnr I had trouble making `spacemacs/alternate-buffer` because the
implementation is as follows,

```elisp
(defun spacemacs/alternate-buffer ()
  "Switch back and forth between current and last buffer in the
current window."
  (interactive)
  (if (evil-alternate-buffer)
      (switch-to-buffer (car (evil-alternate-buffer)))
    (switch-to-buffer (other-buffer (current-buffer) t))))
```

The macro provided by perspectives (`with-persp-buffer-list`) lets you modify the `buffer-list` function so that it only shows buffers in the perspective, BUT `evil-alternate-buffer` doesn't use this. Therefore I was forced to change the binding to a function that does work. Like

```elisp
(defun spacemacs/alternate-buffer-in-persp ()
  "Switch back and forth between current and last buffer in the
  current perspective."
  (interactive)
  (with-persp-buffer-list ()
    (other-buffer (current-buffer) t)))
```

Or I could have created a wrapper for this. I don't know which way is the more `spacemacsy`.

**Comment by syl20bnr** [comment]
@CestDiego I'm OK with the new function.

Excellent work thank you! :purple_heart: Sorry for having delayed this UI, most of it was in your initial PR.
Cherry-picked in rebased in develop branch, you can safely delete your branch.

**Comment by CestDiego** [comment]
No problem @syl20bnr actually I think this is an improvement of what I actually
had thought at the beginning. Sometimes a feature needs to be used and tested to
be improved.

**Pull request closed without merging**
