### PR TITLE
Add thrift mode in extra-langs layer.

### PR DESCRIPTION
**Pull request by secwang**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1:  -- always use topic branches -- never do a PR against the main branch -- I keep `develop` clean always -- it's always tracking upstream changes

**Comment by secwang** [comment]
@robbyoconnor  XD

**Comment by StreakyCobra** [comment]
From a personal point of view I will either:

- Put the `thrift` package inside the `layers/+lang/extra-langs` layer, as it's only one package
- Create a `thrift` layer inside `layers/+config-files/` if it is more configurations files than a language (but some markup format like `yaml` are in `layers/+lang` though)

My preferred choice would be the first for now. If it evolved it can still be moved.

**Comment by secwang** [comment]
@StreakyCobra  will move to extra-langs.

**Comment by StreakyCobra** [comment]
:+1:

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

I removed the `:mode` specification since the package does it itself: https://github.com/apache/thrift/blob/master/contrib/thrift.el#L33

**Pull request closed without merging**
