### PR TITLE
Added a keybinding for inactive time stamps in the org layer

### PR DESCRIPTION
**Pull request by channingwalton**

### CODE REVIEW

**Comment by StreakyCobra** [comment]
You should also document the new keybinding in the layer's README :-)

**Comment by channingwalton** [comment]
Thanks @StreakyCobra, sorry I'm new to this.

**Comment by StreakyCobra** [comment]
No problem :relaxed: :+1:

**Comment by channingwalton** [comment]
ok, I think I've done all the right things.

**Comment by TheBB** [comment]
Thanks! Cherry-picked (and squashed) in develop. You can safely delete your branch.

**Comment by channingwalton** [comment]
Thank you :)

**Pull request closed without merging**
