### PR TITLE
* layers/+lang/python/*: New flag python-enable-importmagic

### PR DESCRIPTION
**Pull request by sunlin7**
Spacemacs slow on opening a single *.py file.

I figured out the top performance killer for python layer are `importmagic` and `pyvenv`.
The `importmagic` will start a background server to process the requests from importmagic, it took ~0.5 seconds on my local; but acctually I rarely using the `importmagic` feature. 

This PR introduce a toggle flag `python-enable-importmagic` to give chance to disable this heavy feature.

PS: For `pyvenv` performance issue (leads Spacemacs slow when opening a *.py), I had an upstream PR, but it seems the project stop update for 3 years.
https://github.com/jorgenschaefer/pyvenv/pull/128

### CODE REVIEW

**Review by bcc32 — COMMENTED** [review]
By the way, thank you for all of your recent investigation into spacemacs's performance!

Do you think we should maybe leave this on by default?  We should weigh the cost of confusing users with silent behavior changes.  Certainly if we change the default behavior I think we should make that clear in the PR title, description, and commit messages.

**Comment by sunlin7** [comment]
Sure, I use Spacemacs for daily works, and really suffered by the slow performance for just opening a single *.py file :)

I had change the default value to `t` to not make a surprise for the users who're using the importmagic feature; and added a section on the document for users how to get performance benefit when they using the importmagic feature.

Please help review again. Thank you.

**Review by smile13241324 — APPROVED** [review]

**Comment by smile13241324** [comment]
Thanks for all the work guys :). Given that importmagic and epc are depreciated for a long time, and are really costly background processes I would disable them by default.

**Comment by sunlin7** [comment]
Thank you so much!

**Pull request merged**
