### PR TITLE
Add org layer keybindings for subtree & TODOs

### PR DESCRIPTION
**Pull request by katshinka**
* Move whole subtrees up/down/right/left with SPC mS commands
* When using more complex TODO sets, move between them with SPC m C-S
commands
* Add more cycling options with SPC mL SPC mK, etc.
(for timestamps, headlines, items, properties)
* Insert timestamps with SPC m.

### CODE REVIEW

**Comment by katshinka** [comment]
Hi,

Here goes my first PR (ever) !
Hope that doesn't show too much.
Those are commands I find myself using a lot, I figured others might too.

**Comment by robbyoconnor** [comment]
Good job <3

**Comment by cpaulik** [comment]
The `mH` keybinding conflicts with a keybinding used for sending org buffers as HTML emails. 
See https://github.com/katshinka/spacemacs/blob/develop/layers/%2Bemail/gnus/packages.el#L99

Could you update your PR to change the binding in the gnus layer and documentation?
I think something like `mm` should work. 

It would probably be better to move the org-mime package to the org layer in the longterm to make all the possible bindings clearer for new developers.

**Comment by robbyoconnor** [comment]
@cpaulik -- I'll do it

**Comment by cpaulik** [comment]
https://github.com/syl20bnr/spacemacs/issues/3062 to not forget about it. @robbyoconnor thanks

**Comment by robbyoconnor** [comment]
@katshinka, I handled the issues that @cpaulik had in #3063 -- so you can just sit back and relax :)

**Comment by katshinka** [comment]
Thanks guys. On that subject, the org-insert-time-stamp binding (SPC m .) collides with the spacemacs//erc-log-micro-state binding, which is defined globally.

I figured it was a non issue, but given what @cpaulik wrote here, it might very well be one...

**Comment by katshinka** [comment]
Also, I just noticed I did not document the new binding for the insert time stamp command :disappointed: . 
I'll do a revert today, when I have a minute to hook up my repo.

**Comment by TheBB** [comment]
Well, that's just a bug. erc-log shouldn't be global.

**Comment by katshinka** [comment]
Fair enough. I can ret easy then :smile:

**Comment by robbyoconnor** [comment]
Don't revert, just add it and rebase.

**Comment by katshinka** [comment]
Will do. Thanks !

**Comment by katshinka** [comment]
The doc has been updated, and the PR rebased.

**Comment by robbyoconnor** [comment]
Nice job :)

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
Cherry-picked in develop branch.

**Pull request closed without merging**
