### PR TITLE
git: add `SPC g L` keybinding for magit-file-log

### PR DESCRIPTION
**Pull request by tko**
Display the log for the currently visited file or another one.

### CODE REVIEW

**Comment by andyque** [comment]
@tko  cool :+1:  I use this command often when review a file version.

**Comment by syl20bnr** [comment]
`SPC g f` is a prefix command and `SPC g f l` is already taken so I propose `SPC g L` for this command.

**Comment by tko** [comment]
Gah, forgot about github layer. Is there an easy way to check if keybinding is already used elsewhere?

**Comment by robbyoconnor** [comment]
[here](https://github.com/syl20bnr/spacemacs/tree/develop/contrib/!source-control/github) is the github layer stuff. From my cursory inspection <kbd>g L</kbd> seems like a safe keybinding.

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
I adapted it for the upcoming magit 2.1 as well.

Cherry-picked into develop branch.

**Pull request closed without merging**
