### PR TITLE
remove structured-haskell-mode

### PR DESCRIPTION
**Pull request by d12frosted**
Ok, so now it's agains develop (see #5078).

---

Just as the title says - by this commit we remove shm. The main reason is that shm doesn't play well with vim editing style and causing more problems that are not so easily fixed. But still, it's very easy to add it to personal configs if you are using emacs editing style. 

Related issues: #5026, #1048 and #3171(this one has more explanations). 

> officially Chris Done marked `shm` and `evil` as mode-conflict and wont-fix

---

Also added some notes about removal.

As @robbyoconnor mentioned in my previous PR we could also support shm only for emacs editing style. So Spacemacs would have a good starting point for shm users. But it's really only two configs - add hook and disable line highlight in haskell sources. So I'll let @syl20bnr to decide what to do with this PR. I am ok with both solutions. 

And as README file says - if someone comes with a good solution for evil + shm - please be so kind and send us PR :)

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Why did nobody fix this shit?

**Comment by d12frosted** [comment]
I think mostly because it's not that trivial. Structured haskell mode was created without evil in mind, and there are some conflicting things. In my opinion solution of this problem should be not in Spacemacs, but in shm. But since it's officially won't fix - we are stuck a bit. As for me - I don't use vim editing style (and don't really want to learn it :-P), so I haven't spend much time on this issue (I don't know how most things should work for vim editing style). 

> Why did nobody fix this shit?

Those who tried - failed :D

**Comment by StreakyCobra** [comment]
> Why did nobody fix this shit?

I'm sure they welcome PR.

**Comment by d12frosted** [comment]
Ping, ping :cry:

**Comment by PierreR** [comment]
I vote for removing it too.

As an aside, there are already  too many `haskell` bindings/features that just don't work in spacemacs because it is broken in `ghc-mod`, `haskell-mode` or whatever.

As an example, `<spc> mmt` (or `,mt`) is supposed to insert signature but does not. There is an issue on `ghc-mod` that dates back to Sep 2015 with no reaction from the project maintainer (https://github.com/DanielG/ghc-mod/issues/628). There is a similar issue in `haskell-mode` that was blindly closed ...

It is very confusing for the end user to face such broken features so I guess we should just comment these bindings while waiting for a fix to come (if it does one day).  

I should probably create an issue for all the "non-working" bindings in the haskell layer. What do you think ?

**Comment by d12frosted** [comment]
> I should probably create an issue for all the "non-working" bindings in the haskell layer. What do you think?

Aside of SHM - sure do so :)

**Comment by d12frosted** [comment]
Ping, ping 😿

**Comment by StreakyCobra** [comment]
Who is there?

**Comment by jhenahan** [comment]
So, what issues are people actually having with this? SHM works great for me with vim bindings (it's actually the only indentation mode that seems to work the way I want), and I can indent just fine with `==`.

**Comment by d12frosted** [comment]
It's great that you don't have any problems with it. I am not using vim, so I am [linking](https://github.com/syl20bnr/spacemacs/pull/5087#issue-133911309) other's issues. 

So in general it doesn't work 100% for evil users and even causing some problems and frustration. People come with these problems and questions here, but no one is willing to fix them or able to help. That's why I thought that it might be good idea to drop shm-support (I say 'support', but anyway it wasn't really supported). Adding `shm` to users config is not hard (it's just a matter of copy-pasting several lines). 

But in case someone wants to step in and support `shm` for vim editing style - I am all for it - just go ahead and help to resolve linked issues. I would be grateful 😸

**Comment by d12frosted** [comment]
Also related: https://github.com/chrisdone/structured-haskell-mode/issues/81

**Comment by jb55** [comment]
> @jhenahan So, what issues are people actually having with this? SHM (with the package from master) works great for me with vim bindings (it's actually the only indentation mode that seems to work the way I want), and I can indent just fine with ==.

I wrote down some of my issues with it here https://github.com/syl20bnr/spacemacs/pull/5026#issue-132896392

**Comment by jhenahan** [comment]
@jb55 I definitely agree that the normal mode bindings should be removed. I made note of how I actually use it, and it seems that I mainly use SHM in insert, anyway, so I guess I was never bitten by those issues. However, those bindings are powerfully fucked up, so I'll work on a PR tonight to make that less ridiculous. The actual functionality is totally working for me (no errors about indentation or anything like that), so I'll do the needful to keep it in.

**Comment by d12frosted** [comment]
Ok. That's great, waiting for PR :)
On Fri, May 20, 2016 at 11:17 PM Jack Henahan <notifications@github.com>
wrote:

> @jb55 <https://github.com/jb55> I definitely agree that the normal mode
> bindings should be removed. I made note of how I actually use it, and it
> seems that I mainly use SHM in insert, anyway, so I guess I was never
> bitten by those issues. However, those bindings are powerfully fucked up,
> so I'll work on a PR tonight to make that less ridiculous. The actual
> functionality is totally working for me (no errors about indentation or
> anything like that), so I'll do the needful to keep it in.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/pull/5087#issuecomment-220708054>
>
-- 
Best regards,
Boris @ d12frosted

**Comment by syl20bnr** [comment]
Not sure what to do with this PR, anyone can refresh me on this ? :-)

**Comment by jhenahan** [comment]
Currently working on it, just had a busy stretch at the office. I'll have new keybinds and some other conveniences within the week, I expect.

**Comment by syl20bnr** [comment]
Great, no hurry :-)

**Comment by d12frosted** [comment]
I rebased so it's not conflicting anymore.

**Comment by syl20bnr** [comment]
This is it, shm is no more!
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
