### PR TITLE
Minor typo fix in CHANGELOG.org

### PR DESCRIPTION
**Pull request by xfq**
Markup fix.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Already fixed in #5156

**Comment by syl20bnr** [comment]
Indeed @rpglover64 has been a little bit quicker.
Thank you for the PR :+1:

**Comment by xfq** [comment]
OK.  I'll submit another fix for CHANGELOG.org.

**Comment by xfq** [comment]
#5159

**Pull request closed without merging**
