### PR TITLE
Fix a link on beginner's tutorial

### PR DESCRIPTION
**Pull request by lpenz**
Fix a 404 link in doc/BEGINNERS_TUTORIAL.org

### CODE REVIEW

**Comment by Nikolaiam** [comment]
Ah, seems like I spotted the same thing in #8093 :) great! Might be we'll have to wait and see whether or not my PR is going to be accepted as ours would conflict if both are merged?

**Comment by lpenz** [comment]
I think they would :)
It's a simple fix though, on your side - on my side there's no need for a fix, we'll just drop the PR.

**Comment by d12frosted** [comment]
Thank you :+1: Cherry-picked into `develop`, you can safely delete your branch.

To be honest I like the full url much more 😸 As we prefer our users to read it from Emacs 😸

**Comment by lpenz** [comment]
:smiley: good to know! :+1:

**Pull request closed without merging**
