### PR TITLE
Set leader keys for projectile-rails minor mode instead of ruby's maj…

### LINKED ISSUE #7424: Rails comma keybindings not available when on a view file window
Working with rails on spacemacs, I found it would be incredibly useful to have rails comma keybindings enabled on view file windows. 
For example when implementing feature tests it is cumbersome to have to switch to any *.rb window in order to be able to `, t a` [rspec-verify-all - run all tests].

I am still learning how to customize spacemacs, but so far couldn't identify how to have those keybindings enabled on view file windows. 

Will gladly send a PR once I learn how to implement that. Meanwhile, any suggestions?

### PR DESCRIPTION
**Pull request by asok**
…or mode

Closes #7424

### CODE REVIEW

**Comment by asok** [comment]
Actually this overwrites a keybinding for web-mode accessible via `,r`.
So it cannot be merged in like that. Maybe someone could suggest a solution? Move the web-mode's keybinding from `,r` to somewhere else? This does not sound like a good approach since the projectile-rails minor mode could be on in other major modes also. So it would need to take care of them also (yaml-mode, compilation-mode, magit-mode etc...)

**Comment by syl20bnr** [comment]
We should move `ruby-on-rails` key bindings as `SPC m r ` is for refactoring. Since it is a web framework, we could put them under `SPC m f` ? This prefix is free, we have no convention on it yet.

**Comment by syl20bnr** [comment]
I added the convention: https://github.com/syl20bnr/spacemacs/commit/90452329

**Comment by asok** [comment]
I've updated the PR so the keybindings are start with the `f` letter. Now the experience is much, much better. You can reach the projectile-rails' keybindings from any buffer with the mode enabled.

**Comment by asok** [comment]
@syl20bnr I'm using this for the last week and it works perfectly. I strongly advise for merging this in :)

**Comment by sdwolfz** [comment]
@asok Can you please also add these new keybindings to the documentation?

**Comment by asok** [comment]
@sdwolfz done

**Comment by sdwolfz** [comment]
Awesome! Thanks @asok, I'll take a look and merge it this weekend.

**Comment by sdwolfz** [comment]
Thank you :heart:!

I reverted your change from `SPC m` to `,` in the documentation since all the other layers use `SPC m`: 3873ed52fe28b5cb8ebb00a34761b4caf63bb597.

Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
