### PR TITLE
Add minimal ERC layer

### PR DESCRIPTION
**Pull request by swaroopch**

### CODE REVIEW

**Comment by cpaulik** [comment]
Hi, I was planning to add a erc layer also and it is actually quite far along. 

You can find it [here](https://github.com/cpaulik/dotfiles/tree/master/.spacemacs-config/config-layers/erc).

Should I open a pull request against your ```swaroopch:erc_layer``` branch so that we can include the additional keybindings?

**Comment by swaroopch** [comment]
@cpaulik Hey Christoph, great, you're indeed further along.

We can either:

1. I can delete my pull request and you can send your pull request to the main repo
2. You can send a pull request to my branch

We can do which ever is easiest for you :)

Regards,
Swaroop

**Comment by syl20bnr** [comment]
Thank to both of you ! :+1:  :+1: 
I improved it a bit in commit 8a1750b7c0ee2bf0f14789263982c0e2f7dd8b66
- I kept the `SPC a e` binding in `:init` and the rest moved to `:config` in order to be sure that the package is lazy loaded.
- `erc-terminal-notifier` is added only on OS X

Cherry-picked in `develop` you can safely delete your branch.

**Comment by swaroopch** [comment]
@syl20bnr Thank you! :)

**Comment by cpaulik** [comment]
Thanks. The best part of contributing to spacemacs is that I always learn a little bit of elisp from you.

**Pull request closed without merging**
