### PR TITLE
Clarification on using packages without a layer

### PR DESCRIPTION
**Pull request by lverns**

### CODE REVIEW

**Comment by lverns** [comment]
I realized that the example code in this section was straight up incorrect, so I removed it. The documentation points users to the correct spot in `~/.spacemacs` which should be all that is needed.

**Comment by lverns** [comment]
I've now squashed the commits and formated the message as specified in [CONTRIBUTING.org](https://github.com/lverns/spacemacs/blob/docs/CONTRIBUTING.org)

**Comment by d12frosted** [comment]
> I've now squashed the commits and formated the message as specified in CONTRIBUTING.org

👍 Wanted to ask you to do so 💃 

> I realized that the example code in this section was straight up incorrect

What's wrong? `setq` vs `setq-default`?

**Comment by lverns** [comment]
> What's wrong? setq vs setq-default? 

I guess the example wasn't technically wrong, so much as confusing or encouraging bad practice.

It turns out that you can set `dotspacemacs-additional-packages` using either `setq` or `setq-default`. However, the variable is already in `.spacemacs` inside a big call to `setq-default` so users should just modify that instead of making a separate call to `setq`/`setq-default`.  Indeed, setting it in multiple places will result in the last call overriding earlier ones.

**Comment by d12frosted** [comment]
Ah I see. I remember several people reporting problems with layers activation. As it turned out, they made new `setq` call instead of modifying existing variable. My usual advice - read the whole `.spacemacs` file and all the comments before reporting errors. 

In any case, I understand your intention and I like it. Though having example is useful. What do you think about using following snippet?

```
(defun dotspacemacs/layers ()
  "Configuration Layers declaration."
  (setq-default
   ;; ...
   dotspacemacs-additional-packages '(llvm-mode dts-mode)
   ;; ...
   ))
```

**Comment by d12frosted** [comment]
FYI https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#install-a-package-not-provided-by-a-layer

**Comment by lverns** [comment]
Question:
Is there a way to build the html [here](http://spacemacs.org/doc/DOCUMENTATION.html) for viewing on my local machine?

**Comment by syl20bnr** [comment]
@lverns Yes you can, load the file `core/core-documentation.el` either with `load-file` or `require` then `SPC SPC spacemacs/publish-doc`. You should have them in `export` folder.

**Comment by syl20bnr** [comment]
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
