### PR TITLE
Clarify logo license (#6469)

### PR DESCRIPTION
**Pull request by nashamri**
Fixing issue #6469

### CODE REVIEW

**Comment by syl20bnr** [comment]
Thank you ! 👍 
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by syl20bnr** [comment]
Ah seems that it was the 3000th closed PR, so you've got an achievement lol

**Comment by syl20bnr** [comment]
Oops I did not sorted by recently updated, actually it is https://github.com/syl20bnr/spacemacs/pull/6338
sorry, next time :-)

**Comment by nashamri** [comment]
Oh dang it! I'll track the next 4000th PR now! lol

**Pull request closed without merging**
