### PR TITLE
 README: update docs for getting emacs on Ubuntu

### LINKED ISSUE #5071: Docs are Misleading
You can't straightup install spacemacs on ubuntu 14.04 LTS which is the current default distro for a lot of people. The default emacs version is 24.3.x when you need 24.4.x for a particular helm package. This should be corrected in the tutorial.

### PR DESCRIPTION
**Pull request by robbyoconnor**
The version is 24.3 and is not well supported anymore.

Closes #5071

### CODE REVIEW

**Comment by syohex** [comment]
This is Ubuntu LTS 12.04, 14.04 issue. Ubuntu 15.10 or higher users can use apt package Emacs(24.5). There is no problems on Ubuntu 15.04 too but it is EOL now.

Current supported Ubuntu is here.

https://wiki.ubuntu.com/Releases

**Comment by robbyoconnor** [comment]
@syohex, see c5539d69c1920d3507c7d673add2c22bcd2ea136

**Comment by syohex** [comment]
:+1:

**Comment by syl20bnr** [comment]
Thank you!
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
