### PR TITLE
Fix inline `code` styling

### PR DESCRIPTION
**Pull request by kyanny**
[Unicode Character 'RIGHT DOUBLE QUOTATION MARK' (U+201D)](https://www.fileformat.info/info/unicode/char/201d/index.htm) breaks inline `code` styling.

Replacing it with [Unicode Character 'QUOTATION MARK' (U+0022)](https://www.fileformat.info/info/unicode/char/0022/index.htm) fixes it.

# Screenshots

## Before

スクリーンショット 2020-06-19 21 58 05

## After

スクリーンショット 2020-06-19 22 00 50

### CODE REVIEW

**Comment by smile13241324** [comment]
Hi @kyanny,

I am not sure I have found the issue your change is fixing. I have checked [here](https://github.com/syl20bnr/spacemacs/blob/develop/doc/BEGINNERS_TUTORIAL.org) as well as [here](https://develop.spacemacs.org/doc/BEGINNERS_TUTORIAL.html) and both have the correct styling on my pc.

I am on manjaro using the latest firefox.

**Comment by duianto** [comment]
I'm seeing the change in Firefox in both PopOS and Windows.

### When comparing the current develop docs:
https://github.com/syl20bnr/spacemacs/blob/develop/doc/BEGINNERS_TUTORIAL.org

#### PopOS:
VirtualBoxVM_2020-06-26_11-55-00

#### Windows:
firefox_2020-06-26_11-54-02


### with kyannys fork:
https://github.com/kyanny/spacemacs/blob/kyanny/fix-doc/doc/BEGINNERS_TUTORIAL.org

#### PopOS:
VirtualBoxVM_2020-06-26_11-55-20

#### Windows:
firefox_2020-06-26_11-54-24

**Comment by smile13241324** [comment]
#
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

**Comment by kyanny** [comment]
You're welcome! Thank you @smile13241324 and @duianto !

**Pull request merged**
