### PR TITLE
keyboard-layout layer

### LINKED ISSUE #6274: buf-move- functions and Bepo layer
#### Description :octocat:
In bepo layer. `SPC b m` isn't bound to correct keys on first use.
#### Reproduction guide :beetle:
- Start Emacs (with bepo layer enabled)
- Make some windows to move
- type `SPC b m` next move is bound to `h, j, k, or l`
- type it again it's corrected to `c, s, r, t`

This one is for @StreakyCobra again.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.50.2
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. ea77a5d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(racket emacs-lisp java javascript clojure
        (python :variables python-test-runner
                '(nose pytest))
        rust common-lisp
        (haskell :variables haskell-process-type 'stack-ghci haskell-enable-shm-support t haskell-enable-hindent-style "gibiansky" haskell-process-path-ghci "stack" haskell-process-args-ghci
                 '("ghci"))
        elm deft markdown org latex speed-reading finance fasd erc jabber
        (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp/mu4e" mu4e-enable-notifications t mu4e-enable-mode-line t mu4e-contexts t)
        twitter slack spacemacs-layouts auto-completion bepo git github
        (ranger :variables ranger-override-dired t ranger-show-dotfiles nil)
        (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
        spell-checking syntax-checking xkcd)
```

### PR DESCRIPTION
**Pull request by StreakyCobra**
My last big gift :gift_heart: (hopefully not poisoned :smiley:)

Move the `+keyboard-layouts/bepo` layer to `+intl/keyboard-layout` and generalize it to support more than one layout. For now these ones are supported:

- bepo
- dvorak

There are probably some bugs left as I cannot test anything (especially for dvorak), but nothing that prevent it to be merged on `develop` and being fixed as bugs appears.

Supersede #5245, #6255, #6280

Fixes #6274 #6264, #561, #1391

cc @brabalan @CharlesHD @AlejandroCatalina @MadAnd

### CODE REVIEW

**Comment by MadAnd** [comment]
@StreakyCobra good work! 

I am ready to test and elaborate on the `dvorak` part once it is merged with `develop`.

**Comment by StreakyCobra** [comment]
Adding a new layout should be as simple as:

- Add the mapping table in `kl--base-rebinding-maps`:

        (newlayout . (("a" . "h")
                      ("b" . "j")
                      ("c" . "k")
                      ("d" . "l")
                      ;;
                      ("h" . "a")
                      ("j" . "b")
                      ("k" . "c")
                      ("l" . "d"))
         ;; Dots should be read as `will behave as'

- All the `:common` properties of all `(kl|config …` configuration blocks are automatically applied for all layouts, including new ones. This is why the code within `:common` should be generic and should mostly (only?) use `(kl/…-correct-keys …` functions calls.

- It is possible to freely add some `:newlayout` properties in the `(kl|config …` configuration blocks to change or add keybindings specific to this new layout, but most of the time it is used to fix issues with automatic remapping :pensive:.

And then the `newlayout` layout can be used as simply as:

             (keyboard-layout :variables kl-layout 'newlayout)

**Comment by CharlesHD** [comment]
What a wonderful gift. Thanks ! I hope it will help spread spacemacs to many international keyboard layouts.

**Comment by MadAnd** [comment]
@syl20bnr I just remembered about my older [PR](https://github.com/syl20bnr/evil-iedit-state/pull/9), relevant for better i18n support within Spacemacs.

**Comment by StreakyCobra** [comment]
I updated the PR to add the remapping of `C-j` and `C-k` in `mu4e`

**Comment by andysaini** [comment]
Awesome 👍

**Comment by AlejandroCatalina** [comment]
Awesome! I am looking forward seeing this merged!

**Comment by syl20bnr** [comment]
Thank you for the wonderful gift 💜  💜  💜  I'm sure lots of users will appreciate it 😍 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
