### PR TITLE
added file-only and directory-only functions and helm-completion to fasd

### PR DESCRIPTION
**Pull request by mijoharas**
This changes the completion-function to be the default completion function. I looked around for what the correct helm-completion function should be (as the default completion function is only helm once helm has been loaded, e.g. after `SPC :`) but couldn't find what I was looking for. Should I add something to the dependencies to make this load helm once it is loaded? (also, what is the correct way to do that? I assume it is something to do with use-package?)

### CODE REVIEW

**Comment by endrebak** [comment]
Very nice, but it seems unfair to me that regular users should have to press one more button to access fasd. Perhaps f-Z can be used for files only and f-(Ctrl-z) for directories only (which I imagine will be the least common use-case)? Or f-(M-z)/f-(Ctrl-z) if he does not want to use the f-Z binding for another fasd function.

I actually use fasd often so I'd like to keep it to two keypresses if possible. These are just comments, obviously. Syl is the judge, and it might very well be that he prefers your way to do it though.

**Comment by mijoharas** [comment]
I commented on the gitter but thought I'd write it here too. I'm good with whatever people think is best, both seem good to me.

**Comment by endrebak** [comment]
`fzf` is probably a great mnemonic. I use fasd so often though that I should make a keychord for it. Shouldn't have commented, sorry.

**Comment by syl20bnr** [comment]
I propose `fa` as the prefix command, then everything can be on the home row (qwerty setting)
- `fas` search
- `faf` file
- `fad` directory

**Comment by mijoharas** [comment]
souds good to me. Done. :+1:

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
Cherry-picked into `develop`.

**Comment by mijoharas** [comment]
Thanks :+1:

**Pull request closed without merging**
