### PR TITLE
Add common-lisp-snippets packages

### PR DESCRIPTION
**Pull request by tuhdo**
This package contains useful snippets for Common Lisp.

### CODE REVIEW

**Comment by TheBB** [comment]
Should probably guard this so that you don't get yasnippet if you don't have the auto-completion layer installed. (It's a dependency of this package.)

**Comment by tuhdo** [comment]
@TheBB Done.

**Comment by Andre0991** [comment]
Great, thanks. I'm learning CL :+1:

**Comment by TheBB** [comment]
:+1:

**Comment by AlejandroCatalina** [comment]
Great, :+1:

**Comment by robbyoconnor** [comment]
:+1:

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

Since the `use-package` expands to a no-op I removed it.

**Pull request closed without merging**
