### PR TITLE
Fix link to themes-megapack layer in documentation

### PR DESCRIPTION
**Pull request by CarlQLange**

### CODE REVIEW

**Comment by StreakyCobra** [comment]
Thanks for your contribution. This link has already been corrected in the `develop` branch. In Spacemacs, all PRs [have to be made against `develop`](https://github.com/syl20bnr/spacemacs/blob/master/CONTRIBUTING.md) by the way :relaxed:

**Comment by CarlQLange** [comment]
Sorry! I knew that! I was just reading the doc and thought I should open a PR to fix, didn't think :)

**Comment by StreakyCobra** [comment]
:-) It's fine, thanks for taking time to help. There are some `Beginner Friendly` issues by the way :innocent:

**Comment by CarlQLange** [comment]
I'm no beginner! ;)

**Comment by StreakyCobra** [comment]
I know, but if you want to fix an issue for your breakfast from time to time :D

**Comment by CarlQLange** [comment]
haha fair point. great work by the way :) best thing about spacemacs is the community

**Pull request closed without merging**
