### PR TITLE
Add Travis CI support for core tests #144

### PR DESCRIPTION
**Pull request by lazywithclass**
Added the badge to the README.md and created a travis config file.

I followed [the guide for contributions](https://github.com/syl20bnr/spacemacs/blob/master/doc/CONTRIBUTE.md), but I'm not really sure I did everything correctly about this passage:

> rebase your PR branch on top of upstream develop before submitting the PR

Could you please explain it briefly? 
What I did was `git pull $remote develop` and `git chekout -b` from it. I think I need another step, but it's not clear to me.

### CODE REVIEW

**Comment by syl20bnr** [comment]
The rebase is only for the case when you have multiple commits in the PR. 

That's great ! Now I have to take the time to code the tests :-)
Thank you :+1: 

Cherry-picked into the `develop` branch, you can safely delete your branch.

**Comment by lazywithclass** [comment]
I've seen that the badge in the README is still in the `unknown` state, are you having problems with that?
I've checked right now on `develop` and the build gets triggered fine in my account.

I'm now going to have a look  at #110, let me know if there's something else I should know.

**Comment by syl20bnr** [comment]
I did not activate Travis CI integration for the repo.
#110 is assigned to me but help is welcome, I'll try to make a first batch of tests for `configuration-layer.el` this week-end. So if you want to add some tests you can start with `spacemacs-mode.el`. The git related functions could be a good start. Thank you !

**Comment by lazywithclass** [comment]
Ah that's perfect then. I was worried it had some problems.

I can have a look at the git functions in `spacemacs-mode.el`, sure.

**Pull request closed without merging**
