### PR TITLE
Adds magit-diff-buffer-file-popup key

### PR DESCRIPTION
**Pull request by agzam**
Sorry for a minuscule PR, this keybinding I think makes sense. ~I also tried to update layer's readme, but there's no section on `g f` keybindings. I wasn't sure where to add one~.

and while we're at it, can we please consider changing `g f h` to `g f l` maybe?

### CODE REVIEW

**Comment by syl20bnr** [comment]
> can we please consider changing g f h to g f l maybe?

Good idea.

Be sure to update the documentation in corresponding `README.org` file when you submit/change key bindings ;-)

**Comment by agzam** [comment]
@syl20bnr Done!

**Comment by syl20bnr** [comment]
Nitpicking but can you split into 2 commits ? I would like to have the key binding change in its own commit to people can quickly spot it in the history or git blame. Or maybe you can put both changed on the first line of the commit if enough space for it.

**Comment by agzam** [comment]
@syl20bnr I cannot agree with you more. Every single modified or new keybinding should be added with care and increased visibility.

**Comment by agzam** [comment]
@syl20bnr this is ready to merge btw.

**Comment by sdwolfz** [comment]
Thank you :heart:!
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
