### PR TITLE
Add pass layer

### PR DESCRIPTION
**Pull request by darkfeline**
This layer adds support for pass, the standard unix password manager.

http://www.passwordstore.org/

### CODE REVIEW

**Comment by oppenlander** [comment]
Hi @darkfeline! I already started a `pass` layer, in #2784.

This was before a lot of changes to the Spacemacs file layout, so it needs to be updated. 
I'll try to get it fixed up later today.

Is there a reason you didn't use the `password-store` package [pass](http://passwordstore.org/) already provides?

**Comment by darkfeline** [comment]
Nope, just poor research on my part.  Let's continue the discussion on your PR.

**Comment by robbyoconnor** [comment]
Close this PR please.

**Comment by robbyoconnor** [comment]
:+1: thanks :D

**Comment by robbyoconnor** [comment]
:+1: thanks :D 

This helps keep the project moving efficiently when we have less duplicate PRs/Issues :)

**Pull request closed without merging**
