### PR TITLE
Add support for other image types in Spacemacs banner

### PR DESCRIPTION
**Pull request by jupl**

### CODE REVIEW

**Comment by syl20bnr** [comment]
There seem to be pattern where we could define a list `banner-supported-image-format` to `'(png svg)

**Comment by jupl** [comment]
Agreed. I can work on that.

**Comment by jupl** [comment]
Found an even more efficient way: `image-type-available-p`

**Comment by syl20bnr** [comment]
Thank you again :+1: 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
