### PR TITLE
Org download layer

### PR DESCRIPTION
**Pull request by krakapwa**
Added layer for org-download support. It is a package that allows to  drag-and-drop images from a web-browser or file-system into org files. Also, it can be used to insert images straight from gnome-screenshot (or the like). The images are automatically saved into a user-defined folder with timestamps.

### CODE REVIEW

**Comment by NJBS** [comment]
Congratulations on your first pull request to spacemacs! :confetti_ball: 

Please take a minute to read through the [Beginner's Guide to Contributing a Pull Request to Spacemacs](https://github.com/syl20bnr/spacemacs/wiki/Beginner's-Guide-to-Contributing-a-Pull-Request-to-Spacemacs) and the [Contribution guidelines](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org)! Take note that all pull requests should be made against the `develop` branch, instead of the `master` branch as you've done here.

**Comment by nixmaniack** [comment]
You should create a PR against `develop`. This should be closed.

**Comment by StreakyCobra** [comment]
Closing this for the reasons explained above. Please open a new PR against `develop` when you are ready :-)

@NJBS I'm stealing your comment for future new users :-) I hope you don't mind?

**Comment by NJBS** [comment]
@StreakyCobra No problem, go for it!

**Pull request closed without merging**
