### PR TITLE
Add transient state for smerge mode

### LINKED ISSUE #7378: Add keybindings for smerge-mode
When using magit to resolve a merge conflict `smerge-mode` opens automatically for me; however, all the keybindings are under <kbd>C-c ^</kbd>. I believe it would be better to also have them under <kbd>SPC m</kbd> or <kbd>SPC g</kbd> or even <kbd>SPC g m</kbd>.
#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:

``` elisp
(auto-completion better-defaults haskell emacs-lisp git ivy emacs-lisp org agda deft spell-checking
                 (syntax-checking syntax-checking-enable-tooltips 'nil))
```

### PR DESCRIPTION
**Pull request by perfectayush**
This layer implements a transient state for using smerge mode. Fixes #7378

### CODE REVIEW

**Comment by perfectayush** [comment]
I have update commit as per suggestions. I am citing other examples of transient state definitions, specifically one for git-time-machine. I have used the :config block as used in git-time-machine. I have tested for a sample merge conflict, it works as intended.

I am not sure about how to wrap `spacemacs/smerge-transient-body` in a command with require for `smerge-mode` . If that's the correct approach and I can cite an example for that, I can do it.

**Comment by idoo** [comment]
@bmag I guess that `c` is better namespace for this scope. `r` is more related to `rebase` or `reset`

**Comment by bmag** [comment]
Thank you :+1: Cherry-picked into develop, you can safely delete your branch.

@idoo I feel `r` is still a better mnemonic, and all of the major magit operations are available at `SPC g m`.

**Comment by bersace** [comment]
Thanks for this addition. Very useful. I'm finally using emacs to resolve conflicts ! Kudo @idoo !

**Comment by jstewart** [comment]
This commit makes resolving merge conflicts in spacemacs a pleasure instead of a pain. Thank you very much, @idoo!

**Pull request closed without merging**
