### PR TITLE
[Lua]Add company-lua for lua-mode

### PR DESCRIPTION
**Pull request by halfcrazy**
Lua-mode it self has poor completion support and company-lua will enhance it.

### CODE REVIEW

**Comment by halfcrazy** [comment]
Any suggestions? or when it will be merged.

**Comment by syl20bnr** [comment]
@d12frosted Same thing for this one, it is tagged to be merged but it is not in develop branch.

**Comment by halfcrazy** [comment]
@syl20bnr Seems still not merged

**Comment by syl20bnr** [comment]
np, I'll look into it soon.

**Comment by syl20bnr** [comment]
Thank you ! 👍 
I updated the PR to use the new `add-company-backends` macro,
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
