### PR TITLE
* core/core-dotspacemacs.el: Mark variable dotspacemacs-command-key obsoleted

### PR DESCRIPTION
**Pull request by sunlin7**
The `dotspacemacs-command-key` was renamed to `dotspacemacs-command-key` on Jan 9, 2016, commit:
58e5241c8d96da0a2cf04d4897a74c9d1250875e .

It should be safe to remove the alias and use the official name only.

### CODE REVIEW

**Comment by bcc32** [comment]
The old name was not made obsolete when the alias was added, so nothing would have automatically warned users of the old variable name.  It's not safe to remove one of the names immediately; it would need to be marked obsolete first (e.g., using `define-obsolete-variable-alias`).

**Comment by sunlin7** [comment]
@bcc32  Sure, I marked it obsoleted now, please review the latest one, thank you.

**Comment by bcc32** [comment]
Thanks.  I removed the docstring because `define-obsolete-variable-alias` already generates one which contains the same information.

**Review by bcc32 — APPROVED** [review]

**Comment by sunlin7** [comment]
Sure, it's more elegant, thanks!

**Pull request merged**
