### PR TITLE
added a function to perform helm-gtags-dwim-other-window (SPC m g G)

### PR DESCRIPTION
**Pull request by mijoharas**

### CODE REVIEW

**Comment by mijoharas** [comment]
Note, the `split-height-threshold` and `split-width-threshold` is to make the buffer appear beside rather than below the window I'm in (which is my preference).

I feel like there's probably a better way to do that, but I don't know what it is :smile:

**Comment by tuhdo** [comment]
You should push the command upstream and we simply reuse it here. I think it's better that way.

**Comment by mijoharas** [comment]
@tuhdo you're probably right, if I do that I'd need to clean up the `split-height-threshold` e.t.c. do you know what the correct way to make a window open to the side rather than below by default?

**Comment by syl20bnr** [comment]
Thank you !
For now I merged it, if the function is merged upstream we can modify the binding to use the new function.

Cherry-picked into develop, you can safely delete your branch.

**Comment by mijoharas** [comment]
Thanks, can I ask you if you know of a cleaner way of making the window show up to the side instead of below?

i.e rather than:

```
(split-height-threshold nil)
(split-width-threshold 140)
```

I feel like there's a cleaner way, I just don't know what it is.

**Comment by tuhdo** [comment]
You can use `C-t` to switch Helm layout to side.

**Comment by tuhdo** [comment]
Or, you can add an entry for helm-gtags buffers like I did with Helm help buffers in this PR: https://github.com/syl20bnr/spacemacs/pull/1638

**Pull request closed without merging**
