### PR TITLE
Define insert <kbd> tag a la C-h k for org and md

### PR DESCRIPTION
**Pull request by CestDiego**
This makes it possible to use the kbd tag. I'm not sure where should
this be in. Feel free to move it around.

Refers to #1568

### CODE REVIEW

**Comment by syl20bnr** [comment]
I would split the function into two functions, one for `org` and one for `markdown` and move them to the respective layers behind a command `SPC m ...` binding.
This is a bit against DRY but in this particular case I find it better to have specific functions.

**Comment by CestDiego** [comment]
what if we only define the key binding in the org and markdown layers?

**Comment by syl20bnr** [comment]
I don't like having `org` or `markdown` related functions in spacemacs layer. They should go in their respective layer.

**Comment by CestDiego** [comment]
Ok it's ready for review

**Comment by syl20bnr** [comment]
Perfect, thank you :+1: 
Cherry-picked into `develop`, you can safely delete your branch.

**Pull request closed without merging**
