### PR TITLE
Add shen layer

### PR DESCRIPTION
**Pull request by bsima**
My first contribution to spacemacs! Let me know if I need to change anything to meet your standards, but I think I got everything on the contributing doc. This is just a simple layer - I'm just starting to learn Shen, so maybe I'll have improvements to this in the future as I learn to use Shen on all its different platforms.

### CODE REVIEW

**Comment by d12frosted** [comment]
You should setup keybindings for `shen-mode` in Spacemacs style. Just check some other languages for example (like python, ruby, haskell, elisp). I am talking about keybindings like [these](https://github.com/eschulte/shen-mode/blob/master/inf-shen.el#L58). 

Some references: 

* [binding keys](https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#binding-keys)
* [evil leader](https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#evil-leader)

**Comment by bsima** [comment]
I'll get to this over the weekend, shouldn't take long, I already have some of it implemented locally, just gotta find time to finish it up

**Comment by CestDiego** [comment]
This is so cool :) I was about to try shen and BAM there is already an Spacemacs Layer in the works :P

**Comment by bsima** [comment]
@d12frosted I just now was able to wrap up the keybindings. Whenever you get a chance, let me know if there is anything else you need me to do :)

**Comment by bsima** [comment]
*note*:  because this branch has fallen so far behind master, I've been experimenting with a private shen layer [here](https://github.com/bsima/me/blob/master/system/spacemacs.org#shen-layer).

**Comment by dcluna** [comment]
:+1:

**Comment by d12frosted** [comment]
Wow, it was left behind. Sorry about that. 

@bsima do you still use Shen? If you wish to see these configs part of Spacemacs, please open new PR. I am closing this PR as your remote repository was removed. 

P. S. thanks for the link to private layer.

**Comment by bsima** [comment]
@d12frosted I haven't been using shen recently, but I will get back to it at some point in the next few months. When I do, I'll open a new PR with my updated and improved shen layer based on my private layer

**Comment by d12frosted** [comment]
Great. Thanks for the update. Have fun 💃 😸

**Pull request closed without merging**
