### PR TITLE
Enable company-mode in alchemist-iex-mode

### PR DESCRIPTION
**Pull request by utkarshkukreti**
I'm not 100% sure if this is correct. I copied the existing `company-mode` related code and replaced `elixir-mode` with `alchemist-iex-mode` and it seems to be working fine.

### CODE REVIEW

**Comment by utkarshkukreti** [comment]
The Travis failure seems to be unrelated.

**Comment by TheBB** [comment]
Seems alright. This is for the REPL, correct?

**Comment by utkarshkukreti** [comment]
Yes.

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
