### PR TITLE
Add exec-path-from-shell link

### PR DESCRIPTION
**Pull request by k-bx**

### CODE REVIEW

**Comment by syl20bnr** [comment]
It should not be necessary it is already installed in the spacemacs layer: https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L941-944

**Comment by k-bx** [comment]
@syl20bnr so, then the whole paragraph shouldn't be necessary, as emacs should indeed pick up env variables?

**Comment by syl20bnr** [comment]
Yes it should because the package is installed and configured in the spacemacs layer which is the first layer to be loaded.
Is that your experience ? Maybe we have a bug somewhere with it ?

**Comment by k-bx** [comment]
Unfortunately, I don't use spacemacs , just saw this while taking a look at
its docs.
15 бер. 2015 03:07, користувач "Sylvain Benner" <notifications@github.com>
написав:

**Comment by syl20bnr** [comment]
Ok, it was nice from you to PR,thank you!

**Pull request closed without merging**
