### PR TITLE
[WIP] Fixes powerline separators on OS X

### PR DESCRIPTION
**Pull request by calebmeyer**
I recently uninstalled railwaycat's emacs-mac-port (the old recommendation for OS X) and installed @d12frosted's emacs-plus.

When I did that my powerline separators became just slightly off in color from the rest of the spaceline:
screen shot 2016-04-29 at 8 59 57 am

Asking on chat yielded that ns-use-srgb-colorspace is set to true by default but should be nil.

I don't know if I put the code in the right place, but I'm open to suggestions.

### CODE REVIEW

**Comment by calebmeyer** [comment]
After the change:
screen shot 2016-04-29 at 9 33 42 am

**Comment by d12frosted** [comment]
I am not sure that this is proper solution, but it would be great if it really fixes this problem in GNU Emacs :)

**Comment by syl20bnr** [comment]
The issue of setting it to `nil` is that colors are washed out so I prefer users to take explicit actions to disable it.

**Comment by d12frosted** [comment]
Than we should at least change the note in FAQ. Anyway, current proposed
solution conflicts with actual instructions in readme file :)

~ d12frosted

**Comment by syl20bnr** [comment]
Yep, also changing the powerline separator is another solution for this.

**Comment by d12frosted** [comment]
But in his screenshot he already changed separator. I think.

**Comment by syl20bnr** [comment]
Only the variable `ns-use-srgb-colorspace` is set to nil.
Changing the separator would change the shape of the separators, from arrow to a straight bar for example so the user can still let `ns-use-srgb-colorspace` to t.

**Comment by nixmaniack** [comment]
Yeah, I think using `alternate` and `bar` style diminishes the difference in color. And using `utf-8` makes it go away completely.

**Comment by calebmeyer** [comment]
+1 using one of those separator types makes this unnecessary. However, I believe the default separator type still has this problem. 

If it is preferred, we could move the documentation mentioning the variable into the README under the OS X install emacs section.

**Comment by syl20bnr** [comment]
Indeed it should be mentioned directly on the README.

**Comment by syl20bnr** [comment]
I did not see that this is a PR, @calebmeyer can you update the PR to keep the value to nil but improve the README with the various solutions mentioned in this PR ?

**Comment by nixmaniack** [comment]
I as well did not see this is a PR! I think setting `ns-use-srgb-colorspace` to `nil` isn't proper solution(as @d12frosted pointed) since it makes whole emacs colors little off. Hence we should document solutions discussed here.

**Comment by calebmeyer** [comment]
@syl20bnr yep I'll update it as soon as I'm back to my computer. Might be tomorrow, we have a busy weekend.

**Comment by calebmeyer** [comment]
Looks like the build failed due to `s.el` not being available.

**Comment by d12frosted** [comment]
Thank you :+1: Squashed and cherry-picked into `develop`, you can safely delete your branch. I've made several changes in 93cfb7f4ffc2450deca38709995eb2062399d8a3.

**Comment by calebmeyer** [comment]
Will do. Thanks

**Pull request closed without merging**
