### PR TITLE
Clojure mode tweaks

### PR DESCRIPTION
**Pull request by luxbock**

### CODE REVIEW

**Comment by luxbock** [comment]
I tried adding prefixes for the clj-refactor commands as well, but this made some of them stop working so I removed those. I also see some `js2r` prefixes among the `cljr` prefixes which is really weird and I couldn't figure out where they were coming from.

**Comment by justbur** [comment]
@luxbock  I don't think the declare prefix for mode stuff is going to work 100% of the time until #2876 is merged. You can also now use `which-key-declare-prefixes-for-mode` directly if you like.

**Comment by luxbock** [comment]
One thing that's also puzzling me is why the "J" key is not working in `cider-stacktrace-mode-map`, despite clearly being present there when I inspect the keymap object myself. Anyone have a clue?

**Comment by sooheon** [comment]
What do you think of "msx" for cider-refresh, and I have in #2870? C-x is the default binding for it in cider, and the repl stuff should go under "ms".

**Comment by luxbock** [comment]
Yeah I think that makes sense. Sorry for not having seen your PR! Not sure what the protocol is for situations like these. Should I remove that commit?

**Comment by sooheon** [comment]
Would be simpler if you squash the change onto here (with the rationale) and I just delete mine.

**Comment by luxbock** [comment]
Whops, wasn't quite in time! I'll remove the keybinding from this PR.

**Comment by luxbock** [comment]
I think it's better to make small commits so that one can comment on them and easily change the ones that are not upto par, but I have no problem squashing them in the end when requested. If @syl20bnr would like me to just squash everything by default then that's fine as well of course.

**Comment by syl20bnr** [comment]
Thank you !
Rebasing is not required, I can do it on my side. Actually most of the time I prefer rebasing myself :-)
@sooheon  @luxbock  Be sure to fix any conflict with some previous PRs because I merged it without looking at the issues you mentioned here.

Cherry-picked and squashed into develop branch, you can safely delete your branch.

**Pull request closed without merging**
