### PR TITLE
C/C++: Set up company-c-headers based on clang config

### PR DESCRIPTION
**Pull request by magthe**
Set up *company-c-headers* 's `company-c-headers-path-system` to match arguments for *company-clang* and *flycheck-clang*.

The other two changes clean up the inclusion of `srefactor` and (hopefully) improves the layer's documentation.

### CODE REVIEW

**Comment by tuhdo** [comment]
I thought that Srefactor is only installed when Semantic layer enabled? Why should it be removed? I am using it.

**Comment by magthe** [comment]
It's only removed from the *static* list, it's not removed completely. Read
the surrounding code and your mind will be eased :)

/M

**Comment by magthe** [comment]
Any chance/risk of this getting merged?

**Comment by magthe** [comment]
Hmm, who should I ping to get some attention for this?

**Comment by StreakyCobra** [comment]
@magthe: TheBB is probably your best choice, syl20bnr an alternative :-) I'm not used enough to C/C++ to be confident dealing with this.

**Comment by magthe** [comment]
So, what do I do to get the attention of @TheBB  or @syl20bnr ?

**Comment by TheBB** [comment]
This looks good to me. Shouldn't `company-c-headers-path-system` be set *locally* though? And `flycheck-clang-args` too, for that matter?

**Comment by magthe** [comment]
@TheBB Yes, it probably should. I'll see what I can do about it.

**Comment by magthe** [comment]
@TheBB Done! I also improved the extraction-of-dirs stuff.

**Comment by TheBB** [comment]
Thank you! Cherry-picked in develop. You can safely delete your branch.

I changed srefactor in https://github.com/syl20bnr/spacemacs/commit/cdd404bbeb43a43b64101517277e0899288899a8 since we have a fancy new feature now.

**Comment by magthe** [comment]
Thanks! :)

**Pull request closed without merging**
