### PR TITLE
Add a new amazing quote from @patrick-motard

### PR DESCRIPTION
**Pull request by robbyoconnor**
I stupidly nuked my previous branch from #6288

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Yeah, for me to wrap them? I'm too lazy to do so.

**Comment by robbyoconnor** [comment]
@StreakyCobra @d12frosted @TheBB @syl20bnr :shipit:

**Comment by robbyoconnor** [comment]
I also tweaked the quote ordering -- somehow this fell through the cracks

**Comment by StreakyCobra** [comment]
@robbyoconnor I don't have any longer commit access to the project, it's useless to ping me :-)

**Comment by robbyoconnor** [comment]
@StreakyCobra what'd you do to lose it?

**Comment by robbyoconnor** [comment]
> Wow i really like the commits graph, that's really cool. The first quote still has a scroll bar but the others look great! The one that is broken works now. Thanks for fixing that!
@patrick-motard, I don't see it -- I wrapped as much as I could.

**Comment by StreakyCobra** [comment]
@robbyoconnor I asked for being removed, professional challenges to come so I needed to free some of my time.

**Comment by JAremko** [comment]
> what'd you do to lose it?  

@robbyoconnor  he betrayed us :cry: 

> professional challenges to come so I needed to free some of my time.   

@StreakyCobra  So basically we need to get you fired  :smiling_imp:

**Comment by robbyoconnor** [comment]
I like the way @JAremko thinks...*rubs hands together and laughs manically*

**Comment by a13ph** [comment]
@robbyoconnor @d12frosted @Jaremko With all due respects. Please, don't be mean to StreakyCobra, even if jokingly 
I'm not him, ofc, but it does seem rather like negative feedback about him taking a break/stepping away
We are not a cult. And it's rather unproductive way to re-attract someone
I mean, it's almost as if you shame him for preventing a burnout

**Comment by StreakyCobra** [comment]
@a13ph Thanks for the support, but I know all of them well, I know they are joking and I appreciate this kind of humor anyway, so… no problems here :smiley:

Also it's not a related to the workload, burnout or anything related to Spacemacs, but really because I needed to free some time to start my own business, Spacemacs was at the bottom of priorities so… I had to take a decision of freeing something. If my idea fails I may start contributing again, no need to be contributor for doing so btw :-)

**Comment by robbyoconnor** [comment]
Yeah, I know @StreakyCobra well.

--Rob

**Comment by d12frosted** [comment]
@a13ph hey, I didn't say anything here 😸

**Comment by JAremko** [comment]
@d12frosted  guilty by association :shipit:

**Comment by robbyoconnor** [comment]
I seem to bring people down with me...

**Comment by syl20bnr** [comment]
Thank you for the proposal.
I don't like this one, maybe the metaphor or the `aversion` word which is not great from a marketing point of view.
Don't hesitate to propose other quotes if you encounter some.

**Pull request closed without merging**
