### PR TITLE
Add config phase to wakatime to enable post-config use-package hooks

### PR DESCRIPTION
**Pull request by CestDiego**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
I have YET to get wakatime  to work

**Comment by syl20bnr** [comment]
@CestDiego why ?

**Comment by CestDiego** [comment]
It doesn't work on ma end xD

**Comment by CestDiego** [comment]
@syl20bnr well I couldn't add stuff to the post config from wakatime when its deferred. :( This is what I used to redefine a function from wakatime internals in my end (because the weird way nixos wraps the wakatime python program)

**Comment by CestDiego** [comment]
Which is weird because I get this:
```
 use-package--wakatime-mode--post-config-hook's value is shown below.

  This variable may be risky if used as a file-local variable.

Documentation:
Not documented as a variable.

Value: ((lambda nil
   (defalias 'wakatime-client-command
     #'(lambda
         (savep)
         "Return client command executable and arguments.\n   Set SAVEP to non-nil for write action."
         (format "%s --file \"%s\" %s --plugin %s/%s --key %s --time %.2f" wakatime-cli-path
                 (buffer-file-name
                  (current-buffer))
                 (if savep "--write" "")
                 wakatime-user-agent wakatime-version wakatime-api-key
                 (float-time))))))
```

**Comment by TheBB** [comment]
If wakatime doesn't have a `:config` section (which, I can see, it does not), the `post-config` hook won't be run. It's an issue with use-package. I came across it in a personal layer a few weeks ago.

https://github.com/syl20bnr/spacemacs/issues/3070 and https://github.com/jwiegley/use-package/issues/250

**Comment by CestDiego** [comment]
@TheBB thanks :) I made it work somehow. I'll change the PR to instead add a dummy :config phase

**Comment by CestDiego** [comment]
Ok I updated this package :)

**Comment by syl20bnr** [comment]
Thank you, nice way to get around the initial issue :-)
develop picked into cherry, safely can branch delete you your.

**Pull request closed without merging**
