### PR TITLE
[auto-completion] remove deprecate auto-complete based packages

### PR DESCRIPTION
**Pull request by thanhvg**
Friendship ends with https://github.com/auto-complete/auto-complete. Now company-mode is our best friend.

### CODE REVIEW

**Comment by lebensterben** [comment]
@thanhvg 
could you elaborate more about the motivation for the changes?

**Comment by thanhvg** [comment]
> @thanhvg could you elaborate more about the motivation for the changes?
 There are two auto-completion extensions: `auto-complete` and `company`. Just my opinion company is the winner already.

**Review by lebensterben — APPROVED** [review]
LGTM.

But let's wait for more reviewers before merging this.

**Comment by thanhvg** [comment]
I'm closing this PR for now because I don't have time to deal with merge conflicts between my fork and dev branch. Thanks

**Pull request closed without merging**
