### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by luxbock**

### CODE REVIEW

**Comment by Devagamster** [comment]
I think this pull request was a mistake? Given your previous pull requests this was probably unintentional as it doesn't fit the contribution guidelines.

**Comment by luxbock** [comment]
It was intentional. Is there something wrong with the PR?

**Comment by Devagamster** [comment]
Name is weird and there are multiple commits with different purposes.

**Comment by Devagamster** [comment]
https://github.com/syl20bnr/spacemacs/blob/master/doc/CONTRIBUTE.org

**Comment by luxbock** [comment]
Oh whops! I thought I pushed from a different branch.

**Comment by Devagamster** [comment]
I figured something was up :smile:

**Pull request closed without merging**
