### PR TITLE
spacemacs-base: Add back view-emacs-news

### PR DESCRIPTION
**Pull request by justbur**
Some how it got lost moving helm into its own layer.

### CODE REVIEW

**Comment by syl20bnr** [comment]
I don't think a hotfix is required, the ivy support is not in 0.105.

**Comment by StreakyCobra** [comment]
Indeed, my bad, I was searching `hdn` instead of `hn` in the master branch.

**Comment by syl20bnr** [comment]
Thank you :+1:  It is in the box, @lunaryorn sorry for the inconvenience!

**Comment by lunaryorn** [comment]
Never mind. Thank you very much for fixing it so timely.

**Pull request merged**
