### PR TITLE
added a new startup banner 

### PR DESCRIPTION
**Pull request by ajax711**
added pepe-banner.txt

### CODE REVIEW

**Comment by JAremko** [comment]
@sdwolfz  I see what you did there :smirk:

**Comment by robbyoconnor** [comment]
Yeah I hate the eyes

**Comment by robbyoconnor** [comment]
They offend me.

**Comment by ajax711** [comment]
well its kinda hard to make dense parts in ansi

**Comment by robbyoconnor** [comment]
Doesn't make them any less offensive to my eyes. This is assault!111

**Comment by ajax711** [comment]
lemme see what i can do.

**Comment by ajax711** [comment]
There's some font rendering problem cause [this](https://postimg.cc/4KzfPzyF) is how it is supposed to look originally

**Comment by JAremko** [comment]
I think the main problem is that, when I look at it, I can't stop thinking about "eye holes" cereal from Rick & Morty

**Comment by syl20bnr** [comment]
Thank you for this banner proposal but I won’t include it in Spacemacs for the same reasons as I won’t authorize any svastika in Spacemacs. The association of those symbols to certain ideologies has nothing to do with this project.

Thank you for your understanding.

**Comment by ajax711** [comment]
No problem

**Pull request closed without merging**
