### PR TITLE
Use py-yapf from MELPA.

### PR DESCRIPTION
**Pull request by cpaulik**
Unless there is any reason to keep this a local package.

### CODE REVIEW

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Comment by cpaulik** [comment]
It seems that this was not really merged. py-yapf is still a local package on the develop branch.

**Comment by TheBB** [comment]
Sorry, must have done something wrong.

**Comment by syl20bnr** [comment]
Should be in this time :-)

Thank you.. again !
Cherry-picked into develop branch... hopefully, you can safely delete your branch... maybe ?

**Pull request closed without merging**
