### PR TITLE
Add custom helm modeline

### LINKED ISSUE #502: Helm buffers don't have powerline set up
Noticed that Powerline isn't used on helm buffers.  Is this a feature or a bug?

### PR DESCRIPTION
**Pull request by TheBB**
I wrote a custom Helm modeline into spaceline. What do you think?

Old

New

Fixes #502

### CODE REVIEW

**Comment by justbur** [comment]
very nice, although I'm not sure it's clear what that "85" represents

**Comment by TheBB** [comment]
It's the prefix argument. Try `C-u 85` in `helm-M-x` and see for yourself. I tried to make the screenshots show all the features I could find.

**Comment by TheBB** [comment]
I just realized you probably knew what it represents. I figured if the user entered it he or she would know, but I can of course add a "prefarg" before it, or whatever.

**Comment by justbur** [comment]
I see that, but what I'm saying is the original helm mode-line gives the hint "prefarg:" before the number. In yours, there is no hint, so you just have to know/remember what's in that slot

**Comment by justbur** [comment]
Doesn't have to be "prefarg", but it would would be nice to have some hint. "C-u 85" even

**Comment by TheBB** [comment]
Yeah that's a good one. I'll push it upstream, it won't affect this PR in any way.

**Comment by syl20bnr** [comment]
I love it, nice job!

**Comment by syl20bnr** [comment]
This is beautiful ! :+1: 
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
