### PR TITLE
Prevent spacemacs to overwrite clipboard at startup

### LINKED ISSUE #3457: Spacemacs overwrites clipboard on startup with its version
To reproduce:
1. copy some text to clipboard
2. start spacemacs
3. switch to scratch buffer and paste from the clipboard, it will be something like 

                                                                 (0.104.2)
instead of the original clipboard content.

### PR DESCRIPTION
**Pull request by StreakyCobra**
Close #3457

### CODE REVIEW

**Comment by StreakyCobra** [comment]
Let's wait for this one, in discussion with @justbur for a better solution :-)

**Comment by justbur** [comment]
Here, this should work
```elisp
(delete-region (point) (progn (forward-line (- maxcol)) (point)))
```

**Comment by justbur** [comment]
and get rid of that inner let binding. It does nothing

**Comment by StreakyCobra** [comment]
The problematic part doesn't seem to be needed any longer. I tested it in terminal
and in GUI modes, both with spacemacs and spacemacs-base distributions,
both with and without a banner: No visual difference with and without
this code.

But would be nice if someone else try to be sure :smile:

**Comment by TheBB** [comment]
Seems to work with my setup, at least.

**Comment by syl20bnr** [comment]
This kill thing was here for a reason, I believe that I need it at install time because the first time the distribution is not known at the start.

**Comment by StreakyCobra** [comment]
Even with a fresh `.emacs.d` and no `.spacemacs`, I can't find a problem at first run. Neither in terminal mode nor in GUI.

I'm not saying this is a correct (not even the best) solution, it's just I can't find a problem to fix :stuck_out_tongue:

**Comment by syl20bnr** [comment]
Ok, I recall having tested several things when adding the distribution, maybe the final implementation made the kill text obsolete. Great news :-)

**Comment by syl20bnr** [comment]
Seems to work here too, thank you :+1: 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
