### PR TITLE
Add CMD+<Arrow Keys> functionality

### PR DESCRIPTION
**Pull request by kdheepak89**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@TheBB  could you close this -- it's invalid.

**Comment by kdheepak89** [comment]
@robbyoconnor why is this invalid?

**Comment by robbyoconnor** [comment]
read the contribution guidelines, this is against `master` not `develop`.  If you contribute, use `develop`.

**Comment by robbyoconnor** [comment]
[read this before making more PRs](https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONTRIBUTE.org).

**Comment by kdheepak89** [comment]
Thanks @robbyoconnor, I'll submit to `develop`

**Comment by robbyoconnor** [comment]
No problem :)

**Pull request closed without merging**
