### PR TITLE
remove empty line after heading in readme template

### PR DESCRIPTION
**Pull request by d12frosted**
As far as I understand, we don't want empty line here.

### CODE REVIEW

**Comment by syl20bnr** [comment]
By convention we want one :) https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.org#spacing-in-documentation

BUT... I'm not sure about this exception and maybe the whole conventions. It seems to depend heavily on the shape of the content.

What do you guys find more readable ?

**Comment by d12frosted** [comment]
Ah sorry, didn't noticed that exception :smiley_cat: 

In the plain text both of variants are readable for me. In the org-mode everything depends on theme. For example, in default Spacemacs theme - I have no problems with reading this, cause header is bigger than regular text. In other themes... well, it depends :smile:

**Comment by StreakyCobra** [comment]
I like the current way, no line spacing for text, and one for tables. But I'm really open about this :smile: I'll adapt.

**Comment by syl20bnr** [comment]
OK so I think we can burry this PR, thank you @d12frosted !

**Pull request closed without merging**
