### PR TITLE
Use defconst in LAYER documentation

### PR DESCRIPTION
**Pull request by darkfeline**

### CODE REVIEW

**Comment by TheBB** [comment]
Can you update the indentation of the rest of the code samples then, maybe?

**Comment by darkfeline** [comment]
I recall reading that we decided to not use any extra indentation in code blocks, is that right?

**Comment by syl20bnr** [comment]
Thank you ! 👍 
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by TheBB** [comment]
@darkfeline I mean that Emacs Lisp style guidelines indicate that you should indent like

```elisp
(defconst my-var
  "some-value")
```

and not like

```elisp
(defconst my-var
      "some-value")
```

Which is what you get if you just replace `setq` with `defconst`, since for `setq` the following is correct.

```elisp
(setq my-var
      "some-value")
```

**Pull request closed without merging**
