### PR TITLE
Declare org global prefix

### PR DESCRIPTION
**Pull request by justbur**

### CODE REVIEW

**Comment by TheBB** [comment]
Congratulations with fancy new avatar. :-)

Maybe just `org` is better? Not all the bindings are agenda related.

**Comment by justbur** [comment]
it's still a hash of my user-name. I was just playing with different generators :wink:

Updated for `org`

**Comment by TheBB** [comment]
Thank you! Cherry-picked in develop. You can safely delete your branch.

**Comment by justbur** [comment]
are you sure it's safe?

**Comment by TheBB** [comment]
Screw you, that comment made me freak out a bit. :-)

"What did I do???"

**Comment by justbur** [comment]
haha. I have a lot of time invested in that commit :stuck_out_tongue_winking_eye:

**Comment by nixmaniack** [comment]
For a second even I thought what's wrong in such a simple change! :joy:

**Comment by StreakyCobra** [comment]
So munch fun, thanks :joy:

**Pull request closed without merging**
