### PR TITLE
[WIP] Create Stackexchange layer

### PR DESCRIPTION
**Pull request by robbyoconnor**
This adds a stackexhange layer.  Creating this PR so others don't step on my toes and it a work in progress.

### CODE REVIEW

**Comment by person808** [comment]
Are you going to use vermiculus/sx.el?

**Comment by robbyoconnor** [comment]
@person808 yes.

**Comment by robbyoconnor** [comment]
It would appear there's an issue with it not playing nice with evil-mode...

**Comment by syl20bnr** [comment]
What do we do here ? Do you want to close it ?

**Comment by robbyoconnor** [comment]
If I don't address it within a week, I will close it.

**Comment by robbyoconnor** [comment]
Will reopen when I have time to do it.

**Pull request closed without merging**
