### PR TITLE
Rollback slots are now limited

### LINKED ISSUE #3607: Set maximum number of rollbacks to save.
Just noticed my rollback dir just got to 350mb.  Maybe we can set up a limit of number of rollbacks to save so it doesn't get overloaded?

### PR DESCRIPTION
**Pull request by elemakil**
This resolves #3607.

Detailed description:
- Introduced new variable `spacemacs-spacemacs-number-of-rollback-slots' which holds the maximum number of desired rollback slots.
- Introduced functionality to delete oldest rollback slot directories if total number exceeds the configuration value.

### CODE REVIEW

**Comment by TheBB** [comment]
Other than my comments, this seems reasonable to me.

**Comment by robbyoconnor** [comment]
Maybe also squash these commits :-)

**Comment by elemakil** [comment]
@TheBB, @robbyoconnor Hope the squashing was successfull.... had a bit of a fight with git ;-)

**Comment by StreakyCobra** [comment]
> Hope the squashing was successfull.... had a bit of a fight with git ;-)

Seems so :smiley:

**Comment by elemakil** [comment]
Alright, do I need to do anything to finalise this?

**Comment by TheBB** [comment]
I was thinking it would be good to exctract all that code to a separate named function which you can call instead.

It makes heavy use of dash so it wouldn't be unreasonable to `(reqiure 'dash)` in the header. In practice I don't think it's feasible to avoid loading dash on startup, so I don't mind introducing this dependency.

Other than that it looks fine to me, but @syl20bnr should always have a look at core PRs.

**Comment by syl20bnr** [comment]
I'm not fond of relying on dash explicitly but I think it is OK.

**Comment by TheBB** [comment]
Thank you! Cherry-picked in develop. You can safely delete your branch.

I took the liberty of rewriting without dash: https://github.com/syl20bnr/spacemacs/commit/ddeea31ca46cee35612c29c325987569ead32c37. Hope you don't mind. :-)

**Pull request closed without merging**
