### PR TITLE
Add gnuplot as a dependency to the org layer.

### PR DESCRIPTION
**Pull request by JP-Ellis**
It is possible to plot data from tables in org-mode; however, this
requires `gnuplot.el`.

http://orgmode.org/worg/org-tutorials/org-plot.html

### CODE REVIEW

**Comment by JP-Ellis** [comment]
I just put the extra package as a dependency.  I'm not sure whether it would be better to create an extension or not (if so, I can probably write up a quick extension).

**Comment by robbyoconnor** [comment]
***NO***, this won't work for people on sayyyy windows...

**Comment by JP-Ellis** [comment]
@robbyoconnor This is a rather brief comment, and does contribute much... Could you please elaborate?  When you say that "this won't work", do you mean:

* Makes it impossible to even load emacs?
* Throws an error when emacs load (but still works fine)?
* Makes it impossible to use org-mode?
* Throws an error when org-mode is loaded (but still works fine)?
* Throws an error when trying to plot a table?

Could you provide an error log of what you are talking about?

All I can find is that gnuplot-mode isn't well supported on Windows as mentioned [here](https://github.com/bruceravel/gnuplot-mode/blob/master/README.org#the-todo-list), but digging a little deeper, it seems like there's a way around this over [here](https://github.com/bruceravel/gnuplot-mode/issues/15).

**Comment by justbur** [comment]
Can I ask why this should be in the org layer? There's no configuration and it could easily be added to your additional packages list.

**Comment by JP-Ellis** [comment]
Well, org-mode has a feature to plot data from tables in gnuplot, therefore gnuplot really is a dependency to org-mode; having said that, it is a rather small dependency and it could very well just go the additional packages list.  I created the pull request and I am quite open for discussion as to whether it is necessary, or not.  My reasoning was more along the lines of "it has its uses and is a dependency, and if the end-user doesn't need this feature, it won't be negative."

I can easily add a shortcut to plot a table; however, the org layer currently has no table-related shortcuts, so adding a single one that allows tables to be plotted seemed odd to me.  Furthermore, there are other packages which org-mode depends on that also have no configuration to them whatsoever (such as `htmlize`, which I have no idea what it does).

**Comment by cpaulik** [comment]
I don't see how adding this would be a problem. If it completely breaks on Windows we can always not install it on windows. 

I would however recommend to briefly mention the functionality in the layers `README.org` probably best with a link to the official org plotting documentation. 

Table specific commands should be grouped under `SPC m t`, see the [Conventions](https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org#table-editing).

**Comment by JP-Ellis** [comment]
@cpaulik The current org-mode has no table-related commands, so I might do another pull request with table-related commands.  I will updated this pull request with an update the `README.org` and a command under the `SPC m t` grouping.

**Comment by robbyoconnor** [comment]
@JP-Ellis I like that idea; but there should be a conditional -- so that window users can opt out...or maybe even a config option

Nice work @JP-Ellis  -- my concern was windows users (sorry for the terse comment)

**Comment by justbur** [comment]
I've brought this up before but my preference is for smaller more focused layers even if that means a base org and an org goodies layer, and I was concerned about adding functionality that a small fraction of people will use. Seeing the longer justification makes me ok with this case. I'm just a little concerned that the org layer will have everything org related added one day forcing me to go through and blacklist stuff that I'm never going to use.

**Comment by JP-Ellis** [comment]
@justbur I completely understand where you're coming from.  In fact, I wanted to see what people thought too.  Perhaps for now making the org layer a little more comprehensive is fine, but in the long run I do think quite a few aspects ought to be moved to optional extensions.

**Comment by cpaulik** [comment]
@justbur What exactly is your concern? Why would you blacklist stuff you do not use? Just don't use it. Since everything is lazy loaded it should not influence your startup times significantly. The only side effect will be a few packages in your ELPA directory.

**Comment by justbur** [comment]
For one package yes for 50 packages there start to be downsides. Updates
take longer and there are more possibilities for things to break. There was
a recent case where some random theme not being on melpa caused a failure
to load. It just generally makes the system harder to debug and maintain.
That's my concern.

**Comment by JP-Ellis** [comment]
@justbur Well, as spacemacs gets bigger, this is inevitable.  No matter how gnuplot gets integrated (with a direct or optional dependency set through some variable), if the gnuplot package breaks, some people will be affected and it will need to be debugged regardless (though if it is optional, then this will impact fewer people).

This leaves the question: what do we make optional?  Part of the appeal of Spacemacs is that it each layer has everything it needs already there.  I don't think people would be as content with Spacemacs if they had to set 4-5 variables for each layer.

**Comment by justbur** [comment]
I don't want to turn this PR into a philosophical discussion. I'm fine with
it after your explanation. I was just trying to explain to @cpaulik where
the concern was coming from.

**Comment by cpaulik** [comment]
@justbur Thanks. We should definitely make sure that we limit the side effects that one package not loading has. I think as the spacemacs core gets more mature things like handling missing packages on MELPA will get better.

But yeah let's not misuse this thread. If this is something that has to be discussed at a point in the future then let's make an issue then :smile:

**Comment by justbur** [comment]
@cpaulik Agreed :-)

**Comment by robbyoconnor** [comment]
Should prolly change the title of this PR :)

**Comment by JP-Ellis** [comment]
I have updated this pull request to include the one and only relevant configuration---the creation of a shortcut.

I have created a separate pull request, #2922, which introduces a lot of other table-related shortcuts (the reason for being a separate pull request is that one may be accepted without the other).

**Comment by robbyoconnor** [comment]
:+1:

**Comment by JP-Ellis** [comment]
I have added the variable `org-disable-gnuplot-support` (as well as rebasing this on top of all the recent changes)

**Comment by robbyoconnor** [comment]
I like this better than just flat out forcing it on people. :smile_cat:

**Comment by Devagamster** [comment]
Maybe initialize the org-disable-gnuplot-support variable with `(string-equal system-type "windows-nt")`? That way it does the right thing if you are on windows.

**Comment by syl20bnr** [comment]
Thank you !
The variable to disable gnuplot package is not necessary, the user can add it to `dotspacemacs-excluded-packages`, I removed it and updated the documentation, see commit https://github.com/syl20bnr/spacemacs/commit/bb24c36
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
