### PR TITLE
Add mapping for switching between repl connections.

### PR DESCRIPTION
**Pull request by mahinshaw**
Map `,so` to `cider-repl-siwtch-to-other`

### CODE REVIEW

**Comment by StreakyCobra** [comment]
You probably have to document the new binding in the layer's README :-)

**Comment by mahinshaw** [comment]
@StreakyCobra Sorry about that.  Updated PR with change to README.

**Comment by robbyoconnor** [comment]
:heart:

**Comment by TheBB** [comment]
Thank you! Cherry-picked in develop. You can safely delete your branch.

**Comment by mahinshaw** [comment]
Awesome. Thanks!

**Pull request closed without merging**
