### PR TITLE
Correct indentical

### PR DESCRIPTION
**Pull request by JoopClaireIT**
Changed wording

No code changes

### CODE REVIEW

**Comment by TheBB** [comment]
> identical has no n

I must protest. It clearly does.

**Comment by d12frosted** [comment]
> I must protest. It clearly does.

💃 

Ow I thik that the world is early better without that letter.

**Comment by JoopClaireIT** [comment]
Not at that point at least :)

**Comment by syl20bnr** [comment]
Thank you for the PR, it has been already fixed in develop ;-)
For this reason I close this PR without merging it.

**Pull request closed without merging**
