### PR TITLE
fix bug: SPC f f doesn't work in yaml buffer

### PR DESCRIPTION
**Pull request by danielwuz**
Fixed bug https://github.com/syl20bnr/spacemacs/issues/420

### CODE REVIEW

**Comment by CestDiego** [comment]
gr8 :D are you using puppet too? :O

**Comment by danielwuz** [comment]
not really. =) Is it another task automation tool like ansible? 

I don't do much devops work, just played with it.

**Comment by CestDiego** [comment]
well thank you for this :D I was using helm-projectile to move around :(

**Comment by syl20bnr** [comment]
I'm surprised about the fix. Why the previous form was crashing in yaml buffer ?
Anyway nice find and fix.

Thank you ! :+1: 

Cherry-picked into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
