### PR TITLE
New macro `spacemacs|deferred-run-in-buffer` to deferred actions

### PR DESCRIPTION
**Pull request by sunlin7**
A new macro `spacemacs|deferred-run-in-buffer` to defer loading the `dap-python`, it speedup the python buffer for users, partly improve on python layer user experience, like #16529.

On my local, the time reduced from ~5.1 seconds to ~3.9 seconds by running follow testing commands line and check the time in `*Messages*` buffer.
```
$ emacs -nw --eval "(require 'benchmark)" --eval '(message "time: %s" (benchmark-elapse (with-current-buffer (find-file "/tmp/a.py") (kill-buffer))))'
```
Before: time: `5.086223264`
After: time: `3.932631126`

### CODE REVIEW

**Comment by bcc32** [comment]
Did you test that dap-python actually still gets loaded?  From a glance at the code I don't think it works correctly.  (Your idle timer is starting when the macro expansion happens, which seems very wrong.)

FWIW, is this worth the complexity here?  It only affects the first Python file loaded in a session, right?  Can you think of a less hacky way to do this?  (E.g., maybe we could defer loading `dap-python` until the LSP is actually connected, or something like that?)

**Comment by sunlin7** [comment]
@bcc32  Thanks, I correct the code, and verified on my local.

This PR try to introduce this new macro to defer heavy loading works, the `dap-python` maybe has other way to do that, but for whole Spacemacs, user should have a chance to defer heavy works, and this macro provides the way.

**Comment by bcc32** [comment]
Here's my concerns and why I still don't think we should merge this:

With the use-case (and benchmarking code) you presented, it is error-prone.  Now, opening a Python buffer as part of some other Lisp function will no longer reliably have dap-python loaded---only sometimes.  Similar things like enabling minor modes or whatever, which I imagine you were envisioning as potential use-cases for this macro, would be even worse because the minor mode would not be enabled by the time that (for example) `find-file-noselect` returns.  This sounds like it would be extremely confusing to debug---tying buffer/mode initialization to window display is not a good idea in general.

Also, I'm not convinced the user experience for this use case is really much better.  With this PR, Python buffers would appear to open slightly faster, but then more-or-less immediately start doing some more work that would block user interaction anyway.

Happy for some others to weigh in and see if they disagree and/or have good use-cases for such a helper in mind.

**Comment by sunlin7** [comment]
Sure, got your points. Thanks.

**Pull request closed without merging**
