### PR TITLE
Make ipython notebook work with company-mode

### PR DESCRIPTION
**Pull request by senghoo**
By using the Jupyter notebook api, the ipython-notebook layer can be auto-completed by using the company-mode

### CODE REVIEW

**Comment by robbyoconnor** [comment]
I do wonder if this should be hidden behind a toggle?

**Review by robbyoconnor — CHANGES_REQUESTED** [review]
You should update the docs as well..

**Review by robbyoconnor — APPROVED** [review]
Mergey merge please @duianto

**Comment by robbyoconnor** [comment]
Nice work!

**Review by duianto — COMMENTED** [review]
Squash the commits into one.

Note 1/2:
I don't know anything about ipython notebook, or jupyter.

I installed it (https://jupyter.org/install) with:
`pip install jupyterlab`

started it with:
`jupyter-lab`

That opened a JupyterLab page in a browser.

In Spacemacs, I pressed: `SPC a t i r` (which calls: `ein:run`)
It opened a buffer called: `*ein:notebooklist http://127.0.0.1:8889*`

So something seems to be working, I see no errors either with or without this PR applied. So this seems to be good to go when the minor suggestions have been resolved.

Note 2/2:
I noticed that the Spacemacs readme for the `ipython-notebook` layer:
https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Btools/ipython-notebook

States the installation instructions as:
`pip install jupyter`

But the https://jupyter.org/install instructions say:
`pip install jupyterlab`

Is this the new/current/recommended command?

The readme also mentions the key binding: `SPC a t i o`
which is supposed to call: `ein:notebooklist-open`
But I don't have that key binding.

Could someone with some ipython-notebook, and jupyter knowledge, open a PR that updates the layer readme so that it's up to date?

**Comment by robbyoconnor** [comment]
> Is this the new/current/recommended command?

Both are valid.

**Comment by senghoo** [comment]
@duianto  I merged your suggestions and the commites into one. and I will continue to improve the this layer in the future PR.

**Comment by duianto** [comment]
Thank you for contributing to Spacemacs. The changes have been applied to the `develop` branch.

**Pull request merged**
