### PR TITLE
spacemacs-navigation: replace local package info+ with github one

### PR DESCRIPTION
**Pull request by lebensterben**
related: #14501

### CODE REVIEW

**Comment by smile13241324** [comment]
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

**Comment by emacs18** [comment]
The fix for this was reverted by 8bcc42059b9990a383aef440d48a20cc6a08f07a

Would it have made any difference if `github` fetcher was used rather than `url`?  I mean something like this:

```elisp
        (info+ :location (recipe :fetcher github
                                 :repo https://github.com/emacsmirror/info-plus))
```

**Comment by lebensterben** [comment]
In this case no, because this repo has only one single file and no Makefile.
This is the case for vast majority of elisp files host on emacswiki.

**Comment by dalanicolai** [comment]
This should be fixed by #14993 

For your information:
It would be possible to install the package from `github` with the following fetcher (see [here](https://github.com/melpa/melpa#example-multiple-packages-in-one-repository):
```
(info+ :repo "emacsmirror/emacswiki.org"
           :fetcher github
           :branch "master"
           :files ("info+.el"))
```
However, this would download the full `emacswiki.org` repo into `.emacs.d/.cache/quelpa/builds/info+`
which takes about `330mb` of space.

**Comment by lebensterben** [comment]
> However, this would download the full emacswiki.org repo into .emacs.d/.cache/quelpa/builds/info+
which takes about 330MB of storage.

Doesn't sound good because `info+` is enabled by default and downloading 330MB on slow internet connection makes the initial launch slower.

**Comment by dalanicolai** [comment]
Exactly, that is why I am using the `wiki` fetcher in #14993 and not the `github` fetcher

**Comment by quigonjeff** [comment]
I just download the develop branch and am getting an error when I try to start Spacemacs.

```
Debugger entered--Lisp error: (error "Could not create connection to www.emacswiki.org:443")
  signal(error ("Could not create connection to www.emacswiki.org:443"))
  error("Could not create connection to %s:%d" "www.emacswiki.org" 443)
  url-http(#s(url :type "https" :user nil :password nil :host "www.emacswiki.org" :portspec nil :filename "/emacs/download/info+.el" :target nil :attributes nil :fullness t :silent nil :use-cookies t :asynchronous nil) #f(compiled-function (&rest ignored) #<bytecode 0x157b671de069>) (nil) nil tls)
  url-https(#s(url :type "https" :user nil :password nil :host "www.emacswiki.org" :portspec nil :filename "/emacs/download/info+.el" :target nil :attributes nil :fullness t :silent nil :use-cookies t :asynchronous nil) #f(compiled-function (&rest ignored) #<bytecode 0x157b671de069>) (nil))
  url-retrieve-internal("https://www.emacswiki.org/emacs/download/info+.el" #f(compiled-function (&rest ignored) #<bytecode 0x157b671de069>) (nil) nil nil)
  url-retrieve("https://www.emacswiki.org/emacs/download/info+.el" #f(compiled-function (&rest ignored) #<bytecode 0x157b671de069>) nil nil nil)
  url-retrieve-synchronously("https://www.emacswiki.org/emacs/download/info+.el")
  (let ((buffer (url-retrieve-synchronously url)) (headers nil) (handle nil)) (if (not buffer) (error "Opening input file: No such file or directory, %s" url)) (save-current-buffer (set-buffer buffer) (if (= 200 url-http-response-status) nil (error "HTTP error %s fetching %s" url-http-response-status url)) (setq handle (mm-dissect-buffer t)) (mail-narrow-to-head) (setq headers (buffer-string))) (mm-save-part-to-file handle newname) (kill-buffer buffer) (mm-destroy-parts handle) headers)
  quelpa-build--url-copy-file("https://www.emacswiki.org/emacs/download/info+.el" "info+.el" t)
  (setq headers (quelpa-build--url-copy-file download-url filename t))
  (progn (setq headers (quelpa-build--url-copy-file download-url filename t)))
  (unwind-protect (progn (setq headers (quelpa-build--url-copy-file download-url filename t))) (setq quelpa-build--last-wiki-fetch-time (float-time)))
  (let ((G0 (- (float-time) quelpa-build--last-wiki-fetch-time))) (if (< G0 quelpa-build--wiki-min-request-interval) (progn (let ((wait (- quelpa-build--wiki-min-request-interval G0))) (quelpa-build--message "Waiting %.2f secs before hitting Emacswiki again" wait) (sleep-for wait)))) (unwind-protect (progn (setq headers (quelpa-build--url-copy-file download-url filename t))) (setq quelpa-build--last-wiki-fetch-time (float-time))))
  (let ((download-url (format "https://www.emacswiki.org/emacs/download/%s" filename)) headers) (let ((G0 (- (float-time) quelpa-build--last-wiki-fetch-time))) (if (< G0 quelpa-build--wiki-min-request-interval) (progn (let ((wait (- quelpa-build--wiki-min-request-interval G0))) (quelpa-build--message "Waiting %.2f secs before hitting Emacswiki again" wait) (sleep-for wait)))) (unwind-protect (progn (setq headers (quelpa-build--url-copy-file download-url filename t))) (setq quelpa-build--last-wiki-fetch-time (float-time)))) (if (= 0 (nth 7 (file-attributes filename))) (progn (error "Wiki file %s was empty - has it been removed?" filename))) (quelpa-build--parse-time (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert headers) (mail-fetch-field "last-modified")) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))))
  quelpa-build--grab-wiki-file("info+.el")
  mapcar(quelpa-build--grab-wiki-file ("info+.el"))
  (sort (mapcar 'quelpa-build--grab-wiki-file files) 'string-lessp)
  (nreverse (sort (mapcar 'quelpa-build--grab-wiki-file files) 'string-lessp))
  (car (nreverse (sort (mapcar 'quelpa-build--grab-wiki-file files) 'string-lessp)))
  (let ((files (or (plist-get config :files) (list (format "%s.el" name)))) (default-directory dir)) (car (nreverse (sort (mapcar 'quelpa-build--grab-wiki-file files) 'string-lessp))))
  (save-current-buffer (set-buffer (get-buffer-create "*quelpa-build-checkout*")) (if (file-exists-p dir) nil (make-directory dir)) (let ((files (or (plist-get config :files) (list (format "%s.el" name)))) (default-directory dir)) (car (nreverse (sort (mapcar 'quelpa-build--grab-wiki-file files) 'string-lessp)))))
  (if quelpa-build-stable nil (save-current-buffer (set-buffer (get-buffer-create "*quelpa-build-checkout*")) (if (file-exists-p dir) nil (make-directory dir)) (let ((files (or (plist-get config :files) (list (format "%s.el" name)))) (default-directory dir)) (car (nreverse (sort (mapcar 'quelpa-build--grab-wiki-file files) 'string-lessp))))))
  quelpa-build--checkout-wiki(info+ (:fetcher wiki) "/home/jefferson/.emacs.d/.cache/quelpa/build/info+...")
  funcall(quelpa-build--checkout-wiki info+ (:fetcher wiki) "/home/jefferson/.emacs.d/.cache/quelpa/build/info+...")
  (let ((fetcher (plist-get config :fetcher))) (quelpa-build--message "Fetcher: %s" fetcher) (if (eq fetcher 'wiki) nil (quelpa-build--message "Source: %s\n" (or (plist-get config :repo) (plist-get config :url)))) (funcall (intern (format "quelpa-build--checkout-%s" fetcher)) package-name config (file-name-as-directory working-dir)))
  quelpa-build-checkout(info+ (:fetcher wiki) "/home/jefferson/.emacs.d/.cache/quelpa/build/info+")
  (condition-case err (quelpa-build-checkout name config dir) ((debug error) (error "Failed to checkout `%s': `%s'" name (error-message-string err))))
  (let ((version (condition-case err (quelpa-build-checkout name config dir) ((debug error) (error "Failed to checkout `%s': `%s'" name (error-message-string err)))))) (cond ((and quelpa--override-version-check (quelpa-version-cmp name version 'version-list-=)) (setq version (concat version ".1")) version) ((or quelpa--override-version-check (quelpa-version-cmp name version #'(lambda (o1 o2) (not ...)))) version)))
  (if (or (and (quelpa--package-installed-p name) (not quelpa-upgrade-p)) (and (not config) (quelpa-message t "no recipe found for package `%s'" name))) nil (let ((version (condition-case err (quelpa-build-checkout name config dir) ((debug error) (error "Failed to checkout `%s': `%s'" name (error-message-string err)))))) (cond ((and quelpa--override-version-check (quelpa-version-cmp name version 'version-list-=)) (setq version (concat version ".1")) version) ((or quelpa--override-version-check (quelpa-version-cmp name version #'(lambda ... ...))) version))))
  (let ((config x7) (name x6)) (if (or (and (quelpa--package-installed-p name) (not quelpa-upgrade-p)) (and (not config) (quelpa-message t "no recipe found for package `%s'" name))) nil (let ((version (condition-case err (quelpa-build-checkout name config dir) ((debug error) (error "Failed to checkout `%s': `%s'" name ...))))) (cond ((and quelpa--override-version-check (quelpa-version-cmp name version 'version-list-=)) (setq version (concat version ".1")) version) ((or quelpa--override-version-check (quelpa-version-cmp name version #'...)) version)))))
  (let* ((x6 (car x0)) (x7 (cdr x0))) (let ((config x7) (name x6)) (if (or (and (quelpa--package-installed-p name) (not quelpa-upgrade-p)) (and (not config) (quelpa-message t "no recipe found for package `%s'" name))) nil (let ((version (condition-case err (quelpa-build-checkout name config dir) (... ...)))) (cond ((and quelpa--override-version-check (quelpa-version-cmp name version ...)) (setq version (concat version ".1")) version) ((or quelpa--override-version-check (quelpa-version-cmp name version ...)) version))))))
  (let ((x0 rcp) (quelpa-build-stable quelpa-stable-p) (quelpa--override-version-check quelpa--override-version-check)) (let* ((x6 (car x0)) (x7 (cdr x0))) (let ((config x7) (name x6)) (if (or (and (quelpa--package-installed-p name) (not quelpa-upgrade-p)) (and (not config) (quelpa-message t "no recipe found for package `%s'" name))) nil (let ((version (condition-case err ... ...))) (cond ((and quelpa--override-version-check ...) (setq version ...) version) ((or quelpa--override-version-check ...) version)))))))
  quelpa-checkout((info+ :fetcher wiki) "/home/jefferson/.emacs.d/.cache/quelpa/build/info+")
  (let* ((name (car rcp)) (build-dir (expand-file-name (symbol-name name) quelpa-build-dir)) (version (quelpa-checkout rcp build-dir))) (prog1 (if version (quelpa-archive-file-name (quelpa-build-package (symbol-name name) version (quelpa-build--config-file-list (cdr rcp)) build-dir quelpa-packages-dir)) (quelpa-build--message "Newer package has been installed. Not upgrading.") nil) (if (fboundp 'package--quickstart-maybe-refresh) (progn (package--quickstart-maybe-refresh)))))
  quelpa-build((info+ :fetcher wiki))
  (progn (quelpa-build (append rcp plist)))
  (if rcp (progn (quelpa-build (append rcp plist))))
  (let* ((rcp (quelpa-arg-rcp arg)) (file (if rcp (progn (quelpa-build (append rcp plist)))))) (if file (progn (let* ((pkg-desc (quelpa-get-package-desc file)) (requires (progn (or ... ...) (aref pkg-desc 4))) (ver (progn (or ... ...) (aref pkg-desc 2)))) (if requires (progn (mapc #'... requires))) (quelpa-package-install-file file) ver))))
  quelpa-package-install((info+ :fetcher wiki))
  apply(quelpa-package-install (info+ :fetcher wiki) nil)
  (and t (apply #'quelpa-package-install arg plist))
  (let* ((ver (and t (apply #'quelpa-package-install arg plist)))) (if ver (progn (if quelpa-autoremove-p (progn (quelpa--delete-obsoleted-package (car cache-item) ver))) (quelpa-update-cache cache-item)) nil))
  (let* ((arg (or arg (let ((quelpa-melpa-recipe-stores (append quelpa-melpa-recipe-stores ...))) (quelpa-interactive-candidate)))) (quelpa-upgrade-p (if current-prefix-arg t quelpa-upgrade-p)) (quelpa-stable-p quelpa-stable-p) (quelpa-autoremove-p (if current-prefix-arg t quelpa-autoremove-p)) (cache-item (quelpa-arg-rcp arg))) (quelpa-parse-plist plist) (quelpa-parse-stable cache-item) (let* ((ver (and t (apply #'quelpa-package-install arg plist)))) (if ver (progn (if quelpa-autoremove-p (progn (quelpa--delete-obsoleted-package (car cache-item) ver))) (quelpa-update-cache cache-item)) nil)))
  (progn (let* ((arg (or arg (let ((quelpa-melpa-recipe-stores ...)) (quelpa-interactive-candidate)))) (quelpa-upgrade-p (if current-prefix-arg t quelpa-upgrade-p)) (quelpa-stable-p quelpa-stable-p) (quelpa-autoremove-p (if current-prefix-arg t quelpa-autoremove-p)) (cache-item (quelpa-arg-rcp arg))) (quelpa-parse-plist plist) (quelpa-parse-stable cache-item) (let* ((ver (and t (apply #'quelpa-package-install arg plist)))) (if ver (progn (if quelpa-autoremove-p (progn (quelpa--delete-obsoleted-package ... ver))) (quelpa-update-cache cache-item)) nil))))
  (if (quelpa-setup-p) (progn (let* ((arg (or arg (let (...) (quelpa-interactive-candidate)))) (quelpa-upgrade-p (if current-prefix-arg t quelpa-upgrade-p)) (quelpa-stable-p quelpa-stable-p) (quelpa-autoremove-p (if current-prefix-arg t quelpa-autoremove-p)) (cache-item (quelpa-arg-rcp arg))) (quelpa-parse-plist plist) (quelpa-parse-stable cache-item) (let* ((ver (and t (apply ... arg plist)))) (if ver (progn (if quelpa-autoremove-p (progn ...)) (quelpa-update-cache cache-item)) nil)))))
  quelpa((info+ :fetcher wiki))
  (if recipe (quelpa recipe) (configuration-layer//warning (concat "Cannot find any recipe for package %S! Be sure " "to add a recipe for it in alist %S.") pkg-name recipes-var))
  (let* ((pkg-name (eieio-oref pkg ':name)) (layer (car (eieio-oref pkg ':owners))) (recipe (cons pkg-name (cdr (eieio-oref pkg ':location))))) (if recipe (quelpa recipe) (configuration-layer//warning (concat "Cannot find any recipe for package %S! Be sure " "to add a recipe for it in alist %S.") pkg-name recipes-var)))
  configuration-layer//install-from-recipe(#<cfgl-package cfgl-package-157b66fdf108>)
  (cond ((or (null pkg) (eq 'elpa location)) (configuration-layer//install-from-elpa pkg-name) (if pkg (progn (cfgl-package-set-property pkg :lazy-install nil)))) ((and (listp location) (eq 'recipe (car location))) (configuration-layer//install-from-recipe pkg) (cfgl-package-set-property pkg :lazy-install nil)) (t (configuration-layer//warning "Cannot install package %S." pkg-name)))
  (condition-case err (cond ((or (null pkg) (eq 'elpa location)) (configuration-layer//install-from-elpa pkg-name) (if pkg (progn (cfgl-package-set-property pkg :lazy-install nil)))) ((and (listp location) (eq 'recipe (car location))) (configuration-layer//install-from-recipe pkg) (cfgl-package-set-property pkg :lazy-install nil)) (t (configuration-layer//warning "Cannot install package %S." pkg-name))) ((debug quote error) (configuration-layer//error (concat "\nAn error occurred while installing %s " "(error: %s)\n") pkg-name err) (spacemacs//redisplay)))
  (if (package-installed-p pkg-name min-version) nil (condition-case err (cond ((or (null pkg) (eq 'elpa location)) (configuration-layer//install-from-elpa pkg-name) (if pkg (progn (cfgl-package-set-property pkg :lazy-install nil)))) ((and (listp location) (eq 'recipe (car location))) (configuration-layer//install-from-recipe pkg) (cfgl-package-set-property pkg :lazy-install nil)) (t (configuration-layer//warning "Cannot install package %S." pkg-name))) ((debug quote error) (configuration-layer//error (concat "\nAn error occurred while installing %s " "(error: %s)\n") pkg-name err) (spacemacs//redisplay))))
  (let* ((layer (if pkg (progn (car (eieio-oref pkg ':owners))))) (location (if pkg (progn (eieio-oref pkg ':location)))) (min-version (if pkg (progn (eieio-oref pkg ':min-version))))) (spacemacs-buffer/replace-last-line (format "--> installing %s: %s%s... [%s/%s]" (if layer "package" "dependency") pkg-name (if layer (format "@%S" layer) "") installed-count not-inst-count) t) (spacemacs//redisplay) (if (package-installed-p pkg-name min-version) nil (condition-case err (cond ((or (null pkg) (eq 'elpa location)) (configuration-layer//install-from-elpa pkg-name) (if pkg (progn (cfgl-package-set-property pkg :lazy-install nil)))) ((and (listp location) (eq 'recipe (car location))) (configuration-layer//install-from-recipe pkg) (cfgl-package-set-property pkg :lazy-install nil)) (t (configuration-layer//warning "Cannot install package %S." pkg-name))) ((debug quote error) (configuration-layer//error (concat "\nAn error occurred while installing %s " "(error: %s)\n") pkg-name err) (spacemacs//redisplay)))))
  configuration-layer//install-package(#<cfgl-package cfgl-package-157b66fdf108>)
  (if (and pkg (memq (eieio-oref pkg ':step) '(bootstrap pre))) nil (setq installed-count (1+ installed-count)) (configuration-layer//install-package pkg))
  (let ((pkg (configuration-layer/get-package pkg-name))) (if (and pkg (memq (eieio-oref pkg ':step) '(bootstrap pre))) nil (setq installed-count (1+ installed-count)) (configuration-layer//install-package pkg)))
  (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (let ((pkg (configuration-layer/get-package pkg-name))) (if (and pkg (memq (eieio-oref pkg ':step) '(bootstrap pre))) nil (setq installed-count (1+ installed-count)) (configuration-layer//install-package pkg))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- upkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (let ((pkg (configuration-layer/get-package pkg-name))) (if (and pkg (memq (eieio-oref pkg ':step) '(bootstrap pre))) nil (setq installed-count (1+ installed-count)) (configuration-layer//install-package pkg))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((delayed-warnings-backup delayed-warnings-list)) (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" not-inst-count)) (configuration-layer/retrieve-package-archives) (setq installed-count 0) (spacemacs//redisplay) (let ((--dolist-tail-- upkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (let ((pkg (configuration-layer/get-package pkg-name))) (if (and pkg (memq (eieio-oref pkg ...) '...)) (progn (setq installed-count (1+ installed-count)) (configuration-layer//install-package pkg)))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (let ((--dolist-tail-- upkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (let ((pkg (configuration-layer/get-package pkg-name))) (if (and pkg (memq (eieio-oref pkg ...) '...)) nil (setq installed-count (1+ installed-count)) (configuration-layer//install-package pkg))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n") (if init-file-debug nil (setq delayed-warnings-list delayed-warnings-backup)))
  (progn (spacemacs-buffer/set-mode-line "Installing packages..." t) (let ((delayed-warnings-backup delayed-warnings-list)) (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" not-inst-count)) (configuration-layer/retrieve-package-archives) (setq installed-count 0) (spacemacs//redisplay) (let ((--dolist-tail-- upkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (let ((pkg (configuration-layer/get-package pkg-name))) (if (and pkg (memq ... ...)) (progn (setq installed-count ...) (configuration-layer//install-package pkg)))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (let ((--dolist-tail-- upkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (let ((pkg (configuration-layer/get-package pkg-name))) (if (and pkg (memq ... ...)) nil (setq installed-count (1+ installed-count)) (configuration-layer//install-package pkg))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n") (if init-file-debug nil (setq delayed-warnings-list delayed-warnings-backup))))
  (if upkg-names (progn (spacemacs-buffer/set-mode-line "Installing packages..." t) (let ((delayed-warnings-backup delayed-warnings-list)) (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" not-inst-count)) (configuration-layer/retrieve-package-archives) (setq installed-count 0) (spacemacs//redisplay) (let ((--dolist-tail-- upkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (let ((pkg ...)) (if (and pkg ...) (progn ... ...))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (let ((--dolist-tail-- upkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (let ((pkg ...)) (if (and pkg ...) nil (setq installed-count ...) (configuration-layer//install-package pkg))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n") (if init-file-debug nil (setq delayed-warnings-list delayed-warnings-backup)))))
  (let* ((upkg-names (configuration-layer//get-uninstalled-packages packages)) (not-inst-count (length upkg-names)) installed-count) (if upkg-names (progn (spacemacs-buffer/set-mode-line "Installing packages..." t) (let ((delayed-warnings-backup delayed-warnings-list)) (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" not-inst-count)) (configuration-layer/retrieve-package-archives) (setq installed-count 0) (spacemacs//redisplay) (let ((--dolist-tail-- upkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (let (...) (if ... ...)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (let ((--dolist-tail-- upkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (let (...) (if ... nil ... ...)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n") (if init-file-debug nil (setq delayed-warnings-list delayed-warnings-backup))))))
  (let ((display-buffer-alist '(("\\(\\*Compile-Log\\*\\)\\|\\(\\*Warnings\\*\\)" (display-buffer-in-side-window) (inhibit-same-window . t) (side . bottom) (window-height . 0.2))))) (configuration-layer//configure-quelpa) (let* ((upkg-names (configuration-layer//get-uninstalled-packages packages)) (not-inst-count (length upkg-names)) installed-count) (if upkg-names (progn (spacemacs-buffer/set-mode-line "Installing packages..." t) (let ((delayed-warnings-backup delayed-warnings-list)) (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" not-inst-count)) (configuration-layer/retrieve-package-archives) (setq installed-count 0) (spacemacs//redisplay) (let ((--dolist-tail-- upkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name ...) (let ... ...) (setq --dolist-tail-- ...))) (let ((--dolist-tail-- upkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name ...) (let ... ...) (setq --dolist-tail-- ...))) (spacemacs-buffer/append "\n") (if init-file-debug nil (setq delayed-warnings-list delayed-warnings-backup)))))))
  configuration-layer//install-packages((ace-jump-helm-line ace-link ace-window aggressive-indent async auto-compile auto-highlight-symbol avy bind-key bind-map centered-cursor-mode clean-aindent-mode column-enforce-mode dash define-word desktop diminish dired-quick-sort dotenv-mode drag-stuff dumb-jump editorconfig elisp-slime-nav emr eval-sexp-fu evil evil-anzu evil-args evil-cleverparens evil-collection evil-easymotion evil-ediff evil-escape evil-exchange evil-goggles evil-iedit-state evil-indent-plus evil-lion evil-lisp-state evil-matchit evil-mc evil-nerd-commenter evil-numbers evil-surround evil-textobj-line evil-tutor evil-unimpaired evil-visual-mark-mode evil-visualstar expand-region ...))
  (let ((packages (append (configuration-layer//filter-distant-packages configuration-layer--used-packages t '(not (oref pkg :lazy-install))) (if (eq 'all dotspacemacs-install-packages) (progn (let (all-other-packages) (let ... ...) (configuration-layer//filter-distant-packages all-other-packages nil))))))) (configuration-layer//install-packages packages) (if (and (or (eq 'used dotspacemacs-install-packages) (eq 'used-only dotspacemacs-install-packages)) (not configuration-layer-force-distribution) (not configuration-layer-exclude-all-layers)) (progn (configuration-layer/delete-orphan-packages packages))))
  (progn (let ((packages (append (configuration-layer//filter-distant-packages configuration-layer--used-packages t '(not ...)) (if (eq 'all dotspacemacs-install-packages) (progn (let ... ... ...)))))) (configuration-layer//install-packages packages) (if (and (or (eq 'used dotspacemacs-install-packages) (eq 'used-only dotspacemacs-install-packages)) (not configuration-layer-force-distribution) (not configuration-layer-exclude-all-layers)) (progn (configuration-layer/delete-orphan-packages packages)))))
  (if spacemacs-sync-packages (progn (let ((packages (append (configuration-layer//filter-distant-packages configuration-layer--used-packages t '...) (if (eq ... dotspacemacs-install-packages) (progn ...))))) (configuration-layer//install-packages packages) (if (and (or (eq 'used dotspacemacs-install-packages) (eq 'used-only dotspacemacs-install-packages)) (not configuration-layer-force-distribution) (not configuration-layer-exclude-all-layers)) (progn (configuration-layer/delete-orphan-packages packages))))))
  configuration-layer//load()
  (cond (changed-since-last-dump-p (configuration-layer//load) (if (spacemacs/emacs-with-pdumper-set-p) (progn (configuration-layer/message "Layer list has changed since last dump.") (configuration-layer//dump-emacs)))) (spacemacs-force-dump (configuration-layer//load) (if (spacemacs/emacs-with-pdumper-set-p) (progn (configuration-layer/message (concat "--force-dump passed on the command line or configu..." "been reloaded, forcing a redump.")) (configuration-layer//dump-emacs)))) ((spacemacs-is-dumping-p) (configuration-layer//load)) ((and (spacemacs/emacs-with-pdumper-set-p) (spacemacs-run-from-dump-p)) (configuration-layer/message "Running from a dumped file. Skipping the loading p...")) (t (configuration-layer//load) (if (spacemacs/emacs-with-pdumper-set-p) (progn (configuration-layer/message (concat "Layer list has not changed since last time. " "Skipping dumping process!"))))))
  configuration-layer/load()
  (let ((file-name-handler-alist nil)) (require 'core-spacemacs) (spacemacs/dump-restore-load-path) (configuration-layer/load-lock-file) (spacemacs/init) (configuration-layer/stable-elpa-init) (configuration-layer/load) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (spacemacs/dump-eval-delayed-functions) (if (and dotspacemacs-enable-server (not (spacemacs-is-dumping-p))) (progn (require 'server) (if dotspacemacs-server-socket-dir (progn (setq server-socket-dir dotspacemacs-server-socket-dir))) (if (server-running-p) nil (message "Starting a server...") (server-start)))))
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (let ((file-name-handler-alist nil)) (require 'core-spacemacs) (spacemacs/dump-restore-load-path) (configuration-layer/load-lock-file) (spacemacs/init) (configuration-layer/stable-elpa-init) (configuration-layer/load) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (spacemacs/dump-eval-delayed-functions) (if (and dotspacemacs-enable-server (not (spacemacs-is-dumping-p))) (progn (require 'server) (if dotspacemacs-server-socket-dir (progn (setq server-socket-dir dotspacemacs-server-socket-dir))) (if (server-running-p) nil (message "Starting a server...") (server-start))))))
  eval-buffer(#<buffer  *load*> nil "/home/jefferson/.emacs.d/init.el" nil t)  ; Reading at buffer position 3159
  load-with-code-conversion("/home/jefferson/.emacs.d/init.el" "/home/jefferson/.emacs.d/init.el" t t)
  load("/home/jefferson/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x157b66a7e365>) #f(compiled-function () #<bytecode 0x157b66a7e331>) t)
  command-line()
  normal-top-level()
```

But I am having no connectivity problems. I can reach `emacswiki.org` through browser or curl with or without port 443.

```
$ curl https://www.emacswiki.org:443/emacs/download/info+.el --output info+.el
%Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  356k    0  356k    0     0   188k      0 --:--:--  0:00:01 --:--:--  188k
```
Any thoughts?

**Comment by lebensterben** [comment]
@quigonjeff 

what if you try to open emacswiki inside eww?
(eww URL)

**Pull request closed without merging**
