### PR TITLE
Add IRC buffers to respective perspectives

### PR DESCRIPTION
**Pull request by CestDiego**
This attempts to fix https://github.com/syl20bnr/spacemacs/issues/4781

Also add configurability for the default binding for the IRC perspectives.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1:

**Comment by CestDiego** [comment]
@syl20bnr this needs to be merged for erc buffers to work

**Comment by TheBB** [comment]
There are some problems with this. I attacked it with a chainsaw and the result is #5272.

**Comment by TheBB** [comment]
Closed via #5272.

**Pull request closed without merging**
