### PR TITLE
Load auctex on startup, adds ~.4s to load time

### PR DESCRIPTION
**Pull request by bjarkevad**
auctex should be loaded on demand as other layers, even if the load time is a bit long.
Comments?

### CODE REVIEW

**Comment by trishume** [comment]
Might be worthwhile, I'm somewhat concerned that the additional 0.4s you get is much lower than the 5-6 seconds it takes for the `SPC e l` command to run for me, maybe it runs way faster on your computer?

Or does this lazy load Auctex despite the lack of `:deferred` in the `use-package` call, and it adds 0.4s to startup but freezes emacs for 5 seconds the first time you open a LaTeX file?

I do think trying to make it like other layers is worthwhile, I was pretty sure to Emacs when I wrote this layer and I'm pretty sure I overreacted with making it manually loaded. Just not 100% sure this code will do it right.

**Comment by bjarkevad** [comment]
Okay, so I tried it on my laptop running OSX, and there the difference is significantly bigger. I don't think this PR should be merged as is now :)

**Comment by trishume** [comment]
I tried this patch but using `:defer t` to only load it when you edit a LaTeX file and it now adds no startup time on any system.

I have a PR in the queue (The way I do git means I only ever have 1 PR open at a time but you can see my queue of changes in the network graph) that implements this with defer and also remembers to remove the manual loading stuff from the readme.

**Comment by bjarkevad** [comment]
That sounds awesome :)

**Pull request closed without merging**
