### PR TITLE
Restructured haskell/init-haskell-mode settings

### PR DESCRIPTION
**Pull request by TakSuyu**
Followed suggestions in https://github.com/syl20bnr/spacemacs/pull/3488

### CODE REVIEW

**Comment by d12frosted** [comment]
How does it play when you change those variables in `user-config` function? 

P. S. Sorry, can't test it right now - gonna play with it tomorrow :smile:

**Comment by TakSuyu** [comment]
So far I've tested with haskell-stylish-on-save and a simple `(setq haskell-stylish-on-save t)` within `dotspacemacs/config` works, and `describe-variable` properly reports that the variable is set to t and the default is nil when in haskell-mode.

**Comment by d12frosted** [comment]
Great. Played with it a bit - works like a charm. 

@syl20bnr thanks for this idea! Much easier to change configs.

**Comment by TakSuyu** [comment]
Looks like there is some other stuff that got pushed, want me to bring the branch up to date?

**Comment by d12frosted** [comment]
@TheBB any chances that it gets merged?

**Comment by StreakyCobra** [comment]
This PR should probably be rebased to have more chances being merged. Then try to ping TheBB :wink:

**Comment by TakSuyu** [comment]
@TheBB Branch has been rebased to match with develop.

**Comment by TheBB** [comment]
Looks good. Labeling this so I don't forget.

**Comment by TheBB** [comment]
I didn't have to remember for long.

Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
