### PR TITLE
C/C++ cleanup

### PR DESCRIPTION
**Pull request by magthe**
My first ever request for spacemacs, and pretty much my first editing of elisp code (outside of trivial configuration) so I'd love to hear what I can do to improve it.

I get the feeling the C/C++ layer has been somewhat neglected and has collected a bit of cruft, so it could do with a bit of a cleanup in time for the holidays ;)  I basically removed all the packages I couldn't find in my elpa dir after adding and using the layer.  I also found some things that didn't seem to work anyway (*stickyfunc-enhance*), so that and the packages it depended on were removed too.

This also uses the `.clang_complete` file to set up *company-c-headers*.

### CODE REVIEW

**Comment by TheBB** [comment]
> I basically removed all the packages I couldn't find in my elpa dir after adding and using the layer.

This, you shold at least not do. Those packages are installed by *other* layers (that you are by chance not using), and for which the C/C++ layer needs optional configuration. This is why they have post-init functions and not init functions.

The packages you have removed are owned by the `semantic`, `ycmd` and `cscope` layers, so unless you have those enabled the packages will not be installed. This is not a bug or due to code cruft.

See [LAYERS.org](https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org#anatomy-of-a-layer) for more information.

**Comment by TheBB** [comment]
Oh, and please put multiline `:init` or `:config` blocks on a separate line. :-)

**Comment by magthe** [comment]
I'll read up on layers and redo.

Should those *post-init* functions not be guarded by checks for the respective layers then?

**Comment by TheBB** [comment]
No, a package will be installed and configured only if an init function is defined in an enabled layer. Since the C++ layer doesn't define an init function for those layers, they will not be installed by that layer alone.

**Comment by magthe** [comment]
I'll make a few less intrusive changes then... in a new merge request I think.

**Pull request closed without merging**
