### PR TITLE
Create distinct Common Lisp, Scheme layers

### PR DESCRIPTION
**Pull request by kingcons**
This pull request moves SLIME into a Common Lisp layer and adds Geiser to better support Scheme editing and resolve Issue #1002.

### CODE REVIEW

**Comment by kingcons** [comment]
@tuhdo Would love any feedback/review. This is enough for me at the moment as it at least gets both Geiser and SLIME off the ground and in good shape.

**Comment by person808** [comment]
Looks pretty good to me

**Comment by tuhdo** [comment]
Looks good to me too. Should be merged.

**Comment by kingcons** [comment]
@syl20bnr This should be ready for merge if you have a minute. Thanks for spacemacs! :tada:

**Comment by srid** [comment]
I'm testing this out. `, s B` doesn't do anyting, except display a string like "void =>" in the status line.

**Comment by kingcons** [comment]
@srid: That's right. Perhaps I should clarify the docs? The buffer was loaded by Racket, the return value of the load expression was nil, and you were then switched to the REPL where you may use the loaded code as you like.

**Comment by syl20bnr** [comment]
Thank you :+1: 
Sometimes asking for a merge works ;-)
Cherry-picked and squashed in develop branch, you can safely delete your branch.

**Pull request closed without merging**
