### PR TITLE
Fix excessive memory usage on first startup

### PR DESCRIPTION
**Pull request by jjlee**
I experienced this reproducibly when spacemacs reached the stage where it shows
the message in the mode line starting like this:

"Downloading stable ELPA repository: "

Without this change I was unable to start spacemacs and in fact had to reboot my
machine multiple times. Emacs 25.1.1, Ubuntu 17.04, no swap configured.

Obviously this needs cleaning up a bit...

Also fixed an extraneous 'kkj' which I assume is a typo (actually I thought this
was my typo but turns out to be syl20bnr himself :-)

### CODE REVIEW

**Comment by jjlee** [comment]
Maybe related to #9803?

**Comment by jjlee** [comment]
Er, to clarify, the excessive memory usage occurred when starting spacemacs for the first time after git cloning.

**Comment by jjlee** [comment]
This fixed the problem for me with wget installed, but this is intended mostly to show the problem and a working solution just to illustrate what the problem is:

* It has not been carefully tested (I didn't even try the curl case for example, nor the fallback "you need to install curl/wget" case)
* I don't know if this works on Windows / Mac
* There's the question of what to do if no external url fetching program is available (curl, wget, ...), hence the commented-out code here
* I imagine my coding style is not up to scratch

Seems bad to fall back to the emacs native `url-copy-file`: I guess I think that having the potential for this bad behaviour, even for only some people, is worse than failing entirely because wget or curl is not installed.  My guess is people won't get as angry if they just have to install curl or wget as if their computer hangs and has to be rebooted :-)  I guess spacemacs could just not fetch the big elpa tarball archive if no external download tool is available, and rely on lazily fetching packages one-by-one in that case?

(I'm not angry :-)

**Comment by NerdsvilleCEO** [comment]
@jjlee Nice catches, I am wondering if it makes sense to just give a message saying it couldn't download all of the elpa dependencies and asking to download cURL or wget if they aren't present... but this does indeed beg the question, how would this be handled in Windows... maybe this is why the fallback was there, I am unsure as I am myself new to spacemacs

**Comment by jjlee** [comment]
Alternative possible hack: split the tarball into 10 parts (may not work: it's just my guess that might fix the most extreme memory usage).  Then, fall back to emacs-native url-copy-file if curl/wget isn't available.

**Pull request closed without merging**
