### PR TITLE
Add TypeScript Layer

### PR DESCRIPTION
**Pull request by hamhut1066**
A simple layer to introduce TypeScript to spacemacs, Integration with flycheck, auto-complete, with dependencies on Microsoft/TypeScript and clausreinke/typescript-tools.

Enjoy!

### CODE REVIEW

**Comment by syl20bnr** [comment]
Outch I hate to say that but a starting layer has already been merged in develop :-(
Can you apply your changes against the layer in develop ?

**Comment by hamhut1066** [comment]
I have updated the package to use a custom flymake command, giving better error handling, and proper referencing of relative files.

I have also disabled flymake, and integrated with flycheck, to conform with the rest of spacemacs using flycheck. I hope these changes are useful.

**Comment by hamhut1066** [comment]
This change removes the use of Flymake from the Typescript Package, and makes it use `FlyCheck` Instead.

**Comment by kRITZCREEK** [comment]
yes please! :+1:

**Comment by hamhut1066** [comment]
@syl20bnr Any update on this? Are you happy merging in? or do you need me to clean up my commits?

Is there something I need to do?

**Comment by zilongshanren** [comment]
@hamhut1066  You should sync with the latest upstream, checkout a new local branch and apply your changes to a new local branch. After that, you could send your clean PR.
Now this PR is messy, it contains many unneeded commits.

**Comment by robbyoconnor** [comment]
git pull --rebase and then rebase (using an interactive rebase) so it's one single commit; and then push to your fork :)

**Comment by hamhut1066** [comment]
I used my dev branch, which can cause problems when just messing around.

moved to a branch which is better.

**Comment by robbyoconnor** [comment]
good call :)

**Pull request closed without merging**
