### PR TITLE
improve the elixir and phoenix layers

### PR DESCRIPTION
**Pull request by PanarinM**
add `SPC m d b` shortcut to elixir layer that toggles a breakpoint
added a functions for that
add `SPC m f x` and `SPC m f d` to phoenix layer to run server +
according functions

By the example of python mode, I added the breakpoint toggle as well as some handy shortcuts, that, I think, are essential.

### CODE REVIEW

**Comment by aislanmaia** [comment]
This have some handful new generators from the latest versions of Phoenix? (mix, phx.gen....)

**Comment by mpanarin** [comment]
> This have some handful new generators from the latest versions of Phoenix? (mix, phx.gen....)
> And the after Phoenix 1.3 onwards there is no more models folder generated at all. All is through generating context, resources... etc.

no, this doesn't include them. As I am not that proficient with Phoenix and currently working with elixir alone, I had no knowledge of them. 
This PR adds only a few handy shortcuts and functions. 

As well as, I think, adding new mix tasks is more of a [Alchemist](https://github.com/tonini/alchemist.el) job and not spacemacs, if I understood you correctly.

**Comment by simpers** [comment]
I'd suggest you check out [Elixir forum - Emacs LSP](https://elixirforum.com/t/emacs-lsp-mode-language-server-elixir-ls-anyone/11834/5) as that works a lot better and is used by other editors as well, like Atom and Visual Studio Code.

Alchemist has not been updated for a year and it has gotten stuck below Phoenix 1.3, which differs a lot from the current 1.4.

If I had the slightest clue of what to do to integrate this, I'd try myself but I have never gotten into elisp enough to be able to. Somebody made another backend for python though using python-lsp, [Spacemacs Python LSP](https://github.com/syl20bnr/spacemacs/commit/81a931f48bdd6bcca4fdf0a3baab7b4bd7695591), which could be used as a base, somebody pointed out in the Elixir form thread.

**Comment by smile13241324** [comment]
Hi guys,

Elixir layer has now support for an LSP server, it may not yet have all the features Alchemist has but as you all now Alchemist is no longer maintained and definitive a dead-end.

I am not too familiar with elixir, working mostly with python, haskel and clojure now a days, so it would be great if you could double check which of the changes in this PR are still useful for the elixir layer and which are obsolete or duplicate.

Btw, we are currently all pretty busy with the incredible amount of PRs so it would be a great help if you could also test the features and post a result. This reduces work for the maintainers dramatically.

**Comment by mpanarin** [comment]
@smile13241324 this is my pr on an "old" account and is superseded by https://github.com/syl20bnr/spacemacs/pull/12705

so, it can be closed )

**Pull request closed without merging**
