### PR TITLE
Replace the typewriter image with the correct one. Fix #6832

### LINKED ISSUE #6832: Selectric has a picture of a Hammond 12, not an IBM Selectric
The selectric layer README.org file has the image of a different, much older, typewriter.

### PR DESCRIPTION
**Pull request by rbanffy**
Replace Hammond 12 image with a 1961 IBM Selectric typewriter

The typewriter pictured is similar to the one used to record the audio
files. A mention to the IBM Selectric is also made in the README, along
with credit for the picture.

### CODE REVIEW

**Comment by TheBB** [comment]
Fixes https://github.com/syl20bnr/spacemacs/issues/6832

**Comment by rbanffy** [comment]
Can you re-run the CI check? It's succeeding on my fork: https://travis-ci.org/rbanffy/spacemacs/builds/153018976

**Comment by TheBB** [comment]
The CI failure is not due to your commit. (Obviously.)

By the way you can skip CI for trivial commits by putting `[ci skip]` in the commit message.

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
