### PR TITLE
Add ERC-SASL to SASL authentication to ERC

### PR DESCRIPTION
**Pull request by CestDiego**
So lately my ISP gave me an IP that was blacklisted and using SASL was the only way to connect to freenode.

### CODE REVIEW

**Comment by CestDiego** [comment]
Awesum...now I have to fix this ;_;

**Comment by syl20bnr** [comment]
oops sorry !

**Comment by CestDiego** [comment]
k #done :)

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
I renamed the variable `erc-enable-sasl-auth` and added `:if` keyword to use-package to honor it, related commit: https://github.com/syl20bnr/spacemacs/commit/42cce3a
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by waltervargas** [comment]
How can I use this feature? 

I am trying this: 

```elisp
extensions.el
(custom-set-variables                                                                                                         │· ;; custom-set-variables was added by Custom.                                                                                 │· ;; If you edit it by hand, you could mess it up, so be careful.                                                              │·
 ;; Your init file should contain only one such instance.                                                                     │· ;; If there is more than one, they won't work right.                                                                         │· '(erc-enable-sasl-auth t)                                                                                                    │· '(erc-away-nickname "walterve-away")                                                                                         │· '(erc-email-userid "waltervargas@linux.com")                                                                                 │·
 '(erc-modules
```

**Pull request closed without merging**
