### PR TITLE
Fix documentation issues with ruby, rails, and swift layers

### PR DESCRIPTION
**Pull request by benjamreynolds**
See #9476

### CODE REVIEW

**Comment by JAremko** [comment]
@balajisivaraman  You have [trailing white space](https://circleci.com/gh/syl20bnr/spacemacs/165?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by balajisivaraman** [comment]
@JAremko You have marked me incorrectly in this thread. I think that you meant @benjamreynolds.

**Comment by JAremko** [comment]
@benjamreynolds You have trailing white space

@balajisivaraman Sorry about that and thanks for pointing out :smile:

**Comment by benjamreynolds** [comment]
Ammended commit and force pushed, thanks for point it out @JAremko. Weird that we dont have a `.editorconfig` file setup to handle that for us. Maybe I'll add that this weekend. (I usually rely on the editorconfig plugin to strip my whitespace in my other projects.)

**Comment by benjamreynolds** [comment]
@JAremko, anything else you need from me on this one?

**Comment by JAremko** [comment]
Thank you :+1: Cherry-picked into develop, you can safely delete your branch.

**Pull request closed without merging**
