### PR TITLE
Update links to FAQ.org

### PR DESCRIPTION
**Pull request by xfq**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
This doesn't actually work.

**Comment by xfq** [comment]
On Fri, Oct 2, 2015 at 5:01 PM, robbyoconnor <notifications@github.com>
wrote:

> This doesn't actually work.
>
>
> Why?  I don't see anything wrong.  Would you like to provide a correct
version of this patch?  Thank you.

**Comment by TheBB** [comment]
Seems to work, yes. Thanks! Cherry-picked in develop, you can safely delete your branch.

**Comment by xfq** [comment]
@TheBB Thank you!

**Comment by robbyoconnor** [comment]
I deleted it when I tested it a bit farther :)

**Pull request closed without merging**
