### PR TITLE
evil-mc: Fix misaligned cursors on macOS and Windows

### PR DESCRIPTION
**Pull request by benreyn**
See #8641
See also gabesoft/evil-mc#49

### CODE REVIEW

**Comment by duianto** [comment]
This is not mac specific. The same thing happens in windows. Setting the `evil-mc-enable-bar-cursor` variable to `nil`, hides the bar symbol on the fake cursors, so that the following characters, don't get shifted to the right, it also stops the line height from changing.

evil-mc-bar-cursor

**Comment by benjamreynolds** [comment]
Interesting. Is it an issue on linux at all (does anyone know?). Should this just be a default? Or should this be a fix made upstream?

**Comment by duianto** [comment]
In a comment: https://github.com/gabesoft/evil-mc/issues/49#issuecomment-286005184 on the evil-mc issue you linked to above, gabesoft says:
>In Linux it looks fine but not on MAC.

So It might be enough to fix it in mac and windows.

**Comment by benjamreynolds** [comment]
Cool!, I amended my commit and fixed this for both platforms.

**Comment by duianto** [comment]
Just tested it, and it works as expected. 👍

**Comment by benjamreynolds** [comment]
Friendly ping @syl20bnr, @TheBB, @d12frosted and @bmag. Can I get a pass on review on this one?

**Comment by benreyn** [comment]
@duianto, would you mind doing a more thorough review of this per the new [PR review policy](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org#reviewing-pull-requests)? Hopefully we can get this fix merged. This bug annoys me every time I use `evil-mc`.

**Comment by duianto** [comment]
I'm not sure what more I could test. I guess I could add a detailed description.

I copied and pasted the PRs changes.

Before applying them, then the lines with evil-mc cursors in insert state, changes line height (at east on windows 10, I'm not sure if it happens on mac). The characters after the insert state cursors, also get shifted to the right by one character (see gif animation above: https://github.com/syl20bnr/spacemacs/pull/9585#issuecomment-329595185).

After the changes have been applied and Emacs has been restarted, then the lines do not change height or shift to the right

I don't have a mac, so I've only been able to test it in windows 10.

The PR review notes suggest using the PR for hours or days, but I don't use evil-mc that often, so I don't know how long it would take to sufficiently test it.

Maybe it would be helpful to add a comment before the changes, like this (or something better):
```elisp
      ;; disable bar cursor on mac and windows, to prevent the insert state
      ;; cursors from shifting the following characters to the right once
      (setq evil-mc-one-cursor-show-mode-line-text nil)
      (when (or (spacemacs/system-is-mac) (spacemacs/system-is-mswindows))
        (setq evil-mc-enable-bar-cursor nil)))))
```


#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4c231ae2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
 emacs-lisp git haskell helm html markdown org treemacs spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by benreyn** [comment]
@syl20bnr @TheBB @d12frosted @bmag @JAremko Can we consider this one ready to be merged?

**Comment by syl20bnr** [comment]
Thank you ! 💜 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
