### PR TITLE
Release 0.104.3

### PR DESCRIPTION
**Pull request by TheBB**
This is a meta-PR. I'll be collecting all the commits I see that need to be applied to master to keep it working.

@syl20bnr

### CODE REVIEW

**Comment by syl20bnr** [comment]
Excellent!

While it is OK to push to master I usually push to release-0.104 update the release number and change log there. Once everything is OK I reset master to release-0.104 head and force push it to origin (this is why master is considered an immutable branch that the user should not alter). To finish I export the org sub-tree on the change log to GFM, I alter the links to prevent from conflict with the other change log in GitHub release page and create the release.

I'm OK to do it when you have finished this PR if you prefer.

**Comment by syl20bnr** [comment]
One last step: import the change log sub-tree in develop branch.

**Comment by TheBB** [comment]
Yeah, maybe you can do it? The PR is finished, I just wanted to collect all of them here instead of scattering e-mail notifications all over the place. As it turns out there were only two commits.

**Comment by syl20bnr** [comment]
Also the release becomes public (ie detected by Spacemacs) when the release is created on GitHub (more accurately when the release tag is created).

**Comment by syl20bnr** [comment]
OK I will do it.

**Comment by syl20bnr** [comment]
Thank you :100:

**Pull request merged**
