### PR TITLE
Use extension for vim-empty-lines layer.

### PR DESCRIPTION
**Pull request by person808**
Better support for hidpi and customization.

Updated #1116

### CODE REVIEW

**Comment by syl20bnr** [comment]
What kind of modification this fork has ?

I'll test this fork tonight.
I will replace vi-tilde-fringe if the performance issues with vim-empty-lines have been fixed. Did you try to open a file with 5k lines and scroll at the end of the buffer ?

**Comment by person808** [comment]
I merged all open PRs from the original repository. 

https://github.com/jmickelin/vim-empty-lines-mode/pulls

I tried scrolling on neovim's eval.c which is over 20k lines and it was smooth.

**Comment by syl20bnr** [comment]
Good news ! I'll try too on the same setup that was slow.

**Comment by person808** [comment]
Hmm... The toggle seems broken. Even toggling the mode manually doesn't seem to work.

**Comment by person808** [comment]
And now the toggle works somehow...

**Comment by syl20bnr** [comment]
I need to test it a bit before replacing vi-tilde-fringe.
Can you update this PR to replace the package in layer `vim-empty-lines` by the extensions and keep vi-tilde-fringe for now ?

**Comment by person808** [comment]
I updated the contrib layer but I cant seem to get the extension to load for some reason.

**Comment by person808** [comment]
@syl20bnr This updates the contrib layer now.

**Comment by syl20bnr** [comment]
Excellent ! :+1: 
I'm using the layer, if everything is fine on my side I will push it to spacemacs layer.

Thank you !
Cherry-picked into `develop`, you can safely delete your branch.

**Comment by syl20bnr** [comment]
@person808 I'm using the layer for quite some time and I found a blocking issue, it seems that `vim-empty-lines` messes multi-term. Check `SPC a s t` and tell me if you have a weird behavior too.

**Comment by person808** [comment]
@syl20bnr I have the same error. I'll try to check what causes it tomorrow.

**Pull request closed without merging**
