### PR TITLE
Keep current random ascii banner and startup summary when auto-centering emacs buffer on window resize

### PR DESCRIPTION
**Pull request by deb0ch**
Written on top of #6259 by @ralesi.

Now, for having tested it, these two PRs combined offer a smooth home buffer experience :smile: 

This PR has several commits because they are tightly related and depend on each other.

### CODE REVIEW

**Comment by TheBB** [comment]
Ah, sorry, I jumped the gun on the random banner fix.

**Comment by TheBB** [comment]
Thanks though. In the end I only needed the last commit. Note, Spacemacs conventions dictate `/` for functions and `-` for variables, so I renamed your variable.

**Comment by TheBB** [comment]
Cherry-picked in develop. You can safely delete your branch.

**Comment by deb0ch** [comment]
Thanks for the precision, I didn't get that yet. Just kept wondering why it is sometimes `/`, `//`, `-`, `--`, `|` or `||`.

Now that you say that I just took a look at CONVENTIONS and it is way clearer now :smile: 

I liked that how I did it it allowed for changing the banner when refreshing the startup page though. But I guess it is not really important and your way takes less code. Is it intentional, leaving the same even on refresh ?

**Pull request closed without merging**
