### PR TITLE
don't force elfeed-org

### PR DESCRIPTION
**Pull request by d12frosted**
Following [this](https://github.com/syl20bnr/spacemacs/commit/2c9e68ae6d77f8b0e5e5377a670610c259400a1e#diff-89d368300b0cf6c4dfbb7df1ede36c0cL44).

### CODE REVIEW

**Comment by d12frosted** [comment]
Never mind. I just made a silly typo. In order to disable it you should set `rmh-elfeed-org-files` to `'()`.

**Comment by d12frosted** [comment]
But just realised that there is nothing about this in elfeed readme. So either this fix should be merged or we should explicitly ask users to set `rmh-elfeed-org-files` to `'()`.

**Comment by syl20bnr** [comment]
I'm ok with the fix, seems counter-intuitive to tell people to set the variable to `'()`.
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by d12frosted** [comment]
Cool. 

> counter-intuitive

That's the phrase I was looking for :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
