### PR TITLE
Added keybinding for cider-format-buffer.

### PR DESCRIPTION
**Pull request by Immortalin**
This keybinding automatically formats the contents of the current Clojure buffer using [this](https://github.com/weavejester/cljfmt).

### CODE REVIEW

**Comment by mbertheau** [comment]
@Immortalin can you add a snippet to the clojure layer docs indicating what to put in `~/.lein/profiles.cljs` (if that's even sufficient?)

**Comment by Immortalin** [comment]
@mbertheau the format function is part of cider, no additional dependencies are needed. Cider only utilizes the library for formatting.

**Comment by mbertheau** [comment]
@Immortalin Ah, sorry for the noise then! :)

**Comment by malchmih** [comment]
:+1:

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop, you can safely delete your branch.

**Pull request closed without merging**
