### PR TITLE
Include Elm in extra-langs

### PR DESCRIPTION
**Pull request by jasonkuhrt**
Add a major mode for the Elm programming language.

### CODE REVIEW

**Comment by trishume** [comment]
Weird PR title, but good candidate for inclusion in `extra-langs`. I see the layer as a layer for programming language nerds (like myself) and elm is certainly a language that has buzz among the same people the other languages would appeal to.

**Comment by jasonkuhrt** [comment]
> Weird PR title

Fixed.

**Comment by trishume** [comment]
You fixed the PR title but now you PR'd to master instead of develop. :stuck_out_tongue_winking_eye: 

You went from mergeable state to trying to PR the entire next release.

**Comment by jasonkuhrt** [comment]
@trishume Whatever issues are now were there before. I made this PR from a in-github file edit which is the reason for the weirdness. I'll either fix this or remake it.

**Comment by trishume** [comment]
@jasonkuhrt I remember looking at this before. The difference is before you correctly PR'd to the `develop` branch but when you changed the title you changed it so the PR is to the `master` branch, which is not right.

**Comment by jasonkuhrt** [comment]
@trishume I edited the title and no more to my knowledge. I don't know how this was done and therefore nor how to undo it. I will redo this PR via a normal git native flow; The Github UI is not helping.

**Comment by ajnsit** [comment]
Did this get aborted? @jasonkuhrt Are you still planning to submit this PR?

**Pull request closed without merging**
