### PR TITLE
[up] and [down] in shell to go to cycle through previous commands

### PR DESCRIPTION
**Pull request by ralesi**
Allow [up] and [down] to cycle through history in `shell-mode`

### CODE REVIEW

**Comment by syl20bnr** [comment]
The key bindings should only work in insert-state, is it the case ?

**Comment by ralesi** [comment]
Yes, my bad, I submit a fix tonight.

**Comment by ralesi** [comment]
Updated for insert mode only.

**Comment by syl20bnr** [comment]
Thank you !
Cherry-picked and squashed in `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
