### PR TITLE
OSX layer keybindings should be applied on macOS no matter it is in G…

### PR DESCRIPTION
**Pull request by an0**
…UI mode or not. Otherwise the keybindings won't be applied if Emacs is launched in daemon mode.

### CODE REVIEW

**Comment by an0** [comment]
This fixes #11883.

**Comment by an0** [comment]
This fixes #11852.

**Comment by an0** [comment]
@smile13241324 Done.

**Comment by smile13241324** [comment]
Just had a look again, and saw that you accidentally added a merge envelope. Please remove it your branch should only have one commit.

**Comment by an0** [comment]
@smile13241324 Is it OK now?

**Comment by smile13241324** [comment]
Thanks for changing I will merge this evening.

**Comment by smile13241324** [comment]
Thank you for contributing to Spacemacs!
The PR has been cherry-picked into the develop branch, you can safely delete your branch.

**Pull request closed without merging**
