### PR TITLE
[core] Implement spacelpa

### PR DESCRIPTION
**Pull request by syl20bnr**

### CODE REVIEW

**Comment by syl20bnr** [comment]
@JAremko this PR needs to be merged to fixed the tests: https://github.com/JAremko/spacemacs-circleci/pull/1

For all, don't merge this PR, I'll merge it myself.

**Comment by syl20bnr** [comment]
Going to work again on this.

**Comment by JAremko** [comment]
Log for `test (macos-latest, 26.3, layers/+distribution/spacemacs-base)` end some other MacOS tests end with:
```
Cleaning up orphan processes
Terminate orphan process: pid (1607) (gpg-agent)
``

Should we kill the process?

**Comment by smile13241324** [comment]
This PR is opened since more than 2 years I don't think it has any chance of getting merged.

**Pull request closed without merging**
