### PR TITLE
Fix inconsistent notation of SPC key in docs

### PR DESCRIPTION
**Pull request by robert-m-johnson**
Replace all occurrences of `<SPC>` in org files with `SPC`.

Fixes syl20bnr/spacemacs#1823

### CODE REVIEW

**Comment by robbyoconnor** [comment]
People will assume that they will need to type the letters `S`, `p`, and then `c` -- this is a concern. it should be: `SPC` -- use do something like this in the org files:

```org
=SPC xxx=
```

**Comment by StreakyCobra** [comment]
@robbyoconnor What are you talking about? `SPC` is the current way of describing nearly all keybindings within Spacemacs, the few `<SPC>` should be corrected. And as far as I know this has never been a problem to understand for users. Also keybindings documentation in Spacemacs use `~` as surrounds, not `=`, so everything is fine on this side too.

After a quick check, this PR seems OK for me, correct PR branch, good commit message, org table aligned, …

**Comment by robbyoconnor** [comment]
@StreakyCobra, maybe I read it fast -- but they didn't do that =foo=

**Comment by StreakyCobra** [comment]
Thank you :+1: Cherry-picked into `develop`, you can safely delete your branch.

**Pull request closed without merging**
