### PR TITLE
Decouple CMake support from C-C++ Layer

### PR DESCRIPTION
**Pull request by myrgy**
Decouple CMake support from c-c++ layer as a part of layer cleanup (#10143)
added helm-ctest( #9980)

@syl20bnr, please, take a look.

### CODE REVIEW

**Comment by MaskRay** [comment]
Great for https://github.com/syl20bnr/spacemacs/issues/10143 !

**Comment by syl20bnr** [comment]
Thank you ! 👍 
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by cormacc** [comment]
Maybe I'm missing something, but can't get the cmake build commands described in the cmake layer readme anymore. Used to get them in the C layer command group -- they've disappeared from there, which kind of makes sense with the decoupling -- but when I open a CMakeLists.txt (triggering cmake mode), there's no modal menu under , or <space>-m
Layer config:

``` elisp
       (c-c++ :variables
         c-c++-enable-clang-support t
         c-c++-enable-rtags-support t
         )
       (cmake :variables
         c-c++-enable-cmake-ide-support t
         )
```
Build pool directory enabled in user-config

``` elisp
  (setq cmake-ide-build-pool-dir (file-truename "~/.cmake_builds"))
  (setq cmake-ide-build-pool-use-persistent-naming t)
```
scrubbed my .emacs.d directory yesterday and redownloaded all packages, so should be a fairly clean config. I am using melpa-stable.

**Comment by myrgy** [comment]
@cormacc , variables were renamed. https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Btools/cmake#cmake-ide-configuration
```
(cmake :variables
         cmake-enable-cmake-ide-support t
         )
```

**Comment by cormacc** [comment]
D'oh -- re-RTFM. Thanks myrgy!

**Pull request closed without merging**
