### PR TITLE
Refactor CONTRIBUTING documentations

### PR DESCRIPTION
**Pull request by StreakyCobra**
This commit merge the `CONTRIBUTING.md` and `doc/CONTRIBUTE.org` file
into a new `CONTRIBUTING.org` file. It also refactors the content to be
more organized and make its navigation more goal-oriented.

guidelines link

Github displays a link to the `CONTRIBUTING.*` file when people are
opening new issues or proposing new PRs. This file is important because
it is the entry-point to contributions guidelines for most of the users.
The current setup is non-optimal, even broken, as it adds a level of
indirection, and points to a contributing file that has broken
links (due to the new documentation format). The possible drawback of
the proposed solution is that I'm not sure if it is possible to include
it into the new online documentation as it is not in `doc/` folder.

The other possibility is to keep a small `CONTRIBUTING.md` file, as it
is now, pointing to the new documentation system (once online), but I'm
preferring the proposed solution for the following reasons:

- People that are willing to contribute will probably open Github
  first (for forking, creating PR, etc), not the online documentation.

- It has one level of indirection less when people click on the
  guidelines guide from a new issue/PR (and the link to the contribution page is lost in the middle of the page).

- `CONTRIBUTING.*` is by convention a special kind of file on github, so
  it's valid reason to break the rule and not having it in the `doc/`
  folder.

### CODE REVIEW

**Comment by nixmaniack** [comment]
I absolutely support this change with some suggestions below! When pointing contributors to this guidelines I myself go through this indirection which isn't good.

Suggestions/feedback. The guidelines doc seems pretty big for users who want to contribute small fixes. Right now in this PR those are buried much deeper. So instead making the user read whole thing, we should have a tl;dr in the starting stating at least following:
- Check github issues/PRs before creating new one.
- PRs must be against `develop` and not master.
- One commit per PR hence squash your commits(with exception for big changes)

**Comment by robbyoconnor** [comment]
Are you certain this will work? last I checked it had to be in markdown....unless I am wrong? Keep the guidelines short, sweet and to the point and link to the main doc -- why have it be so large?

**Comment by StreakyCobra** [comment]
@robbyoconnor https://github.com/StreakyCobra/test_contribute/issues/new

**Comment by robbyoconnor** [comment]
I am wrong, well ok..I withdraw my objection -- let's keep it short, sweet and to the poiint <3

**Comment by robbyoconnor** [comment]
Merge conflicts

**Comment by StreakyCobra** [comment]
Before working further on this I would like to know @syl20bnr opinion?

**Comment by syl20bnr** [comment]
Nice :+1: 
I made some modifications in commit https://github.com/syl20bnr/spacemacs/commit/3a9a130
Thank you !
Cherry-picked in develop branch, you can safely delete your branch.

**Pull request closed without merging**
