### PR TITLE
mask # in the org mode

### LINKED ISSUE #4399: Broken links in some .org files
The TOC links in the following files are broken (404):

* https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org
* https://github.com/syl20bnr/spacemacs/blob/master/doc/FAQ.org
* https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.org
* https://github.com/syl20bnr/spacemacs/blob/master/doc/LAYERS.org
* https://github.com/syl20bnr/spacemacs/blob/master/doc/QUICK_START.org
* https://github.com/syl20bnr/spacemacs/blob/master/doc/VIMUSERS.org
* https://github.com/syl20bnr/spacemacs/blob/master/layers/LAYERS.org
* layers/**/README.org (I haven't tried all of them)

I think the broken links were introduced in 13c5b1d (Nov 2, 2015).

PS: the TOC links in https://github.com/syl20bnr/spacemacs/blob/master/CONTRIBUTING.org are not broken.

-----
**Update:** Not only TOC links, but most (if not all) internal links.

### PR DESCRIPTION
**Pull request by JAremko**
With Emacs you can have your :cake: and eat it too :smile:  
It fixes #4399 ?

**Disclaimer**

no idea

*Not tested and probably misunderstood early morning pr*

### CODE REVIEW

**Comment by nixmaniack** [comment]
Looks like it doesn't allow you to open with `org-open-at-point` (`, l` or `C-c C-o`) from ToC. Custom id needed.

**Comment by JAremko** [comment]
@nixmaniack  At least it looks well. Might be with some extra magic it will work?

**Comment by robbyoconnor** [comment]
On the internet, nobody knows you're a dog.

**Comment by JAremko** [comment]
I think the most of new users rely on the github docs, it is important that the docs look well polished and definitely not have broken links. 

`org-open-at-point` can be fixed with a some kind of wrapper function and might be a special mode for the Spamecas doc headers. For example, add notation to the headers and if cursor is in the denoted block - enable special mode that fixes  `org-open-at-point`

**Comment by JAremko** [comment]
@robbyoconnor  Unless you post your selfie :dog:

**Comment by TheBB** [comment]
But if we want to revert to github links we should do it with `toc-org`, as we used to, and not manually like this.

There are three links that should work:

* Inside Emacs (works right now)
* Github (does not work right now)
* Exported (works right now)

This PR breaks two of them for the benefit of github. `toc-org` at least would keep it working in Emacs.

**Comment by nixmaniack** [comment]
Do we update docs on website with every change in doc? If not I would suggest reverting back to `toc-org` as it keeps Emacs and github working and for website generate docs in another branch with every release.

**Comment by JAremko** [comment]
@TheBB   This updates works properly. At the first glance.

**Comment by JAremko** [comment]
@nixmaniack   Or use sed to append `#`.  Then simply run Emacs in the batch mode over the *.org files to fix the links with  toc-org.

**Comment by JAremko** [comment]
I think I'll close it and we all gonna pretend that it never happened. Okay? /woof

**Pull request closed without merging**
