### PR TITLE
Update spacemacs-theme

### PR DESCRIPTION
**Pull request by nashamri**
Update the theme with the latest changes:
https://github.com/nashamri/spacemacs-theme/commit/a7e76aeb0a62f986e0469183728407c7bcbf4993
https://github.com/nashamri/spacemacs-theme/commit/d79fa1800c58c4e52b5faa4f4e0400622ef98f5b

### CODE REVIEW

**Comment by nashamri** [comment]
Not sure why Travis is failing to build :worried:

**Comment by JAremko** [comment]
@nashamri  Looks like usual installation glitch(melpa/Cask). I restarted tests.

**Comment by JAremko** [comment]
All green :+1:

**Comment by nashamri** [comment]
Awesome @JAremko

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
