### PR TITLE
Elisp tweaks

### PR DESCRIPTION
**Pull request by luxbock**

### CODE REVIEW

**Comment by dcluna** [comment]
Didn't review the PR per se, but according to [contribution guidelines](https://github.com/syl20bnr/spacemacs/blob/master/doc/CONTRIBUTE.org#ideally-and-for-simple-prs), there should be only **one** PR.

You also need to update your branch, so I'd ```git pull --rebase``` this branch, and then squash the 3 commits into one.

**Comment by StreakyCobra** [comment]
As said, this should be rebased and squased in order to get reviewed :-)

**Comment by Compro-Prasad** [comment]
@syl20bnr Any chances of getting this into spacemacs?

**Comment by syl20bnr** [comment]
Pheewww this is old :-)

I believe edebug is not supported in the emacs lisp layer.

What are the improvements for ielm exactly ?

**Comment by sdwolfz** [comment]
I'll go ahead and close this PR due to it's inactivity, and because some of the functionality is already present in the current develop. If somebody wants to revive it then please open a new PR with the bits missing and with an explanation in the message.

**Pull request closed without merging**
