### PR TITLE
Testing the tests

### PR DESCRIPTION
**Pull request by JAremko**
Testing the tests

### CODE REVIEW

**Comment by syl20bnr** [comment]
Keep it like this, I'll look at it when I have a chance.

**Comment by JAremko** [comment]
@syl20bnr  Feel free to merge.  I'm done with this one.

**Comment by syl20bnr** [comment]
Should be fixed with https://github.com/syl20bnr/spacemacs/commit/0ae2a4774

**Comment by syl20bnr** [comment]
Thank you 💯

**Comment by nashamri** [comment]
So meta!

**Pull request merged**
