### PR TITLE
Add elm lang layer for Spacemacs

### PR DESCRIPTION
**Pull request by usharf**
Initial work on an elm lang contribution layer, setup up with elm-mode, flycheck-elm and support for auto-completion.

PS completion-at-point not working yet

### CODE REVIEW

**Comment by srid** [comment]
:+1:

**Comment by usharf** [comment]
Updated. completion-at-point seems to working now.

**Comment by usharf** [comment]
@syl20bnr wondering if you had the time to review

**Comment by srid** [comment]
FWIW, indentation is totally off; hitting enter always indents it without taking the previous expression into consideration:

screen shot 2015-08-31 at 8 14 58 am

I've had troubles with Spacemacs in the past when using the Haskell layer. I got way annoying to the point I stopped using Emacs for hacking on Haskell (and right now I'm using Atom for working on Elm projects).

**Comment by usharf** [comment]
These are indentation issues  for this mode. The layer only wires things up to make it easy to compile and start the reactor, look up the docs and auto completion using oracle (depending on a nodejs module that you need to install ). 

I didn't hack on this layer for a while. If you see useful settings in the code that can be enabled, would love to add. 

 Ps Haskell mode for emacs supports different styles of indentation, some of which require installing additional Haskell packages and enabling these features in the laye explictly.  

Regardless, it is indeed difficult to get every thing working right out of the box.

**Comment by usharf** [comment]
Ps will look into disabling the electric feature that interacts with elm mode. :+1:

**Comment by usharf** [comment]
@srid I've updated the layer to disable electric-indent-local-mode.

As per my previous comment, when trying out your code snippet, typing <ENTER> after the type anon will still indent the way it used to. Pressing <TAB> will auto complete the function name after which you can start writing the function definition.

**Comment by srid** [comment]
It seems odd that I have to go through the tab cycle when it would make sense to always start with "foo =" after the type declaration (for what else can come after?). 

Anyways, everything looks good now ... and you may want to rebase against latest develop branch.

**Comment by mjs2600** [comment]
Is there anything else that needs to be done before this can be merged?

**Comment by syl20bnr** [comment]
Thank you :+1: 
I made various changes, you can read about them in commithttps://github.com/syl20bnr/spacemacs/commit/3c16fcf
I hope I did not break anything :-)
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
