### PR TITLE
Map the usual cmd keys for font scaling

### PR DESCRIPTION
**Pull request by zimbatm**
s-= to scale up
s-- to scale down
s-0 to reset

### CODE REVIEW

**Comment by cpaulik** [comment]
Aren't the normal cmd keys for font scaling:

- `C-+` to scale up
- `C--` to scale down

?

**Comment by syl20bnr** [comment]
This change has already been proposed and merged in develop. I don't know if it's conventional in OS X though.

**Comment by zimbatm** [comment]
@cpaulik on OSX it's Cmd-+ and Cmd--. I think spacemacs maps Cmd to s(uper?) and `=` is the lower-case `+` key so you don't have to Cmd-Shift-+.

@syl20bnr thanks, closing then

**Comment by cpaulik** [comment]
Ohh, I'm sorry. I didn't realize that this was for OSX only. Should also read the filename not only the diff :smile:

**Pull request closed without merging**
