### PR TITLE
Rust layer overhaul

### PR DESCRIPTION
**Pull request by whirm**
- Switch to Rustic, a more complete Rust mode
- Make rust-analizer backend the default and remove support for RLS and Racer (both unmantained and obsoleted by rust-analyzer)
- Add GDB Rust DAP template

### CODE REVIEW

**Review by smile13241324 — CHANGES_REQUESTED** [review]
I like your changes still it looks like you have removed support for cargo from packages.el but not from the documentation. Was this intended?

**Comment by whirm** [comment]
> I like your changes still it looks like you have removed support for cargo from packages.el but not from the documentation. Was this intended?

Rustic brings its own cargo support, I've double checked and realized it's not 1 to 1 with the `cargo.el` package feature wise so I've made some minor changes to the docs and updated the key bindings.

**Comment by whirm** [comment]
@smile13241324 ping!

**Review by smile13241324 — APPROVED** [review]

**Comment by smile13241324** [comment]
Looks good :), will be merged soon.

**Pull request merged**
