### PR TITLE
Fix .spacemacs validation choices

### PR DESCRIPTION
**Pull request by Claude-Ray**
Add choices for variables that are allowed to be nil

### CODE REVIEW

**Comment by smile13241324** [comment]
@JAremko I am not sure whether this makes sense, care to have a look?

**Comment by JAremko** [comment]
`dotspacemacs-major-mode-leader-key` makes sense. Not sure about `dotspacemacs-frame-title-format` is `nil`  simply removes the title?

**Comment by Claude-Ray** [comment]
> `dotspacemacs-major-mode-leader-key` makes sense. Not sure about `dotspacemacs-frame-title-format` is `nil` simply removes the title? If so then why not 🤔

When dotspacemacs-frame-title-format is nil, Spacemacs is using default frame-title-format instead of calculating title by spacemacs/title-prepare all the time.

This did help to avoid performance issues.

**Comment by JAremko** [comment]
@Claude-Ray  that's cool.  Can you update `dotspacemacs-frame-title-format` with info about `nil` ?

**Comment by JAremko** [comment]
And the comment above https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/.spacemacs.template#L454

**Comment by Claude-Ray** [comment]
Yes, my pleasure

**Comment by JAremko** [comment]
Thanks :+1:

**Pull request merged**
