### PR TITLE
Update ligature to disable some chars and only enable in prog-mode

### PR DESCRIPTION
**Pull request by AdeAttwood**
When ligatures are enabled globally emacs gets pined at 100% CPU. In #13967
there were some ligatures that were highlighted but enabling this only in
prog-mode so emacs dose not get pined at 100% when just enabling with
(unicode-fonts-enable-ligatures t). In #14178 it was highlighted that "\\" had
an issue in the `init.el` so this has been removed

- "//" Issues with doom mode line
- ".." "..." Issues with helm find file
- "--" Issues with magit
- "\\" Issue with init.el

### CODE REVIEW

**Comment by lebensterben** [comment]
The upstream package support per-mode ligature sets.
I thinks it's better to have `unicode-fonts-ligature-modes-alist` instead.

So the default value is then `((prog-mode . unicode-fonts-ligature-set))`

**Comment by AdeAttwood** [comment]
If you have `unicode-fonts-ligature-modes-alist` would you not have to have a map of all modes to ligatures

**Comment by lebensterben** [comment]
> If you have `unicode-fonts-ligature-modes-alist` would you not have to have a map of all modes to ligatures

The upstream recommends to set these

https://github.com/mickeynp/ligature.el/blob/c830b9d74dcf4ff08e6f19cc631d924ce47e2600/ligature.el#L71-L83

which includes a generic setting for `prog-mode`.

Specific major modes, if have its own ligature settings, should always take priority over the generic one. I haven't test this because ligature breaks `lsp-ui`. But this should to be an expected behavior

> Entering a programming language mode runs the custom Lisp functions specified in the hook variable prog-mode-hook, followed by those specified in the mode’s own mode hook (see Major Modes)

**Comment by AdeAttwood** [comment]
I am leaning towards getting this merged to fix the immediate issues of #14178 so emacs will load.

Then we can address the issue of setting different ligature sets per mode in a separate feature. Currently, the `unicode-fonts` layer dose not support this. I will be happy to work on it but may need some guidance on the lisp. I had to look up what the `alist` was and the dot in `((prog-mode . unicode-fonts-ligature-set))` did.

My main questions around the "setting different ligature sets per modes" is what will the config look like. I think we should keep the single toggle of `unicode-fonts-enable-ligatures` but this can be discussed in the issues if it gets split out.

**Comment by lebensterben** [comment]
@AdeAttwood Agree

**Review by smile13241324 — APPROVED** [review]
Fast workaround, lets merge it and do the details later.

**Comment by smile13241324** [comment]
I have merged the workaround and adjusted the documentation to state the new default setting. 

Lets have a separate issue for the ligature alist discussion. This could be done in a similar fashion how company settings are done, this is the individual layers define a `pre-init-ligature-mode` function where the alist is extended with mode specific settings. Same thing is done for the `purpose-config`.

**Pull request merged**
