### PR TITLE
Add Testify support for layers/+lang/go

### PR DESCRIPTION
**Pull request by mathieupost**

### CODE REVIEW

**Comment by duianto** [comment]
The new variable should probably be mentioned in the documentation:
https://github.com/syl20bnr/spacemacs/tree/develop/layers/+lang/go#tests

**Comment by mathieupost** [comment]
> The new variable should probably be mentioned in the documentation:
> https://github.com/syl20bnr/spacemacs/tree/develop/layers/+lang/go#tests

Fixed ;)

**Comment by duianto** [comment]
Thank you for contributing to Spacemacs.
The PR has been cherry picked into the `develop` branch. It's safe to delete your branch.

**Comment by duianto** [comment]
There's a comment on this PRs commit.
>This change broke spacemacs/go-run-test-current-function for me.

> Now I'm always getting:
> `go test -run='$'`
> although cursor is in the test function.
> 
> Reverting reqexp in re-search-backward to the one before this commit works fine, for example:
> `go test -run='TestMyTestFunctionName$'`
> 
> I'm using plain tests without testify or gocheck.

https://github.com/syl20bnr/spacemacs/commit/272c96d855bbf4fe90ca896ef15fa25a4dda4d0a#commitcomment-34992834

Can either of you @mathieupost @martijnjanssen take a look?

**Comment by mathieupost** [comment]
I'll look into it 👍🏻

**Pull request merged**
