### PR TITLE
Allow choice of ivy for completion

### PR DESCRIPTION
**Pull request by justbur**
This is a work in process, because there's a lot to do to accomplish this. 

This is a proposal to introduce a choice of completion tool to spacemacs. I'm experimenting with removing helm completely and replacing it with ivy. I don't expect a one for one match, but I like the simplicity of ivy and I expect that it should be easily extensible. 

I'll slowly add to this, but please feel free to submit suggestions.

TODO:
- [x] Replace helm-ag functionality with counsel-ag
- [x] Conditionally exclude helm from remaining layers that use it as a dependency

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Following.

**Comment by d12frosted** [comment]
:+1: Found `ivy` few days ago and was wondering about using it instead of helm.

**Comment by bmag** [comment]
thank you, looking forward for this :+1:

**Comment by scloudyy** [comment]
Good job, I want to try it

**Comment by justbur** [comment]
> Good job, I want to try it

@scloudyy you can checkout the ivy branch on my fork of spacemacs if you want to try it. I've been using it for a few days without problems. There's just some stuff missing. I'll make a todo list for the pr

**Comment by CestDiego** [comment]
ivy <3

**Comment by CestDiego** [comment]
Heeeey

```emacs-lisp
  (defun cestiego/pretty-symbols (new-pretty-symbols)
    (mapcar (lambda (item)
              (push item prettify-symbols-alist))
            new-pretty-symbols))
```
k

**Comment by nixmaniack** [comment]
This is nice! :+1:

**Comment by syl20bnr** [comment]
Wow impressive job :purple_heart: 
 
Instead of hacking `spacemacs-base` layer I would go for two layers:
- spacemacs-helm
- spacemacs-ivy

Then the only place when the dotspacemacs variable is used is in spacemacs layer's `config.el` using `configuration-layer/declare-layer`.
Everywhere else we use `configuration-layer/layer-usedp`.
This will better fit the spacemacs architecture and allow `helm-spacemacs` and `ivy-spacemacs` to correctly being able to list all the packages no matter the completion tool used.

Feel free to rename the local package `helm-spacemacs` and `ivy-spacemacs` to something else to avoid the confusion with the layer names, maybe `helm-spacemacs-doc` and `ivy-spacemacs-doc` ?

**Comment by justbur** [comment]
@syl20bnr I thought about that, but then how would it show up in the spacemacs layer? Is that where `...layer-usedp` would show up? Would `helm-ag` stay here or be in `spacemacs-helm`? I know there's many ways to do this. 

> This will better fit the spacemacs architecture and allow helm-spacemacs and ivy-spacemacs to correctly being able to list all the packages no matter the completion tool used.

On that point, that seems to be a problem with the way packages are listed in `helm-spacemacs`. Shouldn't they only be listed if they are in the `-packages` variable *and* have an init function?

**Comment by syl20bnr** [comment]
Yes `helm-ag` should go in `spacemacs-helm`, basically all helm related packages of `spacemacs` layer should go in `spacemacs-helm`. In the other layers `configuraton-layer/layer-usedp` should be used, like it is the case fo `auto-completion`.

`helm-spacemacs` shoud list all the layers and packages provided by Spacemacs even if they are not used so they are all discoverable and reachable.

I'm not for the conditional append to `-packages` lists but for few packages I allowed it for now. In this case this is too much heavy to not rely on the spacemacs layer architecture though.

**Comment by justbur** [comment]
@syl20bnr I'll get rid of the conditional append and switch to this style. I was doing it because it started to get messy wrapping so many init functions in guards, but this new organization will make it better.

**Comment by justbur** [comment]
@syl20bnr See how that looks to you

**Comment by robbyoconnor** [comment]
Is there a way to use both or is it one or the other?

**Comment by robbyoconnor** [comment]
@justbur -- merge conflicts

**Comment by d12frosted** [comment]
> Is there a way to use both or is it one or the other?

I don't think it's doable having both for completion (as both setup `completing-read-function`). But I think it's possible to switch from one to another.

**Comment by robbyoconnor** [comment]
Yeah -- I mean if ivy is faster than helm -- I'd be happy to switch

**Comment by justbur** [comment]
> Yeah -- I mean if ivy is faster than helm -- I'd be happy to switch

@robbyoconnor I don't know if it's going to be faster everywhere. It certainly should load quicker. The advantage to ivy as I see it is it's much simpler than helm and seems easier to extend. I already wrote my own simple version of helm-ag for spacemacs in this pr for example. 

I resolved the merge conflicts. @syl20bnr if you're interested in merging this it would be helpful for me to tell me how you want it organized. This might be a pain to keep up to date with develop, so I don't want to do that for a long time. Also, if you want me to rebase or squash or something, I'd rather do it sooner rather than later. I merged some commits from @a-sk, so it's not going to be trivial to squash this down (I don't even know the best way to do that at the moment).

**Comment by syl20bnr** [comment]
@justbur I plan to merge it quickly, rewrite the history the best as you can to keep only the minimum number of commits like only on commit for `ivy-spacemacs-help` etc... if possible. It may be easier to start a new branch and recreate the commits in a logical order and then submit a new PR.

**Comment by justbur** [comment]
@a-sk I want to squash this down into a logical series of commits. Would you be offended if I removed your commits?

**Comment by syl20bnr** [comment]
Maybe @a-sk commits could be applied on top of the new commit graph, they seems to be quite local and easy to move. @justbur in case you don't know you can move commits up and down with `J` and `K`, if you knew my apologies :-)

**Comment by justbur** [comment]
@a-sk You can ignore my previous question. I figured it out

**Comment by person808** [comment]
Pretty cool! `SPC f J` also needs to be ported

**Comment by justbur** [comment]
What's fJ?

**Comment by person808** [comment]
@justbur It's `spacemacs/helm-open-junk-file` which is part of the `open-junk-file` init

**Comment by justbur** [comment]
Ok that's doable.

**Comment by justbur** [comment]
@person808 I think I ported the function correctly. I wasn't sure if the directory should be created for the junk file or not.

**Comment by syl20bnr** [comment]
Planned to be merged tomorrow night ;-)

**Comment by CestDiego** [comment]
omg looking forward to this. @syl20bnr is ivy that much better than helm?

**Comment by tuhdo** [comment]
So, is `ido` the default completion method since Helm exists as a layer, or Helm is still the default to be used, and Ivy is only enabled when set?

**Comment by tuhdo** [comment]
I don't know after a year, Ivy improves that much but when testing with fuzzy matching on 210k files, Helm did really well: https://github.com/syl20bnr/spacemacs/pull/1150 while Ido hanged at 20k files or more. Many packages have no Ivy equivalent in many layers.

I assume that this PR only offers `ivy` as a completion choice but not replacing Helm entirely.

**Comment by tuhdo** [comment]
I've just tested with `counsel-M-x`: typing this query `find file proj` gives me this:

```text
helm-projectile-find-file-in-known-projects
projectile-find-file-in-known-projects
```

instead of a bigger list with `projectile-find-file`. Ivy is still missing feature like multi-candidates selection.

**Comment by justbur** [comment]
> So, is ido the default completion method since Helm exists as a layer, or Helm is still the default to be used, and Ivy is only enabled when set?

The basic logic in there now (which probably needs improving) is that if neither is selected and the user is using the spacemacs distribution it defaults to helm.

This is just to offer a choice at the moment, and we are not close to replicating all of the packages/features that helm provides with spacemacs. 

There's no sense in trying to coronate one as "better". They're different and people might have their reasons for choosing one over the other.

**Comment by syl20bnr** [comment]
Postpone to tomorrow :-(

**Comment by syl20bnr** [comment]
Thank you, **outstanding work!** :100:  :purple_heart: 
Merged in develop !

I updated the wizard to be able to choose the completion framework, we start to be really able to tailor spacemacs, for instance choosing the spacemacs-base + ivy distribution.

**Comment by tuhdo** [comment]
@syl20bnr Don't you think it will be confusing for new users, since they don't even know what Helm and Ivy are yet?

**Comment by person808** [comment]
I agree with @tuhdo. The prompt in the setup seems a bit vague

**Comment by syl20bnr** [comment]
@tuhdo @person808 If you refer specifically to `helm` and `ivy`, yes indeed, but the wizard does not, it asks for what kind of completion framewerk the user may prefer, we can offer a full-fledged heavy one, or a lighter one but still very capable and in parenthesis it is the "value" of each choice.

**Comment by syl20bnr** [comment]
The defaults are pre-selected so we can add in the docs that for a default Spacemacs installation user has just to hit enter and it should fix the "I don't know or I just don't want to know for now" ;-)

**Comment by tuhdo** [comment]
@syl20bnr yes that would be good. Since many layers have Helm exclusive packages, we should prompt Helm as default. After all, you can think of Helm as a superset of Ivy.

**Pull request closed without merging**
