### PR TITLE
replace cider-turn-on-eldoc-mode with eldoc-mode

### PR DESCRIPTION
**Pull request by haroldcarr**
replace 

    (add-hook 'cider-mode-hook 'cider-turn-on-eldoc-mode)

with

    (add-hook 'cider-mode-hook 'eldoc-mode)

see: https://groups.google.com/forum/#!topic/clojure/suo83_S3Luo

### CODE REVIEW

**Comment by NJBS** [comment]
This was already solved by https://github.com/syl20bnr/spacemacs/pull/5748.

**Comment by StreakyCobra** [comment]
I suppose the issuer problem is regarding the bug being present on the `master` branch, where it hasn't been hotfixed yet. It's marked as such in https://github.com/syl20bnr/spacemacs/pull/5578, so closing this one.

**Comment by syl20bnr** [comment]
I hope to release the 0.105.19 this evening but it may be tomorrow.

**Comment by haroldcarr** [comment]
Correct - looking forward to seeing this in master.  Thanks.

**Pull request closed without merging**
