### PR TITLE
Add a key combination to format elm files

### PR DESCRIPTION
**Pull request by AetherLorde**
Add a key combination to format elm files

### CODE REVIEW

**Comment by syl20bnr** [comment]
What is your editing style?
Have you tried to select some text and press `=` ?

**Comment by syl20bnr** [comment]
Oh this is a PR, sorry... :-)

**Comment by syl20bnr** [comment]
Thank you ! 👍 
I changed the key binding in commit https://github.com/syl20bnr/spacemacs/commit/7df7233 to `SPC m = b` to reflect the conventions (https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org#L343-L350), this conventions were not explicit before, I added them in commit https://github.com/syl20bnr/spacemacs/commit/bd50484
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by AetherLorde** [comment]
Awesome! Thank you!

**Pull request closed without merging**
