### PR TITLE
Add alex-hhh's sql-indent in place of mepla sql-indent

### PR DESCRIPTION
**Pull request by andrew-christianson**
This replaces the MELPA sql-indent with a supported and far more featureful implementation: https://github.com/alex-hhh/emacs-sql-indent

### CODE REVIEW

**Comment by syl20bnr** [comment]
I agree to replace this package when alex-hhh's fork replaces the package in MELPA.

**Comment by syl20bnr** [comment]
Oh: https://github.com/alex-hhh/emacs-sql-indent/issues/5#issuecomment-348638509

It is now part of GNU ELPA, I guess we can switch to it then, can you update the PR ?

**Comment by andrew-christianson** [comment]
updated to ELPA's version of sql-indent.

**Comment by syl20bnr** [comment]
Thank you ! 👍 
Actually we need to use the recipe as there is no way for now to privilege GNU ELPA over MELPA when the package is in both repositories. I added a comment to explain this.
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
