### PR TITLE
[RDY] Implement modeline DSL

### LINKED ISSUE #524: Mini DSL to define powerline segment
Right now we have huge monolithic blocks for the powerline. It is time to move them to the next level.

This task is about the definition of a mini DSL to define segments and compose them together easily.

The ultimate goal is to be able to define segments in package init functions and append them in arbitrary order to compose them, the render engine should be able to compute a clean powerline, i.e. it should take into account the separator directions as well as choosing the right background colors for them.

This is some work that could be contributed in upstream powerline repository.

### LINKED ISSUE #2283: Powerline truncated with many vertical windows
When I have three vertical windows open, the modeline is truncated and some vital info is not showing like `git branch`, `line-nb` and `col-nb`. Turning off unicode symbols and renaming my minor modes to two-letter names helps.

I'd especially like to turn off `major` and `minor` mode indicators.

Probably not possible as of now, just something to think about for the next version.

https://github.com/syl20bnr/spacemacs/issues/524

### LINKED ISSUE #2386: Highlight remote buffer name in mode line
I'm a long-time emacs user, using spacemacs for only a couple of days. So far I miss very little from my old emacs configuration, and am really impressed with spacemacs.

One small thing I do miss is highlighting remote buffers in the mode-line. This way if you are visiting a remote file with the same name as a local file you are also visiting you never get confused about which is which. 

I tried adding the relevant bit from my old config so I could submit this as a pull request, but I couldn't figure out where/how exactly the mode line is configured in spacemacs. The relevant bit from my config are below. The important bits are defining the format string (`(defconst my-mode-line-buffer-identification ...`) and adding `(powerline-raw my-mode-line-buffer-identification nil 'l)` to the `(lhs (list ...` in `mode-line-format`.

If someone can point me toward the entry point for modifying the mode-line in spacemacs I'll be happy to submit a PR, or feel free to grab anything useful from the code below if you want to implement this in spacemacs.

Thanks.

```elisp
;; face for remote files in modeline
(defface my-mode-line-attention
'((t (:foreground "magenta" :weight bold)))
 "face for calling attention to modeline")

;; highlight hostname if on remote
(defconst my-mode-line-buffer-identification
  '(:eval
    (list
     (propertize
      (if (file-remote-p default-directory 'host)
          (progn
      (let ((host-name
             (or (file-remote-p default-directory 'host)
                 (system-name))))
        (if (string-match "^[^0-9][^.]*\\(\\..*\\)" host-name)
            (substring host-name 0 (match-beginning 1))
          host-name)))
        "")
      'face
      (if (file-remote-p default-directory 'host)
          'my-mode-line-attention
        'mode-line-buffer-id))
   (propertize ": %b"
               'face
                 (if (file-remote-p default-directory 'host)
                     'my-mode-line-attention
                   'mode-line-buffer-id)))))

;; powerline theme using above info about remote hosts.
(defun powerline-my-theme ()
  "Setup the default mode-line."
  (interactive)
  (setq-default mode-line-format
                '("%e"
                  (:eval
                   (let* ((active (powerline-selected-window-active))
                          (mode-line (if active 'mode-line 'mode-line-inactive))
                          (face1 (if active 'powerline-active1 'powerline-inactive1))
                          (face2 (if active 'powerline-active2 'powerline-inactive2))
                          (separator-left (intern (format "powerline-%s-%s"
                                                          powerline-default-separator
                                                          (car powerline-default-separator-dir))))
                          (separator-right (intern (format "powerline-%s-%s"
                                                           powerline-default-separator
                                                           (cdr powerline-default-separator-dir))))
                          (lhs (list (powerline-raw "%*" nil 'l)
                                     (powerline-buffer-size nil 'l)
                                     (powerline-raw mode-line-mule-info nil 'l)
                                     (powerline-raw mode-line-remote nil 'l)
                                     (powerline-raw my-mode-line-buffer-identification nil 'l)
                                     (when (and (boundp 'which-func-mode) which-func-mode)
                                       (powerline-raw which-func-format nil 'l))
                                     (powerline-raw " ")
                                     (funcall separator-left mode-line face1)
                                     (when (boundp 'erc-modified-channels-object)
                                       (powerline-raw erc-modified-channels-object face1 'l))
                                     (powerline-major-mode face1 'l)
                                     (powerline-process face1)
                                     (powerline-minor-modes face1 'l)
                                     (powerline-narrow face1 'l)
                                     (powerline-raw " " face1)
                                     (funcall separator-left face1 face2)
                                     (powerline-vc face2 'r)))
                          (rhs (list (powerline-raw global-mode-string face2 'r)
                                     (funcall separator-right face2 face1)
                                     (powerline-raw "%4l" face1 'l)
                                     (powerline-raw ":" face1 'l)
                                     (powerline-raw "%3c" face1 'r)
                                     (funcall separator-right face1 mode-line)
                                     (powerline-raw " ")
                                     (powerline-raw "%6p" nil 'r)
                                     (powerline-hud face2 face1))))
                     (concat (powerline-render lhs)
                             (powerline-fill face2 (powerline-width rhs))
                             (powerline-render rhs)))))))

(powerline-my-theme)
```

### PR DESCRIPTION
**Pull request by TheBB**
In summary:

- Fixes, or goes some ways to fix #524
- Fixes #2386 (adds remote host in modeline)
- Fixes #2283 (adds toggles for major mode and version control)
- Removes `SPC t m f` since it's the same as `SPC t s`

### CODE REVIEW

**Comment by chrisbarrett** [comment]
Yo, please prefix your utility functions with `spacemacs/`. :)

**Comment by TheBB** [comment]
I was wondering about that. There's heaps of functions in that file that aren't prefixed.

**Comment by chrisbarrett** [comment]
Yeah, looking at that file now and feeling sadness. :'(

Eivind Fonn writes:

**Comment by robbyoconnor** [comment]
Not to be that guy but there should be tests for this...I hate writing tests, not it *touches nose*

**Comment by TheBB** [comment]
Barring tests, which I will have a look at, this PR is now ready. It produces the same modeline as is default in current spacemacs (with some changes which are mostly insignificant or slight improvements, IMO), but it makes it easily configurable using the `spacemacs|define-mode-line-segment` macro and the variables `spacemacs-mode-line-left` and `spacemacs-mode-line-right`.

There are other things I would like to do, but we can leave that for future PRs. For example moving the definition of segments into the relevant layers. This requires either modeline evaluation to check whether the segment is defined (probably the easiest way—it's annoying that the modeline doesn't display for simple errors), or we have to make a cleaner way to build the default value of the variables `spacemacs-mode-line-(left|right)`.

**Comment by TheBB** [comment]
As far as I can tell, there is no test framework for anything outside of `core/`. Not sure how involved it would be to test a layer that depends on packages (such as the `spacemacs` layer). It's huge and woefully untested, but that seems out of scope for this PR.

**Comment by TheBB** [comment]
Rebased and updated. This now includes a fix for #2386 and a number of toggles slimming the modeline (for #2283).

I removed `SPC t m f` since it does exactly the same thing as `SPC t s`.

**Comment by robbyoconnor** [comment]
<3

**Comment by syl20bnr** [comment]
Impressive work and fit perfectly #524 directions ! Thank you ! :100: 

Next step is to move the segments to init functions, we will still have to compose the mode line at a central place (I don't how we could do differently) but segments can be ignored if they don't exist.

My favorite PR to date :+1: 

Cherry-picked into `develop` branch, you can safely delete this branch.

**Comment by robbyoconnor** [comment]
Did this break the modelines currently? I rebased and suddenly have no modeline and getting **TONS** of errors

**Comment by syl20bnr** [comment]
@TheBB I forgot to mention my tweaks:

- made battery info in active mode line only commit: https://github.com/syl20bnr/spacemacs/commit/bf2d840
- tweaked some key bindings, see commit message: https://github.com/syl20bnr/spacemacs/commit/5f0c706

**Comment by syl20bnr** [comment]
@robbyoconnor working here, let me try on a clean install

**Comment by robbyoconnor** [comment]
let me nuke my `elpa`

**Comment by syl20bnr** [comment]
It works great with a fresh develop install. Can you open an issue ?

**Comment by robbyoconnor** [comment]
You should probably document what I need to change in my `~/.spacemacs` -- opened #2421

**Comment by CestDiego** [comment]
Is this really happening? :O what cool things might this bring? btw I don't see any problems here.

**Comment by syl20bnr** [comment]
@CestDiego It is now really really easy to customize the modeline, you can define your own segment with `spacemacs|define-mode-line-segment` macro and then you combine them by creating a lists with segment names: `spacemacs-mode-line-left` and  `spacemacs-mode-line-right`, default arrangement is here: https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L2675-L2709

**Pull request closed without merging**
