### PR TITLE
Disable guide key in bzg

### PR DESCRIPTION
**Pull request by endrebak**
Using `bzg` and big-fringe-mode causes serious trouble for me. I want to use guide-key-mode all the time, except when using bzg. This minor tweak enables this.

### CODE REVIEW

**Comment by syl20bnr** [comment]
I add to disable guide-key to not disturb the micro-states, so there is a better way to disable now (in develop branch): https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L1248-1253
With this advice you can check for `bzg-big-fringe-mode` and then prevent the guide-key from popping.

Sorry for the implementation change.

**Comment by endrebak** [comment]
Thanks!

**Comment by endrebak** [comment]
@syl20bnr Erm, did you want me to do this just in my own `.spacemacs` or may I add a pull request for this?

**Comment by syl20bnr** [comment]
@endrebak make a PR with an update advice that take care of bzg minor mode.

**Comment by endrebak** [comment]
Woud love to.

**Pull request closed without merging**
