### PR TITLE
Add layer for orgwiki package

### PR DESCRIPTION
**Pull request by swaroopch**
- https://caiorss.github.io/org-wiki/
- https://github.com/caiorss/org-wiki

### CODE REVIEW

**Comment by immigrantsheep** [comment]
Tried to configure this locally but to no avail. How did you make it work?

**Comment by swaroopch** [comment]
@immigrantsheep What is the error?

**Comment by immigrantsheep** [comment]
I'm getting "Some test failed" and the only one failing is org-wiki

**Comment by swaroopch** [comment]
@immigrantsheep I'm using it with latest develop branch without any error messages, so I'm not sure how to debug this. If you can provide full details on how to reproduce this error, then I can take a look.

**Comment by immigrantsheep** [comment]
Sorry, it was my mistake. I thought the layer name was org-wiki instead of orgwiki. Working perfectly now :)

**Comment by swaroopch** [comment]
Closing due to inactivity.

**Comment by gsastry** [comment]
@swaroopch Thanks for working on this. Are there plans to get this merged?

**Comment by gone** [comment]
I'd also love this merged

**Comment by swaroopch** [comment]
@gsastry @gone Please feel free to take the code and submit it as your own code. I had closed this pull request as there was no feedback in one year since opening the pull request.

**Comment by sebhahn** [comment]
@syl20bnr Any plans to add this layer in the future?

**Comment by FryJay** [comment]
Thanks for this, I really wanted to give org-wiki a try in Spacemacs and this helped me get started.

It looks like they've changed some of the functions for org-wiki so some of the bindings no longer work.  I fixed most of the bindings but can't get the asset link working yet.  The commands I chose aren't necessarily the exact same functionality as before.

I changed the following:
- org-wiki-asset-open -> org-wiki-dired-all
- org-wiki-insert -> org-wiki-insert-link
- org-wiki-make-page -> org-wiki-insert-new

**Comment by srgkoshelev** [comment]
I second the request of this being added to spacemacs (as org-brain has terrible issues for me)

**Comment by aswinmohanme** [comment]
I third this pull request , it would be nice to have this

**Comment by duianto** [comment]
@swaroopch Do you want to work on this? You've done the majority of the work already.
Otherwise I have a local WIP branch with the changes below, that I can update when the key bindings issues below are fixed, Then I can push it to the develop branch.

@FryJay Do you have a working setup with fixed/replacement key bindings?

#### Request for help
Can someone help with testing and fixing the broken key bindings mentioned below.
Possibly adding/removing any new and useful/obsolete key bindings.

#### Question
Should the key bindings (when they are working) also be bound under the org major mode prefix: 
`SPC m w` or `, w`.
`w` seems to be available.

### Key bindings

#### Working
`SPC a o w h` [org-wiki-index]
Creates an `index.org` file.
messages:
Created wiki link.
Created wiki-asset-sys link.
Saving file c:/Users/username/org/wiki/index.org...
Wrote c:/Users/username/org/wiki/index.org

`SPC a o w j` [org-wiki-helm]
seems to also work, it opens a helm buffer.

#### Not sure if this is working or is broken
`SPC a o w d` [org-wiki-asset-open]
I've seen this message before:
>org-wiki--concat-path: Wrong type argument: stringp, nil

And once the windows 10 file explorer opened, but it closed after a couple of seconds (maybe it crashed).
Now when I press the key binding in a `index.org` buffer that was created with `SPC a o w h`.
Then the Spacemacs frame loses focus, but nothing else seems to happen.

#### Broken
`SPC a o w a` [spacemacs/orgwiki-insert-asset-link]
shows the error message:
>let: Wrong number of arguments: (1 . 1), 2

`SPC a o w i` [org-wiki-insert]
message:
>command-execute: Wrong type argument: commandp, org-wiki-insert

`SPC a o w n` [org-wiki-make-page]
message:
>command-execute: Wrong type argument: commandp, org-wiki-make-page

### PR Changes
- Squashed the commits.
- Added two changelog.develop entries.
  - Added a new Emacs section in the New layers:
```
**** Emacs
- orgwiki (thanks to Swaroop C H)
```
  - Added a new Orgwiki section in Layer changes and fixes:
```
**** Orgwiki
- Key bindings:
  - ~SPC a o w a~ Insert asset link
  - ~SPC a o w d~ Open asset directory for current page
  - ~SPC a o w h~ Go to home page
  - ~SPC a o w i~ Insert page link
  - ~SPC a o w j~ Jump to page (if helm enabled)
  - ~SPC a o w n~ Create new page
    (thanks to Swaroop C H)
```
- README.org
  - Removed a layer template comment:
```
# TOC links should be GitHub style anchors.
```
  - Added a Features section
Copied from the org-wiki package readme:
```
** Features
- A wiki system for Emacs.
- Search wiki pages quickly.
- Create new wiki pages fast.
- Command to export all pages to html without block Emacs.
  =M-x org-wiki-export-html-sync=
- Search wiki pages by its content. (grep)
- org-mode protocol to create and open wiki pages.
- org-mode protocol to open attachment/asset files with default system application.
- Automatic download of attachment files with:
  - =M-x org-wiki-asset-download-insert1=
  - =M-x org-wiki-asset-download-insert2=
```
Features section change:
The `org-wiki/export-html-async` command has been rename to:
`org-wiki-export-html-sync`

source:
Refactor function org-wiki-export-html-async to org-wiki-export-html-sync.
https://github.com/caiorss/org-wiki/commit/10955e4fa3cefb47b2463217b6f6e407ddd0acff

**Comment by swaroopch** [comment]
@duianto Unfortunately I don't use org-wiki any more, so I would have to step back from this. Thank you for asking.

**Comment by duianto** [comment]
How should we handle the Author entry in the header files?
Your the original author of this layer, but you probably don't want to be contacted if someone discovers an issue and finds your email in the header.

**Comment by swaroopch** [comment]
@duianto I'm okay to forego attribution. Thank you.

**Comment by duianto** [comment]
JAremko came up with a solution. We'll add a comment that you won't provide support for this layer, and any issues should be reported to Spacemacs.

So the attribution will remain unchanged. 👍

**Comment by swaroopch** [comment]
@duianto That's kind of you. Thank you for all your community work on Spacemacs!

**Pull request closed without merging**
