### PR TITLE
org: change keybindings for org-agenda-mode

### PR DESCRIPTION
**Pull request by mskorzhinskiy**
I'm actively using org-agenda-mode and facing with some troubles with current evilification of org-agenda-mode. So I want to change some of keybindings and place new one.

Key bindings for calendar
----------------------------------
There are two particular reasons why I've changed this bindings:

1. Emacs in-calendar navigation bindings are "Shift + arrows". So Shift + hjkl is more similar to the old emacs bindings and so they may be less confusing. (IMHO)
2. Binding "M-h" doesn't work for some reason.

Major-mode bindings for agenda-mode
------------------------------------------------------
I confused that evilified agenda mode lacks support of major mode keybindings like "SPC m s" and in evilified agenda buffer you should use "C-c C-s" instead. For my opinion, as far as agenda and org mode is very similar modes, they should have similar keybindings too. So I've tried to add missed major-mode bindings to the agenda mode.

### CODE REVIEW

**Comment by TheBB** [comment]
Don't use evilification to make leader bindings. Use `spacemacs/set-leader-keys` and `spacemacs/set-leader-keys-for-mode`. There should be examples of the latter in the org layer already.

**Comment by mskorzhinskiy** [comment]
I'm really don't want to create leader keybindings in evilifcation code. But for some reason spacemacs/set-leader-keys-for-mode doesn't work. Keybinding just doesn't appear. There are nothing in *Messages* buffer.

I've put code in description so if you don't mind, take a look to this code and say where I'm wrong. I have a theory that set-leader-keys-for-mode doesn't works for evilified modes for some fundamental reason. I've looked to most of evilified modes and failed in searchings for evilified mode with defined leader keys specially for this mode.

**Comment by TheBB** [comment]
Indeed, it doesn't work. But then the right thing to do is to figure out what's wrong (that is, ping @justbur :smile:). We can't have code like this.

**Comment by mskorzhinskiy** [comment]
I did not expect that this PR will be merged. I'm expect that somebody shows me direction then I hack this thing and finally I re-commit my changes. May be I should add [WIP] tag?

Write to the author of the spacemacs/set-leader-keys-for-mode, instead of asking questions to the random people on the channel, is a good and obvious idea, yes. It should be one of the first things that have be done. So, waiting for the @justbur comments.

**Comment by justbur** [comment]
Yep, that was a bug. Fixed in #4503

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

I sorted the bindings in https://github.com/syl20bnr/spacemacs/commit/c62b294b9d3ea7052ffc55af9c7b1886c4631f47. I also changed clock-cancel to `Q` since you had two bindings on `q`.

After thinking about it for a while I decided to leave out the changes to the calendar bindings. The reason being that it's counterintuitive for shift+letter bindings not to enter text in the minibuffer, and I don't see exactly what is more convenient about using shift instead of alt. I like that the current ones mirror the evil-org bindings to some extent. I'd be happy to discuss that in an issue though. :-)

**Comment by TheBB** [comment]
Hang on, I just read your OP again. Let me give it another go.

**Comment by TheBB** [comment]
Okay, I still think I disagree. But, as I said, I don't mind discussing it. `M-h` works here, if it doesn't work for you that might be a bug.

**Comment by mskorzhinskiy** [comment]
I'm also spend some time to thinking about this calendar bindings. The mainline of my arguments about convenience is the idea that "hjkl" is just another types of arrows. So for me it was quite surprising  that for one arrow you should use one modifier and for other - another.

But, as far as evilified state used to provide "vim" state, it would be better to orient to the vim users -- I agree with you point about surprising from not-inserting capitalized h, j, k or l. I'm already surprised from mu4e, where you just can't use "j" for next line -- it mapped to the [j]ump. Also we should consider that people already using spacemacs with evilified org.

So, I don't want to argue about bindings. Still there is a bug with "M-h", I will create an issue. 

Thanks for reviewing my patch!

**Pull request closed without merging**
