### PR TITLE
Fix bug: evil-magit not initailized inside 'keyboard-layout' layer

### PR DESCRIPTION
**Pull request by ACEMerlin**
The Issue: https://github.com/syl20bnr/spacemacs/issues/10133

### CODE REVIEW

**Comment by syl20bnr** [comment]
I think we should split the configuration into `magit` and `evil-magit`. With the current proposal people in holy mode won't get the correct keybindings as `evil-magit` is not initialized at all for them.

**Comment by ACEMerlin** [comment]
not sure how to fix this. FYI evil-magit initialized 2 times inside git layer, seems a bit redundant.

**Comment by nixmaniack** [comment]
@ACEMerlin Where do you see `evil-magit` initialized twice? Could you point to the code?

**Comment by Electron-libre** [comment]
Don't understand why is this closed. It's not merged in develop and this issue is not fixed.

**Comment by nixmaniack** [comment]
> not sure how to fix this 

perhaps because of this @Electron-libre. Help needed in short!

**Pull request closed without merging**
