### PR TITLE
Creates a really basic, early stages purescript layer.

### PR DESCRIPTION
**Pull request by kofno**
Leverages:
- purescript-mode
- psci

### CODE REVIEW

**Comment by syl20bnr** [comment]
Sorry for the late review.

The README.md is missing.
The logo should have a height of 200px and a transparent background would be better ;-)

**Comment by kofno** [comment]
OK. I'm going out of town tomorrow for the weekend. Will try to get to that asap, but may not be until next week.

**Comment by syl20bnr** [comment]
No problem, take your time. Happy Easter :-)

**Comment by kofno** [comment]
OK. I found the README.md and fixed up the logo.

**Comment by syl20bnr** [comment]
Great ! Thank you ! :+1: 
I updated the key bindings to better fit the conventions in commit 81b38d0aba7f669a34dd7d6441fec50d51a5173f

Cherry-picked into `develop`, you can safely delete your branch.

**Pull request closed without merging**
