### PR TITLE
Fix spelling error in NeoTree Key Hints

### PR DESCRIPTION
**Pull request by apeckham**
Changed "horizonatal" to "horizontal" in NeoTree key hints. Thanks!

### CODE REVIEW

**Comment by syl20bnr** [comment]
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by franciscod** [comment]
I was about to send a PR fixing this, but the default PR text discouraged me about merging into master. I read https://github.com/syl20bnr/spacemacs/blob/master/CONTRIBUTING.org and found nothing about when a commit on develop goes into master. Any docs regarding this? Thanks!

**Comment by robbyoconnor** [comment]
It happens when a release is cut. the master branch always contains the
most stable code. develop branch is bleeding edge and prone to breaking
from time to time. You must know how to work with git if you use develop.

**Comment by robbyoconnor** [comment]
It happens when a release is cut. the `master` branch always contains the
most stable code. The `develop` branch is bleeding edge and prone to breaking
from time to time. You must know how to work with git if you use `develop`.

**Comment by robbyoconnor** [comment]
If you want bug fixes faster, use `develop`.

**Pull request closed without merging**
