### PR TITLE
Create a init function for the spacemacs buffer.

### LINKED ISSUE #3354: Recreate spacemacs-buffer's content if needed
After deleting the `*spacemacs*` buffer with `SPC b d`, its content is gone when switching back to it with `SPC b h`. It would be nice if it gets recreated.

### PR DESCRIPTION
**Pull request by person808**
Used to fix #3354

### CODE REVIEW

**Comment by justbur** [comment]
Need to put the buffer in spacemacs-mode probably

**Comment by person808** [comment]
@justbur Thanks! Overlooked that.

**Comment by robbyoconnor** [comment]
<3

**Comment by StreakyCobra** [comment]
Wouldn't it be better to extract the spacemacs-buffer creation from [`spacemacs/init`](https://github.com/syl20bnr/spacemacs/blob/develop/core/core-spacemacs.el#L71-L73) to it's own function (e.g. `spacemacs/init-spacemacs-buffer`) and call it both from `spacemacs/init` and `spacemacs/home`? (I don't know if it is possible though)

Because duplicating the code may lead to issues if the buffer creation is changed later.

I also noticed that either [this check (`dotspacemacs-startup-lists`)](https://github.com/syl20bnr/spacemacs/blob/develop/core/core-spacemacs.el#L201-L202) is redundant, or missing in this PR :smile:

**Comment by justbur** [comment]
I had the same thought as @StreakyCobra (write a init function for the buffer)

**Comment by syl20bnr** [comment]
I'm also againt code duplication. Be sure to check the look & feel of the startup, the current setup is not ideal but I tried to remove some screen flashing or UI element popup when Emacs is starting.

**Comment by person808** [comment]
@syl20bnr I'll do it during the weekend most likely if I don't have time earlier.

**Comment by person808** [comment]
Welp. My laptop charger decided to break so I may not be able to work on this for a while. I'll close this for now, someone else can do this if they want to. If nobody does, I'll work on it when I get a charger.

**Pull request closed without merging**
