### PR TITLE
Fixed grammar in `dotspacemacs-enable-lazy-installation'

### PR DESCRIPTION
**Pull request by ronmrdechai**
Noticed some grammar errors while reading through my .spacemacs file.

### CODE REVIEW

**Comment by joehillen** [comment]
@ronmrdechai You should write a better commit message and clean up the PR description.

**Comment by ronmrdechai** [comment]
How do I remove commits that aren’t mine? I edited the commit message after pulling.

**Comment by sdwolf** [comment]
You should execute:

```bash
git reset --hard HEAD~8
```

This should tell you:
```bash
HEAD is now at 6d89d693 Fixed grammar in `dotspacemacs-enable-lazy-installation'
```

Now you can force push and you will have them as they were before:

```bash
git push origin develop --force
```

Also, if you want the changes from those commits below yours, do:

```bash
git rebase origin/develop
```
Solve any conflicts that may arise and force push again.

**Comment by joehillen** [comment]
@ronmrdechai I recommend learning about interactive rebase: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Pull request closed without merging**
