### PR TITLE
Update layers tutorial with new layer structure

### PR DESCRIPTION
**Pull request by robbyoconnor**
Update the docs for creating a new layer. This is dependant on #4906

### CODE REVIEW

**Comment by syl20bnr** [comment]
Thank you :+1: 
Cherry...

**Comment by robbyoconnor** [comment]
Cherry what? Pie?

**Comment by syl20bnr** [comment]
Picked

**Comment by syl20bnr** [comment]
in

**Comment by syl20bnr** [comment]
develop

**Comment by syl20bnr** [comment]
branch

**Comment by syl20bnr** [comment]
:-)

**Pull request closed without merging**
