### PR TITLE
Integrate helm-cider in clojure layer

### PR DESCRIPTION
**Pull request by Nimamoh**

### CODE REVIEW

**Comment by kommen** [comment]
How does this PR affect people who use ivy instead of helm with Spacemacs?

**Comment by 0atman** [comment]
This is an important fix, as currently this package tries to get installed every startup, which means the package lists are refreshed every startup, which blocks the UI.
Thank you! +1

**Comment by sdwolfz** [comment]
I've merged #11839 for the next release. Please rebase this if you want the helm package, and it will be part of the next release.

**Comment by Nimamoh** [comment]
Updated the documentation and the clojure layer to take #11839 in account.
This PR now uses helm-cider when helm is used.
To answer @kommen . When using ivy, regular cider-apropos and cider-cheatsheet are used, I just tested that.

**Comment by smile13241324** [comment]
I'll check whether this is still relevant and merge it if it is.

**Comment by smile13241324** [comment]
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

**Pull request closed without merging**
