### PR TITLE
make ess keybindings spacemacs compliant

### PR DESCRIPTION
**Pull request by gdkrmr**
see #9096, I also put the `ess-extra-map` under `SPC m r` and added `SPC m h h` for `ess-display-help-on-object` because it is used often and more convenient than `SPC m h d`.

### CODE REVIEW

**Comment by gdkrmr** [comment]
there are some things that do not get rendered correctly in the [README.org](https://github.com/gdkrmr/spacemacs/blob/ess-keybinding/layers/%2Blang/ess/README.org)

**Comment by bmag** [comment]
Thanks for the PR. I've been busy for the past several days, and with the recent changes in develop I didn't have time to test this PR yet. 

The bindings look OK at a casual glance, but there seems to be a formatting issue - see the "Details" link for the failing circleci test to see what needs to be fixed. I hope to test and merge this before the weekend comes.

**Comment by gdkrmr** [comment]
formatting fixed.

**Comment by bmag** [comment]
Thank you :+1: Squashed and cherry-picked into develop, you can safely delete your branch. It took longer than I thought, but thank you for your patience.

It would be nice to add appropriate calls to `spacemacs/declare-prefix-for-mode`, so which-key's help looks nicer and more informative, but I didn't want to delay this PR further.

**Pull request closed without merging**
