### PR TITLE
sr-speedbar layer

### PR DESCRIPTION
**Pull request by CarlQLange**
discussion and old PR here: https://github.com/syl20bnr/spacemacs/pull/2002

had to create a new PR because git.

### CODE REVIEW

**Comment by ralesi** [comment]
Does this show only files,  like another project explorer?  Can we add a taglist from speedbar as well http://alexott.net/en/writings/emacs-devenv/EmacsCedet.html?

**Comment by CarlQLange** [comment]
nope, it also shows tags. though I don't know about specific compatibility with other projects.

**Comment by edrex** [comment]
Feedback:

 - Maybe add (setq speedbar-show-unknown-files t) so speedbar shows all files.
 - IMO keybindings should mirror the NeoTree ones, to make transitioning this to the default easier.

**Comment by robbyoconnor** [comment]
#3264 had one thing that was good, a keybinding -- I propose this PR use the `SPC a f` namespace...

**Comment by CarlQLange** [comment]
Yeah, I'd like to shadow the NeoTree ones, to be honest.

**Comment by robbyoconnor** [comment]
I support that as well. `SPC ft` sounds reasonable -- but be clear that this layer overwrites that keybinding in the README -- I'd make it bold.

**Comment by edrex** [comment]
I've been using this, and the only major issue I've found so far:

Given:
- Two frames, A and B
- I call `spacemacs/sr-speedbar-show-or-hide` in A and observe an instance of sr-speedbar is shown in a new window.
- I switch to B and call `spacemacs/sr-speedbar-show-or-hide` again.

Observed behavior: `sr-speedbar` in A is destroyed.
Expected behavior: Instance of `sr-speedbar` is created in B, distinct from the one in A.

@CarlQLange, I pushed to https://github.com/edrex/spacemacs/tree/sr-speedbar with your commit and one with a keybinding on top of the latest `develop` if you want to pull that in.

**Comment by edrex** [comment]
I just dug in with that issue and it seems that it happens with `sr-speedbar-toggle` as well, so I'm going to push it upstream. with the keybinding, I strongly support merging this :ship: :it:

**Comment by TheBB** [comment]
Closing this in favour of #3559.

**Pull request closed without merging**
