### PR TITLE
Chruby support

### PR DESCRIPTION
**Pull request by Immortalin**
Needs documentation.

### CODE REVIEW

**Comment by StreakyCobra** [comment]
#2321 Is about `chruby` too, so if one get merged, the other should be closed.

**Comment by StreakyCobra** [comment]
It would be nice to document the `chruby-ruby-version` variable in the README. Not all users will read the source code :-)

I also have a question, you didn't added `chruby` to the list of packages because it's provided by another package? Or did I missed something?

**Comment by Immortalin** [comment]
@StreakyCobra aren't you suppose to set the ruby-version-manager variable at runtime I.e. in your .spacemacs.d? I haven't had time to add in the documentation for usage

**Comment by StreakyCobra** [comment]
I'm not a ruby guy, so I don't know how all of this work :smiley: I was just asking, I'll let other people have a look at it :-)

**Comment by syl20bnr** [comment]
Thank you.
I made some changes to make chruby behaves like rbenv and rvm, see documentation here: https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/ruby#ruby-version-management
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
