### PR TITLE
Add LLVM layer

### PR DESCRIPTION
**Pull request by bgamari**
This is a simple layer adding support for `llvm-mode`.

### CODE REVIEW

**Comment by trishume** [comment]
I wonder if this should go in `extra-langs` since it's such a small layer. I'm not sure if my dumping ground practice is the best one, but whenever I add a layer that has no additional configs and is a niche language I just dump it in `extra-langs`.

Cool though! I'm a compiler nut so I might end up using this package at some point.

**Comment by bgamari** [comment]
As a new user of Spacemacs I was a bit surprised by the `extra-langs` layer. It seems like the cost of a new layer is pretty low and individual layers are far more discoverable than catch-alls like `extra-langs`. I think it's reasonable to optimistically assume that while the layer is currently small, it may grow with time.

**Comment by trishume** [comment]
Decent point. Especially since you already did the work to make it a layer. I guess I only use `extra-langs`  because I personally don't like making new layers. Especially since many of the things in `extra-langs` like `nix-mode` and `idris-mode` I only use for a day to try out the language.

You're right about the discoverability penalty but it's smaller than it might otherwise be because of the big "Search Spacemacs" button and the shortcut `SPC f e h` which search all layers for packages. For example searching for `idris` shows `(extra-langs) idris-mode`.

So this is good :+1:

**Comment by syl20bnr** [comment]
I'm thinking about how to address this use case where the layer is only a wrapper around the package with no additional benefit.
Something like a new dotspacemacs variable where the user provide package symbols and Spacemacs generates the thin wrapper for them and put the generated files somewhere (in case the user want to add configuration).

**Comment by syl20bnr** [comment]
I pushed the feature described above in the form of a new variable `dotspacemacs-additional-packages`

>  List of additional packages that will be installed wihout being
wrapped in a layer. If you need some configuration for these
packages then consider to create a layer, you can also put the
configuration in `dostspacemacs/config'.

Related commit: 5930597e500f5c466fb9ff9f7b7136d7d9203c14

So I now consider this kind of layer unnecessary in spacemacs.

@bgamari Thank you for the PR !

**Comment by bgamari** [comment]
Fair enough.

**Comment by syl20bnr** [comment]
@bgamari If you add useful configuration at some point, feel free to submit a new PR.

**Pull request closed without merging**
