### PR TITLE
Fix helm loading for layouts transient state

### PR DESCRIPTION
**Pull request by deb0ch**
Calling the transient state and its functions (particularly `SPC l L` for loading from file) doesn't load helm, so until helm is loaded by something else the default Emacs method is used (I don't remember how it's called).

This makes that helm will always be used for opening layouts from file and all the rest inside the transient state, may there be more currently or in the future.

### CODE REVIEW

**Comment by deb0ch** [comment]
Now that I think of it, should I update the changelog at the same time ? I think it's the new policy after #11741 but not sure

**Comment by sdwolfz** [comment]
I will write proper documentation on adding stuff to the changelog after finishing with #11741 to make sure it's done as part of the PR or as part of the cherry-pick.

**Comment by sdwolfz** [comment]
I'll have to elaborate on that a bit more, define some sections, add an example, and prepare a skeleton for the next release's changelog.

**Comment by duianto** [comment]
The same issue occurs with  `SPC f R` (`spacemacs/rename-current-buffer-file`), as described in issue:
Helm doesn't load automatically for some commands #11479

Instead of fixing them individually (there probably are more), maybe a more universal solution could be to advice `read-file-name` to load helm the first time `read-file-name` is called.

This works for both `SPC l L` and `SPC f R`:
```elisp
(defun load-helm-before-read-file-name
  (prompt &optional dir default-filename mustmatch initial predicate)
  (require 'helm)
  (helm/init-helm)
  (advice-remove 'read-file-name #'load-helm-before-read-file-name))

(advice-add 'read-file-name :before #'load-helm-before-read-file-name)
```

The same issue occurs when trying to checkout a branch `bb` or popping a stash `zp` in Magit before helm has loaded, but Magit uses `magit-completing-read` instead of `read-file-name`.

This works for both `bb` and `zp`:
```elisp
    (defun load-helm-before-magit-completing-read
        (prompt collection &optional
                predicate require-match initial-input hist def fallback)
      (require 'helm)
      (helm/init-helm)
      (advice-remove
       'magit-completing-read #'load-helm-before-magit-completing-read))

    (advice-add 'magit-completing-read :before #'load-helm-before-magit-completing-read)
```

**Comment by sdwolfz** [comment]
@syl20bnr please take a look at @duianto's suggestion as you were the one that lazy loaded helm a long time ago in order to speed up startup. Do you see any reason why this won't work?

**Comment by deb0ch** [comment]
I don't like advising in general but under this light I don't see any real, factual drawback in this case. If Helm itself is specific about these functions and no others then instinctively I'd say it makes more sense

**Comment by duianto** [comment]
@sdwolfz Done:
Load helm before read-file-name and completing-read #11877

**Pull request closed without merging**
