### PR TITLE
Merging `develop` branch into `master`

### LINKED ISSUE #11352: A recent release?
There have been quite a lot of fixes since the last official release, e.g. https://github.com/syl20bnr/spacemacs/issues/9374. While there is a milestone it hasn't really been updated for about a year. If simply using `develop` branch as a rolling release is officially recommended, I'd be more than willing to switch (some of my friends share this idea too). 

So, is it possible to either release one (maybe even a `-rc` or `-hotfix` release), or a recommendation for the develop branch?

### PR DESCRIPTION
**Pull request by dijonkitchen**
Resolves #11352. 

Also a place to analyze potential merge conflicts and how easy/difficult it would be to catch up users of the `master` branch.

### CODE REVIEW

**Comment by sdwolfz** [comment]
Please don't open PRs like this, our release process is not as straightforward as simply merging develop into master, @syl20bnr will take care of this when he has the time.

Until then please wait patiently, we all want a new release, it's going to happen soon, we will work towards making the release process simpler and releasing more often in the future.

**Comment by d12frosted** [comment]
@sdwolfz you deserve a 🍕

**Comment by dijonkitchen** [comment]
Might be worth communicating those milestones more openly, so we don't have issues like https://github.com/syl20bnr/spacemacs/issues/11352

**Comment by fridayd** [comment]
Bump. 

"Until then please wait patiently, we all want a new release, it's going to happen soon, we will work towards making the release process simpler and releasing more often in the future."

I don't mean to sound ungrateful—I love using Spacemacs, and use the Development branch myself—but the reality is that's simply not how master and develop are supposed to be used. The fact is the release _process_ on this project is broken. Even more so if the only message to the users—including ones trying to help move thing along like dijonkitchen has here—is "just wait".

At the risk of sounding like a Cassandra, this is the kind of problem that kills open source projects. The sooner this project-level problem is recognized and addressed, the better.

A rolling release strategy is fine, and so are time- or feature- based releases. Spacemacs appears to be using 'none of the above'.

**Comment by hyiltiz** [comment]
Maybe some prime Raymond reading would benefit us all?

**Pull request closed without merging**
