### PR TITLE
Home buffer

### PR DESCRIPTION
**Pull request by TheBB**
As discussed in https://github.com/syl20bnr/spacemacs/issues/6986 and other places.

### CODE REVIEW

**Comment by JAremko** [comment]
I hope it doesn't break centering. It is my by far favorite feature in the upcoming release :confused:

**Comment by deb0ch** [comment]
@JAremko Don't worry, by looking at it it doesn't seem to break anything, just resolve some performance issues and add a dotspacemacs var for deactivating the responsiveness on resize events.

Centering is nice, but it is even nicer if it works for everyone :smile: 

Really glad that the default value is `t` :smiley:

Btw, centering of startup lists is in progress !

**Comment by TheBB** [comment]
IMO the main content shouldn't be centered. Lists are easier to read and browse through if they're adjusted.

**Comment by TheBB** [comment]
Merged.

**Comment by deb0ch** [comment]
I am not *actually* centering it because as you said it doesn't look nice.

The PR is ready and I should submit it soon, I guess you'll see then what I mean exactly.

**Pull request closed without merging**
