### PR TITLE
counsel: New async implementation

### PR DESCRIPTION
**Pull request by justbur**
This version of counsel--async-command feels smoother for me. Right now
it is just being used for the search functions. If others like it, I'll
propose it upstream.

@syl20bnr Can you try this and see if you like it? It works better for me I think.

### CODE REVIEW

**Comment by syl20bnr** [comment]
Not sure what the difference is, I had 0.05s for the refresh but it feels smooth for me I like it. You display the first candidates right away that's it ?.
I noticed that there is no `++` when the search is not finished and the total number of candidates reset to the initial count when navigating in the results while the ag process is not finished.

**Comment by justbur** [comment]
The current implementation is laggy on my work machine (windows), and it seems totally unnecessary to update the candidates past some large number because as soon as you start typing again it sends a new query out to ag and starts generating results again. I can add the `++`. I changed the way the prompt was generated and didn't try to put that back in yet. 

What I really want is it to work like helm-ag which seems to be truly asynchronous. You can narrow existing results and generate new ones in the background at the same time.

**Comment by syl20bnr** [comment]
I merged it for now, let's see how people find it. At work I still use helm, I use ivy only on my laptop.
Thank you :+1:

**Comment by justbur** [comment]
Thanks. This is currently my main problem with ivy. Maybe we can get a better solution upstream at some point.

**Pull request closed without merging**
