### PR TITLE
Added missing cider-connect-cljs keybinding

### PR DESCRIPTION
**Pull request by AndreTheHunter**
Add missing cider-connect-cljs key binding for connecting to cljs repl.

### CODE REVIEW

**Comment by duianto** [comment]
It's helpful to mention the new keybinding and command in the commit message:
`sC` `cider-connect-cljs`

And you should also state that this PR changes a keybinding:
from: `sC` `cider-find-and-clear-repl-output`
to: `sd` `cider-find-and-clear-repl-output`

But it's marked as a draft so your probably still working on this. 😄

**Comment by jr0cket** [comment]
@duianto 

@AndreTheHunter are you still planning to develop this PR for the ClojureScript connect command?  I ask because CIDER seems to have evolved a lot since this PR.  We now have a lot more `cider-connect-*` commands

From docs.cider.mx we have the following commands available

`C-c C-x c j` to call `cider-connect-clj`
`C-c C-x c s` to call `cider-connect-cljs`
`C-c C-x c m` to call `cider-connect-clj&cljs`

Add new REPLs to the current session with

`C-c C-x s j cider-connect-sibling-clj`
`C-c C-x s s cider-connect-sibling-cljs`

Session life-cycle management commands live on the Sesman map (`C-c C-s`)

`C-c C-s s sesman-start`
`C-c C-s r sesman-restart`
`C-c C-s q sesman-quit`

I suggest this needs a bit of thought as to how best to add these commands

**Comment by AndreTheHunter** [comment]
Hi @jr0cket,

Feel free to close or take over the PR. I have no plans to further maintain it.

**Comment by jr0cket** [comment]
@duianto can you close this PR?  The orginal author no longer wishes to pursue the change.  I will create a separate issue/PR to add the additional connection command keybindings after consulting with the community.

Thank you

**Pull request closed without merging**
