### PR TITLE
Check for smartparens package before calling its functions

### PR DESCRIPTION
**Pull request by carbohydratesn**
smartparens does not seem to be included in the common-lisp layer.  I am using spacemacs-base with common-lisp and emacs-lisp layers, and exwm as an additional package. smartparens is not installed.

Calling its functions when it isn't installed causes slime to crash before getting to a repl, every time.  One of the hooks for the common-lisp layer calls two of them.

Installing the smartparens package from within emacs, using package-install, allowed me to get to a repl.  

Commenting out its functions, without installing smartparens, also allowed me to get to a repl.

This is a better solution than either.  This change allows you to use slime without having smartparens installed.  If it isn't found, its hook isn't invoked.

### CODE REVIEW

**Comment by TheBB** [comment]
The most idiomatic way to do this is to add `smartparens` as a package to the `common-lisp` layer, then move this code to a function called `common-lisp/post-init-smartparens`.

**Comment by carbohydratesn** [comment]
How about for those who don't want the smartparens package?  Or is it considered a 'must-have' default?

**Comment by TheBB** [comment]
That's why it's `post-init-smartparens` and not `init-smartparens`.

See the note here: https://github.com/syl20bnr/spacemacs/blob/master/doc/LAYERS.org#packagesel

**Comment by TheBB** [comment]
> A package will not be installed unless at least one layer defines an init function for it. That is to say, in a certain sense, the init function does mandatory setup while the pre-init and post-init functions do optional setup. This can be used for managing cross-layer dependencies (...)

**Comment by syl20bnr** [comment]
@carbohydratesn any progress on this PR ? Do you need more help for the `post-init-smartparens` thing ?

**Comment by TheBB** [comment]
@carbohydratesn

**Comment by TheBB** [comment]
@carbohydratesn Please open a new PR when you have addressed the comments or if you have other questions. And please do it against the develop branch, when you do. Thanks!

**Pull request closed without merging**
