### PR TITLE
haskell layer: add key binding to jump to imports

### PR DESCRIPTION
**Pull request by bennofs**

### CODE REVIEW

**Comment by jb55** [comment]
:+1: great

**Comment by robbyoconnor** [comment]
:+1:

**Comment by d12frosted** [comment]
Hey @TheBB, what do you think about it? Pretty useful binding :smile:

**Comment by syl20bnr** [comment]
@d12frosted Thanks for the bump up :-)

@bennofs Thnak you !
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
