### PR TITLE
Add `magit-discard` keybinding

### LINKED ISSUE #3362: [magit]  the K is bound to magit-file-untrack ????
Shouldn't it be bound to magit-discard?  @syl20bnr  Anything missing ?

I'm on the latest develop branch.

### PR DESCRIPTION
**Pull request by synic**
Fixes #3362 

Not really sure if it needs to be bound everywhere like the other ones, but it seems to be working fine.

### CODE REVIEW

**Comment by TheBB** [comment]
Isn't this actually a bug in Evilify that should be fixed instead?

**Comment by synic** [comment]
Ah, I will close this then.

**Comment by syl20bnr** [comment]
I would like to investigate the issue before merging this, expect me to look at it pretty quickly.

**Comment by synic** [comment]
Sounds like it's fixed!

**Comment by nixmaniack** [comment]
Not yet for me. Tested on latest develop with updated packages after reading above comment.

**Comment by synic** [comment]
Yeah, it seemed to work one for me, but now I'm getting `magit-file-untrack` again.

**Comment by TheBB** [comment]
This is probably not needed any more after evil-magit?

**Comment by synic** [comment]
Nope.

**Comment by TheBB** [comment]
Thank you anyway. :-)

**Pull request closed without merging**
