### PR TITLE
Add Colemak layout to keyboard-layout layer

### PR DESCRIPTION
**Pull request by fmdkdd**
This commit remaps the HJKL movement keys to JKHL.

See https://colemak.com/ for a description of the Colemak layout.

See #6631 for a background discussion.
### Remaining issues

I would consider this layour useable as is, but far from complete. 
At the very least, this coulp help Colemak users of Spacemacs to get something going without diving into too much Elisp.

Here are a couple of annoying issues that I did not manage to fix yet:
- Lost the binding to `evil-join` which was `J` by default.  Now `J` maps to `evil-window-top` and `evil-join` is unbound.
- In magit, `H` and `K` are correctly rebound to `evil-previous-visual-line` and `evil-next-visual-line`, but not when entering visual mode, where `H` becomes `evil-lookup` and `K` becomes `evil-previous-visual-line`.  This is puzzling to me,  as they are correctly bound in visual mode outside of magit.

cc @StreakyCobra.

### CODE REVIEW

**Comment by StreakyCobra** [comment]
Looks fine :-) I can't really test colemak, but you know better than me if colemak hack/changes are needed! So feel free to do whatever is needed in `:colemak`, you (theoretically) can't broke the other layers by changing these sections.

**Comment by fmdkdd** [comment]
@StreakyCobra Any idea why `evil-join` would end up unbound?  Since this is simply a permutation, I would expect the function to end up *somewhere* (preferably on `J`).  Otherwise, I guess I can always force these bindings to what I expect.

**Comment by StreakyCobra** [comment]
I had unanswered question like this all the time. More or less all `HACK` comments for `bepo` are due to mysterious reasons that I wasn't able to identify :sweat_smile: 

Also, it may be nice to update the README with a colemak section to let users know that it's supported

**Comment by fmdkdd** [comment]
@StreakyCobra Well, I can't say my own layer to rebind HJKL wasn't hackish as well.  I'll try to get around the two remaining issues and update the README.  Please wait before merging.

**Comment by fmdkdd** [comment]
I've restored `evil-join` and fixed `h` and `k` in magit visual mode, and I've added a Colemak section to the README.

I've also managed to rebind `H`, `K` and `L` in normal mode.  Annoyingly, `L` is overridden by the `spacemacs-bootstrap` layer, and even with a spacemacs hooks on evil post-config, I couldn't redefine it.  I used a `post-init` function instead, but I used `kl|config` twice on the configuration `evil`.  Will that cause any issue?

Other than that, I would consider that configuration decent for a colemak user.  There are bindings missing, for `evil-window` or `org`, but  I don't have the energy to deal with them right now.

**Comment by StreakyCobra** [comment]
> Will that cause any issue?

The configuration name is used for 2 purpose:

- Identify and run the associated `pre-config-<name>` and `post-init-<name>` (see https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bintl/keyboard-layout#addoverride-key-bindings)
- Enable or disable the tweak by using it in `kl-enabled-configurations` respectively `kl-disabled-configuations`

The second one is not problematic, and maybe eve useful, because all `evil` related bindings will be activated/disabled at once with only `evil`. The first one *may* be problematic in some case, because the `pre/post-config-<name>` functions will be ran twice. If the users use these functions only for forcing a binding, no problem will arise, but if they are using functions with side effects, like swapping two keys, this will be applied twice and have no effect.

> Other than that, I would consider that configuration decent for a colemak user. There are bindings missing, for evil-window or org, but I don't have the energy to deal with them right now.

Yes, it doesn't have to be perfect, `dvorak` and `bepo` layouts are not fully functional as well. But from an user perspective is always better than nothing at all, especially regarding the complexity of the task.

I hope your experience with the `keyboard-layout` was good, and that it made it easy to implement new keyboard-layout support.

**Comment by fmdkdd** [comment]
@StreakyCobra  I've added a comment and a note to the README indicating the quirk with hooks running twice.  Thanks for catching that.

Well adding the basic permutation through `keyboard-layout` was certainly a breeze.  But then adding the rest was harder than expected.  One thing that may be surprising is that you do not get any output of what was rebound by `kl/correct-keys` and other functions.  So you do not really know what effect the functions had, if any.  Next time I work on it, I will definitely add `message` calls inside these functions ;)

In my own [colemak-hjkl](https://github.com/fmdkdd/dotfiles/blob/master/spacemacs/.emacs.d/private/colemak-hjkl/packages.el) layer, the code is certainly more tedious, but also more straightforward: you see every binding redefinition, and there are no surprises.  Still, I will be adding a link `keyboard-layout` now that it supports Colemak, as it's a worthy alternative.

**Comment by TheBB** [comment]
What's the relationship between this and https://github.com/syl20bnr/spacemacs/pull/7015?

**Comment by TheBB** [comment]
This PR sems more complete, but there are still some things in the other one that aren't here. Could you perhaps pick the remainder from there?

**Comment by fmdkdd** [comment]
Oh, I didn't see #7015, sorry for that.  One immediate difference is that the other PR maps `hjkl` to `hnei` (home row on right hand), while this one maps `hjkl` to `jkhl` (not home row, but not far, and doesn't move any other binding since it's just a permutation).

So the question would be, which one do we keep?

**Comment by TheBB** [comment]
In other words, this one is faithful to the physical locations of the keys? In that case I'd prefer this one. As far as missing content is concerned I was thinking more about the avy keys and such.

**Comment by ajgrf** [comment]
I made some ascii diagrams to help you compare the proposals as someone who doesn't know Colemak. This one looks like this:

    q w f p g  ← → u y ;
     a r s t d  ↑ n e i o
      z x c v b  ↓ m , . /

It doesn't rearrange any keys except hjkl, but as a result you lose out on Vim muscle memory.

For the next diagrams, the capital labels represent the non-direction keys that got rebound. They show which qwerty key it will act like instead of which letter gets typed in insert mode. For example, the key marked N below is actually the Colemak j key, but it will behave like the qwerty N key in normal mode.

So here's the other PR:

    q w f p g *N*I*u y ;
     a r s t d  ← ↓ ↑ → o
      z x c v b *E*m , . /

As you can see this one keeps the direction keys intact. New Colemak converts will find it messes with their muscle memory much less. I think it's better, but in the other discussion I have been advocating for the following tweak to put the "find next" command back into its qwerty position (by just switching E and N):

    q w f p g *E*I*u y ;
     a r s t d  ← ↓ ↑ → o
      z x c v b *N*m , . /

I also kind of want the following tweak as well, simply because I switch between Colemak and QWERTY semi-regularly and anyone who does the same will constantly confuse "undo" with "insert" in both layouts unless they have this tweak:

    q w f p g *E*U*I*y ;
     a r s t d  ← ↓ ↑ → o
      z x c v b *N*m , . /

However I recognize that probably not everyone will want that.

Anyway, I hope that helps and it wasn't too confusing.

**Comment by StreakyCobra** [comment]
You can define two different keyboard layout variants, like name one "colemak-hnei" and the others "colemak-jkhl", each one with their own ":colemak-…" properties block in the configs.

**Comment by fmdkdd** [comment]
Well if that's an option, then yes, let's keep both.   At the end of the day, it's a matter of individual preference.

I'll update this PR to call the layout `colemak-jkhl`.

**Comment by fmdkdd** [comment]
@TheBB I've updated this PR to integrate the missing pieces (avy and ace-window keys), and I've also named the keyboard configuration `colemak-jkhl`, so there's room to add alternate configurations for colemak, should @ajgrf or @lyallcooper want to add them.

**Comment by fmdkdd** [comment]
Also, you can probably close #6631 if this is merged (to help with the cleanup!).

**Comment by syl20bnr** [comment]
Thank you :-)

I guess we can let the neiop variant be named colemak as it is the default "scheme" for the other layout. So we get colemak and colemak-jkhl.

**Comment by allentiak** [comment]
Hi,
I also use Colemak.

From what I can see, there are two different aspects proposed here. One concerns the movement keys. The other one concerns other shortcuts.

At least for now, I would only change the movement keys. In this regard, I think the less shocking change would be to use H-N-E-I as "left-down-up-right". (Even though I would find it most pleasant to use N-E-I-O, à la Dvorak.)

Even if I don't have a strong opinion concertning the keys for the other shortcuts, in principle I would leave them as they are (as long as they don't interfere with any existing shortcut, of course).

Just my opinion.

**Comment by wbolster** [comment]
Evil users using Colemak may be interested in my evil-colemak-basics package, designed as a smart hybrid between Colemak and Qwerty. The docs explain the rationale quite extensively.

**Comment by wbolster** [comment]
Evil users using Colemak may be interested in my [evil-colemak-basics](https://github.com/wbolster/evil-colemak-basics) package, designed as a smart hybrid between Colemak and Qwerty. The docs explain the rationale quite extensively.

**Comment by syl20bnr** [comment]
@fmdkdd  I merged two other PRs regarding Colemak layout. Can you rebase this PR on top of develop ?

**Comment by fmdkdd** [comment]
@syl20bnr Sure.  That would bring the count of Colemak bindings to 3 in `kl--base-rebinding-maps`.  Currently in develop, two of the bindings are named `colemak`, which means only the first one will be picked up.  I could rename the two existing flavours using the scheme:

`colemak-neio` `colemak-hnei` `colemak-jkhl`

and succinctly present the flavours in the README.

**Comment by fmdkdd** [comment]
@syl20bnr Should be good.

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

I had to do a fair bit of conflict resolution still. Maybe it would be good if you double-checked the result.

**Comment by fmdkdd** [comment]
@TheBB As far as as colemak variants are concerned, LGTM.

**Comment by allentiak** [comment]
Just curious... Was this merged into the 200.10 release? I keep on rebasing my own colemak variant on top of checkversion/master...

**Comment by duianto** [comment]
@allentiak The hotfix only fixed two things:
- Fix Helm error when selecting a candidate from a Helm buffer (thanks to bmag)
- Fix window number assignation for Neotree buffer window (thanks to duianto)

source: https://github.com/syl20bnr/spacemacs/blob/master/core/info/release-notes/0.200.10.txt
and: https://github.com/syl20bnr/spacemacs/commits/master

**Comment by allentiak** [comment]
So... Should I prepare a PR?

**Comment by duianto** [comment]
@allentiak Sure, the other Colemak users might also like your variant. Just remember to make the PR against the develop branch.

>Submit your contribution against the develop branch. You should not use your master branch to modify Spacemacs, this branch is considered to be read-only.

source: https://github.com/syl20bnr/spacemacs/blob/master/CONTRIBUTING.org#pull-request

**Pull request closed without merging**
