### PR TITLE
Add rainbow-mode to html layer

### PR DESCRIPTION
**Pull request by m3hr**
It's super useful and simple. Example:

https://julien.danjou.info/media/images/rainbow-mode/rainbow-mode.png

### CODE REVIEW

**Comment by syl20bnr** [comment]
I cannot accept this PR because `rainbow-mode` fail to install on Windows, it is mentioned here: https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L102-103.

But don't worry I plan to integrate [kurecolor](https://github.com/emacsfodder/kurecolor).

**Comment by m3hr** [comment]
Oh sorry, I'll make sure to check better next time. and sorry for all the requests. :)

**Comment by syl20bnr** [comment]
np, all PR are welcome.

**Comment by syl20bnr** [comment]
@m3hr Funny, it pushed the uncommented `rainbow-mode` in `packages.el` of spacemacs layer, and it seems to work on Windows now... so oh well it is now back in spacemacs :-)

It will certainly be replaced by `kurecolor` very soon, I plan to add it tonight if I have enough time.

**Comment by m3hr** [comment]
Want me to add it? rainbow-mode is in the `colors layer, but I don't want to use rainbow-identifiers so I have `colors` disabled.

**Comment by syl20bnr** [comment]
@m3hr rainbow-identifiers is not enabled by default when you add colors, you have to set a layer variable to enable it. So you can use the color layer without any trouble. See the read me file of the layer for more info.

**Pull request closed without merging**
