### PR TITLE
initial stab at edebug support for elisp

### PR DESCRIPTION
**Pull request by npe9**
This is an initial stab at edebug support for spacemacs. I'm not an edebug or spacemacs expert yet, so I'm not entirely sure if I've done the interface right. I'd appreciate any feedback.

### CODE REVIEW

**Comment by npe9** [comment]
It has bugs, when I reset spacemacs it borks my evil config. Can I get any advice on how to fix/debug this?

**Comment by person808** [comment]
FYI `;` is a comment in elisp, not `!`

**Comment by npe9** [comment]
Sorry I should know better, I've been fortranning all month.
On Sat, Jul 25, 2015 at 5:53 PM person808 <notifications@github.com> wrote:

> FYI ; is a comment in elisp, not !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/pull/2413#issuecomment-124916811>.
>
-- 
Noah

**Comment by robbyoconnor** [comment]
This has to be against `master` -- Read the [conventions](https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org)

**Comment by robbyoconnor** [comment]
Additionally, you should rebase your changes **ON TOP OF** `develop` -- do `git pull --rebase upstream develop` -- **NEVER** add new features against `master`

**Comment by npe9** [comment]
gotcha, I'll fix it.

On Mon, Jul 27, 2015 at 6:16 PM robbyoconnor <notifications@github.com>
wrote:

> Additionally, you should rebase your changes *ON TOP OF* develop -- do git
> pull --rebase upstream develop -- *NEVER* add new features against master
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/pull/2413#issuecomment-125384316>.
>
-- 
Noah

**Comment by robbyoconnor** [comment]
You're going to have to close this -- you cannot change the base branch on a PR.

**Comment by npe9** [comment]
Done.

On Mon, Jul 27, 2015 at 7:29 PM robbyoconnor <notifications@github.com>
wrote:

> You're going to have to close this -- you cannot change the base branch on
> a PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/pull/2413#issuecomment-125400959>.
>
-- 
Noah

**Comment by npe9** [comment]
Before I resubmit, I'd like some feedback that I'm on the right track.
After a bit more research, I believe that I should be tying the keybindings
to the edebug minor mode. Is there anything else I should do?

On Mon, Jul 27, 2015 at 7:32 PM Noah Evans <noah.evans@gmail.com> wrote:

> Done.
>
> On Mon, Jul 27, 2015 at 7:29 PM robbyoconnor <notifications@github.com>
> wrote:
>
>> You're going to have to close this -- you cannot change the base branch
>> on a PR.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/syl20bnr/spacemacs/pull/2413#issuecomment-125400959>.
>>
> --
> Noah
>
-- 
Noah

**Comment by robbyoconnor** [comment]
Just open the PR -- you can add to it.

**Pull request closed without merging**
