### PR TITLE
javascript: add instruction for installation of JSHint

### PR DESCRIPTION
**Pull request by cpaulik**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1:

**Comment by oppenlander** [comment]
Should there be general "Flycheck" sections in layer READMEs, which says what checkers are available, and what external tools need to be installed for them?  
For example, I use [eslint](http://eslint.org/) for most of my projects, which works out of the box with Flycheck's Javascript definitions (though you must disable `jshint` for it to properly work).

**Comment by cpaulik** [comment]
@oppenlander Feel free to extend it and PR against my branch if you want to or make a separate PR. 
I'm not very experienced in JS tooling so you probably know more about it.

**Comment by syl20bnr** [comment]
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
