### PR TITLE
fixed feature headers in README's

### PR DESCRIPTION
**Pull request by CeleritasCelery**
Updated the `feature` header in README's to match the Spacemacs style guide as requested in #9476. 

Note that we have a spurious error in `circleci`
```
File "/root/project/layers/+source-control/version-control/README.org" has multiply "Features:" lists in the top level "Description" headline
```
which is incorrect. It looks like it is flagging this file because it has the word "feature" in a table. Hopefully @JAremko can fix that.

### CODE REVIEW

**Comment by JAremko** [comment]
@CeleritasCelery  

`File "/root/project/layers/+source-control/version-control/README.org" has multiply "Features:" lists in the top level "Description" headline`

That's because you need extra white spaces before `git-gutter, or git-gutter+` try this:
``` org
** Features:
- highlights uncommitted changes in the fringe or margin with [[https://github.com/dgutov/diff-hl][diff-hl]],
  git-gutter, or git-gutter+
- adds vcs transient-state ~SPC g.~ to allow quick navigation and modification of
buffer hunks.
```

*Without them there will be two lists (accordingly to org-mode parser :smirk: )*

- - - - - -

Btw. What's up with your email/account? Can you fix it?

**Comment by CeleritasCelery** [comment]
> Btw. What's up with your email/account? Can you fix it?

@JAremko What do you mean? Because I am using different credentials for commits then I am for the pull request? Is that a problem? I went ahead and rebased/reauthored my commits anyway.

**Comment by JAremko** [comment]
> Because I am using different credentials for commits then I am for the pull request?

Yeah. We want your name in contributors :wink:

**Comment by CeleritasCelery** [comment]
I always wondered why I never got the "Contributor" tag. I assumed it was because all my commits were cherry-picked. Anyways, looks like the build is clean and all the documentation issues related to it are fixed.

**Comment by JAremko** [comment]
Thank you ! :+1: Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
