### PR TITLE
Added .jsx to web-mode. Fixes issue #1769

### PR DESCRIPTION
**Pull request by Tritlo**

### CODE REVIEW

**Comment by louy2** [comment]
This is a pretty old pull request. How is this going? I guess it should be submitted to branch:develop.

**Comment by syl20bnr** [comment]
Thank you !
Cherry-picked into `develop` branch.

**Comment by kRITZCREEK** [comment]
I don't think .jsx belongs into web-mode. It's a JavaScript language extension.

**Comment by louy2** [comment]
@kRITZCREEK But `web-mode` has much better indentation and syntax-highlight support for JSX than `js2-mode`.

**Comment by TheBB** [comment]
If this was merged it should be closed.

**Comment by syl20bnr** [comment]
@TheBB Thank you !

**Pull request closed without merging**
