### PR TITLE
Solidity Layer

### PR DESCRIPTION
**Pull request by expede**
# TL;DR

- Add a [Solidity](http://solidity.readthedocs.io/) layer
- Addresses #10629

# About

- Wrote to scratch my own itch
- This is a first pass, and much more functionality could be added
- This layers aims to make it practical to use Spacemacs for Ethereum development

## Includes

- Syntax highlighting
- Syntax checking
- Naive autocomplete

## Does Not (yet) Include

- Smart autocomplete
- Test commands
- Truffle (or similar) integration

### CODE REVIEW

**Comment by jjzmajic** [comment]
I have some configs that address some of those not yet included features. Should I add it now, or wait until the core layer is incorporated into spacemacs so there are more eyes on what we're doing?

**Comment by expede** [comment]
Hey @jjzmajic -- that's great to hear! What I have so far are the bare essentials to scratch my own itch. Feel free to PR against [expede:solidity-layer](https://github.com/expede/spacemacs/tree/solidity-layer). At absolute worst, we delay until this is merged upstream, but I'm not sure what the timeline for that will actually be.

**Comment by duianto** [comment]
It's unrelated to this Leyer, but `flymake-solidity` seems to assume a non-windows setup:
>Not enabling flymake: ’/usr/local/bin/solc’ program not found [2 times]

I don't know if the following messages are related to the above issue, but `jit-lock` error messages appear when a `.sol` example file is opened or edited:
>Error during redisplay: (jit-lock-function 1) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 1001) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 1501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")

The file is the first example on this page:
https://solidity.readthedocs.io/en/latest/solidity-by-example.html

**Comment by duianto** [comment]
The following PRs (possibly modified) changes are now on the develop branch:
Add Solidity layer #12922

**Pull request closed without merging**
