### PR TITLE
Keybinding for setting flycheck checker executable

### PR DESCRIPTION
**Pull request by nashamri**
In case you want to change the checker executable quickly.

### CODE REVIEW

**Comment by TheBB** [comment]
How about `es` for `flycheck-select-checker` and `eS` for `flycheck-set-checker-executable`? From what I see, the former is a subset of the latter. Could be good to document the bindings, too.

**Comment by nashamri** [comment]
Yeah that's a good idea :+1:

**Comment by nashamri** [comment]
Rebased on latest `develop`, because there was a conflict. And updated the documentation.

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Comment by TheBB** [comment]
Ah shit, I just realized this is conflicting with `SPC e s s` for ESS. We should move that.

**Comment by TheBB** [comment]
→ #3290

**Comment by nashamri** [comment]
Oh I didn't know about that keybinding since I don't use that layer. Good catch @TheBB

**Pull request closed without merging**
