### PR TITLE
Reenable lsp mode lighter

### PR DESCRIPTION
**Pull request by yyoncho**
- The lsp modeline is used to provide information about the server status so it
should not be be hidden.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Why was it disabled?

**Comment by yyoncho** [comment]
@robbyoconnor I believe that it was disabled under the impression that the lighter is not used but it is only taking space since not all of the languages are using it to display that info.

**Comment by robbyoconnor** [comment]
Ah okay, makes sense.

**Comment by Compro-Prasad** [comment]
@sdwolfz This is good to go.

**Comment by sdwolfz** [comment]
Thank you :heart:!
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
