### PR TITLE
Add spacemacs badge

### PR DESCRIPTION
**Pull request by nashamri**
As requested by @robbyoconnor here's spacemacs badge.

I tried to add it to the README.md but for some reason, I couldn't get the SVG to show up using a relative path in the markdown file. It looks like a complicated issue or I'm a bit thick :smile: 

Anyhow, after multiple tries, I thought I'll just send the SVG file and let one of you guys *hardcode* the link to the badge against the official repo.

### CODE REVIEW

**Comment by nashamri** [comment]
The badge doesn't have a consistent look on different machines. Because of the font I used. I need to work a bit more on this.

**Comment by shaief** [comment]
@nashamri if you are using Inkscape, you can export text to path, and it'll solve the fonts issues...

**Comment by nashamri** [comment]
@shaief thanks :smile: lol I'm not okay today.

**Comment by syl20bnr** [comment]
:heart: :yellow_heart: :purple_heart: :green_heart: 
We have to use it in our own README :-) I don't know if we should put it at the top or at the bottom though.
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by nashamri** [comment]
I guess the "Supporting Spacemacs" section of the README is the right place
for it.
Not sure :-)

**Comment by d12frosted** [comment]
@nashamri you can link the image using `rawgithub.com` link:

```
<img src="https://rawgithub.com/syl20bnr/spacemacs/develop/assets/spacemacs-badge.svg">
![](https://rawgithub.com/syl20bnr/spacemacs/develop/assets/spacemacs-badge.svg)
```

**Result**

**Comment by syl20bnr** [comment]
> I guess the "Supporting Spacemacs" section of the README is the right place
for it.

Indeed :+1:

**Pull request closed without merging**
