### PR TITLE
Update README.org

### PR DESCRIPTION
**Pull request by kimchichef**
lean -> learn

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@syl20bnr @duianto mark this as invalid so they don't get credit for this to pad their Hacktoberfest PR count

**Comment by robbyoconnor** [comment]
@kimchichef Close this one too. Again you tried to game hacktoberfest and in the process, also ruined it for everyone else. 

If you want to make a good-faith contribution, then make all you typo fixes in one pull request.

**Comment by robbyoconnor** [comment]
For reference as to why I'm calling this out in bad faith is they did these one-word fixes to up their PR count for hacktoberfest, which ruined it for a lot of people.

**Comment by smile13241324** [comment]
Hi @kimchichef,

I had a look at your PR and have noticed that it is not adhering to our rules for a proper PR. You have no description of what you have changed and your commit message says nothing about what you did. In addition there is another PR #14001 which is almost identical to this one.

Both only do a very tiny change on the README which do not justify individual PRs.

Therefore I am going to close this PR now. If you are still interested in helping us, please open a new PR with a proper description, fixing all typos in the README you find and mention me as a reviewer.

Thanks
MAx

**Pull request closed without merging**
