### PR TITLE
Improved exil text object definition and use evil-surround

### PR DESCRIPTION
**Pull request by ralesi**
Now when we define text-objects, it also defines surround pairs.  

Use hooks on different modes to add mode related objects.

Example:

`vips8` will now block comment the paragraph with '/* ... */'

### CODE REVIEW

**Comment by danielwuz** [comment]
Very nice improvement!

I'm actually thinking if we should integrate something like this https://github.com/tarao/evil-plugins/blob/master/evil-textobj-between.el. Good thing about `evil-textobj-between` is that it works for any characters.

**Comment by syl20bnr** [comment]
@danielwuz thanks for pointing out this!
I will merge the PR of @ralesi but for the future we could use `evil-textobj-between` and define the surround pair separately.
What do you think ?

**Comment by danielwuz** [comment]
Absolutely! Actually @ralesi 's text objects work for me pretty well. I rarely have the need for any other text objects beyond those basica ones.

**Comment by syl20bnr** [comment]
Merged.
@ralesi Thank you ! It may be good to generalize it with the script proposed by @danielwuz 
Anyway good job :+1: 
Cherry-picked in `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
