### PR TITLE
Added stylus to the html layer

### PR DESCRIPTION
**Pull request by posva**
It was just missing

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1:

**Comment by robbyoconnor** [comment]
@ilyagr Thank you for your pull request. However this is against `master` and all pull requests must be against `develop` -- [Read the contribution guidelines] (https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org) before you continue. In the mean time, close this PR and open a new one against the correct branch. 

This is in addition to the fact that you didn't use a topic branch.

**Comment by robbyoconnor** [comment]
@posva Thank you for your pull request. However this is against `master` and all pull requests must be against `develop` -- [Read the contribution guidelines] (https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org) before you continue. In the mean time, close this PR and open a new one against the correct branch. 

This is in addition to the fact that you didn't use a topic branch.

**Comment by posva** [comment]
@robbyoconnor Ok, done. I don't get the "topic" branch thought, I guess it's about the branch title. The new PR is #4815

**Pull request closed without merging**
