### PR TITLE
Ocaml tweaks

### PR DESCRIPTION
**Pull request by edwintorok**
Flycheck initialization fixed, although not sure about its interaction with auto-complete and company, maybe it'd be better to just keep it disabled by default for now?

Add bindings for most merlin commands.
Merlin now supports showing ocamldoc (with `company` completion press F1)

### CODE REVIEW

**Comment by syl20bnr** [comment]
I'm confused all my comments are gone and I see you made some changes.

**Comment by syl20bnr** [comment]
Oh caching for the win... :-)
I can see them now.

**Comment by syl20bnr** [comment]
OMG no I don't see them.... I don't understand what's going on here.

**Comment by edwintorok** [comment]
Hmm looks like squashing commits makes the line comments go missing.
Sorry about that next time I'll make separate commits (perhaps with `squash!` or `fixup!`) that can be squashed at merge time.
I found the comments and my replies to them from the notification emails, hope its all there:
https://github.com/edwintorok/spacemacs/commit/e8bdaa69e671024531662522ca301d2c200a2944#commitcomment-11337704
https://github.com/edwintorok/spacemacs/commit/95c73ebcb607c64ae61e6252a950b25e2fbe6931#commitcomment-11337697
https://github.com/edwintorok/spacemacs/commit/e2f25a56f27aa09985b8b42bc07d09725ca3b84f#commitcomment-11337690
https://github.com/edwintorok/spacemacs/commit/e2f25a56f27aa09985b8b42bc07d09725ca3b84f#commitcomment-11337689
https://github.com/edwintorok/spacemacs/commit/e2f25a56f27aa09985b8b42bc07d09725ca3b84f#commitcomment-11337686

**Comment by edwintorok** [comment]
Also this is the diff of my changes as a response to your comments:
```diff
diff --git a/contrib/lang/ocaml/packages.el b/contrib/lang/ocaml/packages.el
index 9eff91f..2b24455 100644
--- a/contrib/lang/ocaml/packages.el
+++ b/contrib/lang/ocaml/packages.el
@@ -29,13 +29,14 @@
   (spacemacs|add-company-hook merlin-mode))
 
 (when (configuration-layer/layer-usedp 'syntax-checking)
+  (defun ocaml/post-init-flycheck ()
+    (add-hook 'merlin-mode-hook 'flycheck-mode))
   (defun ocaml/init-flycheck-ocaml ()
     (use-package flycheck-ocaml
       :if (configuration-layer/package-usedp 'flycheck)
       :defer t
       :init
       (progn
-        (add-hook 'merlin-mode-hook 'flycheck-mode)
         (with-eval-after-load 'merlin
           (progn
             (setq merlin-error-after-save nil)
@@ -52,13 +53,12 @@
       (setq merlin-completion-with-doc t)
       (push 'merlin-company-backend company-backends-merlin-mode)
       (evil-leader/set-key-for-mode 'tuareg-mode
-        "mcb" 'merlin-error-check
-        "mcn" 'merlin-error-next
-        "mcN" 'merlin-error-prev
         "mcp" 'merlin-project-check
         "mcr" 'merlin-refresh
         "mcv" 'merlin-goto-project-file
-        "met" 'merlin-type-expr
+        "meC" 'merlin-error-check
+        "men" 'merlin-error-next
+        "meN" 'merlin-error-prev
         "mgb" 'merlin-pop-stack
         "mgg" #'(lambda ()
                 (interactive)
@@ -73,6 +73,7 @@
         "mgI" 'merlin-switch-to-mli
         "mhh" 'merlin-document
         "mht" 'merlin-type-enclosing
+        "mhT" 'merlin-type-expr
         "mrd" 'merlin-destruct
         ))))
```

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
Great layer!

Cherry-picked and squashed in `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
