### PR TITLE
[WIP] PHP layer improvements

### PR DESCRIPTION
**Pull request by kostajh**
Please don't merge/review etc just yet. This is a work in progress to bring together discussion happening in https://github.com/ejmr/php-mode/issues/284 and elsewhere.

Tasks:
- [ ] Fix ac-php integration. Currently it's not added to company backends
- [ ] Fix semantic-php integration. the package's loaddefs file isn't loaded.
- [ ] Add [phpcbf integration](https://github.com/nishimaki10/emacs-phpcbf)

### CODE REVIEW

**Comment by TheBB** [comment]
I'm marking it as WIP in the title, then.

**Comment by tatsuhirosatou** [comment]
Any updates on this? It would be great to have. Spacemacs is fairly complete for most major languages but the PHP layer doesn't seen to have had much love. Even though I dislike PHP I have to code on it, this would be great.

**Comment by syl20bnr** [comment]
Any update on this PR ?

**Comment by TheBB** [comment]
Please resubmit if you'd still like to get this in.

**Pull request closed without merging**
