### PR TITLE
Add support for editing .vue components

### PR DESCRIPTION
**Pull request by robbert-vdh**
This adds support for editing single file [Vue.js](https://vuejs.org/) components. I wasn't sure where to add this as it's only a single package but it depends on other web related packages being installed.

### CODE REVIEW

**Comment by mrmark** [comment]
There is also https://github.com/emacs-lsp/lsp-vue

**Comment by tbsvttr** [comment]
I would like to see this feature added a lot, because I do a lot of professional work with Vue.js.

**Comment by standino** [comment]
put it into a new vue layer, please.

**Comment by am** [comment]
Is this stall? @robbert-vdh do you plan to keep pushing this feature?

**Comment by robbert-vdh** [comment]
I haven't kept this up to date since I haven't been using Spacemacs for a while now and I hadn't heard anything from the maintainers. If anyone wants to pick this up again, feel free to make a new pull request! I'll leave this open until someone makes a new one.

I'm not sure what the current status of LSP support in Spacemacs is, but it might be useful to integrate [lsp-vue](https://github.com/emacs-lsp/lsp-vue) into the layer after it's been migrated to lsp.el (see https://github.com/emacs-lsp/lsp-vue/issues/19).

**Comment by tbsvttr** [comment]
Is there any progress with this? I know you guys surely have a lot to do, but I still would love to do my Vue work with Spacemacs!

**Comment by duianto** [comment]
What's the next step for this PR?

According to @thanhvg there's a Vue layer PR in the works:
>I am working toward a vue layer PR. You can check it out as a private layer at https://github.com/thanhvg/vue
It works with dev branch. Features include: lsp, eslint, prettier, emmet-mode...
Feedback and contributions are welcome.

source: https://github.com/syl20bnr/spacemacs/issues/6148#issuecomment-463101530

**Comment by duianto** [comment]
There's a new PR open here: Vue layer #12977
If it covers this and more then this PR probably can be closed.

**Comment by smile13241324** [comment]
We have vue layer now in spacemacs so I think this is obsolete. If not please reopen.

**Pull request closed without merging**
