### PR TITLE
Add keybind: SPC-fj should run deer, not dired

### PR DESCRIPTION
**Pull request by sooheon**
This seems more likely to be the desired action if the user chooses the ranger layer.

### CODE REVIEW

**Comment by TheBB** [comment]
To me, this (as well as all other dired things) end up with deer already. CC @ralesi

**Comment by StreakyCobra** [comment]
> end up with deer already

Not in my setup :-|

**Comment by ralesi** [comment]
Set `ranger-override-dired` to always use deer.

**Comment by TheBB** [comment]
Should we do that instead maybe?

**Comment by sooheon** [comment]
@ralesi That setting seems to be buggy for me. It works when ranger/deer is initialized before dired, but if I directly call dired before ranger is initialized, then it wont' take effect.

**Comment by syl20bnr** [comment]
Thank you for the PR!
May be fixed by #5563 @sooheon can you confirm ?

**Comment by sooheon** [comment]
Can confirm, ranger-override-dried in pre-init fn now works as intended.

**Pull request closed without merging**
