### PR TITLE
Switch “bc” -> “bd” and “wc” -> “wd”

### PR DESCRIPTION
**Pull request by robbyoconnor**
Switch `bc`->`bd` and `wc`->`wd`
**Also:**
- switch spacemacs layouts to the same.
- Add `wD` for ace-delete-window
- switch window dedication toggle to `wt`
- all documentation has been updated to reflect these changes

Addresses issues raised in #5031

### CODE REVIEW

**Comment by AlejandroCatalina** [comment]
:heart: :purple_heart:

**Comment by magthe** [comment]
No! Just when my muscle memory has adapted you go and do this. Is this a deliberate attempt at destabilising my mental health? ;)

Think of the kids! Think of the elderly!

**Comment by robbyoconnor** [comment]
Cherry picked in `develop` -- yadda yadda yadda :tada:

**Comment by syl20bnr** [comment]
Thank you :+1:

**Pull request closed without merging**
