### PR TITLE
core: Add support for more doom themes

### PR DESCRIPTION
**Pull request by Beta1440**
This commit address #9084.

The doom themes are located [here](https://github.com/hlissner/emacs-doom-themes/tree/screenshots).

### CODE REVIEW

**Comment by Cmdv** [comment]
be great to have these in 😄

**Comment by nixmaniack** [comment]
Not all of them are complete. The missing ones from Spacemacs are `doom-vibrant`, `doom-nova` and `doom-tomorrow-night`. Check https://github.com/hlissner/emacs-doom-themes/tree/master/themes. 

This would fail for non-existing themes.

**Comment by Cmdv** [comment]
@nixmaniack I can get all three of them running fine on my spacemacs! when using `M-x load-theme`

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Comment by kRITZCREEK** [comment]
@TheBB You're killing it lately, Thank you so much!

**Comment by nixmaniack** [comment]
@Cmdv Yes, because those are defined by doom-theme but absent from spacemacs. Others such as doom-tron, doom-peacock  aren't available yet and will cause error if added now.

**Comment by Cmdv** [comment]
@nixmaniack I was just going by the 3 you mentioned 😛, but with those yes you're quite right 😄

**Pull request closed without merging**
