### PR TITLE
Better avy-keys default value

### PR DESCRIPTION
**Pull request by ernestas**
Staying on the home to reduce RSI.

### CODE REVIEW

**Comment by bmag** [comment]
:+1: 
IIRC `(?a ?s ?d ?f ?g ?h ?j ?k ?l)` is the default value, so removing this `setq` entirely should be enough (and IMHO better)...

**Comment by ernestas** [comment]
Nice. Did not know that. Changed the pull request.

**Comment by syl20bnr** [comment]
Thank you :+1: 
cc @StreakyCobra in case you did not tweak this settings in the bepo layer ;-)
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by StreakyCobra** [comment]
@syl20bnr It is [already](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bkeyboard-layouts/bepo/config.el#L27) tweaked ;-)

**Comment by syl20bnr** [comment]
@StreakyCobra excellent !

**Pull request closed without merging**
