### PR TITLE
[core] evilify Custom-mode if dotspacemacs-editing-style is 'vim

### LINKED ISSUE #5668: add basic evil keys to M-x customize
New users migrating from Vim could be very confused by this. Before I learned that `M-m` could replace the `SPC` leader and `f10` opened the menu I had no way to switch out of a Custom mode buffer. I resorted to restarting emacs.

It's not enough to evilify the buffer, since you have to be able to type things into the text boxes.

### LINKED ISSUE #6699: Customize mode not evil
Not too much more to say. I don't think it's a bug per se because I doubt this functionality was added in the first place. But customize should ideally start in vim/evil mode, not in emacs mode (if you have vim keybindings selected). If someone can point me to some code that reflects the canonical way of doing this for another mode (adding to the major mode hook?), I can prepare the PR myself.

### LINKED ISSUE #7583: "Customize Option" buffers lack evil mode.
#### Description :octocat:
"Customize Option" buffers lack evil mode.

#### Reproduction guide :beetle:
- Start Emacs
- SPC SPC, customize-variable
- Pick some variable

*Observed behaviour:* :eyes: :broken_heart:
- Get stuck in Emacs mode, panic, until you stumble on C-x b to get to another buffer

*Expected behaviour:* :heart: :smile:
- Move around the buffer in evil mode. I don't know what the expected behavior around the buttons and form field should be.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(dash chrome colors deft fasd semantic slack theming themes-megapack typography pdf-tools github helm latex pandoc restclient
      (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-space-key-behavior 'reject auto-completion-return-key-behavior 'reject auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.1)
      better-defaults markdown org
      (shell :variables shell-default-shell 'term shell-default-term-shell "/usr/bin/zsh" shell-default-height 40 shell-default-position 'bottom)
      emacs-lisp javascript clojure react yaml git syntax-checking)
```

#### Backtrace :paw_prints:
```
```

### LINKED ISSUE #13309: When opening the easy-customization menu, the default emacs keybindings are used instead of the evil-mode keybindings.
#### Description :octocat:
When opening the easy-customization menu, the default emacs keybindings are used instead of the evil-mode keybindings.

#### Reproduction guide :beetle:
- Start Emacs
- open a easy-customization menu with SPC-SPC customize-group or SPC-SPC customize-mode

*Observed behaviour:* :eyes: :broken_heart
- notice the emacs keybindings are activated

*Expected behaviour:* :heart: :smile:
- notice the evil-mode keybindings are activated

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 07d12c130)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(ruby lsp gnus
      (plantuml :variables plantuml-jar-path "~/plantuml.jar")
      dap
      (exwm :variables exwm-custom-init
            (lambda nil
              (exwm/autostart-process "Unclutter " "unclutter")
              (exwm/autostart-process "Dropbox " "dropbox")))
      pdf racket html haskell latex helm auto-completion better-defaults emacs-lisp git markdown bibtex deft pandoc octave
      (org :variables org-want-todo-bindings t)
      python
      (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t shell-default-height 35 shell-default-position 'right)
      syntax-checking spell-checking version-control
      (java :variables java-backend 'lsp)
      javascript)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

### PR DESCRIPTION
**Pull request by Kazark**
This has been requested many times but never implemented.

Fixes #6699
Fixes #5668
Fixes #7583
Fixes #13309

The comments describe the rational behind the bindings. Please let me know if you disagree with my choices at all as I am open to changing; this was my attempt to put something together that didn't entirely disregard the default bindings, while making a lot of sense from an Evil perspective.

### CODE REVIEW

**Review by smile13241324 — APPROVED** [review]
Nicely made :+1:, I really like your comments and code.

**Comment by smile13241324** [comment]
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

**Comment by duianto** [comment]
`SPC` and `n` call the default Emacs commands when the cursor is on a link.

### Reproduction steps:
- `M-x` `customize` `RET` opens the customize buffer
- `TAB` jumps to the first link `Easy Customization`

### Observed:
`n` jumps to the next link: `Emacs manual`
```
n runs the command widget-forward (found in custom-mode-link-map), which is an
interactive compiled Lisp function in `wid-edit.el'.

It is bound to n, TAB.

(widget-forward ARG)
```

`SPC` scrolls:
```
SPC runs the command scroll-up-command (found in custom-mode-link-map), which is
an interactive compiled Lisp function in `window.el'.

It is bound to SPC, <next>.

(scroll-up-command &optional ARG)
  Probably introduced at or before Emacs version 24.1.
```

### Expected:
`n` should probably  jump to the next search pattern match,
and `SPC` should probably open the Spacemacs menu.

**Comment by Kazark** [comment]
@duianto ah, did not realize there was a separate map when you are on links. I will investigate. Thanks for the report.

**Comment by Kazark** [comment]
@duianto please test #13963

**Pull request closed without merging**
