### PR TITLE
[core] Fix warnings '* is an obsolete alias ... use ‘cl-*’ instead.'

### PR DESCRIPTION
**Pull request by Bost**

### CODE REVIEW

**Comment by bcc32** [comment]
I think these files are automatically imported from the Emacs Wiki into the Spacemacs repo and updated by a bot, so these fixes would be overwritten in the next import.  See [this commit](https://github.com/syl20bnr/spacemacs/commit/ed54c7e884421ae45e7d6ceda485c3b90ba9d2e6#diff-6c856954cc851ae46691596d6ae92cd17d2b2f3e2ae3816ae6a3015f68db594f) as an example.

They should probably be fixed by updating the Emacs Wiki instead, although I don't know what the process for doing that is.

**Review by smile13241324 — APPROVED** [review]

**Comment by smile13241324** [comment]
I am not sure if these files are updated regularly, I'll close the pr if they are.

**Comment by Bost** [comment]
Ah yeah, you're right. The files are imported from:
https://www.emacswiki.org/emacs/download/zoom-frm.el
https://www.emacswiki.org/emacs/download/frame-cmds.el

[doc/CI_PLUMBING.org](doc/CI_PLUMBING.org) says:

> Built-in updates
> 
> Bash script [.circleci/built_in/upd_built_in](https://github.com/syl20bnr/spacemacs/blob/develop/.circleci/built_in/upd_built_in) reads [.ci/built_in_manifest](https://github.com/syl20bnr/spacemacs/blob/develop/.ci/built_in_manifest) file line by line and downloads every listed file into its specified location overriding existing ones.

And then:
```bash
$ rg --no-line-number frame-cmds.el\|zoom-frm.el .ci/built_in_manifest
https://raw.githubusercontent.com/emacsmirror/frame-cmds/master/frame-cmds.el layers/+spacemacs/spacemacs-visual/local/zoom-frm/frame-cmds.el
https://raw.githubusercontent.com/emacsmirror/zoom-frm/master/zoom-frm.el layers/+spacemacs/spacemacs-visual/local/zoom-frm/zoom-frm.el
```

**Comment by smile13241324** [comment]
Then I am going to close this PR, thanks for making sure.

**Pull request closed without merging**
