### PR TITLE
Add Colemak layout to keyboard-layout layer

### PR DESCRIPTION
**Pull request by lyallcooper**
The [Colemak keyboard layout](https://colemak.com/) is the third most popular English language keyboard layout (behind QWERTY and Dvorak), and also my keyboard layout of choice. So, I thought it'd be worth adding to the new keyboard-layout layer for myself and anyone else that might find it useful.

Overall, this is a pretty basic change that just adds the `hjkl` ↔ `hnei` mapping, specifies the home row keys and updates the README with a description of the layout.

### CODE REVIEW

**Comment by ajgrf** [comment]
I'm glad I found this PR because I was about to start working on Colemak support myself. So thank you for getting it started! However, I think [these](https://github.com/ohjames/colemak) are smarter Colemak rebindings. So the rebinding table would look like this:

    (colemak . (("n" . "j")
                ("e" . "k")
                ("i" . "l")
                ("k" . "n")
                ("u" . "i")
                ("l" . "u")
                ("j" . "e"))))

They are still pretty minimal changes but it puts I, U, and N back into their QWERTY positions. With your bindings I would probably forever confuse I and U in both QWERTY and Colemak layouts!

What do you think? I know that there are a lot of Colemak users out there who have come up with their own incompatible vim bindings, so I hope this isn't too contentious.

**Comment by lyallcooper** [comment]
That's an interesting remapping. Though I'd be hesitant to make it the default colemak mapping simply because I don't think it would be what people would expect. One solution could be to add a `colemak-alt` map, or perhaps let the user specify their own map.

I'll have a look to see if there's a nice way of doing it when I've got a little bit of time.

**Comment by ajgrf** [comment]
I realized I may have over-emphasized swapping the insert/undo commands, but even if you don't do that I think putting the N bindings back into their QWERTY spot is still worthwhile.  So it would look like this:

    (colemak . (("n" . "j")
                ("e" . "k")
                ("i" . "l")
                ("k" . "n")
                ("l" . "i")
                ("j" . "e"))))

**Comment by TheBB** [comment]
What's the relationship between this and https://github.com/syl20bnr/spacemacs/pull/7178?

**Comment by allentiak** [comment]
#7178 has the same objective. Whereas #6631 contains the related discussion (!).
What about merging all these three issues?
I would say #7178 seems to be the best candidate, as it seems to be the most complete PR.

**Comment by wbolster** [comment]
@ajgrf i agree with your preferred colemak remappings. my [evil-colemak-basics](https://github.com/wbolster/evil-colemak-basics) is an extended implementation of this idea.

**Comment by syl20bnr** [comment]
Thank you !
There are multiple PR for colemak, see https://github.com/syl20bnr/spacemacs/commit/4461721e
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
