### PR TITLE
Use rjsx-mode for react framework

### PR DESCRIPTION
**Pull request by ztlevi**
Since `rjsx-mode` is generally considered better mode for react editing, I put the PR to replace the react-mode with `rjsx-mode`. `rjsx-mode` will also be enabled for files with =react= imported by using `magic-mode-alist`.

### CODE REVIEW

**Comment by ztlevi** [comment]
Since we use this method to enable `yasnippet` in `react-mode` setup [here](https://github.com/ztlevi/spacemacs/blob/develop/layers/+frameworks/react/funcs.el#L21). This command might need to be added when init `yasnippet`.

**Comment by ztlevi** [comment]
As for the failed test, I'm not sure if we need to change the second to the third. It seems like `spacemacs-defaults` is the second one here while the [test](https://github.com/syl20bnr/spacemacs/blob/develop/tests/core/core-configuration-layer-ftest.el#L36) assigns the `spacemacs-base` as the distribution. But I wasn't really change any base distributions in the commits.
```
configuration-layer--used-layers is a variable defined in ‘core-configuration-layer.el’.
Its value is
(spacemacs-bootstrap spacemacs-defaults spacemacs-base ...)

Documentation:
A non-sorted list of used layer names.
```

**Comment by fiveNinePlusR** [comment]
I am curious why you removed company-tern... does completion still work with your changes?

**Comment by ztlevi** [comment]
My bad. I totally moved to lsp now and I forget to put company-tern back. I am going to fix this and open a new PR for lsp.😂

**Comment by ztlevi** [comment]
Just added `company-tern` with rebase.

**Comment by ztlevi** [comment]
lsp support can be tested through this [PR](https://github.com/syl20bnr/spacemacs/pull/10628)

**Comment by ztlevi** [comment]
Any thoughts on this PR. From my perspective, I prefer to put `rjsx-mode` in the Javascript layer because it's just one single packages and the `JSX` file editing is really common across Javascript development.

**Comment by fiveNinePlusR** [comment]
I think it is probably worth using. are you aware of anything that `rjsx-mode` can't do compared to `react-mode`?

**Comment by ztlevi** [comment]
Not really. There are a couple reason I pick `rjsx-mode`.
1. `web-mode` is not designed for JSX and I might need more tweaks compared with `rjsx-mode`
2. `rjsx-mode` support `flow-type`.
3. It's just kind of tricky to enable `lsp` for `web-mode` because that doesn't really work for `html`'s scripts.

**Comment by ztlevi** [comment]
Another choice is to put `rjsx` just under `javascript` layer since it's a single package added for JSX file editing.

**Comment by syl20bnr** [comment]
Yes, it could be put under the javascript layer :+1:

**Comment by fiveNinePlusR** [comment]
I tested this pr out and the layer does not have lsp support when in rjsx mode. tested by calling `lsp-capabilities` and I get a message in the bottom saying this buffer does not support lsp mode. switching to js2-mode and doing the above works just fine. any insight as to why that wouldn't work?

**Comment by syl20bnr** [comment]
Actually let's keep it in `+frameworks/react` for now.

We'll see later if another pattern emerges, for now `react` seems the
natural way to go.

Sylvain Benner <notifications@github.com> writes

> Yes, it could be put under the javascript layer :+1:
>

**Comment by fiveNinePlusR** [comment]
@ztlevi indeed i did and it definitely works under the js2-mode

**Comment by ztlevi** [comment]
@fiveNinePlusR It should be good to test now. Anyone who familiar with flow-type javascript is welcome to test since I'm not really using it.

`lsp-capibilities` result for `rjsx-mode`:
```
The server provides command execution support
The server provides code actions
The server provides completion support
The server provides project symbol support
The server provides file symbol support
The server provides references support
The server provides goto definition support
The server provides signature help support
The server provides hover support
Document sync method: None
```

image

**Comment by axyz** [comment]
didn't try this PR yet, how does it behave with indentation?
as mentioned on https://github.com/syl20bnr/spacemacs/issues/8206 web-mode has in general more consistent indentation, with good prettier/eslint support won't be an issue nowadays, but not everybody will use them.

In general I'm currently trying out mixing webmode and rjsx-mode (waiting for https://github.com/felipeochoa/rjsx-mode/pull/66), maybe is something that can be tried out here as well. It still feel a bit buggy:
- weird copy paste
- not relevant completions polluting the list
- indentation issues
- no autoclose of jsx components

Let me know what's the state in these regards and if could benefit to use rjsx as a minor mode, in general I would also be more than happy to move to a more js specific layer as web-mode is working great on the parsing/indenting side but still feel a bit of a hack and lot of IDE features are not available without rjsx minor mode

**Comment by axyz** [comment]
cool then, I think we can give it a try and eventually iterate over it. Ideally in the future everything could be included under js layer in order to also have a single place that could enable prettier/eslint/flow/etc... using autodiscovery

**Comment by fiveNinePlusR** [comment]
>   1.     < inserts </> whenever it would start a new JSX node (and simply inserts < otherwise).
>   2.   > or C-d right before the slash in a self-closing tag automatically inserts a closing tag and places point inside the element

also, typing the tagname and pressing tab will expand it to the full double enclosing tag.

**Comment by syl20bnr** [comment]
Thank you ! 👍 

I extracted both `tern` and `web-beautify` from javascript layer into their own layer. I also simplified the react layer where I could, see the commits following the merge of this PR.

Cherry-picked and squashed into develop branch, you can safely delete your branch.

**Pull request closed without merging**
