### PR TITLE
org: add org-modern support

### PR DESCRIPTION
**Pull request by TheJJ**
even more beautiful `org-mode` :)

### CODE REVIEW

**Comment by real-or-random** [comment]
Nice stuff! I tested this and I prefer to set   `org-modern-hide-stars " "` to keep the headline indentation... I believe this is what most users want, but I'm not entirely sure if we should override the package default here. If not, this should be documented at least.

**Comment by TheJJ** [comment]
I like that the headline is no longer indented :) But yes, this could be documented for easier adjustment.

**Review by smile13241324 — APPROVED** [review]
Looks good.

**Comment by junghan0611** [comment]
Its really nice. But I would like to remove org-mode -hook of bottleneck and delay a little bit. I think it is better manually use. How could I do that?

**Pull request merged**
