### PR TITLE
Ranger Layer: Docs: Updated key bindings

### PR DESCRIPTION
**Pull request by pbrn46**
Key bindings updated describing file marking, based on the issue https://github.com/syl20bnr/spacemacs/issues/9064

Hope this helps all new people like me!

### CODE REVIEW

**Comment by duianto** [comment]
### Commit message
Something to think about for the next PR/commit, try to make the commit message more specific, there are many places "Updated key bindings" could be referring to.

Something like this is more descriptive: 
Ranger layer README.org: update key bindings

### Key bindings
The ranger package: https://github.com/ralesi/ranger.el documentation was updated recently, the key bindings were grouped into sections: basic, navigation, copy, rename/move or delete, marking, sorting, etc.

I'm not sure how many of the bindings should be listed in the Spacemacs layers documentation. It's probably enough to just list the most used key bindings.

Maybe a link could be added at the bottom, stating that more key bindings can be found in the ranger package documentation: https://github.com/ralesi/ranger.el

### Corrections to this PR
Here are a couple of key bindings that should be changed:
`| ~r~             | (ranger) revert buffer                               |`
r is undefined, change `~r~` to `~;g~`.

The single key entry:
`  | ~C-SPC~         | (ranger) mark current file                           |`
can be removed since it's part of the new entry:
`  | ~C-SPC~ / ~TAB~ | (ranger) mark current file                           |`

and
`| ~V~             | (ranger) visually select lines                       |`
can be removed, it only selects the current line, it doesn't seem to be able to expand the selection to the next/previous line either, so I don't know what it's used for. It has also been removed from the ranger documentation.

**Comment by pbrn46** [comment]
Thanks for the info! If I reword the commit in my branch will it effectively update this PR, or should create a new commit? Same for the PR itself, is it usually better to create a PR or edit this title?

**Comment by TheBB** [comment]
If you force-push your branch it will update this PR. That includes any changes whatsoever, be it changed commit messages or new commits. So feel free to change. (The title you'll have to change here on github.)

**Comment by pbrn46** [comment]
@duianto I've added the corrections suggested to this PR.

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
