### PR TITLE
[clojure] bind c-ret to cider-repl-newline-and-indent in repl

### PR DESCRIPTION
**Pull request by thanhvg**
For evil insert mode

### CODE REVIEW

**Comment by didibus** [comment]
What's the current behavior of C-<return> and <return> ?

**Comment by didibus** [comment]
Hum, I'm wondering, in my own config, I have it that RET is always `cider-repl-newline-and-indent` and C-RET is `cider-repl-return`.

I guess keeping RET intact, and just adding C-RET might be the less intrusive change. I'm just wondering what defaults are best here, since REPL is something people use all the time.

**Comment by thanhvg** [comment]
Default binding for cider in Spacemacs is
````
(kbd "RET") 'cider-repl-return)
 ````
`c-ret` is unbound. 

Your own custom config is the reverse.

**Comment by duianto** [comment]
Thank you for contributing to Spacemacs. It's safe to delete your branch.
The PRs changes have been cherry picked into the `develop` branch. https://github.com/syl20bnr/spacemacs/commit/18715b872bd5574f12feca11cd9af04a6652a4ec

**Comment by didibus** [comment]
Ya, I think the default you chose makes more sense as a default for everyone. I would probably had applied it to the `cider-repl-mode-map` as well, so its consistent for Holy mode users as well.

**Pull request closed without merging**
