### PR TITLE
add nlinum layer

### PR DESCRIPTION
**Pull request by CodeFalling**
A layer to replace linum-mode with [nlinum-mode](https://elpa.gnu.org/packages/nlinum.html), and line-relative-mode with [nlinum-relative-mode](https://github.com/CodeFalling/nlinum-relative).

They would have better performance with large complex files(such as large org file)

### CODE REVIEW

**Comment by TheBB** [comment]
This is great, but I don't think we need a layer for this. It's something we should use by default when the user has line numbers enabled.

**Comment by CodeFalling** [comment]
In this case I need take some time to optimize `nlinum-relative-mode` first.

**Comment by StreakyCobra** [comment]
Related: #5436

**Comment by TheBB** [comment]
Is nlinum-relative any worse than linum-relative?

**Comment by CodeFalling** [comment]
@TheBB I just create nlinum-relative today so it may be not so stable. 

- It can't specify current line number's face for now. 
- It won't update line-number when moving, scrolling etc (Or to say, only update when idle).

**Comment by StreakyCobra** [comment]
If it become the spacemacs' default, it would be nice to put them on MELPA instead of using github fetcher :-)

**Comment by TheBB** [comment]
Okay... well anyway I was thinking of using nlinum by default for a while now anyway. It's possible for the moment to fall back on linum if the user wants relative, or to introduce another option for this package... or just let them specify the delay. Not sure. :-)

But as @StreakyCobra says, for sure you should put your package on MELPA.

**Comment by CodeFalling** [comment]
MELPA's PR is waiting for merge in fact😂 

Be patient, I'll try to fix shortcomings of `nlinum-relative` first.

**Comment by CodeFalling** [comment]
I have tried set delay of `nlinum-relative`  to `0`, then it become as slow as `linum-relative` in large org file but get a immediate updating.

So I am going to add current line face custom for `nlinum-relative`, then make them all default and provide a option to custom delay as need. 

- [ ] add current line face custom for `nlinum-relative`
- [ ] put `nlinum-relative` on MELPA
- [ ] make another PR to make `nlinum` and `nlinum-relative` default
- [ ] provide option to custom delay

**Comment by StreakyCobra** [comment]
Should this be closed in favor of #6037?

**Pull request closed without merging**
