### PR TITLE
Eclim based java layer

### PR DESCRIPTION
**Pull request by kleewho**
I think it's nice start to have java support

### CODE REVIEW

**Comment by emmanueltouzery** [comment]
i think what doesn't work yet should be documented so that a user making the effort to install (eclim seems to be complicated to install) is not disappointed after making the effort that he didn't get all that he thought he would.

**Comment by liujoey** [comment]
can't wait for the merge!

**Comment by kleewho** [comment]
@liujoey I didn't but the thing is that I didn't have time to at least give it a shot. 

@emmanueltouzery I will document whatever is not working for me

**Comment by liujoey** [comment]
@kleewho I've just did some tests:
Assume I have `String method = "";`, if I hit Enter on `method.equ` to complete equals(), it do mess up my buffer (with or without yasnippet, acting the same).

If I hit Enter on `method.ends` to complete endsWith(), it works as expected. When with yasnippet enabled, it put the cursor in the middle of parentheses, and also shows `[yas] snippet expand.` at bottom line. If without yasnippet enabled, it complete the string as `method.endsWith(String suffix)|` and leave the cursor at the end of the line.

**Comment by kleewho** [comment]
@liujoey Did the buffer you're editing have somewhere else the `equals()` somwhere else in the code? The same question for `endsWith()`. I think that's the pattern I'm seeing but I'm not sure

**Comment by liujoey** [comment]
@kleewho you are correct, I do have `equals()` somewhere in the same buffer! Negative for `endsWith()`.
Very good catch! So that's the reason cause this issue?

**Comment by Devagamster** [comment]
Any progress on this front?

**Comment by kleewho** [comment]
@Devagamster I was fighting bug that was mentioned here and which was making this layer very unusable. I found the solution so now I can get back to this. Expect to see something more or less ready to merge in couple of days

**Comment by Devagamster** [comment]
Thats fantastic :+1:

**Comment by kleewho** [comment]
@syl20bnr I think it's ready to merge. Is there anything more that I should do except of making PR?

**Comment by TheBB** [comment]
Really excited about this. Good job! :+1:

**Comment by martinmr** [comment]
I would appreciate if this request could be merged. I am excited to look at this layer.

**Comment by syl20bnr** [comment]
I'm currently "full time" on magit 2.1 support for Spacemacs. I should be able to merge again a few days, thank you for your patient.

**Comment by kleewho** [comment]
@syl20bnr No problem

All others. If you wait for this merge then use it for couple of days and get back here with some thoughts about keybindings. Right now I set some default ones grouped by topics (errors, projects, maven and so on). But we can set couple convenient shortcuts and set for those 2 letters bindings instead of 3 letters one.

**Comment by Devagamster** [comment]
This layer is great, but it has a couple of issues in my small interactions with it. First, the completion is often extremely slow. I'm not sure if this is an issue with emacs-eclim or the company configuration. Second, when using the problem correct feature hitting escape or fd does not make the company completion go away. There is no way to back out of trying to use eclipse's auto correct.

Other than that though it's awesome and I look forward to future improvements.

**Comment by Devagamster** [comment]
Another small change is that when I type a given suggestion after hitting "." after a variable, I expect the suggestion to stay around until either I hit enter or I continue typing. The way it acts now is that if I type all of the characters of a given auto completion the company popup goes away. This is not really helpful if I am using the information about the arguments given in the autocomplete buffer.

**Comment by kleewho** [comment]
@Devagamster I admit that correct problem is very annoying but there are other things that I would like to have in place first.  

About the slow completion... I don't know. I would assume that it's some kind of delay in `company`. 

If you hit enter with yasnippets enabled it will insert the completing method with additional info about type of arguments. Then hitting `tab` will clear the first argument and will let you type something but you still see types for rest of the arguments. Another `tab` and your on second argument. So choosing something will give you that option. Unfortunately writing everything will not.

For every pain point I suggest if you can creating an issue in `[emacs-eclim](https://github.com/senny/emacs-eclim)` and if the right time come maybe someone will fix it. 

Thanks for your input. I appreciate it very much. I will try to address all your pain points. Probably not before initial merge of this pr and most probably any changes will be done in `emacs-eclim` since neither of your pain points doesn't seem to be related to spacemacs integration.

**Comment by Devagamster** [comment]
That makes sense :) As for the spacemacs integration I think it is working very effectively. Keep up the good work and hopefully emacs-eclim will improve with time.

**Comment by syl20bnr** [comment]
Thank you ! Very nice work :+1: 
I made some tweaking and fixes in these commits:
- https://github.com/syl20bnr/spacemacs/commit/1a39ffb
- https://github.com/syl20bnr/spacemacs/commit/71ae452
- https://github.com/syl20bnr/spacemacs/commit/8beeaba
- https://github.com/syl20bnr/spacemacs/commit/b5e2e37
- https://github.com/syl20bnr/spacemacs/commit/b19c3fa

Cherry-picked in `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
