### PR TITLE
Reformat documentation

### PR DESCRIPTION
**Pull request by JAremko**
Now we have a tool that can produce strictly formatted .org files.

- - - - -

Btw  "ci/circleci: Formatting (optional)" will fail because it' not yet updated.

### CODE REVIEW

**Comment by d12frosted** [comment]
Insane. Seriously 💯

**Comment by sdwolfz** [comment]
Looks like you have some formatting to fix :wink::
```diff
diff --git a/layers/+lang/ipython-notebook/README.org b/layers/+lang/ipython-notebook/README.org
index ecb05a430..eb7368143 100644
--- a/layers/+lang/ipython-notebook/README.org
+++ b/layers/+lang/ipython-notebook/README.org
@@ -37,11 +37,8 @@ lots of informative stuff.
 This is a WIP, feel free to collaborate.
 
 ** TODO Maybe it'd be better if there was a state for this
-
 ** TODO Make more keybinding to =connect= to a python buffer
-
 ** TODO Deleting visual regions don't work, find out why
-
 * Install
 ** Layer
 To use this configuration layer, add it to your =~/.spacemacs=. You will need to

```

**Comment by JAremko** [comment]
@sdwolfz  I think having empty-lines there is usefull. It helps to differentiate empty headlines and folded ones. :thinking:

**Comment by JAremko** [comment]
@sdwolfz  An empty headline look the same as a folded one(in the org-mode).  Inserting empty lines make them instantly identifiable.  So I prefer to have empty lines there :thinking:

**Comment by sdwolfz** [comment]
:+1: Sounds like a practical choice, do you intend to make them mandatory for all org files? You might have to change in A LOT of files.

**Comment by JAremko** [comment]
@sdwolfz  It's the only place where we have empty headliners :smile: 

*actually empty headlines are treated as a bug unless they have TODO label*

**Comment by robbyoconnor** [comment]
Time to rebase @JAremko -- rebase to the right....rebase to the left...

**Comment by JAremko** [comment]
Alright I'll simply made old format checker happy for now and try to release the new "auto fixer" ASAP.

**Comment by nixmaniack** [comment]
@JAremko Is the replacement of quotation marks(`"` -> `“/”`) and apostrophe(`'` -> `’`) in strings automated? 
With a normal keyboard, I see it getting inconsistent sooner as inserting opening/closing quotes with correct unicodes is "not normal".

**Comment by JAremko** [comment]
@nixmaniack  Yes. Automated.

**Comment by JAremko** [comment]
@deb0ch  I don't think that they look worse(prolly even better). But objectively it's easier to tell witch side is wrapped, especially if closing bracket is on another line.

**Comment by deb0ch** [comment]
Ok, if it's wanted it's fine by me I don't really care. It's just that they are not accessible on a regular keyboard and I would expect ascii files out of org docs, but I don't think that it's too important.

Maybe an old grief due to some code not compiling or bugging because of these f***ers sneaking in.

**Comment by d12frosted** [comment]
Using the right™ typography means more automated PRs.

**Pull request merged**
