### PR TITLE
add chinese layer

### PR DESCRIPTION
**Pull request by andyque**
This layer mainly add the following functionalities:

1. Add Chinese Pinyin Input method.
2. Add Chinese Wubi input method.
3. Add Youdao Dictionary.
4. Add Chinese Pinyin support for ace-jump-mode
5. Add Chinese Pinyin search ability in dired buffer

Improve the font size when mix Chinese and English words.

### CODE REVIEW

**Comment by tumashu** [comment]
Good job!

**Comment by zzguiji** [comment]
nice layer!.. Awesome…

**Comment by hick** [comment]
nice work!

**Comment by mh29110** [comment]
GJ

**Comment by louy2** [comment]
`eim` is pretty old. It has a successor: https://github.com/tumashu/chinese-pyim

**Comment by andyque** [comment]
@louy2  Chinese-pyim only support Pinyin. I use `eim` for Wubi input.  As in this PR, both packages are integrated and the user could determine which package to activate. You could refer to the README.org for more information.
Thanks.

**Comment by syl20bnr** [comment]
This is great ! :+1: 

But `eim` is huge, I cannot merge this PR like this into the Spacemacs repo, here are the solutions I propose:
1) we remove eim extension from the layer but we keep the configuration and we put some instructions in the README.org describing how to install it.
2) we submit a recipe to MELPA if it is doable.

Even if we cannot do 2), it is planned to integrate Quelpa into Spacemacs so we will be able to use elisp code from a github repo. For now we have to do some work-arounds.

**Comment by andyque** [comment]
Thanks, @syl20bnr  I will try to make `eim` a MELPA package. 
After everything is done, I will ping you.

**Comment by syl20bnr** [comment]
@andyque excellent :+1:

**Comment by andyque** [comment]
@hijarian  The "Hiragino Sans GB" font is bundled with Mac OS X. I think the function `spacemacs//set-monospaced-font` could also be called in user's `spacemacs/config` function with a different font name.

Maybe I should add this to the README.org.

**Comment by hijarian** [comment]
@andyque Yeah, but I am quite sure it's not bundled by default into Debian and, more importantly, Windows, too. :)

**Comment by andyque** [comment]
Hi @syl20bnr  The eim has been submitted to MELPA and I have changed the name to *chinese-wbim* to better indicate the intent.

https://github.com/milkypostman/melpa/pull/2874#event-338655231

**Comment by andyque** [comment]
hi @syl20bnr  Any update with this PR?

**Comment by andyque** [comment]
@syl20bnr  new PR with squashed commits at here:  https://github.com/syl20bnr/spacemacs/pull/2132

**Pull request closed without merging**
