### PR TITLE
[React layer] Expand to className when using emmet

### PR DESCRIPTION
**Pull request by CestDiego**
`div.react-class >>> <div className="react-class"></div>`

See https://github.com/smihica/emmet-mode/pull/67

### CODE REVIEW

**Comment by TheBB** [comment]
Doesn't it make sense to make this a buffer-local variable?

**Comment by CestDiego** [comment]
oh...yeah this should've been into a hook :( sorry fixing now :)

**Comment by TheBB** [comment]
It's already in a hook. :-) I suspect you just need `setq-local` since from what I can see that variable doesn't become buffer-local when you set it.

**Comment by CestDiego** [comment]
you are right, just changed the setq-local :( it's 2am here xD I shouldn't be emacs lisping :P

**Comment by CestDiego** [comment]
I actually think that I should've made the variable definition buffer local right? I even think that it shouldn't even take that into account but use the web-mode type thing to guess if the current file is of `jsx` type and set the class => className by itself.

**Comment by TheBB** [comment]
Yeah, I think so too. But this will do for now. I'll merge this later today.

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
