### PR TITLE
[WIP] Cleanse the org file headlines

### PR DESCRIPTION
**Pull request by JAremko**
This way the doc headers are more consistent. Also it will help with making org files work both in Emacs and GitHub.

### CODE REVIEW

**Comment by JAremko** [comment]
I think I'll also write a test for validating org files in PR's so we will not need to do it all over again. But It will be separate PR

**Comment by robbyoconnor** [comment]
> Clense 

 :laughing:

**Comment by JAremko** [comment]
After some extensive grepery and sedery I forget [the list](https://gist.github.com/JAremko/0d9b65c1ed3758acd306) most of those lines has to be replaced with something that works on the GitHub. 

@robbyoconnor  When it sounds epic I feel less lazy :smiley:

**Comment by robbyoconnor** [comment]
Nothing, I'm just in a funny mood

**Comment by JAremko** [comment]
Actually GitHub seems to work well with multiple capitalisations in org files.

**Comment by robbyoconnor** [comment]
:heart:

**Comment by JAremko** [comment]
Ok. Now I know what to do for realz  :smiling_imp:

**Pull request closed without merging**
