### PR TITLE
Fixes #3491 - Prompt to open file literally when opening large files.

### LINKED ISSUE #3491: Open big files seems too slow
I opened a file(4.6 M) in emacs on Mac OS X 10.11, but it seems too slow for me. I tried to stop all the minor mode but it seems of no help. Can any one give a solution?

### PR DESCRIPTION
**Pull request by ralesi**
Addresses #3491 with automatic prompt.

### CODE REVIEW

**Comment by joehillen** [comment]
:+1:

**Comment by syl20bnr** [comment]
That's great, can you add a variable for the size ?

**Comment by ralesi** [comment]
@syl20bnr,  we want it in dotspacemacs?

**Comment by ralesi** [comment]
Currently it is in the form of buffer size,  we could do more work and base it on filesize if that would be better.

**Comment by syl20bnr** [comment]
Yes, it can be a dotfile since it is a pretty important variable and it will make it more obvious to the user that Spacemacs will automatically shutdown modes when a file is too big.

Is there any difference between the file size and the buffer size for this functionality ? I guess that buffer size is ok.

**Comment by ralesi** [comment]
@syl20bnr, the buffer size is simply going to be the number of characters in the buffer, whereas if we determine the file size from the buffer filename, we will be talking in units of MB.

**Comment by syl20bnr** [comment]
@ralesi oh right, for the user exposing file size is better.

**Comment by CestDiego** [comment]
so using something like https://github.com/m00natic/vlfi wouldn't help?

**Comment by syl20bnr** [comment]
@CestDiego Interesting package, we should test it with evil.

**Comment by ralesi** [comment]
@CestDiego, I think `vlfi` would be better if we can get consistent usage across the emacs / evil space.  The problem I have had with `vlfi` in the past is that some of my most common commands (like `:%s`), don't work with it.   To be fair though, I only tried it once with a 40MB file, do you have more experience with it?

**Comment by CestDiego** [comment]
I haven't

**Comment by ralesi** [comment]
@syl20bnr, updated to check for file size instead.

**Comment by TheBB** [comment]
Do we know that this hook runs both early enough to avoid performance problems with large files, and late enough to override anything else that might happen?

I just tried and it certainly caused the major mode and associated minor modes to be loaded, even though they ended up not being enabled in the resulting buffer. The regular `find-file-literally` doesn't have the same behaviour.

**Comment by ralesi** [comment]
Most of the benefit I see from this is easier navigation of files after the fact.   I guess another option would be to add to find-file-functions.   Was there a performance hit when opening the large file?

**Comment by syl20bnr** [comment]
So I'm for merging this, what's your opinions ?

**Comment by tuhdo** [comment]
I used it on 1 GB source file before. It works fine.

**Comment by zilongshanren** [comment]
@syl20bnr 
+1 for merging it into develop

**Comment by matleh** [comment]
What needs to be done to get this merged? I tried to open a 15MB JSON file and emacs is not usable - just hangs and I have to kill it. So this would be very beneficial.

**Comment by TheBB** [comment]
I don't mind merging it, but as noted in https://github.com/syl20bnr/spacemacs/pull/3609#issuecomment-156861749 this solution is not equivalent to `find-file-literally`, and I can't guarantee that there aren't cases where it'll still break.

**Comment by syl20bnr** [comment]
Seems to work, I was able to open a 13MB file without any issue.
Do we think 1MB is a good default ? I find it a bit low.
Thank you :+1: 
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by ksjogo** [comment]
1MB seems indeed a bit low.

**Pull request closed without merging**
