### PR TITLE
add company-php to php layer

### PR DESCRIPTION
**Pull request by xcwen**
add company-php to php layer

### CODE REVIEW

**Comment by robbyoconnor** [comment]
There was no need to make 3 PRs...Learn how to rebase -- heck it's so easy using `magit`!

**Comment by xcwen** [comment]
it is not ok ?!

**Comment by TheBB** [comment]
It's fine. Just update your PR when you want to make changes. No need to make a new one.

I can't find `ac-php-code-eldoc-setup` anywhere in the `company-php` package. Where is it from?

**Comment by xcwen** [comment]
ac-php-code-eldoc-setup  in  `ac-php-core`  ,  company-php  is dependent on  `ac-php-core`

**Comment by TheBB** [comment]
Oh, I was looking at https://github.com/stesie/company-php, which is apparently the wrong company-php.

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

I had to apply some changes to make it correct and/or more idiomatic: https://github.com/syl20bnr/spacemacs/commit/e6a3d01eb541763e9c8d0d896b33e6f40a2d807b

**Comment by xcwen** [comment]
ok :+1:

**Pull request closed without merging**
