### PR TITLE
* core-spacemacs-buffer.el: avoid to call functions from org-mode at startup

### PR DESCRIPTION
**Pull request by sunlin7**
The Spacemacs take a long time to startup, after investigating, I found that it will invoke the function `(org-agenda-files)` from the function `spacemacs-buffer//insert-recent-files`, which will lead loading the `org.el` file, a very heavy loading procedual.

After rewrite the function, it will reduce **50%** of the startup time for Spacemacs.

Please help review and merge it.
Thanks.

### CODE REVIEW

**Review by smile13241324 — APPROVED** [review]

**Comment by yantar92** [comment]
@sunlin7 Would it be possible to provide profiler reports on slow startup?

**Comment by sunlin7** [comment]
I'm working on a slow machine, and load the `org` package from freshed take more than 2 seconds. 
```emacs -nw -q --batch --eval '(message "%s" (benchmark-run 1 (autoload (quote org-agenda-files) "org")(org-agenda-files)))'```

**Comment by yantar92** [comment]
"lin.sun" ***@***.***> writes:

> I'm working on a slow machine, and load the `org` package from freshed take more than 2 seconds. 
> ```emacs -nw -q --batch --eval '(message "%s" (benchmark-run 1 (autoload (quote org-agenda-files) "org")(org-agenda-files)))'```

Is your Org mode byte-compiled?
Can you share the output of M-x profiler-start <RET> cpu <RET> <load
org> M-x profiler-report M-x profiler-report-write-profile?

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by sunlin7** [comment]
Hi @yantar92 
My illustration code  in Spacemacs is:
```
(profiler-start 'cpu)
(define-advice require (:before (&rest args))
  (message "xrequire: %s" (car args)))
(message "%s" (org-agenda-files))
(profiler-report)
```
The profiler result for calling `(org-agenda-files)` in Spacemacs is as below,
``` 
    Samples    %   Function
        5363  99% - normal-top-level
        5363  99%  - command-line
        5363  99%   - command-line-1
        5363  99%    - load-with-code-conversion
        5353  99%     - message
        5269  98%      - org-agenda-files
        2610  48%       - byte-code
        2309  42%        + require
         227   4%        + custom-declare-variable
           5   0%        + load
           1   0%        + org-release
        2483  46%       - do-after-load-evaluation
        2405  44%        + eval-after-load-helper
          77   1%        + eval-after-load-helper
           1   0%          eval-after-load-helper
         175   3%       + defconst
           1   0%       + easy-menu-do-define
           1   0%     + prog1
           7   0% + ...
```
And a simple `(org-agenda-files)` will trigger follow requires:
```
CPU profiler started
xrequire: org-compat
xrequire: cl-lib
xrequire: seq
xrequire: org-macs
xrequire: cl-lib
xrequire: format-spec
xrequire: cl-lib
xrequire: calendar
xrequire: cal-menu
xrequire: calendar
xrequire: find-func
xrequire: format-spec
xrequire: org-macs
xrequire: org-compat
xrequire: org-keys
xrequire: org-macs
xrequire: cl-lib
xrequire: oc
xrequire: org-macs
xrequire: org-compat
xrequire: org-macs
xrequire: seq
xrequire: ol
xrequire: org-macs
xrequire: org-compat
xrequire: org-macs
xrequire: org-fold
xrequire: org-macs [2 times]
xrequire: org-fold-core
xrequire: org-macs [2 times]
xrequire: org-compat
xrequire: oc
xrequire: org-table
xrequire: org-macs
xrequire: cl-lib
xrequire: org-macs
xrequire: org-compat
xrequire: org-keys
xrequire: org-fold-core
xrequire: org-fold
xrequire: org-cycle
xrequire: org-macs [2 times]
xrequire: org-fold
xrequire: ob-emacs-lisp
xrequire: org-macs
xrequire: ob-core
xrequire: org-macs
xrequire: cl-lib
xrequire: ob-eval
xrequire: org-macs [2 times]
xrequire: org-fold
xrequire: org-compat
xrequire: org-cycle
xrequire: outline
xrequire: time-date
xrequire: cl-lib
xrequire: subr-x
xrequire: org-entities
xrequire: org-macs
xrequire: org-faces
xrequire: org-macs
xrequire: org-list
xrequire: org-macs
xrequire: cl-lib
xrequire: org-macs
xrequire: org-compat
xrequire: org-fold-core
xrequire: org-footnote
xrequire: org-macs
xrequire: cl-lib
xrequire: org-macs
xrequire: org-compat
xrequire: org-pcomplete
xrequire: org-macs [2 times]
xrequire: org-compat
xrequire: pcomplete
xrequire: comint
xrequire: ring
xrequire: ansi-color
xrequire: ansi-osc
xrequire: regexp-opt
xrequire: org-src
xrequire: org-macs
xrequire: cl-lib
xrequire: ob-comint
xrequire: org-macs
xrequire: ob-core
xrequire: org-compat
xrequire: comint
xrequire: org-macs
xrequire: org-compat
xrequire: org-keys
xrequire: org-footnote
xrequire: org-macro
xrequire: org-macs
xrequire: cl-lib
xrequire: org-macs
xrequire: org-compat
xrequire: ob
xrequire: org-macs [2 times]
xrequire: org-compat
xrequire: org-keys
xrequire: ob-eval
xrequire: ob-core
xrequire: ob-comint
xrequire: ob-exp
xrequire: org-macs
xrequire: ob-core
xrequire: ob-table
xrequire: org-macs
xrequire: ob-core
xrequire: org-macs
xrequire: ob-lob
xrequire: org-macs
xrequire: cl-lib
xrequire: ob-core
xrequire: ob-table
xrequire: ob-ref
xrequire: org-macs
xrequire: ob-core
xrequire: org-macs
xrequire: cl-lib
xrequire: ob-tangle
xrequire: org-macs
xrequire: cl-lib
xrequire: org-src
xrequire: org-macs
xrequire: ol
xrequire: org-clock
xrequire: org-macs
xrequire: cl-lib
xrequire: org
xrequire: ox-rfc
xrequire: ox
xrequire: org-macs
xrequire: cl-lib
xrequire: ob-exp
xrequire: oc
xrequire: ol
xrequire: org-element
xrequire: org-macs
xrequire: avl-tree
xrequire: generator
xrequire: ring
xrequire: cl-lib
xrequire: ol
xrequire: org
xrequire: org-persist
xrequire: org-macs
xrequire: org-compat
xrequire: org-id
xrequire: org-macs
xrequire: org
xrequire: org-refile
xrequire: org-macs
xrequire: org
xrequire: ol
xrequire: xdg
xrequire: org-compat
xrequire: org-entities
xrequire: org-footnote
xrequire: org-list
xrequire: org-macs
xrequire: org-table
xrequire: org-fold-core
xrequire: org-macro
xrequire: tabulated-list
xrequire: subr-x
xrequire: ox-ascii
xrequire: org-macs
xrequire: ox
xrequire: ox-publish
xrequire: org-macs
xrequire: cl-lib
xrequire: format-spec
xrequire: ox
xrequire: cl-lib
xrequire: ox-html
xrequire: org-macs
xrequire: cl-lib
xrequire: format-spec
xrequire: ox
xrequire: ox-publish
xrequire: table
xrequire: regexp-opt
xrequire: bytecomp
xrequire: ox-html
xrequire: ox-icalendar
xrequire: org-macs
xrequire: cl-lib
xrequire: org-agenda
xrequire: org-macs
xrequire: cl-lib
xrequire: ol
xrequire: org-fold-core
xrequire: org
xrequire: org-macs
xrequire: org-refile
xrequire: org-element
xrequire: ox-ascii
xrequire: ox-latex
xrequire: org-macs
xrequire: cl-lib
xrequire: ox
xrequire: ox-publish
xrequire: ox-odt
xrequire: org-macs
xrequire: cl-lib
xrequire: format-spec
xrequire: org-compat
xrequire: org-macs
xrequire: ox
xrequire: table
xrequire: rng-loc
xrequire: nxml-util
xrequire: nxml-parse
xrequire: nxml-util
xrequire: xmltok
xrequire: nxml-enc
xrequire: nxml-ns
xrequire: nxml-util
xrequire: rng-parse
xrequire: nxml-parse
xrequire: rng-match
xrequire: rng-pttrn
xrequire: rng-util
xrequire: rng-dt
xrequire: rng-util
xrequire: rng-dt
xrequire: rng-uri
xrequire: rng-util
xrequire: xmltok
xrequire: url-parse
xrequire: ox-ascii
xrequire: subr-x
xrequire: ox-rfc
```

**Comment by sunlin7** [comment]
And my local enabled layers:
```
(auto-completion
             better-defaults
             (c-c++ :variables
                    c-c++-backend 'lsp-clangd)
             (chinese :variables chinese-default-input-method t)
             cmake
             csv
             dap
             django
             emacs-lisp
             epub
             git
             helm
             html
             ibuffer
             imenu-list
             ietf
             (javascript :variables
                         js2-basic-offset 2
                         javascript-backend 'lsp
                         javascript-lsp-linter nil)
             (lsp :variables
                  lsp-clients-lua-language-server-install-dir (expand-file-name "share/lua-language-server" portable-root-dir)
                  lsp-lua-workspace-preload-file-size 500)
             (lua :variables
                  lua-indent-offset 4
                  lua-lsp-server 'lua-language-server)
             markdown
             multiple-cursors
             nginx
             (org :variables
                  org-plantuml-jar-path (expand-file-name "share/plantuml.jar" portable-root-dir))
             octave
             python
             rust
             (shell :variables shell-default-shell 'vterm)
             syntax-checking
             systemd
             smex
             (sql :variables sql-capitalize-keywords t
                  sql-capitalize-keywords-blacklist '("name" "varchar"))
             treemacs
             typescript
             vimscript
             version-control
             (xclipboard :variables xclipboard-enable-cliphist t)
             yaml
             windows-scripts)
```

**Comment by sunlin7** [comment]
And follow lines maybe affect process loading org mode:
```
evil-org-20221001.2335/evil-org.el:799:(with-eval-after-load 'org-capture
evil-org-20221001.2335/evil-org.el:804:(with-eval-after-load 'org-src
evil-org-20221001.2335/evil-org.el:809:(with-eval-after-load 'org-table
expand-region-20221030.957/expand-region.el:186:(eval-after-load 'org            '(require 'the-org-mode-expansions))
org-contrib-0.4.1/org-panel.el:42:;;   (eval-after-load 'org-mode
org-contrib-0.4.1/org-choose.el:482:(eval-after-load 'org
smartparens-20230118.2010/smartparens-config.el:121:(eval-after-load 'org                      '(require 'smartparens-org))
orgit-20230212.2013/orgit.el:259:(with-eval-after-load 'org
orgit-20230212.2013/orgit.el:296:(with-eval-after-load 'org
orgit-20230212.2013/orgit.el:361:(with-eval-after-load 'org
treemacs-20230104.1319/treemacs-compatibility.el:128:(with-eval-after-load 'org
window-purpose-20210628.715/window-purpose-fixes.el:291:  (with-eval-after-load 'org
```

**Comment by lebensterben** [comment]
@sunlin7 

is it natively compiled?

**Comment by sunlin7** [comment]
Yes.

**Comment by yantar92** [comment]
"lin.sun" ***@***.***> writes:

> The profiler result for calling `(org-agenda-files)` in Spacemacs is as below,

Thanks. Though providing full information (M-x
profiler-report-write-profile) would be more useful.

>         2309  42%        + require

It is hard to judge this without looking what is inside.

>         2483  46%       - do-after-load-evaluation

This is Spacemacs-specific tweaks loading staff after loading Org.
I recommend deferred loading on idle instead.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by lebensterben** [comment]
> This is Spacemacs-specific tweaks loading staff after loading Org. I recommend deferred loading on idle instead.

how?

**Comment by yantar92** [comment]
Lucius Hu ***@***.***> writes:

>> This is Spacemacs-specific tweaks loading staff after loading Org. I recommend deferred loading on idle instead.
>
> how?

For example, using run-with-idle-timer. You can also study :defer
keyword implementation in use-package.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by lebensterben** [comment]
@yantar92 

in most cases we already use :defer

**Comment by yantar92** [comment]
Lucius Hu ***@***.***> writes:

> in most cases we already use :defer

The backtrace shows that what is remaining is still taking at least as
much time as Org itself. (Note that personal configuration, if any, may
also affect the profiler data)

I do not know if you can or should do anything about this fact.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by sunlin7** [comment]
Hi @yantar92 
The eval-after-load actions for org are heavy, but they're from the Spacemacs essential packages:
`evil-org`, `org-contrib`, `smartparens`, `orgit`, `treemacs`, `window-purpose`.
It's hard to disable the scripts.

And I had try follow the script to measure the peformance.
For vallina emacs, it only take ~0.15 seconds on my local;
while it will take ~5 seconds from Spacemacs.
I had attached the profiler result files and the xrequire log files.
```
(custom-set-variables
 '(gc-cons-threshold 100000000)
 '(gc-cons-percentage 0.1)
 '(org-agenda-files '("personal.org" "action.org" "memory.org" "sched.org" "todo.org" "note.org" "wait.org")))

(profiler-start 'cpu)
(define-advice require (:before (&rest args))
  (message "xrequire: %s" (car args)))
(autoload 'org-agenda-files "org")
(message "time: %s"
         (benchmark-run 1 (org-agenda-files)))
(profiler-report)
```
[emacs-vallina-CPU-profile-for-org.log.gz](https://github.com/syl20bnr/spacemacs/files/10773549/emacs-vallina-CPU-profile-for-org.log.gz)
[emacs-vallina-xrequire-list-for-org.log.gz](https://github.com/syl20bnr/spacemacs/files/10773550/emacs-vallina-xrequire-list-for-org.log.gz)
[spacemacs-CPU-profile-for-org.log.gz](https://github.com/syl20bnr/spacemacs/files/10773551/spacemacs-CPU-profile-for-org.log.gz)
[spacemacs-xrequire-list-for-org.log.gz](https://github.com/syl20bnr/spacemacs/files/10773552/spacemacs-xrequire-list-for-org.log.gz)

**Comment by lebensterben** [comment]
@sunlin7 Can you try this

I optimized it a little bit.

[core-spacemacs-buffer.el.tar.gz](https://github.com/syl20bnr/spacemacs/files/10773687/core-spacemacs-buffer.el.tar.gz)

---

Anyway, I think it's meaningless to delay loading `org-agenda` when `org-agenda-files` variable is a list.

Because we ALWAYS need to load `org-agenda` (and hence `org`) when inserting todos or agenda items into home buffer.

**Comment by yantar92** [comment]
"lin.sun" ***@***.***> writes:

> The eval-after-load actions for org are heavy, but they're from the Spacemacs essential packages:
> `evil-org`, `org-contrib`, `smartparens`, `orgit`, `treemacs`, `window-purpose`.
> It's hard to disable the scripts.
>
> And I had try follow script to measure the peformance.
> For vallina emacs, it only take ~0.15 seconds on my local;

This is similar to what I know. 2-3 seconds loading in vanilla Org has
only been reported on unoptimized Emacs builds.

> while it will take ~5 seconds from Spacemacs.

This is fishy. A simple require should not take that much - Org
byte-code is occupying several Mbs yet it is loaded in a fraction of
second.

So, there is actual Elisp runtime code being executed by Spacemacs (or
packages required by Spacemacs) during loading. Such runtime execution
is generally not a good practice, unless it is strictly necessary.

If possible, I'd recommend doing expensive calculations on compile time
instead of load time. For example, some code may be wrapped into
`eval-when-compile'.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by lebensterben** [comment]
you can also start Emacs with

    emacs --timed-requires

and go to the Load Time buffer

**Pull request merged**
