### PR TITLE
[bot] Documentation formatting

### PR DESCRIPTION
**Pull request by emacspace**
Merge with care - I'm just a stupid bot. Beep boop.

### CODE REVIEW

**Comment by sdwolfz** [comment]
Huh? @JAremko why did it revert this change?

**Comment by JAremko** [comment]
@sdwolfz  https://github.com/syl20bnr/spacemacs/pull/11588#issuecomment-438094243 :thinking:

**Comment by JAremko** [comment]
@sdwolfz  I disabled TravisCI job auto-cancel.  This should help.  :thinking:

**Comment by JAremko** [comment]
Actually merging commits that wasn't re-based may cause this. I'll add re-base to the Travis CI script.

**Pull request closed without merging**
