### PR TITLE
Move forge from github to git

### PR DESCRIPTION
**Pull request by fabianhjr**
Supports:
- Github (Both .com and enterprise on premises)
- Gitlab (Both .com and self-hosting)
- gogs / gitea

https://github.com/magit/forge/

### CODE REVIEW

**Review by smile13241324 — CHANGES_REQUESTED** [review]
I have double checked your changes and noticed that the package you have integrated is already owned by the github layer. If it is able to handle gitlab too, please move it from there to the git layer.

Also remember that just adding a package to the package.el file does not load or install it, it always requires a init function, see doc/LAYERS.org for details.

**Comment by fabianhjr** [comment]
Thanks for the heads up, will take a look.

**Comment by fabianhjr** [comment]
Hi @smile13241324, I amended the commit to be a move of forge form github into the git layer.

**Review by smile13241324 — APPROVED** [review]
Looks good :+1: , will be merged soon.

**Comment by smile13241324** [comment]
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

**Comment by fabianhjr** [comment]
Nice, thanks @smile13241324 UwU

**Pull request closed without merging**
