### PR TITLE
add company mode to lua layer

### PR DESCRIPTION
**Pull request by rphillips**

### CODE REVIEW

**Comment by trishume** [comment]
Really this is solving a specific case instead of a more general one. 

Globally activated company should be the default in spacemacs, but it isn't. I've been using global company for months with no issues and I believe that most people would prefer `company-dabbrev` when there is no specific engine rather than just no auto-completion at all.

**Comment by rphillips** [comment]
@trishume is there a PR or option to enable company mode globally?

**Comment by syl20bnr** [comment]
@trishume We already discussed about this, setting company globally is a user choice. This is not specific to company, we try to avoid global modes when we can and instead explicitly add the setting in the layer in order to have exhaustive layer configuration. The user should be able to read a packages.el and understand what feature we provide.

@rphillips you just have to add `(global-company-mode)` to `dotspacemacs/config` (https://github.com/syl20bnr/spacemacs/tree/develop/contrib/auto-completion#enable-company-or-auto-complete-globally).

**Comment by trishume** [comment]
I disagree and have no idea why you would avoid global modes. 

The main value proposition of spacemacs is that it saves you the time it would take to configure and figure out all this yourself. Having the best defaults is a core part of that. The default behaviour in spacemacs should be the one that most people would want. If you consistently applied the principle of don't enable anything by default you are left with stock emacs and installing melpa packages.

You would still have to add the auto-completion library to get global company and it literally wouldn't change anything except that in places where you previously would have no auto-completion (like lua right now) you now would have completion.

**Comment by tuhdo** [comment]
I agree @trishume, since we already set specific backends for each major mode. If a major mode is not explicitly supported, we should just use `company-dabbrev` as default and set `company-idle-delay` to 0.

**Comment by mijoharas** [comment]
hmm... I kinda see the point in not having company enabled globally, though I don't have any strong thoughts about it. How about having company be enabled for any mode derived from `prog-mode` (or something similar).

**Comment by trishume** [comment]
@mijoharas Indeed what we had before was company enabled globally but excluded from markdown and other writing modes. I like the idea of enabling only for prog-mode derivatives.

**Comment by syl20bnr** [comment]
At spacemacs level company must be explicitly enabled in each layer. At the user level it can be enabled globally as mentioned in the README. It provides better isolation and it is a good thing, for instance it will allow some nice features like being able to exclude a package for a specific layer (not yet implemented: https://github.com/syl20bnr/spacemacs/blob/develop/core/core-configuration-layer.el#L267).

@rphillips Thank you for the PR but I close it as a duplicate of the merged PR #1760

**Comment by rphillips** [comment]
sounds great. thanks for looking at it.

**Pull request closed without merging**
