### PR TITLE
Inject `user-emacs-directory' in `async-start'

### PR DESCRIPTION
**Pull request by brabalan**
This should address issue #3390 .

### CODE REVIEW

**Comment by syl20bnr** [comment]
@brabalan @justbur is this PR still required or did you manage to resolve the issue differently ?

**Comment by justbur** [comment]
I think @brabalan's reason for needing this is somewhat unique (running two separate instances of emacs side-by-side, one of which is spacemacs), and this is not necessarily a robust solution. However, I don't think it hurts anyone to do this. 

We talked about other possible solutions, but haven't found any yet that satisfies @brabalan's use case.

**Comment by brabalan** [comment]
@syl20bnr I still need this to be able to run spacemacs alongside another instance of emacs. This works for me, but I would be happy with any other solutions that lets me do that.

**Comment by AdrieanKhisbe** [comment]
I'm facing the same use case than @brabalan, 
The patch is very clean and explicit and would not cause trouble to people having just one `.emacs.d`

Shall we merge it? :)

**Comment by TheBB** [comment]
Indeed, let's.

Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
