### PR TITLE
Remove magit-gh-pulls as it never worked too well for me

### PR DESCRIPTION
**Pull request by robbyoconnor**
Remove `magit-gh-pulls`

### CODE REVIEW

**Comment by fiveNinePlusR** [comment]
I must say that being able to easily create topic branches to check out pull requests from inside magit is a huge productivity gain for anyone working on github. magithub doesn't have that feature so I vote this package stays in spacemacs.

**Comment by syl20bnr** [comment]
If magithub can fully replace magit-gh-pulls to handle PR we can remove
it.

I would be happy to use magithub to manage PRs if it is faster than
magit-gh-pulls with it very slow when > 100 PRs.

**Comment by robbyoconnor** [comment]
@syl20bnr magithub is also kinda slow -- and even more so for the issues.....BUT it works for creating PRs and has a better UX...imho.

**Comment by robbyoconnor** [comment]
This is one of the more controversial PRs -- I suspect others would be bothered by this..

**Comment by kommen** [comment]
Note that magit itself added functionality in the last release to deal with pull requests:

https://emacsair.me/2018/03/29/magit-2.12/ https://github.com/magit/magit/blob/66d9558f4f50332a68213683f7702ca0735f7171/Documentation/RelNotes/2.12.0.txt#L263-L272

**Comment by Miciah** [comment]
Did you forget to delete `magit-gh-pulls` from `github-packages`?

**Comment by Compro-Prasad** [comment]
Vote for magithub +1.

**Comment by robbyoconnor** [comment]
Folks: Please use the emoji reactions -- and not simply comment.. it
adds noise and little to no value.

**Comment by Compro-Prasad** [comment]
How do you remove the PR section in magit status buffer?

**Comment by robbyoconnor** [comment]
I am not sure.

**Comment by sdwolfz** [comment]
I played with magit and magithub a bit today, apparently you need to generate 2 tokens, one for the `magit` package and one for the `magithub` package. And Two Factor does not work, so you need to set them up manually in the `.authinfo` file.

I could not check out PRs from this repository, there are to many and maybe the API request times out too fast, as I could easily do that with other project that had only a handful.

**Comment by robbyoconnor** [comment]
2FA worked for me just fine....

**Comment by syl20bnr** [comment]
Is there a variable to control the maximum number of PRs to fetch like
in `magit-gh-pulls`?

**Comment by sdwolfz** [comment]
Some more digging into this, it was not timing out, it was looking for PRs in the wrong place. I have the following remotes defined:
```
origin  git@github.com:sdwolfz/spacemacs.git (fetch)
origin  git@github.com:sdwolfz/spacemacs.git (push)
upstream        https://github.com/syl20bnr/spacemacs (fetch)
upstream        https://github.com/syl20bnr/spacemacs (push)
```

And it was trying to get PRs from `origin`, while I wanted them from `upstream`. I have not found a way to tell it to use `upstream`, that's my next target.

For the other repos I only have one remote, but I can not see more than 30 pull requests, no matter how many are open.

**Comment by Compro-Prasad** [comment]
How can I tell if the PRs shown in status buffer are from `magit-gh-pulls` or `magithub`?

**Comment by sdwolfz** [comment]
I am not sure since I've excluded `magit-gh-pulls` from my packages for this exercise. I don't see anything in the status buffer related to PRs so If I'd have to guess, it should be `magit-gh-pulls`.

**Comment by robbyoconnor** [comment]
@Compro-Prasad very easily -- they're both triggered differently.

**Comment by robbyoconnor** [comment]
@sdwolfz Did you set which is the upstream repository? I forgot how to do it -- I opened this PR from magithub...so I know it works.

**Comment by sdwolfz** [comment]
@robbyoconnor I could not find how to do that so I renamed my remotes, just to try out the functionality. The biggest inconvenience is still the 30 PR limit. I believe it's because of the GH API. Will keep an eye on the magit repo to see what can be done about that.

**Comment by syl20bnr** [comment]
Like it is fetching only the first page of PR ?

**Comment by sdwolfz** [comment]
Yes, only the most recent 30 PRs are fetched and displayed in the helm buffer.

**Comment by sdwolfz** [comment]
Latest version of `magit-gh-pulls` is broken for me since `magit` removed some obsolete functions it was using. So I guess this is a nudge to using magit only from now on :smile_cat:.

```elisp
Debugger entered--Lisp error: (void-function magit-section-value)
  magit-section-value(#<magit-section magit-section-284c148>)
  magit-gh-section-req-data()
  magit-gh-pulls-fetch-commits()
  funcall-interactively(magit-gh-pulls-fetch-commits)
  call-interactively(magit-gh-pulls-fetch-commits)
  magit-invoke-popup-action(102)
  funcall-interactively(magit-invoke-popup-action 102)
  call-interactively(magit-invoke-popup-action nil nil)
  command-execute(magit-invoke-popup-action)

```

**Comment by robbyoconnor** [comment]
:joy_cat:

**Comment by sdwolfz** [comment]
I just merged a PR using only magit. It's not as smooth as using magit-gh-pulls but since that one is broken it will have to do. I will try it out for a few more days and then update the wiki page.

**Comment by fiveNinePlusR** [comment]
So, after a bit of frustration trying to get spacemacs to work with an origin as my own repository and upstream as this repository and having the ability to fetch pull requests from within magit easily I found the setting that needs to be changed. 

Inside magit you probably want to configure `b C` your fetch defaults as upstream, push default as origin. 

The critical one to change is from the command line inside the `~/.emacs.d/` folder you need to add a git variable that is not documented anywhere to set the appropriate upstream for magit to use.

`git config --add magit.upstream upstream`

where upstream is whatever your remote is named for the syl20bnr/spacemacs remote.

**Comment by robbyoconnor** [comment]
I can't seem for the life of me to get 2FA working :crying_cat_face:

**Comment by Compro-Prasad** [comment]
`b y` and `b Y` shows the first thirty pulls. How to get the others?

**Comment by fiveNinePlusR** [comment]
@Compro-Prasad i am not sure but if you know the specific one you want you can type the issue number in and hit enter and it will apply it.

**Comment by sdwolfz** [comment]
After using both `magit` and `magit-gh-pulls` for a while I can say that I like the speed and interactivity of `magit` but I also enjoy the convenience that `magit-gh-pulls` gives.

I found myself using `magit-gh-pulls` again in the end since it allows me to search and I don't have to checkout and delete branches, saving a few keystrokes.

Closing this for now. Hopefully magit itself will one day have a similar experience, but until then `magit-gh-pulls` is the more convenient option.

**Comment by robbyoconnor** [comment]
Perfectly fine! It was a proposal

**Comment by robbyoconnor** [comment]
I will keep this branch updated so just reopen it.

**Comment by sdwolfz** [comment]
@robbyoconnor  :+1: this PR started a good debate, and it definitely pushed me into trying using magit more, so while it's closed, overall it did manage to have a good impact.

**Comment by sdwolfz** [comment]
> I will keep this branch updated so just reopen it.

No need to do that as the change is quite trivial.

**Comment by sdwolfz** [comment]
Thank you :heart:!

I made sure to update the contributing section and the collaborators PR guide.

Cherry-picked into develop branch, you can safely delete your branch.
Commit: 0b5ae3ccbfa36104477c17d6455ea9a0625cfc75.

**Pull request closed without merging**
