### PR TITLE
Add spacemacs OS X icon asset for Emacs.app

### PR DESCRIPTION
**Pull request by ptb**
To replace the default Emacs.app icon with the spacemacs icon:

/bin/cp ~/.emacs.d/assets/spacemacs.icns /Applications/Emacs.app/Contents/Resources/
/usr/bin/defaults write /Applications/Emacs.app/Contents/Info 'CFBundleIconFile' -string 'spacemacs.icns'
/usr/bin/plutil -convert xml1 /Applications/Emacs.app/Contents/Info.plist
/usr/bin/touch /Applications/Emacs.app
/usr/bin/killall Dock && /usr/bin/killall Finder

These steps should not ever be necessary, but are included for completeness:

/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user
/usr/bin/sudo /usr/bin/find /private/var/folders/ -name com.apple.dock.iconcache -exec /bin/rm {} \;
/usr/bin/sudo /usr/bin/find /private/var/folders/ -name com.apple.iconservices -exec /bin/rm -rf {} \;
/usr/bin/sudo /bin/mv /Library/Caches/com.apple.iconservices.store /.Trashes/
/usr/bin/sudo /sbin/reboot

To re-build the spacemacs.icns file, follow these instructions:

<http://stackoverflow.com/questions/6337787/how-can-i-set-the-icon-for-a-mac-application-in-xcode/12156032#12156032>

### CODE REVIEW

**Comment by trishume** [comment]
Note the existence of https://github.com/railwaycat/homebrew-emacsmacport/blob/master/Formula/emacs-mac.rb#L17

**Comment by ptb** [comment]
I wasn't aware of that repository. That said, it seems like the appropriate place for a spacemacs.icns file would be in this repository, not a brew formula for a specific emacs port. Also, the .icns file I built is half the size of the file referenced in that brew formula, even with all the same icon sizes (I used ImageOptim to compress the PNG files before building).

**Comment by trishume** [comment]
@nashamri has a spacemacs icon repository, it's quite possible it should go there.

**Comment by nashamri** [comment]
I don't use OS X but I can see this new icon is smaller in size. @ptb if you send this PR to my repo, I'll merge it there.

**Comment by syl20bnr** [comment]
@ptb Thank you for the optimization of the icon :+1:
Since you PR it in the icon repo I close this PR.

**Pull request closed without merging**
