### PR TITLE
add semantic stickyfunc toggle and activate in python layer

### PR DESCRIPTION
**Pull request by cpaulik**
As discussed a while ago in #738 this adds a toggle for semantic stickyfunc

It also adds the stickyfunc-enhance function to the python layer

If you want I can separate these two things into 2 PR

### CODE REVIEW

**Comment by syl20bnr** [comment]
Great !

cc @tuhdo 
I wonder why but I really would prefer to see the header listing the function where the point is than the name of the function cut at the top of the window, it does not feel right to me, especially without smooth-scrolling.
I know that the minibuffer can display the function signature but it is local to the point in Python, i.e. it does not reflect the defined function where the point is but it reflect the current called function.

@cpaulik  Anyway, great toggle :+1:
Thank you !
Cherry-picked into `develop`, you can safely delete your branch.

**Comment by syl20bnr** [comment]
@cpaulik Oh I just realized that the toggle is global. We may have some issue with it. It should go under a major-specific key binding but `SPC m t` and `SPC m T` are already taken...

**Comment by syl20bnr** [comment]
@cpaulik it is possible to easily set a major-mode specific in the toggle macro, see https://github.com/syl20bnr/spacemacs/tree/develop/contrib/lang/html/packages.el#L89

**Comment by tuhdo** [comment]
@syl20bnr It serves two different purposes: one is for function at point (`eldoc` style) and one is for the function signature that are out of screen. It is useful because sometimes I wonder whether a variable is a global defined variable or just a parameter, or in the case of Python, you have default values and you want to quickly look it up. Sometimes I just forget or there are too many parameters to remember i.e. look at `helm` function as an example. 

But it's ok to toggle it on/off when needed. Just remember that this is a different thing than `eldoc`.

**Comment by cpaulik** [comment]
Yeah the global toggle is not a perfect solution since it will only work in modes semantic supports but I don't see that as a major problem. If a mode does not support it and it is toggled on then the message `Buffer <buffer-name> was not set up for parsing.` is shown so people will probably know what the problem is.

If we limit this to certain major modes then there will be no way to use the `global-semantic-stickyfunc-mode` which would certainly be annoying if somebody does not like the feature.

Also with the way it is implemented at the moment in both the python and c++ layers it is activated also in e.g.  Java buffers since it is added to the `semantic-default-submodes` but this might be a different issue altoghether

**Pull request closed without merging**
