### PR TITLE
Better reporting

### PR DESCRIPTION
**Pull request by JAremko**
Move
 ```
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>
```
 instruction into overlay to make it more visible. Also it does not need to be removed by user.

- - - - - - - - -
Error in the branch name is a touch of style :shipit:

### CODE REVIEW

**Comment by duianto** [comment]
This sounds like a good improvement.

When i press `SPC h I` then the REPORT_SPACEMACS_ISSUE buffer appears, without the top line, but the overlay isn't visible. The buffer is in fundamental mode.

When i switch it to `spacemacs/report-issue-mode` manually from `M-x`, then the overlay appears.

**Comment by JAremko** [comment]
@duianto  thx!
That's probably because you don't have markdown mode. :thinking:

**Comment by duianto** [comment]
The markdown layer is installed in windows as well.
Copied from above:
```
(auto-completion autohotkey colors emacs-lisp git helm markdown
                 (org :variables org-agenda-files
                      '("c:/Users/Username/Documents/"))
                 version-control)
```

**Comment by duianto** [comment]
I just noticed that the messages buffer shows:
```
save-excursion: Search failed: "(%LAST_KEYS%)
```
This could be the issue, error probably occurs before the report-issue-mode command is called.

**Comment by JAremko** [comment]
@duianto Try now :+1:

**Comment by duianto** [comment]
With the markdown layer uncommented and commented:
Overlay [Check]
`^M` characters gone [Check]
Report-Issue mode [Check]
❤️ JAremko [Check] 😄 

PR is Okay to go! 👍

**Comment by JAremko** [comment]
@duianto  Thx for the help! :heart:

**Comment by duianto** [comment]
The key binding in the removed line is listed as: `` `C-c C-c` ``, but in the overlay as: `` `C-c` `C-c` ``.
The most common way I've seen it is without the middle backticks.

**Comment by JAremko** [comment]
@duianto Ok fixed  :smile:

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

Thanks @duianto also for the review. :-)

**Pull request closed without merging**
