### PR TITLE
Make NeoTree more "vim" friendly

### LINKED ISSUE #2783: `gg` doesn't work in NeoTree, other keybindings do.
This is for `develop`.

In the spacemacs documentation, it doesn't give you the keybindings for navigating to the top and bottom of the NeoTree buffer.   I tried to use vim keybindings, and while most of them work, there's one glaring exclusion.  

`S-g` works to go to the bottom of the file, but `gg` does nothing.  It should go to the top of the file.

### PR DESCRIPTION
**Pull request by synic**
This rebinds keys in NeoTree so that `g` and `G` work correctly.

Fixes #2783

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1:

**Comment by TheBB** [comment]
@justbur decided to use `gr` for refresh in the evil-magit implementation. What do you think of doing the same here, for consistency? You can leave `f` in, as well, if you like.

**Comment by synic** [comment]
@TheBB Done

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
