### PR TITLE
git: Add new evil-magit bindings

### PR DESCRIPTION
**Pull request by justbur**
Also turn off evilification for magit conditional on the evil-magit
package being used.

### CODE REVIEW

**Comment by justbur** [comment]
@a13ph @mbertheau

**Comment by syl20bnr** [comment]
Nice work :+1: 
Can we wait for this being available MELPA or is there anything holding it from being hosted there ?

**Comment by justbur** [comment]
I wanted to do it officially through the magit repo to get others to look
at it and critique it. I could obviously make my own package though. What
do you think?

**Comment by syl20bnr** [comment]
> I wanted to do it officially through the magit repo to get others to look at it and critique it.

Good point. As soon as it is merged (by me or @TheBB), we can open an issue to discuss about the proposal and reference the PR link.

**Comment by nixmaniack** [comment]
@justbur Amazing experience! Pretty evil! :smiling_imp:  :+1: Been using it for some time, feels home.

**Comment by CestDiego** [comment]
I can't wait for this to be merged. :)

**Comment by TheBB** [comment]
Is this magit 2.3 certified ® © ™?

**Comment by justbur** [comment]
@TheBB It looks to me like we were getting the 2.3 commits the whole time. In other words, it's only a significant upgrade for the stable users

**Comment by syl20bnr** [comment]
Thank you :+1:

**Comment by justbur** [comment]
Thank you @syl20bnr !

**Comment by CestDiego** [comment]
#itsHappening! :)

**Comment by PierreR** [comment]
For the record, the latest commit t 150e38e76c2 in develop has increased the loading startup time significantly. At least for me ;-)

**Comment by justbur** [comment]
@PierreR It's quelpa downloading the package. It should only happen once. As soon as this new package is on melpa we'll switch back. For the record, this is not the only quelpa package in use

**Comment by PierreR** [comment]
@justbur  well it was still happening after a couple of restarts. Maybe because there is a compilation error:

```
Compiling file /home/vagrant/.emacs.d/elpa/evil-magit-20151029.1713/evil-magit.el at Thu Oct 29 16:44:20 2015
evil-magit.el:146:1:Error: Cannot open load file: no such file or directory, magit
```

**Comment by justbur** [comment]
@PierreR do you have magit installed?

**Comment by PierreR** [comment]
@justbur I just enable the git layer (I was not aware of a `magit` layer ?)

**Comment by justbur** [comment]
@PierreR hm. It looks like quelpa is not handling the dependency correctly

**Comment by justbur** [comment]
@PierreR After spacemacs loads do `M-x package-install RET magit RET` as a workaround

**Comment by justbur** [comment]
then restart

**Comment by PierreR** [comment]
> After spacemacs loads do M-x package-install RET magit RET as a workaround
@justbur well I have a lot of magit-* package when I do that but no `magit` alone

**Comment by CestDiego** [comment]
I lost the ability to go up/down one line :( to have precise selection staging. is this expected?

**Comment by justbur** [comment]
@PierreR ok, then it seems it is installed but can't be found. Go into `.emacs.d/elpa` and look for a magit-[date] folder and a evil-magit-[date] folder. Delete both and restart. You might have a bad download of magit

**Comment by justbur** [comment]
@CestDiego magit uses `n` and `p` to navigate sections and `C-n` and `C-p` to navigate by line. Just swap `j` for `n` and `k` for `p` in those

**Comment by CestDiego** [comment]
`n` makes a search forward D:

**Comment by PierreR** [comment]
@justbur  Thanks. Your last tip fixes it ;-)

**Comment by justbur** [comment]
@CestDiego https://github.com/justbur/spacemacs/blob/evil-magit-doc/layers/%2Bsource-control/git/README.org#magit (not merged yet)

**Comment by justbur** [comment]
@PierreR :+1: I get an abnormal number of corrupted downloads from melpa. I have no idea why, but usually redownloading the package works

**Comment by CestDiego** [comment]
I thought updating would make this work.

**Comment by justbur** [comment]
>I thought updating would make this work.

Is that directed at me? What do you mean?

**Comment by justbur** [comment]
@CestDiego anyway use #3592 for comments on the bindings

**Comment by CestDiego** [comment]
@justbur I thought that updating spacemacs (given that this PR was merged) would make `n` and `p` work. And would not make `n` do `next-search`

**Comment by justbur** [comment]
@CestDiego please read the documentation I linked to which is merged by the way. j and k play the role of n and p. also see the pull request at magit/evil-magit

**Comment by CestDiego** [comment]
I misunderstood your comment and was confused by the link. Now I get it :) `C-j` and `C-k` are what moves one in lines :) amazing :) thanks

**Comment by CestDiego** [comment]
@justbur @syl20bnr I want to raise a big concern regading `j` `k` for chunks and `C-j` `C-k` for lines.

I want to explain why this is not a good translation directly from the Emacs keybindings:

In Emacs you move up and down lines with `C-p` and `C-n`, and that is unchanged in magit, additionally, in magit you use `p` and `n` to move up and down chunks... So basically the way you move lines is not changed.

In Evil, you move up and down with `k` and `j`, but in evil-magit you move up and down in lines with `C-k` and `C-j` which is very confusing , and more when you try to select lines and have to switch your mind from using `j|k` to move between lines to `C-j|C-k` ... I hope you guys can see my point and evaluate it while you also use the `region staging` features.

**Comment by justbur** [comment]
@CestDiego update your packages. this was already changed

**Comment by CestDiego** [comment]
@justbur I just updated, the behaviour is changed :) but when I try to select regions, I can't use `j` nor `k` only `C-n` and `C-p` is this expected?

**Comment by justbur** [comment]
@cestdiego no not expected. What's the context? What buffer?

**Comment by CestDiego** [comment]
@justbur the magit-status buffer....just trying to select regions to stage.

**Comment by justbur** [comment]
@cestdiego after hitting v or V?

**Comment by CestDiego** [comment]
any of those will say: `Mark Activated` and after pressing `j` it'll exit the

**Comment by justbur** [comment]
What does exit the mark mean?

**Comment by CestDiego** [comment]
woops, I meant exit the selection..and the marks dissappear.

**Comment by justbur** [comment]
I own the repo now. Just open an issue and I'll look into it.

**Comment by nixmaniack** [comment]
I can use `jk` when selecting regions to stage after hitting `v/V`. Does the evil-state matters? I'm using hybrid.

**Comment by justbur** [comment]
@nixmaniack right now no it shouldn't make any difference what editing style you use.

**Pull request merged**
