### PR TITLE
Loading warnings for using warning-minimum-level

### PR DESCRIPTION
**Pull request by syohex**
This is related to #3184 and #3187.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Why didn't any of us running on `develop` hit this error?

**Comment by syohex** [comment]
> Why didn't any of us running on develop hit this error?

#3184 issue is reproduced only Emacs 24.3. I cannot reproduce on Emacs 24.4 or higher.

**Comment by hujianxin** [comment]
@syohex So, I have to upgrade Emacs to 24.4?

**Comment by hujianxin** [comment]
@syohex By the way, you are a so productive developer, I'm your fan

**Comment by robbyoconnor** [comment]
We are dropping support for 24.3.

**Comment by syohex** [comment]
> So, I have to upgrade Emacs to 24.4?

I recommend you to upgrade Emacs 24.4 or higher if feasible. Some package like magit requires Emacs 24.4 or higher.

> By the way, you are a so productive developer, I'm your fan

Thanks.

**Comment by syl20bnr** [comment]
Thank you :+1: :+1: :+1: 
Released in 0.104.2 :-)

**Pull request merged**
