### PR TITLE
[mu4e] update to README.org

### PR DESCRIPTION
**Pull request by andreas-h**
Clarify usage for multiple accounts, as discussed by @darkfeline in #4670

### CODE REVIEW

**Comment by magthe** [comment]
I'm not really keeping track, but I'm guessing the `mu4e-contexts` stuff isn't in a release yet?

**Comment by nwolfe** [comment]
@andreas-h Oops, you should retarget this at the `develop` branch.

**Comment by darkfeline** [comment]
@magthe  I'm not keeping track either.  Looks like mu4e has this feature: http://www.djcbsoftware.nl/code/mu/mu4e/Dynamic-folders.html#Dynamic-folders

Unfortunately, for sending messages using multiple accounts, we need to stick to the current configuration, and personally I don't need to have separate trash folders for each account.

**Comment by robbyoconnor** [comment]
Thank you for your contribution. However, all PRs must be against `develop`. Please [review our contribution guidelines](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org).  This is against `master`.  Please close this, and open a new pull request against `develop`.

**Comment by magthe** [comment]
@darkfeline This is what I was referring to: <https://groups.google.com/d/msg/mu-discuss/BvUj3xFU7Ik/2Rlb7iZKCQAJ>

**Comment by darkfeline** [comment]
@magthe Thanks for the link, I definitely didn't know about that.  It looks like the feature isn't in a release yet, so once it comes out, we can consider using it.

**Comment by magthe** [comment]
@darkfeline ah, OK.  I can report it's a *very* nice feature.  I'm running *mu* from git, so not sure what's released yet or not ;)

**Comment by magthe** [comment]
@darkfeline 0.9.16 was released about 15 hours ago, and it includes `mu4e-contexts`.

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

I was able to apply this to develop, but in the future, @andreas-h, please target the correct branch as discussed.

**Comment by andreas-h** [comment]
Sure, will do that.  It was just a quick fix, so I used the 'edit'
function on the Github website.

Maybe you can configure Github such that Master cannot be edited via the
web?

**Comment by TheBB** [comment]
I think it's possible to set the default branch to something other than master, but then people will get that branch when they go to http://github.com/syl20bnr/spacemacs, which is maybe not ideal.

**Comment by robbyoconnor** [comment]
The quick fix would be for people to read the contribution guidelines BEFORE making a PR...you're linked to them.

**Comment by andreas-h** [comment]
Suppose a user sees a mistake in some document and wants to quickly let
you know. Maybe the user doesn't care too much, and maybe the user
doesn't really have the time at the moment, but Github has this nice
edit button. It's by far the most convenient path for the user who is
not regularly involved with your project to point you towards a place
where you can improve. If you choose not to care because the user didn't
read the guidelines before, that's your choice. But not a smart one IMO.

In this case I don't mind at all, especially since it seems that the
mu4e layer might change soon and this would make the configuration
described in the README obsolete anyways.

**Comment by StreakyCobra** [comment]
@andreas-h I'm not aware of a way to prevent people from editing files from the web interface. Setting `develop` as the default branch is not a good option for the reason @TheBB mentioned (i.e. changing the default cloning url, default branch displayed, etc.).

We care about people wanting to help and contribute, even if it is in a hurry or as a quick fix. A PR against `master` is better than a mistake not fixed. We are usually comprehensive and asking kindly people to open a new PR against `develop`, if they can. If they can't or for simple fixes without conflicts we can of course do like @TheBB did here, cherry-picking them into `develop`.

Our dear @robbyoconnor can be a little bit too… direct sometimes :wink: Don't take his words too literally :relaxed:

**Comment by andreas-h** [comment]
I agree with you guys that having |develop| as default is probably not a
good idea.

And just as some people can be too direct sometimes, I can be too
sensitive sometimes ;)  No offense taken!

Thanks for making Spacemacs -- it has finally enabled/motivated me to
move basically all of my everyday workflow (except for webbrowsing) into
Emacs -- yeay!

**Comment by robbyoconnor** [comment]
I have done everything I can..Github prominently links to contribution guidelines -- nobody seems to read them... the fact we have to even change the default branch is sad.

**Comment by andreas-h** [comment]
I do agree.  In my defense I can say that Github does *not* link to the
contribution guidelines at all when I use the "edit" button on a file
within Github.  At least not in a way which allowed me to notice it ;)

**Comment by robbyoconnor** [comment]
It does right before you open a pull request.

**Comment by Andre0991** [comment]
@andreas-h You're right, Github still make it impossible to customise basic things that would make managing projects so much easier (example: show guidelines when a user is opening a new issue.)

People even wrote [an open letter](https://github.com/dear-github/dear-github) very recently because Github's ha been stagnating in that aspect for years.

**Comment by robbyoconnor** [comment]
Yeah it's messed up...they don't seem to give a shit

**Comment by magthe** [comment]
Gitlab has answered on that open letter, some things are already in place ([blog post](https://about.gitlab.com/2016/01/15/making-gitlab-better-for-large-open-source-projects/)) and some are being addressed ([ticket 8938](https://gitlab.com/gitlab-org/gitlab-ce/issues/8938)).

Just letting you know ;)

**Pull request closed without merging**
