### PR TITLE
github layer: secure tokens, timeouts

### PR DESCRIPTION
**Pull request by nochiel**
Add:
- Information on storing API tokens securely. (This replaces the insecure advice that was provided with the layer.)
- Information about API timeouts and how to avoid them on slow connections.

### CODE REVIEW

**Comment by joehillen** [comment]
`magithub` was [recently disabled](https://github.com/syl20bnr/spacemacs/commit/655eec4ca46adb3263d9dc8a3b665f20a37f9463), so this PR is moot until it's enabled.

**Comment by nochiel** [comment]
> magithub was recently disabled, so this PR is moot until it's enabled.

Ha! It was literally disabled a day ago!  Thanks for the heads up.  I didn't see that commit.

**Comment by Miciah** [comment]
Magithub has since been re-enabled (https://github.com/syl20bnr/spacemacs/pull/9946), so this PR is no longer moot.

Note that upstream bumped the default timeout up to 3 (https://github.com/vermiculus/magithub/commit/aa4d96ab1607731be595ee86bce91a09ae5c2fd8; this PR still says it is 1).

**Comment by syl20bnr** [comment]
Is this PR still relevant ?

**Pull request closed without merging**
