### PR TITLE
Helm-mu integration.

### PR DESCRIPTION
**Pull request by numkem**
Also contains leader key changes for fitting with [helm-mu](https://github.com/emacs-helm/helm-mu) integration.

* `a M m` launches `mu4e`
* `a M c` launches `helm-mu-contacts` (searching for contacts to compose email to)
* `a M s` launches `helm-mu` (searching with helm)

### CODE REVIEW

**Comment by nixmaniack** [comment]
How about changing the default key for mail to `a m`? Current default is a bit difficult to reach. Just a suggestion as I already remap it!

**Comment by numkem** [comment]
@nixmaniack I remember seeing a discussion saying that `a m` already belongs to Spotify for music. I think it should be `a m` for mail clients as it makes more sens coming from a text editor.

**Comment by nixmaniack** [comment]
I see. Let's keep the discussion open for it then!

**Comment by StreakyCobra** [comment]
+1 `am` for mail and `aM` for music

**Comment by StreakyCobra** [comment]
Following the discussion in #4416, it doesn't seem to be any objection for the `SPC a [m/M]` swap, so it can be proposed. If you do it here, try at least keep 2 separated and documented commits.

**Comment by numkem** [comment]
Last commit changes all binding that used to be `a M` to `a m` so:

* `a m m` launches `mu4e`
* `a m c` launches `helm-mu-contacts` (searching for contacts to compose email to)
* `a m s` launches `helm-mu` (searching with helm)

**Comment by numkem** [comment]
Closing this as it's targeting `master` instead of `develop`.

Will open a new one.

**Pull request closed without merging**
