### PR TITLE
Disable evil-snipe in ranger

### LINKED ISSUE #5029: ranger-search-files does not work
#### Description
In default ranger `f` is bound to `ranger-search-files` while in ranger layer in Spacemacs this key is shadowed by the default evil-mode behaviour of `f` key. I suggest using different key binding for `ranger-search-files`.

#### Reproduction guide
- Start Emacs
- Be sure to use `vim` editing mode
- Be sure ranger layer is loaded
- Open ranger with `SPC a r`
- Press `f`

*Observed behaviour:*
I observe Emacs is waiting for the next letter, because `f<X>` puts the cursor on the next occurrence of the letter <X>.

*Expected behaviour:*
I expect it brings `ranger-search-files` as it is the default ranger behaviour.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: nil (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t)
 better-defaults emacs-lisp javascript clojure haskell python lua c-c++ html shell-scripts ess sql go scala java react git markdown org restclient selectric erc dockerfile latex
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 evil-commentary spell-checking syntax-checking version-control ranger semicolon org-latex-classes org-psamim psamim-defaults)
```

### PR DESCRIPTION
**Pull request by TheBB**
Fix #5029, possibly supersedes #5030.

CC @StreakyCobra @ralesi @psamim

### CODE REVIEW

**Comment by StreakyCobra** [comment]
I prefer this over #5030

**Comment by psamim** [comment]
It is a better solution.

**Comment by ralesi** [comment]
This works,  but is there a way we can just set up either:
- an alist of modes in evilsnipe to not apply the hook
- bind the evilsnipe commands directly to evil-motion-state-map so they don't interfere with keys applied on evil. 

 I believe this is going to come up for any mode that is using evil-motion-state

**Comment by TheBB** [comment]
I merged it as an initial solution. We can write something more elegant later.

**Pull request closed without merging**
