### PR TITLE
Append eshell-switch-company-frontend in eshell-mode-hook

### PR DESCRIPTION
**Pull request by benjamreynolds**
Fixes bug when opening eshell before using company-mode

See #7720

### CODE REVIEW

**Comment by benjamreynolds** [comment]
Thanks for the review @bmag! 

I reverted previous changes in 55b7a72 and went with the alternate fix in 5d96654. You can probably just cherry-pick that commit, but let me know if there is any git-fu you want me to do on this branch.

**Comment by bmag** [comment]
It's fine, I just cherry-picked the last commit (will push to develop tomorrow probably)

**Comment by bmag** [comment]
Thank you :+1: Cherry-picked into develop, you can safely delete your branch.

**Comment by robbyoconnor** [comment]
This is hilarious -- it triggered travis CI's Abuse detection

**Pull request closed without merging**
