### PR TITLE
Switch off `spacemacs-purpose` if not enabled from .spacemacs

### PR DESCRIPTION
**Pull request by bixuanzju**
The README says to enable it, add `spacemacs-purpose` to the dotfile.

### CODE REVIEW

**Comment by nixmaniack** [comment]
I think the layer README was not updated when the `purpose` layer was made part of Spacemacs experience. So the documentation should be changed and not the other way around :).

**Comment by bixuanzju** [comment]
Personally I don't like purpose. If this is part of Spacemacs, then at least let me know how to disable it.

**Comment by nixmaniack** [comment]
Unaware of the clean way to disable full layer which are part of the spacemacs distribution. But `dotspacemacs-excluded-packages '(window-purpose)` comes to my mind as an easy fix. The hard way would be to go with `spacemacs-core` and build up from there.

**Comment by bmag** [comment]
> I think the layer README was not updated when the `purpose` layer was made part of Spacemacs experience. So the documentation should be changed and not the other way around :).

Indeed.

**Comment by bmag** [comment]
I'm closing this one, but feel free to submit a PR fixing the documentation.

**Comment by bixuanzju** [comment]
@nixmaniack Well I need to also exclude `helm-purpose` among other packages used by `spacemacs-purpose`. That's not satisfactory.  Maybe we could provide, like `dotspacemacs-excluded-packages`, something like `dotspacemacs-excluded-layer`.

**Comment by bixuanzju** [comment]
ok, found a way, at least feel regain the control. use `spacemacs-base`, then add layers I want.

**Comment by nixmaniack** [comment]
> That's not satisfactory. Maybe we could provide, like `dotspacemacs-excluded-packages`, something like `dotspacemacs-excluded-layer`

I can totally understand and agree.

**Pull request closed without merging**
