### PR TITLE
Add asm-layer

### PR DESCRIPTION
**Pull request by tuhdo**

### CODE REVIEW

**Comment by tuhdo** [comment]
Here is how it looks:

asm-layer-demo

**Comment by robbyoconnor** [comment]
:+1:

**Comment by ikhthiandor** [comment]
:heart:

**Comment by syl20bnr** [comment]
Very nice layer, great job :+1: 
Thank you!
I tweaked it in commit https://github.com/syl20bnr/spacemacs/commit/408e710
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by c0r3d3v** [comment]
error when pressing ':' in nasm-mode after adding this layer
backtrace:
```lisp
Debugger entered--Lisp error: (wrong-type-argument characterp nil)
  string(nil)
  (member (string (char-after)) (quote (" " "	")))
  (if (member (string (char-after)) (quote (" " "	"))) (progn (setq asm-colon-has-space t)))
  asm-colon-check-space()
  apply(asm-colon-check-space nil)
  #[128 "\300\301\"\210\300\302\"\207" [apply asm-colon-check-space #[nil "\301\212\302\303!\210\302\304!\210n\211\203\305 \210)\306\307!\210\205\"\305 \210\310 )\207" [labelp nil skip-syntax-backward "w_" " " delete-horizontal-space call-interactively self-insert-command tab-to-tab-stop] 2 ("/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/share/emacs/24.5/lisp/progmodes/asm-mode.elc" . 6281) nil] nil] 4 nil nil]()
  apply(#[128 "\300\301\"\210\300\302\"\207" [apply asm-colon-check-space #[nil "\301\212\302\303!\210\302\304!\210n\211\203\305 \210)\306\307!\210\205\"\305 \210\310 )\207" [labelp nil skip-syntax-backward "w_" " " delete-horizontal-space call-interactively self-insert-command tab-to-tab-stop] 2 ("/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/share/emacs/24.5/lisp/progmodes/asm-mode.elc" . 6281) nil] nil] 4 nil nil] nil)
  asm-colon()
  call-interactively(asm-colon nil nil)
  command-execute(asm-colon)
```

**Pull request closed without merging**
