### PR TITLE
space-doc-mode and centered-buffer-mode improvements

### PR DESCRIPTION
**Pull request by JAremko**
As promised in #6916

### CODE REVIEW

**Comment by JAremko** [comment]
It will be incremental PR.

**Comment by JAremko** [comment]
### TODO

- [x]  Disabled by default centering in space-doc-mode.
- [x] 	Recenter buffer when content width increase.
- [ ] 	Disable space-doc if org-mode disabled (replaced with another major mode).
- [ ] 	Use test properties instead of overlays.
- [ ] 	*BONUS:*  Restore previous layout  after `SPC w C` `SPC w C`

**Comment by JAremko** [comment]
@TheBB  :shipit:

**Comment by JAremko** [comment]
@TheBB  ok I think we need to merge it asap so the changes will be battle-tested before the next release.

*It might be the last major rework.* :fireworks:

**Comment by syl20bnr** [comment]
Thank you ! 👍 
I bet that

> Remove [WIP]

was the hardest of all! :-)

I noticed an issue with winner-undo, the fringe color is not reset. So I guess we should do the BONUS to be sure to correctly toggle the mode.

Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
