### PR TITLE
Add reddit layer

### PR DESCRIPTION
**Pull request by BenediktBroich**
This layer adds Reddit support to Spacemacs via the package reddigg. This package allows you to browse reddit in org-mode. You can find more information in the README.org.

### CODE REVIEW

**Comment by lebensterben** [comment]
Pinging the package author.
@thanhvg 
What do you think of this PR?

**Comment by thanhvg** [comment]
Very happy that my package can be added to Spacemacs. But this layer can add another reddit package:  https://github.com/ahungry/md4rd and have a variable to use reddigg or md4rd. 

I don't know what to do about it but our keybindings for prefix `spc a` are ridiculously too long. They look well organized but good luck invoking them.

**Comment by BenediktBroich** [comment]
I tried md4rd but the package is currently broken (https://github.com/ahungry/md4rd/issues/32). I will add this package when it is working again.

**Comment by BenediktBroich** [comment]
I think the shortcut `SPC a r r` would also fit instead of `SPC a w r`.
Hacker News could be `SPC a r h` or `SPC a w h`.
Lobsters could be `SPC a r l` or `SPC a w l`.

**Comment by lebensterben** [comment]
Changing keybinding for `SPC a` prefix is daunting. It may easily conflict with other packages.

**Review by lebensterben — APPROVED** [review]
LGTM

**Comment by smile13241324** [comment]
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

**Pull request closed without merging**
