### PR TITLE
Add clipboard layer to integrate with clipboard managers.

### PR DESCRIPTION
**Pull request by xuhdev**
Also, I'm wondering whether we should move contents from `xclipboard` layer to this layer, so we can have a "clipboard enhancement" layer.

### CODE REVIEW

**Comment by sdwolfz** [comment]
I'm not sure this layer should exist by itself given that the configuration is minimal and only works with ivy. But it might make sense to live with the rest of the clipboard code although I would prefer it be behind a feature flag and disabled by default.

**Comment by xuhdev** [comment]
@sdwolfz OK. Are you suggesting merging this layer and `xclipboard`, and name the merged layer as `clipboard`?

**Comment by xuhdev** [comment]
And why disabled by default?

**Comment by xuhdev** [comment]
Close in favor of #12510

**Comment by sdwolfz** [comment]
Hello @xuhdev , sorry for not replying for so long, I lost track of this PR. I'm glad you and @duianto managed to sort this thing out ❤️.

**Pull request closed without merging**
