### PR TITLE
add note about setting up $PATH

### PR DESCRIPTION
**Pull request by d12frosted**
It's pretty common problem. So I decided to create a separate 'how to' for setting up `$PATH`.

### CODE REVIEW

**Comment by StreakyCobra** [comment]
:+1: Really nice

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Comment by TheBB** [comment]
I made some changes in https://github.com/syl20bnr/spacemacs/commit/16e7ad29231208bca1bca7dc399cc80b31122d4e.

**Comment by d12frosted** [comment]
Thanks for the fixes! :smile:

**Pull request closed without merging**
