### PR TITLE
add support for material-light theme

### PR DESCRIPTION
**Pull request by cpaulik**

### CODE REVIEW

**Comment by sooheon** [comment]
Not objecting, but just for discussion, how do we differentiate what goes in core themes and in themes megapack?

**Comment by cpaulik** [comment]
This is just so that spacemacs does not look for a 'material-light-theme' package on MELPA.

Theme loading in spacemacs is a little strange now because there is the 'themes-megapack' and then there is this list in 'core'.

I'm not sure if it is such a good idea to automatically [look for a package](https://github.com/syl20bnr/spacemacs/blob/master/core/core-themes-support.el#L181-L186) if the theme is not in the list but I guess @syl20bnr has his reasons.

**Comment by syl20bnr** [comment]
themes-megapack actually installs a bunch of packages available to browse. The alist in core is for being able to use any theme in `dotspacemacs-themes` without needing to install them explicitly in the first place which is convenient and even mandatory to support te case where someone install Spacemacs with a dotfile using a not yet installed theme.

**Comment by syl20bnr** [comment]
Very nice light version of your theme :+1: 

Thank you !
Cherry-picked into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
