### PR TITLE
add org2blog

### PR DESCRIPTION
**Pull request by choppsv1**
Add org2blog org wordpress integration layer

### CODE REVIEW

**Comment by robbyoconnor** [comment]
why so wordpress-centric?!

**Comment by choppsv1** [comment]
robbyoconnor <notifications@github.com> writes:
> why so wordpress-centric?!

Its an org to wordpress package. I guess you'll have to ask the author of
the package for a better answer. :)

I did place org2blog under +blog parent in case there were other
packages out there (or in the future).

Thanks,
Chris.

**Comment by robbyoconnor** [comment]
eh, just curious is all.

**Comment by a13ph** [comment]
@robbyoconnor @choppsv1 there are other org blogging packages, a LOT of them

**Comment by d12frosted** [comment]
> a LOT of them

indeed, and also it's easy to use org-publish for such task :/ so one can create a layer with some helpers for configuring your org-blog export process :)

**Comment by choppsv1** [comment]
Feel free to add things under the +blog directory, that's why I put it there.

**Comment by robbyoconnor** [comment]
I love you all

--Rob

**Comment by maikol-solis** [comment]
What happened with this package? Someone could be kind and merge this to the develop branch to test it?

**Pull request closed without merging**
