### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by benwbooth**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Your commit msg should be a lil clearer -- `git commit --amend` 

When looking at the commit history...I have no idea what the hell your commit did...Be descriptive...

**Comment by CestDiego** [comment]
@syl20bnr this typo somehow doesn't break spacemacs xD

**Comment by robbyoconnor** [comment]
I've yet to hit this

**Comment by TheBB** [comment]
@CestDiego The variable `pkg-name` is only used for the error message in case a recipe is not found.

**Comment by syl20bnr** [comment]
@TheBB ahah I was wondering why it did not break anything, thanks for the answer :-)
@benwbooth Thank you! Excellent catch :+1: 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
