### PR TITLE
Add "o" keybinding for opening links with ace-jump

### PR DESCRIPTION
**Pull request by nixmaniack**
There might be better way of using `avy` for doing this but since we're already using `elfeed-goodies` I just added it to evilified bindings.

### CODE REVIEW

**Comment by fandag** [comment]
Going slightly off on a tangent, I've been a happy user of [link-hint](https://github.com/noctuid/link-hint.el) the last couple of weeks. It's quite similar to ace-link, except it provides one command to handle all (or at least, many) link types. I.e. I can use the same short cut to open links, no matter if its elfeed, org links, mu4e, http, etc. I appreciate the simplicity, but of course you loose on the fine grained control in jumping to specific link types... I bind it to `spc o l`, but I guess it would fit nicely into `spc x o` or `spc j U` (but it is not only jumping, also opening).

**Comment by StreakyCobra** [comment]
@fandag Looks like a good alternative for `SPC x o` indeed. I'll have a look at it, thx.

**Comment by nixmaniack** [comment]
Cool. We can definitely think of using it across. Although from a quick look it looks like it uses avy in the backend, how much different it is from ace-link then?

**Comment by StreakyCobra** [comment]
@nixmaniack I don't know if you are speaking about `SPC x o`, but if yes the current implementation uses a regex to search `https?://` links, so having a package that handle all kind of links in one entry function would be far better :-)

PS: Your question is answered [here](https://github.com/noctuid/link-hint.el#similar) ;-)

**Comment by nixmaniack** [comment]
@StreakyCobra Thanks for the link. That sounds promising. One function to cover all link types. Nice! I'll try that out.

**Comment by StreakyCobra** [comment]
@nixmaniack Do you still want this change now that #4863 has been merged?

**Comment by nixmaniack** [comment]
Not needed anymore! Thanks for adding link-hint. @StreakyCobra

**Comment by nixmaniack** [comment]
OTOH, I would like to keep the consistent binding of `o` across such buffers if possible. @StreakyCobra

**Comment by StreakyCobra** [comment]
I don't have any problem with adding `o` in elfeed, it was just a question :-)

**Comment by nixmaniack** [comment]
Let's add `o` then. :-)

**Comment by StreakyCobra** [comment]
It needs a rebase by the way ;-)

**Comment by nixmaniack** [comment]
@StreakyCobra Rebased.

**Comment by StreakyCobra** [comment]
Thank you :+1: Cherry-picked into `develop`, you can safely delete your branch.

**Pull request closed without merging**
