### PR TITLE
Core compiler warnings

### PR DESCRIPTION
**Pull request by justbur**
After seeing #4199, I compiled the core files to see what else popped up for compiler warnings. I started fixing some of them but there's a bunch. 

If anyone wants to add to this pr I can give access to this branch. @TheBB ?

### CODE REVIEW

**Comment by justbur** [comment]
Just making a note here of two variables that seem misplaced. 

`update-packages-alist` https://github.com/syl20bnr/spacemacs/blob/develop/core/core-configuration-layer.el#L1056
`recipes-var` https://github.com/syl20bnr/spacemacs/blob/develop/core/core-configuration-layer.el#L760

**Comment by justbur** [comment]
Also @syl20bnr you might consider using `defmethod` in core-configuration-layer to define some of the functions as methods on the classes you have here. Not sure if it's worth the effort though

**Comment by syl20bnr** [comment]
Initially Spacemacs was not meant to be byte-compiled but now we have a pretty good way to recompile on save elisp files so compiled configuration can be relevant. It can be a pretty big task and may involve some tricky cases inherent to Spacemacs design which has never take byte-compilation into account. I don't expect big performance improvement though.

**Comment by syl20bnr** [comment]
@justbur to answer your last post, either we use `defmethod` everywhere to make Spacemacs byte-compiled friendly, either we don't do it at all.

**Comment by justbur** [comment]
@syl20bnr Sorry I think you might have misunderstood. I'm not saying we should byte compile spacemacs. I'm just using the compiler to catch possible errors in the code. 

The `defmethod` thing was just for functions that are called on objects like `cfgl-layer` (I don't think this is necessary though)

**Comment by justbur** [comment]
For example, see https://github.com/syl20bnr/spacemacs/pull/4203#issuecomment-165189437 for possible errors. The uses of these variables do not seem to be right.

**Comment by syl20bnr** [comment]
You have to explain in more details because I don't know a lot of things about byte-compilation.
Do you mean that dynamically created methods by `eieio` should be `defmethodified` ?  The mentioned variables are from `package.el`, do we need to declare them with `defvar` ?
I'm open for any change if it is not just adding code just to please the compiler, or we make byte-compilation a feature of Spacemacs :-)

**Comment by justbur** [comment]
@syl20bnr Most of the commits here are fixing free variable warnings and function usage warnings that came out of compiling the code

One minor part of this exercise is that I see a bunch of warnings of the form 
```
core-configuration-layer.el:345:25:Warning: Unknown slot ‘:name’
```
in the configuration layer. These are mostly `oref`s on the objects in that layer. I was looking to see if there was a way to prevent these and make the functions more type safe, but I think you should just ignore these actually. I don't want to overcomplicate things.

**Comment by justbur** [comment]
> The mentioned variables are from package.el, do we need to declare them with defvar ?

@syl20bnr  I can't find `recipes-var` anywhere. I see where `update-packages-alist` is coming from now. I can defvar that one with an explanation of what it is.

**Comment by syl20bnr** [comment]
Nice, seems that even me forget what `update-packages-alist` was all about.. :-)
Thank you again :+1: 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
