### PR TITLE
haskell: Fix command name

### PR DESCRIPTION
**Pull request by lunaryorn**
Changed in https://github.com/chrisdone/hindent/commit/323cb55391f8d58da31fad6c9960d522330577c0

### CODE REVIEW

**Comment by syl20bnr** [comment]
Thank you :+1: 
Cherry-picked into develop branch, you can safely delete your branch.

Keep this issue opened to check if it needs to be cherry-picked into master.

**Comment by lunaryorn** [comment]
@syl20bnr Oh, sorry, I didn't mean to close this one.  I was cleaning up branches in my Spacemacs fork, and Github apparently closes PRs when the corresponding branch is deleted.  Sorry :cry:

**Comment by lunaryorn** [comment]
I've restored the branch and re-opened this issue.

**Comment by syl20bnr** [comment]
Backported in 0.104.7.

**Pull request closed without merging**
