### PR TITLE
Add region state

### PR DESCRIPTION
**Pull request by StreakyCobra**
There is two commits:
- One correct the sorting in the packages list of `spacemacs` distribution (I was on it and syl20bnr is preparing some merge so I post it there, can be cherry-picked alone)
- The other one add region-state package in the `spacemacs` distribution:

region-state

### CODE REVIEW

**Comment by syl20bnr** [comment]
Spaceline already displays this informatio ;-)

**Comment by StreakyCobra** [comment]
The number of lines yes, not the number of chars. But indeed, in may be redundant for a not so wide usage.

**Comment by syl20bnr** [comment]
The number of chars can be added.
One advantage of this package is that it is always visible, the mode-line segment may be invisible. OTOH we could move the segment to the left.

**Comment by StreakyCobra** [comment]
It's up to you, both are fine for me.

**Comment by StreakyCobra** [comment]
From @TheBB on gitter:

> I don't mind moving it out of the modeline actually.
Segments that don't show still cost in terms of performance. And the modeline updates quite frequently, and spaceline is already not so fast.
May need to optimize a bit.

**Comment by syl20bnr** [comment]
Ok let's remove it from spaceline and use this package instead

**Comment by StreakyCobra** [comment]
Updated to remove the spaceline segment.

I just noticed that the message in the echo area is overridden sometimes, like by the function definition under the cursor in elisp files, so… the current situation is maybe better. I let you decide on this, close the PR if we keep the current way.

**Comment by TheBB** [comment]
Since spaceline does this and is faster now, I think it's safe to close this PR. Thanks!

**Pull request closed without merging**
