### PR TITLE
Fixes ansible-doc-mode error on `SPC h d k`

### PR DESCRIPTION
**Pull request by sdwolf**
I saw this being done for `org-mode` and implemented it here as well.

Refs #8027.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
The reason it is done with `org-mode` is that there is a bundled version of `org-mode` which is ancient - so we want to be sure which version of org-mode we're using.

**Comment by robbyoconnor** [comment]
cc: @syl20bnr @TheBB

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Comment by sdwolfz** [comment]
Apparently this fix was not enough, I'm now having this problem again... Looks like if I move the keybinding definition in `:config` everything works. 

Will submit a patch soon.

**Comment by sdwolfz** [comment]
Pushed a3debe157032fc0999044eeb060d1e83107c87ee as a fix.

**Comment by syl20bnr** [comment]
:+1: moving them in `:config` was a better solution.

**Pull request closed without merging**
