### PR TITLE
Partition spacemacs layer into finer categories

### PR DESCRIPTION
**Pull request by justbur**
Re: #2937

This will allow people using spacemacs-base to have finer control over
what additional packages they install on top of base.

The proposed split is as follows

spacemacs-editing-packages:
 - aggressive-indent
 - avy
 - bracketed-paste
 - clean-aindent-mode
 - eval-sexp-fu
 - expand-region
 - hexl
 - hungry-delete
 - iedit
 - lorem-ipsum
 - move-text
 - neotree
 - pcre2el
 - smartparens

spacemacs-editing-visual-packages:
 - adaptive-wrap
 - auto-highlight-symbol
 - highlight-indentation
 - highlight-numbers
 - highlight-parentheses
 - hl-anything
 - indent-guide
 - linum-relative
 - rainbow-delimiters
 - volatile-highlights

spacemacs-evil-packages:
 - evil-anzu
 - evil-args
 - evil-exchange
 - evil-iedit-state
 - evil-indent-plus
 - evil-jumper
 - evil-lisp-state
 - evil-mc
 - evil-nerd-commenter
 - evil-matchit
 - evil-numbers
 - evil-search-highlight-persist
 - evil-terminal-cursor-changer
 - evil-tutor
 - evil-unimpaired

spacemacs-language-packages:
 - define-word
 - google-translate

spacemacs-ui-packages:
 - ace-link
 - ace-window
 - buffer-move
 - centered-cursor
 - desktop
 - doc-view
 - flx-ido
 - info+
 - open-junk-file
 - window-numbering

spacemacs-ui-visual-packages:
 - fancy-battery
 - golden-ratio
 - leuven-theme
 - neotree
 - smooth-scrolling
 - spaceline
 - vi-tilde-fringe
 - zoom-frm

### CODE REVIEW

**Comment by Andre0991** [comment]
Cool, Spacemacs is getting even more modular.

Isn't `doc-view` builtin in Emacs?

**Comment by StreakyCobra** [comment]
<3

**Comment by robbyoconnor** [comment]
:heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart:

**Comment by syl20bnr** [comment]
Excellent :purple_heart: 
I did not check the split for now, if it is needed we can move packages later.
I did not cherry-pick the second commit because it would break the dynamic switch of style, we will be able to remove it when the lazy install system allows it.
For people wondering why I merge this PR so quickly and not theirs, this is because it moves a lot of code, so the sooner it is merged the better. I will merge PRs tomorrow :-)

Thank you :+1:

**Comment by syl20bnr** [comment]
@StreakyCobra nice new label ;-)

**Comment by justbur** [comment]
@syl20bnr that's fine but I wasn't excluding evil for hybrid users just the additional evil related packages.

**Comment by AdrieanKhisbe** [comment]
@syl20bnr Shall we use a `cherry-pick` label to distinguish the closed PR that has been _cherry-merged_, from the one that were denied or _abandonned_? :smiley: 

(and :fireworks: to you @justbur :clap: :grinning: )

**Pull request closed without merging**
