### PR TITLE
Spacemacs as an package

### PR DESCRIPTION
**Pull request by declanqian**
Use spacemacs as an package.  

https://www.reddit.com/r/emacs/comments/47y2eg/use_spacemacs_as_an_elisp_package/

It will not effect the other lisp code.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Why?

**Comment by syl20bnr** [comment]
While I like the idea we won't support it officially because of the management overhead it will induce by requiring more tests and creating new issues.

If people wants to use this clever hack then they can use quelpa as shown in the reddit post.

**Comment by declanqian** [comment]
@robbyoconnor For fun? Anyway ignore this. Another way of doing thing ha.

**Comment by declanqian** [comment]
@syl20bnr Ok, I am closing this.

**Pull request closed without merging**
