### PR TITLE
Feature startup lists

### LINKED ISSUE #807: Idea: better start experience ala vim-startify
I thought this was a great idea: https://github.com/mhinz/vim-startify

I've been using it in `vim` for a week or so now and generally my feeling has been that it helps provide better context on boot. Its helpful to "continue from where you left off" or get a sense for "what you've been doing lately".

I think spacemacs could take this a lot further but I just wanted to reference it as an example to get the discussion going.

At this point I can only contribute the suggestion, maybe I can help implement this or other things in the future.

### PR DESCRIPTION
**Pull request by CarlQLange**
Closes #807: Displays lists of recent files, projects, and bookmarks at startup in the *spacemacs* buffer. Each item is a button, so you can go straight to it. If you don't have recent files, projects, or bookmarks, they won't show up.

### CODE REVIEW

**Comment by trishume** [comment]
This looks cool! :+1:

**Comment by syl20bnr** [comment]
Excellent ! :+1: :+1: :+1: 
Thank you !
Cherry-picked and squashed in `develop` branch, you can safely delete your branch.

See commit f42b686f4c8330a6b50337f91cb6b563bcda9148 for minor changes and tweaks.

**Comment by person808** [comment]
@syl20bnr I think it would look better if the `[x packages loaded in 2.2s]` message was above the recent files and had some kind of seperator under it.

**Comment by person808** [comment]
Like this:

```
Found 1 orphan package(s) to delete...
--> deleting adaptive-wrap... [1/1]
[226 packages loaded in 2.663s]
------------------------------------------------
Recent Files:
    ....

Projects:
    ...
```

**Comment by syl20bnr** [comment]
Indeed, see commit f5713f8d443756d9ee1fbd7794371045041742a7
Thank you for the suggestion :-)

**Comment by CarlQLange** [comment]
Awesome!! Thanks @syl20bnr!

**Pull request closed without merging**
