### PR TITLE
[WIP] Fixes #3242 - Add SPARQL-mode to +lang/extra-langs layer

### LINKED ISSUE #3242: Add a SPARQL mode
There is currently no extended support for SPARQL. Although it's use it's far from massive it would be nice to add support at least for highlighting.
I think that this should be done on `extra-langs` until a new Query Language Layer is created grouping support for SQL, SPARQL and other NoSQL modes (Neo4j, MongoDB, CouchDB, ArangoDB (AQL), OrientDB, ...)
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.104.2
- Spacemacs branch: nil (rev. 074f425)
- Distribution: spacemacs
- Layers:

``` elisp
(auto-completion syntax-checking c-c++ clojure d emacs-lisp haskell html javascript latex markdown python ruby rust scala sql colors
                 (git :variables git-enable-github-support t git-gutter-use-fringe t)
                 version-control gtags org
                 (shell :variables shell-default-width 120 shell-default-height 30 shell-default-position 'right shell-default-term-shell "/bin/zsh"))
```

### PR DESCRIPTION
**Pull request by Dietr1ch**
#3242 Grabs the `*.sparql` extension

### CODE REVIEW

**Comment by Dietr1ch** [comment]
Company completion is not yet working ootb :c

**Comment by robbyoconnor** [comment]
Add the [WIP] tag to the beginning of your title ;)

**Comment by d12frosted** [comment]
@Dietr1ch any progress on this?

**Comment by Dietr1ch** [comment]
I haven't got the time to work on it :c

**Comment by syl20bnr** [comment]
Thank you !
You repo is gone but I was able to reconstruct your contribution.
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
