### PR TITLE
Actually download `nyan-mode' from MELPA.

### PR DESCRIPTION
**Pull request by jjzmajic**
Why was this set to `:location local` in the first place? I know it's a useless
feature, it just bugged me.

### CODE REVIEW

**Comment by sdwolfz** [comment]
I think there was an incompatibility that required a fork until the changes were upstreamed, don't know it's status though.

**Comment by jjzmajic** [comment]
@sdwolfz I see. It worked when I tested it just now though

**Comment by robbyoconnor** [comment]
See discussion here: https://github.com/syl20bnr/spacemacs/pull/9689

**Comment by robbyoconnor** [comment]
Your PR fails to remove the local package as well. So this is woefully incomplete.

**Comment by smile13241324** [comment]
I have just compared the version on melpa with the fork from @syl20bnr and noticed that the changes done for the spacemacs specific version are not included in the version on melpa.

I am not sure if providing a PR to upstream would help. I have checked the project pulse of [https://github.com/TeMPOraL/nyan-mode/pulse/monthly](the original repo) and there had been no commit since over a month.

**Comment by robbyoconnor** [comment]
See the discussion on my closed PR.

**Comment by robbyoconnor** [comment]
See this comment from @syl20bnr https://github.com/syl20bnr/spacemacs/pull/9689#issuecomment-336713331: 

> Is this in the MELPA repo ?
> 
> -** Fork modifications
> -- the starting nyan cat image has no rainbow behind it,
> -- the starting rainbow image has zigzags,
> -- the animation loop is not endless and occurs only when nyan cat moves.

**Comment by jjzmajic** [comment]
Should I close this then? Or do you guys think we should should try to solve this upstream again?

**Comment by robbyoconnor** [comment]
@jjzmajic I would close this

**Pull request closed without merging**
