### PR TITLE
An attempt at a perl5 layer using cperl, perlnow, and template.

### PR DESCRIPTION
**Pull request by abelew**
Thank you for contributing to Spacemacs!

Before you submit this pull request, please ensure it is against the develop branch and not master.

This message should be replaced with a description of your change.

Thank you <3

### CODE REVIEW

**Comment by bmag** [comment]
Thanks for the PR, but please submit it against develop branch. I haven't looked too deeply, but adding `template.el` and its templates like this might not be the best way.

**Comment by bmag** [comment]
Also, you should write something in the PR's description...

**Comment by abelew** [comment]
Greetings,
  I am sorry for the doofus move by making a PR not against develop.  I
believe I fixed that.  I also cleaned up the autoloads somewhat and have
it working properly for (at least my own) HTML::Mason and bioperl code
-- which makes me happy as that was always a bit of a pain to have
working properly.

  Thank you for your time,
atb

**Comment by syl20bnr** [comment]
Closing in favor of #8572 which is against develop.

**Pull request closed without merging**
