### PR TITLE
Move Rust to own layer

### PR DESCRIPTION
**Pull request by mkaito**

### CODE REVIEW

**Comment by trishume** [comment]
:+1:

**Comment by Tyler-Anderson** [comment]
moving rust to it's own layer is a good idea

**Comment by jupl** [comment]
TOML should be in extra lang as it is not exclusive to Rust. https://github.com/toml-lang/toml#projects-using-toml

**Comment by caspark** [comment]
+1. Once Rust has its own layer, we can add cargo (build), flycheck and rust racer (autocomplete) integration for a better out of the box config.

I've got those integrations working already in my Rust layer - in fact, I was about to open a PR for it when I saw this one - so I'll contribute them once this PR is merged.

**Comment by syl20bnr** [comment]
Excellent :+1: 
Thank you 1
Cherry-picked in `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
