### PR TITLE
add org-enable-company-mode configuration variable

### PR DESCRIPTION
**Pull request by d12frosted**

### CODE REVIEW

**Comment by d12frosted** [comment]
Ah sorry, aa1b556 is not related to this PR. Only 4fa69a8.

**Comment by CestDiego** [comment]
Why set it to nil by default though?

**Comment by d12frosted** [comment]
Well, I don't care about default. I just want to have an option to turn it off. 

I want it off for two reasons:
- I don't get why I would like to have company mode enabled in org mode (it just distracts me very much, but I still need it in some of prog modes. 
- It doesn't look well in GUI emacs when your theme sets different line height for different headers.

**Comment by robbyoconnor** [comment]
@d12frosted, remember you're not the only person...some want it :P For me personally...it doesn't bug me.

**Comment by CestDiego** [comment]
@d12frosted you are right about that.. it looks ugly with different line-heights... Also I feel the backends are not good enough..there should be backends only for dictionary words...not function names? I mean if you are editing source blocks and *need* completion just `C-c '` and you are done.

**Comment by d12frosted** [comment]
@robbyoconnor Well, I am not against company mode in org. 

> Well, I don't care about default. I just want to have an option to turn it off.

**Comment by CestDiego** [comment]
would it be a valid guess that if people enable auto-completion layer they want auto-completion everywhere? And expect it to work. So we don't get people that are like "How do I enable completion in org? ERC? RCIRC?" Maybe it would best be to have the default to true and specify it in the Layer Doc, Or better, the Spacemacs doc, that if they don't want company in certain layer they have a variable to tune? @syl20bnr would that make sense? given that we don't a single company backend for everything.

**Comment by d12frosted** [comment]
> Would it be a valid guess that if people enable auto-completion layer they want auto-completion everywhere?

I wouldn't say that. Even not in all prog modes. Because not all of them has good backend. Anyway, I am really good with having it enabled by default. I just want to have an option to disable it. I know that I can do something like `(remove-hook 'org-mode-hook 'company-mode)`, but in my opinion from user's perspective it looks like a hack. Plus you need to be sure that it's ok to remove that. Having configuration variable is nice because it tells to user - it's intended that this behaviour can be changed to suite your needs.

**Comment by TheBB** [comment]
> Anyway, I am really good with having it enabled by default. I just want to have an option to disable it.

That's how I feel, too, and that was my idea with #2810.

**Comment by syl20bnr** [comment]
The issue with opt-in is that it introduce double opt-in which can be annoying too. Using the syntax-checking layer is already an opt-in so the natural things to do is to provide the possibility of selectively opt-out for the same functionality.

TBH I'm a bit worried about this layer variables, I don't see them as a good thing and I fear that it will introduce more confusion than providing convenience. Ill try to explain, stay with me :-)
I want a `:disabled-for` property for the layer like this:

```elisp
   dotspacemacs-configuration-layers
   '(
     (auto-completion :disabled-for '(org git))
     better-defaults
     c-c++
     csharp
     eyebrowse
     git
     org
     syntax-checking
     )
```

`:disabled-for` will prevent the `pre-init`, `init` and `post-init` from being run, effectively removing the `auto-completion` feature for the listed layers.
I like this solution because it stays *at the layer level* and does not bleed into the package world. When you think about it, good layer variables are variables configuring a behavior at the layer level, variables too closed to the package level are bad layer variables. Which make me get to the PR #2810 and this PR, to me those variables are bad variables.

If you don't want to `:disable-for` org a given layer and just deactivate the layer feature by default then we should instruct the users how to do so in plain Emacs lisp and let the user going deeper into the package level to fine tune her configuration. Here it is a matter of a one liner `(remove-hook....)` which is a basic Emacs Lisp feature.

**Comment by justbur** [comment]
I agree that the layer level is the correct way to think about enabling auto complete, but if I had my way I would make auto completion more of a built in library available to all layers. The standard way to enable auto completion for a language would be something like

```elisp
(org :enable-completion) 
```

The auto completion "layer" would not have to be declared. It would be implicitly declared if one of the layers used it. Could do something similar for flycheck.

**Comment by syl20bnr** [comment]
Very interesting proposition, I like it a lot! But it does not solve the issue addressed by this PR because even with your proposal we need a way to enable globally  a layer (which is the current way).

I like the idea to add another way to enable a layer via a scoped keyword like your proposal though. The keyword symbol would be build like this `:enable-<layer>`. I think I could have something working pretty quick, maybe :-)

Anyway in the case where the user enable the layer globally, we still have to propose a way to not hook a  particular package by default. I stated my feeling on this, to me it is a matter of user configuration `dotspacemacs/config` with `remove-hook`.

**Comment by syl20bnr** [comment]
(Sorry in advanced for hi-jacking the issue)
After reflexion I think `:disabled-for` is the less confusing although it goes against my preferences (I prefer to declare what is _used_ instead of what is not), I made an exception here and here is the reason: there is no guarantee that `auto-completion` is configured in the org layer, so it would be confusing for the user to declare `(org :enable-auto-completion)` and then note that it does not work. By starting from the principle that a declared layer L is implicitly enabled "globally", `:disabled-for` has the same effect when another layer M do or do not configure the packages for L. Of course the user will notice that M has feature provided by L but that's less confusing to me because it is implicit, there is no explicit expression in the dotfile sayng that it should be otherwise.

So, for the issue of this PR I would like to hear if you are OK with letting fine tunning of package configurations to the user (especially when it is trivial like here). Moreover for the particular cases of flycheck and some others `disabled-for` has the same effect than a `remove-hook`, I know that it is not the case for `org` but do you think that someone willing to not have company in `org` would enable it temporarily ? I think that `:disabled-for` would fit the bill in most cases, even if it totally disabled the feature.

**Comment by syl20bnr** [comment]
BTW I implemented `:disabled-for`.

**Comment by CestDiego** [comment]
How should we use it then? it feels a little like black magic :( Do people create their own layers and reconfigure org or sth?

**Comment by person808** [comment]
@syl20bnr Couldn't we do stuff like enabling `global-flycheck-mode

**Comment by syl20bnr** [comment]
@person808 if there is something I don't want to do is to break the layer isolation with `global-flycheck-mode`. For a package to be used by layer it has to be declared explicitly in `packages.el`, this is a core principle of Spacemacs. By looking at the packages.el you can see everything the layer configure. There are exceptions currently like Yasnippet etc... they should be declared like flycheck, company etc...
I know that it breaks the beautiful design of Yasnippet and company which are designed to be fire and forget packages that are enabled globally and auto-configure themselves depending on the context, I believe that this kind of design - although being very convenient for personal configuration - is not suited for a mega community driven set of package configuration like Spacemacs because they break isolation, the package becomes the boss of what happens instead of the distribution, could be perfectly OK but I have decision to make to make things consistent and hold well together.

**Comment by syl20bnr** [comment]
> How should we use it then? it feels a little like black magic :( Do people create their own layers and reconfigure org or sth?

If you want to disable `auto-completion` layer for say... org :-)

```
(setq dotspacemacs-configuration-layers
'((auto-completion :disabled-for (org))))
```

**Comment by CestDiego** [comment]
that makes so much sense.. thanks

**Comment by CestDiego** [comment]
So it really is user defined. So we are on the responsibility of defining company for *everything* ? D:

**Comment by syl20bnr** [comment]
For company to be enabled in a layer, company must be declared explicitly in `packages.el`. Moreover we leverage this to be able to cherry-pick the backends for each buffer, instead of having one big list of backends that auto-elect them depending on the context.

**Comment by syl20bnr** [comment]
These are tradeoff that violates the DRY principle and goes against the design of famous packages but I do feel that this the good way to go in order to sustain a stable mega distribution.

**Comment by robbyoconnor** [comment]
https://github.com/syl20bnr/spacemacs/commit/88d30d7074e00d82d6d773cc240b8f6afd2f59dd

**Comment by d12frosted** [comment]
@syl20bnr Thank you for such detailed comments. I like the idea of `:disabled-for` property. It's actually what I want to do and it looks natural. And also it allows to decrease amount of custom customisation variables (which I agree - good point). 

About `remove-hook`. I think you greatly described what I don't like about it. It is too close to package level. So yeah, I agree with you.

---

> After reflexion I think `:disabled-for` is the less confusing although it goes against my preferences (I prefer to declare what is used instead of what is not), I made an exception here.

I do also prefer declaring what is used instead of what is not. But as you say, it makes more sense in this case. The only thing I don't like about following snipped is that configurations is messed a bit.

```
dotspacemacs-configuration-layers
   '(
     (auto-completion :disabled-for '(org git))
     better-defaults
     c-c++
     csharp
     eyebrowse
     git
     org
     syntax-checking
     )
```

I would prefer to disable `auto-completion` layer in following manner (mirroring @justbur's proposal). 

```
dotspacemacs-configuration-layers
   '(
     auto-completion
     better-defaults
     c-c++
     csharp
     eyebrowse
     (git :disable-auto-completion)
     (org :disable-auto-completion)
     syntax-checking
     )
```

But I am ok with either way. 

> So, for the issue of this PR I would like to hear if you are OK with letting fine tunning of package configuration to the user (especially when it is trivial like here). 

I am not sure that I understand you here :smile: But anyway I am really OK with either of your decisions. Moreover, you are working towards consistency which is really nice. 

> Moreover for the particular cases of flycheck and some others, disabled-for has the same effect than a remove-hook, I know that it is not the case for company but do you think that someone willing to not have company in org would enable it temporarily?

Hard to say what people would do. But in case of `org` mode I don't think people would want to enable it temporarily. 

> BTW I implemented `:disabled-for`.

Haha, fast. I'll give it a try! Thank you!

**Comment by d12frosted** [comment]
@syl20bnr Doesn't seem to work for me. I pulled your changes and tried to `(auto-completion :disabled-for (org))`, but it didn't work for me. It still loads up `company-mode`.

**Comment by syl20bnr** [comment]
@d12frosted oops sorry, this is the drawback of TDD, I actually forgot to read the new property :-)
Fixed in commit https://github.com/syl20bnr/spacemacs/commit/8adc82d

**Comment by d12frosted** [comment]
@syl20bnr Thank you! It solves my problem indeed. But I found another problem - when I open org file by passing it's path to emacs when starting emacs - `auto-completion` layer is not disabled. I mean, when I open org file in terminal using

```
$ emacs path/to/file.org
```

Emacs runs and loads that file, but `company-mode` is enabled. If I alternate file - everything is fine. But it's not that critical. Just FYI.

**Comment by syl20bnr** [comment]
That's strange, I don't see why such behavior would happen. Did you have an old emacs server running or something ?

**Comment by d12frosted** [comment]
Sorry for delayed answer. Just tried restarting my computer and running terminal and `emacs /path/to/file.org` as a first action. Still the same. I don't have any daemons running emacs server on startup. Even checked list of processes, but didn't find emacs there. So yeah, that's strange.

**Comment by TheBB** [comment]
I see the same behaviour, actually. It's puzzling. Maybe you can open a new issue about it.

**Comment by d12frosted** [comment]
@TheBB done

**Pull request closed without merging**
