### PR TITLE
Add Spacemacs docker distribution

### PR DESCRIPTION
**Pull request by JAremko**
[README.org](https://github.com/JAremko/spacemacs-pr/blob/spacemacs-docker/layers/%2Bdistributions/spacemacs-docker/README.org)

## TODO
- [x] Added @TheBB @syl20bnr @bmag @d12frosted to the companion repositories[[1](https://github.com/JAremko/docker-emacs)],[[2](https://github.com/JAremko/spacemacs-docker-seed)] as requested by @syl20bnr 
- [x] Create [Spacemacs organization](https://hub.docker.com/u/spacemacs/) -by @syl20bnr 
- [x] Merge this PR
- [x] Create `spacemacs/spacemacs-docker:latest` automated build from merged `/layers/+distributions/spacemacs-docker/dockerfiles/spacemacs-docker/Dockerfile` and link it to `jare/spacemacs-docker` DockerHub repository.
- [x]  Create `spacemacs/onbuild:latest` automated build from merged `https://github.com/JAremko/spacemacs-pr/blob/spacemacs-docker/layers/%2Bdistributions/spacemacs-docker/dockerfiles/onbuild/Dockerfile` link it to `spacemacs/spacemacs-docker` DockerHub repository and disable the auto-build in the `Build Settings` - this way it will build in the right order.   -- *probably wait before the first build of `spacemacs/spacemacs-docker:latest` is finished(magic)*
- [ ] Collect bug reports and fix them. Add more docs and examples.

This is heavily expanded version of my https://github.com/JAremko/spacemacs Docker Image that some people (including me) actually use :smile:  
**I used this new extended version to write itself and so far it works fine.**

### CODE REVIEW

**Comment by JAremko** [comment]
Squash and rebase with reordering commits at 6 am
*fingers are so crossed...* :cold_sweat:

**Comment by TheBB** [comment]
Eep!

**Comment by syl20bnr** [comment]
I created the automated build in the spacemacs docker hub organization, I hope everything is fine this is my first time using docker hub.

If the automated builds are OK then we can close this PR and open an issue to track the bugs/work for spacemacs-docker distribution.

**Comment by robbyoconnor** [comment]
Oh wow -- this exists -- saw this come in when I pulled in changes

**Comment by robbyoconnor** [comment]
@JAremko, FYI avoid excessively switching users like that -- use [gosu](https://github.com/tianon/gosu)

**Comment by JAremko** [comment]
@robbyoconnor  We switch the user only once and with USER - not sudo. Boot scripts have sudo in them and it seems irrelevant in this case. But any improvements are welcome :stuck_out_tongue:

**Comment by JAremko** [comment]
No actualy we use sudo in two places.  But they are in Elisp wrappers so the output will be filtered.  I'll think about  gosu. Thx.

**Comment by robbyoconnor** [comment]
Just a suggestion

**Comment by JAremko** [comment]
https://github.com/JAremko/docker-emacs/issues/2

**Comment by JAremko** [comment]
I'll change quite a few thing and make another PR.  I think Now I know how to get it right :wink:

**Pull request closed without merging**
