### PR TITLE
README: fix macOS prerequisites regarding grep

### PR DESCRIPTION
**Pull request by thvnx**
The --with-default-names option seems to no longer exist. A directory have to be added to PATH instead.

### CODE REVIEW

**Review by lebensterben — APPROVED** [review]

**Comment by lebensterben** [comment]
Great. We should recommend users to install grep's faster replacement as well.

**Comment by thvnx** [comment]
> Great. We should recommend users to install grep's faster replacement as well.

Thanks. I think I don't know it, what are you talking about?

**Comment by lebensterben** [comment]
> > Great. We should recommend users to install grep's faster replacement as well.
> 
> 
> 
> Thanks. I think I don't know it, what are you talking about?

rg ag ack

**Comment by thvnx** [comment]
OK thanks ;)

**Pull request merged**
