### PR TITLE
[WIP] add org agenda to home screen

### PR DESCRIPTION
**Pull request by tonyday567**
I find the startup screen with projects, bookmarks and recentf as a really useful one-stop shop for navigating my way around (and heading to when lost which is often). I felt it was missing the org agenda so I hacked up some functions to append a todo list and a simple agenda.
It would be great to get some comment on whether this would be useful to others and, if so, where development should head.

### CODE REVIEW

**Comment by TheBB** [comment]
This is a cool feature. I see there are some theming issues in the screenshot. Any chance we could take care of those?

The other thing I'm wondering is if this really needs to be a layer. We already have a dotspacemacs variable for choosing what to show in the home buffer, and one of those (projects) forces the loading of a package (projectile) that wouldn't otherwise be loaded so soon. So it's not unprecedented to put something like this in core, even if there is a lot of code...

**Comment by d12frosted** [comment]
Indeed cool feature, can't wait to see it in develop. :+1:

**Comment by elemakil** [comment]
Very cool feature :+1: One though though: It might be nice to provide some core `spacemacs` functionality that allows creation of new _startup screen widgets_. We already have `dotspacemacs-startup-lists` which allows to configure which core _widgets_ shall be shown, it would be nice if this list were extensible thus allowing layers to provide their own functionality for the startup screen.

**Comment by StreakyCobra** [comment]
> It might be nice to provide some core spacemacs functionality that allows creation of new startup screen widgets.

I totally agree with this :relaxed:

**Comment by tonyday567** [comment]
@TheBB Thanks.  Can you expand on the themeing issues a bit?  The todo list and the agenda list look exactly the same as their org-mode cousins.  I'm sure there are themeing issues but it just might be a glitch in my personal setup.  That 2 space indent in the lists isn't a 2 space indent but the result of org-agenda mode calculii hard-coded in the guts of org-agenda.  In other words, I couldn't get it to line up with the indent in other widgets.
A widget method for the home screen would be awesome.  The org lists don't refresh on changes, so I was going to look at how to add refresh to the home screen as a next step, and I can see that a home-screen-is-refreshing-widgety hook being offered to non-core layers would make this work.

**Comment by ralesi** [comment]
I agree that this makes more sense in core than to try to force this to work like a layer.   Unless,  as mentioned,  we were able to make an API to work with the buffer with 3rd party packages.   

In terms of the layout or theming, coud we perhaps just parse the org agenda buffers as ordered lists and hotlink the lists so that if an item is clicked we will go to that section of the buffer.   In that way you will get a more seamless feel with the rest of the buffer.

**Comment by tonyday567** [comment]
@ralesi thanks
> this makes more sense in core than to try to force this to work like a layer.
Will have to think about this.  Org isn't in core and I don't think it should be.  If I recall the load order, the widgets dont actually load till after the layer config, so instantiating org only after the org layer configs should work (with a enable check flag as is done for the other widgets).
> could we perhaps just parse the org agenda buffers as ordered lists and hotlink the lists
It's definitely a trade-off between theming and functionality - org theming and functionality is inseparable.  On reflection I think theming wins, and that a simple spacemacs-todo/agenda is the nicest approach.  It was a cool hack to get the whole of the org-agenda bindings hooked in, but it was an ugly hack - I just ripped out lines from the underlying org code until it worked. Developing that hack into something that can be maintained would involve going upstream and generating enthusiasm for an org-agenda widget approach compared with their buffer-centric method - a long hard road.
I don't think I can get around having to load all the agenda buffers but, and I'm sure this little widget adds significantly to load time.

**Comment by d12frosted** [comment]
Just tried this layer and it seems to break some org functions. For example, archiving is not working and `tab` in tables.

**Comment by tonyday567** [comment]
@d12frosted should work ok now.  Was firing up the built-in org due to a bare require.

**Comment by d12frosted** [comment]
Nice, thanks for the update. As for that problem I reported previously - it's not the case anymore.

Some feedback:

1. This layer really lacks ability to automatically insert agenda and/or todo. Right now I would better use regular org agenda. But I like the idea of having agenda and todo list in the home buffer (and overall idea of widgets), because it's better when you don't have to do anything in order to see important stuff. So I hope we'll manage this problem.
2. It would be nice to have ability to press return and jump to item. Right now it shows error about home buffer being read only. At least in terminal.
3. Insertion function is a bit clumsy. Calling `SPC a o T` twice inserts todo twice. Which is not nice. First time it inserts it right after Agenda block without any empty line delimiter. After that it inserts todo block after another todo block with 2 empty lines as delimiter. Calling agenda for the second time inserts empty agenda block. Ideally this should be fixed by implementing widgets functionality (we just need to keep in mind that we want to update widgets in some circumstances).

**Comment by tonyday567** [comment]
Ok, ditched the separate layer and moved everything into spacemacs-core-buffer, refactored as close as I could to the other widgets.  You just have to add `todos` to dotspacemacs-startup-lists.  Just a todo list for now to prove concept.  I haven't changed tests or anything like that yet.

**Comment by tonyday567** [comment]
Last commit was a squash.

**Comment by d12frosted** [comment]
Ya, it's nice! And good to have `d` and `c` key bindings! I will use it now more to see how it plays. Thanks for the update!

**Comment by d12frosted** [comment]
Already have one request. In agenda it would be nice to have time included in item. For example, I have a meeting from 11:00AM till 11:30AM. And would like to see it in home buffer. 

E. g., instead of

```
    ~/path/to/file.org - Meeting
```

I would like to see

```
    ~/path/to/file - 11:00-11:30 - Meeting
```

Just as example.

**Comment by tonyday567** [comment]
I've never used times with org - happy to get within a month of a deadline.

Does this work for you?

**Comment by CestDiego** [comment]
Is there an image for this?

**Comment by tonyday567** [comment]
home-screen

**Comment by d12frosted** [comment]
It's nice. Thanks for the update. Just what I wanted :)

**Comment by ralesi** [comment]
:+1: this looks awesome!

**Comment by CestDiego** [comment]
@tonyday567 is this still a WIP?

**Comment by tonyday567** [comment]
No. Good to go! (from my perspective).

The only issue I thought of was whether we should put this in the org-layer rather than core spacemacs, but to do that requires a lot of refactoring.

**Comment by CestDiego** [comment]
@syl20bnr  might be able to help with this.

**Comment by tonyday567** [comment]
Needs a rebase, and update for some tests, which I can do soon. On my setup, it works independently of whether the org layer is enabled.

**Comment by StreakyCobra** [comment]
@tonyday567 If it is ready you can remove the `[WIP]` then :-)

**Comment by tonyday567** [comment]
Oops, sorry about that.  I have never been able to squash remote commits without stuffing up.  I created a new PR at #4483

**Pull request closed without merging**
