### PR TITLE
Add ox pandoc

### PR DESCRIPTION
**Pull request by jcf**
Having to open this again as GitHub closed my previous PR when I removed a branch in my repo. See #2285.

---

[`ox-pandoc`][] adds support for exporting Org mode files via Pandoc.

I wanted to make the dependency optional in the same way `ox-gfm` is, so copied the general approach. I've verified `ox-pandoc` is only enabled with `org-enable-pandoc-support` is non-nil, but would appreciate feedback if this could be better implemented.

With Pandoc we can export Org mode files to the following formats:

| Format            | Extension | Buffer | File |
|-------------------|-----------|--------|------|
| asciidoc          | txt       | t      | t    |
| beamer            | tex       | t      | t    |
| beamer-pdf        | pdf       | nil    | t    |
| commonmark        | md        | t      | t    |
| context           | tex       | t      | t    |
| docbook           | xml       | t      | t    |
| docx              |           | nil    | t    |
| dzslides          | html      | t      | t    |
| epub              |           | nil    | t    |
| epub3             | epub      | nil    | t    |
| fb2               | fb2       | t      | t    |
| html              |           | t      | t    |
| html5             | html      | t      | t    |
| icml              |           | t      | t    |
| json              |           | t      | t    |
| latex             | tex       | t      | t    |
| latex-pdf         | pdf       | nil    | t    |
| man               |           | t      | t    |
| markdown          | md        | t      | t    |
| markdown_github   | md        | t      | t    |
| markdown_mmd      | md        | t      | t    |
| markdown_phpextra | md        | t      | t    |
| markdown_strict   | md        | t      | t    |
| mediawiki         |           | t      | t    |
| native            | hs        | t      | t    |
| odt               |           | nil    | t    |
| opendocument      | xml       | t      | t    |
| opml              |           | t      | t    |
| org               |           | t      | t    |
| plain             | txt       | t      | t    |
| revealjs          | html      | t      | t    |
| rst               |           | t      | t    |
| rtf               |           | t      | t    |
| s5                | html      | t      | t    |
| slideous          | html      | t      | t    |
| slidy             | html      | t      | t    |
| texinfo           | texi      | t      | t    |
| textile           |           | t      | t    |

[`ox-pandoc`]: https://github.com/kawabata/ox-pandoc

### CODE REVIEW

**Comment by jcf** [comment]
Good shout on updating the README, @cpaulik.. I've written something that hopefully explains what's going on. Thanks for the feedback!

**Comment by jcf** [comment]
Oh, I'll squash the commits down if we finish reviewing and decide to merge. :smile:

**Comment by robbyoconnor** [comment]
Why not squash now...and just amend the commit message ;) do `git commit --amend` and then `git push  origin add-ox-pandoc -f`

**Comment by jcf** [comment]
@robbyoconnor my preference based on my experience of using GitHub flow for quite a few years now is to address feedback in individual commits, only squashing/rebasing at the point we're happy to merge.

If I were to amend the commit and force push you can't see how the patch has evolved over time. I personally value that information, and have found it makes it infinitely easier for others who want to participate in the review process after it has started.

**Comment by robbyoconnor** [comment]
You can't rebase with github -- you have to learn how to use the git CLI.  When you push to your branch, it will update here...and show one commit instead of 2. People don't actually care how the patch evolved...your commit msg and the initial comment on the PR will tell us that.

**Comment by jcf** [comment]
> You can't rebase with github -- you have to learn how to use the git CLI. When you push to your branch, it will update here...and show one commit instead of 2.

I've been using Git for years, and I'm extremely comfortable with its CLI. In fact, I'd confidently describe myself as an expert so I don't need any tips on how to rebase, amend commits or manage branches, but thanks for offering.

> People don't actually care how the patch evolved...your commit msg and the initial comment on the PR will tell us that.

This is very much your opinion, which you're entitled to. I'll squash the commits down when the review is complete.

**Comment by syl20bnr** [comment]
@robbyoconnor there is no need to tell people to rebase/change commit message/open the PR against develop instead of master etc... The reason is simple: it does not matter, what matters is the content of the PR, for the form Git is flexible enough to allow me to squash, cherry-pick and amend commits.
While these steps are listed in the CONTRIBUTE.org file, *they are not mandatory*, so I ask you to stop commenting about these topics on the PRs. Thank you ;-)

**Comment by robbyoconnor** [comment]
:+1:

**Comment by robbyoconnor** [comment]
Apologies to both @syl20bnr  and @jcf

**Comment by syl20bnr** [comment]
Thank you for the PR !
I moved it to the pandoc layer so it is automatically installed when the pandoc layer is used which makes sense to me. See commits https://github.com/syl20bnr/spacemacs/commit/a1dace9 and https://github.com/syl20bnr/spacemacs/commit/d66a285
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
