### PR TITLE
replace custom ivy hydra-menu by original hydra-menu

### PR DESCRIPTION
**Pull request by dalanicolai**
Replaced the custom ivy hydra menu with the original (and updated) ivy hydra menu. Additionally checked parts of the documentation that required modification and applied them accordingly (no modifications were needed, only some additions)

### CODE REVIEW

**Comment by nixmaniack** [comment]
👍 For this change, my only gripe is the missing `s-M-SPC`–an alternate for `M-SPC`–according the [convention](https://github.com/syl20bnr/spacemacs/blob/cb48ec74c1f401bd2945760799633c0e81e69088/doc/CONVENTIONS.org#transient-state). We should, ideally, add them.

**Comment by smile13241324** [comment]
Thank you for contributing to spacemacs :purple_heart:, I have squashed and cherry picked your commits into develop.

@dalanicolai next time please take care that your PR has only one commit. To do so either force push on your PR branch or make single commits and squash them in the end.

**Comment by dalanicolai** [comment]
Yeah I am learning git... and sometimes some things happen that I do not understand yet... anyway I will check things again and next time think about the squash

**Comment by j-martin** [comment]
I suspect this PR broke the completion if not using the `ivy` layer. https://github.com/syl20bnr/spacemacs/issues/13395

**Pull request closed without merging**
