### PR TITLE
git: Add binding to magit-reset-popup

### PR DESCRIPTION
**Pull request by magthe**
Signed-off-by: Magnus Therning <magnus@therning.org>

### CODE REVIEW

**Comment by StreakyCobra** [comment]
> [ALWAYS document your new keybindings or keybindings changes inside the relevant documentation file. It should be the layer’s README.org file for layer’s keybindings, or DOCUMENTATION.org for general Spacemacs key bindings.](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org#contributing-a-keybinding)

:wink:

**Comment by magthe** [comment]
Done!

**Comment by robbyoconnor** [comment]
:+1:

**Comment by joehillen** [comment]
@robbyoconnor Use the new github [reaction button](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments).

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Comment by magthe** [comment]
Brilliant!

**Comment by JAremko** [comment]
Awesome! I need it badly. Fat fingers.. :wink:

**Pull request closed without merging**
