### PR TITLE
Bind mbb to sbt-command in scala layer

### PR DESCRIPTION
**Pull request by lunaryorn**
Provides a shortcut to run arbitrary SBT commands from scala mode
buffers

### CODE REVIEW

**Comment by syl20bnr** [comment]
Thank you!
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by lunaryorn** [comment]
@syl20bnr Thanks for merging so fast :)  Just being curious, I noticed that you're closing all of your PRs with pretty much the same “Cherry-picked into …” message.  I presume you have some kind of automation for this task:  May I ask what you're using?  I'd like to have such a tool for Flycheck as well :)

**Comment by syl20bnr** [comment]
@lunaryorn I don't have any automation for this but this is something I definitely need to automate.
For now here is how I proceed:
1. Fetch all the PRs with `magit-gh-pulls`
2. Cherry-pick or merge a PR (95% of the time it is cherry-picking), make modifications/fixes like typos if needed (I often do this myself instead of asking to the contributor to do it in the review).
3. Sometimes squash some commits if it makes sense.
4. Push upstream.
5. Manually go to the PR thread and write a thank you and relevant info about the PR.

`5.` could be automated in the majority of the PRs. Actually it could be done for all the PRs and then I could just add useful info in a new comment.

This workflow is pretty heavy on my side but it has the benefit to not bother the contributors more than needed and it keep the history simple. Since it is heavy I usually batch the cherry-picking which is fine for now because we are only two to merge PRs. Obviously this workflow does not scale and lacks some atomicity.

**Comment by lunaryorn** [comment]
That's an interesting workflow.  I'm do not particularly like cherry-picking, but I guess that'd work with branches too.  Haven't used magit-gh-pulls so far, I just pressed the Merge button :joy:

**Comment by lunaryorn** [comment]
@syl20bnr Just tried your workflow on a Flycheck PR.  I've a really bad conscience for cherry-picking, but other than that it's really convenient.  Magic GH Pulls is really nice.

**Pull request closed without merging**
