### PR TITLE
highlight current layout and workspace in transient state

### PR DESCRIPTION
**Pull request by nixmaniack**
Not sure about the right face but this looks decent I think!

screenshot 2016-03-03 14 01 07

### CODE REVIEW

**Comment by fbergroth** [comment]
The `(when current ...)` checks are  not needed because of the parent `(if current ...)`. Maybe the brackets are not needed at all if we highlight it:
```
(if current
    (propertize caption 'face 'highlight)
  caption)
```

**Comment by nixmaniack** [comment]
> The `(when current ...)` checks are not needed because of the parent `(if current ...)`

Right. I'll make the changes.

> Maybe the brackets are not needed at all if we highlight it

I'm not so sure about removing brackets and I leave the decision on syl20bnr. There might be users who don't like colors(or are colorblind) hence we should probably keep it.

**Comment by fbergroth** [comment]
> There might be users who don't like colors(or are colorblind) hence we should probably keep it. 

Good point!

**Comment by TheBB** [comment]
Thanks. I was going to do this myself. Can you do the same for the workspaces transient state?

**Comment by nixmaniack** [comment]
@TheBB Done!

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

I found the warning face in Monokai to be disappointingly non-obvious. :-(

**Comment by nixmaniack** [comment]
@TheBB I hear you. It's not obvious in Monokai. I think spacemacs should define custom faces here for providing more granularity in configuring faces. It would easier to override using theming then.

**Pull request closed without merging**
