### PR TITLE
Fix `SPC u` not repeating universal-argument

### PR DESCRIPTION
**Pull request by luxbock**
- Addresses #371

### CODE REVIEW

**Comment by luxbock** [comment]
This might not be super robust as modifies the `universal-argument-map`, which would affect its behavior outside of `evil` as well, though I did add a check to only create the binding when `dotspacemacs-editing-style` is set to `'vim`.

**Comment by TheBB** [comment]
Nice! Probably want this also for the hybrid editing style.

**Comment by luxbock** [comment]
I don't really know how the hybrid-style works. Does adding it to the `dotspacemacs-editing-style` `eq` check work?

**Comment by TheBB** [comment]
Should be fine

`(when (memq dotspacemacs-editing-style '(vim hybrid)) ...)`

**Comment by luxbock** [comment]
Cool, fixed it.

**Comment by syl20bnr** [comment]
That's great ! :+1: 
I did not find a function to test with though, can you give me one ?

Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by luxbock** [comment]
The simplest test I can think of is simply doing `SPC u SPC u SPC u i` which will repeat the string inserted 64 times instead of 4 as it would do before.

**Pull request closed without merging**
