### PR TITLE
Update CHANGELOG.develop

### PR DESCRIPTION
**Pull request by yqu212**
I forgot to update CHANGELOG.develop in #12594 to reflect the change. Sorry.

### CODE REVIEW

**Comment by duianto** [comment]
A changelog.develop entry was added to the commit when your PR was cherry picked: https://github.com/syl20bnr/spacemacs/commit/53a0dd85bf001a1a364dd99a22de34b1a58a1fa8

But your correct that it should be in the `Dotfile changes` section, I'll move it there.

**Comment by yqu212** [comment]
@duianto Please use my full name. Thank you.

**Comment by duianto** [comment]
We use the full name from the commits `From:` field, which can be viewed on the second line here:
https://patch-diff.githubusercontent.com/raw/syl20bnr/spacemacs/pull/12596.patch

If you update your gitconfig to show your full name then we won't make the same mistake again.

**Comment by duianto** [comment]
There are two places where it can be set:
- Globally in the `.gitconfig` file in your home directory.
- Locally in the `CONFIG` file in a repositories `.git` directory.

**Comment by yqu212** [comment]
It's my fault. I have set my full name in the repository.

**Pull request closed without merging**
