### PR TITLE
keyboard-layout: Fixes #15249

### LINKED ISSUE #15249: Keybinding issues when using dvp keyboard layout with org layer.
#### Description :octocat:
When using `dvp` layout with `keyboard-layout` in conjunction with the `org` layer, `d` will be bound to `'evil-org-delete` instead of `'evil-backward-char` in org-mode buffers.

#### Reproduction guide :beetle:
- Configure `keyboard-layer` as shown in "Layers" system info.
- Start Emacs
- Open any org file
- Try using `d` to navigate backwards.

*Observed behaviour:* :eyes: :broken_heart:
Instead of moving the point, `'evil-org-delete` is executed.

*Expected behaviour:* :heart: :smile:
The point moves backward by one character.

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a843146f1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((keyboard-layout :variables kl-layout 'dvp)
 emacs-lisp helm multiple-cursors org treemacs)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER GMP

### PR DESCRIPTION
**Pull request by lebensterben**
Replaced d and h in evil-org-mode
fixes #15249

### CODE REVIEW

**Comment by lebensterben** [comment]
@nilswloka
Please verify whether this solves the issue.
I'm not able to test since I'm not using a dvp keyboard.

**Comment by nilswloka** [comment]
Hello @lebensterben,
thanks for looking into this. Unfortunately, it seems that even on your branch, `evil-org-mode` minor mode still overwrites the binding for `d` with `evil-org-delete`. Since I'm new to spacemacs: I assume all I have to do to verify is pulling and checking out your branch, then restarting Emacs, correct?
Kind regards,
Nils

**Comment by nilswloka** [comment]
I think I figured it out (though I don't exactly understand *why* it's behaving the way it behaves). I will prepare my own PR with a fix once I've read the contributing guidelines and set up my environment. In the meantime, this is what works:

```
    :dvp
    (progn
      (spacemacs|use-package-add-hook evil-org
        :post-config
        (progn
          (evil-define-key 'normal 'evil-org-mode 
            (kbd "d") 'evil-backward-char
            (kbd "j") 'evil-org-delete))))
```

Thanks for pointing me into the right direction with your PR 🙇‍♂️

**Comment by lebensterben** [comment]
@nilswloka thanks.
I can also adapt your code in the PR and make you an co-author, if you agreed.

**Comment by nilswloka** [comment]
Sure, absolutely fine with that, too! Thanks again.

**Comment by lebensterben** [comment]
@nilswloka 
Please retry.

**Comment by nilswloka** [comment]
Almost good, I'd say. Binding delete to `h` will not work, though, as `h` is a navigation key in `dvp` layout, too. Following the pattern for that particular layout, I would probably go for `j` as default.

**Comment by lebensterben** [comment]
@nilswloka 
Is it good now? If so I will merge it.

**Review by smile13241324 — APPROVED** [review]

**Comment by lebensterben** [comment]
Merging now.
Let me know if it's not working as expected.

**Pull request merged**
