### PR TITLE
Add lsp backend support for Dockerfile

### PR DESCRIPTION
**Pull request by sei40kr**
# Description

Add lsp backend support for Dockerfile.

https://github.com/syl20bnr/spacemacs/pull/11320

### CODE REVIEW

**Comment by nixmaniack** [comment]
Do you have any reasoning why this needs to be a separate layer? 

IMO having a separate layer just for `Dockerfile` doesn't make much sense when the functionality could be part of the `docker` layer.

**Comment by sdwolfz** [comment]
I agree with @nixmaniack, Dockerfiles have no meaning without docker so they should be bundled together.

**Comment by sei40kr** [comment]
@nixmaniack @sdwolfz 
I've updated the PR!

**Comment by sei40kr** [comment]
@nixmaniack @smile13241324 
Thank you for your kind review. I updated the PR, please review again.

**Comment by smile13241324** [comment]
Thank you for contributing to spacemacs :purple_heart:, I have cherry picked your PR into develop.

**Pull request closed without merging**
