### PR TITLE
Add xkcd-layer

### PR DESCRIPTION
**Pull request by CestDiego**
xkcd greatness

### CODE REVIEW

**Comment by t3chnoboy** [comment]
DAMMIT, EMACS (－‸ლ)

**Comment by CestDiego** [comment]
You love it :P

**Comment by nashamri** [comment]
:+1:

**Comment by mijoharas** [comment]
:+1:

**Comment by syl20bnr** [comment]
Excellent ! :heart: :heart: :heart: 
I evilified the layer in commit 655e1a2c6be1759d989fbc2c7026fd7724deada1

Thank you ! :+1: 
Cherry-picked into develop, you can safely delete your branch.

**Pull request closed without merging**
