### PR TITLE
[BREAKING CHANGE] delete extra-langs layer

### PR DESCRIPTION
**Pull request by robbyoconnor**
This layer has long been deprecated and is due to be nuked.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@syl20bnr @JAremko @sdwolfz

**Comment by syl20bnr** [comment]
I did not know we had such layer `major-modes`, that's a weird layer for
sure :-)

**Comment by syl20bnr** [comment]
Thank you ! 👍 
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by robbyoconnor** [comment]
@syl20bnr it's mostly just major-modes that didn't really belong in a layer..or are too basic...

**Pull request merged**
