### PR TITLE
hybrid-mode: Simplify implementation

### PR DESCRIPTION
**Pull request by justbur**
Make use of new evil variable evil-disable-insert-state-bindings. This
is better because we are not copying evil code to get hybrid state to
work. We should not need to worry about tracking upstream evil changes
with this version of hybrid mode.

The only effect I can think of with this change is that there is no
longer a distinct hybrid-map, since there is no longer a distinct hybrid
state. This means that, for example, (evil-define-key 'hybrid ...)
will throw an error. You can either use (evil-define-key 'insert ...) or
the preferred (global-set-key ...). The latter is preferred because the
purpose of hybrid mode is to not interfere with Emacs bindings in insert
state.

### CODE REVIEW

**Comment by nixmaniack** [comment]
How will this affect the hooks of hybrid state?
Right now there's clear distinction between insert state of vim mode and insert state of hybrid mode, it looks like they'll be merged with this change. I do use these hooks and hybrid state keymap and occasionally vim style, which might have adverse/unexpected effect.

**Comment by justbur** [comment]
@nixmaniack The current version of hybrid mode is really a hack because it copies/modifies code from evil's insert state to get things like repeat to work correctly. So this is the right way to go in my opinion for long-term maintenance reasons. 

If you can describe how you use the hooks, we can probably come up with a way to do the same thing with this implementation.

**Comment by nixmaniack** [comment]
It looks as follows at majority of places.
```elisp
(use-package lispy
    :defer t
    :init
    (progn
      ;; (spacemacs/load-or-install-package 'hydra)
      (defvar nix-lispy-major-modes '(emacs-lisp-mode lisp-interaction-mode inferior-emacs-lisp-mode cider-repl-mode clojure-mode racket-mode))
      (defun turn-on-lispy-mode ()
        (when (member major-mode nix-lispy-major-modes)
          (lispy-mode)))
      (defun turn-off-lispy-mode ()
        (when (and (member major-mode nix-lispy-major-modes)
                   lispy-mode)
          (lispy-mode -1)))

      (add-hook 'evil-hybrid-state-entry-hook 'turn-on-lispy-mode)
      (add-hook 'evil-hybrid-state-exit-hook 'turn-off-lispy-mode)
      :config
      (progn
        (evil-define-key 'hybrid emacs-lisp-mode-map (kbd "s-m") 'lispy-mark-symbol)
        (with-eval-after-load 'clojure-mode
          (evil-define-key 'hybrid clojure-mode-map (kbd "s-m") 'lispy-mark-symbol)
          (evil-define-key 'hybrid cider-mode-map (kbd "s-m") 'lispy-mark-symbol)))))

;; enable emacs refactoring in insert state
(define-key evil-hybrid-state-map (kbd "s-r") 'emr-show-refactor-menu)

;; multiple cursors
(use-package multiple-cursors
  :defer t
  :bind (:map evil-hybrid-state-map
              ("C-S-c C-S-c" . mc/edit-lines)
              ("C->" . mc/mark-next-like-this)
              ("C-<" . mc/mark-previous-like-this)))

```

Like lispy, I use `worf` in `org-mode` hybrid state with similar setup.

Now even if I switch to vim style, I like to keep lisp major modes, org-mode in hybrid state(as they offer me to manipulate text structure from within insert/hybrid mode with special lispy, worfy keys) but other modes remain in vim like insert state. 

Looks like this won't be possible if hybrid and insert state gets merged.

**Comment by nixmaniack** [comment]
Okay, Looking back again, I don't seem to use vim insert state that much, I guess I can port all of my `hybrid-state` changes to `insert-state`. If this change helps in long-term maintenance and reduces complexity feel free to merge.

**Comment by justbur** [comment]
The entry and exit hooks are easy to recreate. I might want to rename them, but we can keep them with no problem. As for the evil-define-key stuff, I think the "right" thing to do is to use basic emacs (non-evil) keybindings for hybrid insert state. After all the whole point of hybrid state, was to unshadow emacs keybindings in insert state.

**Comment by justbur** [comment]
Added `hybrid-mode-insert-state-entry-hook` and `hybrid-mode-insert-state-exit-hook`, which will only be run if `hybrid-mode` is enabled.

**Comment by nixmaniack** [comment]
>After all the whole point of hybrid state was to unshadow emacs keybindings in insert state.
Agreed. 

Good to have separate hooks. Thanks. :+1:

**Comment by justbur** [comment]
Just rebased this. Also added a wrapper for `evil-define-key` that will translate the call to using `define-key` when hybrid state is specified as well as issuing a warning. I also define `evil-hybrid-state-map` for the same reason (so that using these work temporarily).

**Comment by syl20bnr** [comment]
Thank you :100: Let's see how this goes.
I'm for removing the advice pretty quickly.
@nixmaniack Can you report back your experience with the new implementation ?

**Comment by nixmaniack** [comment]
Cool. I tried this in latest develop.
1. The advice seemed to fail for `(evil-define-key 'hybrid emacs-lisp-mode-map (kbd "s-m") 'lispy-mark-symbol)`. It failed with following error.
```
Debugger entered--Lisp error: (wrong-type-argument arrayp (kbd "s-m"))
```

Changed `hybrid` to `insert` and seems to work fine. 

2. This failed as well `(evil-set-initial-state 'mu4e-compose-mode 'hybrid)`. Although I know I should I use `insert` now, just wanted to point out where it can fail. 

I had used evil-hybrid-state-map which I changed to insert and works fine. 

So if anyone who uses `vim` and `hybrid` (occasionally) would need to define these hybrid-insert bindings with guard ` (when (eq dotspacemacs-editing-style 'hybrid) ... )` so as to avoid polluting vim-insert state bindings. @justbur Is that correct?

Apart from above observations, everything seems to work perfect. :+1:

**Comment by nixmaniack** [comment]
I'm facing one major issue here where `C-p` does `hippie-expand` which is not expected in `hybrid`

Looks like this is set over here https://github.com/syl20bnr/spacemacs/blob/18874c9a3eee11c82528d105dacec9034c5432e1/layers/auto-completion/packages.el#L171

Tried to fix in https://github.com/syl20bnr/spacemacs/pull/4916

**Comment by nixmaniack** [comment]
Is `evil-hybrid-state-map` temporary as well?

**Comment by justbur** [comment]
@nixmaniack 

> So if anyone who uses vim and hybrid (occasionally) would need to define these hybrid-insert bindings with guard (when (eq dotspacemacs-editing-style 'hybrid) ... ) so as to avoid polluting vim-insert state bindings. @justbur Is that correct?

Yes, that's correct. 

> Is evil-hybrid-state-map temporary as well?

Yes

@syl20bnr Instead of trying to fix the problems that @nixmaniack found I think we should just remove the temporary patches and provide some instructions somewhere. I can write them up in the wiki for now.

**Comment by justbur** [comment]
@nixmaniack https://github.com/syl20bnr/spacemacs/wiki/Hybrid-Editing-Style-Changes

**Comment by syl20bnr** [comment]
I cannot test for now and I should have test it before merging. Does this new implementation breaks dynamic switching between hybrid and vim style ? If yes I'll have to revert this new implementation :-(

**Comment by justbur** [comment]
No it doesn't break it. It's a matter of porting personal configuration
that's all.

**Comment by syl20bnr** [comment]
I was wondering because of this:

> So if anyone who uses vim and hybrid (occasionally) would need to define these hybrid-insert bindings with guard (when (eq dotspacemacs-editing-style 'hybrid) ... ) so as to avoid polluting vim-insert state bindings. @justbur Is that correct?

Without the guard is the separation between the two styles broken ?

**Comment by justbur** [comment]
@syl20bnr My recommendation is this https://github.com/syl20bnr/spacemacs/wiki/Hybrid-Editing-Style-Changes

hybrid-mode insert bindings should be defined globally in my opinion. The whole point of hybrid-mode was to not shadow emacs bindings in insert state, so the recommendations on that page are completely consistent with the spirit of hybrid mode. 

When hybrid-mode is off all of the evil insert state bindings come back and shadow the emacs global ones again automatically. So we have the dynamic switching. 

If someone is absolutely intent on having all three styles available all the time (which is a little ridiculous in my opinion) they can use `hybrid-mode-hook` to toggle their bindings, but this should not be necessary.

**Comment by syl20bnr** [comment]
> When hybrid-mode is off all of the evil insert state bindings come back and shadow the emacs global ones again automatically. So we have the dynamic switching.

So why the guard is necessary ? I don't understand.
Maybe it is ridiculous but it is important for me that editing styles don't collide with each other.

**Comment by justbur** [comment]
The guard is not necessary and it's not in the recommendation. 

It's only necessary if you *insist* on using the inset state maps in hybrid mode (this is not the recommendation I made).

**Comment by nixmaniack** [comment]
@justbur Thanks for clarification. I'll try your recommended settings and report here for any feedback.

Also currently there doesn't seem to be a way to toggle between `hybrid` and `vim` styles. Either you can have `emacs` and `hybrid` or `emacs` and `vim` in the `SPC t E`

**Comment by justbur** [comment]
@nixmaniack it works like this

hybrid-mode and holy-mode both off -> vim style
hybrid-mode on holy-mode off -> hybrid
hybrid-mode off holy-mode on -> emacs
both on -> ??

**Comment by nixmaniack** [comment]
@justbur Woops! I totally misunderstood it's working.

My perception was spacemacs starts with whatever editing style we define in dotspacemacs. Then these toggles enable/disable the other editing style at runtime for a quick switch using `C-z`. 

Perhaps we should have the "current final style" displayed while using these toggles using transient state with the way you've represented? 

| hybrid  | holy | final |
| ------------- | ------------- |------------- |
| nil | nil | vim  |
| t  | nil  | hybrid  |
| nil  | t  | emacs  |

Or this would be more intuitive I think. `SPC t E` then `e` for emacs, `h` for `hybrid` and `v` for `vim` without keeping track of which is on/off.

**Comment by syl20bnr** [comment]
We can improve this.
Currently we have a weird mix of radio buttons and check boxes which can be confusing.
I'm OK to move to a fill radio button style UX so we should have not toggles but instead idempotent functions to enable a style.

**Pull request closed without merging**
