### PR TITLE
hybrid-mode: Define hybrid state

### PR DESCRIPTION
**Pull request by justbur**
This state is functionally equivalent to insert state but uses a new
keymap `evil-hybrid-emacs-state-map` that is just populated with escape
and the evil-leader bindings.

Ref #2971

### CODE REVIEW

**Comment by syl20bnr** [comment]
Call it hybrid with <H> :-)

**Comment by justbur** [comment]
You mean just hybrid state?

by the way, evil-escape will need to add this state once this is settled.

**Comment by justbur** [comment]
Also, any idea how to get the mode-specific evil-leader maps to work in emacs state with `M-m m`? They don't right now, and the same is true of hybrid

**Comment by syl20bnr** [comment]
The mode specific leader in emacs state is `C-M-m` which is also translated to `M-RET`.
No problem for evil-escape I'll add this new state to it.
I like `hybrid state` name, it is simpler and this is the name we will use to communicate anyway. Since it is a brand new state it is also good to not mix it with other state (even if implementation wise hybrid state inherits from emacs state - note that this is also the case for the evilified state).

**Comment by justbur** [comment]
Done! Found some other issues and fixed them too. This seems to be working well.

**Comment by syl20bnr** [comment]
Excellent :+1: 
I updated evil-escape, hybrid state support will be available in 3.08

Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by robbyoconnor** [comment]
*facepalm* this broke spacemacs

**Comment by robbyoconnor** [comment]
I just tracked down the regression: See https://github.com/syl20bnr/spacemacs/issues/2980#issuecomment-139480821

**Pull request merged**
