### PR TITLE
ipython layer

### PR DESCRIPTION
**Pull request by CestDiego**
You asked for it :) This is very trivial still ;_;

Also, sorry this is the first org README xD

### CODE REVIEW

**Comment by tuhdo** [comment]
I think the `kbd` should just be replaced with a `=`. We will update the `=` face for viewing Spacemacs documentation.

**Comment by CestDiego** [comment]
Oh i had forgotten about that. Changing it now.

**Comment by cpaulik** [comment]
Great that this is making its way into spacemacs.

Two questions:

- Why a micro state? Does the regular `SPC m` prefix not work?
- I think moving between cells should probably be bound to `g j`, `g k`?

**Comment by CestDiego** [comment]
I had trouble even triggering. This for the major mode. The package has
some complicated mode settings.

**Comment by nashamri** [comment]
:+1: Thanks for this!
Something tiny I noticed, when `SPC a i`, the guide-key entry is `[i] group:applications-irc` which is not obvious for discoverability.

**Comment by syl20bnr** [comment]
`SPC a n i` is free could be it for `notebook` (for another PR).

Thank you ! :+1:  Simple but really cool PR.
I renamed the layer `ipython-notebook` and moved it to `!lang` since ESS is already there, should make sense for data-scientists to have them in the same directory. Related commit: https://github.com/syl20bnr/spacemacs/commit/eaba99a

Cherry-picked into `develop` branch, you can safely delete your branch.

**Comment by tuhdo** [comment]
@geo7 you can update to latest `develop` to try the new `ipython-notebook` layer. Remember to install dependencies according to the `README`.

**Comment by geo7** [comment]
@tuhdo cheers. I've gone to `.spacemacs` and run `SPC f e h` to view available layers - I'm not getting anything for a search of `ipy` though, I'm guessing that there should be an `ipython`layer` available from there?

**Comment by tuhdo** [comment]
You should update to latest `develop` before starting Emacs:

```text
git checkout origin/develop
git pull
```

Then start Emacs.

**Pull request closed without merging**
