### PR TITLE
Make eyebrowse workspaces local to perspective

### PR DESCRIPTION
**Pull request by bmag**
Integrates persp-mode and eyebrowse, so each perspective has its own set of eyebrowse workspaces.
It works great for me, but would be nice if someone else can also confirm that it works.
This takes care of #3733.

### CODE REVIEW

**Comment by syl20bnr** [comment]
This is awesome :purple_heart: 
I think we should move eyebrowse to spacemacs-layouts and add a layer variable to enable it, I'm not sure if it should be enabled by default though.

Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by TheBB** [comment]
Holy shit, you did it!

**Comment by d12frosted** [comment]
Wow, @bmag thank you, this is exactly what I wanted! Going to use it on daily basis.
@TheBB your new key bindings are great to use!

**Comment by nixmaniack** [comment]
This is amazing. @bmag Thanks! :+1:

**Comment by bmag** [comment]
> I think we should move eyebrowse to spacemacs-layouts

@syl20bnr Are you sure about it? Right now a user can have either of the layers or both, and the code is fairly organized.
Moving eyebrowse into spacemacs-layouts will prevent using eyebrowse without spacemacs-layouts, and require a custom way of enabling eyebrowse. What are the advantages? Are they worth it?

**Comment by syl20bnr** [comment]
@bmag spacemacs-layouts is part of the base distribution and the default perspective does not appear in the mode-line and acts as stock Spacemacs without perspectives, so people can already have eyebrowse without perspective of they don't create any additional perspective.

**Comment by bmag** [comment]
OK, so the change still allows people to effectively use eyebrowse without perspectives. So the user just has to enable eyebrowse via layer variable instead of enabling an eyebrowse layer. In that case I have nothing against the change.

Furthermore, it occurred to me that using `SPC l <...>` just for switching layouts, and `SPC b b` for switching buffers, effectively means spacemacs-layouts acts the same as eyebrowse (please correct me if I'm wrong). So spacemacs-layouts acts as a superset of eyebrowse. Now we use eyebrowse for perspective-local workspaces, instead of global workspaces, so it just makes sense to move eyebrowse into spacemacs-layouts.

**Comment by rphillips** [comment]
Thank you! Been looking forward to this.

**Comment by tuhdo** [comment]
I really enjoy using this. Thanks.

**Comment by nwolfe** [comment]
:+1: for combining `eyebrowse` and `spacemacs-layouts` layers, with some layer variables for configuration.

**Comment by robbyoconnor** [comment]
*drools*

**Comment by zilongshanren** [comment]
:+1:  Awesome!

**Comment by spacegoing** [comment]
THIS IS SUPERIOUS

**Pull request closed without merging**
