### PR TITLE
[doc] Fix spelling mistake

### PR DESCRIPTION
**Pull request by bhipple**

### CODE REVIEW

**Comment by smile13241324** [comment]
I am not a native speaker but I think loose should be correct there. @lebensterben could you double check?

**Review by Kazark — APPROVED** [review]
`loose` as a verb means "to set free or cut off" but `lose` as a verb means "to no longer have that which you had"

**Comment by Kazark** [comment]
Helpful: https://www.thefreedictionary.com/loose

**Comment by Kazark** [comment]
Also: https://www.thefreedictionary.com/lose

**Comment by lebensterben** [comment]
It's best to use subjunctive moode
>  If you chose to use =(global-company-mode)= then you would lose some advantages ..

But it's also okay to say
>  If you choose to use =(global-company-mode)= then you will lose some advantages ..

both are better than the imperative mood
> then you lose some advantages ..

**Comment by smile13241324** [comment]
Thanks for the explanation guys :), I'll merge it.

**Pull request merged**
