### PR TITLE
make python indentation configurable

### PR DESCRIPTION
**Pull request by d12frosted**
Hey!

Usually I am just creating a separate function for that and adding it to the python hook. But I feel like this will be useful for others as well.

### CODE REVIEW

**Comment by d12frosted** [comment]
Oh is it ok that I am pushing it to master?

**Comment by TheBB** [comment]
You should make PRs to develop. @syl20bnr tends to cherry-pick, so often it's not a problem, and in fact this commit looks to be conflict-free on the develop branch.

Python will guess the indentation offset when you open a new file, though. Does this cause problems with that?

**Comment by d12frosted** [comment]
> You should make PRs to develop. @syl20bnr tends to cherry-pick, so often it's not a problem, and in fact this commit looks to be conflict-free on the develop branch.

Aha, I see. So should I cherry-pick it to `dev` branch?

> Python will guess the indentation offset when you open a new file, though. Does this cause problems with that?
Well, I want to configure the default value. For example, when I create new file I don't want it to be `4`.

**Comment by TheBB** [comment]
Right. I'm just asking if you have made sure that this `set-local` doesn't override the guessed value when you open a file that *isn't* new.

**Comment by d12frosted** [comment]
Hm. `setq` and `setq-local` do override this. Because this hook is called only after the value is guessed. Just haven't thought about it. So that's for pointing this out.
Probably we should set the value only if `spacemacs/python-indent-level` is not `nil`. And it's default value should be `nil`. So if user sets this value, than offset will be overridden.

**Comment by robbyoconnor** [comment]
@TheBB can you close this?

**Pull request closed without merging**
