### PR TITLE
Provide dos2unix and unix2dos interactive commands.

### PR DESCRIPTION
**Pull request by ralesi**
Helper functions to change file encoding.

### CODE REVIEW

**Comment by syl20bnr** [comment]
Same thing here, the functions are not used (bound).
We could put it behind `SPC f C f` for Convert. Maybe `SPC f C d` and `SPC f C u`.

**Comment by ralesi** [comment]
I will update using these suggested bindings.

**Comment by ralesi** [comment]
updated and added functions to spacemacs namespace.

**Comment by syl20bnr** [comment]
Great, thank you!!!
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
