### PR TITLE
helm-projectlie-dwim - use ag / ack / pt or grep based on whats installed

### PR DESCRIPTION
**Pull request by ralesi**
Defaults to ag to remain consistent with previous mapping. 

This is the last PR.  I promise.

### CODE REVIEW

**Comment by syl20bnr** [comment]
Nice batch indeed :-)
Interesting approach, directly related to #954.
It's hard for me to merge these 2 PRs, we have to think carefully about the search tools, I have the feeling that the present approach is too complicated.

**Comment by ralesi** [comment]
If `SPC /` is the projectile-search variant, what binding would we like for the do-search variant?

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
Cherry-picked in `develop`, you can safely delete your branch.

Good remark, I came up with the following design:

To search in an arbitrary directory
SPC s / -> do what I mean (select the first found utility)
SPC s a -> ag
SPC s g -> grep
SPC s k -> ack
SPC s p -> pt

To search in a project
SPC /     -> do what I mean (select the first found utility)
SPC p s a -> ag
SPC p s g -> grep
SPC p s k -> ack
SPC p s p -> pt

Note the symmetry.

helm-projectile-switch-project has been move on `SPC p S`

`SPC s /` and `SPC /` search in this order: `pt, ag, ack, grep`. If an universal argument is used `SPC u SPC s /` or `SPC u SPC /` then the search list is just `ack, grep` and `pt` and `ag` are ignored.

Related commit: 66e1641c424c453848e7ed556b37f8b328f9bc76

**Comment by tuhdo** [comment]
Why don't you move `helm-projectile-switch-project` to `SPC p p` since this is free? It's closer to the default Projectile key bindings, so new users who are used to old Projectile key binding are easier to adapt. And seriously, this is a frequent command I use, just below `SPC p f` and you put it on an upper case key?

**Comment by syl20bnr** [comment]
You are right, `SPC p p` is free, I'm changing it ;-)

**Pull request closed without merging**
