### PR TITLE
Update Evil repo

### PR DESCRIPTION
**Pull request by pirj**
Gitorious is now defunct and Evil moved to Bitbucket according to [Emacs Wiki](https://www.emacswiki.org/emacs/Evil)

### CODE REVIEW

**Comment by nixmaniack** [comment]
...and it recently migrated to https://github.com/emacs-evil/evil (official update at https://bitbucket.org/lyro/evil/wiki/Home) 😄 .

**Comment by pirj** [comment]
@nixmaniack Good catch! Real life race condition, when I started to prepare this massive patch, bitbucket Wiki had nothing regarding migration, so this catched me up unguarded. Updated the PR. Should I squash commits?

**Comment by pirj** [comment]
Squashed commits.

**Comment by robbyoconnor** [comment]
Failing Travis isn't your fault.

**Comment by syl20bnr** [comment]
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
