### PR TITLE
Add ghc-show-type/info key mappings (haskell).

### PR DESCRIPTION
**Pull request by PierreR**
Two short key mappings for two very useful functions.

### CODE REVIEW

**Comment by PierreR** [comment]
A few people have found these key mappings convenient so I propose them as a PR.

**Comment by syl20bnr** [comment]
Sorry to make them longer but according to conventions these key bindings must go under `SPC m h`, see the C# layer for instance. So the bindings should be `SPC m h t` and `SPC m h i`.
`SPC m t` is reserved for testing.

Also can you update the `README.org` file with the new bindings ? ;-)

**Comment by syl20bnr** [comment]
Stoooooooooooooooooooop ! :-D
Apparently your PR is superseeded by the previous one #3197.
I think you can close this PR.

**Comment by PierreR** [comment]
Sure I should done so before

**Pull request closed without merging**
