### PR TITLE
New cquery layer

### PR DESCRIPTION
**Pull request by danielsuo**
This PR is 100% the work of @cormacc. I opened the pull request to start a conversation about his work.

I was able to get everything working pretty easily (great!), but the commits completely zonk syntax highlighting for me in C/C++ files. For example, the function names in their declarations are all different shades of brown/orange!

Wasn't sure if there was a simple fix.

### CODE REVIEW

**Comment by cormacc** [comment]
Hey Daniel,
I intentionally haven't raised this as a PR until the lsp-layer PR is merged, as reckoned it was potentially confusing having one PR built on top of another pending PR. It's also tedious continuously rebasing the lsp-layer PR on develop, and then the cquery layer on that.

Re. rainbow highlighting -- you can disable that for now by editing the cquery layer packages.el and commenting out line 42, which reads:
    `(cquery-use-default-rainbow-sem-highlight)`

It's a subjective preference, so probably a good idea to set it based on a layer configuration parameter instead. I'll look at it when/if the lsp-layer PR ever gets merged. Not getting to do much actual development myself the last few weeks, between different things going on at work.

**Comment by danielsuo** [comment]
Cormac: yep, I saw your note about not opening a PR! Just wasn’t sure
where else to log this comment for you to respond and others to be able to
search.

Feel free to close. Thanks for the response! I’ll give it a try.

**Comment by MaskRay** [comment]
`lsp-remap-xref-keybindings` looks to me somewhat redundant. `lsp-ui-peek-find-references` can be added as a candidate if a generic find-reference handler is available (similar to a jump-handler)

I know as a fork it will never be as successful as cquery is. Just want to remind that such alternative exists:  <https://github.com/MaskRay/ccls/wiki/Getting-started>

**Comment by cormacc** [comment]
Hey Fangrui,
If the lsp layer improvements PR gets accepted I might look at reworking
the cquery layer as an lsp-c layer that works with either cquery or ccls as
a back-end. You reckon that's viable? Haven't got near any actual c
development work myself for the last month or so, as work for a small
company and wear a few too many hats, so don't have time to play with
either at the moment. That'll probably be the case for another couple of
weeks, but have a whole load of embedded C work in the pipeline so should
get back to it soon.

**Comment by danielsuo** [comment]
Get on board the cquery train!

(Just kidding; I think this would be a great direction for the PR)

**Comment by shwsun** [comment]
@danielsuo I think it would be great if you want to weigh in in #10486 , I think the community needs more people to test and report in order to move things forward -- getting the PR merged.

**Comment by danielsuo** [comment]
I’m not sure I’ve used enough to weigh in technically. I’d really only be
another voice that says “come on, LSP is tablestakes now”.

Which...I’m happy to be...

**Comment by Glaeqen** [comment]
I guess it should be closed & declined because of #10486 ?

**Comment by cormacc** [comment]
Yep - this should probably be closed as I've rolled the cquery layer into the lsp-layer-improvements PR as a usage example. @danielsuo can you do this? Think only the submitter and maintainers have the necessary privileges.

**Pull request closed without merging**
