### PR TITLE
core: Add resize hook later in startup

### LINKED ISSUE #6986: REGRESSION: auto centering spacemacs-buffer causes several second startup hang
#### Description :octocat:
Auto centering spacemacs-buffer (a7d4674) when combined with using
initial-frame-alist causes a several second hang during starutp.

#### Reproduction guide :beetle:
- Add something like this to your init.el:
```
(setq initial-frame-alist
      '(
        (top . 23)
        (left . 0)
        (width . 122)
        (height . 40)))
```
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Emacs freezes for several seconds after the window resizes.

*Expected behaviour:* :heart: :smile:
Emacs does not freeze.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: nil (rev. 4e7d80b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(better-defaults spacemacs-layouts helm emacs-lisp markdown
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 (auto-completion :variables auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup nil)
                 erlang elixir git dash html clojure
                 (org :variables org-enable-github-support t)
                 colors osx github javascript react deft ruby
                 (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
                 spell-checking ranger version-control rcirc tmux yaml docker elm evil-little-word auto-correct frame-geometry cleverparens-lispy flow)
```

### PR DESCRIPTION
**Pull request by aaronjensen**
Fixes hang while resizing on startup with initial-frame-alist.

Fixes #6986

### CODE REVIEW

**Comment by TheBB** [comment]
That looks peculiar, but seems to make sense from the docstring. Thanks!

**Comment by aaronjensen** [comment]
No problem. This still does not fix #6997 which would require some sort of debouncing and i'm not sure how to do that w/ emacs.

**Comment by aaronjensen** [comment]
Given that #6986 ended up being a configuration change issue, this isn't necessary. It may be slightly more correct?

**Comment by TheBB** [comment]
Yes, I would keep this anyhow.

**Comment by TheBB** [comment]
I put your commit on top of https://github.com/syl20bnr/spacemacs/pull/7007 just to keep everything in one place.

**Pull request closed without merging**
