### PR TITLE
Add 'SPC p $' to run multi-term at project root

### PR DESCRIPTION
**Pull request by tonylotts**

### CODE REVIEW

**Comment by CestDiego** [comment]
This :+1:

**Comment by syl20bnr** [comment]
It does not seem to work for me :-(

**Comment by syl20bnr** [comment]
Ok... I have a `cd ~` seems to be required in my config under xquartz.

**Comment by tonylotts** [comment]
I'll take a look.  I'm using emacs-mac-port 24.5, and the osx layer.

**Comment by syl20bnr** [comment]
@tonylotts there is nothing wrong in your PR, this is on my side, I have a `cd ~` in my bashrc file so it defeats the default directory set by projectile.

**Comment by tonylotts** [comment]
@syl20bnr ok good.  Please let me know if there's anything else this needs.

**Comment by syl20bnr** [comment]
Thank you ! It works as intended, it was just my bashrc.
I moved  the binding from `SPC p $` to `SPC p $ t` to mimic the `SPC a s t` shortcut and keep `t` for multi-term. I also moved the function in `init-projectile`. Related commit https://github.com/syl20bnr/spacemacs/commit/7a3f32b

Cherry-picked into `develop`, you can safely delete your branch.

**Pull request closed without merging**
