### PR TITLE
replaced typescript layer pr2

### LINKED ISSUE #4766: TypeScript layer is outdated
[spacemacs/layers/+lang/typescript/](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/typescript)   uses [tss](https://github.com/aki2o/emacs-tss) but as mentioned in #3418, [typescript-tools](https://github.com/clausreinke/typescript-tools/tree/develop) is outdated and tss repo looks neglected. 

On the other hand, [tide](https://github.com/ananthakumaran/tide) package supports TypeScript `1.7.3`(tss  `1.5`)

**I propose 3 solutions:**
  - Replace tss with tide
  - Add alternate  TypeScript layer or allow to choose underling package via configs
  - Create a monster [1](https://gist.github.com/mars888/cc53e761ec892bcd31d6),[2](https://www.reddit.com/r/emacs/comments/39ejtn/tide_typescript_interactive_development/)  

*tss has more elisp in it, but both rely on third party libs and runtime.*

### PR DESCRIPTION
**Pull request by JAremko**
This resolves #4766  closes #3418 and  fixes #4788

### CODE REVIEW

**Comment by syl20bnr** [comment]
Why a new PR ? #3418 is wrong ?
cc @reed1

**Comment by JAremko** [comment]
@syl20bnr  poor quality

  - It lacks key binding for the reference mode and one for the typescript mode
  - README.org doesn't cover all the points
  -  It hasn't `spacemacs/declare-prefix-for-mode`
   
And reed1 not active on GitHub so I'm not sure he's coming back to fix it.

**Comment by reed1** [comment]
Haha true, I'm no expert on emacs/spacemacs, it was just basic demonstration that tide can be used to replace emacs-tss, @JAremko PR is much better. I'm more than happy if this got merged. Mine can be closed anyway :+1:

**Comment by JAremko** [comment]
@reed1 thank :blush:

**Comment by syl20bnr** [comment]
Thank you guys :+1: 
I adapted the key bindings to better fit the conventions and omnisharp, see commit https://github.com/syl20bnr/spacemacs/commit/d924f03
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by JAremko** [comment]
@syl20bnr  cool Thanks!

**Pull request closed without merging**
