### PR TITLE
add evil-tmux-navigator

### PR DESCRIPTION
**Pull request by rphillips**
Working great for me.

### CODE REVIEW

**Comment by rphillips** [comment]
[Video Demo](https://www.youtube.com/watch?v=zFax7dviIqM)

**Comment by syl20bnr** [comment]
Great integration! :+1: 
Can you rename the layer to the more general name `tmux` ?

**Comment by rphillips** [comment]
thanks. fixed.

**Comment by rphillips** [comment]
when I renamed the files I forgot to update the extension.el... fixed.

**Comment by syl20bnr** [comment]
Great ! :+1: 
Thank you !
Cherry-picked into `develop`, you can safely delete your branch.

**Pull request closed without merging**
