### PR TITLE
Bugfix for spray package loading

### LINKED ISSUE #3882: Move spray package to its own layer
After a lot of sweat and hard thought, we can move to the layer names `speed-reading`.

### PR DESCRIPTION
**Pull request by StreakyCobra**
And some small UX improvements when on it.

Fixes #3882 (again :-))

### CODE REVIEW

**Comment by TheBB** [comment]
Looks :+1: to me except the whole shared which-key prefixes thing is going to become unmaintanable quite quickly if we do it that way.

**Comment by StreakyCobra** [comment]
I know, I though the same when writing it. But is there any better solution?

**Comment by justbur** [comment]
> except the whole shared which-key prefixes thing is going to become unmaintanable quite quickly if we do it that way.

Agreed. If you want to do this we should have a append-prefix function or something like that

**Comment by StreakyCobra** [comment]
Ok. I can move it to `SPC a R` for now, and we can tackle the whole problem later if needed. What do you think?

**Comment by StreakyCobra** [comment]
@TheBB @justbur Updated

**Comment by syl20bnr** [comment]
Thank you :+1: 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
