### PR TITLE
Create the layer README on create-layer

### LINKED ISSUE #3259: README template not included when configuration-layer/create-layer is called
This should happen. I don't know when it stopped being created.

### PR DESCRIPTION
**Pull request by StreakyCobra**
When using `configuration-layer/create-layer`, the `README.org` file is
not created from the template. This change corrects this.

Close #3259

### CODE REVIEW

**Comment by TheBB** [comment]
I don't much care for that `ext` argument...

Is there a reason we can't just name the source files the same as their target files? Or remove the `.template` part automatically so that the source files are called e.g. `packages.el.template`?

**Comment by robbyoconnor** [comment]
I was gonna work on this but my Emacs Lisp skills suck

**Comment by StreakyCobra** [comment]
@TheBB done. I don't know if you already want to remove `extensions.el` from here, or if we do it globally later? Also wouldn't it be better if we provide and create directly also `funcs.el`, `config.el` and `keybindings.el`? It's far more easier to remove them if not needed than creating them.

**Comment by robbyoconnor** [comment]
That extension caused me so much of a headache when trying to fix this myself

**Comment by TheBB** [comment]
I think this PR is fine as it is. We can introduce the others in a new PR if you feel that's important.

I guess we will remove extensions together with the rest of the deprecated features later.

**Comment by robbyoconnor** [comment]
> I think this PR is fine as it is. We can introduce the others in a new PR if you feel that's important.
>
>I guess we will remove extensions together with the rest of the deprecated features later.

:+1:

**Comment by StreakyCobra** [comment]
Cherry-picked into develop.

**Pull request closed without merging**
