### PR TITLE
[spacemacs-editing] disable show-paren-mode when smartparens is used

### PR DESCRIPTION
**Pull request by bb2020**

### CODE REVIEW

**Comment by lebensterben** [comment]
> spm and smartparens are mutually exclusive

where do you get this?

**Comment by bb2020** [comment]
`show-paren-match` face masks `sp-show-pair-match-face`. it may be a good idea to disable `show-paren-mode` when `smartparens` is enabled.

**Comment by lebensterben** [comment]
> show-paren-match face masks sp-show-pair-match-face. it may be a good idea to disable show-paren-mode when smartparens is enabled.

source? or how do you find out this?

**Comment by bb2020** [comment]
first image = both disabled
second image = `show-smartparens-mode`
third image = `show-smartparens-mode` + `show-paren-mode`

Screenshot_2023-02-12_00-40-17
Screenshot_2023-02-12_00-40-53
Screenshot_2023-02-12_00-41-13

**Comment by lebensterben** [comment]
post the output of SPC h I

**Comment by bb2020** [comment]
test it yourself. you are enabling two packages which are doing the same job.

**Comment by lebensterben** [comment]
I don't see anything you mentioned so I asked you.

**Pull request closed without merging**
