### PR TITLE
fix python layers anaconda-mode requirements 404

### PR DESCRIPTION
**Pull request by Rand01ph**
Thank you for contributing to Spacemacs!

Before you submit this pull request, please ensure it is against the develop branch and not master.

This message should be replaced with a description of your change.

Thank you <3

### CODE REVIEW

**Comment by Stebalien** [comment]
@Rand01ph I assume you meant to close this one?

**Comment by Rand01ph** [comment]
@Stebalien yes, sorry for this.

**Comment by Stebalien** [comment]
FYI,

**Comment by Rand01ph** [comment]
This isn't a real issue. I'll close #7896

**Pull request closed without merging**
