### PR TITLE
Add Pacmacs to games layer

### PR DESCRIPTION
**Pull request by CestDiego**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1:
:100: 
:grinning:

**Comment by syl20bnr** [comment]
This PR made me smile, I wanted to add it this week end but I had not the time to do it. Thank you for fixing this :-D
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by CestDiego** [comment]
Now the pacman on the readme makes sense :D

**Comment by kRITZCREEK** [comment]
For anyone interested... @rexim is actually developing the game live on stream right now: https://www.livecoding.tv/rexim/

**Comment by CestDiego** [comment]
Thanks @kRITZCREEK. I've been watching it, didn't know you could use jabber.el with livecoding feed

**Pull request closed without merging**
