### PR TITLE
Change ruby layer to use RSpec-Mode

### PR DESCRIPTION
**Pull request by alexgirdler**
Rebase off develop for #3757

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Doesn't this force people to use rspec?

**Comment by robbyoconnor** [comment]
Which I don't think we want to do...that said rspec is the industry standard soo...but still.

**Comment by TheBB** [comment]
The Python layer has a variable for the test runner to use, so there's precedence for supporting both tools. Then again I'm out of my depth in Ruby, so you rubyists should agree on something.

**Comment by StreakyCobra** [comment]
For the record: Duplicate of #3067. If this PR get merged, the other one should be closed.

**Comment by codedmart** [comment]
Just to throw in my opinion. I haven't written Ruby in a while, but I think this seems ok as long as it is overridable if you want to use something else.

**Comment by alexgirdler** [comment]
I'm going to add a variable to switch the test runner and update the PR.

**Comment by rejeep** [comment]
Perhaps instead of `ruby-use-ruby-test`, the name should be more generic, for example: `ruby-test-framework`. Now it's limited to just Rspec and ruby-test, but there are others.

**Comment by syl20bnr** [comment]
Thank you :+1: 
I modified it to follow to use the same kind of variable as python, see commit https://github.com/syl20bnr/spacemacs/commit/7e0d8f2
The variable is now `ruby-test-runner` which takes a symbol, either `rspec` or `ruby-test` (default). It should also be possible to use directory local variable to change this settings on a per project basis.
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by karmajunkie** [comment]
I'm unable to get the keybindings for ruby-test to work, even when the project doesn't have rspec in its bundle. I've got the layer in the dotfile as follows

```
     (ruby :variables ruby-test-runner 'ruby-test)
```

but when I hit `SPC m t` all I get are the rspec versions of the test runner. I've also tried manually overriding the bindings with no results. Am I doing something wrong here?

**Comment by alexgirdler** [comment]
@karmajunkie I just created a branch that should fix your issue #4251

**Pull request closed without merging**
