### PR TITLE
Use counsel-projectile for projects with ivy.

### PR DESCRIPTION
**Pull request by ralesi**
Use `counsel-projectile` for project based commands in ivy, providing for additional custom actions.

### CODE REVIEW

**Comment by d12frosted** [comment]
I just tried it and it looks like bindings are not applied properly. Because in `init-porjectile` (in `spacemacs-base`) there's following line:

```
(unless (configuration-layer/package-usedp 'helm-projectile)
        (spacemacs/set-leader-keys
          "pb" 'projectile-switch-to-buffer
          "pd" 'projectile-find-dir
          "pf" 'projectile-find-file
          "pF" 'projectile-find-file-dwim
          "ph" 'helm-projectile
          "pr" 'projectile-recentf
          "ps" 'projectile-switch-project))
```

We should also avoid this for `ivy` 😄

**Comment by ralesi** [comment]
@d12frosted, thanks for catching this.  I updated to test for `counsel-projectile` as well.

**Comment by sooheon** [comment]
The package looks really useful, I was just thinking that kind of dispatch after projectile would be great.

**Comment by ralesi** [comment]
Updated this to work with the new ivy location.

**Comment by syl20bnr** [comment]
Thank you ! 👍 
I refactored it a bit to use :toggle and use-package hooks: https://github.com/syl20bnr/spacemacs/commit/47988be and https://github.com/syl20bnr/spacemacs/commit/4dead4c
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
