### PR TITLE
Colorized files in Spacemacs Buffer

### PR DESCRIPTION
**Pull request by alexameen**
I wanted to spruce up my Spacemacs Buffer a bit and thought it might be enjoyed by others as well.
I made the following changes: (TL;DR added pretty colors to Spacemacs Buffer Lists)

File Lists will not automatically detect if a path is a directory or a regular file and colorize each.
The format for these lists has been changed from the full file path to: `BASENAME/DIRNAME - (/the/full/path)`. The color faces are: `{ basename: bold, dirname: dired-directory, path: file-name-shadow, "- ()": default }`.
A similar change was made to Bookmarks where I retain the conventional label rather than using a basename/dirname.

These changes were not applied to any other lists, but easily could.
Full disclosure: I am fairly new to Elisp so there are likely tweaks to be made to my code, but the
【﻿ａｅｓｔｈｅｔｉｃ】
is undeniable pleasing :joy:.

[Preview Image](https://imgur.com/a/jZGEftP)

### CODE REVIEW

**Comment by duianto** [comment]
Thank you for contributing to Spacemacs.
The PR has been cherry picked into the `develop` branch. It's safe to delete your branch.
Commit: https://github.com/syl20bnr/spacemacs/commit/bbb9d3d559fe3d6f91ef123dddb41fcc9b5bc7e2

This looks like a nice improvement. 👍 

I added this now. But another maintainer: bmag said:
>I'd prefer if the colors would distinguish between the sections, e.g. recent files in red, projects in purple, and bookmarks are ok as is (blue for directories, gray for files).

I said that red might be interpreted as an error or that a file has been deleted.

bmag responded with:
>Doesn't have to be red, it was just an example

If you would like to implement that suggestion, or something similar. Feel free to open a new PR.

**Comment by BadDecisionsAlex** [comment]
> Thank you for contributing to Spacemacs.
> The PR has been cherry picked into the `develop` branch. It's safe to delete your branch.
> Commit: [bbb9d3d](https://github.com/syl20bnr/spacemacs/commit/bbb9d3d559fe3d6f91ef123dddb41fcc9b5bc7e2)
> 
> This looks like a nice improvement. 
> 
> I added this now. But another maintainer: bmag said:
> 
> > I'd prefer if the colors would distinguish between the sections, e.g. recent files in red, projects in purple, and bookmarks are ok as is (blue for directories, gray for files).
> 
> I said that red might be interpreted as an error or that a file has been deleted.
> 
> bmag responded with:
> 
> > Doesn't have to be red, it was just an example
> 
> If you would like to implement that suggestion, or something similar. Feel free to open a new PR.

I had just been trying to copy the coloring style used by Dired to distinguish files and folders; but I can understand that folks might want to apply their own color-schemes. I think what I will do is add some custom variables so folks can set files/folders of specific sections (bookmarks, recents, etc..) in their `.spacemacs`

**Comment by duianto** [comment]
There's an issue with this PR on the `spacemacs-base` distribution.

The distribution is changed with the `dotspacemacs-distribution` variable at the top of `.spacemacs`.

On startup the spacemacs buffer shows:
>Recent Files:

Then this void message appears:
>if: Symbol’s function definition is void: f-directory-p

`f-directory-p` seems to be defined in the f package https://github.com/rejeep/f.el#f-directory-path

The `f` package doesn't seem to be loaded in the `spacemacs-base` distribution.

Is there a way to solve the issue without an external package?

**Comment by duianto** [comment]
I reverted the commit, the issues wasn't limited to the spacemacs buffer.
`SPC /` showed:
>let: Symbol’s function definition is void: projectile-project-root

It can be re-added when the issue is solved.

**Pull request closed without merging**
