### PR TITLE
unimpaired: Update ownership

### PR DESCRIPTION
**Pull request by ralesi**
Update owner on unimpaired

### CODE REVIEW

**Comment by d12frosted** [comment]
@syl20bnr you are the person who can judge this PR 😸

**Comment by ralesi** [comment]
He sent me a PM asking me to update,  so I went ahead. 


Rich






On Thu, Dec 22, 2016 at 7:40 AM -0700, "Boris" <notifications@github.com> wrote:












@syl20bnr you are the person who can judge this PR 😸

**Comment by ralesi** [comment]
@syl20bnr,  should I just make this a package in melpa?

**Comment by syl20bnr** [comment]
It could be a MELPA package but don't close this PR.

**Comment by beta1440** [comment]
Are there any updates on this issue?

**Pull request closed without merging**
