### PR TITLE
Add option to show snippets in the company popup.

### PR DESCRIPTION
**Pull request by person808**
~~Its a little flaky (sometimes snippets dont show, sometimes they do) but I dont know why. When it works, it is fine~~

Seems to work reliably now

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1:

**Comment by andyque** [comment]
@person808  good :+1:

**Comment by syl20bnr** [comment]
Nice ! Thank you ! :+1: 

Cherry-picked into develop branch, you can safely delete your branch.

**Comment by andyque** [comment]
@person808  I have enabled   `auto-completion-show-snippets-in-popup` in `auto-completion` layer, but it seems not working.  Any suggestions?

**Comment by person808** [comment]
@andyque `auto-completion-enable-snippets-in-popup` Its a typo in the docs

**Comment by stormpat** [comment]
PR: #2195

**Pull request closed without merging**
