### PR TITLE
Fix widget-button-click for core Spacemacs buffer

### LINKED ISSUE #14964: Spacemacs buffer terminal mouse click on links appears broken
It seem that this line: https://github.com/syl20bnr/spacemacs/blob/develop/core/core-spacemacs-buffer.el#L91

Should instead bound to `mouse-1` and not to `down-mouse-1` as it does.

The way it is now, when I click on a link from a terminal Emacs, the link gets highlighted, but it doesn't navigate, and Emacs is stuck waiting for more input as if I have not finished typing a keychord:

> down-mouse-1 ESC [ < 0 ; 8 1 ; 1 9 ; m

I'm not too sure why this happens, but it prevents the click from working, and afterwards everything I type or click on just gets added to more commands on the keychord and it only stops if I `C-g`.

I tried to simply change it to:

```
(define-key map [mouse-1] 'widget-button-click)
```

And that seems to have fixed it.

### PR DESCRIPTION
**Pull request by opie4624**
Fixes syl20bnr/spacemacs#14964

Possibly related to syl20bnr/spacemacs#13539

### CODE REVIEW

**Review by smile13241324 — APPROVED** [review]

**Comment by real-or-random** [comment]
This has the strange effect that I'm always in "visual select" mode... 	

See screencast:
[Screencast from 2023-01-03 11-36-25.webm](https://user-images.githubusercontent.com/1071625/210341371-7869a6de-4c16-417b-a810-4fbc31e79eff.webm)

I'm never *holding down* the mouse button during this screencast, just pressing it.

I haven't included the mode indicator but it shows grey (=visual in my theme) the entire time.

**Comment by lebensterben** [comment]
@real-or-random 

Because if you use `evil`, `down-mouse-1` is now bound to `evil-mouse-drag-region` which enters `evil-visual-state`.

So in other word this PR introduced the new issue.

**Comment by real-or-random** [comment]
Is there a chance that this fixed https://github.com/syl20bnr/spacemacs/issues/15105 on the way?

**Comment by lebensterben** [comment]
@real-or-random 

I never reproduced the issue described there so I don't know.

**Pull request merged**
