### PR TITLE
Update csharp layer to be more up to date with the latest omnisharp package

### PR DESCRIPTION
**Pull request by razzmatazz**
This updates documentation and keybindings for `csharp` layer to be more in line to what we have in the latest `omnisharp` package.

### CODE REVIEW

**Comment by razzmatazz** [comment]
Btw, how should I find out what is the problem with ci/circleci CI tests?

All I get is a non-ending spinner wheck trying to check what it is that failed:
bildschirmfoto 2017-08-21 um 12 21 41

**Comment by duianto** [comment]
The infinite spinning animation also happens for me, but clicking on: `v bash ./.circleci/run` to close it: 
`> bash ./.circleci/run` and again to open it. Shows the output:
```
#!/bin/bash -eo pipefail
bash ./.circleci/run
First commit: fb33d466e7d301a8a1f617dcdf35968074475f45
======================================================================
Testing changed ORG files with spacefmt
======================================================================
Files to be formatted: ("/root/project/layers/+lang/csharp/README.org")
Done!
Done.
======================================================================
Testing with exporter
======================================================================

PROCESS: #<process worker>


!!!!!!!!!!!!!! TEST FAILED !!!!!!!!!!!!!!
File "/root/project/layers/+lang/csharp/README.org" doesn't have "Features:"(With a colon) list in the top level "Description" headline
See "https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/README.org.template"
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Process worker has finished

Test failed.
Documentation needs some fixing ;)
Exited with code 1
```

**Comment by razzmatazz** [comment]
Ok, fixed

**Comment by syl20bnr** [comment]
Thank you ! 💜 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
