### PR TITLE
[bot] Documentation formatting

### PR DESCRIPTION
**Pull request by emacspace**
Merge with care - I'm just a stupid bot. Beep boop.

### CODE REVIEW

**Comment by sdwolfz** [comment]
@JAremko help! What's the deal with that TOC?

**Comment by JAremko** [comment]
@sdwolfz  Not sure. But I changed a lot in the bot lately (like last week) could mess up something :thinking: 

 I'll figure out.

**Comment by JAremko** [comment]
@sdwolfz  Looks like it was a third party code update that broke the TOC.  :thinking: 

And I can't reproduce it locally soo...  I'll apply random fix :crossed_fingers:

**Comment by JAremko** [comment]
I poked randomly and it helped. Amazing! :muscle:

**Pull request merged**
