### PR TITLE
Fixes #5508 - don't disable menu-bar on os x in emacs 25

### LINKED ISSUE #5508: Menu bar disabled in Emacs 25 on OSX
#### Description
I just switched to Emacs 25 on OSX, found the menu bar is disabled. This is not the case when I used Emacs 24.5.

#### Reproduction guide
- Start Emacs (version 25)

*Observed behaviour:*
Menu bar is gone

*Expected behaviour:*
Menu bar should be there

#### System Info
- OS: darwin
- Emacs: 25.0.92.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. 82fdd9a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm auto-completion emacs-lisp
                (git :variables git-magit-status-fullscreen t)
                markdown org spell-checking syntax-checking version-control osx colors idris haskell
                (latex :variables latex-build-command "LatexMk")
                (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
                ocaml proof-general)
```

I did a little research, found the culprit was that the value of `window-system` was changed to `ns` instead of `mac` in Emacs 25.

### PR DESCRIPTION
**Pull request by d12frosted**
Fixes #5508

### CODE REVIEW

**Comment by d12frosted** [comment]
Wait. Today is bad day for me - `spacemacs/system-is-mac` is not defined yet at that point.

**Comment by d12frosted** [comment]
@syl20bnr `spacemacs/system-is-mac` is defined in `spacemacs-base` distribution. Shouldn't it be part of core?

**Comment by TheBB** [comment]
It should. I can't use those functions in the dotfile, which is annoying.

**Comment by d12frosted** [comment]
I moved them to core. Did it in a separate commit (cause it looks better in separate commits), but if you wish - I can squash them.

**Comment by bixuanzju** [comment]
Any update on this?

**Comment by d12frosted** [comment]
Ping :)

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
I move the functions to `core-funcs.el` and create a new function `spacemacs/window-system-is-mac` and use it instead of `spacemacs/system-is-mac` because it was not working on a `--with-x11` compiled emacs in XQuartz. Hopefully it should be good, @bixuanzju waiting for your confirmation.

Seems that travis errored with my changed but it does not seems to be related to the PR.

Cherry-picked into develop branch, you can safely delete your branch.

**Comment by d12frosted** [comment]
> create a new function spacemacs/window-system-is-mac and use it instead of spacemacs/system-is-mac because it was not working on a --with-x11 compiled emacs in XQuartz

Ah... good that you've noticed that before users :)

**Comment by bixuanzju** [comment]
@syl20bnr yes, it's good, thanks!

**Pull request closed without merging**
