### PR TITLE
Add key bindings for org-feed-update-all and org-feed-goto-inbox

### PR DESCRIPTION
**Pull request by seemyvest**
Add global and layer key bindings for `C-c C-x g` and `C-c C-x G` (org-feed-update-all & org-feed-goto-inbox, respectively).

### CODE REVIEW

**Comment by Compro-Prasad** [comment]
Seems like a nice addition @syl20bnr . It is part of `org-plus-contrib` thus a default org mode function and the keybinding is nice too. See for yourself to confirm.

**Comment by seemyvest** [comment]
I don't mind either way, both make sense to me.

**Comment by syl20bnr** [comment]
We try to not put key bindings under `C-c`.
The only place where I agree to put them globally is under `SPC a o`
which is application/org.

So `SPC a o f u` for instance.

**Comment by syl20bnr** [comment]
Thank you ! 👍 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request merged**
