### PR TITLE
Add 2048-game layer

### PR DESCRIPTION
**Pull request by nashamri**
More fun :smile: and less productivity!

### CODE REVIEW

**Comment by CestDiego** [comment]
I was starting to worry nobody had done this :P

**Comment by syl20bnr** [comment]
Excellent :-)
You can rename the layer `games` and we will put all the gameplay adapted games in their.

**Comment by nashamri** [comment]
Okay, pushed another PR for the evil games :smiling_imp: #1613

**Comment by syl20bnr** [comment]
I close this one since it is superseed by the new games layer in PR #1613

**Pull request closed without merging**
