### PR TITLE
helm-mu4e integration + keybinding changes

### PR DESCRIPTION
**Pull request by numkem**
This pull request contains 2 things:
- helm-mu integration
- Change keybinding `SPC M` to `SPC m` for `mu4e` layer
- Change keybinding `SPC m` to `SPC M` for `spotify` layer
  - Adds `SPC m s` for `helm-mu`
  - Adds `SPC m c` for `helm-mu-contacts`

### CODE REVIEW

**Comment by darkfeline** [comment]
Looks good, I think, but this should probably have been split into two or three commits and PRs.

Hint: the `+` in the title

**Comment by numkem** [comment]
@darkfeline do you want me to resubmit multiple PRs or this could be OK?

**Comment by nixmaniack** [comment]
@numkem It should be fine for now, maintainers can cherry pick them. Just keep in mind for the future contributions.

**Comment by syl20bnr** [comment]
Thank you ! 👍 

I updated to nowadays standard in commit: https://github.com/syl20bnr/spacemacs/commit/0b484bc6

Also note that I reverted the key bindings to `SPC a M` and moved the helm-mu key bindings under major-mode specific key bindings.

The reason I reverted to `SPC a M` is that people are used to it now and there will be better management if the application like packages lime mu4e in the future.

Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
