### PR TITLE
adds psc-ide support to purescript layer

### PR DESCRIPTION
**Pull request by kRITZCREEK**
This adds support for https://github.com/kRITZCREEK/psc-ide.

This is my first contribution to spacemacs and my second adventure into elisp land so I'd ask you to review this thoroughly... I don't want to break people's configuration.

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
@StreakyCobra ping. Is there anything you need me to fix?

**Comment by StreakyCobra** [comment]
I'm not used to `purescript` so I can't really test you PR, but it looks fine code-wise. Only TheBB or syl20bnr are allowed to merge PR for new packages, so I can't help more on this one :-)

**Comment by kRITZCREEK** [comment]
ahh allright I just saw that you added the label

**Comment by syl20bnr** [comment]
Nice project!
Thank you :+1: 
I changed `SPC m m t` for `SCP m h t` like in the other languages.
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by kRITZCREEK** [comment]
Thank you for the kind words :tada: :

**Pull request closed without merging**
