### PR TITLE
Add ability to **add** a layer in helm-spacemacs

### PR DESCRIPTION
**Pull request by CestDiego**
I've been introducing tons of people to Spacemacs, and most of them
always think that having to read documentation in how to add a layer is
too much.

I made this modification to make it easier to install layers.

Using Shift+Return...I'm hopeful there are other ways of doing this that are more pretty....I'm open to suggestions.

### CODE REVIEW

**Comment by nixmaniack** [comment]
I'm not entirely sure but in some terminals `S-RET` will be a problem as these combinations are generally  not detected ttys. Your previous binding of `<f2>`  would have been better.

**Comment by TheBB** [comment]
Will this work if the line looks like this?

`dotspacemacs-configuration-layers '(...)`

**Comment by CestDiego** [comment]
It will add a new line always ;_;

**Comment by TheBB** [comment]
Yeah that's fine, I'm just wondering if the new layer still ends up inside the parens in this case. :-P

**Comment by TheBB** [comment]
I could of course try it out but I'm lazy.

**Comment by CestDiego** [comment]
It will end up there. This could use some beautifying but oh well I'll try
to make a gif.

**Comment by CestDiego** [comment]
@TheBB here:

 [alt](http://i.imgur.com/ui5fpfN.gif)

That's how it looks

**Comment by StreakyCobra** [comment]
:joy: You should have been in a lack of inspiration to use the `bepo` one as demo :joy: :+1:

**Comment by CestDiego** [comment]
@StreakyCobra it was the first one I didn't had already installed I think

**Comment by syl20bnr** [comment]
Excellent :+1: 
I've been wanting this for a long time, seems to work fine.
Cherry-picked in develop branch, you can safely delete your branch.

**Pull request closed without merging**
