### PR TITLE
Fix readme for GUI only nyan-mode

### PR DESCRIPTION
**Pull request by NerdsvilleCEO**
README does not demonstrate how to dynamically show/hide nyanmode

### CODE REVIEW

**Comment by NerdsvilleCEO** [comment]
Is everything good here? :)

**Comment by robbyoconnor** [comment]
@NerdsvilleCEO I have PRs that have been sitting for over a year -- patience grasshopper.

**Comment by NerdsvilleCEO** [comment]
My apologies was just going through and cleaning my config and saw the readme snippet didn't work still, no rush was just checking in case it was forgotten :)

**Comment by robbyoconnor** [comment]
In almost all cases the list will be there already you'll just append it like: 

```(colors :variables
          colors-enable-nyan-cat-progress-bar (display-graphic-p))```

**Comment by NerdsvilleCEO** [comment]
I know. Thanks

**Comment by robbyoconnor** [comment]
@bmag, @d12frosted, @syl20bnr

**Comment by syl20bnr** [comment]
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
