### PR TITLE
Fix issue where both test modes are loaded in Ruby Layer

### PR DESCRIPTION
**Pull request by alexgirdler**
Fixes https://github.com/syl20bnr/spacemacs/pull/3761#issuecomment-166415910

### CODE REVIEW

**Comment by karmajunkie** [comment]
Fixed my problem from #3761 

Thanks!

**Comment by syl20bnr** [comment]
@alexgirdler I did not do this because I want `ruby-test-runner` to be able to be set as local file or directory variable (see documentation). Using `:if` keyword of use-package prevent from being able to do this.

Maybe the packages add themselves some hook we have to remove by hand ?

**Comment by alexgirdler** [comment]
@syl20bnr I was just going off what I saw in the [python layer](https://github.com/syl20bnr/spacemacs/blob/44d4525543b1f2a385142721d0cb16cd3b0be580/layers/%2Blang/python/packages.el#L97), I'm not an elisp(or lisp in general) programmer I've just been trying to contribute and help people so I wasn't entirely sure how `use-package` works but I knew that the python layer did work so I just copied it from there.

I do believe however that [rspec mode does add a hook for ruby modes](https://github.com/pezra/rspec-mode/blob/68c85ac4e0ed1817f68e7039d0ff87bc3b8d1688/rspec-mode.el#L820) although I'm not sure what to do to disable that.

Although would moving the `(when (eq 'rspec ruby-test-runnner) )` [line](https://github.com/syl20bnr/spacemacs/pull/4251/files#diff-a2dff97dda4ab7bcf6d47c892dec213cL153) to inside of the `(progn)` fix the issue?

**Comment by syl20bnr** [comment]
@alexgirdler 
Thank you for the PR 👍 
I finally looked into it and I think I nailed it thanks to the information you provide, see commit https://github.com/syl20bnr/spacemacs/commit/14c4b7e in develop branch.
Should fix the issue to I close the PR.

**Pull request closed without merging**
