### PR TITLE
Bind dotspacemacs-* variables to current values when protecting them in test

### PR DESCRIPTION
**Pull request by 15cm**
Fix https://github.com/syl20bnr/spacemacs/issues/15022.

### CODE REVIEW

**Comment by lebensterben** [comment]
the binding SPEC of let form is a list of:

(SYMBOL EXPR)

where a new variable named SYMBOL is bound to the return of EXPR.

If EXPR is omitted, SYMBOL gets value of nil.

Therefore this PR should be dismissed.

**Comment by 15cm** [comment]
The problem is: nil is not a valid value for `dotspacemacs-install-packages`. Binding it to nil causes this error as I explained in the issue https://github.com/syl20bnr/spacemacs/issues/15022.
```
condition-case: Variable: "dotspacemacs-install-packages" has value: "nil" that doesn’t match its type: "(choice (const used-only) (const used-but-keep-unused) (const all))". Validator message: "(user-error Looking for `(choice (const used-only) (const used-but-keep-unused) (const all))' in `nil' failed because:
  all of the options failed
    Looking for `(const used-only)' in `nil' failed because:
      not the expected value
    Looking for `(const used-but-keep-unused)' in `nil' failed because:
      not the expected value
    Looking for `(const all)' in `nil' failed because:
      not the expected value)"
```

The purpose of this PR is to still follow the comment to protect altering global variables but initialize the local variables with their current value. So we don't assume nil to be the default value of the global variables.

**Comment by 15cm** [comment]
To limit the scope of the PR, I change the commit to only fix the initialization of `dotspacemacs-install-packages`. PTAL at the updated commit https://github.com/15cm/spacemacs/commit/036784cc259bd339da246209fbb61c1311d85b5b. The PR doesn't reflect it probably because the PR has been closed.

**Comment by lebensterben** [comment]
I will investigate.

**Comment by 15cm** [comment]
Not a bug but IMO a better to have per discussion in https://github.com/syl20bnr/spacemacs/issues/15022#issuecomment-909771382.

**Comment by lebensterben** [comment]
The following variables are protected by shadowing in `dotspacemacs//test-dotspacemacs/layers`:
- `dotspacemacs-additional-packages`
- `dotspacemacs-configuration-layer-path`
- `dotspacemacs-configuration-layers`
- `dotspacemacs-excluded-packages`
- `dotspacemacs-install-packages`

---

# `dotspacemacs-additional-packages`

`dotspacemacs/sync-configuration-layers` ->
[`configuration-layer/load`](https://github.com/syl20bnr/spacemacs/blob/ed12b1118f1e6b3813dfc2a98536f2316524d0d4/core/core-dotspacemacs.el#L850) ->
[`configuration-layer/load`](https://github.com/syl20bnr/spacemacs/blob/ed12b1118f1e6b3813dfc2a98536f2316524d0d4/core/core-configuration-layer.el#L563) ->
[`configuration-layer//load`](https://github.com/syl20bnr/spacemacs/blob/ed12b1118f1e6b3813dfc2a98536f2316524d0d4/core/core-configuration-layer.el#L584) (appears in the first three branch of `cond`, but should go to the second one because of https://github.com/syl20bnr/spacemacs/blob/ed12b1118f1e6b3813dfc2a98536f2316524d0d4/core/core-dotspacemacs.el#L849) ->
[`configuration-layer//declare-used-packages`](https://github.com/syl20bnr/spacemacs/blob/ed12b1118f1e6b3813dfc2a98536f2316524d0d4/core/core-configuration-layer.el#L633) ->
[`configuration-layer/make-packages-from-dotfile`](https://github.com/syl20bnr/spacemacs/blob/ed12b1118f1e6b3813dfc2a98536f2316524d0d4/core/core-configuration-layer.el#L1675) which appends additional theme packages to `dotspacemacs-additional-packages`(https://github.com/syl20bnr/spacemacs/blob/ed12b1118f1e6b3813dfc2a98536f2316524d0d4/core/core-configuration-layer.el#L1237).

It's safe to set it to nil in test environment.

# `dotspacemacs-configuration-layer-path`

This is used more than once.

`dotspacemacs/sync-configuration-layers` ->
[`dotspacemacs/test-dotfile`](https://github.com/syl20bnr/spacemacs/blob/ed12b1118f1e6b3813dfc2a98536f2316524d0d4/core/core-dotspacemacs.el#L836) ->
[`configuration-layer/discover-layers`](https://github.com/syl20bnr/spacemacs/blob/ed12b1118f1e6b3813dfc2a98536f2316524d0d4/core/core-dotspacemacs.el#L1215)

`dotspacemacs/sync-configuration-layers` ->
[`configuration-layer/load`](https://github.com/syl20bnr/spacemacs/blob/ed12b1118f1e6b3813dfc2a98536f2316524d0d4/core/core-dotspacemacs.el#L850) ->
[`configuration-layer//load`](https://github.com/syl20bnr/spacemacs/blob/ed12b1118f1e6b3813dfc2a98536f2316524d0d4/core/core-configuration-layer.el#L593) ->
[`configuration-layer/discover-layers`](https://github.com/syl20bnr/spacemacs/blob/ed12b1118f1e6b3813dfc2a98536f2316524d0d4/core/core-configuration-layer.el#L631)

both funcall of `configuration-layer/discover-layers` uses
[`dotspacemacs-configuration-layer-path`](https://github.com/syl20bnr/spacemacs/blob/ed12b1118f1e6b3813dfc2a98536f2316524d0d4/core/core-configuration-layer.el#L1427)

It's safe to set it to nil in test environment.

**Pull request closed without merging**
