### PR TITLE
Add neo keyboard layout

### PR DESCRIPTION
**Pull request by benozol**
[Neo](https://www.neo-layout.org/) is an ergonomic keyboard layout, optimized for German.

The `'neo` option for the `keyboard-layout` layer basically maps the keys `hjkl` to `snrt`, which is the right home row under Neo, and applies a few fixes (mainly for `org-mode`).

(Please be careful, this is my first PR here and I have now previous experience with Emacs Lisp.)

### CODE REVIEW

**Comment by TheBB** [comment]
Thanks. Can you rebase this?

**Comment by benozol** [comment]
@TheBB Here we go…

**Comment by duianto** [comment]
The neo-layout image could probably be cropped, since the arrow keys and numpad seem to be unmodified. It could also be resized to a width of 640px, so that it matches the size of the other layout images (the image sizes were updated today on the develop branch).

Here's the cropped and resized image:

neo-layout

If your unsure how to replace the image, then I could make a PR with the changed image if/when this PR is merged.

**Comment by benozol** [comment]
Good idea, and thanks for the crop! I have update the PR

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
