### PR TITLE
haskell: Add all haskell-mode keybindings to haskell-literate-mode

### PR DESCRIPTION
**Pull request by codygman**
This actually isn't working. For some reason haskell/init-literate-haskell-mode isn't being called and I'm not sure why. The code is a simple copy of init-haskell-mode with small modifications for haskell-literate-mode.

Issue #3458 is related to this.

### CODE REVIEW

**Comment by d12frosted** [comment]
This is because `layer-name/init-package-name` is called for `package-name` in `layer-name`. Haskell literate mode is part of `haskell-mode` pckage. That's why all literate haskell key bindings should be configured in `haskell/init-haskell-mode` function.

**Comment by d12frosted** [comment]
What you might want to do is to copy some key bindings from `haskell-mode` to literate mode. Check the [key bindings](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/haskell/packages.el#L102) in `haskell-mode`.

**Comment by codygman** [comment]
@d12frosted Alright, that's what I did originally but figured it would be better to separate into a new function. Should have known that was wrong when it didn't work.

**Comment by d12frosted** [comment]
By the way, [here](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#within-a-layer) is some useful info about creating new layer in spacemacs. Not that you are creating one, but worth reading when you supporting / improving existing layers :smile: 

> Alright, that's what I did originally but figured it would be better to separate into a new function. Should have known that was wrong when it didn't work.

Yeah, it's a good idea to separate into different functions, but you copied the whole thing :smile: 

P. S. After you work on this PR is done (it's working and you thin it's ready to be merged / cherry picked) you should squash all commits into one, since it's simple improvement :smile:

**Comment by codygman** [comment]
@d12frosted Thanks for the help. I think I should add the literate-haskell keybindings to my own layer until they get into master. Is that how you recommend handling stuff like that?

**Comment by codygman** [comment]
@d12frosted Thanks again! I made a temporary layer to add those keybindings until these changes are merged with master.

**Comment by TheBB** [comment]
Thanks for this, but can you do something about the code duplication?

```lisp
(dolist (m '(haskell-mode literate-haskell-mode))
  (evil-leader/set-key-for-mode m
    ;; ....
    ))
```

**Comment by codygman** [comment]
Sure! I had a feeling something like that was possible.

**Comment by codygman** [comment]
Oops... pushed on accident. Have a small error and fixing it now.

**Comment by d12frosted** [comment]
@TheBB please, add haskell label here :smile:

**Comment by d12frosted** [comment]
Oh, it's PR !

**Comment by StreakyCobra** [comment]
Another improvement may be to extract `'(haskell-mode literate-haskell-mode)` to a variable and use this variable in the `dolist`

**Comment by d12frosted** [comment]
@codygman @StreakyCobra @TheBB any update on this pr?

**Comment by robbyoconnor** [comment]
You're going to need to rebase this @codygman ;) Also squash your commits.

**Comment by StreakyCobra** [comment]
When this will have been rebased/squashed and remarks would have been addressed, I think this one is a good candidate for merge :-)

**Comment by jb55** [comment]
I have a rebased version here: #4992

**Comment by syl20bnr** [comment]
@codygman Thank you for the PR and sorry for the late merge, I close this since it is superseded by #4992

**Pull request closed without merging**
