### PR TITLE
setup keybindings in haskell-debug-mode

### PR DESCRIPTION
**Pull request by d12frosted**
Following #6069 

Ideal solution is to evilify that buffer, but I'd leave it to someone who uses evil part of Spacemacs 😸

### CODE REVIEW

**Comment by d12frosted** [comment]
Ok, evilification is not hard, so I updated PR.

**Comment by TheBB** [comment]
The typography layer packages can also be considered for moving to prose.

**Comment by TheBB** [comment]
Ugh, wrong PR.

**Comment by user471** [comment]
Wouldn't it be better if you get keys directly from https://github.com/haskell/haskell-mode/blob/master/haskell-debug.el#L76 ? In this case it will automatically update if they add new keys.

**Comment by syl20bnr** [comment]
Thank you ! 👍 
I unified the key bindings in commit https://github.com/syl20bnr/spacemacs/commit/a1d60c0
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
