### PR TITLE
Add leader key for projectile-run-shell

### PR DESCRIPTION
**Pull request by eskimor**

### CODE REVIEW

**Comment by eskimor** [comment]
I just discovered there is also a projectile-run-term. Would projectile-run-term be better?

**Comment by d12frosted** [comment]
Hey, thanks you for your contribution 😸 

> Would projectile-run-term be better?

Not better, not worse :D Everyone uses whatever suits his / her needs. Also, there is `projectile-run-eshell`, which is also popular. 

So it would be nice to have keybindings for all of them. For example, under `SPC p x` (just like `C-c p x`) or `SPC p s` (consistent with `SPC a s`). With `t` for `term`, `s` for `shell` and `e` for `eshell`.

**Comment by eskimor** [comment]
That makes sense :-) On the other hand - it gets lengthy. Maybe in addition ps with a customize option for using one of the three?

**Comment by eskimor** [comment]
Added all shells as suggested. The customize thing does not really make sense, as you can equally well just add the binding your self in .spacemacs.

**Comment by d12frosted** [comment]
Hey, thanks for the update. Two comments:

1. You should also document these key bindings [here](https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#managing-projects). 
2. You [should](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org#ideally-for-simple-prs-most-of-them) squash your commits into one.

**Comment by eskimor** [comment]
Thank you! Is it ok now?

**Comment by d12frosted** [comment]
@eskimor ya, it's great. Thank you 💃

**Comment by syl20bnr** [comment]
Why not follow `SPC a s` prefix ?
- `SPC p s e`  for eshell
- `SPC p s i` for interactive shell
- `SPC p s T` for term

Would be ideal to provide also the missing `SPC p s m` (multiterm) and `SPC p s t` (ansi-term) :-)

**Comment by eskimor** [comment]
@syl20bnr for consistency with projectiles default key bindings: C-c p x [est]
also this way p s stays free, so one can map his/here preferred shell there. (I did that in my .spacemacs already)

**Comment by eskimor** [comment]
There is no projectile-run-multiterm nor run-ansi-term. Otherwise - why not ;-)

**Comment by d12frosted** [comment]
I am really bad at key bindings, so... @syl20bnr, @TheBB or @bmag could you share your thoughts?

**Comment by eskimor** [comment]
Closing, because it's stale.

**Pull request closed without merging**
