### PR TITLE
Feature/comint keybindings

### LINKED ISSUE #586: shell-mode C-j and C-k not working
in `*shell-mode*` (`SPC a s i`) and eshell (`SPC a s e`) `C-j` and `C-k` (which [should be](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#key-bindings-1) next and previous in history) do not work ( spacemacs 0.60.0 ). `C-j` goes down a line and `C-k` cycles up to `?` and then `^K` regardless of the history.

In addition `SPC m H` does not seem to work in `*eshell*` (it fails upon attempted insertion into the buffer.)

### PR DESCRIPTION
**Pull request by mijoharas**
Sets up `C-j` and `C-k` for comint mode, also fixes a typo that meant the `init-shell` function wasn't being called (thanks @tuhdo). Fixes #586.

### CODE REVIEW

**Comment by mijoharas** [comment]
Note, I only did this to fix `shell-mode` similar should be done for `term` and `multi-term` (I ran into some bugs and didn't have any more time to fix them).

**Comment by tuhdo** [comment]
`C-j` and `C-k` should be enabled when `dotspacemacs-editing-style` is equal to `'vim`. Emacs users will be annoyed by such key bindings.

**Comment by mijoharas** [comment]
good point @tuhdo (sorry, I need to think of the emacs-classic users more :worried: ). I'll push an update.

**Comment by mijoharas** [comment]
Aghhh... sorry, accidentally pushed a commit that was meant for a different branch, will fix.

**Comment by TheBB** [comment]
@syl20bnr I was looking through old issues and found this. @mijoharas can you please rebase?

**Comment by TheBB** [comment]
There are some modes that aren't derived from comint also which should be considered, eshell in particular.

**Comment by TheBB** [comment]
@mijoharas This PR is pretty old and has conflicts. Is it ok with you if I do a new version?

**Comment by mijoharas** [comment]
@TheBB, that sounds great. Sorry I've been meaning to rebase this but have been kinda busy with work and so haven't found the time. Thanks!

**Comment by TheBB** [comment]
Continued in #3794.

**Comment by syl20bnr** [comment]
Thank you for your work @mijoharas and sorry for not having merging this.

**Pull request closed without merging**
