### PR TITLE
use org-mime provided by melpa

### PR DESCRIPTION
**Pull request by amosbird**
discussed at https://github.com/org-mime/org-mime/issues/6

### CODE REVIEW

**Comment by nickanderson** [comment]
+1 org-mime stopped working for me in a recent package update. After applying this patch I had to restart emacs 2 times.

**Comment by jb55** [comment]
@TheBB <3

**Comment by jb55** [comment]
Related? https://github.com/syl20bnr/spacemacs/issues/9712

**Comment by everiori** [comment]
Tested

**Comment by syl20bnr** [comment]
Thank you ! 👍 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
