### PR TITLE
Unset unneeded scroll-margin in some modes

### PR DESCRIPTION
**Pull request by darkfeline**
Fixes https://github.com/syl20bnr/spacemacs/issues/3098

### CODE REVIEW

**Comment by joehillen** [comment]
:+1:

**Comment by person808** [comment]
Its probably better to make a small function and use that in the hooks. I think spacemacs also provides some macros like `spacemacs/add-to-hooks` to add a function to multiple hooks.

**Comment by darkfeline** [comment]
Using `spacemacs/add-to-hooks` now.  I don't see a reason to make a named function for this though.

**Comment by joehillen** [comment]
@darkfeline I suspect it's a convention to make the code self documenting. For examples https://github.com/syl20bnr/spacemacs/commit/bb80e94d384a1d9a60f4fd6e58ded2f64836afd4 Also other modes might want to use it, for example I want to add it to the haskell repl.

**Comment by TheBB** [comment]
It's also easier to remove from hooks named functions than lambdas.

**Comment by joehillen** [comment]
This looks ready to be merged. :rocket:

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
