### PR TITLE
Add yatemplate package to Auto-completion layer

### PR DESCRIPTION
**Pull request by YasuharuIida**
- yatemplate provides insertion template automatically (It's template like yasnippet's snippet)

### CODE REVIEW

**Comment by TheBB** [comment]
Thanks :-)

Fixes https://github.com/syl20bnr/spacemacs/issues/6304

**Comment by YasuharuIida** [comment]
Why isn't this PR merged yet?

**Comment by YasuharuIida** [comment]
Update README.

**Comment by YasuharuIida** [comment]
candidate of template directory
- ~/.emacs.d/private/templates
- ~/.emacs.d/private/snippets
- other directory

Which is desirable?

**Comment by TheBB** [comment]
The repository is unknown so I opened https://github.com/syl20bnr/spacemacs/pull/6893 with my suggestions.

**Pull request closed without merging**
