### PR TITLE
Ignore rake.cache in the repository

### PR DESCRIPTION
**Pull request by asok**
The file is used by package [rake](https://github.com/asok/rake)

### CODE REVIEW

**Comment by TheBB** [comment]
https://github.com/asok/rake/blob/master/rake.el#L61-L65

Can you configure rake to place it in Spacemacs' cache directory instead?

**Comment by asok** [comment]
I could. But I would need to handle two cases - when someone is using spacemacs and when someone is not using spacemacs.
I guess that the userbase of the `rake` package in majority are people who don't use spacemacs.

**Comment by TheBB** [comment]
You misunderstand. Instead of changing gitignore, instead have Spacemacs change the value of `rake-cache-file` to live in .emacs.d/.cache instead. We do it with all the other cache-type files so we might as well do it with this one too.

**Comment by TheBB** [comment]
Or to be blunt: please turn this PR into something that `(setq rake-cache-file ...)`.

**Comment by asok** [comment]
> Or to be blunt: please turn this PR into something that (setq rake-cache-file ...)

Thanks. Indeed this looks much better.

I've updated the PR. I've added the `rake` package to the ruby layer.  The package was already included in `ruby-on-rails` layer (via the dependency on `projectile-rails` package). But for me it makes sense to have a rake runner for every ruby project since it's so omnipresent.

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
