### PR TITLE
Fix/delete dead references to HOWTOs.org file

### LINKED ISSUE #4853: HOWTOs pages doesn't exists anymore
`http://spacemacs.org/doc/HOWTOs.html` doesn't exist and was referenced in [here](http://spacemacs.org/doc/QUICK_START.html#orgheadline2)

### PR DESCRIPTION
**Pull request by balajisivaraman**
Fixes #4853

### CODE REVIEW

**Comment by StreakyCobra** [comment]
Nice PR, as usual :wink: :+1: Thx

**Comment by robbyoconnor** [comment]
:heart: :heart_eyes_cat:

**Comment by balajisivaraman** [comment]
Thanks guys! :smile: 

This also fixes #4378, which is an older duplicate issue raised about a month back.

**Comment by robbyoconnor** [comment]
@balajisivaraman documentation is just as important as the code

**Comment by syl20bnr** [comment]
Nice :purple_heart: 
Thank you :+1: 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
