### PR TITLE
Fixes #5644 - [go] Use flycheck-gometalinter

### LINKED ISSUE #5644: Provide an alternative linter for the go layer
We can add an alternative to the default Spacemacs go linter [Flycheck checker for golang using gometalinter](https://github.com/favadi/flycheck-gometalinter)  But not sure how it performs - it might be too heavy for a complete replacement.

### PR DESCRIPTION
**Pull request by swaroopch**
See https://github.com/alecthomas/gometalinter for go package.

See https://github.com/favadi/flycheck-gometalinter for emacs package.

### CODE REVIEW

**Comment by StreakyCobra** [comment]
@bogdanteleaga Need some go testing here :smiley:

**Comment by swaroopch** [comment]
Had to switch from use-package's `:defer t` to `:ensure t` and only then `SPC e v` would show the gometalinter package...

**Comment by bogdanteleaga** [comment]
So this does seem to work to some extent. I can see some gocyclo errors popping up.

However I have a few questions/suggestions:
1. I'd really like this to define either some sort of variable to toggle it on/off, or to choose which linters to enable. It would probably be too slow to run *everything* on big projects.
2. Do we even need any other flycheck linters here? It looks like we could disable all of the other ones besides this one.

Overall, I do like it, looks promising.

**Comment by swaroopch** [comment]
@bogdanteleaga 

1. Regarding toggling linters, please see https://github.com/favadi/flycheck-gometalinter#configuration - perhaps we should mention that in the documentation?

2. My understanding is that gometalinter doesn't include `go build` output which the built-in flychecker would do? Please correct me if I'm wrong.

**Comment by bogdanteleaga** [comment]
1. Yes, include docs for that.
People can just toggle those using :variables(it works as a setq), or just do it in their config function.

2. If you go in a go file with flycheck enabled and use `SPC e v`, you'll see there are already some linters enabled. What I was afraid of is that the metalinter would also run some of these and maybe do it twice, so I'm guessing there's 2 steps here:
  - figure out if they do run twice or not
  - if they do, try to disable any duplicates

**Comment by swaroopch** [comment]
@bogdanteleaga 

1. I've added docs for the same

2. I found these duplicate linters - go-golint, go-vet, go-errcheck

However, I have difficulty in disabling them. Inspired by https://github.com/flycheck/flycheck/issues/269#issuecomment-30507074 I tried this:

```elisp
(defun go/init-flycheck-gometalinter ()
  (use-package flycheck-gometalinter
    :if (configuration-layer/package-usedp 'flycheck)
    :ensure t
    :config
    (progn
      (flycheck-gometalinter-setup)
      ;; To prevent duplicate checkers running through both flycheck and gometalinter
      ;; See http://www.flycheck.org/manual/latest/Supported-languages.html#Go
      ;; and https://github.com/alecthomas/gometalinter#supported-linters
      (add-hook 'go-mode-hook
                (lambda ()
                  (setq flycheck-disabled-checkers '(go-golint go-vet go-errcheck)))))))
```

But those linters are still enabled.

Any advice is most welcome.

**Comment by skyjia** [comment]
+1

**Comment by JAremko** [comment]
| Default     | gometalinter    |
|-------------|-----------------|
| go-gofmt    |                 |
| go-golint   | golint          |
| go-vet      | go vet          |
| go-build    |                 |
| go-test     |                 |
| go-errcheck | errcheck        |
|             | go vet --shadow |
|             | gotype          |
|             | deadcode        |
|             | gocyclo         |
|             | varcheck        |
|             | structcheck     |
|             | aligncheck      |
|             | dupl            |
|             | ineffassign     |
|             | interfacer      |
|             | unconvert       |
|             | goconst         |
|             | gosimple        |

gometalinter disabled `testify`, `test`, `gofmt -s `, `goimports`, `lll`

**Comment by JAremko** [comment]
I propose:
 - add variable `go-use-gometalinter` - if not `nil` disables the overlapping build-in flycheck checkers and loads the `flycheck-gometalinter` package.

**Comment by JAremko** [comment]
For example the [TS layer uses extra optional linters.](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/typescript/packages.el#L39)

**Comment by syl20bnr** [comment]
Why not base the choice on the presence of the gometalinter on the system ?

I guess that if the user has gometalinter then they want to use it since it should be more efficient.

**Comment by JAremko** [comment]
@syl20bnr   Good idea. But how about providing a variable `go-disable-gometalinter` and `go-gometalinter-only-fast` ? 
 -  Someone might want to disable it while running a lot of file watchers.  Like sass,ts compilers, tests etc.  If you add a heavy linter on top of it...  Might be too much for a laptop :confused:   
 - If someone has gometalinter on the system for some other IDE or to run from a shell, I think it's kinda overkill to make the person remove gometalinter form the system if it's just too slow it the particular setup.

**Comment by JAremko** [comment]
Alright. Gonna do it myself.

**Comment by syl20bnr** [comment]
@swaroopch Thank you for the PR and sorry for the long wait. I close it in favor of #5759

**Pull request closed without merging**
