### PR TITLE
Update git bindings. Make use of popup.

### PR DESCRIPTION
**Pull request by ralesi**
Popup bindings for magit are much better for entry into magit.

### CODE REVIEW

**Comment by StreakyCobra** [comment]
:+1: agreed

**Comment by geksilla** [comment]
@StreakyCobra, @ralesi <kbd>SPC g d</kbd> keybinding will cause conflicts with [version-control](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bsource-control/version-control) package.

**Comment by StreakyCobra** [comment]
@geksilla As @ralesi is working on a rewrite of `version-control` in #3632, he probably has handled it :-)

**Comment by geksilla** [comment]
Oh, ok. Sorry, didn't saw that PR.

**Comment by robbyoconnor** [comment]
:heart:

**Comment by ralesi** [comment]
This should work seamless with the vcs microstate,  let me know if you see issues.

**Comment by syl20bnr** [comment]
Very nice PR :purple_heart: 
Thank you !
I added the required autoload for popup functions and also moved stage/unstage bindings to `SPC g S` and `SPC g U`. I was not really fond of `w` for staging. Se commits https://github.com/syl20bnr/spacemacs/commit/74bc25c and https://github.com/syl20bnr/spacemacs/commit/22cba50
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
