### PR TITLE
Fix broken alignment commands

### PR DESCRIPTION
**Pull request by justbur**
Saw someone in the gitter room had trouble with this

### CODE REVIEW

**Comment by TheBB** [comment]
Thanks... how did this sneak through... :-P

**Comment by justbur** [comment]
:-) No idea. I was proud of those damn it

**Comment by cpaulik** [comment]
Does `spacemacs/align-repeat-decimal` work for you? It does nothing for me on e.g.

```
1.2.3.4
one.two.three.four
```

whereas `SPC x a r \.` works as expected

**Comment by justbur** [comment]
@cpaulik that command is to align decimal numbers

**Comment by justbur** [comment]
@cpaulik Try this for example

```elisp
1.2 3 4.99
4.99 3. 12.
```

**Comment by cpaulik** [comment]
@justbur Ahh I see. 

Should we change the keybinding for this to maybe `SPC x a d` and use `SPC x a .` for the usage I thought it was? This would be consistent with the use of all the other align commands.

**Comment by justbur** [comment]
@cpaulik I don't have a problem with that

**Pull request closed without merging**
