### PR TITLE
Remove trailing whitespace (again)

### PR DESCRIPTION
**Pull request by robbyoconnor**
This snuck in -- please type `SPC x d w` to prevent this!

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@syl20bnr, @bmag, @ThEBB, @d12frosted

**Comment by robbyoconnor** [comment]
CI failing isn't my fault.

**Comment by JAremko** [comment]
@robbyoconnor  hmm 24.5 keep on failing but 24.4 works.

**Comment by JAremko** [comment]
@deb0ch  :roll_eyes:

**Comment by robbyoconnor** [comment]
Again not my problem -- I literally changed org/markdown files

**Comment by JAremko** [comment]
@deb0ch  :eyes:

**Comment by robbyoconnor** [comment]
I use emacs 26

**Comment by JAremko** [comment]
This https://github.com/syl20bnr/spacemacs/commit/62167f708d0d244ca98fe9e578f32b13434ca0c4 might be the reason.

**Comment by deb0ch** [comment]
@JAremko I didn't really work on the subject, just reported a bug the the `html-export` repo (forgot the name) and the guy considered it "not a bug".

Here it is: https://github.com/snosov1/toc-org/issues/35

**Comment by deb0ch** [comment]
Oh, I also reported an issue in Spacemacs concerning org tags showing in the docs: https://github.com/syl20bnr/spacemacs/issues/8216

**Comment by smile13241324** [comment]
ups sorry didn't notice that, sorry for the inconvenience. Was my test killing the CI builds?

**Comment by JAremko** [comment]
@smile13241324  I looks like the publishing function doesn't like https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org and only with emacs 24.5  :thinking:

**Comment by smile13241324** [comment]
Sounds interesting, I'll have a look this evening.

**Comment by JAremko** [comment]
@smile13241324  I think I'll move doc test into separate test suite.  It takes too long and even package installation process is too verbose +  there is no reason to export all files and do it for each commit and each Emacs version.

**Comment by smile13241324** [comment]
@JAremko you may be right, that test is actually not reliable enough if this fails randomly on certain emacs versions. Do we have a place to store tests we want to run once in a while but not for each and every commit?

**Comment by JAremko** [comment]
@smile13241324  My current solution https://github.com/syl20bnr/spacemacs/pull/8736 also I'll try to make URL check work if possible (by retrieving only http headers)

**Comment by smile13241324** [comment]
@JAremko I like your solution, this would still run the doc tests for every commit but we avoid those random problems with older emacs versions. Having emacs only retrieve the http headers would be very interesting, I have also tried to get that running but did not find a good elisp function to do so.

**Comment by JAremko** [comment]
@smile13241324  We probably can exclude this test if no *.ORG files have changed. If it will run too long (in comparison to other tests)

**Comment by JAremko** [comment]
Apparently Emacs 24.5 can't work without `CUSTOM_ID` but earlier versions and later ones are ok. I'll try to fix it. Also given how random it is, we probably need to run export test with all versions :smile:

**Comment by robbyoconnor** [comment]
Can we move this discussion elsewhere? Thanks!

**Comment by JAremko** [comment]
@robbyoconnor  discussion is over. We won :shipit:

**Comment by syl20bnr** [comment]
Thank you ! :-D
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
