### PR TITLE
Adding keybinding to jump to currently open file in neotree

### PR DESCRIPTION
**Pull request by arjunurs**
Adding a keybinding to jump to the currently open file in neotree. The existing shortcut `SPC f t` requires toggling neotree to jump to current file.

### CODE REVIEW

**Comment by bmag** [comment]
Thanks for suggesting this key binding. However, I think `fn` isn't a good mnemonic. I assume `n` is for "neotree", but that's in contrast to `ft` which stands for "tree" (I think), so it will be awkward to have use `n` for "neotree" when there's another key binding that also uses neotree. I prefer to use `fT` (for "tree", because it's a variant of opening a file tree), despite it being harder to reach. What do you think?

**Comment by arjunurs** [comment]
@bmag Sounds good to me

**Comment by bmag** [comment]
Thank you :+1: Squashed and cherry-picked into develop, you can safely delete your branch.

**Comment by syl20bnr** [comment]
Nice and perfect choice of key bindings as capital letter often means to change focus to the other window involved in the action 💜

**Pull request closed without merging**
