### PR TITLE
PHP mode improvements

### PR DESCRIPTION
**Pull request by kostajh**
Hi @syl20bnr,

In this PR, I've basically moved over most of my PHP configuration from my private config layer to the PHP one. I've added most of the major PHP packages from MELPA.org. I also did some basic configuration so that php-mode works with the new auto-completion layer.

I'm sure this could be improved, so marking as `[WIP]` but let me know what you think.

### CODE REVIEW

**Comment by kostajh** [comment]
After #1143 is merged, I'll remove the `helm-gtags` and `ggtags` packages from this PR.

**Comment by kostajh** [comment]
@syl20bnr OK, I think this is ready for your review. Is there a way to add a dependency for the `gtags` layer with this? That would be nice.

**Comment by syl20bnr** [comment]
Yes, I will update this review when #1143 is merged to tell you how to do
it.

-syl20bnr-

**Comment by syl20bnr** [comment]
Great :+1: 
I refactored it a bit to use post-init functions (which are run only if a corresponding init function is found, so it play nicely if someone exclude a package). Related commits:
- ff8b339813526827f9b6e9573ec8537d90361021
- ad06363b399b86290fc931654fe3f82e1894da09

Thank you !
Cherry-picked into `develop` branch, you can safely delete your branch.

**Comment by kostajh** [comment]
Hi @syl20bnr,

Thanks for merging this and making the changes, but there are some issues now. When I start up Emacs, I get this error:

`An error occurred while initializing ggtags (error: (wrong-type-argument symbolp ((lambda nil (set (make-local-variable (quote eldoc-documentation-function)) (function ggtags-eldoc-function))) eldoc-mode drupal-mode-bootstrap flycheck-mode spacemacs//init-company-php-mode company-mode)))`

Any ideas on how to fix?

**Pull request closed without merging**
