### PR TITLE
[bot] Auto-update

### PR DESCRIPTION
**Pull request by emacspace**
Merge with care - I'm just a stupid bot. Beep boop.

### CODE REVIEW

**Comment by JAremko** [comment]
@duianto  @smile13241324  looks like latest version of some built-in libraries aren't compatible with Spacemacs. We need to figure out which ones. :thinking: 

This list handles auto update https://github.com/syl20bnr/spacemacs/blob/develop/.ci/built_in_manifest

Worst case scenario, we can apply custom patch after each auto-update.

**Comment by smile13241324** [comment]
Jup, lets see why they are not compatible maybe we can change our side to be working with their main branch or at least factor out the spacemacs specific changes....

**Comment by duianto** [comment]
There seems to only be an issue in Windows 10, with: `core/libs/load-env-vars.el`
It's fine in Manjaro.

#### Cause
The upstream function:
https://github.com/diasjorge/emacs-load-env-vars/blob/3808520efaf9492033f6e11a9bffd68eabf02a0f/load-env-vars.el#L74
```elisp
(defun load-env-vars-set-env (env-vars)
  "Set envariable variables from key value lists from ENV-VARS."
  (dolist (element env-vars)
    (let ((key (car element)) (value (cadr element)))
      (setenv key value))))
```

Was modified in this PR:
[[core] Environment variable caching fixes by Miciah #12417](https://github.com/syl20bnr/spacemacs/pull/12417)

https://github.com/syl20bnr/spacemacs/blob/bd1631bdce8625f4f56efc10c4bf342e60080e0e/core/libs/load-env-vars.el#L77-L94

With the upstream function, in Windows 10.
When I try to update the packages, then it shows:
>condition-case: Failed to checkout ‘font-lock+’: ‘Command ’(c:/tools/cygwin/bin/timeout.exe -k 60 600 git remote show -n origin)’ exited with non-zero status 127: /usr/bin/timeout: failed to run command 'git': No such file or directory

**Comment by JAremko** [comment]
```
 FAILED  test-declare-layers--base-layer-is-third-for-base-distribution
 FAILED  test-declare-layers--bootstrap-layer-always-first
 FAILED  test-declare-layers--defaults-layer-is-second-for-base-distribution
```

I doubt that it's env related. Could be ht.el :thinking:

**Comment by JAremko** [comment]
I'll update packages one by one and see when tests break.

**Comment by JAremko** [comment]
Seems like it's `mocker.el` so I exclude it and env thingy from the auto-update list and we'll see if it works.

**Comment by JAremko** [comment]
Looks like it helped.

But now we have 2 problems: 

- windows-latest/snapshot seems to fail now - it's not that bad since we don't guarantee that Spacemacs works with  snapshot builds.  But it would be helpful if we can figure out what's broken and report it upstream.

- We need to figure out what's up with the mocker.  It doesn't look that different https://www.diffchecker.com/4wBnjYbZ but those 3 tests  are failing with the latest version :thinking:

**Comment by JAremko** [comment]
Ok mocker should work now https://github.com/syl20bnr/spacemacs/pull/14280

**Comment by JAremko** [comment]
@TheBB  Looks like Evil might have compatibility issue with the Emacs snapshots (on windows for some reason)

(define-obsolete-function-alias 'evil-ex-shell-command-completion-at-point 'comint-completion-at-point)  


``` elisp
 #f(compiled-function (obsolete-name current-name when &optional docstring) "Set OBSOLETE-NAME's function definition to CURRENT-NAME and mark it obsolete.\n\n(define-obsolete-function-alias \\='old-fun \\='new-fun \"22.1\" \"old-fun's doc.\")\n\nis equivalent to the following two lines of code:\n\n(defalias \\='old-fun \\='new-fun \"old-fun's doc.\")\n(make-obsolete \\='old-fun \\='new-fun \"22.1\")\n\nWHEN should be a string indicating when the function was first\nmade obsolete, for example a date or a release number.\n\nSee the docstrings of `defalias' and `make-obsolete' for more details." #<bytecode -0xc3f2ab0a40cd5b1>)('evil-ex-shell-command-completion-at-point 'comint-completion-at-point)
  (define-obsolete-function-alias 'evil-ex-shell-command-completion-at-point 'comint-completion-at-point)
  eval-buffer(#<buffer  *load*-480978> nil "c:/Users/runneradmin/.emacs.d/elpa/28.0/evil-20201..." nil t)  ; Reading at buffer position 22912
  load-with-code-conversion("c:/Users/runneradmin/.emacs.d/elpa/28.0/evil-20201..." "c:/Users/runneradmin/.emacs.d/elpa/28.0/evil-20201..." nil t)
```

`(define-obsolete-function-alias 'evil-ex-shell-command-completion-at-point 'comint-completion-at-point)` is a suspect.

We had similar issue with another package  https://github.com/syl20bnr/spacemacs/pull/14262/files#diff-675c7e805802d3c8c184084adac902fa2bc0aa22ca4309a5e81786bfbbebbe59R109

**Comment by robbyoconnor** [comment]
Snapshot has been failing for a while for me

**Comment by smile13241324** [comment]
Is a failing snapshot build really an issue for us? We cannot guarantee that Spacemacs works on any of them anyway. In my opinion we should only worry about supporting finished releases.

Can I help with this ticket or do you want to run some more integration tests against it @JAremko?

**Comment by JAremko** [comment]
@smile13241324  Snapshot tests are optional :+1:

**Comment by JAremko** [comment]
Also tests seems to fix themselves.  Most likely someone realized that it's pretty stupid to break Emacs install for making last argument to obsolete annotation allays required

**Comment by robbyoconnor** [comment]
This scares me -- how is this happening?

**Comment by robbyoconnor** [comment]
> Is a failing snapshot build really an issue for us? We cannot guarantee that Spacemacs works on any of them anyway. In my opinion we should only worry about supporting finished releases.

@smile13241324 -- I never ever expect spacemacs to always work on Emacs Snapshot -- things break and I usually expect it from time to time -- I am after all using unreleased software that is built from the repository itself.

**Comment by JAremko** [comment]
> This scares me -- how is this happening?

Well.. I can make an uneducated guess that Windows snapshot got built with different flags or something that caused  this. I don't think it was intended behavior.

**Comment by JAremko** [comment]
Actually it seems to be fixed in the package https://github.com/emacs-evil/evil/commit/19cc5f8eef8bfffdec8082b604c7129782acb332  a while ago.  I guess we got the new version only now :thinking:

**Comment by robbyoconnor** [comment]
> Well.. I can make an uneducated guess that Windows snapshot got built with different flags or something that caused this. I don't think it was intended behavior.

@JAremko I never used Emacs on windows lol -- I've used Mint for as long as I've been using emacs.

**Pull request merged**
