### PR TITLE
Add location contrib layer

### PR DESCRIPTION
**Pull request by usharf**
Playing around with a "location" layer. Currently supporting automatic theme changer, sunshine weather forecasts, and optionally, support for OS X's CoreLocation service (which helps with with the previous modes, but just strictly necessary.)

Could not figure out how to introduce geolocation support on Linux, other than some hacks I saw, which are based on accessing the internet.

### CODE REVIEW

**Comment by tko** [comment]
@usharf on Linux I believe [GeoClue](http://freedesktop.org/wiki/Software/GeoClue/) is the thing to use. (I only know the name, sorry.)

**Comment by usharf** [comment]
@tko right, I now remember it is used bt Redshift in fact. Will look into that.
Thanks

**Comment by syl20bnr** [comment]
@usharf Thank you ! :+1: 
I renamed the layer `geolocation` to be more explicit as well as the layer variables etc... see commit https://github.com/syl20bnr/spacemacs/commit/234cb96
But there is not much that works on this layer for now:
- I get the error you got a few years ago: https://github.com/hadronzoo/theme-changer/issues/5 What can we do about it ?
- The weather service asks for credentials, can you add this to the README ?
- Do you think you'll be able to add some info for GeoClue ?
Thank you again :-)

Cherry-picked into develop branch, you can safely delete your branch.

**Comment by usharf** [comment]
Wow. Forgot about this layer. I will look (first time I've seen an authentication request for the geo API).

**Comment by usharf** [comment]
@syl20bnr is "extensions.el" still used? I'm having problems with execution precedence on the post hook.

If I have something like `(setq geolocation-post-extensions '(change-theme))` in extensions.el, shouldn't `geolocation/init-change-theme` only be executed after "all" the package hooks in `packages.el`?

**Comment by usharf** [comment]
@syl20bnr  sent an new PR for a re-write, breaking the osx-location functionality out into to the OS X layer.

**Pull request closed without merging**
