### PR TITLE
Ivy: Add keybinding for counsel-minibuffer-history

### PR DESCRIPTION
**Pull request by et2010**
Currently, the function bound to C-r is `helm-minibuffer-history` even if ivy layer is chosen.

### CODE REVIEW

**Comment by sdwolfz** [comment]
@et2010 can you please provide some reproduction steps? I have a hard time figuring out how to check this.

**Comment by et2010** [comment]
Sorry about that! You can check this by following steps:

1. Enable Ivy layer
2. Enter elisp evaluation buffer by `M-:`
3. Enter minibuffer history by `C-r`, without this commit, it would be `helm-minibuffer-history`.

**Comment by sdwolfz** [comment]
I am unable to reproduce this problem, tried enabling ivy in my setup and `C-r` is bound correctly. I also took a look at your dotspacemacs repositroy and tied the setup you have there, with both master and develop branches, still no problem. Also tried enabling helm and ivy at the same time and everything works.

What I suggest is you nuke your `~/.emacs.d` and clone spacemacs again to see if the problem persists.

**Comment by et2010** [comment]
That's weird. I nuked my elpa directory and .spacemacs file, reinstalled all packages from scratch. The problem still persists.

I'm on develop branch. The layers I enabled are:
```
   dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press `SPC f e R' (Vim style) or
     ;; `M-m f e R' (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     ivy
     (auto-completion :disable-for org)
     better-defaults
     bibtex
     emacs-lisp
     git
     markdown
     org
     pdf-tools
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
     (spell-checking :variables spell-checking-enable-by-default nil)
     syntax-checking
     (version-control :variables git-gutter+-disable-modes '(image-mode org-mode))
     )
```
No other customization was made.


image

**Comment by sdwolfz** [comment]
Still not able to reproduce the issue, not even with the setup from your last post.

What emacs version do you have? Maybe it's related to that... (I'm on emacs 27, master branch built from source).

**Comment by et2010** [comment]
I'm on emacs 25.3.2, binary version installed from a ppa

```
http://ppa.launchpad.net/kelleyk/emacs/ubuntu xenial main
```

**Comment by sdwolfz** [comment]
You might want to try out a newer version of emacs, 26 should be released today, if this commit is to be trusted: https://github.com/emacs-mirror/emacs/commit/5cec2b03ef9f3fd7a5f9fc156fabbf3b335486c5. Otherwise you'll need to install emacs from source.

I'll try to reproduce with your version.

**Comment by Compro-Prasad** [comment]
@et2010 I don't even get the completion list. Emacs completes everything in place and I have to repeatedly press `C-r` to cycle through history in `M-:` when I have helm enabled. What is the case for @sdwolfz ? Do you get helm completion? Tried with `M-!` and it also completes in place.

**Comment by et2010** [comment]
@sdwolfz I switched to emacs 26.1 and the issue is gone! Thanks for your help. I'm closing this.

**Comment by sdwolfz** [comment]
@et2010 @Compro-Prasad I did not have time to do anything related to this issue, and i'm a bit busy in the next few days, but since Spacemacs still supports emacs 25 this issue is still valid.

I'll look into it more when I have the time. Reopening so I don't forget.

**Comment by sdwolfz** [comment]
Thank you :heart:!

I went ahead and merged this as is since it was an incremental improvement, sorry for keeping it open for so long.

Cherry-picked into develop branch, you can safely delete your branch.

**Pull request merged**
