### PR TITLE
new sr-speedbar layer for !tools

### PR DESCRIPTION
**Pull request by BlinkD**
cause `spacemacs` already include `neotree`, so i leave the function `spacemacs/sr-speedbar-show-or-hide` for users' to binding.

### CODE REVIEW

**Comment by BlinkD** [comment]
sr-speedbar

**Comment by robbyoconnor** [comment]
Squash all these commits into one tidy commit

**Comment by robbyoconnor** [comment]
*bump*

**Comment by CarlQLange** [comment]
God I want this, can it please be merged?

**Comment by robbyoconnor** [comment]
@BlinkD -- rebase and squash this...

**Comment by CarlQLange** [comment]
I'll probably add some evil bindings in a few days as I use it more often. @BlinkD if you're not around anymore I can take care of this for you

**Comment by robbyoconnor** [comment]
Yeah needs to be rebased and add some keybindings. The fact this was not done is beyond me. Also the fact this hasn't been touched and @BlinkD has gone AWOL...have at it @CarlQLange

**Comment by edrex** [comment]
sr-speedbar windows get replicated geometrically (1 -> 2 -> 4 ...) whenever the helm window comes up. https://github.com/syl20bnr/spacemacs/issues/29#issuecomment-61594911

**Comment by edrex** [comment]
Maybe add `(setq speedbar-show-unknown-files t)` to show non-code files, as @tuhdo suggested (https://github.com/syl20bnr/spacemacs/issues/29#issuecomment-61592275)

**Comment by CarlQLange** [comment]
> sr-speedbar windows get replicated geometrically (1 -> 2 -> 4 ...) whenever the helm window comes up. #29 (comment)

I haven't seen this.

By the way, just running `(evilify)` seems to be enough to add suitable vim bindings.

**Comment by edrex** [comment]
This consistently reproduces for me (may depend on frame size):

 - launch emacs
 - from spacemacs buffer, `SPC : sr-speedbar-toggle`, now there's one speedbar window
 - `SPC` - now there are two speedbar windows - `ESC`
 - `SPC` - now there are four

**Comment by edrex** [comment]
I realized that I hadn't actually enabled the sr-speedbar layer. The included `post-init` function fixes the cloning issue I was seeing.

Suggestion: add `(setq speedbar-show-unknown-files t)`, since otherwise speedbar only shows files for which it has semantic information (list, c, etc).

It seems like this is a good candidate for replacing NeoTree.

**Comment by edrex** [comment]
Spoke too soon: I'm still seeing the cloning issue.

This consistently reproduces for me (may depend on frame size):

launch emacs
from spacemacs buffer, SPC : sr-speedbar-toggle, now there's one speedbar window
SPC - now there are two speedbar windows - ESC
SPC - now there are four

**Comment by CarlQLange** [comment]
I still can't reproduce that at all @edrex. However, it does seem like `golden-ratio` mode will make strange things happen...

**Comment by edrex** [comment]
I don't have golden ratio toggled on. It may be a platform specific thing (I'm on a mac), or a difference in our emacs configuration/spacemacs layers. I'm pretty new so my config is close to stock. At least one other person, @syl20bnr, reported experiencing the issue. For me it happens quite a lot (but seems slightly nondeterministic).

**Comment by CarlQLange** [comment]
want to try and include a video of it? and are you using `(spacemacs/sr-speedbar-show-or-hide)`?

**Comment by edrex** [comment]
Oh, I had been using `(sr-speedbar-toggle)`. `(sr-speedbar-show-or-hide)` is behaving better with Helm. 

So yeah.. other than the keybindings, seems good.

**Comment by CarlQLange** [comment]
nice one.

**Comment by CarlQLange** [comment]
OK, since I can't change where this PR is coming from, there's a new one here: #3224
this one can be closed.

**Comment by TheBB** [comment]
Closing this in favour of #3559.

**Pull request closed without merging**
