### PR TITLE
[WIP] Doc: support all link styles

### LINKED ISSUE #4399: Broken links in some .org files
The TOC links in the following files are broken (404):

* https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org
* https://github.com/syl20bnr/spacemacs/blob/master/doc/FAQ.org
* https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.org
* https://github.com/syl20bnr/spacemacs/blob/master/doc/LAYERS.org
* https://github.com/syl20bnr/spacemacs/blob/master/doc/QUICK_START.org
* https://github.com/syl20bnr/spacemacs/blob/master/doc/VIMUSERS.org
* https://github.com/syl20bnr/spacemacs/blob/master/layers/LAYERS.org
* layers/**/README.org (I haven't tried all of them)

I think the broken links were introduced in 13c5b1d (Nov 2, 2015).

PS: the TOC links in https://github.com/syl20bnr/spacemacs/blob/master/CONTRIBUTING.org are not broken.

-----
**Update:** Not only TOC links, but most (if not all) internal links.

### PR DESCRIPTION
**Pull request by TheBB**
Patience. :-)

Will fix #4399. Hopefully.

### CODE REVIEW

**Comment by JAremko** [comment]
@TheBB  What kind of problem do you have?

**Comment by jb55** [comment]
I just got directed to here from [codetriage](http://www.codetriage.com/syl20bnr/spacemacs) anything left to do?

**Comment by TheBB** [comment]
I need to think more about this.

**Comment by JAremko** [comment]
@TheBB  I  think I know how to make the dream come true and not go absolutely crazy  :smile_cat:

**Comment by TheBB** [comment]
I'd love to see a small example. :+1:

**Pull request closed without merging**
