### PR TITLE
Refactor `spacemacs/open-in-external-app`

### PR DESCRIPTION
**Pull request by bixuanzju**
New interactive function`spacsmacs/open-file-or-directory-in-external-app`, depending on the
value of prefix argument, it opens the current file or directory in external app.

### CODE REVIEW

**Comment by TheBB** [comment]
Fixes #6766

**Comment by pkkm** [comment]
There seems to be a typo: `spacemacs` is spelled as `spacsmacs`.

**Comment by bixuanzju** [comment]
@pkkm Thanks, fixed!

**Comment by TheBB** [comment]
Love it! Thanks! Cherry-picked in develop. You can safely delete your branch.

Made a slight change in https://github.com/syl20bnr/spacemacs/commit/c0950f6421efc61899d96d451cb18bfb6e6bf3a1 to make it work with ranger as well.

**Pull request closed without merging**
