### PR TITLE
added yasnippet to company-mode source for python

### PR DESCRIPTION
**Pull request by mijoharas**
small change to integrate yasnippet with company-mode

### CODE REVIEW

**Comment by trishume** [comment]
You can use the `company-mode/backend-with-yas` function in the company-mode layer instead, that way it will respect the company yasnippet enable/disable variable.

**Comment by trishume** [comment]
Looks good :+1: 

(I previously suggested you use the `company-mode/backend-with-yas` function but it looks like you changed to that since the last PR).

**Comment by mijoharas** [comment]
Thanks, @trishume. There are a few things I've noticed about `company-mode` and I just want to check if I'm missing anything/doing anything wrong. The first is that if there is a single `yasnippet` it doesn't appear to be added to the company-mode list (e.g. try typing `if` into python mode, you can expand with tab, but it doesn't have a drop-down like normal), is this a bug or expected functionality?
The other thing I wanted to ask was `TAB` vs `ENTER` as the triggers. It looks like you disabled tab to stop company-mode stepping on `yasnippet`. could we disable the tab trigger for yasnippet instead and use that instead of enter (or have it configurable, this would remove the issues with ruby `do` e.t.c.)?
The final thing I was wondering about was navigating the company-mode list with `C-i` and `C-j`, would that be the desired functionality for the future? shoud I guess that that's a todo (or is there a different interface we'd want)?

**Comment by trishume** [comment]
@mijoharas Having it be an option to use tab for completion would be awesome, but I fixed enough of my annoyance at enter to not be personally motivated to do it right now.

The reason `if` isn't popping up I think is that company is built for autocomplete so when the prefix matches the target exactly, it thinks it is done. There might be a setting in company-mode to fix this. It isn't a problem with a single matching yasnippet (try typing `bota` in an elisp buffer).

I use arrow keys to do navigation (which is convenient for me since I use a custom keyboard), I don't know any Emacs bindings (I can only infer that `C-i` and `C-j` are up/down) but if you want to implement them and they don't work go ahead.

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
I added a condition on yasnippet presence here: 5f0078506f010a1ebc93b45a797d247fd594102e

Cherry-picked into develop branch, you can safely delete your branch

**Comment by mijoharas** [comment]
@trishume, yes, I meant `C-j` and `C-k`, that was a typo and yes they're down and up in micro-states in spacemacs (e.g. [helm-buffers](https://github.com/syl20bnr/spacemacs/blob/0e4dc90d5da35c419efb45acb5c46f1560446aa8/doc/CONVENTIONS.md#navigation-in-insert-state-buffers), e.t.c.), not regular emacs I think, I'll have a look into integrating them along with the `TAB` completion option.
:+1: @syl20bnr, doesn't `company-mode/enable-with-yas` already check for yasnippet [here](https://github.com/syl20bnr/spacemacs/blob/365de215ee66c94df9eaacb3fd531756801035fd/contrib/company-mode/packages.el#L19)? Also I didn't think `yasnippet` was declared as a configuration layer but was declared simply as a package [here](https://github.com/syl20bnr/spacemacs/blob/857b5fbf0b23e2fa4769f4ce16c57eeb93cd3886/spacemacs/packages.el#L119), (this is partly from reading [here](https://github.com/syl20bnr/spacemacs/blob/857b5fbf0b23e2fa4769f4ce16c57eeb93cd3886/spacemacs/packages.el#L213) where the check is simply for `configuration-layer/package-declared-p`, but I still don't fully understand the configuration layers especially in the case of core so that could be the problem)?

With regards to the `C-j` and `C-k` for up down, there is a `company-mode` keymap [here](https://github.com/company-mode/company-mode/blob/master/company.el#L615) which looks like it coud be overridden, or I could try and make a micro-state, what would you recommend @syl20bnr  (there are also other keys that could be remapped, e.g. `C-/` for search)? how does that sound?

**Comment by trishume** [comment]
Yah @syl20bnr there is no yasnippet layer, it's in the core spacemacs layer. And even if any checks are done they should be done in the backend-with-yas function.

I think that commit effectively disables the functionality added by this PR since it won't find a yasnippet layer.

**Comment by syl20bnr** [comment]
oops, thanks @trishume, should `configuration-layer/package-declaredp` :-(

**Pull request closed without merging**
