### PR TITLE
polish - mode-line: spacemacs same height active / inactive

### PR DESCRIPTION
**Pull request by ahmadseleem**
When you have a split the - active - mode-line "height looks shorter because there's no border.
I Understand that it looks nicer without border and the inactive needs contrast, but, I added neutral color so it looks as nice as possible.

### CODE REVIEW

**Comment by TheBB** [comment]
You should base your branch on `develop`. See the list of commits on this PR.

**Comment by ahmadseleem** [comment]
Yep, Sorry about that...

**Comment by cpaulik** [comment]
I guess that this PR should go to https://github.com/nashamri/spacemacs-theme as well since I would be surprised if the theme extension would be kept when the spacemacs theme is on melpa

**Comment by robbyoconnor** [comment]
Holy mother of god 

- this is against master - switch to develop do your fix there and then do a PR there...
- `git pull --rebase`

**Comment by ahmadseleem** [comment]
@TheBB @cpaulik So, Should I go to https://github.com/nashamri/spacemacs-theme  or base it off develop here ?

**Comment by TheBB** [comment]
You'll note that the file you have changed doesn't even exist here in the develop branch any more, so you'll have to do it in the spacemacs-theme repo.

**Comment by ahmadseleem** [comment]
Got you! I'm sorry I was very busy to into that... I thought it was just a very minor theme change, that nobody cares about editing it. that I just did it on github's website without cloning the repo or anything.
Plus, I am just using Atom for a while now. and happy enough with vim-mode there.  but, some modes and features are only in emacs. so, just starting to clean my emacs config. it's been rusty!

**Comment by ahmadseleem** [comment]
@TheBB Also there's not develop over there :) so, it's master, then!

**Comment by ahmadseleem** [comment]
@TheBB Just did:
https://github.com/nashamri/spacemacs-theme/pull/10

**Pull request closed without merging**
