### PR TITLE
Added extra information

### PR DESCRIPTION
**Pull request by dineshbhosale**
Added extra information for setting default tab width for go files.

### CODE REVIEW

**Comment by LemmingAvalanche** [comment]
I would squash those two commits if I were you.

**Comment by Stebalien** [comment]
I don't really see how that extra bit of documentation is useful; the documentation already gives you a way to set the tab width. This is one of those cases where I feel that less is more (don't confuse users with options).

**Comment by KamranMackey** [comment]
@LemmingAvalanche They don't need to. GitHub offers automatic squashing capabilities when you merge the PR.

**Comment by KamranMackey** [comment]
@Stebalien Yeah, I agree.

**Comment by LemmingAvalanche** [comment]
@KamranMackey The repository owner tends to cherry-pick commits from pull requests, though. Of course Sylvain could squash them after having cherry-picked both of them (if he were to cherry-pick both). Personally though I would prefer to only rewrite my own commits, and not others’.

**Comment by bmag** [comment]
@KamranMackey we prefer simple pull requests to be squashed into a single commit, please. We usually don't use GitHub's button because we want more control over the process.

**Comment by KamranMackey** [comment]
@bmag Ah, alrighty then. :)

**Pull request closed without merging**
