### PR TITLE
Bind SPC g r to magit-rebase-popup

### PR DESCRIPTION
**Pull request by c089**

### CODE REVIEW

**Comment by StreakyCobra** [comment]
@ralesi Just to be sure, was there a special reason to not bind this one when you did #3827? Or it is just because you didn't thought about it?

**Comment by ralesi** [comment]
I just missed it.  Are there any other `-popup` keys I missed too?

On Wed, Jan 6, 2016 at 2:49 PM, Fabien Dubosson <notifications@github.com>
wrote:

> @ralesi <https://github.com/ralesi> Just to be sure, was there a special
> reason to not bind this one when you did #3827
> <https://github.com/syl20bnr/spacemacs/pull/3827>? Or it is just because
> you didn't thought about it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/pull/4460#issuecomment-169473555>.
>



-- 
Rich

**Comment by c089** [comment]
Yes, there's ~50 magit popup commands in total... I personally use rebase a lot - not sure if it makes sense to bind all of them and I'm sure there will be conflicts that will make it hard to find easy to remember shortcuts...

**Comment by ralesi** [comment]
@c089, obviously don't want all of those =).  I haven't gotten to the point of being comfortable doing rebase in a non gui interface (like TortoiseGit).   Was just wondering if there were other major pop-up bindings I missed.

**Comment by c089** [comment]
nope, that's the only one I missed so far. great work, thanks :)

**Comment by robbyoconnor** [comment]
:+1: 

We should also have one for cherry-picking too, no?

**Comment by StreakyCobra** [comment]
Thanks :+1: Cherry-picked in `develop`. You can safely delete your branch. I aligned the table in 9ab4ddb3b5b43f69d7600a8a5a994929d6e905d6 .

@robbyoconnor PR welcome :wink:

**Comment by robbyoconnor** [comment]
@StreakyCobra -- done! -- See #4736

**Pull request closed without merging**
