### PR TITLE
mu4e-compose: add some convenient major mode bindings

### PR DESCRIPTION
**Pull request by xificurC**
I'm missing some nice shortcuts for sending mail, attaching files etc. These bindings are similar to that of magit. Open to further discussion

### CODE REVIEW

**Comment by fandag** [comment]
Even though putting "attach" on `a` is tempting, I think it would be better to follow [conventions](http://spacemacs.org/doc/CONVENTIONS.html#confirm-and-abort) have "abort" on `a`.

**Comment by xificurC** [comment]
@fandag didn't know about those conventions, thanks. I changed the bindings to follow them.

**Comment by TheBB** [comment]
Thanks! Squashed and cherry-picked in develop. You can safely delete your branch.

Note that the `,,` convention is not just `dotspacemacs-major-mode-leader-key` followed by `,` but actually a double tap of `dotspacemacs-major-mode-leader-key`, so I made a change to reflect this: https://github.com/syl20bnr/spacemacs/commit/c7df45a0a9fbb52415796d6ad23bcfd1c297cab1 See e.g. https://github.com/syl20bnr/spacemacs/blob/develop/layers/+source-control/git/packages.el#L364 as an example for magit commit messages.

**Comment by xificurC** [comment]
Thanks @TheBB , nice to know :) The bindings for `mu` are a bit of a struggle sometimes, e.g.

- in `mu4e-headers-mode` `p` moves back a message but `n` does not, although both `C-n` and `C-p` work
- in `mu4e-view-mode` `n` doesn't work and `p` does, *but* `C-n` works and `C-p` doesn't :D 

So if you're open to new changes I might flash up another PR

**Pull request closed without merging**
