### PR TITLE
Add eshell layer

### PR DESCRIPTION
**Pull request by trishume**
This layer adds some fancy features and better defaults to the built in Emacs Eshell:
- Commands for popping out shells
- Better integration with evil mode
- Company mode completion integration
- Some handy aliases and config options

It also fixes some annoyances so that it works better with spacemacs.

### CODE REVIEW

**Comment by rphillips** [comment]
nice. very nice. May I suggest a `SPC E b` to switch to a specific eshell by name.

**Comment by tuhdo** [comment]
@trishume I did not notice that your PR already does this. In my PR, I added `shell-pop` to perform similar features: https://github.com/syl20bnr/spacemacs/pull/1312

- Commands for popping out shells
- Pop open an eshell window below the current buffer in its dir
- Switch an existing eshell to the directory of the current buffer

And it does not work with `ehsell` but for `shell` and `term` as well. I think we should reuse `shell-pop` and you keep everything else for Eshell layer.

**Comment by trishume** [comment]
Sounds good, shell-pop looks cool. I might get around to removing this next week but I'm fairly busy at the moment and I wrote this layer when I thought I might use eshell but I decided against it, just dumped this here so other people won't have to repeat my work. I won't be using it myself.

**Comment by robbyoconnor** [comment]
I merged this into my fork of the [develop](https://github.com/robbyoconnor/spacemacs/tree/develop) -- because I wanted it.

**Comment by syl20bnr** [comment]
I merged the PR from @tuhdo and started a new layer called `shell` (commit https://github.com/syl20bnr/spacemacs/commit/d681234). Unfortunately it makes this PR hard to merge. @trishume thank you the PR, I invite you to apply the relevant bits to the new layer. Sorry for the inconvenience.

@robbyconnor you can open an issue for the features you miss from this PR in the new layer.

**Comment by trishume** [comment]
I won't be applying these changes, someone else who wants them can or they can be left to rot. I'm quite busy nowadays and as I mentioned I don't actually plan on using this layer.

**Pull request closed without merging**
