### PR TITLE
core: support native-compile the "core/*.el" files

### PR DESCRIPTION
**Pull request by sunlin7**
Hi,
There are many errors when I try to byte-compile all the `<spacemacs>/core/*.el` files into `*.elc` files, and it will automatically do native-compile for my local emacs has native-compile feature on.
This PR will fix the errors when running the byte-compile and native-compile the `core/*.el` files.
Please help review it. Thanks.

Just run follow line to compile the `core/` directory.
```
(byte-recompile-directory spacemacs-core-directory 0)
```

### CODE REVIEW

**Comment by lebensterben** [comment]
I will handle them myself.

**Comment by sunlin7** [comment]
Hi @lebensterben 

My local emacs is builded with `native-comp` enabled, the `*.elc` will be builded to `*.eln` automatically.
The reproduce steps:
1. build all `core/*.el` files `core/*.elc` files, then
2. restart the emacs, check the native-compile log

Please pay attention on the messages in buffer `*Async-native-compile-log*`, there will have errors for the native compile routine.

**Comment by sunlin7** [comment]
I created the ticket #15695 to track this request.

**Comment by lebensterben** [comment]
I acknowledge the issue you mentioned. In fact you don't have to compile those files to see the warnings. You can just turn on flycheck and you will see even more complaints.

I closed this PR because I'm going to deal with those core/* files myself.

**Comment by sunlin7** [comment]
Hi @lebensterben 
Thank you for the comments.
This PR is the minimum changes to make the `core/*.el` files work with native-compile.

If you didn't start the work yet, please consider approve this PR first, it maybe save your hours.

And I have another PR depends on this PR, to be able to native compile `core/*.el`.

**Pull request closed without merging**
