### PR TITLE
FIx Template header comment: Typo `;;` to `e;`

### PR DESCRIPTION
**Pull request by CestDiego**
@syl20bnr @StreakyCobra @TheBB New users will flip when their new spacemacs doesn't work

### CODE REVIEW

**Comment by syl20bnr** [comment]
It seems that this typo is not present in master branch anymore.

**Comment by CestDiego** [comment]
it is in develop

**Comment by syl20bnr** [comment]
Ohhh thank you ! @person808 beat you on this one ;-)

**Comment by CestDiego** [comment]
kek....you are right.

**Pull request closed without merging**
