### PR TITLE
added basic ediff layer

### PR DESCRIPTION
**Pull request by mijoharas**
This is just a basic bare bones ediff-contribution-layer. I couldn't figure out how to successfully change the keybindings. I documented an attempt to do this in the readme, so hopefully someone else can see the right way to do it/ see what hook functions I think are useful.

### CODE REVIEW

**Comment by syl20bnr** [comment]
Since `ediff` is a built-in package it should go in the spacemacs layer.
Sorry I did not know that ediff was in the default distribution until I checked.

**Comment by mijoharas** [comment]
ok, sounds good, whereabouts should it go? [I'm guessing here](https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el)? also, I added some stuff in the readme, (basically documenting my attempt to evilify the buffer, which didn't work), is there anywhere I can/should add that information?

**Comment by syl20bnr** [comment]
Yes this is the place, be sure to respect the sorting.
You can move the attempt in comments for now.

**Comment by syl20bnr** [comment]
I merged it and moved it to spacemacs, I put your notes in a comment above the init function, see a5784f37560b74529bba681bae7b7b4358e5d249

Thank you ! :+1: 
Cherry-picked into `develop`.

**Comment by mijoharas** [comment]
Cheers. :+1:

**Pull request closed without merging**
