### PR TITLE
update docs for switch to `SPC l` for perspectives

### PR DESCRIPTION
**Pull request by joehillen**
Update docs for change in 1d340dcc779f

### CODE REVIEW

**Comment by person808** [comment]
Its better to put related changes in the same PR

**Comment by joehillen** [comment]
@person808 This PR is obvious and necessary. #3674 is subject to opinion.

After this one is merged, the other one becomes a single patch.

**Comment by person808** [comment]
@joehillen My bad. You're right. I read them both a little too fast.

**Comment by robbyoconnor** [comment]
:+1:

**Comment by syl20bnr** [comment]
Thank you!
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
