### PR TITLE
[multiple-cursors] Add evil-mc keys, cursors from selection

### PR DESCRIPTION
**Pull request by duianto**
Added evil-mc make cursors from selection key bindings:
`grI` calls `evil-mc-make-cursor-in-visual-selection-beg`
`grA` calls `evil-mc-make-cursor-in-visual-selection-end`

### CODE REVIEW

**Comment by duianto** [comment]
It might be better to bind these upstream, since they are available. And non-Spacemacs users also would benefit.

I'll open a PR upstream.

**Comment by leezu** [comment]
@duianto some multiple-cursors changes were merged to develop branch and break magit (https://github.com/syl20bnr/spacemacs/issues/12961).
Please revert https://github.com/syl20bnr/spacemacs/commit/6556cfc80d4ba070c7385f44f932fbe2b97c0663

**Comment by duianto** [comment]
@leezu Let's continue the discussion about the magit issue in #12961

**Comment by duianto** [comment]
It's been a week since the evil-mc PR was posted, the author is probably busy.

We can merge this into Spacemacs and remove it when it's added upstream.

**Comment by duianto** [comment]
This PRs modified changes have been cherry-picked into the `develop` branch.
https://github.com/syl20bnr/spacemacs/commit/8bb98bcffac3cc6b52becefd5f2b8c93f8092b12

My previous update to this PR accidentally removed the actual key bindings. 😆 
I fixed it in the version that I just cherry picked into `develop`.

**Comment by duianto** [comment]
`grI` and `grA` have been added upstream https://github.com/gabesoft/evil-mc/commit/d50885d5515cff4fd79733a6608f60b465e870fd

They didn't survive long in the `multiple-cursors` layer 😄 
I removed them from the layer.

**Pull request closed without merging**
