### PR TITLE
Add keybinding and evilify CIDER Inspect

### PR DESCRIPTION
**Pull request by ppold**
I evilified `cider-inspector` and replaced `l` to `L` for `cider-inspector-pop`.

I would like to hear some opinions of keeping `L` (`cider-inspector-pop`) and `g` (`cider-inspector-refresh`) or if there are better keybindings for those commands.

Also, is "<leader> mi" a good keybinding for `cider-inspect`?

### CODE REVIEW

**Comment by syl20bnr** [comment]
Nice !
Maybe put `cider-inspect` under `SPC m h i`.

**Comment by ppold** [comment]
I was reading doc/CONVENTIONS.org and found out that `cider-inspect` goes better with `SPC m d i` (just pushed the changes).

**Comment by ppold** [comment]
I also added the key-binding `SPC m d b` for `cider-debug-defun-at-point`.

**Comment by syl20bnr** [comment]
Thank you :+1: 
Cherry-picked and squashed into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
