### PR TITLE
[shell] Enable `helm-esh-pcomplete` for eshell tab completion

### PR DESCRIPTION
**Pull request by bb2020**
I am using `helm-esh-pcomplete` over a year and it seems stable. I think it is not broken anymore and ready for prime time.

### CODE REVIEW

**Comment by duianto** [comment]
It seems to be working:

helm-esh-pcomplete

The `<tab>` key binding for calling `helm-esh-pcomplete` might never have been enabled in Spacemacs. 

The commented out line seems to have been added in this commit (Dec 12, 2014): 
Fixes #78 Use helm histories for eshell/comint https://github.com/syl20bnr/spacemacs/commit/79302c3ca63d7dfe89e3d10a14696fed6e2ac5a1

**Comment by duianto** [comment]
List `TAB` in the Eshell key binding documentation:
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+tools/shell/README.org#eshell-1

And add a changelog.develop entry:
https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop#shell

**Comment by duianto** [comment]
Currently it looks like this when `TAB` is pressed:

emacs_2019-05-08_23-54-53

I wonder if there are users that might be used to or prefer to use the current behavior.

Should there be a variable to enable or disable `helm-esh-pcomplete`?

**Comment by bb2020** [comment]
As long as Emacs is concerned, probably :grin:
This command should achieve that. However it does not work.
`(setq-default dotspacemacs-configuration-layers
    '(org git shell
      (helm :disabled-for shell)))`

**Comment by duianto** [comment]
Thank you for contributing to Spacemacs!
The PR has been cherry-picked into the `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
