### PR TITLE
Update of `evil-org-mode`.

### PR DESCRIPTION
**Pull request by dschrempf**
Change `evil-org-mode` link to the new maintained GitHub repository.

Add the ability to process prefix arguments with `evil-org-eol-call`.

Use this ability to create list items with checkboxes with `clever-insert-item`.

I just saw that there is another pull request about `evil-org-mode` that asks for replacement with `worf`. I do not know `worf` but still provide this code in case it is needed.

Further, wouldn't it be better to use a submodule for `evil-org-mode` so that the spacemacs version does not diverge from the maintained one?

### CODE REVIEW

**Comment by TheBB** [comment]
> Further, wouldn't it be better to use a submodule for evil-org-mode so that the spacemacs version does not diverge from the maintained one?

If the idea was not to diverge from the official version, then we would be using the MELPA package. The reason we have a local copy is so that we *can* diverge, and the reason we wanted to diverge was essentially that evil-org was doing some very intrusive things, like making leader bindings that we had to restore. Eventually it just got easier to maintain a fork. See https://github.com/syl20bnr/spacemacs/issues/3294 and https://github.com/syl20bnr/spacemacs/pull/3305.

I see a lot of work has been done on evil-org lately by @Somelauw, which is great. I'll have to look at the current state of the package to see if we can't just remove our fork and go back to MELPA instead, or whether worf is still better. The original evil-org was quite frankly more trouble than it was worth.

**Comment by Stebalien** [comment]
The default keybindings seem to have been tamed. `evil-org` has introduced ["key themes"](https://github.com/Somelauw/evil-org-mode/blob/master/doc/keythemes.org) for enabling/disabling sets of keybindings and the invasive ones appear to have been disabled by default.

**Comment by TheBB** [comment]
Closing this for https://github.com/syl20bnr/spacemacs/pull/9041

Thanks though!

**Comment by dschrempf** [comment]
Thanks for taking care of this!  Cheers.

**Pull request closed without merging**
