### PR TITLE
Set global pyenv version if no .python-version file exists

### PR DESCRIPTION
**Pull request by cpaulik**
Should solve https://github.com/syl20bnr/spacemacs/issues/4760.

WIP until https://github.com/proofit404/pyenv-mode/pull/24 is merged.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1:

**Comment by cpaulik** [comment]
This is ready. PR to upstream was not accepted so I've put the function in spacemacs.

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Comment by fbergroth** [comment]
@cpaulik This change made `python-auto-set-local-pyenv-version` with a value of `on-visit` pretty annoying. If you are in a project with a set `pyenv`, and jump to a definition in a package outside of the project, the version will change to `system` (or whatever global version is set). Now, if you press `C-o` to jump back, the version will still be the global one, and completion/jump to definition etc breaks.

**Comment by cpaulik** [comment]
@fbergroth Yes that is true. So I can not think about a better solution than to revert this and not look at the global version. Do you have a better idea?

**Comment by fbergroth** [comment]
This kind of "auto" tracking is kind of broken to begin with, as you cannot switch between two python buffers in different projects and have the pyenv version update accordingly.

If you're onto something in https://github.com/syl20bnr/spacemacs/issues/4760#issuecomment-174194230, it's probably better than this :)

Maybe just remove `python-auto-set-local-pyenv-version` and add a keybinding to `pyenv-mode-set-local-version`?

**Comment by fbergroth** [comment]
The first line of `.python-version` (if any) can also simply be used as the preselected value when setting the pyenv version.

**Comment by cpaulik** [comment]
What I meant in my comment runs in to the same problem because restarting the anaconda mode server would probably also be decided when visiting a new file. 

What if we remove the `on-visit` option and set the default to `nil` since `on-visit` is not super useful since it does not change when a file is already open.

Another option might be adding a `on-layout-switch` option if that is even possible. Because I keep my different projects on different layouts so `on-project-switch` does not really do it for me.

I'll try to think about a better solution. Until that https://github.com/syl20bnr/spacemacs/pull/4809

**Pull request closed without merging**
