### PR TITLE
Updated osx layer instructions.

### LINKED ISSUE #3423: OSX keybindings not working
Following instructions installed mac using hombrew and attempted to configure osx layer:

.spacemacs:
``` lisp
(defun dotspacemacs/user-init ()
  "Initialization function for user code.
It is called immediately after `dotspacemacs/init'.  You are free to put any
user code."
  (setq-default dotspacemacs-configuration-layers '(osx))
  (setq-default dotspacemacs-configuration-layers '((osx :variables osx-use-option-as-meta nil)))
  )

```

Saved and sync-configuration-layers.

M-+ is undefined.

Any hints how to proceed?

### PR DESCRIPTION
**Pull request by t-my**
Updated osx layer instructions to be more noob friendly. Now it's clear how you get the layer in use. Resolves #3423

### CODE REVIEW

**Comment by TheBB** [comment]
Thanks. This fixes https://github.com/syl20bnr/spacemacs/issues/2113 for the `osx` layer only.

Would be nice if we can get a PR that does this to *all* layers. And it would be good to be a bit less verbose and not copy all the comments into the documentation. See the referenced issue for an example.

Don't worry about the build failure.

**Comment by justbur** [comment]
How about better instructions in the main documentation file and a default link in each layer readme?

**Comment by robbyoconnor** [comment]
Should (in the future) be against 'develop' -- please have a peek at the [contribution guidelines](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.md). :stuck_out_tongue:

**Comment by syl20bnr** [comment]
@t-my Thank you!
This PR seems outdated and superseeded by #4431.
I'm sorry to close this one in favor of #4431, my bad for not being quick enough to merge it.

**Pull request closed without merging**
