### PR TITLE
Add docker-tramp and docker.el - move to +tools

### PR DESCRIPTION
**Pull request by cpaulik**
Should we move the docker layer from `+config-files` into `+tools`. I'm just asking since the `vagrant` layer is in `+tools`

### CODE REVIEW

**Comment by StreakyCobra** [comment]
As this adds functionalities not only related to `docker` configuration files, but to docker in general, I'm in favour of moving it to `+tools` :+1:

**Comment by cpaulik** [comment]
I've extended the commit to include a move into `+tools`. I would also favor a rename to `docker`. I guess there is no way to do that without breaking configuration.

**Comment by StreakyCobra** [comment]
Probably not. For me it can be changed as it make sense, as long as it's explained in the release note. But it's maybe better to wait for @syl20bnr or @TheBB opinions :smiley:

**Comment by robbyoconnor** [comment]
:+1:

**Comment by cpaulik** [comment]
I've just rebased this. So it might be merged easily :smile:

**Comment by jpfairbanks** [comment]
Thanks for the work @cpaulik. Is there anything holding this back?

**Comment by cpaulik** [comment]
@jpfairbanks It just takes a while for stuff to be merged. :+1: the PR then it might go up in priority.

**Comment by jpfairbanks** [comment]
Ok great, I checked it out and there seems to be some features from docker.el missing. In particular the `docker-run` command. Are they supposed to be there or is that a problem with my .spacemacs file?

**Comment by cpaulik** [comment]
@jpfairbanks There is currently no `spacemacs`keybinding for docker run. It might be newer than this PR. I'll check the current docker.el to see if I can add additional features. 

But docker run should be available using the keybinding as described in the docker.el readme.

**Comment by syl20bnr** [comment]
Thank you ! 👍 
Sorry for being late, I made various changes (more conventions related than anything else) in commit https://github.com/syl20bnr/spacemacs/commit/79c8dc1
Most importantly **I renamed the layer docker**.
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by robbyoconnor** [comment]
Thank you -- I love this!

**Pull request closed without merging**
