### PR TITLE
Change the year to 2016 for the release of 0.105.0

### PR DESCRIPTION
**Pull request by robbyoconnor**
This should be 2016...

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Got enough labels there?

**Comment by StreakyCobra** [comment]
Oh you right, I forgot one :-)

**Comment by d12frosted** [comment]
You forgot this one: `¯\_(ツ)_/¯ `

**Comment by d12frosted** [comment]
It's just... the last time @syl20bnr had a nap it still was 2015 ˆ_ˆ

**Comment by StreakyCobra** [comment]
Here we are!

**Comment by d12frosted** [comment]
yay! thanks mate!

**Comment by robbyoconnor** [comment]
This is my favorite PR -- it's just glorious. I love this community a lot.

**Comment by syl20bnr** [comment]
I knew that all these labels were useful !
Thank you :+1: 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
