### PR TITLE
Key-Seq Layer

### PR DESCRIPTION
**Pull request by Devagamster**
Adds key sequence and key chord functionality to spacemacs.

Sequences are rapid ordered pressing of keys, and chords are simultaneous presses of keys.

I like them because I can bind them to insert mode or normal mode without clobbering other existing key bindings. Its definitely not for everyone, but it's nice to have.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
<3

**Comment by syl20bnr** [comment]
I'll have to re-evaluate key-chord because at the time of 24.3 there were some bugs with evil.
This layer does not bring much though, anyone willing to enable key-chord mode can add the package to additional-package and require it in the config function.

**Comment by Devagamster** [comment]
Thats totally fine. Chord mode was mentioned in the gitter chat and I had been using it for a good long while on 24.4 with seq mode and thought somebody else might find it useful. Take it or leave it :smile:

**Comment by StreakyCobra** [comment]
@syl20bnr Now that we are removing 24.3 support, do you think this one is gonna to be merged? Otherwise we can consider closing it. From my point of view it can be merged as it is useful and sometime we have people asking how to use them.

**Comment by syl20bnr** [comment]
@Devagamster Thank you for the PR.
I'm sorry but I don't see the benefit of such layer since it only add packages. But more importantly I'm against supporting officially in Spacemacs because:
1) I don't like the paradigm
2) It is a lot of work to come up with good key bindings that does not break POLA for very few benefits (only not pressing SPC key).

Since we won't take the risk to propose some configuration for these packages, I consider them a user preference not supported by Spacemacs (Spacemacs has already all the tool needed for a very good UX).

**Pull request closed without merging**
