### PR TITLE
Fix typo in helm-use-posframe

### LINKED ISSUE #16644: Helm-posframe seems to break completely the display on the terminal.
If you are posting about a *bug* please close this issue and open a new one from within Spacemacs using:
- `SPC h I`
- `M-m h I`
Will this even work in the terminal (emacs -nw)? It opens the Github, but seems impossible to login.

ANYWAY:

#### Description :octocat:
helm-posframe in new spacemacs completely wrecks the terminal (emacs -nw) each time it's called.
It also ignores the controlling variable, maybe because there's a typo in packages.el:
    (helm-posframe :toogle helm-use-posframe)
note the oo instead of og.

#### Reproduction guide :beetle:
- Start Emacs in terminal (-nw, or over SSH) while configured for Helm.
- Press SPC SPC
- Display breaks

*Observed behaviour:* :eyes: :broken_heart:
SPC SPC breaks the display.

*Expected behaviour:* :heart: :smile:
Like it was before - working. ;)
I think it should not be default if it breaks the terminal/SSH users. Should be documented in README and possible to disable. helm-posframe on github looks really abandoned BTW, with calls for new maintainer. Maybe it should not be used at all? 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 31.0.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 60dcd8cf9)
- Graphic display: nil
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((shell :variables shell-default-height 30 shell-default-position 'bottom) helm
 emacs-lisp better-defaults multiple-cursors
 (tree-sitter :variables tree-sitter-syntax-highlight-enable t
              tree-sitter-fold-enable t tree-sitter-fold-indicators-enable t)
 python javascript asm html markdown sql csv protobuf dap graphviz docker yaml
 latex plantuml
 (mu4e :variables mu4e-installation-path
       "/usr/share/emacs/site-lisp/elpa-src/mu4e-1.12.6")
 xclipboard helm
 (auto-completion :variables auto-completion-private-snippets-directory
                  "~/.emacs.custom/snippets/")
 git markdown
 (org :variables org-enable-github-support t org-enable-roam-support t
      org-enable-org-journal-support t org-enable-bootstrap-support t
      org-enable-reveal-js-support t org-enable-sticky-header t
      org-enable-epub-support t org-roam-v2-ack t)
 (c-c++ :variables c-c++-backend 'lsp-clangd c-c++-enable-clang-format-on-save
        nil c-c++-enable-auto-newline t c++-enable-organize-includes-on-save nil
        c-c++-default-mode-for-headers 'c++-mode)
 (lsp :variables lsp-ui-doc-delay 2 lsp-ui-doc-max-height 10 lsp-ui-doc-enable
      nil lsp-ui-imenu-auto-refresh t lsp-ui-imenu-auto-refresh-delay 1.0
      lsp-rust-server 'rust-analyzer)
 (rust :variables rust-backend 'lsp) themes-megapack syntax-checking
 version-control)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ IMAGEMAGICK JPEG LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODU\
LES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XAW3D XDBE XIM XINPUT2 XPM LUCID ZLIB

### PR DESCRIPTION
**Pull request by jaeyeom**
Before this commit helm-postframe was enabled by default since it ignore helm-use-posframe variable. Fixes #16644

### CODE REVIEW

**Comment by larebsyed** [comment]
thanks for fixing this.

**Comment by jaeyeom** [comment]
Who can approve this PR and merge it? I guess it's an obvious fix that resolves an issue that affects almost everyone.

**Review by smile13241324 — APPROVED** [review]

**Comment by smile13241324** [comment]
Sorry for the delay, Im a bit busy right now and needed to cut some project time. Anyway for urgent issues please just ping me directly @jaeyeom

**Comment by michaelpass** [comment]
Sorry. I've been a follower of the way EMacs works. As a lazy vim.engineer.Model.cache...

I like elongated, super obvious signals in animal reference Loooney Tunes. Enforceable nature of reading these logs. I'm busy and disjointed at this logical juncture, unraveling my rats next logical life.

**Comment by jaeyeom** [comment]
@michaelpass @smile13241324 Oh... don't be sorry! I know everyone is busy and I deeply appreciate the maintainers of open source projects. Hopefully more and more passionate contributors appear and become maintainers. Thank you for taking care of this PR!

**Pull request merged**
