### PR TITLE
Add .jsx to html layer #1769 #1770 @Tritlo

### PR DESCRIPTION
**Pull request by louy2**
Originally by @Tritio but requested against master branch.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
It will appear in `develop` before master

**Comment by catesandrew** [comment]
Should we also add flycheck to jsx at same time?

```lisp
(after "flycheck"
  (when-let (eslint (executable-find "eslint"))
    (setq flycheck-javascript-eslint-executable eslint)
    (flycheck-add-mode 'javascript-eslint 'web-mode))

  (when-let (tidy5 (executable-find "tidy5"))
    (setq flycheck-html-tidy-executable tidy5)
    (flycheck-add-mode 'html-tidy 'web-mode)))

(add-hook 'web-mode-hook
  (lambda ()
    (when (equal web-mode-content-type "jsx")
      (setq-local cursor-type nil)
      (after "flycheck"
        (add-to-list 'flycheck-disabled-checkers 'html-tidy)
        (flycheck-select-checker 'javascript-eslint)))))

```

**Comment by robbyoconnor** [comment]
I think so -- yes.

**Comment by louy2** [comment]
@catesandrew I am not familiar with flycheck. In that case is it better that we create a new layer for jsx?

**Comment by robbyoconnor** [comment]
@louy2 no need -- it's very easy to setup and @catesandrew  did all the work for you.

**Comment by louy2** [comment]
@robbyoconnor Although I understand what @catesandrew wrote, I don't agree with putting `eslint` in `html` layer. In addition `tidy5` is not officially released and can only be obtained by compiling from source code or via 3rd-party.

**Comment by catesandrew** [comment]
Simple substitute `after` with `(when (configuration-layer/package-usedp 'flycheck) ...)`. probably best to put it in web-mode since you're adding a new mode file extension for it. The main piece is `(flycheck-add-mode 'javascript-eslint 'web-mode)`. Without that nothing happens. I also use html5 (via homebrew) to syntax check my html, i know its got a bunch of false positives for templates, but they've saved my butt a few times in the past so i still use them. I just wanted to illustrate how you might now want html5 tidy running in flycheck while the `web-mode` content type is jsx.

**Comment by louy2** [comment]
After all kinds of experiments and JSX layer and such, I am going on with adding @catesandrew 's suggestion. I am also adding Tern.

**Comment by robbyoconnor** [comment]
:cat: :+1:

**Comment by tritio** [comment]
Hi,

you are send me emails in reference with a project in which I am not join.
Please delete me from you list.

2015-07-22 9:07 GMT+02:00 robbyoconnor <notifications@github.com>:

**Comment by louy2** [comment]
Oh, just realized I got the name wrong. It was @Tritlo not @tritio . But I don't know how to remove participant from this issue. Could @tritio you login and unsubscribe this?

**Comment by robbyoconnor** [comment]
@tritio 

You can easily unsubscribe if you did saw it -- sorry -- just click it again :smile_cat: 
image

**Comment by TheBB** [comment]
You also want to remove his name from the commit message.

**Comment by louy2** [comment]
Oh that... will do after I squash everything down to one commit. For now please give it a try if you are interested.
I am getting `void-function` on `flycheck-add-mode` for some reason, so I have refrained from adding @catesandrew 's suggestion.

**Comment by syl20bnr** [comment]
I merged #1770 since it was a little change.

Tern is already in the javascript layer.

Do you think we should merge the JS layer and the html layer under a unified `web` layer ? I fear that the scope of this layer maybe too wide though.

**Comment by louy2** [comment]
From my experience I think a unified `web` layer is quite plausible. I don't know of any significant use case where JavaScript is independent from HTML and CSS.

**Comment by robbyoconnor** [comment]
It's really up to @syl20bnr  -- I don't use jsx :)

**Comment by robbyoconnor** [comment]
I think merging the `html` and `js` layers would be helpful EXCEPT in the case of `node.js` -- because -- it's not always web...so that is a case where we'd want a separate js layer...

**Comment by louy2** [comment]
The most common use case of node.js is MEAN, which is a web stack. The whole node ecosystem is around web.

The divide of concern may then be controled by `:with`.

**Comment by robbyoconnor** [comment]
@louy2 -- I disagree...but my point is that the `js` layer should remain separate in my opinion.

**Comment by louy2** [comment]
Closing this request. Discussion about whether to merge html and javascript into a web layer can go further in an issue.

**Pull request closed without merging**
