### PR TITLE
Adding ibuffer layer

### PR DESCRIPTION
**Pull request by alex-glv**
ibuffer layer support and functions that group buffers by major mode.
Currently mapped to "B"

### CODE REVIEW

**Comment by tuhdo** [comment]
It would be nice if [projectile-ibuffer](https://github.com/purcell/ibuffer-projectile) got added to the layer. 

Also, `ibuffer` should replace `list-buffer` bound to `C-x C-b`, but no in this layer but Spacemacs core key bindings in `spacemacas/keybindings.el`.

**Comment by alex-glv** [comment]
I will add projectile-ibuffer.
About keybinding, shouldn't I replace keybinding in ibuffer layer because it's optional, and if it's not installed default keybinding will point to void function?

**Comment by tuhdo** [comment]
ibuffer is built into Emacs so there should be no problem. I mean you only bind the command Ibuffer to C-x C-b but not other commands in external packages.

**Comment by danielwuz** [comment]
Can we have ex command `ls` bind to `ibuffer` too? I think `ibuffer` is better than `list-buffers`, the default one with `ls` command.

**Comment by alex-glv** [comment]
I have included ibuffer-projectile and added a config option to group by projects, although at this stage it requires restart.

**Comment by alex-glv** [comment]
Curious, if we can get this shipped, or what else I can do to bring it up to the repository standards? Thanks!

**Comment by syl20bnr** [comment]
@danielwuz I think you can provide a PR to add the ex command to the layer.
@alex-glv Thank you !
I rework the layer to merge the 2 variables into one and changing the grouping should not require a restart. I also added a README to the layer. Related commits https://github.com/syl20bnr/spacemacs/commit/2da8982 and https://github.com/syl20bnr/spacemacs/commit/bb29c92

Cherry-picked into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
