### PR TITLE
Improve home buffer

### PR DESCRIPTION
**Pull request by tuhdo**
Here is how it looks with this commit:

spacemacs-new-face

`r` and `p` are highlighted as well, but look a bit pale due to the image quality.

### CODE REVIEW

**Comment by CarlQLange** [comment]
:+1:

**Comment by tuhdo** [comment]
@syl20bnr Spacemacs's home buffer is currently buggy for `holy-mode`. You should merge this before releasing to the Emacs users.

**Comment by tuhdo** [comment]
@syl20bnr I'm not sure if this test case is releated to my PR or not

```text
(Spacemacs) Warning: Missing value for variable var2 !
Test test-set-layers-variables--odd-number-of-values backtrace:
  (if (and (eieio-oref r (quote :-active)) (< (eieio-oref r (quote :-o
  (lambda (r) (if (and (eieio-oref r (quote :-active)) (< (eieio-oref 
  mapc((lambda (r) (if (and (eieio-oref r (quote :-active)) (< (eieio-
  (lambda (mock) (mapc (function (lambda (r) (if (and (eieio-oref r (q
  apply((lambda (mock) (mapc (function (lambda (r) (if (and (eieio-ore
  #[385 "\301\302\303\304\305!\306\"\307$\310K\311K\301\302\312\304
  apply(#[385 "\301\302\303\304\305!\306\"\307$\310K\311K\301\302\3
  #[128 "\302\300\303\304\305\306\307\301\"\310\"\311\312%#\207" [#
  apply(#[128 "\302\300\303\304\305\306\307\301\"\310\"\311\312%#\2
  mocker-verify([eieio-class-tag--mocker-mock spacemacs-buffer/message
  (prog1 (let* ((vnew (function (lambda (msg &rest args) "\n\n(fn MSG 
  (let ((spacemacs-buffer/message--mock [eieio-class-tag--mocker-mock 
  (let ((input (quote ((testlayer :dir "/a/path/" :ext-dir "/a/path/ex
  (lambda nil (let ((input (quote ((testlayer :dir "/a/path/" :ext-dir
  ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc
  ert-run-test([cl-struct-ert-test test-set-layers-variables--odd-numb
  ert-run-or-rerun-test([cl-struct-ert--stats t [[cl-struct-ert-test t
  ert-run-tests(t #[385 "\306\307\"\203D\211\211G\310U\203\211@\20
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  command-line-1(("-l" "ert" "-l" "/home/travis/.emacs.d/core/core-loa
  command-line()
  normal-top-level()
Test test-set-layers-variables--odd-number-of-values condition:
    (mocker-record-error "Expected call to mock `spacemacs-buffer/message', with input like anything, was not run.")
   FAILED  18/19  test-set-layers-variables--odd-number-of-values
```

**Comment by syl20bnr** [comment]
It is not related to your PR, I broke it yesterday so your PR just inherits of the failure. It has been fixed this morning, if you rebase the PR it should be green.

**Comment by syl20bnr** [comment]
Note that I removed the shortcuts in master because they make the buffer less readable and once a user know the key binding they are useless. We have to find another way to make the key binidngs discoverable in the startup buffer. I like the idea of the widget `[?]` at the end of the second line.

**Comment by tuhdo** [comment]
@syl20bnr I've updated it, but not the `[?]` button. I think we should place it on the first line, right where the cursor initially appears, so complete new users can immediately press for help, rather than using the mouse.

**Comment by syl20bnr** [comment]
We could also inject it in the upper left of the banner.

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
Cherry-picked into `develop` and `release-0.101`, you can safely delete your branch.

**Pull request closed without merging**
