### PR TITLE
Add evil-set-jumps to avy commands

### PR DESCRIPTION
**Pull request by luxbock**

### CODE REVIEW

**Comment by cmccloud** [comment]
weird - evil jumper and evil already seem to work for me.

**Comment by luxbock** [comment]
@cmccloud definitely not the case for me. Weird indeed.

**Comment by robbyoconnor** [comment]
Time to rebase ;) -- You have some conflicts :P

**Comment by bmag** [comment]
@luxbock If you're testing with `M-x avy-goto-<command>`, then you should try `M-x evil-avy-goto-<command>` instead. Evil remaps all `avy-goto-*` commands to `evil-avy-goto-*` commands, which are valid Evil motions.

**Comment by TheBB** [comment]
Closing this since it seems not to be a problem.

**Pull request closed without merging**
