### PR TITLE
Improve Python virtual environment docs and keybindings

### PR DESCRIPTION
**Pull request by cpaulik**
Inspired by the discussion in
https://github.com/syl20bnr/spacemacs/issues/2841 I thought it was
useful to improve the Documentation and provide keybindings for all the
useful `pyvenv` functions.

@autosquid might like to review this.

### CODE REVIEW

**Comment by TheBB** [comment]
Good work as usual. :+1:

**Comment by autosquid** [comment]
:+1: I think it is very clear now on virtual environment usage now. Thanks.

**Comment by robbyoconnor** [comment]
:+1:

**Comment by TheBB** [comment]
Thank you! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
