### PR TITLE
added fasd contribution layer

### PR DESCRIPTION
**Pull request by mijoharas**
I added this as a contribution layer as I figured that was best from reading [CONTRIBUTE.md](https://github.com/syl20bnr/spacemacs/blob/master/doc/CONTRIBUTE.md), but I think conceptually this makes more sense in the [core packages.el](https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el).  Any thoughts?

### CODE REVIEW

**Comment by mijoharas** [comment]
oh and a description. [fasd](https://github.com/clvv/fasd) is a command line tool like autojump. fasd-emacs adds that to emacs. (it's pretty handy for getting to your project and then you can use projectile to take you from there).

**Comment by syl20bnr** [comment]
:+1: 
Cool integration thank you !
I tweaked the README a bit here: https://github.com/syl20bnr/spacemacs/tree/develop/contrib/fasd

Cherry-picked into develop branch, will be available in 0.42.0

**Comment by mijoharas** [comment]
Thanks for the improvements to the documentation, I'll use that as a template for any other contribution layers I add.

**Comment by tshort** [comment]
Cool! Thanks for this.

**Pull request closed without merging**
