### PR TITLE
Add typescript-tsx-mode (derived from web-mode)

### PR DESCRIPTION
**Pull request by aaronjensen**
This makes it easier to configure things for tsx files. It borrows from the idea
in the react layer.

### CODE REVIEW

**Comment by syl20bnr** [comment]
Thank you ! 👍 
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by linchen2chris** [comment]
typescript-tsx-mode is missing in spacemacs now,

**Comment by aaronjensen** [comment]
> typescript-tsx-mode is missing in spacemacs now,

Are you on `develop`? I don't think it's on `master` yet, and I still see it on `develop`

**Comment by linchen2chris** [comment]
It works now. I am on develop branch, but forgot to add html layer 😅

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aaronjensen** [comment]
Ah, I wonder then if the html layer should be depended on by the typescript layer now...

**Comment by linchen2chris** [comment]
> Ah, I wonder then if the html layer should be depended on by the typescript layer now...

that would be better

**Pull request closed without merging**
