### PR TITLE
[clojure] Add sesman keybindings

### PR DESCRIPTION
**Pull request by jr0cket**
Add Spacemacs keybindings to the Clojure layer for all the sesman functions.
https://docs.cider.mx/cider/0.23/usage/managing_connections.html

Sesman has been a part of CIDER for many versions now and provides session
management for nREPL connections (in fact any connections).

Several keybindings relating to the use of a specific repl been migrated the
`mR` sub-menu, providing a cleaner separation between repl connection and
session management and interacting with a specific repl.

**Please read issue #12593 which discusses alternatives to this PR**

### CODE REVIEW

**Comment by jr0cket** [comment]
I have updated the keybinding changes based on feedback in the Clojurians slack channel.  The change should have very minimal impact to esablished workflows, whist adding more features of CIDER.

I still need to update the documentation and changelog.

**Comment by jr0cket** [comment]
Positive feedback for these revised changes have been received from the Clojure community, so have updated the documentation and changelog entries

**Comment by duianto** [comment]
Thank you for contributing to Spacemacs. It's safe to delete your branch.
The changes have been applied to the `develop` branch.
Commit(s): https://github.com/syl20bnr/spacemacs/commit/e47494229b965014e7ed8ecb308fa6e710508a12

**Comment by syl20bnr** [comment]
@jr0cket This is a great PR but I need to revert it as it breaks the conventions: https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org#repls

I suggest reopening a PR and managing sessions under `SPC m S` or another available prefix that does not break convention.

**Comment by jr0cket** [comment]
@syl20bnr ah, finally I understand what the `s` means.  Sorry, although I knew there were conventions I never realized there was a document that explained them, its very helpful.  Thanks

Although I am now confused about what the keybindings should be now, as it raises more questions than it answers. 

The `s` convention does seems to be a little overloaded in the Clojure layer, as there have long been keybindings to start/restart/clear/quit the REPL.  These don't seem to fit into a menu where the focus is sending code to the REPL.  There are a lot of commands used manage the REPL connection in Clojure it seems, and lots more to send code to the REPL buffer, and quite a few to evaluate (some of which have been asked about but no one added yet).

In Clojure its far less common to have the REPL buffer on display and the buffer is not displayed by default.  Instead evaluation is done in the source code buffer, using the keybindings under `SPC m e`.  So it did seem to make sense to put all the keybindings that evaluate code in one place.   But I appreciate this breaks the convention.

If it fits convention, then I can keep `SPC m e` for source code buffer evaluation, `SPC m s` for sending code to the REPL buffer.

I am confused where start/stop/restart/clear/quit the REPL make sense.  I checked the conversions doc for suggestions, but didnt see anything about sessions or starting / stopping external repl processes.  

Leaving the `SPC m s` menu as it is after the roll-back seems to break convention too, because it has REPL connection management in there too.  Or am I missing something?

What about moving the start/stop/restart/clear/quit REPL keybindings to `SPC m c` (for connections) and keeping all the send-code-to REPL commands in `SPC m s`?  Would this be okay?

I'll make a new PR so people can try the new set of keybindings and see what feedback I get from the Clojure community as well.

Thank you.

**Pull request closed without merging**
