### PR TITLE
eww web browsing layer

### PR DESCRIPTION
**Pull request by axyz**
As proposed on #4107 here it is an initial implementation of vimperator style keybindings for the eww browser.

the layer provides also a helm-eww-bookmarks function to quickly work with saved urls.

The layer seems to work, but it need to be reviewed:
- I'm not sure about function naming: I've seen a lot of variants around so I've prototyped everything with short names to be able to add prefixes as requested.
- I'd like to add a `<SPC> h w` key to open `helm-eww-bookmarks` from everywhere, but the functions needed to populate and generate it are enclosed in the eww use-package and I was not able to have them defined on spacemacs start, but only on the first eww launch (I'd like to avoid to force code outside of a deferred use-package)

new ideas and new keybindings are also welcomed.

also with just those few keys and the magic of lnum is now a pleasure to me to quickly google or stackoverflow something right inside emacs :smile:

### CODE REVIEW

**Comment by syl20bnr** [comment]
Nice work! But what I feared is confirmed here, some precious normal state key bindings are not available.

I propose this design articulated around 3 main states and switch rules:
- evilified or a state from scratch used to navigate
- normal state untouched
- insert state untouched
- ESC in navigation state -> normal state 
- ESC in normal state -> navigation state
- ESC in insert state -> normal state
- i in both navigation and normal state -> insert state

**Comment by syl20bnr** [comment]
I implemented the above designed in evilified state, now in all evilified states the following is true:
- pressing `ESC` in evilified state -> normal state
- pressing `ESC` in normal state -> evilified state

I also updated `evil-escape` to be able to perform the same operations.

So now if you just evilify eww you'll get the behavior of my previous post for free :-)

**Comment by axyz** [comment]
Great! I'll try this out soon ;)

**Comment by axyz** [comment]
Seems to work so far, is it safe to overwrite some unwanted keys on normal mode as well? Such as `o` inserting a new line that could make sense on an textarea, but is quite annoying if you just want to open a new url thinking to be in evilified state while you are in normal and then have the website layout modified by a new line (may happen often)

**Comment by axyz** [comment]
When you are over a link in evilified state and press o ace-jump will start... while if you are not over a link open new url works correctly, needs to be investigated, may be related to some eww specific map for when you are over links? (similar to eww-text-map or eww-submit-map)

**Comment by syl20bnr** [comment]
@axyz I tried it and I was not able to correctly do a search in google, can you give me a repro step to do a successful search when landing on the google homepage ?

**Comment by axyz** [comment]
@syl20bnr you are right, but it seems to be a google/eww related bug.

a search on bing or wikipedia seems to work, while on google I get `find-coding-systems-region: Wrong type argument: integer-or-marker-p, nil`.

the layer seems to work correctly as that error is raised by `eww-submit` that is invoked when pressing enter on an input.

Do you get the same error?

**Comment by syl20bnr** [comment]
I tried the layer and there are numerous bugs especially with input fields where I am able to delete anything in the buffer when in normal state. Also the focus seems to remain in the input field even when I leave it. There is definitely something to be done when leaving an input focus.

I used duckduckgo to test.

**Comment by cal2195** [comment]
Is there any progress on this PR? :)

**Comment by szobov** [comment]
Hi there!
Thanks a lot for your work!
But what could we do to make this PR to be merged?

**Comment by duianto** [comment]
There's another PR for adding a `eww` layer: Add eww layer #9871
It seems like syl20bnr might be using it as a starting point, so the development is probably on going there.

This PR was last updated, Dec 14, 2015, and it had some issues.
Therefore we'll close this PR in favor of the other one.

**Pull request closed without merging**
