### PR TITLE
Improve smooth-scrolling

### PR DESCRIPTION
**Pull request by sooheon**
Problems with previous:
Go to any decently sized file, play around with `zt` and `zb` movements. You will see that the point is moved within the 5 line margin quite often. Furthermore, `zt` and then `k` will at least move the cursor to just outside the margin, but `zb` and then `j` will jump your cursor all over the place.

With my version, none of these things happen. `zt` and `zb` move your cursor to the expected line just outside of margin, and further movements into margin scroll smoothly.

I'm also not sure what the defadvice disables accomplish, but haven't had time to test them out. If the original contributor could chime in with the reasoning for them please?

Edit: It also fixes the point being moved into the margin after `zt` and `C-e` or `zb` and `C-y`.

### CODE REVIEW

**Comment by tuhdo** [comment]
I've tested it. This commit works fine. It keeps the old behavior when you search something at the bottom and move down, the screen won't be scrolled in half. About the advice, I don't know. I didn't write it.

**Comment by sooheon** [comment]
Think we could just get rid of those, they made no difference to me using for a while without them.

**Comment by syl20bnr** [comment]
The advice stuff is necessary to deactivate smooth-scrolling if `dotspacemacs-smooth-scrolling` is nil.

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
Cherry-picked and squashed into `develop`, you can safely delete your branch.

**Pull request closed without merging**
