### PR TITLE
Add documentation about specify socket server for client

### PR DESCRIPTION
**Pull request by razum2um**
Additional docs for https://github.com/syl20bnr/spacemacs/pull/10431/

### CODE REVIEW

**Comment by razum2um** [comment]
@syl20bnr didn't expect such failures.. oO

**Comment by CarlQLange** [comment]
@razum2um just FYI, it should be "its" rather than "it's", but I'm just being pedantic 😅 I'd fix it myself but I'm on the side of a mountain ⛰

**Comment by syl20bnr** [comment]
Don't mind the CI errors for this one. I'll fix them.

**Comment by syl20bnr** [comment]
I mean, these errors are from previous commits merged in develop.

**Comment by razum2um** [comment]
updated

**Comment by sdwolfz** [comment]
Thank you :heart:!
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
