### PR TITLE
add emacs banner

### PR DESCRIPTION
**Pull request by robert-zaremba**
This Pull requests add Emacs banner ASCII art banner.

### CODE REVIEW

**Comment by robert-zaremba** [comment]
Any chance to merge this PR?

**Comment by Compro-Prasad** [comment]
@robert-m-johnson Its marked as a part of Future release. So, I guess it will be merged but in future.

**Comment by robert-zaremba** [comment]
@Compro-Prasad thank you for response.
This PR is only a cosmetic add-on, which doesn't change or add any functionality. So humbly speaking I don't see any blocker.
Best regards

**Comment by Compro-Prasad** [comment]
Many simple PRs are also on hold. I think you might need to modify the CHANGELOG too when you submit a PR. This will make sure we don't double the work when a new Spacemacs version is released.

So, modify the `CHANGELOG.develop` and ping the maintainers. That would probably help them merge the PR faster.

**Comment by robert-zaremba** [comment]
@sdwolfz , @Compro-Prasad , @chrismcg I've updated release notes.

**Comment by duianto** [comment]
Thank you for contributing to Spacemacs!
The PR has been cherry-picked into the `develop` branch, you can safely delete your branch.

Corrections:
- The `.projectile` file was removed.
- The changelog entry was moved to the `Core`, `Other` section.
- The usage instruction was moved to the commit body.
- The commits were squashed.

**Comment by robert-zaremba** [comment]
Thank you.

**Pull request closed without merging**
