### PR TITLE
Limit lines to 80 chars

### PR DESCRIPTION
**Pull request by duianto**
And fix comment indentation. Vertically aligned comments in function
definitions, indents them in the help buffer.

### CODE REVIEW

**Comment by sdwolfz** [comment]
:+1: Just curious, did you do this manually or used some automatic tool or elisp function?

**Comment by duianto** [comment]
Manually, with `fill-column-indicator` enabled `SPC t f`.

I also recently noticed that there's a `highlight-long-lines` feature `SPC t 8`. It shows the characters from column 80+ with the `column-enforce-face`, (it adds an underline and inherits from the `font-lock-warning-face`) which is orange with the default spacemacs-dark theme. That really makes the long lines stand out.

**Comment by sdwolfz** [comment]
I want to have a tool that does this automatically and can also check the files as part of the CI (to add to my https://github.com/syl20bnr/spacemacs/pull/11251 PR), do you happen to know any?

By the way, similarly to `SPC t 8` there is `SPC t w` which highlights lines that go above 80 with a different foreground color (and I could not find a way to turn that off).

**Comment by duianto** [comment]
I don't know anything about automatic checking, but it sounds like a nice feature 👍 

I haven't used `SPC t w` enough to notice that it also highlights 80+ lines. That's good to know. Thanks.

### About turning off the whitespace long line coloring.

While checking how the whitespace coloring is defined: https://github.com/emacs-mirror/emacs/blob/9dd95bf0b12c8ddba82acae741f944743e37cdd8/lisp/whitespace.el#L2051

#### Method 1

I noticed that it's using a variable called `whitespace-line-column`. It can be used for "turning off" long line coloring, by setting it to a larger column number than the number of characters that fit on a line in a fullscreen Emacs frame with a single window. For example:
```elisp
(setq whitespace-line-column 300)
```

#### Method 2

I also noticed that there's a function called `whitespace-toggle-options`:
https://github.com/emacs-mirror/emacs/blob/9dd95bf0b12c8ddba82acae741f944743e37cdd8/lisp/whitespace.el#L1143
it lets us toggle any of the whitespace styles.

This toggles the long line coloring:
```elisp
(whitespace-toggle-options 'lines)
```
and there's also:
```elisp
(whitespace-toggle-options 'lines-tail)
```
but it's only visible if `lines` is toggled off.

Since they are toggles then they won't work by themselves in the `.spacemacs` user-config section. Because if the configuration layers are synchronized `SPC f e R`, then they will be toggled again.

The toggle function modifies the variable `whitespace-active-style`, and it's default value seems to be:
```elisp
(face tabs spaces trailing lines space-before-tab newline indentation empty space-after-tab space-mark tab-mark newline-mark)
```

I tried checking the current value before toggling:
```elisp
(when (memq 'lines whitespace-active-style)
  (whitespace-toggle-options 'lines))
```
It does toggle off the whitespace long line coloring, but the next time whitespace is toggled off and on again, then `lines` gets added back to the `whitespace-active-style` list, which restores the long line coloring.

It seems like `whitespace-active-style` gets assigned the `whitespace-style` list:
https://github.com/emacs-mirror/emacs/blob/9dd95bf0b12c8ddba82acae741f944743e37cdd8/lisp/whitespace.el#L1992

Which is defined as:
```elisp
(defcustom whitespace-style
  '(face
    tabs spaces trailing lines space-before-tab newline
    indentation empty space-after-tab
    space-mark tab-mark newline-mark)
```
https://github.com/emacs-mirror/emacs/blob/9dd95bf0b12c8ddba82acae741f944743e37cdd8/lisp/whitespace.el#L283

Therefore assigning the whitespace styles without `lines`:
```elisp
    ;; Don't color whitespace long lines, by removing `lines' from the list.
    (setq whitespace-style
          '(face
            tabs spaces trailing space-before-tab newline
            indentation empty space-after-tab
            space-mark tab-mark newline-mark))
```
results in whitespace mode being shown without the long line coloring.

**Comment by d12frosted** [comment]
@JAremko ? 😸 do you accept the challenge?

**Comment by JAremko** [comment]
@JAremko  I think @sdwolfz  linting thingy #11251 will handle this for all types of files( not only .org)

**Comment by smile13241324** [comment]
Thank you for contributing to spacemacs :purple_heart:, cherry picked your commit into develop.

**Pull request closed without merging**
