### PR TITLE
[layers/+emacs/tabs] introduces tabs layer with Centaur backend

### PR DESCRIPTION
**Pull request by WarFox**
Adding `tabs` layer with `Centaur` tabs as backend

This layer is without customisation now with default values

Starting with a draft PR to gather comments/opinions

### CODE REVIEW

**Comment by duianto** [comment]
It seems to work.

#### Question:
Are the tabs hidden by design in some buffers?
- magit
- compile-log
- help

Maybe there's more, those were just the once I noticed during the quick test.

#### Key bindings

There's some issues with the `gt` and `gT` key bindings.
- In a `dired` buffer, `g` calls `revert-buffer`, and since it doesn't seem to have any visual change if nothings modified. Someone might try to press `gT`, and `T` opens a Change Timestamp prompt for the file under the cursor.
- In a `magit` buffer `gt` calls `magit-jump-to-tracked`, and `gT` doesn't have a binding so it's interpreted as `gt`.

`C-c t s` calls `centaur-tabs-counsel-switch-group` which is `ivy` specific.
Is there an equivalent command for `helm`?

The need for a helm command might be up in the air at the moment, since:
Helm development is now stalled · Issue #2386 · emacs-helm/helm - Google Chrome
https://github.com/emacs-helm/helm/issues/2386

but I would suspect that someone might take over the repo, or it could be forked.

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fbe9a4093)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git go graphviz haskell helm
            (javascript :variables javascript-backend 'lsp)
            lsp multiple-cursors org
            (python :variables python-backend 'lsp python-lsp-server 'mspyls)
            shell version-control tabs treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by WarFox** [comment]
@duianto thank you for taking your time to test this layer

> Are the tabs hidden by design in some buffers?

Yes, they are hidden in some buffers by design in https://github.com/ema2159/centaur-tabs

There is customisation available for that, should we add it to documentation?

https://github.com/ema2159/centaur-tabs/blob/a6e4eed2c228997fac6b93b9061a6eecea315583/centaur-tabs-functions.el#L79 
``` emacs-lisp
(defcustom centaur-tabs-hide-tabs-hooks
  '(magit-status-mode-hook
    magit-popup-mode-hook
    reb-mode-hook
    completion-list-mode-hook)
  "Set hooks for buffers in which it isn't desired to have tabs."
  :type '(repeat symbol)
  :group 'centaur-tabs)
```

> keybindings

I'm happy to remove `gt` and `gT` if it's conflicting with other modes

> C-c t s calls `centaur-tabs-counsel-switch-group` which is ivy specific.
> Is there an equivalent command for helm?

There is a helm integration available but the author is not a helm user and he won't be able to fix problems with it.
https://github.com/ema2159/centaur-tabs/blob/master/README.org#helm-integration

> You can integrate Helm with centaur-tabs for changing tab-groups. Just add helm-source-centaur-tabs-group in helm-source-list. Then you’ll be able to use (centaur-tabs-build-helm-source) function and bind it to any key you want. (I’m not a Helm user so I’ll not be able to solve problems related to this).


I haven't used helm before, but I'm going to try it out

**Comment by duianto** [comment]
>There is customisation available for that, should we add it to documentation?

It might be good to document how to show/hide tabs in specific modes.

The `(centaur-tabs-build-helm-source)` command shows an error:
>centaur-tabs-build-helm-source: Invalid function: helm-build-sync-source

I opened an issue upstream, with a possible fix.
centaur-tabs-build-helm-source "fix" https://github.com/ema2159/centaur-tabs/issues/124

As described in the issue, there seems to still be an issue with helm when multiple windows are open.

Could you squash the commits into one, and add a changelog entry,
to the New layers > Emacs section
https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop#emacs
```diff
1 file changed, 1 insertion(+)
CHANGELOG.develop | 1 +

modified   CHANGELOG.develop
@@ -343,6 +343,7 @@ sane way, here is the complete list of changed key bindings
 - templates (thanks to YasuharuIida and Eivind Fonn)
 **** Emacs
 - helpful (thanks to Johnson Denen, Andriy Kmit)
+- tabs (thanks to Deepu Mohan Puthrote)
 - verb (thanks to Federico Tedin)
 **** Email
 - notmuch (thanks to Francesc Elies Henar, Leonard Lausen, Willian Casarin,
```

**Comment by WarFox** [comment]
@duianto thank you for opening issue upstream

I've squashed commits and updated documentation

**Comment by duianto** [comment]
Thank you for contributing to Spacemacs. It's safe to delete your branch.
The changes have been applied to the `develop` branch.
Commit(s): https://github.com/syl20bnr/spacemacs/commit/8b888c6a082eebb9eccb5e4f7708cdd253b65f03

**Comment by WarFox** [comment]
Thank you 🎉

**Pull request closed without merging**
