### PR TITLE
Helm-spacemacs facelift

### PR DESCRIPTION
**Pull request by TheBB**
I added some faces. Also show leader keybinding for toggles, and I reversed the order for packages (the leftmost thing should be what you are primarily searching for). This means that the packages are not ordered by layer any more, but I think it's okay like this. I also refactored the FAQ source a bit since some of the lines were getting long.

The light blue you're seeing is `font-lock-type-face` and the dark gray is `font-lock-doc-face`. For the keybindings I went with the `helm-M-x` standard key face. I can change this of course if it turns out that these are terrible choices for some themes. We could also define our own faces.

packages

toggles

faq

### CODE REVIEW

**Comment by TheBB** [comment]
I see the keybinding didn't work exactly as planned. Gimme a sec...

**Comment by TheBB** [comment]
There, that's better. :-)

**Comment by syl20bnr** [comment]
:zap: Realtime fixes :bug: :gun: 

Very nice, I like it :+1: This is like night and day, the current sources make my eyes bleed now :sob:

**Comment by CestDiego** [comment]
Thank you for this..I'll inspect your code to see how to define faces in helm :D

**Comment by CestDiego** [comment]
@TheBB also, how do you have your helm thing on the minibuffer (bottom) and not on the top? D:

**Comment by TheBB** [comment]
@CestDiego Set `helm-echo-input-in-header-line` to `nil`.

For the faces I just propertize the strings in the source definitions.

**Comment by CestDiego** [comment]
@TheBB thanks :D now sweetgreen.el looks way prettier 
[alt](https://i.imgur.com/ij3XJaA.png)

**Pull request merged**
