### PR TITLE
Improve additional packages docstring

### PR DESCRIPTION
**Pull request by dalanicolai**
Many new users (quite logically) assume that the additional-packages list
behaves like installing a layer, so they assume the file is also loaded
automatically. This commit adds info about the requirement to also load the
package with load/require/use-package in the user-config section of the dotfile.

### CODE REVIEW

**Comment by dalanicolai** [comment]
My god... I just wanted to PR the last commit. Can you cherry-pick it? Or tell me how to correct it. Git keeps surprising me everytime, one day I will get it...

**Review by smile13241324 — APPROVED** [review]
Nice catch

**Comment by smile13241324** [comment]
No worries I can cherry pick your latest PR only.

**Comment by smile13241324** [comment]
and done.

Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

**Pull request closed without merging**
