### PR TITLE
Link git folder to the correct location.

### PR DESCRIPTION
**Pull request by Profpatsch**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Read the contribution guidelines. Do this against develop.

**Comment by Profpatsch** [comment]
I see.

**Comment by syl20bnr** [comment]
@Profpatsch that's ok I applied your commit against the develop branch, you don't need to resubmit it.
It will be pushed tonight to the github repo.
Thank you !

**Comment by Profpatsch** [comment]
Ah, thanks!

**Pull request closed without merging**
