### PR TITLE
fix evil-lisp-state prefixes & improve related functions

### PR DESCRIPTION
**Pull request by lebensterben**
- make sure `evil-lisp-state` related prefix keys are displayed correctly.
- `which-key-add-keymap-based-replacements` accepts multiple key-def pairs
  thus this commit allow `spacemacs/declare-prefix` to accept multiple inputs
  too.

### CODE REVIEW

**Comment by lebensterben** [comment]
@DrWaleedAYousef
Please pull this PR and restart emacs to see whether the prefix keys now correctly shows the descriptions instead of just "+prefix".

**Comment by DrWaleedAYousef** [comment]
I think it is the same. The `SPC-k` shows the `+lisp` menus.

**Comment by lebensterben** [comment]
@DrWaleedAYousef It should be the lisp menu, isn't it?

**Comment by DrWaleedAYousef** [comment]
> @DrWaleedAYousef It should be the lisp menu, isn't it?
> 
> To clarify, SPC k is the prefix for both smartparens and evil-lisp-state.

Yes, I know what you mean. I am confirmgin that it gives only the +lisp state. And the smartparens (the +prefix) does not exist.

**Comment by DrWaleedAYousef** [comment]
I have a hypothesis that I am testing now: I think the reason of this bug and of this #15106 as well is the `org` layer. I just started disabling it and every thing works fine now. I will confirm with you after some days of keeping it dissabled.

**Comment by lebensterben** [comment]
@DrWaleedAYousef
Please see the screenshot below.

You would see the smartparen bindings (those started with sp-) and the evil-lisp-state bindings (under prefix keys `, d, and D, near the end).

Screenshot_2022-01-10-50_1687x306

**Comment by DrWaleedAYousef** [comment]
Ok I will retry

**Comment by DrWaleedAYousef** [comment]
I tried several times to retart emacs and do `SPC-k`. It is very undeterministic! sometimes it gives the image that you shared above, and sometimes it gives only the three prefix keys!

**Comment by lebensterben** [comment]
@DrWaleedAYousef 
> and sometimes it gives only the three prefix keys

If you haven't opened any buffer, you would only see these three prefix. And this is not a bug.

Is that the case?

**Comment by DrWaleedAYousef** [comment]
> @DrWaleedAYousef
> 
> > and sometimes it gives only the three prefix keys
> 
> If you haven't opened any buffer, you would only see these three prefix. And this is not a bug.
> 
> Is that the case?

No; I open a buffer and simply do `SPC q r` to restart on the same buffer. However, I just noticed something. The correct menu only activates when I open a lisp file (`.el`). Then, it works correctly with any other file (e.g. `.tex`). However, if start with opening any other file it does now show up, unless I open a list file.

Also, aside issue is that at the start up this message appear: `Error (use-package): gnus/:init: replacement is neither a cons cell or a string`

**Comment by lebensterben** [comment]
@DrWaleedAYousef 
A few findings.

Previously I said `SPC k` is for `evil-lisp-state` and `smartparens` because I saw some bindings like `SPC k $` is bound to `sp-end-of-sexp`. This is technically correct but the twist is that those `sp-*` commands are actually `evil-lisp-state-sp-*` commands. That is, they're registered when `evil-lisp-state` configured the keymap and they are just wrapper functions calling the `sp-*` commands from `smartparens` package.

`evil-lisp-state` is *lazily loaded*. It's *fully loaded* only after you opened a buffer that derives from `prog-mode`.
- The three prefix keys are always there because they're registered via `which-key`, regardless of whether `evil-lisp-state` is loaded or not.
- If you just opened Emacs, or you opened the message buffer, scratch buffer, a `plaintext` file like .txt or .org, since none of them is `prog-mode`, `evil-lisp-state` is not loaded. And you would not see anything other than three prefixes.
- If you've opened a buffer for any programming language, it's `prog-mode`. And `evil-lisp-state would be fully loaded. And you should see the full list of commands as I showed in the screenshot.

---

> However, if start with opening any other file it does now show up, unless I open a lisp file.

Please describe what are 'any other file' you've opened.

**Comment by DrWaleedAYousef** [comment]
Thanks so much for these explanations. I just made a silly typo above; I said:
> However, if start with opening any other file it does now show up, unless I open a lisp file.
I just meant:
However, if start with opening any other file it does **not** show up, unless I open a lisp file.

So, when opening any other file, e.g., `.tex`, before I open a `.el` file, the `sp-*` does not show up.

**Comment by lebensterben** [comment]
@DrWaleedAYousef 
1. Open an .tex file. (Alternatively open an empty buffer and start `Tex-tex-mode` manually.
2. Evaluate `(derived-mode-p 'prog-mode)` and you will see `nil`. (It derives from text-mode instead)
3. As I said those bindings are loaded for `prog-mode`. And `.tex` file is not. That's why you don't see them.

If you're convinced and if you can confirm there's no other unexpected behaviour, then I'll merge this PR.

**Review by smile13241324 — APPROVED** [review]

**Comment by DrWaleedAYousef** [comment]
> 2\. (derived-mode-p 'prog-mode)

Ok; thanks for your patience. I am convinced. Just one remaining question: how then I can have the `sp-*` functionalities for the tex files natively? From wht you explained, the only way is to open a dummy file for any programing, .e.g., `.el`, then close it. Is there any natural way like adding something to the `.spacemacs`?

**Comment by lebensterben** [comment]
@DrWaleedAYousef 
I will merge this now but keep your original issue open.

**Comment by DrWaleedAYousef** [comment]
@lebensterben Just to confirm (to keep you posted) I am able to use all the keybindings of `sp-parens` *only* after opening, e.g., a lisp file and close it again.

**Comment by lebensterben** [comment]
@DrWaleedAYousef 

You should update in your original issue, not in this closed PR.

**Comment by DrWaleedAYousef** [comment]
Oh sorry; I thought it is the original post. I was rushing

**Pull request merged**
