### PR TITLE
[ipython-notebook] Change prefix from "ai" to "ay"

### PR DESCRIPTION
**Pull request by swaroopch**
Because "ai" is already being used for IRC (ERC)!

It's weird to say ipython-notebook stuff under "IRC"

### CODE REVIEW

**Comment by TheBB** [comment]
`"an"` is used for deft though. :-/

Would be good to figure out once and for all what to do in such cases.

**Comment by swaroopch** [comment]
Err, is there a catalogue of used key bindings? :)

**Comment by swaroopch** [comment]
Switching to `ay`, I believe it is unused...

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

We still need to figure out how to fix this problem of colliding bindings in different layers, though.

**Pull request closed without merging**
