### PR TITLE
Add Layer for the Factor Programming Language

### PR DESCRIPTION
**Pull request by timor**
Add support for the Factor programming language.  This includes `factor-mode` and `fuel-mode`.  Note that this is special in the sense that the factor elisp files are supposed to be installed site-wide already, as they come with the factor package.

### CODE REVIEW

**Comment by syl20bnr** [comment]
💜 
Can you add a `Feature:` section to the README. Example in Python layer: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/python/README.org#features

**Comment by timor** [comment]
Well, it really only exposes the features already present that come with FUEL and factor mode.  Should I try to highlight what that actually can do?  I understood the features section to describe what additional stuff has been added...

**Comment by syl20bnr** [comment]
Thank you ! 💜 
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by duianto** [comment]
Calling the snippet directory `:` (colon), might not work in windows.

When I try to pull the latest develop branch, then I get the following message:
>error: unable to create file layers/+lang/factor/local/snippets/factor-mode/:: Invalid argument

Outside Spacemacs, in the windows file explorer, if one tries to add a colon to a file or folder name, then the following message appears:
>A file name can't contain any of the following characters:
\ / : * ? " < > |

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c130014f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey helm emacs-lisp git org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by syl20bnr** [comment]
@duianto thank you for the report, can you open an issue for it ?

**Pull request closed without merging**
