### PR TITLE
Update Documentation.org

### PR DESCRIPTION
**Pull request by person808**

### CODE REVIEW

**Comment by justbur** [comment]
The bit about hybrid mode is not currently correct. The current implementation removes all vim bindings from insert state allowing those keys to pass through.

**Comment by person808** [comment]
@justbur fixed

**Comment by justbur** [comment]
@person808 Looks great thanks

**Comment by syl20bnr** [comment]
Very nice job :+1: 
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by justbur** [comment]
@person808 Sorry I spoke too soon. I didn't realize @syl20bnr was going to merge #2676 which actually makes your original statement about hybrid mode more accurate now.

**Pull request closed without merging**
