### PR TITLE
Update README.org

### PR DESCRIPTION
**Pull request by kimchichef**
neeed -> need

### CODE REVIEW

**Comment by duianto** [comment]
People follow incentives.

They took the time to find real typos, so they seem to be valid to me.

**Comment by robbyoconnor** [comment]
Yes, but they did literally one typo per PR -- this is not valid for Hacktoberfest.

**Comment by robbyoconnor** [comment]
@kimchichef Close this one too. You tried to game hacktoberfest and in the process, also ruined it for everyone else. 

If you want to make a good-faith contribution, then make all you typo fixes in one pull request.

**Comment by robbyoconnor** [comment]
For reference as to why I'm calling this out in bad faith is they did these one-word fixes to up their PR count for hacktoberfest, which ruined it for a lot of people.

**Comment by smile13241324** [comment]
Hi @kimchichef,

I had a look at your PR and have noticed that it is not adhering to our rules for a proper PR. You have no description of what you have changed and your commit message says nothing about what you did. In addition there is another PR #14001 which is almost identical to this one.

Both only do a very tiny change on the README which do not justify individual PRs.

Therefore I am going to close this PR now. If you are still interested in helping us, please open a new PR with a proper description, fixing all typos in the README you find and mention me as a reviewer.

Thanks
MAx

**Comment by NANASHI0X74** [comment]
I feel dirty, but I think I'm going to fix these :sweat_smile:

**Comment by robbyoconnor** [comment]
> I feel dirty, but I think I'm going to fix these

By all means but do it in one PR not 4

**Pull request closed without merging**
