### PR TITLE
Dired with coreutils gls

### PR DESCRIPTION
**Pull request by usharf**
Make `dired` use `gls` on OS X, if found (maybe installed with `brew`). 

If not available, make sure `ls` is called with legal options only, so to avoid this error:

```emacs-lisp
ls does not support --dired; see `dired-use-ls-dired' for more details.
```

### CODE REVIEW

**Comment by mkcode** [comment]
:+1:

**Comment by mkcode** [comment]
To install on OSX:

`
brew install coreutils
`

**Comment by syl20bnr** [comment]
Interesting PR, thank you!
I added some doc in commit f4670d6c7acede9ac18e7e0cb065224877b7140c
Cherry-picked in `develop` branch, you can safely delete your branch.

**Comment by usharf** [comment]
Thanks!

**Pull request closed without merging**
