### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nathan-boyd**
- Remove un-needed '$' symbol from shell command examples

Thank you for contributing to Spacemacs!

Before you submit this pull request, please ensure it is against the develop branch and not master.

This message should be replaced with a description of your change.

Thank you <3

### CODE REVIEW

**Comment by nathan-boyd** [comment]
Just a change in the readme

**Comment by edran** [comment]
@nathan-boyd adding `$ ` to all shell commands in docs is on purpose:

* it [usually] signals that the string is a shell command;
* it forces a lot of users to double read the command before running it (as most people will copy the whole string and run anything off the internet).

This PR should therefore probably be closed :)

**Comment by sdwolfz** [comment]
These were already removed on the `develop` branch.

**Comment by duianto** [comment]
This PR can probably be closed.

**Reason 1:**
>Before you submit this pull request, please ensure it is against the develop branch and not master.

The master branch is read-only.

**Reason 2:**
As stated by sdwolfz, the `$` characters have already been removed on the develop branch:
https://github.com/syl20bnr/spacemacs/blob/c130014ff0f263e14bd93786f880d2679958b484/README.md#macos

In this commit:
Add commands for font install on macOS https://github.com/syl20bnr/spacemacs/commit/419fc605ec20c2a23ddbbc6ccf8d94f4e4aa15f4

They will probably be removed on the `master` branch, when the next major version of Spacemacs is released (I don't know when that is).

**Pull request closed without merging**
