### PR TITLE
[Readme] Fix link

### PR DESCRIPTION
**Pull request by arifer612**
Fix dead link. Addresses #14860.

This is meant to replace #14871 since the original author had closed the PR. Addressing the open change request by @lebensterben, I credited the author of the page that the original link referenced to because I feel that it is important to give credit where it is due.

### CODE REVIEW

**Comment by dalanicolai** [comment]
Thanks for fixing. Just two small unnecessary comments. I would say these instructions are valid for most GNU/linux desktops in general. Also, I think the kudo's, although nice, are not so important here as it is only a small explanation for how to create a desktop file. I think it would fit better in the [CHANGELOG.develop file](https://develop.spacemacs.org/CONTRIBUTING.html#changelog-entry), because it would be too much if all small fixes like this get kudo's in the docs.
So if you like (and you agree) then you could update the PR, but otherwise, for me, it is fine like this also

**Comment by arifer612** [comment]
Got it! Moving it to the CHANGELOG.develop file makes sense.

**Comment by lebensterben** [comment]
merged. Thanks for your contributions.

**Comment by arifer612** [comment]
Thanks for the merge! Can you also help to close #14860 since this PR resolves that issue?

**Comment by lebensterben** [comment]
Closed now.

**Pull request merged**
