### PR TITLE
ycmd: Set global config only if not already set

### PR DESCRIPTION
**Pull request by naseer**

### CODE REVIEW

**Comment by naseer** [comment]
setting variable in my .spacemacs had no effect for flycheck, but worked for ycm. Making this change resolves the problem

**Comment by trishume** [comment]
:+1:

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
Cherry-picked into `develop` branch, you can safely delete your branch.

**Comment by syl20bnr** [comment]
Note that I removed the hardcoded path with the following method: 8a616cb04084c7ac9f08d47f581f83a6af6d3367

**Pull request closed without merging**
