### PR TITLE
Add bindings for local variable commands

### PR DESCRIPTION
**Pull request by lunaryorn**
- `fvd`: Add a directory variable
- `fvf`: Add a file variable
- `fvp`: Add a file variable to property line

### CODE REVIEW

**Comment by justbur** [comment]
:+1:

**Comment by TheBB** [comment]
Can you document these, please?

**Comment by justbur** [comment]
I wanted to do this, but I wanted a version that also automatically sets the variable to the value you specify. Is there anything wrong with doing that?

**Comment by lunaryorn** [comment]
@justbur I would not want that, and updating the variable values is just one `s-u` (`revert-buffer`) away, so I don't see the point in adding extra custom code.  You don't change local variables every minute, do you? :relaxed:

**Comment by lunaryorn** [comment]
@TheBB Of course.  If you could just tell me where the documentation for these commands should go :blush:

**Comment by TheBB** [comment]
With the [rest of `SPC f`](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#files-manipulations-key-bindings) I'm thinking.

**Comment by justbur** [comment]
@lunaryorn fair enough. Not a big deal

**Comment by lunaryorn** [comment]
@TheBB Alright, added.

**Comment by TheBB** [comment]
:+1:

**Comment by syl20bnr** [comment]
Very useful key bindings, I like the used mnemonic as well, thanks again for a great PR :+1: 
Cherry-picked into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
