### PR TITLE
Adapt for Magit's move to Transient

### PR DESCRIPTION
**Pull request by bmag**
Magit now uses Transient instead of magit-popup, and we must adapt. Also had to replace the recently removed `magit-diff-buffer-file-popup` with `magit-diff-buffer-file` (similar but doesn't offer a popup before displaying the diff).

Note some upstream packages haven't adapted to this change, but when they do we might need similar fixes:
- magithub
- magit-gitflow
- magit-svn

Related: https://github.com/syl20bnr/spacemacs/issues/11978

### CODE REVIEW

**Comment by duianto** [comment]
Could `magit-diff` be the new equivalent command?

This is what the `SPC g f d` (`magit-diff-buffer-file-popup`) popup looked like before:

emacs_2019-02-15_19-37-01

This is what `SPC g f d` (`magit-diff-buffer-file`) looks like now:

emacs_2019-02-15_19-32-26


This is what `M-x` `magit-diff` looks like now:

emacs_2019-02-15_19-54-46

And pressing `d` (for Dwim), shows a prompt: `Diff for range (magit-transient-PR):`
Pressing `RET` shows the same buffer as `SPC g f d` (second screenshot) but with a shorter buffer name `magit-diff: .emacs.d`.

**Comment by duianto** [comment]
Or if `magit-diff` isn't correct, then maybe `magit-file-dispatch` (`C-c M-g`) works better.

The popup looks different:

emacs_2019-02-15_20-19-07

but pressing `d` shows the same buffer as in the second screenshot above, with the long buffer-name (that includes the current file name).

Pressing `D` from that popup shows the same popup as in the third screenshot above.

**Comment by syl20bnr** [comment]
Thank you ! 💯

**Comment by domenzain** [comment]
Related: https://github.com/syl20bnr/evil-escape/issues/90
Although magit is useable, with the latest `develop`, `evil-escape` fails to escape from these transient windows.

**Pull request merged**
