### PR TITLE
Pull spacemacs-theme from MELPA

### PR DESCRIPTION
**Pull request by nashamri**
Pulls `spacemcas-theme` from MELPA directly.
I also deleted the old spacemacs-theme.

### CODE REVIEW

**Comment by TheBB** [comment]
Wouldn't it make sense to

* remove `spacemacs-theme` from the list of extensions, and
* move `spacemacs/init-spacemacs-theme` to `packages.el`?

**Comment by nashamri** [comment]
Yeah I guess moving `spacemacs/init-spacemacs-theme` to `packages.el` makes more sense. But if I remove `spacemacs-theme` from the extensions list, it wouldn't download it. My lack of knowledge :smile: !

**Comment by nashamri** [comment]
Hopefully this now works as intended. First time I mess with spacemacs core :smile:

**Comment by robbyoconnor** [comment]
Please merge :+1:

**Comment by syl20bnr** [comment]
This is it ! Spacemacs has its own theme and a high quality one, THANK YOU :+1: :+1: :+1:

Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
