### PR TITLE
Fix py yapf for yapf >= 0.3.0

### LINKED ISSUE #3023: Could not apply yapf. Check *yapf Errors* for details
@kennethlove I follow the config tutorial. I install `yapf` using `pip`, but I still cannot solve this problem.
And the `*yapf Errors*` is empty.

### PR DESCRIPTION
**Pull request by a-sk**
yapf >= 0.3.0 now returns 2 if source code was changed.
This should fix #3023 for users with updated yapf.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1:

**Comment by cpaulik** [comment]
I welcome this, but is there a reason why we can not apply this patch [upstream](https://github.com/paetzke/py-yapf.el) and ditch the local version of this package?

**Comment by a-sk** [comment]
Yeah, we should definitely do this.
I suppose py-yapf was not in MELPA at that time: #1120

**Comment by syl20bnr** [comment]
I merged this, I let you do the migration to the MELPA package in a separate PR.
Thank you !
Cherry-picked in develop branch, you can safely delete your branch.

**Pull request closed without merging**
