### PR TITLE
Added more keybindings to p4

### PR DESCRIPTION
**Pull request by snandan**
Listed all the important commands provided by 'p4' package and given some keybindings to them.

### CODE REVIEW

**Comment by tuhdo** [comment]
Nice. You should update the README as well.

**Comment by snandan** [comment]
Sure. please find the readme changes in 'e57dcc8'

**Comment by snandan** [comment]
Please ignore my changes in 'init.el' (fe6defa) I am not sure how to remove that from the 'pull requests' queue.

**Comment by syl20bnr** [comment]
Excellent :+1: 
Nice work!

Thank you,
Cherry-picked in `develop` branch, the init stuff has been ignored. Next time use a dedicated branch for your PR so you won't have the issue of mixing other commits with the PR commits.

**Comment by snandan** [comment]
Thanks Sylvain, Tu Do. Appreciate your work. I will create a different branch for PRs

**Pull request closed without merging**
