### PR TITLE
add c/c++ extension: disaster, disassemble c/c++ code

### PR DESCRIPTION
**Pull request by jb55**
https://github.com/jart/disaster

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1:

**Comment by person808** [comment]
It looks like this is on MELPA. I dont think an extension is needed.

**Comment by jb55** [comment]
oh really? for some reason I didn't see it when I checked. Will redo this.

**Comment by jb55** [comment]
Ok fixed :+1:

**Comment by jb55** [comment]
guess I can't reopen it after force pushing, will open a new PR

**Comment by robbyoconnor** [comment]
Why not leave it open and just rebase and force push?

**Comment by jb55** [comment]
I closed by accident, apparently github doesn't let you re-open after a force push :|

**Comment by robbyoconnor** [comment]
Same happened to me with a PR :(

**Pull request closed without merging**
