### PR TITLE
[layers/+lang/haskell] Removed intero, ghc-mod and company-ghci backends, set dante as default backend.

### PR DESCRIPTION
**Pull request by Martinsos**
@duianto and @smile13241324 : here is another PR for Haskell layer with changes that we discussed. Solves issues #13867 and #13868.

### CODE REVIEW

**Comment by michaelpj** [comment]
`ghc-mod` is also very obsolete, and I think could be removed.

**Comment by Martinsos** [comment]
@michaelpj true, thanks for pointing this out. On their repo they say: `Please note that using ghc-mod as a user facing tool for IDE/Editor integration is no longer supported or maintained. We are in the process of refocusing our efforts around haskell-ide-engine as the main user/IDE facing program.`. So I agree we should remove it also, I will add that to this PR.

**Comment by Martinsos** [comment]
All right, should be it now! Intero, company-ghci and ghc-mod removed, dante is default.

**Review by smile13241324 — APPROVED** [review]
Woah the entire layer looks much clearer now.

**Comment by Martinsos** [comment]
Ah yes, the best PR is the PR that removes a lot of code :)!

**Pull request merged**
