### PR TITLE
Paste TS: fix doc

### LINKED ISSUE #7249: paste-transient-state not working
#### Description :octocat:
I changed `dotspacemacs-enable-paste-transient-state` variable from `nil` to `t` in `dotspacemacs/init`, but see no effect.

*Observed behaviour:* :broken_heart:
Pressing <kbd>p</kbd> again will paste the last yanked text on the kill ring again.

*Expected behaviour:* :heart:
from Docs:
> Pressing <kbd>p</kbd> again will replace the pasted text with the previous yanked (copied) text on the kill ring.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. ac31e45)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm auto-completion better-defaults emacs-lisp git markdown org shell
                (shell :variables shell-default-position 'full)
                syntax-checking version-control python github javascript)
```

### PR DESCRIPTION
**Pull request by bmag**
fixes #7249

### CODE REVIEW

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Comment by darkfeline** [comment]
@TheBB Is there a reason why we're still using cherry-picks instead of rebase-and-merge?

**Comment by TheBB** [comment]
For single commit PRs, those two are essentially the same, no?

**Comment by darkfeline** [comment]
Essentially, yes, but GitHub also displays the relevant commit hash in the PR and closes the PR as merged.  It saves the tedium of posting "Thanks! Cherry-picked in develop. You can safely delete your branch." either manually or via script.

**Comment by syl20bnr** [comment]
I believe rebase-and-merge and what we do are not the same thing.
When we cherry-pick we avoid to create a merge commit. When I checked the debase-and-merge feature on the blog it seemed to be just a rebase of the PR + a merge commit.

**Comment by darkfeline** [comment]
@syl20bnr It doesn't create a merge commit; that's the point of the rebase, after all.

For example https://github.com/darkfeline/spacemacs/pull/10

**Pull request closed without merging**
