### PR TITLE
Updated some punctuation, syntax and grammar.

### PR DESCRIPTION
**Pull request by jsonify**
I wasn't sure how to squash the changes into one commit, as per the guidelines for contributing.

### CODE REVIEW

**Comment by TheBB** [comment]
Please branch off a recent develop before you make a PR. As you can see this PR has a bunch of commits from the master branch.

**Comment by robbyoconnor** [comment]
Close this PR as it is basically invalid.

**Comment by robbyoconnor** [comment]
Why leave this open if it's invalid @StreakyCobra ?

**Comment by StreakyCobra** [comment]
I'm a squirrel, I keep some closable issues/PRs hidden to pass the winter.

**Comment by robbyoconnor** [comment]
Just in case we catch up somehow...you feel better? I see..

**Comment by robbyoconnor** [comment]
I see that @TheBB doesn't keep closable PRS to pass the winter :P

**Pull request closed without merging**
