### PR TITLE
Add indent-guide package with toggles

### PR DESCRIPTION
**Pull request by ralesi**
`t I` for toggling indent-guides

### CODE REVIEW

**Comment by cpaulik** [comment]
Moving the keybinding to <kbd>SPC t h I</kbd> would be compatible with the proposed [highlight-indent toggles](https://github.com/syl20bnr/spacemacs/pull/936). But should we support both? I haven't used neither extensively so I can't say which one is better. indent-guide would have a global toggle which is not present for highlight-indent.

**Comment by ralesi** [comment]
The difference I saw was that highlight-indent, though looking nicer, took my computer much longer to scroll through the file, as it looks globally at the indent level.  Indent guides on the other hand only looks locally at the current code block and highlights the indentation of only the current line (similar to `highlight-current-column-mode`, though you are able to also make it show all indentation levels simulataneously. 

Personally, the look of `highlight-indentation` is nicer, but I didn't like the slow down. 

In the case of toggles, I haven't tried setting them up in `spacemacs` yet, but we could align on that as well based on the discussion.

**Comment by Funnnny** [comment]
Highligh-indentation is already in the packages, I don't see the point of supporting a layer with nearly the same functionality.

I'm agree that indent-guide is faster, but highlight-indentation has better color settings and match nicely with the theme.

**Comment by ralesi** [comment]
Are there features then in highlights indentation that we could modify to speed it up?

**Comment by Funnnny** [comment]
Actually, it's just the default settings that makes indent-guide faster.

Highlight-indentation just read the indentation offset, and display the guide with it. Indent-guide does some better parsing, so it will display better in mode with various offset (like lisp). So because of this, indent-guide will slow down a lot, try enable it in paradox packages.

**Comment by syl20bnr** [comment]
I like the fast feedback of `indent-guide`. To be honest, after having tested the 3 toggles, `indent-guide` seems the only one I would use regularly. I don't find `highlight-indentation` nicer but I had no problem with the navigation speed when it is enabled (I don't use smooth-scrolling).

I agree to have the 3 indentation modes.

**Comment by syl20bnr** [comment]
I confirm that `indent-guide` has performance issue :-(
Try navigating at the bottom of `spacemacs/packages.el` with it enabled.

**Comment by syl20bnr** [comment]
I merged it with the following changes:
- used the toggle macro with the key bindings `SPC t h I`
- added a delay of 0.3s to fix the performance issue
- the toggle is global
See commits: cf926a80bc3a4f1090e905882efaa982764a3dcf and af2dd525910479ddb267898ec4362a10fdc6dc11

Thank you ! :+1: 
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by syl20bnr** [comment]
@cpaulik @Funnnny @ralesi I moved the key binding to `SPC t i` to group it with `aggressive-indent` which is now on `SPC t I`. It makes sense to do so to me because `indent-guide` is not really an highlight. Moreover the toggle key matches the lighters on the mode-line.

**Pull request closed without merging**
