### PR TITLE
updated echo area documentation for auto-highlight symbol as I didn't kn...

### PR DESCRIPTION
**Pull request by mijoharas**
...ow about this. Tried to delete something after moving to it with `*` got confused when I got moved to the function that defined it. I don't know about the conventions on line length, what should you do when a string starts getting long (I feel like this should be split onto two lines but am unsure of the elisp conventions for doing this.)

### CODE REVIEW

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
Cherry-picked into `develop`, you can safely delete your branch.

**Comment by mijoharas** [comment]
Ok, cool. So I'm going to take that to mean that long lines aren't an issue if they're strings? is there an elisp style guide anywhere that you subscribe to? (whenever I start learning a new language I like to pick up the conventions too, as apart from the aesthetic side, it sometimes teaches you a few tricks)

**Comment by syl20bnr** [comment]
No special convention for a string in the minibuffer, in the code you could have break it by using `concat`.
The convention (at least in spacemacs) is to avoid going further than the 80th column.

**Comment by mijoharas** [comment]
ok, cool, I'll use concat next time (and I might go back and change that to use `concat` if I have the time/inclination.) Thanks.

**Pull request closed without merging**
