### PR TITLE
ivy: Add custom transient state

### PR DESCRIPTION
**Pull request by justbur**
Replace the hydra usually bound to C-o

@Andre0991 I saw your discussion and came up with this alternative.

### CODE REVIEW

**Comment by AlejandroCatalina** [comment]
Oh my, this is love <3 :+1:

**Comment by StreakyCobra** [comment]
@justbur Rhaaa, stop improving `ivy` that much, I'll have to switch to it otherwise :wink:

**Comment by Andre0991** [comment]
Excellent! This is way more intuitive.

Thank you  so much @justbur, I'm really happy with this.

**Comment by justbur** [comment]
See #4969

**Pull request closed without merging**
