### PR TITLE
Fix OSX mapping issue, because of a recent commit changed the way of …

### PR DESCRIPTION
**Pull request by liujoey**
A recent commit 2215ffe68d36c5a2f80b0830e2f7f19bb7803ce2 changed how CMD key was handled, this PR was trying to reflect that change on the CMD-1..9 key mapping for windows jumping.

### CODE REVIEW

**Comment by TheBB** [comment]
I don't use mac. Is this discussed in an issue somewhere, or is there broad consensus among mac users that this is how it should be? Possibly a stupid question, obviously.

**Comment by fiveNinePlusR** [comment]
Looks good to me as a mac user.

**Comment by syl20bnr** [comment]
This was expected, see https://github.com/syl20bnr/spacemacs/pull/8689
Thank you for the fix :-)

**Comment by syl20bnr** [comment]
Thank you ! 👍 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
