### PR TITLE
[WIP][CORE] synchronize the environment variables from the default shell

### PR DESCRIPTION
**Pull request by fiveNinePlusR**
hopefully fixes the env caching problem by spawning a shell and synchronizing the environment variables from that.

### CODE REVIEW

**Comment by bleggett** [comment]
This is generally and historically a macOS problem, so it probably makes sense to disable it by default on other platforms.

Also, it is only a problem with **vanilla** Emacs macOS builds, the main Emacs macOS porter [maintains a modified macOS build](https://bitbucket.org/mituharu/emacs-mac/overview) that patches the env var inheritance problem, so even for macOS I would like an option to disable this and not take the startup hit.

**Comment by fiveNinePlusR** [comment]
it is a problem in the main version that the spacemacs manual says to install though. It's not present on the emac-mac port but it's definitely a bug/doesn't import the shell env with emacs-plus.

**Comment by bleggett** [comment]
@fiveNinePlusR As long as I can disable it with no ill effects I'm fine with it. I know we want things to work with vanilla Emacs because that's what we want most people to use, but if vanilla Emacs is borked and I'm running a variant that's not I don't want to take the hit.

**Comment by fiveNinePlusR** [comment]
you should be able to put spacemacs-environment into your excluded packages and it should work fine. if @syl20bnr wants to we can add in a variable to disable it... something like `(defvar spacemacs-import-env t "import all environment values from your default shell")`

**Comment by bleggett** [comment]
Tested this PR on macOS/emacs-mac 26.1, I cannot detect or measure any significant perf hit, so I am fine with this as a non-toggleable workaround for vanilla Emacs.

**Comment by ljupchokotev** [comment]
Tested this PR with the `go` layer and I didn't find any issues. `GOPATH` and `GOROOT` are set, which means all the go tools work.

I didn't notice any performance hit either.

**Comment by syl20bnr** [comment]
Thank you ! 💜 

I made it asynchronous and added some dotfile variables for better control over it, see commits: https://github.com/syl20bnr/spacemacs/commit/9ee832955 and  https://github.com/syl20bnr/spacemacs/commit/d28990537

Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
