### PR TITLE
Add cscope layer keybinding to find assignments to symbol

### PR DESCRIPTION
**Pull request by dubnde**
Add cscope layer binding `SPC m g =` to `helm-cscope-find-assignments-to-this-symbol`

### CODE REVIEW

**Comment by LemmingAvalanche** [comment]
> Merge branch 'develop' of ...

I don’t know if merging `develop` into your branch is necessary when the collaborators are going to use cherry-pick to include your commit/patch into upstream `develop`.

**Comment by dubnde** [comment]
@LemmingAvalanche Doh! My mistake. Let me correct that. Thanks for seeing it.

**Comment by LemmingAvalanche** [comment]
Why did you close this?

**Comment by dubnde** [comment]
Thought to create a new/clean one

**Pull request closed without merging**
