### PR TITLE
fix(spacemacs-buffer): mouse click

### LINKED ISSUE #14964: Spacemacs buffer terminal mouse click on links appears broken
It seem that this line: https://github.com/syl20bnr/spacemacs/blob/develop/core/core-spacemacs-buffer.el#L91

Should instead bound to `mouse-1` and not to `down-mouse-1` as it does.

The way it is now, when I click on a link from a terminal Emacs, the link gets highlighted, but it doesn't navigate, and Emacs is stuck waiting for more input as if I have not finished typing a keychord:

> down-mouse-1 ESC [ < 0 ; 8 1 ; 1 9 ; m

I'm not too sure why this happens, but it prevents the click from working, and afterwards everything I type or click on just gets added to more commands on the keychord and it only stops if I `C-g`.

I tried to simply change it to:

```
(define-key map [mouse-1] 'widget-button-click)
```

And that seems to have fixed it.

### PR DESCRIPTION
**Pull request by lebensterben**
fixes #14964

### CODE REVIEW

**Comment by lebensterben** [comment]
@opie4624 @real-or-random 
Please review

**Comment by real-or-random** [comment]
Unfortunately this fixes it only partly.  :/

I get into visual select again by
 * double-clicking mouse left and then clicking mouse left, or 
 * clicking mouse right

**Comment by lebensterben** [comment]
@real-or-random 

This PR only intends to fix the left mouse click that it should open entries on spacemacs-buffer.

what you mentioned can be reported in a separate issue.

**Comment by real-or-random** [comment]
> This PR only intends to fix the left mouse click that it should open entries on spacemacs-buffer.

Okay, I see. 

The thing is that even without this PR here, opening entries with left mouse in fact works, also when I'm in visual mode after clicking somewhere.

**Comment by opie4624** [comment]
Fixes it for me!

**Comment by TheJJ** [comment]
thanks! it seems to be fixed for good now :)

**Pull request merged**
