### PR TITLE
Wrap init in file-name-handler-alist nil to speed it up

### PR DESCRIPTION
**Pull request by aaronjensen**
This shaves about 0.7s off of my init, or 7.8%

See
https://www.reddit.com/r/emacs/comments/3kqt6e/2_easy_little_known_steps_to_speed_up_emacs_start/
and https://github.com/hlissner/doom-emacs/wiki/FAQ#how-is-dooms-startup-so-fast

### CODE REVIEW

**Comment by aaronjensen** [comment]
I wonder if this will impact resuming layouts in some way? Where does that happen? Maybe we don't need to wrap that piece with the let.

**Comment by aaronjensen** [comment]
Ah, it looks like there may be a delay, so it may actually wait until init is completely done, so this is probably fine. It'd be great if someone else could test this out.

**Comment by aaronjensen** [comment]
ping @syl20bnr @TheBB @d12frosted @bmag @JAremko

**Comment by syl20bnr** [comment]
I can confirm the boost on several on my installs, nice one 👍 
Thank you again !
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
