### PR TITLE
General solution for underscores in word-motions

### PR DESCRIPTION
**Pull request by elcritch**
c.f. https://github.com/syl20bnr/spacemacs/issues/1261 

I am currently going between many programming languages and the current solution falls short for me. The 'prog-mode-hook seems to work pretty well.

Thank you for contributing to Spacemacs!

Before you submit this pull request, please ensure it is against the develop branch and not master.

This message should be replaced with a description of your change.

Thank you <3

### CODE REVIEW

**Comment by aaronjensen** [comment]
Seems like a good tip for people that want that.

Ready to be merged! (@syl20bnr @TheBB @d12frosted @bmag @JAremko)

**Comment by JAremko** [comment]
@elcritch  Sorry but  we accept PRs from only to the develop branch (based on develop branch)

**Comment by elcritch** [comment]
I'll port it over to the develop branch in that case.

Jaremy Creechley
creechley@gmail.com
το ευαγγελιον

**Comment by sdwolfz** [comment]
Thank you :heart:! 
And congratulations on your first Spacemacs PR :tada:!
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
