### PR TITLE
Added an icon file in OS X .icns format and a link to adding it to the

### PR DESCRIPTION
**Pull request by OliverM**
mac app bundle

### CODE REVIEW

**Comment by syl20bnr** [comment]
The icon is already available in the [spacemacs-logo](https://github.com/nashamri/spacemacs-logo) repository so you can remove it from the PR and update the documentation. Also with homebrew there is a flag to install emacs-mac-port with the spacemacs-logo.

**Comment by OliverM** [comment]
Done, and doc'd the emacs-mac-port flag too

**Comment by OliverM** [comment]
Fixed, thanks @jupl

**Comment by syl20bnr** [comment]
Thank you !
Cherry-picked into develop branch.

**Pull request closed without merging**
