### PR TITLE
Add a banner for my cute cate nemad momo

### PR DESCRIPTION
**Pull request by qoshi**
I have create a new banner same like my cute cat and her name is momo. So I name This banner as momacs.

### CODE REVIEW

**Comment by d12frosted** [comment]
Totally like it 😸

**Comment by syl20bnr** [comment]
Thank you !
I changed the index to 998 and add support `'cate` value for the dotspacemacs variable.
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by qoshi** [comment]
actually, it cat not cate, I miss spell it cuz I was a little bit excitingT_T

**Comment by syl20bnr** [comment]
Ok, I renamed it to `cat` in https://github.com/syl20bnr/spacemacs/commit/881b1f1

**Pull request closed without merging**
