### PR TITLE
core: fix typo

### PR DESCRIPTION
**Pull request by robbyoconnor**
There was a typo...I think...

### CODE REVIEW

**Comment by syl20bnr** [comment]
Thank you :+1: 
Cherry-picked.... you know the song :-)

**Comment by robbyoconnor** [comment]
:trumpet: :notes:  :notes:  :notes:  :notes:  :notes:  :notes:  :notes:  :notes:  :notes:  :notes:  :notes:

**Comment by robbyoconnor** [comment]
Is that the song?

**Comment by syl20bnr** [comment]
Right ! :guitar:

**Pull request closed without merging**
