### PR TITLE
Use built-in evil variable to set Y behavior.

### PR DESCRIPTION
**Pull request by person808**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1:

**Comment by TheBB** [comment]
Using this PR I can't get `nil` to work, i.e. setting `dotspacemacs-remap-Y-to-y$` to `nil` does not have the effect I expect. Do you see the same? The evil variable ends up with `t` anyway, and the `defcustom` for it doesn't make me any wiser.

**Comment by justbur** [comment]
Looks like it's being set too early. You need to call `dotspacemacs/init` first

**Comment by justbur** [comment]
Also if there's an evil setting that's exactly what is needed why can we just put that variable in the dotfile with a comment about how to use it? Is there any advantage to defining a dotspacemacs version in that case? If there is the dotspacemacs version could be an alias, no?

**Comment by justbur** [comment]
I think the advantage to having a dotspacemacs version of an evil variable is you know where it is set. The disadvantage is the reduced transparency. My proposal would be to do this in place of the `defvar` for `dotspacemacs-remap-Y-to-y$`
```elisp
(defvaralias 'dotspacemacs-remap-Y-to-y$ 'setq-default evil-want-Y-yank-to-eol)
```

**Comment by person808** [comment]
@TheBB fixed.

**Comment by TheBB** [comment]
Confirmed!

**Comment by robbyoconnor** [comment]
:+1:

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
