### PR TITLE
Improving html export

### PR DESCRIPTION
**Pull request by JAremko**
<ADD TODO>

### CODE REVIEW

**Comment by JAremko** [comment]
@syl20bnr  @bmag  I fixed CI like yesterday.  :roll_eyes:  Probably should've ping you earlier :smile:

**Comment by syl20bnr** [comment]
@JAremko  Do I have to cherrypick `CI test test` ?

**Comment by JAremko** [comment]
@syl20bnr   no  sry. Didn't know that you are merging :smile:

**Comment by JAremko** [comment]
@syl20bnr  I'll open another PR.

**Comment by syl20bnr** [comment]
:joy:

**Comment by JAremko** [comment]
@syl20bnr  You haven't cherry-picked it :confused:

**Comment by syl20bnr** [comment]
When the tag `merged` appears it means I merged it locally and will push soon.

**Pull request closed without merging**
