### PR TITLE
[haskell] Put the jump handlers straight into the buffer var

### LINKED ISSUE #12238: [Develop] Jump-to-definition is broken in haskell mode with dante
#### Description :octocat:
Jump-to-definition is broken in haskell mode with dante once again.

#### Reproduction guide :beetle:
- Start Emacs. Spacemacs develop branch.
- Using haskell layer with `(haskell :variables haskell-completion-backend 'dante)`.
- trigger `spacemacs/jump-to-definition` with `gd` or similar.

*Observed behaviour:* :eyes: :broken_heart:
It does "HELM Dumb jump" instead, which just searches for the string without knowing what a definition is.

*Expected behaviour:* :heart: :smile:
With dante it should do `xref-find-definitions`, which works when run manually.

As a workaround, setting `(spacemacs|define-jump-handlers haskell-mode xref-find-definitions haskell-mode-jump-to-def-or-tag)` in `layers/+lang/haskell/config.el` works, but this may break other backends that are not dante. I couldn't figure out the actual issue. There is an inconsistency between spacemacs-jump-handlers and spacemacs-jump-handlers-haskell-mode in haskell buffers, I'm not sure if that is correct behavior.

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e7e2283cf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git github gpu markdown html neotree org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control osx python javascript
      (haskell :variables haskell-completion-backend 'dante)
      c-c++ colors scala swift themes-megapack)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

### LINKED ISSUE #12289: Haskell: jump handlers aren't correct in the first buffer opened
#### Description :octocat:
Jump handlers aren't set properly for the first file opened in Haskell mode.

#### Reproduction guide :beetle:
- Configure Spacemacs with the haskell layer using intero
- Start Emacs
- Open one Haskell file
- Inspect `spacemacs-jump-handlers`
- Open a second Haskell file
- Inspect `spacemacs-jump-handlers`

*Observed behaviour:* :eyes: :broken_heart:
The (buffer-local) variable `spacemacs-jump-handlers` is different in the two buffers, in particular `intero-goto-definition` is present only in the second buffer's variable.

*Expected behaviour:* :heart: :smile:
The two buffers' value for `spacemacs-jump-handlers` should be the same.

#### Possible cause

Upon inspecting the haskell layer I noticed that `spacemacs-jump-handlers-haskell-mode` is modified in functions called from the mode hook. I'm guessing that the buffer variable `spacemacs-jump-handlers` is set based on the value of `spacemacs-jump-handlers-haskell-mode` prior to the mode hook being executed. At least that would explain why only the first buffer gets the wrong value but all following buffers have the correct value.

Unfortunately I'm not familiar enough with the load sequence to know exactly where the modifications to `spacemacs-jump-handlers-haskell-mode` should be set to get the desired behaviour. If I get a suggestion I'm more than happy to put together a patch.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e8e4c6338)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 dash docker evil-commentary evil-snipe git github gtags
 (helm :variables helm-no-header t)
 mu4e restclient
 (spell-checking :variables spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
 syntax-checking
 (clojure :variables clojure-enable-sayid t clojure-enable-clj-refactor t)
 emacs-lisp
 (haskell :variables haskell-completion-backend 'intero)
 shell-scripts graphviz html json latex markdown
 (org :variables org-enable-reveal-js-support t org-enable-github-support t)
 spacemacs-org
 (sql :variables sql-auto-indent nil)
 pandoc terraform yaml archlinux clipboard-fix)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

### PR DESCRIPTION
**Pull request by magthe**
Fixes #12238
Fixes #12289

### CODE REVIEW

**Comment by michaelpj** [comment]
Isn't this the exact opposite of what someone did earlier? https://github.com/syl20bnr/spacemacs/pull/11699/files

(I don't understand the difference, just seems odd.)

**Comment by magthe** [comment]
Well, based on what I've found out, and written about above

- the mode hooks seem to be run _after_ the buffer local `spacemacs-jump-handlers` is set, so trying to influence it by modifying `spacemacs-jump-handlers-haskell-mode` in a mode hook results in the first buffer having the "wrong" value for `spacemacs-jump-handlers`, and
- setting `spacemacs-jump-handlers-haskell-mode` is really only necessary to do _once_ so it arguably shouldn't ever be set in a mode hook.

So, maybe that change actually _broke_ things, or maybe the behaviour of setting `spacemacs-jump-handlers` changed _after_ that change so that it stopped working. I'm not sure, all I know is that it's broken ATM. :man_shrugging: 

I'll be happy to get some input on how this _should_ be done, e.g. by setting `spacemacs-jump-handlers-mode` exactly once, while still setting it correctly based on the chosen completion backend (which influences the jumping).

**Comment by magthe** [comment]
Any chance of getting this reviewed, or comments on the issue it addresses?

**Comment by duianto** [comment]
I don't know anything about haskell, but I might have gotten it installed and setup correctly.

The following are the results of trying to replicate the two issues that this PR marks as `fixes`:
[Develop] Jump-to-definition is broken in haskell mode with dante #12238
Haskell: jump handlers aren't correct in the first buffer opened #12289

Example files:
`haskell-test.hs`
```haskell
-- https://www.schoolofhaskell.com/school/to-infinity-and-beyond/pick-of-the-week/Simple%20examples

import System.Info

main = do
    print os
    print arch
    print compilerName
    print compilerVersion
```

`haskell-test-2.hs`
```haskell
-- https://www.schoolofhaskell.com/school/to-infinity-and-beyond/pick-of-the-week/Simple%20examples

import System.Environment

main = do
    getArgs >>= print
    getProgName >>= print
    getEnvironment >>= print
```

## Dante

With Dante, after (re)starting Spacemacs, then a HELM buffer has to be opened at least once (with for example: `SPC SPC`), before pressing `g d`.

It's an issue with helm being lazy loaded, it's not related to this PR.

If a Helm buffer hasn't been opened first, then nothing happens `g d` is pressed.

### Before PR

#### First file

With cursor on the first instance of `print`.
Pressing:
`g d`, `, g g` or `, g G` opens: `HELM Dumb Jump Choices`

`spacemacs-jump-handlers` contains:
```elisp
(haskell-mode-jump-to-def-or-tag evil-goto-definition dumb-jump-go)
```

#### Second file
With cursor on the first instance of `print`.
Pressing:
`g d` or `, g g` opens: `HELM Dumb Jump Choices`
`, g G` opens: `HELM Xref Find Definitions`

`spacemacs-jump-handlers` contains:
```elisp
(xref-find-definitions haskell-mode-jump-to-def-or-tag evil-goto-definition dumb-jump-go)
```

### After PR

#### First file
With cursor on the first instance of `print`.
Pressing:
`g d` or `, g g` opens: `HELM Dumb Jump Choices`
`, g G` opens: `HELM Xref Find Definitions`

`spacemacs-jump-handlers` contains:
```elisp
(xref-find-definitions haskell-mode-jump-to-def-or-tag evil-goto-definition dumb-jump-go)
```

#### Second file
With cursor on the first instance of `print`.
Pressing:
`g d` or `, g g` opens: `HELM Dumb Jump Choices`
`, g G` opens: `HELM Xref Find Definitions`

`spacemacs-jump-handlers` contains:
```elisp
(xref-find-definitions haskell-mode-jump-to-def-or-tag evil-goto-definition dumb-jump-go)
```

## Intero

Pressing: `g d` with Intero seems to load helm automatically, therefore a helm buffer doesn't need to be opened first.

### Before PR
#### First file
With cursor on the first instance of `print`.
Pressing:
`g d`, `, g g` or `, g G` opens: `HELM Xref Find Definitions`

`spacemacs-jump-handlers` contains:
```elisp
(haskell-mode-jump-to-def-or-tag evil-goto-definition dumb-jump-go)
```

#### Second file
With cursor on the first instance of `print`.
Pressing:
`g d`, `, g g` or `, g G` opens: `HELM Xref Find Definitions`

`spacemacs-jump-handlers` contains:
```elisp
(intero-goto-definition haskell-mode-jump-to-def-or-tag evil-goto-definition dumb-jump-go)
```

### After PR

#### Both First and second file
With cursor on the first instance of `print`.
Pressing:
`g d`, `, g g` or `, g G` opens: `HELM Xref Find Definitions`

`spacemacs-jump-handlers` contains:
```elisp
(intero-goto-definition haskell-mode-jump-to-def-or-tag evil-goto-definition dumb-jump-go)
```

**Comment by magthe** [comment]
@duianto Just to check that I've read and understood, that was a _long_ comment saying that

1. both the issues exist, and
2. the change in this PR fixes both issues?

**Comment by duianto** [comment]
The first issue with `dante` might only be partially solved, because `g d` still opens `HELM Dumb Jump Choices`. But `, g G` does open the expected `HELM Xref Find Definitions` buffer.

The second issue with `intero` seems to be fixed, because the jump handlers are the same for both the first and second opened files.

I think we can cherry pick this to the develop branch and let the first issues author test it to see if it works as expected. I might not have setup haskell correctly.

**Comment by CthulhuDen** [comment]
I've not been writing any Haskell lately, but I've just checked and it seems goto definition currently isn't working in `develop` branch (again), but it does with this fix, so I guess this is now the way to go. I really wish new stable release was out already.

**Comment by duianto** [comment]
Thank you for contributing to Spacemacs!
The PR has been cherry-picked into the `develop` branch, you can safely delete your branch.
Commit: https://github.com/syl20bnr/spacemacs/commit/37dcecbec9220e9359e27741640be67040bf9ab3

@CthulhuDen Thanks for testing this.

**Pull request closed without merging**
