### PR TITLE
Make `org-projectile` integration compatible with its new version

### LINKED ISSUE #8045: Changes coming to org-projectile
I have a pretty serious refactor coming for org-projectile (work is happening at https://github.com/IvanMalison/org-projectile/tree/big-changes, but I have not put most of the changes there yet.)

I'm going to try to keep it as backwards compatible as possible, but there may be some things that I'm not able to do this for.

As I'm not a spacemacs user, I'm not sure if spacemacs is able to pull packages from melpa-stable or something like that, but it may be a good idea to do so for org-projectile if possible. If not I can always make a pull request to try to ensure that thing still work in spacemacs, but things may not work for users with old version of spacemacs

### PR DESCRIPTION
**Pull request by IvanMalison**
Fixes  #8045

### CODE REVIEW

**Comment by d12frosted** [comment]
Many thanks for the PR! ❤️ 💯 

Ok, I tried to apply it, but it seems that latest version is not on MELPA, so `org-projectile-per-project` is not defined for me. I am going to wait for MELPA to update and then I'll merge this.

Reference commit: https://github.com/IvanMalison/org-projectile/commit/977ad410e2e436b5006fd544fd5938136ab1b651

**Comment by aaronjensen** [comment]
I believe this is on MELPA now @d12frosted, I've got it and am broken.

**Comment by d12frosted** [comment]
@aaronjensen Yeah, it's already there 😸

**Comment by d12frosted** [comment]
Thank you :+1: Cherry-picked into `develop`, you can safely delete your branch.

**Comment by aaronjensen** [comment]
tooofast. Thanks!

**Comment by lululau** [comment]
```elisp
(defun org/init-org-projectile ()
  (use-package org-projectile
    :commands (org-projectile-location-for-project)
    :init
    (progn
      (spacemacs/set-leader-keys
        "aop" 'org-projectile/capture
        "po" 'org-projectile/goto-todos)
      (require 'org-projectile))
    :config
    (if (file-name-absolute-p org-projectile-file)
        (progn
          (setq org-projectile-projects-file org-projectile-file)
          (push (org-projectile-project-todo-entry
                 nil nil nil :empty-lines 1)
                org-capture-templates))
      (org-projectile-per-project)
      (setq org-projectile-per-project-filepath org-projectile-file))))
```

@IvanMalison The arguments passed to `org-projectile-project-todo-entry` does not match definition of the func:

```elisp
(cl-defun org-projectile-project-todo-entry
    (&rest additional-options &key (capture-character "p")
           (capture-template org-projectile-capture-template)
           (capture-heading "Project Todo"))

   ...function body...
)
```

**Comment by IvanMalison** [comment]
oops. Yeah, I forgot that that was changed. Looks like those arguments became keyword arguments. I think all of the nils can simply be erased.

**Comment by lululau** [comment]
It seem there exist declarations only for these three keyword args: `capture-character`, `capture-template` and `capture-heading`, no declaration for `empty-lines`.

**Comment by IvanMalison** [comment]
@lululau it takes a rest parameter. so the other options should be included there. They are passed on at a later point.

**Comment by IvanMalison** [comment]
@lululau Hmm looks like that function needed a &allow-other-keys

Fixed here: https://github.com/IvanMalison/org-projectile/commit/c39d28d925916ee7e08a879d5d9dd2287b3b9184

**Comment by zer09** [comment]
It looks like this fix introduced other issue the ```counsel-projectile``` is not working anymore. after this commit.

**Comment by aaronjensen** [comment]
@zer09 try it with https://github.com/syl20bnr/spacemacs/pull/9380 to see if that helps.

**Comment by zer09** [comment]
@aaronjensen thanks, I tried it and it works gracefully.

**Pull request closed without merging**
