### PR TITLE
Basic Gnus contribution layer

### PR DESCRIPTION
**Pull request by cpaulik**
This is my first try at a gnus contribution layer. Related to issue #386.
Features:

- Org-mime integration
- evilified Gnus Buffers
- Open RSS Articles directly in Browser

### CODE REVIEW

**Comment by CestDiego** [comment]
I checked this for my config : http://blog.binchen.org/posts/notes-on-using-gnus.html#sec-5

**Comment by cpaulik** [comment]
This is a great article. 

The main issue I'm having with a gnus contribution layer is to decide what to include because there are so many options.

**Comment by CestDiego** [comment]
Whatever that goes inside that feels like pushing it onto users should have info on how to extend on it and the articles used as reference. So as to make it easier for people to override it in their own config. We should only go for a very basic setup. I'm fine with even just having the gmail thingy to work and some things like spacemacs//gmail-username spacemacs//gmail-passwd to be setted up at the config... or even better add support for authinfo for it :P

**Comment by syl20bnr** [comment]
Great layer ! :+1: 
Thank you !
Cherry-picked into `develop` branch, you can safely delete your branch.

**Comment by autosquid** [comment]
This layer is too basic, and not friendly at all. Comments from @CestDiego is of key importance.
Current layer is a waste of the "Gnus" name. I can not have a private layer named 'gnus' now.

**Comment by cpaulik** [comment]
@autosquid Feel free to improve upon it.

**Comment by CestDiego** [comment]
:+1: @autosquid if you want to extend on it you can have a `my-gnus` layer and have `my-gnus/post-init-gnus` and `my-gnus/pre-init-gnus` functions to extend it.

**Pull request closed without merging**
