### PR TITLE
Yet another modeline fix

### PR DESCRIPTION
**Pull request by TheBB**
Hopefully the last one.

### CODE REVIEW

**Comment by CestDiego** [comment]
omg not only does this make perspectives not f*ck up the modeline...but it actually makes the perspective name show up! :O *nice work* @TheBB

**Comment by CestDiego** [comment]
There is sth about the face that makes it look ugly though... @nashamri 
[alt](https://i.imgur.com/oVt6TNK.png) <- Spacemacs-dark

[alt](https://i.imgur.com/gm7RuIt.png) <- monokai

[alt](https://i.imgur.com/1XI3Tp7.png) <- spacemacs-light


[alt](https://i.imgur.com/zMVsfC9.png) <- leuven

**Comment by TheBB** [comment]
@CestDiego Why don't you have any minor mode indicators? Should I be worried?

**Comment by CestDiego** [comment]
@TheBB ah no... I actually don't like the ones that show `yasnippet` and stuff... D: I mean...for me at least they are useless.

**Comment by nashamri** [comment]
is the last segment of the modline (the [@spacemacs]) what you referring to @CestDiego?

**Comment by TheBB** [comment]
@nashamri Yes, that is `persp-selected-face` AFAIK.

**Comment by syl20bnr** [comment]
@CestDiego I'm surprised about this empty segment too. Have you "diminished" all the lighters ?

**Comment by syl20bnr** [comment]
Also you have like a forward slash in two of the screenshots, this should not happen I believe.
Did you revert the commits for the new powerline segments at one point ?

**Comment by nashamri** [comment]
Yeah the forward slash separator is not present in spacemacs-theme. Needs investigation.

**Comment by TheBB** [comment]
I think the forward slash you see is just the rightmost separator and the leftmost separator on the right side being squeezed together because the window is small. That slash is the empty middle part being uncharacteristically small.

**Comment by CestDiego** [comment]
@nashamri Yes, the perspective face is the one.

For the diminished minor modes I think i did something with the toggle...
```
  (setq spacemacs-mode-line-minor-modesp nil)
  (setq spacemacs/mode-line-battery-time 1)
```

The first one is for the minor modes...and the other one is for the battery (which I can't see ;_;) If separators make a space there then maybe there is something wrong with the variable @syl20bnr  @TheBB

**Comment by CestDiego** [comment]
Let's take it to gitter :+1: 
:point_up: [July 27, 2015 3:22 PM](https://gitter.im/syl20bnr/spacemacs?at=55b692f688d69e9839a3e46d)

**Comment by TheBB** [comment]
Okay, @syl20bnr I'll let you know when this is ready.

**Comment by TheBB** [comment]
Pretty sure this is ready now. :sleeping:

**Comment by syl20bnr** [comment]
@TheBB Thank you ! :+1: 
You can go to bed now :moon: :smile:

**Pull request merged**
