### PR TITLE
Add key bindings to spacemacs-base

### PR DESCRIPTION
**Pull request by beta1440**
Add key bindings for goto-line and zap-to-char

### CODE REVIEW

**Comment by Beta1440** [comment]
I realized that "Ng" might be a better key binding for goto-line

**Comment by Beta1440** [comment]
May I ask which documentation you are referring to? From what I understand, the `spacemacs-base` layer doesn't have a README like other layers do.

**Comment by TheBB** [comment]
DOCUMENTATION.org in the root directory serves as the documentation for all the `spacemacs-*` layers.

**Comment by Beta1440** [comment]
I've added the keybindings to the DOCUMENTATION.org file

**Comment by Beta1440** [comment]
I'm planning on adding more keybindings to spacemacs-base on this pull request so that I can squash them all together.

**Comment by Beta1440** [comment]
I've done adding key bindings

**Comment by TheBB** [comment]
Are these necessary for emacs editing style users? Most of the bindings feel quite superfluous from the POV of an evil user.

**Comment by Beta1440** [comment]
It's true that most of these keys are basic.Emacs has bindings for most of them, but I'm adding these key bindings since it makes it easier for beginners to discover them. I want to reduce the need to remember obscure key bindings.

**Pull request closed without merging**
