### PR TITLE
add lsp-javascript-flow to javascript-backends

### PR DESCRIPTION
**Pull request by robert-zaremba**
Adding LSP JavaScript Flow backend to the `javascript` layer.
This is highly anticipated feature and was requested many time.

### CODE REVIEW

**Comment by sei40kr** [comment]
https://github.com/syl20bnr/spacemacs/pull/10927/files
I was working on Flow support (and I've completely forgot about that).
As written in the PR, Flow support has many problems to solve. Most difficult one is syntax highlighting.
`flow-js2-mode` works but it's not perfect.

**Comment by sei40kr** [comment]
I hope my old PR helps you a lot. There implements more Flow features.
I did not use LSP for Flow, because `lsp-mode` uses a same server in same major mode.

**Comment by robert-zaremba** [comment]
Hi @sei40kr 
The solution I propose here works out of the box: syntax highlighting, error checking, type hints, jump-to-definition ...
Not sure what do you mean with: "lsp-mode uses a same server in same major mode." ?

**Comment by yyoncho** [comment]
This pr is no longer relevant with the latest lsp mode since it has several breaking changes. Take a look at #11626

**Comment by sei40kr** [comment]
@robert-zaremba 
Sorry for my poor English.
AFAIK, flow-minor-mode doesn't provide syntax highlighting.
And flow-bin overlaps flow-language-server, so it shouldn't be invoked together.

**Comment by robert-zaremba** [comment]
@yyoncho  Thanks for the link. AFAIS your PR doesn't touch the JavaScript layer. 

I've rebased my updates on the latest develop (which include your changes). The `lsp-ui` stopped working, but all other functionality works (flow, type-checks, jumps, etc...). Could you advise what should I change to make it working again? Also - do you think I should rebind the `C-c C-j` to `M-.`?

**Comment by Compro-Prasad** [comment]
> Also - do you think I should rebind the `C-c C-j` to `M-.`?

Yes, `M-.` is the standard keybinding in Emacs for `jump-to-definition` related stuff. But in most of jumps `M-,` helps in jumping back to the previous location. So, if `C-c C-j` makes use of the marker stack in Emacs then `M-.` is a good switch but if it doesn't then try defining a function that does the same.

**Comment by smile13241324** [comment]
@robert-zaremba @yyoncho  can you tell is this PR still relevant for the javascript layer, especially for LSP support? From the last post of yyoncho I read that the changes would be obsolete compared with current javascript layer can you describe a bit more what your PR does and how it fits in with the javascript backend architecture applied in the javascript layer as of today?

If it is still relevant, and fits in with the existing backends in the layer aka not breaking anything, please rebase to develop and fix the conflicts. I will then happily review and merge it.

**Comment by yyoncho** [comment]
@smile13241324 emacs-lsp/lsp-mode#603 was later reverted so I think that we will need some code in spacemacs but I think that the current approach is wrong. AFAIK you should be able to use typescript/flow-language server in one project at the same time and the server will be selected from lsp-mode based on the presence of the flow header. So, I think that there should be only one backend - `lsp` and spacemacs should let lsp-mode select the correct language server.

**Comment by robert-zaremba** [comment]
I'm using this patch and it works well. Let me test tomorrow if it's needed or not.

**Comment by robert-zaremba** [comment]
I've checked the latest version.
Indeed, `lsp` supports the type exploration. However the following features are missing:

* using `flow` for jumps (`*goto*`)
* flow syntax handling (eg through `flow-js2-mode`)

I'm going to decline this PR. Currently I'm using the following configuration to support `flow` in spacemacs:

```
;; in dotspacemacs-configuration-layers
(javascript :variables javascript-backend 'lsp )

;; in dotspacemacs/user-config
  (add-hook 'js2-mode-hook
            (lambda ()
              ;(flow-js2-mode)
              (define-key js2-mode-map (kbd "C-c C-j") #'flow-minor-jump-to-definition)))
```

I've added `flow-js2-mode` to `dotspacemacs-additional-packages`.

One idea would be to add `flow-js2-mode` to the `javascript` layer end enable it by default. What do you think?

**Pull request closed without merging**
