### PR TITLE
Add binding to connect to REPL in Cider

### PR DESCRIPTION
**Pull request by jcsims**
A fairly simple keybinding add - I use it frequently in my work, and I imagine others do as well.

### CODE REVIEW

**Comment by nwolfe** [comment]
@jcsims Is this different than `SPC m s i` (`, s i`) for `cider-jack-in`?

I believe this is a the standard "launch the REPL" command that works across all Lisp languages, which explains why it might not be a mnemonic for `cider-jack-in`.

**Comment by jcsims** [comment]
@nwolfe It is indeed different - cide-jack-in starts a new REPL session, where cider-connect connects to an already-running REPL session. In anything outside of a standalone dev environment, this is how you would connect to a REPL.

**Comment by nwolfe** [comment]
@jcsims Ah, makes sense. Thanks for the explanation.

Out of curiosity, what are the benefits of running the REPL outside of Emacs?

**Comment by jcsims** [comment]
If it's any kind of running process (for example in production, testing,
etc), you need to be able to connect to an already running REPL using
nREPL (the networked REPL) to peek into its internals, and do all the
regular fun REPLy things.

Or, if you don't use lein or boot, emacs/cider won't necessarily know
how to actually start a REPL.

--Chris


On Fri, May 8, 2015, at 11:47 AM, Nate Wolfe wrote:
> @jcsims[1] Ah, makes sense. Thanks for the explanation.


> Out of curiosity, what are the benefits of running the REPL outside
> of Emacs?


> — Reply to this email directly or view it on GitHub[2].

>



Links:

  1. https://github.com/jcsims
  2. https://github.com/syl20bnr/spacemacs/pull/1537#issuecomment-100324964

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
Cherry-picked in `develop` branch.

**Pull request closed without merging**
