### PR TITLE
Add home buffer recent files numbers

### PR DESCRIPTION
**Pull request by duianto**
Prepend numbers to the Recent Files list.
and bind the number keys to open that file.

Before:

emacs_2021-01-27_16-40-00

After:

emacs_2021-01-27_16-36-16

Fixes: Is it able to show the index of the recent files/projects in spacemacs home page? #12519

And possibly: Improve keybindings on spacemacs buffer (home buffer) #14230

### CODE REVIEW

**Comment by lebensterben** [comment]
I've tested this and it works great.
Do you think we can expand this idea to other parts?

For example, `r N` goes to `N`-th recent file, and `p N` goes to `N`-th project etc.

**Comment by duianto** [comment]
Thanks for testing. I'll merge this now.

Additional features can be handled in a new PR.

For example:
Maybe the first startup list in `dotspacemacs-startup-lists`:
```
   dotspacemacs-startup-lists '((recents . 5)
                                (recents-by-project . (7 . 5))
                                (bookmarks . 5)
                                (projects . 7)
                                (agenda . 5)
                                (todos . 5))
```
could exclude the prefix (only show the numbers).

**Comment by duianto** [comment]
### Issue:
I forgot to test with more than the default 5 recent files.

The home buffer breaks when there are more than 9 recent files.
The messages buffer shows:
>progn: Key sequence 1 0 starts with non-prefix key 1

**Comment by duianto** [comment]
I found a possible solution: 
Limit home buffer recent files numbers to 9 https://github.com/syl20bnr/spacemacs/commit/38a314f7ccf2f9fe702e3d5fdbe3e6eb1eac4a4f

**Comment by winsphinx** [comment]
This is a pretty work. Thanks a lot.
However, I met such an issue -- when i open a file (eg No.3) and edit it and close it (with key ~spc b d~), now emacs returns back to home buffer. Then i try to open it again i press key ~3~, another file is opened. The reason is that the No3 file is last opened and is on the place of No1, but in `recent files` list, it keeps on No3.
Would this issue be checked?

**Comment by duianto** [comment]
Confirmed.

The `recentf-list` has updated in the background but the home buffer still shows the previous order.

The number keys on the home buffer calls commands like this one:
`(recentf-open-most-recent-file-1)`

which opens that item in the `recentf-list`.

One solution might be to update the home buffer when a file is saved,
and the home buffer is open in another window.

possibly like this:
```elisp
    (defun spacemacs-buffer/refresh-in-other-window ()
      (when (get-buffer-window spacemacs-buffer-name)
        (save-selected-window
          (switch-to-buffer-other-window spacemacs-buffer-name)
          (spacemacs-buffer/refresh))))

    (add-hook 'after-save-hook 'spacemacs-buffer/refresh-in-other-window)
    ;; (remove-hook 'after-save-hook 'spacemacs-buffer/refresh-in-other-window)
```

**Comment by duianto** [comment]
It's probably not a good idea to refresh it on every file save.

A PR has been opened with a possible solution:
Fix home buffer recent files order after file save #14472

**Pull request merged**
