### PR TITLE
Do not override user customisation of projectile on windows.

### PR DESCRIPTION
**Pull request by puzl**
[Edit TheBB: removed text that specifically says to remove]

### CODE REVIEW

**Comment by TheBB** [comment]
Why though? Is it a problem to set these variables in dotspacemacs/user-config?

**Comment by TheBB** [comment]
See https://github.com/syl20bnr/spacemacs/pull/5168 for discussion about a more comprehensive solution to the “customize problem”. Checking for boundp might not be sufficient.

**Comment by puzl** [comment]
I really like using my customisation file because I set it to live outside of the .emacs.d directory.  I can then version control it and have it survive reinstalls of spacemacs etc.

I agree replacing the setq calls everywhere is laborious.  

Executing the custom-file after user-config has run might work.  Wouldn't it be better to have spacemacs do this automatically, whether or not custom-file has been modified by the user.

**Comment by TheBB** [comment]
Of course, that is what I am proposing.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/pull/7483

**Comment by syl20bnr** [comment]
Thank you for the PR, I pushed a commit which delays the application of custom settings, they are now applied after `user-config`.

See commit: https://github.com/syl20bnr/spacemacs/commit/e699f18

**Pull request closed without merging**
