### PR TITLE
tmux: fix for break in master

### PR DESCRIPTION
**Pull request by aaronjensen**
**This pull request must be against master, please do not close without reading**

This is a fix for #5975 

https://github.com/syl20bnr/spacemacs/commit/34438273889b7e8bf9dedc0ecd406cb9919616e8 was pulled into master without https://github.com/syl20bnr/spacemacs/commit/33ead6fc42700a6000ef10a662ceff604f3f8e51 which broke the tmux layer.

I'm guessing that https://github.com/syl20bnr/spacemacs/commit/33ead6fc42700a6000ef10a662ceff604f3f8e51 is not ready for master, so the fix can only be applied directly to master.

### CODE REVIEW

**Comment by aaronjensen** [comment]
@syl20bnr @TheBB there are now a couple issues open for this, it'd be great to get it merged to master to fix it please. Thanks!

**Comment by jamesla** [comment]
Since this is taking a while to get merged into master I thought I would ask if anybody had figured out a workaround? Not being able to navigate tmux panes has quite a detrimental effect on workflows!

**Comment by aaronjensen** [comment]
@jamesla cherry pick 66e6307

**Comment by justjake** [comment]
Can  we please get this merged?

**Comment by ajoslin** [comment]
:+1: patch works great for me, no problems. I'd love a merge as well.

**Comment by tthew** [comment]
+:1: Can also confirm that this patch works for me.

**Comment by syl20bnr** [comment]
I need to block an evening to make a 105 release, I hope to do so this week.

**Comment by syl20bnr** [comment]
Thank you ! 💜 
Backported to 0.105.21
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
