### PR TITLE
IETF related layers and packages.

### PR DESCRIPTION
**Pull request by choppsv1**
Adds 2 new layers and an exporting package for org mode, all related to doing work in the IETF.

New Layers:
- +misc/ietf :: Support for packages related to IETF work (loading, reading and writing RFCs).
- +lang/yang :: Support for YANG modeling language

### CODE REVIEW

**Comment by smile13241324** [comment]
Thanks for contributing these two new layers to Spacemacs! :+1: 
The PR has been cherry-picked into the develop branch, you can safely delete your branch.

I have made two small changes on your commit before merging:
* I have added two lines to CHANGELOG.develop for you
* and fixed a small loading issue in the `ietf layer` causing `ox-rfc` not to be found by `org-export-dispatch` when not called manually before.

**Comment by robbyoconnor** [comment]
Did nobody test this? 
```
Found 2 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: irfc@ietf... [2/2]
Package irfc is unavailable. Is the package name misspelled?
```

**Comment by smile13241324** [comment]
I did test this before 4 days I think, there all packages where properly installed. However I also noticed yesterday that after the package update `irfc` package is gone now.

However I have thought this would be a temporary issue with elpa and ignored it for now. I will have a look this evening.

**Comment by smile13241324** [comment]
Ok looks like `irfc` is not longer on `elpa` the documentation suggests installing it manually so I will change the package declaration to use a local version instead.

**Comment by robbyoconnor** [comment]
They removed all emacswiki packages from melpa apparently

**Comment by choppsv1** [comment]
Are we good to go on deleting the branch now? I'm a little confused about a message that says there are branch has unmerged commits. Thanks for the merge BTW.

**Comment by robbyoconnor** [comment]
Yes.

Spacemacs uses cherrypicking vs merging so it will appear unmerged, but
the commits are there.

**Pull request closed without merging**
