### PR TITLE
Bother robbyoconnor

### PR DESCRIPTION
**Pull request by JAremko**
test

### CODE REVIEW

**Comment by JAremko** [comment]
If I @<NAME> someone in a commit message will <NAME> receive some kind of notification ?

**Comment by JAremko** [comment]
Doesn't seem to do anything.

**Comment by robbyoconnor** [comment]
:monkey: :hocho: :shipit:

**Comment by robbyoconnor** [comment]
image

**Comment by JAremko** [comment]
@robbyoconnor   You received email?

**Comment by robbyoconnor** [comment]
Yup. That's a clip of the inbox :) I have Message Filters set up...if I didnt -- I'd go insane

**Comment by JAremko** [comment]
Hm... I contacted GitHub support:
```
When you mention someone in a commit message (for example, @jaremko) and this commit becomes a part of a public PR the person should be notified.

We could use this mechanism with Travis CI (it has TRAVIS_COMMIT_MESSAGE var) to make sure that the commit message includes mention of a person that is responsible for the affected code. It will make code reviewing easier.
```
 and @danayel said that  they'll add it to `feature request list`

```
Hello,

Thanks for reaching out. I can see how this would make it easier to notify people who ned to review or check on a commit.

I can't make any promises, but I have definitely added it to the feature request list and will share it with the team for consideration.
```

:confused:

**Comment by JAremko** [comment]
@robbyoconnor  do you have same setting?

**Comment by robbyoconnor** [comment]
Very likely

**Comment by JAremko** [comment]
Then I assume it didn't work on me because I already saw commit or because it is mine and it didn't work on my smurf because it's not subscribed to Spacemacs.

**Comment by JAremko** [comment]
It can only mean one thing. It is time for more spam :shipit:

**Comment by JAremko** [comment]
It works! I'm just retarded. It was wrong email  :dizzy_face:

**Comment by robbyoconnor** [comment]
> It works! I'm just retarded. I was checking wrong email  :dizzy_face:

You said it, not me!

**Pull request closed without merging**
