### PR TITLE
Add dynamic list of workspaces in transient state

### PR DESCRIPTION
**Pull request by TheBB**
This vanished in the move to transient state.

### CODE REVIEW

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Comment by TheBB** [comment]
Why, you're welcome of course.

**Comment by StreakyCobra** [comment]
:facepalm:

**Comment by syl20bnr** [comment]
:-)

**Comment by a13ph** [comment]
That brightened my day :laughing:

**Pull request closed without merging**
