### PR TITLE
sql: add layer

### PR DESCRIPTION
**Pull request by BrianHicks**
This PR adds a SQL contribution layer, which really just sets a bunch of key bindings and defaults for `sql-mode`.

### CODE REVIEW

**Comment by BrianHicks** [comment]
I noticed a typo in the keybindings this morning and have force-pushed another single commit. The final commit should be f3ed7cb.

**Comment by BrianHicks** [comment]
Is this up to spec? Do I need to change anything before it's mergeable?

**Comment by syl20bnr** [comment]
It is a great layer :+1: 
Sorry for the delay I did not have the time to merge it before.
I updated it to match the [conventions](https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.md#repls). I did not finish it though, there are two TODOs [here](https://github.com/syl20bnr/spacemacs/tree/develop/contrib/lang/sql/packages.el#L84-L86) and [here](https://github.com/syl20bnr/spacemacs/tree/develop/contrib/lang/sql/packages.el#L101).
I changed `SPC m s s` to `SPC m s f` since `SPC m s s` is to show SQLi buffer, and the paragraph can match the idea of a function.
I think that `SPC m b s` does not show SQLi buffer but only shows its name.
I implemented all this without testing it, I just refered to the function docstrings to see what they do, I hope I did not break too much things.
Related commit: https://github.com/syl20bnr/spacemacs/commit/81706ba

Thank you, great PR :+1: 
Cherry-picked into `develop`, you can safely delete your branch.

**Comment by BrianHicks** [comment]
@syl20bnr I've implemented the TODOs you had in the source, I'm just about to sign off for the weekend but I'll fix the docs up and submit a PR probably Monday.

**Comment by syl20bnr** [comment]
Excellent ! Have a good week end :-)

**Pull request closed without merging**
