### PR TITLE
Swift contribution layer

### PR DESCRIPTION
**Pull request by usharf**
Basic support for Swift (scripting).

Only customization for Spacemacs available is basic support for switching back and forth from the REPL.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Next time do a search -- duplicate of #2536

**Comment by TheBB** [comment]
This one seems more complete though.

CC @myrjola

**Comment by robbyoconnor** [comment]
Still -- it seems like duplicate work is better done collaboratively on the same PR -- similar to what happened with #2845

**Comment by usharf** [comment]
Hmm... pretty sure I did... anyhow, this one adds the edit-to-repo roundtrip and setup flychecking.

**Comment by robbyoconnor** [comment]
@usharf -- Personally (my opinion doesn't carry any weight other than I care) -- I'd leave it.

**Comment by myrjola** [comment]
@usharf Good work! I closed my pull request as it does bring fever things to the table than yours. Let's hope yours gets merged.

**Comment by usharf** [comment]
:+1: @myrjola

**Comment by d12frosted** [comment]
It has some problems.

1. You need to set `flycheck-swift-sdk-path` to something like `"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk"`. Otherwise you'll see `File mode specification error: (void-variable flycheck-swift-sdk-path) ` on visiting swift file. So it should be part of installation guide. 
2. After that when you visit swift file you'll see another problem - `eval-after-load: Symbol's value as variable is void: swift`. How to fix that I am not sure :-P

**Comment by d12frosted** [comment]
Plus, `swift-mode` doesn't support swift 2.0, so it's kinda pointless at this point.

**Comment by syl20bnr** [comment]
At @TheBB request I merged it, if there are some issues with it, don't hesitate to mention them in the README.
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
