### PR TITLE
Add toggle for mouse click events

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
I got the suggestion to [make a toggle for mouse click events](https://twitter.com/spacemacs/status/613335292666195968) so I got this pull request. Let's start a discussion whether we want this feature in Spacemacs.

Rationale: I often click on the Emacs window to focus it and, coming from console vim, it was never a problem. Unfortunately, Spacemacs relocates the cursor to the random area I clicked, so the focus jumps to some random place. Personally, I only move the cursor using the keyboard, so I wanted to disable it altogether.

This pull request adds a new function to enable and disable the default evil mouse bindings (`spacemacs/mouse-binding`, this part works) and a toggle (this part does not work, for some reason).

I don't know any Emacs Lisp, so I am completely open to suggestions on how to improve it and hope to get it merged eventually.

Looking forward to your suggestions!

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
I've just read the contributing docs and would rebase onto the `develop` branch and squash it into a single commit once this feature would be good to go. Sorry for the current meh-state of the PR.

**Comment by syl20bnr** [comment]
No need to create a new PR, I can do all this on my side.
I'll merge it soon, thank you.

**Comment by syl20bnr** [comment]
I tested and fixed the toggle and it works but I I find this feature hard to explain, I mean either we completely disable the mouse or we don't. This PR only disable the single click.
Unfortunately disabling all the mouse events is not so easy, especially if we want to make a toggle. Moreover some major modes can bind some actions to mouse events and the toggle won't be able to to anything for this.

I can't believe there is no easy way in Emacs to ignore the mouse.

**Comment by syl20bnr** [comment]
I posted a question here: http://emacs.stackexchange.com/questions/14246/is-it-possible-to-disable-the-support-for-the-mouse

**Comment by Leonidas-from-XIV** [comment]
> I mean either we completely disable the mouse or we don't.

Yes, sure, completely disabling the mouse is fine with me. I just did it for single click, because that was by far the most annoying one.

**Comment by robbyoconnor** [comment]
@TheBB can you close this as it's invalid.

**Comment by Leonidas-from-XIV** [comment]
@robbyoconnor Why would it be invalid?

**Comment by TheBB** [comment]
It's submitted against master instead of develop.

**Comment by Leonidas-from-XIV** [comment]
I was about to rebase it, but @syl20bnr said it is ok, https://github.com/syl20bnr/spacemacs/pull/2120#issuecomment-117432241.

**Comment by robbyoconnor** [comment]
then leave it :)

**Comment by syl20bnr** [comment]
@Leonidas-from-XIV thank you for the PR :+1: 

Since there is no reliable way to disable the mouse and I have no update on the SE question I prefer to close this PR.

It may be useful to add this trick to the HOWTOs.org file though.

**Pull request closed without merging**
