### PR TITLE
 add-company-backends must be called at post-init-company otherwise w…

### PR DESCRIPTION
**Pull request by carlos-wong**
…ill cause call void define function

Thank you for contributing to Spacemacs!

Before you submit this pull request, please ensure it is against the develop branch and not master.

This message should be replaced with a description of your change.

Thank you <3

### CODE REVIEW

**Comment by carlos-wong** [comment]
@non-Jedi Hi, you are right. I am remove the useless progn

**Comment by carlos-wong** [comment]
@non-Jedi how's going on with this pull request?

**Comment by non-Jedi** [comment]
@carlos-wong I'm not a maintainer; was just trying to help out. Sorry. On another note, it does look like you need to rebase on develop.

**Comment by carlos-wong** [comment]
@syl20bnr Hi, How's going on with my patch? Can you merge now?

**Comment by Miciah** [comment]
A layer does still need to have an init function for a package in order for that layer to own the package and make sure the package gets installed.  Specifically, you need to keep `html/init-company-web`, `lua/init-company-lua`, and `restclient/init-company-restclient`, even if they are empty.  For example:
```emacs-lisp
(defun html/init-company-web ())
```
Disclaimer: I'm not a maintainer either; also just trying to help out.

**Pull request closed without merging**
