### PR TITLE
 resolve the geolocation conflicts

### PR DESCRIPTION
**Pull request by declanqian**
Trying to make #3476 work

### CODE REVIEW

**Comment by syl20bnr** [comment]
@declanqian I still have conflicts, can you rebase the PR branch on top of develop ?

**Comment by declanqian** [comment]
Hi, I just rebase this branch on the latest develop branch. And test the auto change theme fun and `sunshine-forecast`. And they work fine. Credits goes to @usharf . 
Some notes:
* the osx location services need to turn on wifi
* And `calendar-*` need be set in `user-init`.

Correct me if I do this wrong:)

**Comment by syl20bnr** [comment]
Thank you :+1: 
I added your comments above to the README, but I think the calendar stuff should work if set in `dotspacemacs/user-config` (not `dotspacemacs/config` which is deprecated).
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by syl20bnr** [comment]
@declanqian Sorry but the squash removed you from the commit authors, my sincere apologies for this.

**Pull request closed without merging**
