### PR TITLE
Add missing commands to omnisharp layer

### PR DESCRIPTION
**Pull request by retran**
Add some missing omnisharp commands.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
`git pull --rebase` **not** `git pull` 

also rebase and squash these into one commit.

**Comment by retran** [comment]
Done.

**Comment by robbyoconnor** [comment]
Also add documentation for these commands to the README...when you add any commands or keybindings, always update the README.

**Comment by retran** [comment]
Added new commands to README.

**Comment by d12frosted** [comment]
Oh, this is nice PR. Thanks for bringing `omnisharp-navigate-to-current-file-member`. I usually call it by name, but having keybinding would be really nice.

**Comment by d12frosted** [comment]
@syl20bnr Any chances that it will be merged?

**Comment by retran** [comment]
Any news? ;)

**Comment by TheBB** [comment]
Sorry, sometimes PRs go too long. This looks reasonable to me. I'll label it so I won't forget.

**Comment by TheBB** [comment]
Thank you! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
