### PR TITLE
Buffer specific bindings - buffer micro state

### PR DESCRIPTION
**Pull request by ralesi**
`b d` to kill buffer
`b l` to list buffers

### CODE REVIEW

**Comment by tuhdo** [comment]
`helm-buffers-list` is redundant with `helm-mini`.

**Comment by ralesi** [comment]
Really? I have thought it showed an abbreviated list. Sometimes I don't find what I am looking for with it. But maybe I need to search to see it

**Comment by tuhdo** [comment]
`helm-mini` comprises of 3 sources *by default*:

- The buffer list.
- Recentf list: the list of most recently visited files.
- Create new buffer if nothing found.

`helm-buffers-list` only includes 2 *by default*:

- The buffer list.
- (Disabled) Virtual Ido buffers, which are most recently visited files but pretend like unopened buffers. That's why it's called virtual. To enable this source, you have to set `ido-use-virtual-buffers` to `t`.
- Create new buffer.

Both `helm-mini` and `helm-buffers-list` uses the same `helm-source-buffers` for retrieving buffers, so for selecting buffer they are essentially the same. You can filter buffers to not include in the list with `helm-boring-buffer-regexp-list`.

>  I have thought it showed an abbreviated list.

What do you mean by an abbreviated list?

**Comment by ralesi** [comment]
Yep, you proved me wrong.  I was thinking for some reason that the `helm-mini` list only showed a limited number of entries on default.  I just opened up 20 buffers and see that they are all listed in the `mini` buffer.  I will remove it from the PR.

**Comment by ralesi** [comment]
Updated to include buffer micro-state with `b .` binding

**Comment by syl20bnr** [comment]
Nice micro-state.
I made the following modifications:
- `N` instead of `p` to match the conventions (I know about emacs `p` conventions, but I have to choose either one and since it is `n/N` in the conventions, I keep ip for historical reasons).
- `K` instead of `k` because `k` can be hit very easily to quit the micro-state so it was a bit violent to kill the buffer (or even several)

Related commit: af06a20348904f79571e77842777e6b519d5507e

Thank you ! :+1: 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
