### PR TITLE
restclient: add helm support to jump to variable or request

### PR DESCRIPTION
**Pull request by tko**
Enable restclient-helm that is included in restclient package and add
`SPC m j` key binding.

### CODE REVIEW

**Comment by tko** [comment]
Split off from #6323 . Seems like `SPC s j` and `SPC i j` are already allocated key bindings for the same - or extremely similar - functionality, but I don't know if one should simply override the keys or somehow hook up to Imenu. I don't know anything about imenu.

**Comment by syl20bnr** [comment]
Thank you ! 👍 
I removed the bindings `gj` and `gk` to keep the default Vim behavior.
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by syl20bnr** [comment]
Oops wrong PR ;-)

**Comment by syl20bnr** [comment]
Thank you ! 👍 
I moved the key binding to `SPC j i` since it nicely fits the purpose of it.
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
