### PR TITLE
Include magit/forge SQLite db file in .gitignore

### PR DESCRIPTION
**Pull request by Asgavar**
Where by `forge` I mean: https://github.com/magit/forge

### CODE REVIEW

**Comment by nixmaniack** [comment]
As of now magit/forge isn't included in spacemacs. Once it's included it'd be better to setup `forge-database-file` inside `~/.emacs.d/.cache`(as per general convention of spacemacs package configs) than add it to `.gitignore`.

**Comment by sdwolfz** [comment]
Thank you :heart:! 
And congratulations on your first Spacemacs PR :tada:!
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by syl20bnr** [comment]
Ok already done actually. I think this is safe to revert as it should not be necessary.

**Comment by syl20bnr** [comment]
Seems that `forge` creates the file in `.emacs.d` when installing...

**Comment by Miciah** [comment]
> Seems that `forge` creates the file in `.emacs.d` when installing...

Do we need to set `forge-database-file` earlier? Maybe in `layers/+source-control/github/config.el`?

**Pull request merged**
