### PR TITLE
git: migrate git{attributes,config,ignore}-mode to git-modes

### PR DESCRIPTION
**Pull request by lebensterben**
fixes https://github.com/syl20bnr/spacemacs/issues/15111

### CODE REVIEW

**Review by bhipple — APPROVED** [review]
Would be really nice to get this in; every startup my emacs is hanging for ~30 seconds trying to find the 3 removed packages, since I cleared out my old melpa cache :)

**Comment by robbyoconnor** [comment]
Add the packages to your `dotspacemacs-excluded-package` list in your `.spacemacs` or `~/.spacemacs.d/init.el`. This will fix things.

**Comment by robbyoconnor** [comment]
The other option is to merge this locally into your fork.

**Review by smile13241324 — APPROVED** [review]
:+1:

**Pull request merged**
