### PR TITLE
Add a command for reporting issue to spacemacs

### PR DESCRIPTION
**Pull request by StreakyCobra**
Offer a Spacemacs command to open a new issue on Github with the message pre-filled with the template.

Actually better than this, the template already includes:

- the output of `SPC h d s`
- the backtrace if the `*Backtrace*` buffer exists
- It's possible to include the last pressed keys by using the prefix argument (`SPC u`)

I know `SPC e r` may not be the best (**e**rror **r**eport), I also thought about `SPC d r` (**d**ebug **r**eport), but I don't really care what it is, I can easily change it if you want something else :-)

### CODE REVIEW

**Comment by robbyoconnor** [comment]
YES! I love you @StreakyCobra :heart: :smile_cat:

**Comment by greasynose** [comment]
It's a good idea that can make spacemacs better and better.

**Comment by robbyoconnor** [comment]
> It's a good idea that can make spacemacs better and better.

:+1:

**Comment by CestDiego** [comment]
I'd worry about sensible data in the `*backtrace*` buffer but I guess one can hope no developer puts sensible data in the `*backtrace*` .

Having said this, this is great! thank you for this @StreakyCobra  :) will try to use this.

**Comment by d12frosted** [comment]
@StreakyCobra :+1: 

```
I'd worry about sensible data in the *backtrace* buffer but I guess one can hope no developer puts sensible data in the *backtrace* .
```

:laughing:

**Comment by robbyoconnor** [comment]
Developers who put shit like that in the backtrace need to be taken out back and shot.

**Comment by StreakyCobra** [comment]
:+1: Thx guys.

Concerning the backtrace, this system is not directly creating the PR, it is just opening the page with the message pre-filled. I hope people will review the full message before creating it :wink:. Also I don't see any reason to put information in the `*Backtrace*` buffer in purpose. And backtraces usually don't contain sensitive information. So everything put together I don't think it is a problem to include it if the buffer exists.

It is a little bit different for last pressed keys, hence the warning.

**Comment by JAremko** [comment]
As a Spacemacs newbie I often add nonsense into the `.spacemacs` file. It might be better to also include the file.

**Comment by StreakyCobra** [comment]
@JAremko Sadly it is not possible nor wanted because:

- This file may contain sensitive information such as password, login, IP, etc…
- There is a size limit on the URL that is used to pre-fill the issue. The default `.spacemacs` file is *probably* already to big for this

**Comment by JAremko** [comment]
@StreakyCobra [You can create gist](https://developer.github.com/v3/gists/#create-a-gist) with a `.spacemacs` file.  But sure. It might be overkill.

**Comment by StreakyCobra** [comment]
@JAremko Indeed, but I prefer to do it on-demand, it's a too much sensitive file :-)

**Comment by syl20bnr** [comment]
Excellent :purple_heart: 
To make it even better we could open a buffer in spacemacs to edit the template and use `C-c C-c` to commit and open the issue in the browser.
I moved the key binding to `SPC h I`, I was not comfortable with `SPC e r`.
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by StreakyCobra** [comment]
> To make it even better we could open a buffer in spacemacs to edit the template and use C-c C-c to commit and open the issue in the browser.

Added to my todo list. Once I'll have found the max URL request size I can check it directly in the buffer.

**Pull request closed without merging**
