### PR TITLE
[Fix #1668] Don't enable Vim key bindings if holy-mode

### LINKED ISSUE #1668: `C-k` and `C-j` is not usable for holy-mode in Python REPL
Since `comint-previous-input` is bound to `C-k` and `comint-next-input` is bound to `C-j`.

### PR DESCRIPTION
**Pull request by tuhdo**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1:

**Comment by syl20bnr** [comment]
@tuhdo just for reference, what's the alternative in emacs world ?

**Comment by tuhdo** [comment]
People use default key bindings: `M-n/M-p` in place of `C-j/C-k`. Currently I cannot delete with `C-k`, which is annoying. `C-r` is the default. The only thing that does not exist is `C-l`. I will update my PR to exclude `C-l`.

**Comment by tuhdo** [comment]
I updated and add comments. Actually, `C-l` is also an important default key binding for Emacs user that cannot be changed.

**Comment by syl20bnr** [comment]
@tuhdo I agree with these modifications but there is an issue that need to be resolved. This should work dynamically when a user switches between the 2 styles so we cannot only do it at initialization time.

What I propose is to implement a macro to easily be able to provide a variant for vim and emacs style for a given command.

**Comment by tuhdo** [comment]
We can do it later in another PR. This issue makes Python REPL unusable for Emacs users.

**Comment by syl20bnr** [comment]
Right, I'll add a comment. Don't do it, I'm going to merge it.

-syl20bnr-

**Comment by syl20bnr** [comment]
Thank you !
Cherry-picked into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
