### PR TITLE
Not retoggle fullscreen/maximized on `SPC f e R`

### PR DESCRIPTION
**Pull request by MadAnd**

### CODE REVIEW

**Comment by TheBB** [comment]
This PR is pretty old and we have some new toys now. It would be better to add a status to the toggles and instead call `(spacemacs/toggle-...-on)` in `config.el`, wouldn't you say?

**Comment by MadAnd** [comment]
@TheBB thanks for mentioning about new toggles approach, I didn't tracked the recent changes in upstream.

@syl20bnr I have rewritten the commits in this PR. Please review them on you spare time. Thanks.

**Comment by TheBB** [comment]
Thanks! Finally got around to merging this. :-)

It's now safe to delete your branch.

I made a change in https://github.com/syl20bnr/spacemacs/commit/69b14b49507612cc076520b7823d90abcf24c0a2. On my computer, it was the `fullscreen` frame parameter that indicated maximized state, and not `maximized`. If this is incorrect on other systems please let me know so I can add it back in with an `or` or something.

**Comment by nixmaniack** [comment]
@TheBB Thank you!

Seven months!!!

**Comment by MadAnd** [comment]
@TheBB nice catch! The proper frame parameter name is indeed `fullscreen`. 

FYI, `maximized` is just temporary frame parameter, so the frame will go to the right maximization state
after disabling fullscreen mode. In emacs 25 it was [renamed](https://github.com/emacs-mirror/emacs/commit/02138cb0b88c5f6addf891d725967d9867eda3f9) to `fullscreen-restore`.

Thanks for merging.

**Pull request closed without merging**
