### PR TITLE
add projecttalk links

### PR DESCRIPTION
**Pull request by manukall**
this adds links to the spacemacs messageboard at projecttalk.io

i noticed you get quite some usage questions in the issues. i think a message board is a bit better suited for those. the badge would make that more visible. 

i know you already have gitter as "community help", but i think a chat sometimes just isn't the best way to receive help.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
[read the guidelines](https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONTRIBUTE.org) -- This is invalid. @syl20bnr, @TheBB

**Comment by manukall** [comment]
hey @robbyoconnor,
what do you mean? i actually read through the guidelines and couldn't find anything wrong. should i have made this against the develop branch?

if you don't want to use ProjectTalk that is completely fine of course. just want to make sure it's not some technicality that i missed.

**Comment by TheBB** [comment]
Yes, he means you should have made it against the develop branch.

I can't answer whether we would like to sanction a projecttalk room... that's really up to @syl20bnr.

**Comment by manukall** [comment]
ok, got you. i thought that master would be fine, because it only touches the readme. i'll create another PR against develop if that's fine with you.

btw, it's not really rooms you get on ProjectTalk. it's more like an "old fashioned" message board that is just better integrated into Github. for example we just added the "Moved to ProjectTalk" label which you can add to github-issues to have them automatically moved to ProjectTalk. use case is to steer usage discussions away from the github issues so they can be more easily used as proper bug tracker.

**Comment by robbyoconnor** [comment]
The issue was that you should first check if it's fixed in `develop` because if it is, then it's will be merged to `master` when the next version is released.

**Comment by robbyoconnor** [comment]
The issue was that you should first check if it's fixed in `develop` because if it is, then it's will be merged to `master` when the next version is released.

**Comment by robbyoconnor** [comment]
Something like this should have had an issue first...for me...not having to go to different places it worth it...**WHY** add another thing to the mix?

**Comment by mbertheau** [comment]
I personally think forums are a very ineffective way of communication, though compared to the gitter chat they have a notion of a topic that can be discussed over the course of several days without being interrupted by discussions about other topics. This is quite impossible on gitter.

Maybe links to projecttalk can be added in a less assertive manner, i.e. "some community members prefer a forum for discussion and they hang out at <link to projecttalk>".

Another alternative is to link to the emacs stackexchange spacemacs tag, although maybe we're doing that already.

We may indicate which of these communication channels community members with a special role frequent, and which they don't. This way we provide guidance for a new user where to turn for help, without inhibiting the development of a new communication channel.

**Comment by mbertheau** [comment]
And in the interest of honesty, I will add that this PR is @manukall 's first contribution in this repo: https://github.com/syl20bnr/spacemacs/issues?utf8=%E2%9C%93&q=author%3Amanukall

**Comment by manukall** [comment]
@mbertheau i'm not pretending to be a regular contributor. i should probably have stated that projecttalk is my project, though. 
regarding ineffectiveness of forums, do you have any suggestions? i just think they have their place next to live chat for the reasons you stated above. they also act as a better searchable archive for past problems and solutions then live chat, in my opinion.

regarding not having to go to different places: if the spacemacs project wants to use Github issues as discussion platform, that is perfectly fine. i started projecttalk in part because of a few threads on hackernews where maintainers were talking about how they wanted to use the issues tab just for bug tracking and how hard that was, because so many usage questions are posted there.

**Comment by manukall** [comment]
by the way, even though i haven't contributed yet, i have been USING spacemacs for quite some time and i swear no line of projecttalk was written in any other editor :wink:

**Pull request closed without merging**
