### PR TITLE
Git-gutter: Check for linum-mode, not global-linum-mode.

### PR DESCRIPTION
**Pull request by person808**
Not everyone has linum-mode on globally.

### CODE REVIEW

**Comment by syl20bnr** [comment]
Thank you again :-)
I amended it to test for both (there are indeed two distinct variables depending on how linum is set).

Cherry-picked into `develop` branch, you can safely delete your branch.

**Comment by person808** [comment]
@syl20bnr  `linum-mode` should be quoted, otherwise there is an error.

**Comment by person808** [comment]
#1252

**Comment by syl20bnr** [comment]
What is the error ?

Le dimanche 19 avril 2015, person808 <notifications@github.com> a écrit :

> @syl20bnr <https://github.com/syl20bnr> linum-mode should be quoted,
> otherwise there is an error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/pull/1196#issuecomment-94251240>.
>


-- 
-syl20bnr-

**Comment by person808** [comment]
Error (use-package): git-gutter :init: Symbol's value as variable is void: linum-mode

**Pull request closed without merging**
