### PR TITLE
avoid being evil in deft with emacs editing style

### PR DESCRIPTION
**Pull request by d12frosted**

### CODE REVIEW

**Comment by StreakyCobra** [comment]
I think @AlejandroCatalina implemented a core method recently for doing this.

**Comment by AlejandroCatalina** [comment]
Exactly. I'm on the phone so I don't have the reference, maybe #5111?

On Feb 28, 2016 13:58, Fabien Dubosson <notifications@github.com> wrote:

I think @AlejandroCatalina implemented a core method recently for doing this.

**Comment by d12frosted** [comment]
Yeah, I aslo feel like it's not ideal, that's why I opened a related issue #5291. Thanks for the link though.

**Comment by d12frosted** [comment]
Ah, so you propose to use `spacemacs/normal-to-insert-state` function instead of this check, right?

**Comment by AlejandroCatalina** [comment]
Yes I think that would work.

On Feb 28, 2016 14:12, Boris <notifications@github.com> wrote:

Ah, so you propose to use spacemacs/normal-to-insert-state function instead of this check, right?

**Comment by d12frosted** [comment]
Done, thanks @AlejandroCatalina

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
