### PR TITLE
Fix for #7383

### PR DESCRIPTION
**Pull request by mahinshaw**
I added a var for setting `sp-show-pair-delay`, called `dotspacemacs-sp-show-pair-delay`.

### CODE REVIEW

**Comment by TheBB** [comment]
Maybe a more descriptive description?

**Comment by mahinshaw** [comment]
A better description of the var?

**Comment by TheBB** [comment]
Not necessarily, just something that tells a new user browsing their new dotfile what it does more or less.

**Comment by syl20bnr** [comment]
Thank you for the PR. We usually try to not duplicate existing variables, so it would be better to update the DOCUMENTATION.org file about the vanilla variable `sp-show-pair-delay`.

**Comment by mahinshaw** [comment]
@syl20bnr - This was in response to #7383. The issue was around initializing the `sp-show-pair-delay`.  Based on the bug report, setting it in user-init was too early, and user-config, was too late. Hence the shadowed variable.  If there is another approach, I am happy to alter or close this PR.

**Comment by TheBB** [comment]
I pushed this fix instead. https://github.com/syl20bnr/spacemacs/commit/2b7893ee1780b0c5727064ee6b9805d1b49d9a3f

Thanks though!

**Pull request closed without merging**
