### PR TITLE
spacemacs-base: Fix renaming of evilified-state

### PR DESCRIPTION
**Pull request by justbur**
@syl20bnr you missed some things in renaming the evilified-state package. This is the rest of the cases I think

### CODE REVIEW

**Comment by syl20bnr** [comment]
Probably I only made what must be done for the tests to pass :-)

**Comment by TheBB** [comment]
I posted these comments in the commits but I'll repeat them here.

I'm still confused. In https://github.com/syl20bnr/spacemacs/commit/629d736b79e05558a9fce5a36e66005e683e18a9 you made this package un-removable, and in https://github.com/syl20bnr/spacemacs/commit/f95422c61d633614379514c1b70c2fed5dd8af43 you removed the `package-usedp` guard for magit on the assumption that the package is indeed unremovable.

So... what do?

I assumed part of the advantage of having evilified be its own package was to have it be removable.

**Comment by justbur** [comment]
That and to disentangle it from the core but yes that was my thought too

**Comment by syl20bnr** [comment]
evilified-state is part of the spacemacs-base package, the whole spacemacs experience depends on it.
I will gradually move all packages to the layer system, the extended notion of protected packages is mandatory and feels natural.

**Comment by TheBB** [comment]
So you're saying these guards should be removed rather than renamed?

**Comment by syl20bnr** [comment]
Protected packages is like part of spacemacs core, do we need a guard for those ?

**Comment by syl20bnr** [comment]
Maybe I should tell more about my plan, I'll do a new layer `spacemacs-bootstrap` which will hold all the mandatory packages, obviously all those packages will be protected.

**Comment by TheBB** [comment]
I was just trying to get a clear answer whether this PR needed to be changed or not. Currently it renames the package in all the guards, but if I'm interpreting you correctly you would rather have them all removed.

**Comment by syl20bnr** [comment]
Sorry, I didn't understand, so yes I guess we can remove them.

I know the distinction is rather blurry between a protected package with a variable to enable it and a not protected package. It the case of evilified-state I'm fore making it a core feature, a pro for this view is that it can be considered mandatory for dynamic change of editing style.

**Comment by syl20bnr** [comment]
Actually it is not mandatory anymore for dynamic change :-D But yeah... gut feeling ... :-)

**Comment by justbur** [comment]
My view is that a package should only be mandatory if too many packages
depend on it. That's not the case with evilified state.

**Comment by syl20bnr** [comment]
I will put it another way, it is part of the conventions.

**Comment by justbur** [comment]
Then how do I disable it if I want to?

**Comment by syl20bnr** [comment]
As I wrote:
> I know the distinction is rather blurry between a protected package with a variable to enable it and a not protected package.

So you cannot until we put an explicit dotspacemacs variable to disable it.

**Comment by TheBB** [comment]
Based on the above discussion I'm closing this PR. I removed the guards in https://github.com/syl20bnr/spacemacs/commit/e7fbc84ff086d52408828636d03743f0b086cd24. I'm sure we can find a cleaner way of disabling this feature.

**Comment by mkomitee** [comment]
@TheBB Not sure if I should open a new issue on this, but ever since e7fbc84 made it to develop, I get the following on startup:

```
Symbol's function definition is void: evilified-state-verify
```

I've had to roll back to the previous commit to get spacemacs to load completely.

**Comment by TheBB** [comment]
@mkomitee Do you have a backtrace? Launch with `--debug-init`.

I can't find any reference to a function by this name in our source code.

**Comment by mkomitee** [comment]
Using 3a5c375:

```
(void-function evilified-state-evilify)
  (evilified-state-evilify dired-mode dired-mode-map "j" (quote vinegar/move-down) "k" (quote vinegar/move-up) "-" (quote vinegar/up-directory) "0" (quote dired-back-to-start-of-files) "=" (quote vinegar/dired-diff) (kbd "C-j") (quote dired-next-subdir) (kbd "C-k") (quote dired-prev-subdir) "I" (quote vinegar/dotfiles-toggle) (kbd "~") (quote (lambda nil (interactive) (find-alternate-file "~/"))) (kbd "RET") (if vinegar-reuse-dired-buffer (quote dired-find-alternate-file) (quote dired-find-file)) "f" (quote helm-find-files) "J" (quote dired-goto-file) (kbd "C-f") (quote find-name-dired) "H" (quote diredp-dired-recent-dirs) "T" (quote dired-tree-down) "K" (quote dired-do-kill-lines) "r" (quote revert-buffer) (kbd "C-r") (quote dired-do-redisplay) "gg" (quote vinegar/back-to-top) "G" (quote vinegar/jump-to-bottom))
  (lambda nil (evilified-state-evilify dired-mode dired-mode-map "j" (quote vinegar/move-down) "k" (quote vinegar/move-up) "-" (quote vinegar/up-directory) "0" (quote dired-back-to-start-of-files) "=" (quote vinegar/dired-diff) (kbd "C-j") (quote dired-next-subdir) (kbd "C-k") (quote dired-prev-subdir) "I" (quote vinegar/dotfiles-toggle) (kbd "~") (quote (lambda nil (interactive) (find-alternate-file "~/"))) (kbd "RET") (if vinegar-reuse-dired-buffer (quote dired-find-alternate-file) (quote dired-find-file)) "f" (quote helm-find-files) "J" (quote dired-goto-file) (kbd "C-f") (quote find-name-dired) "H" (quote diredp-dired-recent-dirs) "T" (quote dired-tree-down) "K" (quote dired-do-kill-lines) "r" (quote revert-buffer) (kbd "C-r") (quote dired-do-redisplay) "gg" (quote vinegar/back-to-top) "G" (quote vinegar/jump-to-bottom)))()
  eval-after-load(dired (lambda nil (evilified-state-evilify dired-mode dired-mode-map "j" (quote vinegar/move-down) "k" (quote vinegar/move-up) "-" (quote vinegar/up-directory) "0" (quote dired-back-to-start-of-files) "=" (quote vinegar/dired-diff) (kbd "C-j") (quote dired-next-subdir) (kbd "C-k") (quote dired-prev-subdir) "I" (quote vinegar/dotfiles-toggle) (kbd "~") (quote (lambda nil (interactive) (find-alternate-file "~/"))) (kbd "RET") (if vinegar-reuse-dired-buffer (quote dired-find-alternate-file) (quote dired-find-file)) "f" (quote helm-find-files) "J" (quote dired-goto-file) (kbd "C-f") (quote find-name-dired) "H" (quote diredp-dired-recent-dirs) "T" (quote dired-tree-down) "K" (quote dired-do-kill-lines) "r" (quote revert-buffer) (kbd "C-r") (quote dired-do-redisplay) "gg" (quote vinegar/back-to-top) "G" (quote vinegar/jump-to-bottom))))
  eval-buffer(#<buffer  *load*-483848> nil "/Users/mkomitee/.emacs.d/layers/+vim/vinegar/keybindings.el" nil t)  ; Reading at buffer position 1064
  load-with-code-conversion("/Users/mkomitee/.emacs.d/layers/+vim/vinegar/keybindings.el" "/Users/mkomitee/.emacs.d/layers/+vim/vinegar/keybindings.el" nil nil)
  load("/Users/mkomitee/.emacs.d/layers/+vim/vinegar/keybindings.el")
  (if (file-exists-p file) (load file))
  (let ((file (concat (eieio-oref layer (quote :dir)) file))) (if (file-exists-p file) (load file)))
  (while --dolist-tail-- (setq file (car --dolist-tail--)) (let ((file (concat (eieio-oref layer (quote :dir)) file))) (if (file-exists-p file) (load file))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- files) file) (while --dolist-tail-- (setq file (car --dolist-tail--)) (let ((file (concat (eieio-oref layer (quote :dir)) file))) (if (file-exists-p file) (load file))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  configuration-layer//load-layer-files([object cfgl-layer "vinegar" vinegar "/Users/mkomitee/.emacs.d/layers/+vim/vinegar/" nil nil] ("funcs.el" "config.el" "keybindings.el"))
  configuration-layer//configure-layer([object cfgl-layer "vinegar" vinegar "/Users/mkomitee/.emacs.d/layers/+vim/vinegar/" nil nil])
  (while --dolist-tail-- (setq l (car --dolist-tail--)) (configuration-layer//configure-layer l) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- layers) l) (while --dolist-tail-- (setq l (car --dolist-tail--)) (configuration-layer//configure-layer l) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((warning-minimum-level :error)) (let ((--dolist-tail-- layers) l) (while --dolist-tail-- (setq l (car --dolist-tail--)) (configuration-layer//configure-layer l) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  configuration-layer//configure-layers(([object cfgl-layer "spacemacs" spacemacs "/Users/mkomitee/.emacs.d/layers/+distribution/spacemacs/" nil nil] [object cfgl-layer "emacs-lisp" emacs-lisp "/Users/mkomitee/.emacs.d/layers/+lang/emacs-lisp/" nil nil] [object cfgl-layer "version-control" version-control "/Users/mkomitee/.emacs.d/layers/+source-control/version-control/" nil nil] [object cfgl-layer "auto-completion" auto-completion "/Users/mkomitee/.emacs.d/layers/auto-completion/" (auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory "~/.dotfiles/emacs/snippets") nil] [object cfgl-layer "better-defaults" better-defaults "/Users/mkomitee/.emacs.d/layers/better-defaults/" nil nil] [object cfgl-layer "c-c++" c-c++ "/Users/mkomitee/.emacs.d/layers/+lang/c-c++/" nil nil] [object cfgl-layer "colors" colors "/Users/mkomitee/.emacs.d/layers/colors/" nil nil] [object cfgl-layer "deft" deft "/Users/mkomitee/.emacs.d/layers/deft/" nil nil] [object cfgl-layer "evil-commentary" evil-commentary "/Users/mkomitee/.emacs.d/layers/+vim/evil-commentary/" nil nil] [object cfgl-layer "evil-snipe" evil-snipe "/Users/mkomitee/.emacs.d/layers/+vim/evil-snipe/" nil nil] [object cfgl-layer "git" git "/Users/mkomitee/.emacs.d/layers/+source-control/git/" (git-gutter-use-fringe t magit-last-seen-setup-instructions "1.4.0") nil] [object cfgl-layer "go" go "/Users/mkomitee/.emacs.d/layers/+lang/go/" nil nil] [object cfgl-layer "haskell" haskell "/Users/mkomitee/.emacs.d/layers/+lang/haskell/" nil nil] [object cfgl-layer "html" html "/Users/mkomitee/.emacs.d/layers/+lang/html/" nil nil] [object cfgl-layer "javascript" javascript "/Users/mkomitee/.emacs.d/layers/+lang/javascript/" nil nil] [object cfgl-layer "markdown" markdown "/Users/mkomitee/.emacs.d/layers/+lang/markdown/" nil nil] [object cfgl-layer "org" org "/Users/mkomitee/.emacs.d/layers/org/" nil nil] [object cfgl-layer "puppet" puppet "/Users/mkomitee/.emacs.d/layers/+config-files/puppet/" nil nil] [object cfgl-layer "python" python "/Users/mkomitee/.emacs.d/layers/+lang/python/" nil nil] [object cfgl-layer "ranger" ranger "/Users/mkomitee/.emacs.d/layers/+tools/ranger/" (ranger-show-preview t) nil] [object cfgl-layer "ruby" ruby "/Users/mkomitee/.emacs.d/layers/+lang/ruby/" nil nil] [object cfgl-layer "rust" rust "/Users/mkomitee/.emacs.d/layers/+lang/rust/" nil nil] [object cfgl-layer "shell" shell "/Users/mkomitee/.emacs.d/layers/shell/" (shell-default-shell (quote eshell)) nil] [object cfgl-layer "shell-scripts" shell-scripts "/Users/mkomitee/.emacs.d/layers/+lang/shell-scripts/" nil nil] [object cfgl-layer "spacemacs-layouts" spacemacs-layouts "/Users/mkomitee/.emacs.d/layers/+window-management/spacemacs-layouts/" nil nil] [object cfgl-layer "spell-checking" spell-checking "/Users/mkomitee/.emacs.d/layers/spell-checking/" nil nil] [object cfgl-layer "sql" sql "/Users/mkomitee/.emacs.d/layers/+lang/sql/" nil nil] [object cfgl-layer "syntax-checking" syntax-checking "/Users/mkomitee/.emacs.d/layers/syntax-checking/" (syntax-checking-enable-tooltips nil) nil] [object cfgl-layer "themes-megapack" themes-megapack "/Users/mkomitee/.emacs.d/layers/themes-megapack/" nil nil] [object cfgl-layer "unimpaired" unimpaired "/Users/mkomitee/.emacs.d/layers/+vim/unimpaired/" nil nil] [object cfgl-layer "vinegar" vinegar "/Users/mkomitee/.emacs.d/layers/+vim/vinegar/" nil nil] [object cfgl-layer "yaml" yaml "/Users/mkomitee/.emacs.d/layers/+lang/yaml/" nil nil]))
  configuration-layer/sync()
  (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (if init-file-debug (progn (require (quote core-debug)))) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  (if (spacemacs/emacs-version-ok) (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (if init-file-debug (progn (require (quote core-debug)))) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start))))
  eval-buffer(#<buffer  *load*> nil "/Users/mkomitee/.emacs.d/init.el" nil t)  ; Reading at buffer position 1042
  load-with-code-conversion("/Users/mkomitee/.emacs.d/init.el" "/Users/mkomitee/.emacs.d/init.el" t t)
  load("/Users/mkomitee/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()
```

And if I roll back to e7fbc84, the first commit where loading fails:
```
(void-function evilified-state-evilify)
  (evilified-state-evilify dired-mode dired-mode-map "j" (quote vinegar/move-down) "k" (quote vinegar/move-up) "-" (quote vinegar/up-directory) "0" (quote dired-back-to-start-of-files) "=" (quote vinegar/dired-diff) (kbd "C-j") (quote dired-next-subdir) (kbd "C-k") (quote dired-prev-subdir) "I" (quote vinegar/dotfiles-toggle) (kbd "~") (quote (lambda nil (interactive) (find-alternate-file "~/"))) (kbd "RET") (if vinegar-reuse-dired-buffer (quote dired-find-alternate-file) (quote dired-find-file)) "f" (quote helm-find-files) "J" (quote dired-goto-file) (kbd "C-f") (quote find-name-dired) "H" (quote diredp-dired-recent-dirs) "T" (quote dired-tree-down) "K" (quote dired-do-kill-lines) "r" (quote revert-buffer) (kbd "C-r") (quote dired-do-redisplay) "gg" (quote vinegar/back-to-top) "G" (quote vinegar/jump-to-bottom))
  (lambda nil (evilified-state-evilify dired-mode dired-mode-map "j" (quote vinegar/move-down) "k" (quote vinegar/move-up) "-" (quote vinegar/up-directory) "0" (quote dired-back-to-start-of-files) "=" (quote vinegar/dired-diff) (kbd "C-j") (quote dired-next-subdir) (kbd "C-k") (quote dired-prev-subdir) "I" (quote vinegar/dotfiles-toggle) (kbd "~") (quote (lambda nil (interactive) (find-alternate-file "~/"))) (kbd "RET") (if vinegar-reuse-dired-buffer (quote dired-find-alternate-file) (quote dired-find-file)) "f" (quote helm-find-files) "J" (quote dired-goto-file) (kbd "C-f") (quote find-name-dired) "H" (quote diredp-dired-recent-dirs) "T" (quote dired-tree-down) "K" (quote dired-do-kill-lines) "r" (quote revert-buffer) (kbd "C-r") (quote dired-do-redisplay) "gg" (quote vinegar/back-to-top) "G" (quote vinegar/jump-to-bottom)))()
  eval-after-load(dired (lambda nil (evilified-state-evilify dired-mode dired-mode-map "j" (quote vinegar/move-down) "k" (quote vinegar/move-up) "-" (quote vinegar/up-directory) "0" (quote dired-back-to-start-of-files) "=" (quote vinegar/dired-diff) (kbd "C-j") (quote dired-next-subdir) (kbd "C-k") (quote dired-prev-subdir) "I" (quote vinegar/dotfiles-toggle) (kbd "~") (quote (lambda nil (interactive) (find-alternate-file "~/"))) (kbd "RET") (if vinegar-reuse-dired-buffer (quote dired-find-alternate-file) (quote dired-find-file)) "f" (quote helm-find-files) "J" (quote dired-goto-file) (kbd "C-f") (quote find-name-dired) "H" (quote diredp-dired-recent-dirs) "T" (quote dired-tree-down) "K" (quote dired-do-kill-lines) "r" (quote revert-buffer) (kbd "C-r") (quote dired-do-redisplay) "gg" (quote vinegar/back-to-top) "G" (quote vinegar/jump-to-bottom))))
  eval-buffer(#<buffer  *load*-483848> nil "/Users/mkomitee/.emacs.d/layers/+vim/vinegar/keybindings.el" nil t)  ; Reading at buffer position 1064
  load-with-code-conversion("/Users/mkomitee/.emacs.d/layers/+vim/vinegar/keybindings.el" "/Users/mkomitee/.emacs.d/layers/+vim/vinegar/keybindings.el" nil nil)
  load("/Users/mkomitee/.emacs.d/layers/+vim/vinegar/keybindings.el")
  (if (file-exists-p file) (load file))
  (let ((file (concat (eieio-oref layer (quote :dir)) file))) (if (file-exists-p file) (load file)))
  (while --dolist-tail-- (setq file (car --dolist-tail--)) (let ((file (concat (eieio-oref layer (quote :dir)) file))) (if (file-exists-p file) (load file))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- files) file) (while --dolist-tail-- (setq file (car --dolist-tail--)) (let ((file (concat (eieio-oref layer (quote :dir)) file))) (if (file-exists-p file) (load file))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  configuration-layer//load-layer-files([object cfgl-layer "vinegar" vinegar "/Users/mkomitee/.emacs.d/layers/+vim/vinegar/" nil nil] ("funcs.el" "config.el" "keybindings.el"))
  configuration-layer//configure-layer([object cfgl-layer "vinegar" vinegar "/Users/mkomitee/.emacs.d/layers/+vim/vinegar/" nil nil])
  (while --dolist-tail-- (setq l (car --dolist-tail--)) (configuration-layer//configure-layer l) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- layers) l) (while --dolist-tail-- (setq l (car --dolist-tail--)) (configuration-layer//configure-layer l) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((warning-minimum-level :error)) (let ((--dolist-tail-- layers) l) (while --dolist-tail-- (setq l (car --dolist-tail--)) (configuration-layer//configure-layer l) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  configuration-layer//configure-layers(([object cfgl-layer "spacemacs" spacemacs "/Users/mkomitee/.emacs.d/layers/+distribution/spacemacs/" nil nil] [object cfgl-layer "emacs-lisp" emacs-lisp "/Users/mkomitee/.emacs.d/layers/+lang/emacs-lisp/" nil nil] [object cfgl-layer "version-control" version-control "/Users/mkomitee/.emacs.d/layers/+source-control/version-control/" nil nil] [object cfgl-layer "auto-completion" auto-completion "/Users/mkomitee/.emacs.d/layers/auto-completion/" (auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory "~/.dotfiles/emacs/snippets") nil] [object cfgl-layer "better-defaults" better-defaults "/Users/mkomitee/.emacs.d/layers/better-defaults/" nil nil] [object cfgl-layer "c-c++" c-c++ "/Users/mkomitee/.emacs.d/layers/+lang/c-c++/" nil nil] [object cfgl-layer "colors" colors "/Users/mkomitee/.emacs.d/layers/colors/" nil nil] [object cfgl-layer "deft" deft "/Users/mkomitee/.emacs.d/layers/deft/" nil nil] [object cfgl-layer "evil-commentary" evil-commentary "/Users/mkomitee/.emacs.d/layers/+vim/evil-commentary/" nil nil] [object cfgl-layer "evil-snipe" evil-snipe "/Users/mkomitee/.emacs.d/layers/+vim/evil-snipe/" nil nil] [object cfgl-layer "git" git "/Users/mkomitee/.emacs.d/layers/+source-control/git/" (git-gutter-use-fringe t magit-last-seen-setup-instructions "1.4.0") nil] [object cfgl-layer "go" go "/Users/mkomitee/.emacs.d/layers/+lang/go/" nil nil] [object cfgl-layer "haskell" haskell "/Users/mkomitee/.emacs.d/layers/+lang/haskell/" nil nil] [object cfgl-layer "html" html "/Users/mkomitee/.emacs.d/layers/+lang/html/" nil nil] [object cfgl-layer "javascript" javascript "/Users/mkomitee/.emacs.d/layers/+lang/javascript/" nil nil] [object cfgl-layer "markdown" markdown "/Users/mkomitee/.emacs.d/layers/+lang/markdown/" nil nil] [object cfgl-layer "org" org "/Users/mkomitee/.emacs.d/layers/org/" nil nil] [object cfgl-layer "puppet" puppet "/Users/mkomitee/.emacs.d/layers/+config-files/puppet/" nil nil] [object cfgl-layer "python" python "/Users/mkomitee/.emacs.d/layers/+lang/python/" nil nil] [object cfgl-layer "ranger" ranger "/Users/mkomitee/.emacs.d/layers/+tools/ranger/" (ranger-show-preview t) nil] [object cfgl-layer "ruby" ruby "/Users/mkomitee/.emacs.d/layers/+lang/ruby/" nil nil] [object cfgl-layer "rust" rust "/Users/mkomitee/.emacs.d/layers/+lang/rust/" nil nil] [object cfgl-layer "shell" shell "/Users/mkomitee/.emacs.d/layers/shell/" (shell-default-shell (quote eshell)) nil] [object cfgl-layer "shell-scripts" shell-scripts "/Users/mkomitee/.emacs.d/layers/+lang/shell-scripts/" nil nil] [object cfgl-layer "spacemacs-layouts" spacemacs-layouts "/Users/mkomitee/.emacs.d/layers/+window-management/spacemacs-layouts/" nil nil] [object cfgl-layer "spell-checking" spell-checking "/Users/mkomitee/.emacs.d/layers/spell-checking/" nil nil] [object cfgl-layer "sql" sql "/Users/mkomitee/.emacs.d/layers/+lang/sql/" nil nil] [object cfgl-layer "syntax-checking" syntax-checking "/Users/mkomitee/.emacs.d/layers/syntax-checking/" (syntax-checking-enable-tooltips nil) nil] [object cfgl-layer "themes-megapack" themes-megapack "/Users/mkomitee/.emacs.d/layers/themes-megapack/" nil nil] [object cfgl-layer "unimpaired" unimpaired "/Users/mkomitee/.emacs.d/layers/+vim/unimpaired/" nil nil] [object cfgl-layer "vinegar" vinegar "/Users/mkomitee/.emacs.d/layers/+vim/vinegar/" nil nil] [object cfgl-layer "yaml" yaml "/Users/mkomitee/.emacs.d/layers/+lang/yaml/" nil nil]))
  configuration-layer/sync()
  (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (if init-file-debug (progn (require (quote core-debug)))) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  (if (spacemacs/emacs-version-ok) (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (if init-file-debug (progn (require (quote core-debug)))) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start))))
  eval-buffer(#<buffer  *load*> nil "/Users/mkomitee/.emacs.d/init.el" nil t)  ; Reading at buffer position 1042
  load-with-code-conversion("/Users/mkomitee/.emacs.d/init.el" "/Users/mkomitee/.emacs.d/init.el" t t)
  load("/Users/mkomitee/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()
```

... though I'll say that it's possible that this is due, at least in part, to my custom configuration. If I move my `.spacemacs` file out of the way, and start over, I get this instead:

```
Error (use-package): evil-lisp-state :config: Symbol's value as variable is void: evil-leader--default-map
```

Though that doesn't seem to be as big of an issue.jjj

My config is at https://github.com/mkomitee/dotfiles/blob/master/emacs/spacemacs -- I've already tried changing my use of evil-leader to the new spacemacs commands, but that didn't help. I suspect it may have something to do with my layer config. Bisecting my config it looks like the problem is actually in the vinegar layer.

**Comment by mkomitee** [comment]
I can confirm that 4937a83 resolves my issue. Thanks for the incredibly quick turn-around @TheBB.

**Comment by TheBB** [comment]
Oh, you wrote verify instead of evilify first ;-)

**Comment by mkomitee** [comment]
Autocorrect.

**Pull request closed without merging**
