### PR TITLE
get new

### PR DESCRIPTION
**Pull request by wogaokui**

### CODE REVIEW

**Comment by justbur** [comment]
@robbyoconnor

**Comment by TheBB** [comment]
These are getting annoying. Why are they kept open?

**Comment by robbyoconnor** [comment]
Can we stop doing this shit. @wogaokui -- you are seriously pissing off the people who do actual work. Close this. I'm half tempted to report you to github for spamming.

**Comment by robbyoconnor** [comment]
Can we stop doing this shit. @wogaokui -- you are seriously pissing off the people who do actual work. Close this. I'm half tempted to report you to github for spamming. 

What i suspect happened here is that @wogaokui doesn't understand how git works. 

To update YOUR BRANCH -- you don't need a PR -- PRs are for integrating your changes into the upstream branch -- stop doing these stupid meaningless PRs. If you have something to contribute, by all means make a PR...otherwise DO NOT, I repeat **DO NOT** make PRs. 

Simply do: 
```
git pull --rebase upstream master
```

then 
```
git push origin master
```
Was this harsh, yes -- and it's rightfully harsh. 

And while we are at it: **NO PULL REQUESTS AGAINST MASTER**, READ the freaking conventions before you contribute. @syl20bnr, please close this as completely invalid.

**Comment by robbyoconnor** [comment]
Still open, why?

**Comment by d12frosted** [comment]
For the reasons unknown 😸

**Pull request closed without merging**
