### PR TITLE
prodigy-view-mode: go to file at point

### PR DESCRIPTION
**Pull request by FrancescElies**
This is a small feature request.
When running a process and having a look at it's output in prodigy (`prodigy-view`), I would love to be able to open the file at point with <gf> as in other modes.

What do you think?
Thanks for your time

### CODE REVIEW

**Comment by FrancescElies** [comment]
I also added revert buffer, would it be fine.
This is useful in case you want to add a new service without having to restart emacs

**Comment by d12frosted** [comment]
Hey @FrancescElies,

Thanks for PR!

I am not sure about the part about `find-file-at-point`. Since this change looks useful not only for prodigy layer.

 But regarding your second commit - [you should document it in README file of prodigy layer](https://github.com/syl20bnr/spacemacs/blob/master/CONTRIBUTING.org#contributing-a-keybinding). 

And note that these two commits [would look better](https://github.com/syl20bnr/spacemacs/blob/master/CONTRIBUTING.org#pull-request) as two separate PRs.

**Comment by FrancescElies** [comment]
Hi @d12frosted,
thanks for your comments I made a new PR for the revert buffer binding https://github.com/syl20bnr/spacemacs/pull/8032

**Comment by FrancescElies** [comment]
With regards to `find-file-at-point`, maybe we would like do something similar as with compile-mode see https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distributions/spacemacs-base/keybindings.el#L238

What do you think, shall this be placed in keybindings.el?

Best

**Comment by d12frosted** [comment]
Thanks for splitting these :) Welp, actually I went ahead and just merged this (so it's now available in `develop`). This should not be in `keybindings.el` as it [has other purpose](https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org#keybindingsel).

**Comment by FrancescElies** [comment]
Wonderful, (and thanks for the explanations:)

**Pull request closed without merging**
