### PR TITLE
Share installed packages

### PR DESCRIPTION
**Pull request by emacs18**
Thank you for contributing to Spacemacs!

Before you submit this pull request, please ensure it is against the develop branch and not master.

This message should be replaced with a description of your change.

Thank you <3

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Wow...

**Comment by a13ph** [comment]
What the hell happened here? I can't even begin to understand this :confounded:

**Comment by JAremko** [comment]
Now I have PTSD   :scream_cat: 

I demand safe room and hugging.

**Comment by NJBS** [comment]
@emacs18 Check out [this wiki page](https://github.com/syl20bnr/spacemacs/wiki/Beginner's-Guide-to-Contributing-a-Pull-Request-to-Spacemacs) on how to properly submit and update a pull request to spacemacs!

**Comment by emacs18** [comment]
Sorry.  I thought I removed this PR within minutes of submitting it, but the fact that you guys noticed this means that I did not properly remove it.  Please see PR #5464 which I submitted after removing this PR (or at least I thought I removed this).  I think what happened was that I clicked on wrong branch, e.g., "master" rather than "develop".

I'm puzzled.  It looks like this PR is closed.  Isn't it?
If so, why did you guys even see this?
How can I complete erase a PR that has a mistake?

**Comment by JAremko** [comment]
@emacs18  
> How can I complete erase a PR that has a mistake?

It will stay with  you forever :grinning:

**Comment by emacs18** [comment]
@NJBS Thanks for the pointer.  I think I followed the process mostly.  The problem is that I made at least two mistakes which was compounded by the fact that a conflict arose due to a change on the develop branch after the original PR.  That is why I tried to completely remove my fork of spacemacs and start over.

**Comment by JAremko** [comment]
@emacs18  Do not worry. They're just a bunch of trolls.  :wink:

**Comment by robbyoconnor** [comment]
That was my question....

**Comment by robbyoconnor** [comment]
@emacs18 -- we're cool -- I've done it myself...but what got me was that you didn't even replace the filler text!

**Pull request closed without merging**
