### PR TITLE
Add PonyLang mode in Extra langs

### PR DESCRIPTION
**Pull request by rajatvig**
This adds support for the Pony Language http://www.ponylang.org/

### CODE REVIEW

**Comment by robbyoconnor** [comment]
You may wanna close this and resubmit it against a topic branch

**Comment by rajatvig** [comment]
@robbyoconnor which branch do I resubmit it against? Any document I can look at?

**Comment by robbyoconnor** [comment]
You just make a new branch and do it against develop, this is quite clear (at least I think it is)

**Comment by robbyoconnor** [comment]
You just make a new branch and do it against `develop`, this is quite clear (at least I think it is)

**Comment by rajatvig** [comment]
@robbyoconnor I get what you're saying. For the next PR, I'll use a topic branch to avoid getting stuck.

**Comment by robbyoconnor** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Robert

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67oex-a2&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=vtFN6Inl&invitationId=6130896968030961664








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67oex-a2&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHOObylfD4r5wAAAVRVScmgemi1UXVZhOwUPUh18tB4eovGDIDOuyEvphwVcYs4Wi7R0_0k0ATN-U5FCxfH5DdWa4g2-MbwDMVKSNQ-k8oAISLX44yOtHzCOCvqJhSCEp7tPW2pDZfpd8y0eU8psEpwl5ewpRWM2qw3Tn99koZscKDSNTUqog3phJVeTklKhJOj&eid=0-ini67oex-a2


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67oex-a2&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by TheBB** [comment]
Thanks, but https://github.com/syl20bnr/spacemacs/pull/5663 seems much more complete so I will roll with that.

**Pull request closed without merging**
