### PR TITLE
fix geolocation layer on non-macos systems

### LINKED ISSUE #9221: Geolocation layer appears to assume OSX
On linux, using the geolocation package results in a warning when initializing the rase package.

    rase :init: Symbol’s function definition is void: osx-location-watch

It is apparently trying to run osx-location-watch regarless of the operating system.  Or is this layer not meant to work except on OSX?

```
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 7e57b1f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python javascript
        (org :variables org-enable-bootstrap-support t org-enable-reveal-js-support t org-enable-priority-commands nil org-enable-github-support t org-bullets-bullet-list
             '("■" "◆" "▶" "▲")
             org-projectile-file "TODO.org")
        html yaml csv
        (ruby :variables ruby-version-manager 'rbenv ruby-test-runner 'rspec)
        (go :variables go-tab-width 4)
        ruby-on-rails shell-scripts
        (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
        (better-defaults :variables better-defaults-move-to-beginning-of-code-first t better-defaults-move-to-end-of-code-first t)
        (latex :variables latex-build-command "ErbTeX" latex-enable-auto-fill t latex-enable-folding t)
        pdf-tools pandoc emacs-lisp git github markdown sql gtags
        (geolocation :variables geolocation-enable-automatic-theme-changer t geolocation-enable-location-service nil geolocation-enable-weather-forecast t)
        search-engine
        (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/usr/bin/fish" shell-default-height 40 shell-default-position 'bottom)
        (spell-checking :variables enable-flyspell-auto-completion nil)
        syntax-checking deft dash
        (colors :variables colors-colorize-identifiers 'variables)
        version-control selectric ibuffer chrome command-log
        (go :variables go-tab-width 2)
        graphviz games github
        (ranger :variables ranger-show-preview t)
        systemd twitter themes-megapack)

- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

### PR DESCRIPTION
**Pull request by d12frosted**
Fixes #9221

P. S. I know I mistyped 'geolocation' in the name of the branch 😝 SHAME!!!

### CODE REVIEW

**Comment by yurighensev** [comment]
It is causing `theme-changer-hour-fraction-to-time: Wrong type argument: number-or-marker-p, nil` for me.

**Comment by d12frosted** [comment]
Are you sure it's after my PR and not before? Because I didn't change anything related to `theme-changer`. And it is used only inside of that package: [definition](https://github.com/hadronzoo/theme-changer/blob/master/theme-changer.el#L74), [usage 1](https://github.com/hadronzoo/theme-changer/blob/master/theme-changer.el#L97), [usage 2](https://github.com/hadronzoo/theme-changer/blob/master/theme-changer.el#L98).

I dunno, try updating your packages 😸

**Comment by d12frosted** [comment]
Oh and btw, thanks for testing!

**Comment by d12frosted** [comment]
@yurighensev I have checked that error. Indeed, it comes from `theme-changer`. The problem is that you haven't configured `location`. I've updated readme file and added `user-error` for that.

**Comment by yurighensev** [comment]
Beautiful! Your pr fixes the problem nicely.

That error I got was my bad. I indeed had location set, as I use theme-changer for a while now. The problem was that while testing your pr I accidentally changed my system's clock without changing `calendar-location-latitude` and `longitude`. So I had my clock at 11 a.m. but `location` set to a place where it was 11 p.m.

I guess that is a separate bug that I should file.

**Comment by d12frosted** [comment]
@yurighensev great, I am glad to hear that

Ah, that happens 😸 Anyways, it's good that you've run into it as documentation didn't mention this important bit.

**Comment by d12frosted** [comment]
Thank you :+1: Cherry-picked into `develop`, you can safely delete your branch.

**Pull request closed without merging**
