### PR TITLE
c-c++: Add clangd support

### PR DESCRIPTION
**Pull request by auscompgeek**
Closes: #12351

### CODE REVIEW

**Comment by kvaneesh** [comment]
One issue I have found with a similar approach is handling the lsp-extensions. Some of the command within ` SPC m g` gives me the error like:

command-execute: Wrong type argument: commandp, c-c++/find-refs-write
command-execute: Wrong type argument: commandp, c-c++/find-callers

**Comment by auscompgeek** [comment]
@kvaneesh Yup, this will also need to not bind the keys for the cquery/ccls LSP extensions.

**Comment by cormacc** [comment]
@auscompgeek Finally got around to doing this myself yesterday - didn't realise you'd most of the work done already until I came to raise a PR :)  My implementation is pretty similar, but tackles the keybinding issue. Also separates the lsp-server selection and backend selection (i.e. you now set `c-c++-backend` to `nil`, `rtags` or `lsp`, then set `c-c++-lsp-server` to `clangd`, `ccls` or `cquery` -- `clangd` default). 

Want to pool our efforts or something? My branch is here:
https://github.com/cormacc/spacemacs/tree/c-lsp-clangd

N.B. it branched from another open PR (minor update to lsp layer #12695 )

**Comment by auscompgeek** [comment]
> Also separates the lsp-server selection and backend selection (i.e. you now set c-c++-backend to nil, rtags or lsp, then set c-c++-lsp-server to clangd, ccls or cquery -- clangd default).

I'd be wary of possibly breaking people's existing configs here.

It'd definitely be good to consolidate our efforts. Your changes to packages.el look much better than mine. We still need to define a keybinding for clangd's switch source header extension though, which looks to be missing from yours altogether.

**Comment by cormacc** [comment]
Re. clangd switch source/header -- I hadn't seen the clangd extensions page -- good call. Some of those other extensions look nice too, though probably a bit more work in putting them to use. Do you reckon the clangd switch should replace or complement the existing goto-alternate-file binding?

Re. breaking existing configs -- I'm afraid I'm guilty of creating the current `c-c++-backend` situation. I adopted a similar approach in a later PR against the python layer and @sdwolfz called it an anti-pattern -- on reflection I was inclined to agree with him and changed it to something like what I've introduced in my current branch of the `c-c++` layer.  Considering none of the lsp additions to c/c++ have been part of a spacemacs release yet, it may be acceptable? Perhaps one of the maintainers might weigh in...

**Comment by cormacc** [comment]
@auscompgeek Did you manage to use that textDocument/switchSourceHeader binding? I'm having difficulties with it (and figuring out if/what parameters it needs). Pushed some changes to my branch (which was pretty profoundly broken, but now seems less so) if you fancy taking a look.

**Comment by bhipple** [comment]
FWIW, one of the best things about spacemacs is that it's reasonably opinionated with a sane/good set of defaults for everything that mostly just works.  The C/C++ layer is a bit of an exception, in that it seems to try to support just about everything, and (at least last time I've played with it) ends up being a little confusing and gives the impression that it doesn't work particularly well.  I see a lot of commentary on various isssues, r/emacs, and other communities trying to figure out what the "best" way to setup Spacemacs for C++ is, so if you think one set of tools has momentum, such as the clangd lsp backend, I think most users would be happy to absorb some develop branch breakage in order to get a more polished / opinionated experience.

**Comment by cormacc** [comment]
I've fixed some additional clangd configuration options that weren't getting passed through (based on feedback from @kvaneesh) Think my branch is more or less there now, except that the clangd switch source/header bit, which I'm not calling correctly. To be honest, I'm perfectly happy with the generic projectile goto alternate file implementation and not inclined to spend more time on clangd-specific switch source header (particularly as I'll probably continue to use the ccls server anyway). @auscompgeek will I go ahead and raise a new PR from my branch, or would you rather proceed some other way?

**Comment by auscompgeek** [comment]
Go for it - I'm not personally attached to this PR :)

**Comment by cormacc** [comment]
Thanks @auscompgeek -- didn't want to tread on anyone's toes ;)

**Pull request closed without merging**
