### PR TITLE
Add evil-lion

### PR DESCRIPTION
**Pull request by et2010**
Add evil-lion for operator alignment. More details here: https://github.com/edkolev/evil-lion

### CODE REVIEW

**Comment by Somelauw** [comment]
I think evil-lion looks nice, because it acts like an operator.

Unfortunately, the gl binding conflicts with current Spacemacs conventions:
https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.org#movement-in-normal-mode

By the way, Spacemacs already has some alignment bindings on SPC xa.

**Comment by et2010** [comment]
Thanks for pointing that out, @Somelauw. I didn't notice it before.
Maybe we could add a toggle for evil-lion?

**Comment by Somelauw** [comment]
Maybe put it on ga?

**Comment by TheBB** [comment]
I think it would be ok to put a keybinding under `SPC x a`, no? I don't personally use alignment so often that this would be prohibitive, but maybe others do.

Seems it would suffice to set `evil-lion-left-align-key` and `evil-lion-right-align-key` to `nil` before loading the mode, and then adding leader bindings for `evil-lion-left` and `evil-lion-right`.

**Comment by TheBB** [comment]
I made some changes at 529045630496faafa0706a0c486cb9cff7b184df reflecting my previous comment. Also added documentation.

Thanks! Cherry-picked in develop. You can safely delete your branch.

**Comment by peterhoeg** [comment]
What is the proper way to use evil-lion as an operator with spacemacs?

**Pull request closed without merging**
