### PR TITLE
changed binding `SPC j =` to `SPC x i` for indenting buffer

### PR DESCRIPTION
**Pull request by adrianstaniec**
imho it belongs better together with align-\* commands 
rather than with jumps and joins
`x i` for teXt Indent seems also an easier mnemonic
at least for the 'holy' guys

### CODE REVIEW

**Comment by StreakyCobra** [comment]
Same as for the other PR, need documentation :wink:

**Comment by adrsta** [comment]
now i'm thinking about maybe `SPC b i` or `SPC b I`
which would fit to buffer functions like `SPC b Y` and `SPC b P`
but less to the region side of things

**Comment by syl20bnr** [comment]
Should be `SPC b =`, `=` is used to format in Vim.

**Comment by Compro-Prasad** [comment]
@adrianstaniec, It is better to assign to `SPC b =` as suggested by Sylvain. It would by default indent whole buffer and would work on regions too which is a plus point. A newcomer will definitely look into `SPC b` for new things and having indentation functionality there is a plus point.

**Comment by robbyoconnor** [comment]
This needs to be rebased.

**Comment by adrianstaniec** [comment]
Sorry, I've lost the interest in spacemacs already.

**Pull request closed without merging**
