### PR TITLE
Add helm-find binding

### PR DESCRIPTION
**Pull request by justbur**
My proposal for #3108 

Replaces `SPC f l` for `find-file-literally`. If that's a useful binding then maybe we can move this. I like `fl` for find "locally" and `fL` for find "globally" on the system.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
:+1:

**Comment by bmag** [comment]
:+1:
Do you think adding documentation about installing `find` (and `locate`, while we're at it) on Windows is necessary? I don't use Emacs on Windows, so I don't know if it's really needed.

**Comment by justbur** [comment]
Yes that would be nice. I can put it together

**Comment by justbur** [comment]
Added note to windows users

**Comment by sooheon** [comment]
I was the one who suggested find literally, it's extremely useful to get around emacs' slow long line rendering for really big files, but it is niche enough to move I guess. "f C-l" or "F l" come to mind, any better options?

**Comment by justbur** [comment]
@sooheon This is a different approach, but wouldn't it makes sense to add a helm action for `helm-find-files` that allows you to open it using `find-file-literally`?

**Comment by sooheon** [comment]
@justbur that way does seem more elegant :)

**Comment by justbur** [comment]
@sooheon try this
```elisp
(helm-add-action-to-source "Find File Literally" 'find-file-literally helm-source-find-files 2)
```

**Comment by sooheon** [comment]
@justbur yep thanks. And if anyone reading uses swiper/ivy, the following is the equivalent:

```
(ivy-set-actions
     'counsel-find-file
     '(("l" find-file-literally "Find file literally")))
```

**Comment by justbur** [comment]
Great. Added the helm action to this or

**Pull request closed without merging**
