### PR TITLE
Fix jump handlers conflict for haskell and intero

### PR DESCRIPTION
**Pull request by CthulhuDen**
`intero-mode` is a minor mode which is usually active alongside `haskell-mode`. In code as it was previously in my installation hook from define-jump-handlers for haskell-mode ran *after* hook set up for intero-mode so `spacemacs-jump-handlers` got it's final value from `spacemacs-jump-handlers-haskell-mode`, so it did not contain `intero-goto-definition`.

Instead of defining separate `spacemacs-jump-handlers-intero-mode` via macro I modify `spacemacs-jump-handlers-haskell-mode` when initializing intero.

### CODE REVIEW

**Comment by magthe** [comment]
I would love to see this merged. It fixes the issue that `, g g` doesn't work in Haskell/Intero mode.

**Comment by magthe** [comment]
So, now that this PR is more than a month old, it was approved the day after its creation, it's has had one duplicate... is it not time to merge it soon?

**Comment by sdwolfz** [comment]
We're in a code freeze right now as we prepare for the next release. Right now we're doing the changelog for the last 1600 commits and it will take a while to finish it. Once that is done we'll merge any remaining urgent fixes and finally do the release.

Please have a bit more patience as it's the middle of December and we're busy at work with the last push before the Christmass freeze. We will probably have everything sorted out by the end of this year.

**Comment by magthe** [comment]
I can absolutely wait! I know you'll get to it when you have time.

**Comment by sdwolfz** [comment]
Thank you :heart:! 
And congratulations on your first Spacemacs PR :tada:!
Cherry-picked into develop branch, you can safely delete your branch.
Commit: 3a509fc0d9eee15b90e31fb9044fd6d3b57110f3

**Pull request closed without merging**
