### PR TITLE
Re-add org-trello

### PR DESCRIPTION
**Pull request by magthe**
After finding issue #9328 I thought I'd try to add _org-trello_ in the "right" way.

- I'm using the really rather cool `:toggle` option of declaring dependencies.
- The loading should be deferred.
- There's a rather minimal set of spacemacs-style key bindings at the moment, but it should be enough to get started (I think)

Comments and suggestions are most welcome!

### CODE REVIEW

**Comment by magthe** [comment]
I believe that addresses all review comments so far. Anything else, or does it look good enough now?

**Comment by sdwolfz** [comment]
Thank you :heart:!

I squashed your commits into one: d29c7832868e072a73166440437ca88c4a268724 and made a change to load `org-trello` after `org` otherwise the keybindings were not created.

Cherry-picked into develop branch, you can safely delete your branch.

**Comment by syl20bnr** [comment]
We cannot use `SPC m o` prefix for this, it is reserved for the user. See conventions: https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org#user-prefix

We need a prefix for Org integrations, `SPC m a` and `SPC m A` for `application` are already taken. `SPC m s` for `service` is already taken. `SPC i` for `integration` already taken ... :-)

Maybe `SPC m m` for `more` ? and then we can use `t` for Trello. Could be a conventions to add a second layer of major modes specific key bindings.

**Comment by LucaMarconato** [comment]
Hi, I tried adding `org-trello` in the layers (I am using the `develop` branch) but at the startup I get this in the `*Message*` buffer. Any idea why?

```
(Spacemacs) Warning: Unknown layer org-trello declared in dotfile.
(Spacemacs) --> deleting request-deferred... [1/1]
Package ‘request-deferred-20160419.2305’ deleted.
```

**Pull request closed without merging**
