### PR TITLE
Add ob-cfengine3 to cfengine layer

### LINKED ISSUE #9462: Add support for executing cfengine src blocks in orgmode
I have a function that allows me to execute cfengine src blocks in org-mode. I would like to have this functionality available in spacemacs but I am unsure if I should add the function in the cfengine or org layer.

### PR DESCRIPTION
**Pull request by nickanderson**
This change adds the ob-cfengine3 package to the cfengine layer enabling
execution of cfengine3 SRC blocks inside of org-mode.

Closes #9462

### CODE REVIEW

**Comment by nickanderson** [comment]
:/ I don't understand the current test failure.

**Comment by nickanderson** [comment]
This works for me, but I am unsure what the formatting (optional) issue is. The test failure is cryptic.

**Comment by syl20bnr** [comment]
Thank you ! 👍 
I made the configuration more idiomatic in commit https://github.com/syl20bnr/spacemacs/commit/ddcb5dc1
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by nickanderson** [comment]
Oh thanks for merging and tidying!

**Pull request closed without merging**
