### PR TITLE
Uncommented declare-for-mode

### PR DESCRIPTION
**Pull request by martinmr**
It seems that the issue with guide-key preventing declare-for-mode from working has been solved since and the method works correctly now. Tested by declaring prefixes for java-mode.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Squash into one neat commit as the [contribution guidelines](https://github.com/syl20bnr/spacemacs/blob/master/doc/CONTRIBUTE.org) state, which you may want to read :wink:

**Comment by robbyoconnor** [comment]
Don't close this -- just rebase your branch and force-push it

**Comment by martinmr** [comment]
About five years ago I submitted a pull request for adding commands to multi-term. Since I needed to use it immediately, I merged the branch into develop. I didn't realize this was a mistake until today so if I want to rebase I have to merge a lot of commits and I didn't got it to work. Instead I deleted my repository and forked this one again. I will clean up all the files and resubmit them as new PRs with only one commit. Sorry about the confusion.

**Comment by martinmr** [comment]
Done: https://github.com/syl20bnr/spacemacs/pull/2266 smf https://github.com/syl20bnr/spacemacs/pull/2267

**Comment by robbyoconnor** [comment]
@martinmr, much nicer! -- Always do `git pull --rebase upstream <branch>`

**Comment by martinmr** [comment]
I am confused. Should I run the above command to pull changes from syl20bnr/spacemacs to my fork instead of merging?

**Comment by robbyoconnor** [comment]
hop onto the gitter chat -- it's the place to have a conversation, not on the PR

**Pull request closed without merging**
