### PR TITLE
Core env patch

### PR DESCRIPTION
**Pull request by wpmcbee**
Fix issue #12451 by causing the env
file to be created and loaded when
emacs is run in daemon mode.

Also, remove a superfluous variable 
and an unnecessary option.

### CODE REVIEW

**Comment by smile13241324** [comment]
@JAremko this looks like a controversial change to me, care to have a look?

Basically we seem to not find our env file in deamon mode, however I am not sure if this change will have side effects to non deamon users and I am not too familiar with the entire env file mechanism to be honest.

**Comment by lebensterben** [comment]
Part of the bug in #12451 seems like caused by wrong settings to me.

exporting a variable in a shell only makes it available within that shell and all sub shells, hence it's found in emacs -nw.

But daemon is usually handled by system service manager, eg systemd. So that variable is not valid in any sub shell of systemd, including emacsclient.

**Comment by JAremko** [comment]
@smile13241324  I don't get why it's bad to load env file multiply times? Maybe it has something to do with  portable dumper setup :thinking:

**Comment by lebensterben** [comment]
Normally it's not a good idea to load shell init files for multiple times because they can be arbitrarily shell scripts, which may be slow to load or have side effects.

But current design of .spacemacs.env is not shell script, but a simple key-value storage, so there's no issue with performance.

Also, it's pure and idempotent, meaning that loading it has no side effects and always have same results.

So I think there's no big issue for that.

**Comment by wpmcbee** [comment]
First of all, I stupidly conflated two separate mechanisms so the first part of my proposed change should be ignored.  Only the modifications to spacemacs/load-spacemacs-env should be considered.

Secondly, my use case is running the Cygwin version of "emacs --daemon" in Windows startup, something which is probably not very common.  This change might not be as useful for systemd or other means of starting daemon mode.

**Comment by lebensterben** [comment]
> Secondly, my use case is running the Cygwin version of "emacs --daemon" in Windows startup, something which is probably not very common.  This change might not be as useful for systemd or other means of starting daemon mode.

Then you can wrap the forms in a conditional and only evaluate them in cygwin.

**Comment by wpmcbee** [comment]
Seems clear this pull request is defective and should not be accepted.  The workaround from ccruquan is probably the better option.

**Pull request closed without merging**
