### PR TITLE
Add bindings to navigates defun in Haskell

### PR DESCRIPTION
**Pull request by PierreR**

### CODE REVIEW

**Comment by bmag** [comment]
Note: if/when #2747 is merged, then `M-h` and `M-l` will provide the same movements.

**Comment by syl20bnr** [comment]
These are generic functions of Emacs, it feels weird to define them only for Haskell.

**Comment by PierreR** [comment]
Yep, I have actually asked on the IRC channel which bindings I should use but I have received any definitive answer.
It might make sense to make them on `SPC-m` because AFAIK it is not always implemented by every mode. But sure the binding should be consistent across modes that support the feature.

**Comment by d12frosted** [comment]
Shouldn't it be closed? :)

**Comment by PierreR** [comment]
Well so what's the current bindings general or not for this feature ?

**Comment by d12frosted** [comment]
Yeah, these are really built-in Emacs functions so it's better to map them in every prog mode. 

But there's one strange thing. Definition of `end-of-defun` says that an end of a defun occurs right after the close-parenthesis that matches the open-parenthesis that starts a defun. So it should not even work for `haskell-mode`. And this is what I experience - instead of navigating between function definitions, it just jumps to beginning or end of module. But it works great for c-like and lisp-like languages.

I wonder if such behaviour is observable only in Emacs 25, hence you sent this PR to add *useful* key bindings.

**Comment by gracjan** [comment]
Haskell mode has those functions defined to support Haskell syntax. (right now this is a bit buggy and is disabled by default).

Surely this is generic Emacs functionality and does not have much to do with Haskell specifically.

**Comment by TheBB** [comment]
Agree with the above discussion, it would be preferable to do this in a more generic way.

**Pull request closed without merging**
