### PR TITLE
Update emacs to the more formal e-macs.

### PR DESCRIPTION
**Pull request by mssabr01**
Change instances of 'emacs' to 'e-macs' so that developers and users
more easily understand this product is the electronic macs without the
casual 'emacs' shorthand.

### CODE REVIEW

**Comment by lebensterben** [comment]
-1

**Comment by mssabr01** [comment]
Apologies, updated with encoding fix

**Comment by DinoBytes** [comment]
gr8 work. much more reading better. i hope you have nice day

**Comment by sdwolfz** [comment]
Please upstream your change here first: https://lists.gnu.org/mailman/listinfo/emacs-devel, after which we will consider such a PR.

**Pull request closed without merging**
