### PR TITLE
[python] update jedi instructions

### PR DESCRIPTION
**Pull request by d12frosted**
Following https://github.com/proofit404/anaconda-mode/commit/150390968bb0c5180026932d27255483d690e00f

### CODE REVIEW

**Comment by bet4it** [comment]
After proofit404/anaconda-mode#327, `anaconda-mode` won't check for `jedi` which is installed globally, but will install it in `~/.emacs.d/.cache/anaconda-mode/0.1.13`, so the `pip install` command has no effects with `anaconda-mode`.
We should delete these workarounds with `anaconda-mode` now.

**Comment by d12frosted** [comment]
@bet4it cool! thank you for sharing this information!

**Comment by d12frosted** [comment]
@bet4it wait, I still see [this](https://github.com/proofit404/anaconda-mode/blob/master/anaconda-mode.el#L150). If I understand it correctly, if you haven't installed `jedi >= 0.13`, then you'll get an assert.

**Comment by bet4it** [comment]
proofit404/anaconda-mode#327 was created to resolve the situation that we have to do some workarounds like the README described.

Sure, even if we download packages locally, we still need to import them and it's better to check its version to avoid something unexpected.
I think what have been done in `install_deps` is same with we run `pip install` manually, except it will install them locally. There is no exception handling in this function, so if there are any errors during the installing, the following expressions won't be executed. So the `assert` will only be executed when the installing is success, and I can't image any situation that `jedi` still can't satisfy the requirement that we have to install them manually now.

I think it's better for us to notice user to take a look at the output in `*anaconda-mode*` buffer when `anaconda-mode` can work.

**Comment by bet4it** [comment]
OMG, there is one situation that we should update `jedi` manually: https://github.com/proofit404/anaconda-mode/pull/327#issuecomment-436956933
I think we can wait `anaconda-mode` for a solution to it.

**Comment by smile13241324** [comment]
Thank you for contributing to spacemacs :purple_heart:, I have cherry picked your commit into develop.

**Pull request closed without merging**
