### PR TITLE
Fix Markdown to Org for README in Jabber Layer

### PR DESCRIPTION
**Pull request by robbyoconnor**
Fix tables in the README for the Jabber Layer which had markdown artifacts.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@syl20bnr this should be a blocker to the next release of spacemacs.

**Comment by TheBB** [comment]
Ah I didn't see this. So #2680 probably conflicts with this.

**Comment by robbyoconnor** [comment]
Yeah it's gonna be messy for you @TheBB...depending on the order he merges...if he merges yours first, I'll simply close this.

**Comment by robbyoconnor** [comment]
Merged in b2deed4

**Comment by syl20bnr** [comment]
Ahah I was sure I'll find these cherry-picked PRs in the closed filter :-)
Thank you for the PR !

**Comment by robbyoconnor** [comment]
I close PRs for you sometimes if I see the PR cherry-picked :)

**Pull request closed without merging**
