### PR TITLE
update lua readme

### PR DESCRIPTION
**Pull request by d12frosted**
Add a note about luacheck

---

Didn't know that this layer can do this :) Probably good thing to mention.

### CODE REVIEW

**Comment by fbergroth** [comment]
Flycheck is likely already supported via the lua compiler checker.

You can run `SPC e v` in any buffer to see what checkers are available.

**Comment by d12frosted** [comment]
> Flycheck is likely already supported via the lua compiler checker.

Don't really understand what you mean. 

In any case, I think it worth mentioning external dependency.

**Comment by fbergroth** [comment]
I just thought that the wording was a bit strange since basic syntax checking already works with the luac checker. 

I don't disagree that mentioning the other checker is good. :)

**Comment by robbyoconnor** [comment]
:+1:

**Comment by d12frosted** [comment]
> basic syntax checking already works with the luac checker

what is `luac checker`? 

---

Syntax check works only when `luacheck` is installed. See [flycheck](https://github.com/flycheck/flycheck/blob/d4c302c09fdbbc2190a72406d71bfb9b3dcd5c45/flycheck.el#L7222). 

And this is really funny, because I've read lua layer readme and didn't find any mention about syntax checker. So I started to look for one. Then I found `luacheck` and decided to try. Imagine how was I surprised to see it working automatically in Spacemacs. That's why I've added that line - I want to save other people time :)

**Comment by robbyoconnor** [comment]
Yeah all flycheck does is run the program and parse its output using a regular expression

**Comment by fbergroth** [comment]
Sorry for the confusion. Flycheck comes with two checkers for lua, the other checker called [lua](https://github.com/flycheck/flycheck/blob/d4c302c09fdbbc2190a72406d71bfb9b3dcd5c45/flycheck.el#L7245-L7256).

You wrote
>In order to enable =flycheck= support ...

The lua checker will probably be enabled for most people, so I meant to suggest that it should written like "In order to enable linting via Luacheck ...".

**Comment by d12frosted** [comment]
> Yeah all flycheck does is run the program and parse its output using a regular expression

Yes, I know. But it's not the point of our discussion. See my response to @fbergroth 

> Flycheck comes with two checkers for lua

Wow, didn't know. But why then it didn't work? 

> The lua checker will probably be enabled for most people

Indeed, you are right then :) Right, I'll change that. Thanks for information :)

**Comment by fbergroth** [comment]
> Wow, didn't know. But why then it didn't work?

See enabled checkers with `SPC e v`. If you have troubles with a particular checker, you can run `M-x flycheck-compile`. Probably you just don't have `luac` in your path. :)

**Comment by d12frosted** [comment]
@fbergroth I've updated it :) 

Thanks for the help and for `SPC e v`.

**Comment by TheBB** [comment]
Thank you! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
