### PR TITLE
Add Twitter layer

### PR DESCRIPTION
**Pull request by CestDiego**

### CODE REVIEW

**Comment by CestDiego** [comment]
@syl20bnr I rebased this.

**Comment by syl20bnr** [comment]
Can you resize the logo to 200px height ?

**Comment by aminb** [comment]
Look forward to seeing this merged!

@CestDiego As @syl20bnr mentioned can you please resize the logo to 200px, and also use the new twitter logo instead of the old one? ([See here](https://about.twitter.com/company/brand-assets))

**Comment by CestDiego** [comment]
It has been rebased and changed to 200px

**Comment by aminb** [comment]
@CestDiego Fantastic. @syl20bnr Can we have this merged please? :smiley:

**Comment by StreakyCobra** [comment]
@CestDiego You probably have to adapt the README to the new template (like `:noexport:` tag for `TOC`).

**Comment by CestDiego** [comment]
@StreakyCobra I modified the tag :)

**Comment by tsenart** [comment]
+1

**Comment by nosami** [comment]
+1

**Comment by cpaulik** [comment]
This will need a few keybindings since SPC is used by twittering-mode. See also https://github.com/syl20bnr/spacemacs/issues/5304.

**Comment by syl20bnr** [comment]
Cherry-picked into develop branch !!
I improved it a bit in commit https://github.com/syl20bnr/spacemacs/commit/92cc50b

Thank you :+1:

**Comment by nixmaniack** [comment]
Awesome! I can remove my layer now. :smile:

**Pull request closed without merging**
