### PR TITLE
Adds install instructions to gnus contrib README

### PR DESCRIPTION
**Pull request by JoshTGreenwood**
Just adds basic install instructions to gnus.

### CODE REVIEW

**Comment by trishume** [comment]
Man having this is every single layer is so redundant, I am :crying_cat_face: 

Oh well though, its convention and aids discoverability, it just pains my rubyist DRY sensibilities

**Comment by JoshTGreenwood** [comment]
Yeah, I don't prefer repeating it each time but I still find it beneficial.  My eyes are trained to look for an "Install" or "Getting Started" in every README.

**Comment by syl20bnr** [comment]
This is good repetition IMO. Each layer must be isolated as much as possible, the documentation is not an exception, too much DRY could hurt this principle.

Thank you !
Cherry-picked into `develop` branch, you can safely delete your branch.

**Comment by trishume** [comment]
Just for reference I totally agree that install instructions should be in the docs of every layer, I just don't like them being in the *source* of the docs of every layer.

I was thinking of more of a docs build step that automatically added all the repetitive boilerplate to the docs of every layer before publishing it somewhere.

**Comment by syl20bnr** [comment]
This would be a nice thing to have indeed. I would like to make the snippet
less error prone (right now it is not obvious that the variable is a list
and should be defined at a unique place), generating those snippets would
allow to do that easily. OTHO it makes contributions less straightforward,
edition should happen in a source file as opposed to directly in the
README. We could consider to use texinfo (it may possible to do the above)
but few people knows it (I don't even know it :-))

Le mercredi 3 juin 2015, Tristan Hume <notifications@github.com> a écrit :

> Just for reference I totally agree that install instructions should be in
> the docs of every layer, I just don't like them being in the *source* of
> the docs of every layer.
>
> I was thinking of more of a docs build step that automatically added all
> the repetitive boilerplate to the docs of every layer before publishing it
> somewhere.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/pull/1805#issuecomment-108408457>.
>


-- 
-syl20bnr-

**Pull request closed without merging**
