### PR TITLE
Add c-minus-minus layer

### PR DESCRIPTION
**Pull request by bgamari**
This is a simple layer adding support for `cmm-mode`.

### CODE REVIEW

**Comment by syl20bnr** [comment]
Thank you, since it is related to haskell I would rather put it into the haskell layer.

**Comment by bgamari** [comment]
Fair enough. I've pushed a new commit adding the `cmm-mode` package into the Haskell layer.

**Comment by bgamari** [comment]
@syl20bnr how does this look?

**Comment by syl20bnr** [comment]
Seems good :+1: 
I delay some new layers for the next release though because the current one is already huge.

**Comment by syl20bnr** [comment]
Finally I merge it :-)

Thank you !
Cherry-piked into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
