### PR TITLE
react: improved react file recognition

### PR DESCRIPTION
**Pull request by panjan**
This is a regex that looks for importing react regardless of position in file and variable naming. Criticism is welcome.
#6952

### CODE REVIEW

**Comment by Delapouite** [comment]
Thanks. Does this regex support 'react' with simple quotes?

**Comment by panjan** [comment]
It does support both double and single quotes.

**Comment by panjan** [comment]
I've been successfully using this for a while. Is the pull request OK or does it need any changes?

**Comment by panjan** [comment]
ping

**Comment by willopez** [comment]
I tried you update and it failed to apply the react-mode on a file with an import that looks like this: `import React, { PropTypes } from 'react';`

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
