### PR TITLE
repair search highlighting (spacemacs/counsel-search)

### PR DESCRIPTION
**Pull request by ivasonn**
Repair search highlighting (spacemacs/counsel-search) with ivy--regex-plus by replaced it with spacemacs/ivy--regex-plus

bug with search highlighting when using extra arguments for searching using ivy--regex-plus

after fixing

### CODE REVIEW

**Comment by ivasonn** [comment]
With current `spacemacs/counsel-search` we can't write "foo -- bar" to search this phrase, because it will translated to `foo "bar" .` and ag (for example) will try to search foo in bar directory. if user search for `-Glang -- "foo -- bar"` the end of ag command will be right. If user want to search `"foo -- bar"` he should use `foo.--.bar` or `foo \-\- bar`. 
I know about this bug. But i don't have enough experience in elisp to fix it correctly. Sorry.

**Comment by bmag** [comment]
Thanks, I'll fixup the documentation a bit and merge today or tomorrow.

**Comment by ivasonn** [comment]
Thanks to you too

**Comment by bmag** [comment]
Thank you :+1: Cherry-picked into develop, you can safely delete your branch.

I squashed your commits into a single commit and re-worded the commit message into a valid form - see https://github.com/syl20bnr/spacemacs/commit/d2dab66724711aba77454f677771b59566bd6208.
I fixed the docs in https://github.com/syl20bnr/spacemacs/commit/e109777f8b8c5e9b9a697ad1004c1521b09ccd68.

**Pull request closed without merging**
