### PR TITLE
Activating linum-relative now activates linum

### PR DESCRIPTION
**Pull request by deb0ch**
#6151

### CODE REVIEW

**Comment by TheBB** [comment]
What's the desired behaviour if I turn it off though? Right now it will just go back to regular line numbers.

**Comment by deb0ch** [comment]
Yes, it is intended. 

That's to not conflict with people (like me) who often switch between normal and relative.

This way I'm not changing the behaviour that already exists, and the only behaviour that *should* always be logical and was missing is the one change brought by that commit, activating linum when turning on relative linum.

Does this make sense to you ?

**Comment by TheBB** [comment]
Yeah it makes sense, but maybe toggles isn't really the thing when there are three states. Maybe it would be more POLA to have three bindings that bring the user to no, regular and relative line numbers respectively, disregarding the current state.

**Comment by TheBB** [comment]
Anyway I'm fine with this for now. There are conflicts though, maybe you can fix those.

**Comment by deb0ch** [comment]
Ooops, forgot about the conflicts. It's all fixed now :smile: 

But I think that it is best if we can avoid adding an extra shortcut. They are cluttered enough like that.

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request merged**
