### PR TITLE
[Fix #890] Improve editing functionality for holy-mode

### LINKED ISSUE #890: Add more convenient editing commands for Emacs users
Since Emacs users use chording, they won't have as many key bindings as Vim users. To make up for it, they make smart commands. For example, move to beginning of line or beginning of indentation with one key binding: [Smarter Navigation to the Beginning of a Line](http://emacsredux.com/blog/2013/05/22/smarter-navigation-to-the-beginning-of-a-line/). The newer implementation is in Prelude [here](https://github.com/bbatsov/prelude/blob/master/core/prelude-core.el#L138).

Some useful commands that I use daily:

- Open line below/above.
- Join line. We get `evil-join-line` for this
- Smart `kill-line`: If you press `C-w` and no region is active, it kills a line. If regions is active, it kills region instead. It can be done by advising `kill-region` like [this](https://bitbucket.org/hoangtu/.emacs.d/src/4ae1e7eabfa180fb474d7268854845b51a5c6329/custom/setup-editing.el?at=master#cl-359).
- Smart `kill-ring-save`: similar to `C-w`, but copy a line when no region is active and copy a region otehrwise. It can be done by advising [kill-ring-save](https://bitbucket.org/hoangtu/.emacs.d/src/4ae1e7eabfa180fb474d7268854845b51a5c6329/custom/setup-editing.el?at=master#cl-350).
- A command to indent whole buffer without moving point.

I will think of more.

### PR DESCRIPTION
**Pull request by tuhdo**
Add:

- Key binding for evil-join for both evil/holy-mode.
- A command for indenting whole buffer and a key binding in both
evil/holy-mode.
- A smart beginning of line for holy-mode.

### CODE REVIEW

**Comment by syl20bnr** [comment]
This is promising ! I moved it to a layer which gives full flexibility to spacemacs, one can choose raw emacs, better defaults emacs, or vim, or a mix or... :-)
https://github.com/syl20bnr/spacemacs/tree/develop/contrib/better-defaults

For the redundant functionality on the normal state we discussed about it on the chat and we agree which makes me very happy (I truly think that we have to abolish the frontier between the 2 style and this is good move in this direction).

Thank you ! :+1: 
Cherry-picked in `develop`, you can safely delete your branch.

**Comment by syl20bnr** [comment]
@tuhdo I forgot that I had another thing to tell you. While for `SPC j o` I sure about my decision, I am not sure about the format command you put on `SPC j i`. I removed for now for the same reason as `SPC j o` since `=` in Vim does exactly this, but the exclusion list of indentation sensitive modes is really useful.
So I wonder if we could improve `=` directly.

**Comment by syl20bnr** [comment]
@tuhdo OTHO, to reindent the whole buffer with `=`, it would be `g g = G`...
OK, you can uncomment it and re-enable it on `SPC j i`  (or `SPC  j =` to be consistent with Vim ?) there is a true additional value to it.
Sorry for the fuzz.

**Comment by tuhdo** [comment]
I have to disagree about this. Similar to `gg = G`, in Emacs we select whole region with `C-x h` and indent region with `C-M-\`. However, both of these built-in commands have this inconvenience: point is moved to the end/beginning of buffer after re-indenting. Another inconvenience is that both built-in commands requires you to specify the range, while the new indent comment can act smart: it indents whole buffer if no region is active and indent region otherwise. It's one of a very nice feature of Prelude that I love.

**Comment by tuhdo** [comment]
I think `SPC j i` is better because it's easier to press (homerow)

**Pull request closed without merging**
