### PR TITLE
Fix relative css imports for layer docs

### PR DESCRIPTION
**Pull request by mathcass**
Fix speed-reading, command-log, and csv README.org css import based on
path.

### CODE REVIEW

**Comment by mathcass** [comment]
I noticed that the [command-log](http://spacemacs.org/layers/+tools/command-log/README.html) and [speed-reading](http://spacemacs.org/layers/speed-reading/README.html) were un-styled on the spacemacs.org layer documentation. I believe this should address. I searched around a Makefile or other information on locally building docs but must over overlooked them. Any way test test these out locally?

**Comment by robbyoconnor** [comment]
:+1:

**Comment by robbyoconnor** [comment]
You should close this and do this in a topic branch and open a new PR.

**Comment by StreakyCobra** [comment]
> You should close this and do this in a topic branch and open a new PR.

@mathcass This is a better practice for you, but it doesn't change anything from our side, the PR is fine as it is ;-)

**Pull request closed without merging**
