### PR TITLE
Fix typo in org/README

### PR DESCRIPTION
**Pull request by xinzhige**

### CODE REVIEW

**Comment by bmag** [comment]
What's the deal with the yml and makefile?

**Comment by xinzhige** [comment]
@bmag Hi, I am new here. Currently, I am not sure which CI should I use, Travis CI or Circle CI?

**Comment by xinzhige** [comment]
@bmag I wonder why all checks have failed and it showed no test commands were found after my first commit. Is that because I did not run tests locally? Sorry for the naive question. It is my first commit.

**Comment by bmag** [comment]
Here is why: https://circleci.com/gh/xinzhige/spacemacs/2?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link (this is the same link as the "details" button on this page next to the failed test).

You don't need to add/remove tests for this PR.

**Comment by bmag** [comment]
Thank you :+1: Cherry-picked the first commit (only the typo fix) into develop, you can safely delete your branch.

**Pull request closed without merging**
