### PR TITLE
add counsel-dash

### PR DESCRIPTION
**Pull request by ralesi**
Use counsel-dash when choosing ivy.

### CODE REVIEW

**Comment by d12frosted** [comment]
Please, update README file :D

**Comment by ralesi** [comment]
This is pretty seamless, nothing really changes in the documentation.  `counsel-dash` is actually just a wrapper for helm-dash anyway, so it requires it as well.  The bindings remain the same for either ivy or helm completion.

**Comment by d12frosted** [comment]
Ok, now I see that it's just a wrapper. But still, readme says (for example):

> Lookup thing at point in `helm-dash`

If I am `ivy` user I would not use that key binding, because I don't use `helm` :D Confuses me a bit.

**Comment by ralesi** [comment]
Documentation updated to reference both now.

**Comment by syl20bnr** [comment]
Thank you ! 👍 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
