### PR TITLE
Fix image of update indicator

### PR DESCRIPTION
**Pull request by tvon**
Looks like it was added in org format in https://github.com/syl20bnr/spacemacs/commit/2ab7a2a60fc40f94d6e2efcb058ca15cdb88de5f

### CODE REVIEW

**Comment by tvon** [comment]
I haven't the foggiest idea why this build fails.

**Comment by TheBB** [comment]
It's probably unrelated to your PR. Documentation fixes should have `[ci skip]` somewhere in the commit message to signal CI that it doesn't have to build that commit.

**Comment by tvon** [comment]
Ah, I'm not very familiar with travis specifics.

Amended and force-pushed.

**Comment by syl20bnr** [comment]
@tvon thank you for the PR :+1: 
Unfortunately it has already been submitted previously be someone else. For the next PRs, be sure to make the changes in the develop branch to get all the last changes.

**Pull request closed without merging**
