### PR TITLE
Add link-hint package

### PR DESCRIPTION
**Pull request by StreakyCobra**
Use `link-hint` package. Bind it to `SPC x o` and `SPC x O`.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
This failure looks like it's Travis' fault

**Comment by StreakyCobra** [comment]
Indeed, travis CI networking problems.

**Comment by syl20bnr** [comment]
Interesting package, it covers lots of links. Thank you :+1: 
Cherry... :-)

**Comment by syl20bnr** [comment]
I moved the code to the new spacemacs-editing layer.

**Comment by fandag** [comment]
1 day from a casual mention to an actual PR. Another 3 days and it has landed in develop! This project is moving at an amazing speed :smile: :smile:

**Pull request closed without merging**
