### PR TITLE
Feature/python django pyenv

### PR DESCRIPTION
**Pull request by BrianHicks**
Adds `pyenv-mode` (for [pyenv](https://github.com/yyuu/pyenv)) and `pony-mode` (for [Django](https://www.djangoproject.com/)) to the Python layer.

This seems to be mostly working for me, but the config layer isn't setting the prefix captions. I see this done in other layers, is this the right way to do it?

### CODE REVIEW

**Comment by syl20bnr** [comment]
This is a truly awesome addition ! :heart: 
Thank you !

Cherry-picked and squashed into `develop` branch, you can safely delete your branch

I made some minor modifications in ef34305403a6bd9aaf4967eda40eea11b083f8b8
- `mjtg` is `mjte` which is a better mnemonic to go the test error
- `mps` and `mpu` moved to `mvs` and `mvu`, I also move `mv` for `pyvenv` to `mV`
I updated the [README.md](https://github.com/syl20bnr/spacemacs/tree/develop/contrib/lang/python) in aa5b9e4d3b0e974c8bf7e9beac21b1586a2a377c and added a logo in 579f8eb64966e3912aeca9dcfeabce19f0052cf3

As you can see in the README I put the function name. When you have some can you replace the function names which what they do ? Thank you!

**Comment by BrianHicks** [comment]
Thanks! The changes look good. Do you know why the prefix captions aren't
showing up?

I'll fill in the descriptions soon.

**Comment by syl20bnr** [comment]
@BrianHicks  Oh ... I completely forgot... We have a limitation with guide-key for now, we should not add prefixs for major mode specific key bindings under `SPC m`.

Can you submit a PR to remove them ?

**Comment by syl20bnr** [comment]
or comment them :-)

**Pull request closed without merging**
