### PR TITLE
Fix magit-gh-pulls docs since #g isn't defined

### PR DESCRIPTION
**Pull request by robbyoconnor**
The docs weren't correct. This corrects them.

### CODE REVIEW

**Comment by d12frosted** [comment]
Ya, first time I tried using `gh-pulls` run into the same problem - `#g` is not defined.

But, shouldn't it be changed by `#r`?

**Comment by robbyoconnor** [comment]
@d12frosted fixed it -- and added everything else :)

**Comment by d12frosted** [comment]
Now that I think about it - there is fundamental problem with `magit-gh-pulls` key bindings. The package itself [uses](https://github.com/sigma/magit-gh-pulls/blob/master/magit-gh-pulls.el#L594) `# g`. It's reflected in it's documentation and in the `magit` buffer. 

The problem is that `evil-magit` [makes](https://github.com/justbur/evil-magit/blob/master/evil-magit.el#L376) `magit-gh-pulls` popup evil in it's nature. But doesn't update documentation. 

I'll fetch solution for changing helper message in `magit-gh-pulls` today so it can reflect real key bindings.

Anyway, thanks @robbyoconnor 👍

**Comment by d12frosted** [comment]
Thank you :+1: Cherry-picked into `develop`, you can safely delete your branch.

**Pull request merged**
