### PR TITLE
Improved travis Build relying on container and EVM

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Enhanced the build so it rely on travis container infrastructure, and [Emacs Version Manager](https://github.com/rejeep/evm) to test against latest emacs versions

:smiley:

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
since `travis` directory only contains the run `run_build.s`, I consider it's better to 
remove the dir puttin the script on the root with name `.travis-build.sh`

@syl20bnr, what do you think? :)

**Comment by syl20bnr** [comment]
I think this is great, especially the setup of the test matrix!

**Comment by AdrieanKhisbe** [comment]
Et voilà :smiley:

**Comment by AdrieanKhisbe** [comment]
(seems like I need to rebase)

**Comment by AdrieanKhisbe** [comment]
haha, I hadn't see you cherry-picked it.

Maybe you would like to cherry-pick https://github.com/AdrieanKhisbe/spacemacs/commit/fbaf6a8aa5db4a6d8d1e2804ba3e1da9a2000e52 too

------ 
Was considering also refactoring test organisation to rely on [Cask](https://github.com/cask/cask), ert-runner and using coverage with [undercover](https://github.com/sviridov/undercover.el).

Are you open to this? (Asking since it requires quite some work)

cf: https://github.com/AdrieanKhisbe/spacemacs/tree/setup-cask-and-reorg-test

**Comment by robbyoconnor** [comment]
This has been merged in `develop`

**Comment by syl20bnr** [comment]
@robbyoconnor thank you ;-)

@AdrieanKhisbe Thank you :+1: 
I cherry-picked the second commit as well, you can safely delete your branch.

**Comment by AdrieanKhisbe** [comment]
*great :)*

**Comment by AdrieanKhisbe** [comment]
@syl20bnr :
> Was considering also refactoring test organisation to rely on Cask, ert-runner and using coverage with undercover.

> Are you open to this? (Asking since it requires quite some work)

> cf: https://github.com/AdrieanKhisbe/spacemacs/tree/setup-cask-and-reorg-test

and what do you say about that? :smiley:

**Comment by syl20bnr** [comment]
Sorry I skipped that.
This seems awesome, PR whenever you want :-)

**Comment by AdrieanKhisbe** [comment]
will do :D

2015-12-20 5:09 GMT+01:00 Sylvain Benner <notifications@github.com>:

**Pull request closed without merging**
