### PR TITLE
Add a README listing all the layers

### PR DESCRIPTION
**Pull request by StreakyCobra**
List all available layers with a one-line description for each.

Page rendered on github can be viewed here: https://github.com/StreakyCobra/spacemacs/tree/feature/layers-list/layers#layers

### CODE REVIEW

**Comment by d12frosted** [comment]
:+1: like this idea

Also it would be nice to have those short descriptions in `SPC f e h`.

**Comment by StreakyCobra** [comment]
It's a good idea. It would imply forcing a one-liner description of each module, in an easily parse-able/loadable place. What do you suggest? If we do this we can then use these information to generate this page.

This PR can still be used in the meantime to provide a list to users.

**Comment by robbyoconnor** [comment]
This is awesome.

**Comment by TheBB** [comment]
Yes, this is nice, but my kneejerk reaction is that it would fit in with a kind of layer metadata structure, so that we wouldn't have to work hard to keep this up to date (not that we merge layers *that* often, but still)…

**Comment by StreakyCobra** [comment]
It would be better of course to setup a system that can generate this page automatically and allow to give one-liner description in helm-spacemacs. But in the meantime this could be used to have a "documentation" of layers :smile: (I wrote this just after someone asked where to look for layers on Gitter). It shouldn't be to much of a hassle to maintain, if layer's author are filling it on new layer's PR.

If you don't feel using it, don't worry, I didn't took me too much time to write, and I had already forgotten it until @d12frosted pinged it :joy:

**Comment by d12frosted** [comment]
Haha. That's me, bringing forgotten goodies :smile: 

> Yes, this is nice, but my kneejerk reaction is that it would fit in with a kind of layer metadata structure, so that we wouldn't have to work hard to keep this up to date (not that we merge layers that often, but still)…

What other metadata could be there? Tags? 'Maintainer'? Hm...

**Comment by TheBB** [comment]
As part of the documentation work in #3604 I wrote a small function to auto-generate a file with an overview of all layers. It doesn't have any descriptions, though. It looks like I can merge those changes this weekend. Maybe you want to do something on top of that instead?

**Comment by StreakyCobra** [comment]
Yep, forgot this one, it's a lame idea to do it manually. I close it :smile:

**Pull request closed without merging**
