### PR TITLE
Default spaceline highlight face foreground to "black".

### LINKED ISSUE #10916: Low color contrast in spaceline-highlight face while running in terminal.
#### Description :octocat:
Low color contrast in spaceline highlight face when running in terminal.

#### Reproduction guide :beetle:
- Start Emacs using -nw or in terminal client.

*Observed behaviour:* :eyes: :broken_heart:
Very low color contrast in spaceline (the highlight face, particularly), like observed in https://github.com/TheBB/spaceline/issues/109 and https://github.com/TheBB/spaceline/issues/37.  I originally commented in those issues but I think my issue is related to the way spacemacs configures spaceline.

*Expected behaviour:* :heart: :smile:
Dark foreground colors in the spaceline highlight face for nice visibility.

#### Extra information :books:
Adding lines like the following in `.spacemacs` fixes the issue. So it seems like the spacemacs faces are getting overridden somewhere.

``` elisp
(set-face-attribute 'spacemacs-normal-face nil :foreground "#262626")
(set-face-attribute 'spacemacs-hybrid-face nil :foreground "#262626")
(set-face-attribute 'spacemacs-emacs-face nil :foreground "#262626")
(set-face-attribute 'spacemacs-evilified-face nil :foreground "#262626")
(set-face-attribute 'spacemacs-visual-face nil :foreground "#262626")
(set-face-attribute 'spacemacs-replace-face nil :foreground "#262626")
;; etc
```

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 390462e36)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((auto-completion
  (haskell :variables haskell-completion-backend 'dante))
 c-c++ clojure coq csv dash docker
 (elm :variables elm-format-command "elm-format")
 (emacs-lisp :variables emacs-lisp-hide-namespace-prefix nil)
 emoji
 erlang evil-snipe fsharp
 (git :variables git-magit-status-fullscreen t)
 graphviz
 (gtags :variables gtags-enable-by-default t)
 (haskell :variables haskell-process-type 'stack-ghci haskell-enable-hindent-style "fundamental")
 html
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 idris ivy
 (java :variables java-backend 'ensime)
 (javascript :variables tern-command
             '("node" "/usr/local/bin/tern"))
 (latex :variables latex-build-command "LaTeX" latex-enable-auto-fill t latex-enable-folding t)
 lua
 (markdown :variables markdown-live-preview-engine 'vmd)
 nginx nixos
 (org :variables org-enable-reveal-js-support t org-enable-github-support t org-projectile-file "TODOs.org")
 osx python react restclient ruby rust
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts
 (spell-checking :variables spell-checking-enable-by-default nil)
 spotify sql swift syntax-checking systemd tmux treemacs twitter version-control vimscript vinegar windows-scripts yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

### PR DESCRIPTION
**Pull request by jsoo1**
Default foreground to "black" if foreground is unavailable - primarily a problem in daemon.

  - Closes #10916 

Sorry for the spam. Not used to github PR UI.

### CODE REVIEW

**Comment by sdwolfz** [comment]
I don't think this is the right approach, it should be fixed in the theme itself and not have a hard coded value.

**Comment by jsoo1** [comment]
Ok, what are you thinking for the right approach?

**Comment by jsoo1** [comment]
we could add the configuration to `spacemacs-evil-cursors`. Each of those could have an additional foreground attribute.

**Comment by jsoo1** [comment]
It kinda seems like those cursors should be customizable by the user.

**Comment by syl20bnr** [comment]
They are customizable but this is not documented: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distributions/spacemacs-bootstrap/config.el#L71-L83

**Comment by jsoo1** [comment]
Would it be reasonable to provide default foreground colors with the list of cursors?

**Comment by syl20bnr** [comment]
@jsoo1 can you provide some screenshots _before_ and _after_ so we can see the differences the foreground color makes ?

> should the spacemacs-evil-cursors be a dotspacemacs variable?

Good question, I find this variable to be too complicated to appear in the dotfile and I find state colors to be somewhat important enough to be hardcoded. So it looks like an advanced tweak. We can better document it for sure though, in the main documentation file `doc/DOCUMENTATION.org`.

**Comment by jsoo1** [comment]
With `emacs --daemon=term`, then `emacsclient -t --socket-name term`:

Before: Without default foreground (current develop):
screen shot 2018-08-02 at 8 57 48 am

After: With default foreground:
screen shot 2018-08-02 at 8 58 40 am

As for the customization, how would someone go about customizing existing colors/adding new ones?  Is that as easy as `(setq spacemacs-evil-cursors (add-to-list ...))` or something else?

**Comment by jsoo1** [comment]
Could the evil cursors take advantage of a struct? the customization might read like:
``` elisp
dotspacemacs-evil-cursors `((:cursor "#..." :background "#..." :foreground "#...")
                                                  ...)
```

**Comment by syl20bnr** [comment]
> As for the customization, how would someone go about customizing existing colors/adding new ones?

Using `spacemacs/add-evil-cursor` should work.

> Could the evil cursors take advantage of a struct?

I forgot that we have the function above so I don't think this is needed.

Do you think it's possible to use the `fg-color` of `spacemacs-evil-cursors` only as a fallback ? i.e. if the face cannot be found then we use the `fg-color` of the struct ? It would require an additional parameter to function `spacemacs/add-evil-cursor` to force the application of `fg-color` (by default would be nil).

**Comment by sdwolfz** [comment]
@jsoo1 Did you get the chance to follow up on the feedback provided in this thread?

**Comment by jsoo1** [comment]
I became very busy since. I would like to make the fixes and try to get it merged.

**Pull request closed without merging**
