### PR TITLE
Add keybindings for debugging using emacs-eclim

### PR DESCRIPTION
**Pull request by kleewho**
This is very basic and not 100% compliant with https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.org#debugging. What is missing:
- no toggle on `mdb`
- no remove all breakpoints

I had little problem with defining micro state but with little help I think I could manage it.

### CODE REVIEW

**Comment by person808** [comment]
Heres an example of a micro-state: https://github.com/syl20bnr/spacemacs/blob/master/contrib/!lang/emacs-lisp/packages.el#L54

This should be a good starting point
```elisp
(spacemacs|define-micro-state eclim
        :doc "[b] break [r] run [q] quit"
        :disable-evil-leader t
        :persistent t
        :evil-leader-for-mode (java-mode . "md.")
        :bindings
        ("b" gud-break)
        ("r" gud-run)
        ("q" nil:exit t))
```

**Comment by kleewho** [comment]
@person808 thanks. I'm almost sure I had something similar but had trouble with entering the microstate.

**Comment by kleewho** [comment]
Ok, so right now I think it's good for start

**Comment by Devagamster** [comment]
I noticed that one of the recent versions of eclim proper has debugging support in the vim plugin. Would it be possible to add debug support to emacs-eclim as well and use that instead of gud? This is especially important for projects that have complicated run and debug configurations. Just a thought. I don't know how complicated it would be, so it could be totally out of scope. I think eclim has a toggle breakpoint function and a remove all breakpoint function, so it would probably fix that problem as well.

**Comment by kleewho** [comment]
@Devagamster yeah, for the run and debug configurations I've got fix for that in `emacs-eclim`, so if that's your concern then check this out https://github.com/senny/emacs-eclim/wiki/Run-Configurations

**Comment by Devagamster** [comment]
Hmmm. Is there no way to just piggy back on the way that eclipse is set up to run and debug? To me that would be the more natural way to do it. My ideal would be to just pipe all debug commands through to eclipse and let it manage how to start, stop and deal with breakpoints in the project. I suppose if that were done then we would lose a lot of the benifits of using gud like the fringe breakpoints and such...

**Comment by kleewho** [comment]
Fringe breakpoints? What fringe breakpoints? ;) Unfortunatelly those are only supported for `gdb` and only with `mi` switch

And for the eclipse part then I'm sorry, I don't see working on it any time soon. The debugging is very `vim` oriented. It's not so easy as just calling and waiting for response. There's whole application running underneath and if some breakpoint is hit it needs to communicate back that event. It's done in `eclim` via `VimClient` where it calls some remote functions on `vim`. That's why I decided to rather reuse what is already present in `emacs`. 

That being said I welcome you to work on it. There's always something to work on so step by to [emacs-eclim](https://github.com/senny/emacs-eclim)

**Comment by emmanueltouzery** [comment]
+1 should be merged

**Comment by elken** [comment]
+1 would love this

**Comment by TheBB** [comment]
You can thumb up the first post to show your support.

**Comment by TheBB** [comment]
Now that the java layer uses ensime and its debugging facilities, I don't think we need this any more. Sorry!

**Pull request closed without merging**
