### PR TITLE
fix toggle-truncate off bug

### PR DESCRIPTION
**Pull request by driftcrow**
fix can't toggle-truncate-line off bug

### CODE REVIEW

**Comment by bmag** [comment]
The old toggle works fine for me as it is. Is it broken for you?

**Comment by driftcrow** [comment]
yes, always toggle on

**Comment by syl20bnr** [comment]
@driftcrow  what is your version of Emacs ?

**Comment by driftcrow** [comment]
my emacs on windows version is follow,but my emacs on OSX is installed follow your document.all are the same result.
#### System Info
- OS: windows-nt
- Emacs: 25.0.50.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. df1cabe)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion better-defaults autohotkey emacs-lisp python clojure html javascript restclient markdown org my-org latex
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 osx version-control git github search-engine
                 (colors :variables colors-enable-nyan-cat-progress-bar t)
                 (chinese :variables chinese-default-input-method 'wubi chinese-enable-youdao-dict t)
                 my-misc)
```

**Comment by driftcrow** [comment]
it works fine ,but always display "tuncate-lines enabled." in mini-buffer echo area, even toggled off .

**Comment by StreakyCobra** [comment]
This change doesn't make it work, it does the opposite, i.e. always displays `truncate-lines disabled.`

**Comment by TheBB** [comment]
Seems to work fine here, so I merged it in.

Thank you! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
