### PR TITLE
[WIP] Bump minimum required Emacs version for Spacemacs

### PR DESCRIPTION
**Pull request by NJBS**
The currently stated minimum required [Emacs version for spacemacs is 24.3](https://github.com/syl20bnr/spacemacs/blob/master/init.el#L17). However, spacemacs-base includes the [helm-flx package](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistribution/spacemacs-base/packages.el#L31) which requires a [minimum Emacs version of 24.4](https://github.com/PythonNut/helm-flx/blob/master/helm-flx.el#L9). As it currently stands attempting to install Spacemacs on a 24.3 and below breaks on installing helm-flx.

### CODE REVIEW

**Comment by StreakyCobra** [comment]
Related comments:

- https://github.com/syl20bnr/spacemacs/issues/3198#issuecomment-169247889
- https://github.com/syl20bnr/spacemacs/issues/5071#issuecomment-185613661

Some cleanup will also be needed, for code like [this](https://github.com/syl20bnr/spacemacs/blob/82fdd9a511f1f5cc4f371b91ce691308686f8ec6/layers/%2Blang/emacs-lisp/packages.el#L159-L162). The [readme](https://github.com/syl20bnr/spacemacs/tree/develop#emacs) need also to be updated.

**Comment by NJBS** [comment]
I've started to remove some 24.3 functionality, should core-emacs-backports stick around just in case more functions need to be backported in the future or should it be wiped?

**Comment by StreakyCobra** [comment]
@syl20bnr :point_up:

**Comment by syl20bnr** [comment]
I believed it was an issue and not a PR in the milestone. I resolved the conflict and merged it.
Thank you ! 👍 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
