### PR TITLE
Support importmagic in the Python layer

### PR DESCRIPTION
**Pull request by signalpillar**
Problem
-------
If the symbol is not resolved due to a missing import there is no automatic way
in the Python layer to import it.

Solution
--------
Use 'importmagic' package.

Pressing `SPC m r f` at point that requires an import will suggest a list of
possible options.

### CODE REVIEW

**Comment by signalpillar** [comment]
If virtual environment is used this solution requires installing of the python libs required in the venv itself - not always handy. I think we need in the future add this to anaconda server as there is no need to run another RPC server.

**Comment by CeleritasCelery** [comment]
`importmagic` should be autoloaded (don’t use `:ensure t`)

**Comment by syl20bnr** [comment]
Thank you ! 👍 
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by signalpillar** [comment]
Thank you

**Comment by lukeorland** [comment]
It seems like this code addition might freeze Emacs startup: #10145

**Comment by signalpillar** [comment]
@lukeorland look like it does. Can we roll it back, the feature I've added to the python layer?

**Pull request closed without merging**
