### PR TITLE
add key bindings for moving org table cells

### PR DESCRIPTION
**Pull request by emacs18**
Org mode key `,tc` was bound to `org-table-convert` command.  This is changed so that `,tc` is a prefix key to add four new key bindings for moving current org table cell left, right, up, and down.

### CODE REVIEW

**Comment by lebensterben** [comment]
you need to add the prefix for which key too

**Comment by emacs18** [comment]
I hope I got this right.

**Comment by lebensterben** [comment]
alternatively, do you think "C" ("s-c") fits better for table convert?

Benefit is it clearly separate this from cell related commands.

---

Alternatively, is there other way to move cells?

And if swapping cells is commonly used, "SPC t c h/j/k/l" is too long to type. We'd better having something easier to type.

**Comment by emacs18** [comment]
I submitted https://github.com/syl20bnr/spacemacs/pull/14778 which used `,tC` prefix key.

**Comment by emacs18** [comment]
I am not aware of any org mode commands which swap contents of cells.  If there were such commands, I would use those rather than commands to move cell content from one cell to adjacent cell.

**Comment by lebensterben** [comment]
@emacs18 
Actuall, `SPC m H/J/K/L` are used to move cells. So you don't need to define them again.
Check documentation of `org-shiftleft` etc.

**Comment by emacs18** [comment]
@lebensterben Thanks.  Now that you mention it, I vaguely recall `org-shiftleft`.  I'll probably forget it again, but hopefully not for few months.

**Pull request closed without merging**
