### PR TITLE
add "counsel-spotify" to Spotify layer for ivy users

### PR DESCRIPTION
**Pull request by pyonk**
Hello, thank you for the greatest editor.
I usually use spacemacs with ivy.

I want to search tracks as helm users can.
So I have used "counsel-spotify".
I hope it will be help for ivy users.

counsel-spotify
https://github.com/Lautaro-Garcia/counsel-spotify

Best reagrds.

### CODE REVIEW

**Comment by sdwolfz** [comment]
This PR look OK to me but unfortunately I can not test it locally since I don't use Spotify. If someone else can try it out and see that it works properly then I can trust the crowd and merge this.

**Comment by WarFox** [comment]
I can give this a try in my setup and let you know if it works

**Comment by WarFox** [comment]
This works!

I made this modification in my local
```
(defun spotify/init-counsel-spotify ()
  (use-package counsel-spotify
    :defer t
    :init
    (progn
      (spacemacs/set-leader-keys
        "amsp" 'counsel-spotify-toggle-play-pause
        "amsn" 'counsel-spotify-next
        "amsN" 'counsel-spotify-previous
        "amsst" 'counsel-spotify-search-track
        "amssa" 'counsel-spotify-search-artist
        "amssA" 'counsel-spotify-search-album
        "amssTa" 'counsel-spotify-search-tracks-by-artist
        "amssTA" 'counsel-spotify-search-tracks-by-album))))
```

**Comment by WarFox** [comment]
Tested this with `helm` and `ivy`, works great!

Also updated readme

```diff
diff --git a/layers/+music/spotify/README.org b/layers/+music/spotify/README.org
index d908a4904..4a61582bf 100644
--- a/layers/+music/spotify/README.org
+++ b/layers/+music/spotify/README.org
@@ -33,3 +33,11 @@ If [[https://github.com/emacs-helm/helm][Helm]] layer is enabled, you can also u
 | Key Binding   | Description            |
 |---------------+------------------------|
 | ~SPC a m s g~ | Search for a new track |
+
+If [[https://github.com/abo-abo/swiper][Ivy]] layer is enabled, you can also use the following binding(s):
+| Key Binding       | Description                    |
+| ~SPC a m s s a~   | Spotify search artist          |
+| ~SPC a m s s A~   | Spotify search album           |
+| ~SPC a m s s t~   | Search for a new track         |
+| ~SPC a m s s T a~ | Spotify search track by artist |
+| ~SPC a m s s T A~ | Spotify search track by album  |
diff --git a/layers/+music/spotify/packages.el b/layers/+music/spotify/packages.el
index 6054f9bdf..a8681293d 100644
--- a/layers/+music/spotify/packages.el
+++ b/layers/+music/spotify/packages.el
@@ -10,24 +10,21 @@
 ;;; License: GPLv3
 
 (setq spotify-packages
-      '(
-        (spotify :toggle (configuration-layer/package-usedp 'helm))
+      '(spotify
         (helm-spotify-plus :toggle (configuration-layer/package-usedp 'helm))
-        (counsel-spotify :toggle (configuration-layer/package-usedp 'ivy))
-        ))
+        (counsel-spotify :toggle (configuration-layer/package-usedp 'ivy))))
 
 (defun spotify/init-spotify ()
   (use-package spotify
     :defer t
-    :init
-    (progn
-      (spacemacs/declare-prefix "am" "music")
-      (spacemacs/declare-prefix "ams" "Spotify")
-      (spacemacs/set-leader-keys
-        "amsp" 'spotify-playpause
-        "amsn" 'spotify-next
-        "amsN" 'spotify-previous
-        "amsQ" 'spotify-quit))))
+    :init (progn
+            (spacemacs/declare-prefix "am" "music")
+            (spacemacs/declare-prefix "ams" "Spotify")
+            (spacemacs/set-leader-keys
+              "amsp" 'spotify-playpause
+              "amsn" 'spotify-next
+              "amsN" 'spotify-previous
+              "amsQ" 'spotify-quit))))
 
 (defun spotify/init-helm-spotify-plus ()
   (use-package helm-spotify-plus
@@ -37,19 +34,13 @@
 (defun spotify/init-counsel-spotify ()
   (use-package counsel-spotify
     :defer t
-    :init
-    (progn
-      (spacemacs/declare-prefix "am" "music")
-      (spacemacs/declare-prefix "ams" "Spotify")
-      (spacemacs/set-leader-keys
-        "amsp" 'counsel-spotify-toggle-play-pause
-        "amsn" 'counsel-spotify-next
-        "amsN" 'counsel-spotify-previous
-        "amsst" 'counsel-spotify-search-track
-        "amssa" 'counsel-spotify-search-artist
-        "amssA" 'counsel-spotify-search-album
-        ))))
+    :init (progn
+            (spacemacs/set-leader-keys
+              "amssa" 'counsel-spotify-search-artist
+              "amssA" 'counsel-spotify-search-album
+              "amsst" 'counsel-spotify-search-track
+              "amssTa" 'counsel-spotify-search-tracks-by-artist
+              "amssTA" 'counsel-spotify-search-tracks-by-album))))
 
 (defun spotify/post-init-counsel-spotify ()
-  (load-library "counsel-spotify")
-  )
+  (load-library "counsel-spotify"))
```

**Comment by pyonk** [comment]
@WarFox thank you for your cooperation and your great works!!

**Comment by WarFox** [comment]
@pyonk to be honest, I badly needed this 🙈 
thanks for submitting the PR

**Comment by sdwolfz** [comment]
Thank you @pyonk and @WarFox  :heart:! 
And congratulations on your first Spacemacs PR :tada:!
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by WarFox** [comment]
excellent! 👏

**Pull request closed without merging**
