### PR TITLE
Eww gitignore fix

### PR DESCRIPTION
**Pull request by ahyatt**
I realize that eww support in spacemacs is still not done, but at least using eww files should be in .gitignore.  This is that fix (although it's possible this does not include every kind of eww file).

### CODE REVIEW

**Comment by AlejandroCatalina** [comment]
This might need a little rebase.

**Comment by robbyoconnor** [comment]
you need to branch from `develop` -- you branched from `master` here

**Comment by ahyatt** [comment]
Although I'm sure there must be a way to fix up this pull request by doing clever git things, I basically have no idea how to do that, so I'll just close it instead and open a new one.

**Comment by ahyatt** [comment]
New request is #4976.

**Pull request closed without merging**
