### PR TITLE
Add tldr layer

### PR DESCRIPTION
**Pull request by et2010**
This layer adds integration of https://github.com/tldr-pages/tldr which is a collection of simplified and community-driven man pages.

### CODE REVIEW

**Comment by fiveNinePlusR** [comment]
looks good to me. The only thing that requires some thought is if those key bindings are the right ones to use.

**Comment by et2010** [comment]
I'm using the `SPC d m` keybinding for `tldr`. Is `SPC d t` better?

**Comment by fiveNinePlusR** [comment]
I looked through the layers and it seems like that is not bound to anything. spc d seems to be mainly for the dash layer but could be renamed to documentation. I personally would suggest that you change the prefix for that leader to show "documentation" instead of dash(look for set-prefix for that). not sure where that would best be put though as it's currently not set with the dash layer. perhaps one of the maintainers knows a good place to put it so it works for both dash and tldr regardless of which layer is installed.

**Comment by robbyoconnor** [comment]
I agree -- change the prefix from `SPC d` please.

**Comment by et2010** [comment]
@fiveNinePlusR @robbyoconnor Thanks for the feedback! I've changed the prefix to 'documentation`.

**Comment by robbyoconnor** [comment]
LGTM.

**Comment by BadDecisionsAlex** [comment]
I want this <3
Thank you!

**Pull request closed without merging**
