### PR TITLE
Require a package dependency of inspector package

### PR DESCRIPTION
**Pull request by bryce-carson**
Fixes an function definition error caused by a missing package dependency in the Emacs Lisp layer.

### CODE REVIEW

**Comment by sunlin7** [comment]
It should consider as an issue of `tree-inspector`.
Using the `Package-Requires:` in its main file can resolve this dependency issue.
https://github.com/mmontone/emacs-inspector/pull/25

**Comment by bryce-carson** [comment]
> It should consider as an issue of `tree-inspector`. Using the `Package-Requires:` in its main file can resolve this dependency issue. [mmontone/emacs-inspector#25](https://github.com/mmontone/emacs-inspector/pull/25)

Thank you for the constructive criticism.

I don't know package development, and I'm really, horribly understudied in the layering and package configuration maintenance of Spacemacs, so it's not surprising that there is a better place for this proposed fix (upstream, of course!). I'll close this pull-request, as it will be made redundant if upstream participates.

**Comment by sunlin7** [comment]
Hi @bryce-carson 
Since the inspector package owner consider it's a package management issue, so neither the Spacemacs nor the inspector won't fix this issue.
Suggest you add the `treeview` to the `dotspacemacs-additional-packages`,

**Comment by lebensterben** [comment]
since upstream refuses to fix the issue. I reopened this PR.

**Comment by bryce-carson** [comment]
> since upstream refuses to fix the issue. I reopened this PR.

I will read the documentation for authoring layers, update this branch, and then request review.

**Comment by sunlin7** [comment]
Currently Spacemacs only target on two inspector functions `inspect-expression` and `inspect-last-sexp`.
https://github.com/syl20bnr/spacemacs/blob/e4b20f797d9e7a03d9a5603942c4a51ea19047b2/layers/%2Blang/emacs-lisp/packages.el#L380-L382

Spacemacs don't use any `tree-inspector-*` functions, no need to depends on `treevew`. 

If Spacsemacs bind a function to `tree-inspector-*`, then we should add `treeview` into the dependency list.

**Comment by sunlin7** [comment]
@bryce-carson  @lebensterben 
Now `tree-inspector` is a standalone package, won't be included in the `inspector` pacakge. 
And the package management can process the dependency correctly.

**Comment by bryce-carson** [comment]
> @bryce-carson  @lebensterben 
> Now `tree-inspector` is a standalone package, won't be included in the `inspector` pacakge. 
> And the package management can process the dependency correctly. 

Okay. I'll upgrade my packages and recompile and see if I get the same warning about a missing function definition.

**Review by smile13241324 — APPROVED** [review]

**Pull request merged**
