### PR TITLE
Fix treemacs-project-toggle (SPC p t)

### PR DESCRIPTION
**Pull request by Trapez**
Seems to be caused by projectile-project-root returning nil.

### CODE REVIEW

**Comment by duianto** [comment]
### Issue:
If `SPC p t` is pressed in a non-project buffer, for example: `.spacemacs`, before helm has been loaded (this occurs right after starting Spacemacs, before opening a helm buffer), then this error message is shown:
>user-error: Please install helm from https://github.com/emacs-helm/helm


And after helm has loaded, then `SPC p t` from a non-project buffer opens a helm projectile buffer.
But when a project is chosen, then Treemacs opens with the selected project, but it's name is a dash: `-`


The non-project buffer error message has been discussed and solved upstream:
Add an error message to: do add project to workspace #380
https://github.com/Alexander-Miller/treemacs/issues/380

The new Treemacs function: `treemacs-add-and-display-current-project`
shows an error message if the current buffer isn't part of a project:
>[Treemacs] Not in a project.

### A possible solution
I've been working on a possible solution that uses built-in Treemacs functions:
```elisp
(defun spacemacs/treemacs-project-toggle ()
  "Toggle Treemacs closed/open and add the current project root.
If Treemacs is:
- Open: Close Treemacs.
- Closed: Open Treemacs:
  - If the current buffer isn't part of a project: Show an error message.
  - If the current buffers project root:
    - Exists in Treemacs: Select the projects root.
    - Doesn't exist in Treemacs: Add the project and select the current file."
  (interactive)
  (treemacs-with-toggle (treemacs-add-and-display-current-project)))
```

This requires adding `treemacs-with-toggle` to the `treemacs/init-treemacs` function in `treemacs/packages.el`
```elisp
(defun treemacs/init-treemacs ()
  (use-package treemacs
    :commands (treemacs-select-window
               treemacs-with-toggle
               treemacs--window-number-ten)
...
```

### Possible improvements
I hadn't created a PR for it yet because there's a slight inconvenience with the current `SPC p t` behavior.

If Treemacs is open and one navigates to a file in a project that isn't listed in Treemacs, and one want to add that project to Treemacs, then:
`SPC p t` detects that Treemacs is open and closes Treemacs.
`SPC p t` again opens Treemacs and adds the new project.

It seems like one should be able to add the current project while still keeping Treemacs open.

And with this PR's suggestion of opening Helm Projectile if there's no project, that might be better than just showing an error message.

**Comment by smile13241324** [comment]
Nice fix :+1: , I have cherry-picked your commit into spacemacs, you can safely remove your branch.

**Comment by duianto** [comment]
@smile13241324 I'm guessing that you pulled the PR before I posted the comment. This introduces two issues. They are not bad, but they might cause some confusion.

**Comment by smile13241324** [comment]
Sorry @duianto I have misread your comment, I have thought that the issues has been already solved by the author. As my test worked well I have just merged it.

Thanks for pointing this out, I will try to fix the issues shortly.

**Comment by duianto** [comment]
No problem, at least the helm issue is a side effect of Spacemacs lazy loading helm, so it's not encountered with everyday use.

**Pull request closed without merging**
