### PR TITLE
Switch the default distribution to spacemacs

### PR DESCRIPTION
**Pull request by robbyoconnor**
This will cause a lot of confusion for newcomers. It is documented that it's an option.

### CODE REVIEW

**Comment by izahn** [comment]
It is documented as an option, but I can't find a description of what the differences are between the available options. What happens if I set it to `spacemacs`? What happens if I set it to `spacemacs-base`?

**Comment by robbyoconnor** [comment]
Not really right now -- it'e mentioned in passing in the changelog and in the .spacemacs template file...if you're really curious check out the package.el files in the respective directories [here](https://github.com/syl20bnr/spacemacs/tree/develop/layers/+distribution).

**Comment by robbyoconnor** [comment]
It will definitely be documented prior to the 0.104 release I am sure.

**Comment by robbyoconnor** [comment]
@syl20bnr -- Ping :)

**Comment by cmccloud** [comment]
@izahn you can take a look at the various packages brought in by spacemacs and spacemacs-base in the new layers/distribution folder. Like robbyoconnor said, the first is a superset of the second. Previous versions of spacemacs used all of hte packages from both layers, so use 'spacemacs if you don't want to see any changes.

**Comment by justbur** [comment]
This will break `dotspacemacs/install`

**Comment by robbyoconnor** [comment]
I might have missed it...I'll address that when I'm near my laptop and fix
it.

--Rob

**Comment by robbyoconnor** [comment]
@justbur are you certain this is the case? There was already a default...I just switched it.

**Comment by robbyoconnor** [comment]
This is a simple fix!

**Comment by robbyoconnor** [comment]
@justbur, fixed. That was a simple fix :) The reason for this is so that people can just copy it over...

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
Cherry-picked intro develop branch, you can safely delete your branch.

**Pull request closed without merging**
