### PR TITLE
Disable evil-snipe in magit-status-mode.

### PR DESCRIPTION
**Pull request by person808**
Evil-snipe takes over the keybinding for s, making it impossible to
stage part of a hunk.

### CODE REVIEW

**Comment by syl20bnr** [comment]
Nice catch, thank you ! :+1: 
Cherry-picked in `develop` branch, you can safely delete your branch.

**Comment by person808** [comment]
This broke on me for some reason. There is an error when opening `magit-status`.

Traceback:

```elisp
Debugger entered--Lisp error: (wrong-number-of-arguments (2 . 2) 3)
  advice-remove(evil-force-normal-state :before evil-snipe--pre-command)
  turn-off-evil-snipe-mode(t)
  evil-snipe-mode(-1)
  (lambda nil (evil-snipe-mode -1))()
  run-hooks(change-major-mode-after-body-hook special-mode-hook magit-mode-hook magit-status-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook special-mode-hook magit-mode-hook magit-status-mode-hook))
  run-mode-hooks(magit-status-mode-hook)
  magit-status-mode()
  magit-mode-init("/home/kainalu/.emacs.d/" magit-status-mode magit-refresh-status)
  apply(magit-mode-init "/home/kainalu/.emacs.d/" (magit-status-mode magit-refresh-status))
  magit-status("/home/kainalu/.emacs.d/")
  call-interactively(magit-status nil nil)
  command-execute(magit-status)
```

**Comment by sooheon** [comment]
Maybe this should be reopened? Getting the same error in latest develop:
`turn-off-evil-snipe-mode: Wrong number of arguments: (2 . 2), 3`

**Comment by person808** [comment]
@syl20bnr @sooheon I fixed it. New PR incoming :)

**Pull request closed without merging**
