### PR TITLE
Add a configuration layer for Elpy.

### PR DESCRIPTION
**Pull request by bonega**
Look at the readme for recommended usage.
Elpy: https://github.com/jorgenschaefer/elpy

Why?
Mostly because I find Elpy more pleasant to work with.
Much better auto-completion for instance.

### CODE REVIEW

**Comment by bonega** [comment]
Note also that I have stolen most of the base layer from lang/python.
Thanks for providing that as an example.

**Comment by syl20bnr** [comment]
Thank you for this PR. This is interesting but Elpy is a big beast so I need more information on it.

Can you provide more information about what Elpy brings to the table ? Does it have _exclusive_ useful features that wouldn't work without it ? Does it have killer features ? Can we take some useful functions from it and add them to the current Python layer instead ?

**Comment by syl20bnr** [comment]
I looked more closely at Elpy and I'm open to consider it for spacemacs. We will have to choose between the current python layer and Elpy. I don't want to confuse the user with 2 python layers.

On the + side for Elpy:
- pyvenv author is the author of Elpy so we can expect it is well-integrated
- the code is well tested

On the - side for Elpy:
- pretty big code base on top of what we have (dispatch between elisp and python code)
- monolithic solution (but packages can be omitted, I hope we can tailor it for spacemacs)
- refuse to officially support flycheck (but there is known solution to replace flymake)

@danielwuz @CestDiego Did you used Elpy in the past ? Could you try it by fetching this PR ?

**Comment by bonega** [comment]
I agree with you points.

Anaconda claims to use Jedi for completion, which should mean that they have the same type of completion.
Sadly I can't get it to work as well as Elpy.
This is my main complaint with Anaconda, perhaps it is just buggy for me?
I have jedi installed globally and in every virtualenv used.

Using Elpy:
If I write `'a string'.` there will be immediate auto-complete alternatives for all String functions. 
In Anaconda nothing is seen before 3 chars are written and many alternatives are garbage from my local namespace.
Ex: `'a string'.lockfile`

I agree with Elpy containing a whole lot of code for autocompletion and eldoc.(more or less what I use).
For example:

Project management - Better to use git/projectile for this.
Rope support - I think that it should be deprecated.

**Comment by danielwuz** [comment]
Yes. 

I actually started off by using Elpy with `emacs-prelude`. Elpy, by itself, is a pretty complete development environment solution for python. It has lots of overlapping functionality with `prelude` by that time, things that I don't need, like project file management, indentation blocks, especially when I started to use `evil` mode. Later someone integrated `anaconda-mode` into `prelude`, then I abandoned my personal configuration for `Elpy` and switched to `anaconda-mode`.

I've been happy with `anaconda-mode` since then because it feels more light-weight and works just fine out of box, whereas with `Elpy` I believe users need to install `jedi` or `rope` manually, but I don't think it's a big deal if we document properly.

Although I don't see any thing missing in our current python contrib, I'm also open to have `Elpy`. But instead of a separate contrib, I think it's a good idea to integrate it with the current one somehow, and make it as an option, so that a user can choose between `anaconda` and `elpy`, and we don't end up with maintaining two pieces of duplicate code.

How do you think?

**Comment by danielwuz** [comment]
@bonega Tested the case you gave, I think it's just some bug in your `anaconda` config:). Hitting `.` after a string, e.g.
```
'a string`.
```
triggers auto-completion popup with all available functions for me. See [screenshot](https://www.dropbox.com/s/ck8qqo5wr66ldri/Screen%20Shot%202015-01-02%20at%2011.42.48%20AM.png?dl=0)

**Comment by bonega** [comment]
@danielwuz that is strange, might you be using `company-mode`?
Apparently python-completion will not work for me without it.

**Comment by danielwuz** [comment]
@bonega yes, I do use `company` mode, which is the one `Elpy` use by default. Does `anaconda` auto complete on `dot` for you if you use `company-mode` contrib?

**Comment by bonega** [comment]
@danielwuz yeah, I was a bit unclear in my wording.

**Comment by danielwuz** [comment]
@bonega `ac-anaconda` does not auto complete on `dot` for me neither. But as soon as I started typing `ac-auto-start` length of letters, candidates menu pops up. That's the way how `auto-complete` works.

**Comment by danielwuz** [comment]
It's a feature, not a bug =)

**Comment by bonega** [comment]
That might be, but it still tries to complete with more or less everything in the local namespace

**Comment by danielwuz** [comment]
`auto-complete` is just a front-end, it reads all candidates from `ac-sources`. You might check the value of `ac-sources` and see which backend provides the garbage candidates.

**Comment by syl20bnr** [comment]
Between `anaconda-mode` and `elpy` the choice is not hard. We will stick with `anaconda-mode`. If `elpy` does no bring anything useful to the table I only see drawbacks to use it, be it in the current python layer or in a separate layer (even worst).

@bonega did you succeed in using the python layer with company ? If yes, does it fulfil your needs ?

**Comment by bonega** [comment]
I agree, `anaconda-mode` should stay.
My problems right now are mostly related to #374 
I am closing this PR.

**Pull request closed without merging**
