### PR TITLE
Make evil-org a local package

### PR DESCRIPTION
**Pull request by TheBB**

### CODE REVIEW

**Comment by fintelkai** [comment]
Seems to work here and seems to solve the problem of `SPC o` bindings being clobbered. Thanks!

**Comment by CestDiego** [comment]
So this is an unofficial fork? :P

**Comment by syl20bnr** [comment]
Indeed unofficial fork, I guess at some point we will have to work on our own "evilified" org.
Thank you!
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by CestDiego** [comment]
Time to take `evil-org` out of the excluded packages :3

**Pull request closed without merging**
