### PR TITLE
Add note on erc-tls usage to README

### PR DESCRIPTION
**Pull request by swaroopch**

### CODE REVIEW

**Comment by CestDiego** [comment]
Why not connect securely everytime?

**Comment by swaroopch** [comment]
@CestDiego Because the port numbers are different, and default is not the secure one. I don't think we should use whatever default ERC does so as to not confuse users.

**Comment by syl20bnr** [comment]
Currently the key bindings in develop branch for ERC is <kbd>SPC a i e</kbd>. I propose to add <kbd>SPC a i E</kbd> for the secured version.

**Comment by syl20bnr** [comment]
I merged it and added <kbd>SPC a i E</kbd> key binding in e44996690337b6dd460b7d281267954f31cdd195

Thank you ! 
Cherry-picked in `develop` branch, you can safely delete your branch.

**Comment by swaroopch** [comment]
:+1:

**Pull request closed without merging**
