### PR TITLE
Added sqlite3 requirement info

### PR DESCRIPTION
**Pull request by Melon-Bread**
I added a note in the readme letting the user know to make sure they have a sqlite3 install for Helm Dash per request of #7501 . I am still very new to pull requests and such so if I did something wrong let me know and I will do my best to fix it.

### CODE REVIEW

**Comment by NJBS** [comment]
Thanks for the PR! 😄 

Please note that Spacemacs [requires PRs to be opened against the `develop` branch](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org#pull-request). Could you kindly resubmit your PR so it complies with the contribution guidelines?

You might find the [Beginner's Guide to Contributing a Pull Request to Spacemacs](https://github.com/syl20bnr/spacemacs/wiki/Beginner's-Guide-to-Contributing-a-Pull-Request-to-Spacemacs) helpful!

**Comment by JAremko** [comment]
YAY IT WORKS! https://travis-ci.org/syl20bnr/spacemacs/jobs/169247531 :laughing:

**Comment by Melon-Bread** [comment]
Oh my apologies I saw that and guess I did not switch branches like I had thought. I will do so now

**Comment by syl20bnr** [comment]
Closing in favor of #7507

**Pull request closed without merging**
