### PR TITLE
holy-mode: Assume we are always in emacs state

### PR DESCRIPTION
**Pull request by justbur**
There's some confusion about holy-mode, because users are accidentally
getting into another evil state and don't know what to do. The
assumption should be that if holy mode is enabled we are *always* in
emacs state, so we don't provide any easy means of getting out of it.

#3495 
#3473 
#3453

### CODE REVIEW

**Comment by syl20bnr** [comment]
This PR removes too much stuff. We only need to not override the `ESC` key. Being able to switch editing style dynamically is a feature that cannot be removed, if there are bugs we have to fix them.

**Comment by justbur** [comment]
You can switch editing styles dynamically with this. `evil-buffers-regexp` overrides all of the mode specific stuff, so it's not necessary to change those.

**Comment by syl20bnr** [comment]
Perfect :-1:  You should make several commits then, in its current state this commit tells the why but not the what and how (which are more important to me, for the why just use issue ids with `Fixes`). I would prefer one commit for the ESC key and another one for the great simplification.

**Comment by justbur** [comment]
ok, I can do that. No problem

**Comment by justbur** [comment]
@syl20bnr It's split into two commits

**Comment by justbur** [comment]
On second thought maybe there should be a variable that allows the old behavior too

**Comment by syl20bnr** [comment]
The old behavior is hybrid no ? I have to look at those evilified state in hybrid state, I know we have a PR you submitted but maybe we just need a global toggle for evilification instead ?

**Comment by justbur** [comment]
No not really. The old behavior was to always start in emacs state, allow
users to escape to normal state, and override evil-insert-state. This turns
the last two off by default.

**Comment by syl20bnr** [comment]
If we can toggle off the evilification, hybrid looks like the old behaviour to me. And I like the fact that having ESC to switch to normal state is an hybrid thing.

**Comment by syl20bnr** [comment]
Ah there is the default state too. All this can be hybrid options. Actually should be hybrid options from the beginning.
At start we had not the hybrid style, now we have it we can make Emacs style as authentic as possible and put the options for hybrid behaviour in hybrid style.

**Comment by justbur** [comment]
> At start we had not the hybrid style, now we have it we can make Emacs style as authentic as possible and put the options for hybrid behaviour in hybrid style.

I think it shouldn't be that hard to have a mode that disables evil entirely and makes the right adjustments for the mode-line, helm, etc. Is that what you mean by "as authentic as possible"?

Also there's another distinction between hybrid and emacs that's relevant to these issues. The reason these issues came up is because some people want to use ESC as a meta key, which is only possible with evil on in emacs state. Since hybrid uses a variation of insert state, this could be tricky to disable there.

**Comment by syl20bnr** [comment]
I was not very clear sorry.
I mean `ESC` to go to normal state is an hybrid thing which is already covered by hybrid-mode right now. The toggles are for:
1) evilification
2) default state
Which only purpose is to fine tune the hybrid mode.

**Comment by syl20bnr** [comment]
Hybrid without normal state is not hybrid in my opinion so it makes little sense to remove ESC.

**Comment by nixmaniack** [comment]
I would prefer the current hybrid left untouched. Yes, hybrid without normal mode is almost emacs state then. I even prefer buffers be opned in normal state even if I'm using hybrid, only when I enter insert state I should have all keys as emacs way for editing text, but for getting out of that state let it be `ESC`.

**Comment by syl20bnr** [comment]
Hybrid will be left untouched, those would be options to alter it, default values will setup the hybrid as it is right now.

**Comment by justbur** [comment]
Closing in favor of #3514

**Pull request closed without merging**
