### PR TITLE
Add a new ASCII banner

### PR DESCRIPTION
**Pull request by bryce-carson**
This banner was created using [TAAG](https://patorjk.com/software/taag/), the
Delta Corps Priest 1 FIGFont created by CoSMiC cHiLD, and Spacemacs.

🄯 2022 Bryce Carson

### CODE REVIEW

**Comment by lebensterben** [comment]
What’s the point of this?

**Comment by bryce-carson** [comment]
Fun. :)

**Comment by lebensterben** [comment]
no thanks

**Comment by arifer612** [comment]
I agree with @lebensterben
This is not a Spacemacs banner and would better serve as part of a personal configuration.

**Comment by robbyoconnor** [comment]
> 🄯 2022 Bryce Carson

What the... seriously?

**Comment by robbyoconnor** [comment]
@bryce-carson Copyright is antithetical to the GPL and copyleft.

**Comment by bryce-carson** [comment]
> @bryce-carson Copyright is antithetical to the GPL and copyleft. 

That is the copy left symbol.

**Comment by robbyoconnor** [comment]
Oh shit, I missed that - sorry @bryce-carson

**Comment by bryce-carson** [comment]
> Oh shit, I missed that - sorry @bryce-carson 

No worries. You'll also note that all of `core/*` is copyrighted.

**Pull request closed without merging**
