### PR TITLE
Fix key binding part in c-c++/README.org

### PR DESCRIPTION
**Pull request by fenxian**
:smile:

### CODE REVIEW

**Comment by fenxian** [comment]
@StreakyCobra  Thank you for your help in https://github.com/syl20bnr/spacemacs/pull/4561

Is It right now?
I am studing it .. This is my first PR~~ :smiley:

**Comment by AlejandroCatalina** [comment]
It seems fine now ;). It is also a good workflow to create a new branch for each feature or fix you work on, so you can make changes to your local branch without altering the PR.

**Comment by fenxian** [comment]
@AlejandroCatalina  Thank you~ :ok_hand:

**Comment by syl20bnr** [comment]
Thank you :+1: 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
