### PR TITLE
Implement helm-dir-search

### PR DESCRIPTION
**Pull request by jgertm**
I found myself wishing for this functionality.

 It behaves like the other helm-search wrappers, with the current directory as the scope of the search.

### CODE REVIEW

**Comment by TheBB** [comment]
Is there a reason why you let-bind `default-directory` to `dir`, using that as an argument, instead of just calling with `default-directory` as a function argument directly?

**Comment by TheBB** [comment]
IOW, why

```elisp
(let ((dir default-directory))
  (some-function dir))
```

instead of

```elisp
(some-function default-directory)
```

**Comment by jgertm** [comment]
Mostly misguided aesthetic sensibility.

**Comment by jgertm** [comment]
@TheBB ping

**Comment by TheBB** [comment]
You neglected the ivy layer so I had to do that myself. That's why it took a while. https://github.com/syl20bnr/spacemacs/commit/ebc6ba015eef0184d9bb46dabd2052b004baf652

Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
