### PR TITLE
Fix a typo introduced when setting up org-babel support

### PR DESCRIPTION
**Pull request by robbyoconnor**
Fix a typo introduced in 42a33f3ae8c58b8f416207e6d553dbcbd78e5385

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@syl20bnr may wanna rush this before next release

**Comment by d12frosted** [comment]
Thank you :+1: Cherry-picked into `develop`, you can safely delete your branch.

**Comment by robbyoconnor** [comment]
Why is it showing merged?

**Comment by d12frosted** [comment]
Because sometimes during rebase fast-forward is used -> the same as merge.

**Comment by robbyoconnor** [comment]
Ah :)

**Pull request merged**
