### PR TITLE
add clang-format support to the c-c++ layer

### PR DESCRIPTION
**Pull request by gnzlbg**
This adds a configuration layer for clang-format

### CODE REVIEW

**Comment by syl20bnr** [comment]
Thank you for the PR. Since it is related to C/C++ it should go in the `c-c++` layer.

**Comment by gnzlbg** [comment]
AFAIK clang-format also supports Java so it might be worth it to integrate it there too. 

I'll take a look at the c-c++ layer and figure out how I can integrate it there. It should probably be opt-in only.

**Comment by gnzlbg** [comment]
It seems that something wrong happened :/

**Comment by tuhdo** [comment]
You should add a variable `c-c++-use-clang-format` and if set to `t`, it will be installed, since not everyone uses Clang. It should look similar to [this](https://github.com/syl20bnr/spacemacs/blob/master/contrib/git/packages.el#L42).

**Comment by gnzlbg** [comment]
Like this?

**Comment by tuhdo** [comment]
You have to add a variable to include it after including `c/c++` layer. For example, you can include `git` layer like this in your .spacemacs:

```
(git :variables
                                            git-enable-github-support t
                                            git-gutter-use-fringe t)
```

Only when you enable ` git-enable-github-support`, Github related packages are installed. Similarly, only when `git-gutter-use-fringe` is set, `git-gutter` is installed to show changes in the fringe.

**Comment by gnzlbg** [comment]
Setting the variable `c-c++-use-clang-format` to `t` and `nil` works as expected. 
Leaving it out completely produces the error:

```
An error occurred while initializing clang-format (error: (void-variable c-c++-use-clang-format))
```

**Comment by person808** [comment]
Add the variable to the `c-c++` config.el file using `defvar`. If the file doesn't exist, create it.

**Comment by tuhdo** [comment]
That's right. I forgot it. You must define the variable at the top with `defvar`.

**Comment by gnzlbg** [comment]
Thank you guys, now one can enable/disable clang-format at will and it works as expected on all cases.

Are the additions to the README file ok?

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
I changed the variable to the more general variable `c-c++-enable-clang-support` and updated the README accordingly, relate commit: https://github.com/syl20bnr/spacemacs/commit/b7dfc18

Cherry-picked into `develop`.

**Comment by gnzlbg** [comment]
:)

**Pull request closed without merging**
