### PR TITLE
spacemacs-layouts: fix creation of perspective with ivy

### LINKED ISSUE #10240: REGRESSION: spacemasc/ivy-persp-switch-project no longer creates new layouts
#### Description :octocat:
`SPC p l` / `spacemacs/ivy-persp-switch-project` no longer creates layouts after
4b111f7701ffea8e724666471a64867fe0c7af22 (and the subsequent fixes).

/cc @tadfisher 

#### Reproduction guide :beetle:
- Start Emacs
- `SPC p l`
- Select a project
- `SPC l l`

*Observed behaviour:* :eyes: :broken_heart:
The selected project does not have a layout in the list of layouts.

*Expected behaviour:* :heart: :smile:
The selected project should have a layout in the list of layouts.

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 03343a7f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(rust octave gtags swift nginx better-defaults spacemacs-layouts ivy
      (markdown :variables markdown-live-preview-engine 'vmd)
      (syntax-checking :variables syntax-checking-enable-tooltips t)
      (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup nil spacemacs-default-company-backends
                       '(company-capf
                         (company-dabbrev-code company-keywords)
                         company-files company-dabbrev))
      git dash pdf-tools html
      (org :variables org-enable-github-support t org-enable-reveal-js-support t org-want-todo-bindings t)
      colors
      (osx :variables osx-command-as 'super)
      (github :variables magit-gh-pulls-pull-detail-limit 200)
      (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
      (spell-checking :variables spell-checking-enable-by-default nil)
      version-control rcirc tmux yaml docker restclient lua chrome
      (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
      emoji aj-elixir aj-emacs-lisp aj-javascript aj-term aj-typescript aj-ruby auto-correct cleverparens-lispy dotenv flow match-indent shift-number writing)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES LCMS2

### PR DESCRIPTION
**Pull request by nixmaniack**
Fix #10240

### CODE REVIEW

**Comment by aaronjensen** [comment]
Tested scenario in #10240 and it worked. Ensured that you could switch to existing layouts w/o creating new ones and that new ones are created as necessary.

Ready to be merged! (@syl20bnr @TheBB @d12frosted @bmag @JAremko)

**Comment by aaronjensen** [comment]
Originally reported as #10193

**Comment by semihalf-dubiel-michal** [comment]
This fixes #10193 as well.

**Comment by syl20bnr** [comment]
Thank you ! 👍 
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
