### PR TITLE
Add jsfmt package to javascript lang layer.

### PR DESCRIPTION
**Pull request by geksilla**
Added plugin [jsfmt.el](https://github.com/brettlangdon/jsfmt.el) to javascript layer and installation instruction.

### CODE REVIEW

**Comment by geksilla** [comment]
@TheBB, @StreakyCobra, can you check this one when you'll have an opportunity? Thanks!

**Comment by robbyoconnor** [comment]
:+1:

**Comment by ikhthiandor** [comment]
:+1:

**Comment by laduke** [comment]
Is there something I could do to help this get merged? Was it just the README conflict that stopped it? 
Using jsfmt could possible reduce the amount of incoming "JSX / ES6 / ES7 indenting doesn't work" issues.

**Comment by geksilla** [comment]
Resolved merge conflicts.

**Comment by Compro-Prasad** [comment]
@syl20bnr Any updates on this?

**Comment by robbyoconnor** [comment]
You know how things work around here..be patient.

**Comment by Compro-Prasad** [comment]
I think jsfmt is already there in react layer but there is no mention of the package. We also have `web-beautify` which should be enough to format things. @sdwolfz This can be closed if we already have jsfmt else we can ask @geksilla to update this PR.

**Comment by robbyoconnor** [comment]
@geksilla Rebase needed :)

**Pull request closed without merging**
