### PR TITLE
which-key: Allow evil-operators to popup buffer

### PR DESCRIPTION
**Pull request by justbur**
I'm adding some stuff to which-key that is automatically activated if evil is loaded.

I can do this in the which-key config, but this seems simpler and doesn't affect anything in spacemacs.

### CODE REVIEW

**Comment by justbur** [comment]
I had a change of heart on this. The new commit just sets the new which-key option instead of relying on the load order

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

I assume it's intended that I will get which-key after e.g. `di` but not after just `d`?

**Comment by justbur** [comment]
Not necessarily intended but I think d is a complete command and which key
looks for prefix commands as it's written.

**Comment by justbur** [comment]
@TheBB just curious. How useful would that be?

**Comment by TheBB** [comment]
Not sure. I know some people wanted this. I can imagine it helps learning evil. The reason I asked was just because I thought that was what you were implementing.

**Comment by justbur** [comment]
It just shows the inner and outer object maps now because that was the easy
part. Having a popup without a prefix key is something that has been
discussed but it will take more time because the code has to be rewritten.
I'll try at some point

**Pull request closed without merging**
