### PR TITLE
Fix #6500, only change ediff hook if org loaded

### LINKED ISSUE #6500: `outline-show-all` void when using `ediff`
When trying to use `ediff` through `SPC f e D` I'm getting the error: `Symbol function definition is void: outline-show-all`.

This bug might have been introduced recently. It happened just after I pulled from `develop` today.

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. a650877)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm html auto-completion emacs-lisp git github haskell html java markdown osx
      (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t)
      scala spell-checking syntax-checking version-control yaml)
```

### PR DESCRIPTION
**Pull request by NJBS**
Fix https://github.com/syl20bnr/spacemacs/issues/6500

### CODE REVIEW

**Comment by syl20bnr** [comment]
Thank you ! 👍 
I moved the code to the org layer in commit: https://github.com/syl20bnr/spacemacs/commit/93f09bc
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by NJBS** [comment]
Thanks for the merge!

Does `post-init-ediff` preserve the dependency? It seems to me this would just add `outline-show-all` back into the hook after ediff has loaded, without org or the function necessarily being loaded yet.

**Comment by syl20bnr** [comment]
My bad, can you revert my commit? Or move the hook to `default-org-config` in `spacemacs-org` layer ?

**Comment by NJBS** [comment]
Sorry, just saw this message.

Fortunately, @d12frosted Has a working solution which uses the alias from outline instead of the one from org :smile: 

https://github.com/syl20bnr/spacemacs/pull/6527

**Pull request closed without merging**
