### PR TITLE
elisp: add "gb" binding for pop-tag-mark

### PR DESCRIPTION
**Pull request by grammati**

### CODE REVIEW

**Comment by StreakyCobra** [comment]
You should document the new keybinding in the layer's `README` :relaxed:

**Comment by grammati** [comment]
Thanks for pointing that out. I pushed a new commit with the README change.

**Comment by StreakyCobra** [comment]
:+1:

**Comment by nwolfe** [comment]
:+1: - we used to have this

**Comment by syl20bnr** [comment]
Maybe we could make it global under `gb` in normal state ?

**Comment by kRITZCREEK** [comment]
+1 for having it available under just gb

**Comment by TheBB** [comment]
This is another feature which we should have a generic solution for, if at all.

**Pull request closed without merging**
