### PR TITLE
spacemacs-base does not exist.

### PR DESCRIPTION
**Pull request by robbyoconnor**
This fixes a small typo...if it was a typo...if not feel free to simply close this PR as invalid.

### CODE REVIEW

**Comment by TheBB** [comment]
Pretty sure it will be renamed, as per https://github.com/syl20bnr/spacemacs/pull/3002#issuecomment-140393516.

**Comment by robbyoconnor** [comment]
Hmm ok -- as I said -- feel free to reject...should I just close this?

**Comment by TheBB** [comment]
Well, if you feel like it you can do the renaming in this PR instead. :-P

Otherwise, I'm pretty sure this can be closed and we'll just wait for @syl20bnr to do the renaming instead.

**Comment by robbyoconnor** [comment]
What I was gonna do was rename it for him and do a PR :)

**Pull request closed without merging**
