### PR TITLE
* layers/+tools/shell/funcs.el: Avoid loading semantic for eshell

### PR DESCRIPTION
**Pull request by sunlin7**
The `eshell` layer try to exclude the `semantic-mode` but leading a heavy loading. Reproducing steps:
1. Enable the layers `semantic`, `eshell`.
2. Start Spacemacs and then start the `eshell`, it will lead the `semantic` feature been loaded (but not activated).

This PR speeds up the eshell by avoiding loading the `semantic` feature.

### CODE REVIEW

**Review by fnussbaum — APPROVED** [review]
The change is fine, though I think we should reconsider disabling a global minor mode in a mode hook like that.

**Comment by sunlin7** [comment]
Agree, I'm going to research the way to disable semantic mode locally.

**Comment by fnussbaum** [comment]
I am not sure why it gets disabled at all, perhaps it is does not need to be.

**Comment by sunlin7** [comment]
The action turning off `semantic-mode` for `eshell` was introduced in the commit
https://github.com/syl20bnr/spacemacs/commit/40487778e697a680c762fccde5c7407cc2a68277
there is no comment why need turn off it.

I tried the eshell with turning on semantic mode, try function `semantic-mode-ia-fast-jump`, there is a message says `Cannot analyze buffers not supported by Semantic`, same behavior on Spacemacs and vanilla Emacs.

**Comment by sunlin7** [comment]
I create the PR #16728 to remove the line.

**Pull request merged**
