### PR TITLE
Locate layers in arbitrary subdirectories

### PR DESCRIPTION
**Pull request by TheBB**
Sorry, I had a minor misunderstanding with git yesterday and the branch vanished, since I figured it wouldn't be merged anyway. Here it is again. See #1622 for the previous discussion.

Ping @syl20bnr @trishume

### CODE REVIEW

**Comment by syl20bnr** [comment]
@TheBB Thank you !

After sleeping on it a bit I decided to merge it  and will move the category things directly inside the layers (in config.el for instance). For the possibility to add layer on remote repo it will be easily achieved via the `dotspacemacs-configuration-layer-path` variable where we could add a repo URL for instance.

**Comment by syl20bnr** [comment]
I have to ship the `0.102.0` though I think this change will go in `0.103.0`. The `0.102.0` is almost ready so it should not be too long before this PR is merged.

**Comment by TheBB** [comment]
Sure, that's not a problem.

**Comment by syl20bnr** [comment]
Thank you ! Nice work :+1: 
I added auto-discovery of categories which are directories starting with `!`, they were introduced after your PR. The `!` is optional and categories don't have any value for now. Related commit: https://github.com/syl20bnr/spacemacs/commit/86c94a2

Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
