### PR TITLE
Make scratch buffer major mode configurable

### LINKED ISSUE #690: Make *scratch* Emacs LIsp by default
@syl20bnr  We shouldn't change it to `Text`. I guess it is because you want `*scratch*` to be something to temporary store text.  However, we can always create a new temporary  buffer by entering non-existent buffer name. Otherwise this behaviour should be documented.

### PR DESCRIPTION
**Pull request by TheBB**
Fix #690.

### CODE REVIEW

**Comment by StreakyCobra** [comment]
https://github.com/syl20bnr/spacemacs/blob/de17125e6d0ab4e6c03d024790aaaac064f2b233/layers/%2Bdistribution/spacemacs-base/funcs.el#L867

**Comment by TheBB** [comment]
Thanks. Better now?

**Comment by TheBB** [comment]
Persp-mode won't let me delete the scratch buffer to check...

**Comment by StreakyCobra** [comment]
Tested by excluding `persp-mode`. It works :+1:

**Comment by choppsv1** [comment]
Would be nice to get this merged as it's hard to work around it not being there. :)

**Comment by choppsv1** [comment]
FWIW I think making this text mode by default is misguided. I tested load times and didn't see much if any difference with lisp interaction mode. Additionally from the emacs manual:

> When Emacs starts up, it contains a buffer named *scratch*, which is provided for evaluating Emacs Lisp expressions interactively. Its major mode is Lisp Interaction mode. You can also enable Lisp Interaction mode by typing M-x lisp-interaction-mode.

**Comment by syl20bnr** [comment]
@choppsv1 We cannot guess the major mode for the user so we make as generic as possible by default, I believe this is the saner default.

@TheBB Thank you ! Released in 0.105.7 :+1:

**Comment by choppsv1** [comment]
Sylvain Benner <notifications@github.com> writes:

> @choppsv1 We cannot guess the major mode for the user so we make as generic as possible by default, I believe this is the saner default.

But, you don't have to guess at what to set it to! It's documented in
the manual as "the lisp-interaction-buffer". What we're doing here is
changing it so it violates the documentation. Why?

**Comment by syl20bnr** [comment]
I don't agree with reducing the scratch buffer to lisp interaction by
default, it is even *elisp interaction buffer* in this case. The term
scratch is too general and the usage of Emacs too wide to reduce it to
elisp.

But all this discussion diverged from the main reason why it is text-mode
by default in Spacemacs, this is to avoid loading too much stuff at startup.

Le lundi 11 janvier 2016, Christian Hopps <notifications@github.com> a
écrit :

> Sylvain Benner <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> writes:
>
> > @choppsv1 We cannot guess the major mode for the user so we make as
> generic as possible by default, I believe this is the saner default.
>
> But, you don't have to guess at what to set it to! It's documented in
> the manual as "the lisp-interaction-buffer". What we're doing here is
> changing it so it violates the documentation. Why?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/pull/4424#issuecomment-170541137>.
>


-- 
-syl20bnr-

**Pull request closed without merging**
