### PR TITLE
fix youdao-dictionary toggle cannot work

### PR DESCRIPTION
**Pull request by TinySong**
fix youdao-dictionary cannot load youdao-dictionary package when (chinese :variables chinese-enable-youdao-dict t )

### CODE REVIEW

**Comment by zilongshanren** [comment]
@TinySong  duplicated with https://github.com/syl20bnr/spacemacs/pull/6185

**Comment by TinySong** [comment]
@zilongshanren, Should I close current PR ?

**Comment by StreakyCobra** [comment]
>  Should I close current PR ?

Yes you can.

**Comment by zilongshanren** [comment]
@TinySong  Yes you can

**Pull request closed without merging**
