### PR TITLE
bind-map: Add evilified state to evil major-mode keys

### PR DESCRIPTION
**Pull request by justbur**
Fixes problem referred to in #4495

### CODE REVIEW

**Comment by mskorzhinskiy** [comment]
I've tried to apply your patch and everything works fine, but there are message in *Warnings* buffer.

Text of the message:
"Error (use-package): bind-map :init: Wrong type argument: keymapp, nil"

**Comment by justbur** [comment]
@mskorzhinskiy my mistake. Can you try it once more? It should work now

**Comment by TheBB** [comment]
Can confirm it works! Thanks! Cherry-picked in develop.

**Comment by mskorzhinskiy** [comment]
Everything works fine now. Thanks!

**Pull request closed without merging**
