### PR TITLE
New screenshot without rainbow-identifiers

### PR DESCRIPTION
**Pull request by nashamri**
The existing screenshot is with `rainbow-identifiers-mode` turned on which is not the default setting and made the theme look funny :smile:

### CODE REVIEW

**Comment by d12frosted** [comment]
I support it.

**Comment by robbyoconnor** [comment]
This is fine to do (for now) but in the future -- against `develop` -- See [contribution guidelines](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.md) :P

**Comment by nashamri** [comment]
Sure thing :smile:

**Comment by syl20bnr** [comment]
Very nice ! Feel free to submit new screenshots :-)
Thank you :+1: 
Cherry-picked into develop, you can safely delete your branch.

**Pull request closed without merging**
