### PR TITLE
Prefix categories with !

### PR DESCRIPTION
**Pull request by trishume**
See #1701. Basic summary is that it is currently really hard to tell if a folder in `contrib` is a category or a layer and even if you know it is hard to search through the list for them. `!` was chosen since it is unobtrusive and early in ascii so categories sort first.

This prefix makes life easier for contributors when they are deciding where to place their layers and makes Spacemacs easier to browse in github or a file manager.

I have tested that this massive renaming doesn't muck anything up by cloning spacemacs and going through a fake update with this change. I also checked and the renaming is handled gracefully with respect to merges, I was able to merge pull requests that alter the moved layers with no issues.

Also Github only counts this as a 9 line change (the category list in elisp) so I won't get contributor credit for a bajillion additions and deletions. :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by tuhdo** [comment]
Since you already did it, that's fine then. But, you should also document this change since new users won't have any idea about directories prefixed with `!`.

You should also test if it works with `SPC f e h`.

**Comment by trishume** [comment]
Done, also updated all the links.

**Comment by syl20bnr** [comment]
Good idea ! :+1: 
I wonder how the old PR will do when I'll merge them :-)

Cherry-picked into `develop` branch, you can safely delete your branch.

**Comment by trishume** [comment]
I mentioned that I already tested an old PR and it worked fine. Git is awesome :+1:

**Pull request closed without merging**
