### PR TITLE
Write file with SPC f w.

### PR DESCRIPTION
**Pull request by dschrempf**
Add a spacemacs shortcut to save files with a different name (`write-file`).

### CODE REVIEW

**Comment by nixmaniack** [comment]
This isn't needed since we already have `write-file` wrapper under <kbd>SPC f c</kbd>.

**Comment by dschrempf** [comment]
That's right. However, as far as I know the buffer is still pointing to the old destination then? So the file has to be reopened. Please correct me, if this is wrong! Thanks.

**Comment by CeleritasCelery** [comment]
The buffer is pointing to the new file after `SPC f c`

**Comment by dschrempf** [comment]
Ah OK, thank you. It's interesting that there are two functions that do apparently the same thing.

**Comment by nixmaniack** [comment]
I don't know the exact reasoning of [writing a wrapper on `write-file`](https://github.com/syl20bnr/spacemacs/blob/b4b7d63e41ace986b05ee31c344e7da2f3db5b87/layers/%2Bdistributions/spacemacs-base/funcs.el#L918-L921) but it certainly helps to have a descriptive name in the keybindings pop-up. `copy-file` describes the purpose more prominently than `write-file`.

You can close the issue if you are satisfied with the current binding.

**Pull request closed without merging**
