### PR TITLE
Add functionality to move layouts in layout list

### PR DESCRIPTION
**Pull request by Linuus**
This adds functionality to move layouts in the layouts list as discussed here: https://github.com/syl20bnr/spacemacs/issues/9544

This is the first elisp code I ever write so maybe it's not the best way of doing it...

### CODE REVIEW

**Comment by duianto** [comment]
Tested, and it works 👍 

Would it be possible to implement this for the workspaces transient state `SPC l w` as well?

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 9341e1d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 colors emacs-lisp git helm markdown org spell-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by Linuus** [comment]
@duianto Perhaps. I've never had the need for it but sure :) I have no idea how eyebrowse is implemented or how easy it would be to implement though.

I'll have a look but if this PR is OK I can submit a separate one for workspaces later.

**Comment by bmag** [comment]
Thank you :+1: Cherry-picked into develop, you can safely delete your branch. I added a separate "move-right" and touched the docstring a bit in https://github.com/syl20bnr/spacemacs/commit/cc1970ce447fc8712c4208f8086004c3ad160966

Adding the same for workspaces is going to be much harder, if you manage it then PR welcome.

**Comment by Linuus** [comment]
@bmag thanks! ❤️

**Pull request closed without merging**
