### PR TITLE
Bind `SPC g B` to 'magit-blame-quit

### LINKED ISSUE #2171: magit-blame-quit keybinding
What should be the key binding for magit-blame-quit

### PR DESCRIPTION
**Pull request by synic**
`q` doesn't work, `SPC g b` just blames farther into the history.  There seems to be no action whatsoever on the ticket, other than "me too".  This solves the problem.

Fixes #2171

### CODE REVIEW

**Comment by TheBB** [comment]
:+1: But please also document it.

**Comment by lunaryorn** [comment]
:+1:

**Comment by robbyoconnor** [comment]
Always document, always :heart:

**Comment by synic** [comment]
Haha, deal.  Will add some docs.

**Comment by fbergroth** [comment]
What about using a toggle?
```el
(defun git/toggle-magit-blame ()
  (interactive)
  (if magit-blame-mode
      (magit-blame-quit)
    (call-interactively #'magit-blame)))

(evil-leader/set-key "gb" #'git/toggle-magit-blame)
```

**Comment by synic** [comment]
@fbergroth successive `SPC g b` presses show you farther back in history.

**Comment by fbergroth** [comment]
@synic not if you bind `SPC g b` to `git/toggle-magit-blame` in my previous post.

**Comment by fbergroth** [comment]
Oh sorry, I misread. Nevermind me :)

**Comment by syl20bnr** [comment]
Thank you :+1: 
The proposition of the toggle from @fbergroth was very interesting. Turns out that we do something similar for the git time machine but we use a micro-state instead.
So I defined a micro-state for magit-blame and it seems to work OK, the documentation is lacking though. Related commit https://github.com/syl20bnr/spacemacs/commit/bf7d9a4
Cherry-picked into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
