### PR TITLE
Add Solidity layer

### PR DESCRIPTION
**Pull request by sei40kr**
Forked from @expede's PR
https://github.com/syl20bnr/spacemacs/pull/11907

Please see for solidity layer README:
https://github.com/syl20bnr/spacemacs/blob/4bb61c6958784d1c353cd8e88d6822f3323d8927/layers/%2Blang/solidity/README.org

### CODE REVIEW

**Comment by duianto** [comment]
I'm seeing the same/similar error message as in the original PR: Solidity Layer #11907

When opening this example `.sol` file:

<details><summary>
solidity-layer-test.sol
</summary>
<pre>
/* example file from:
   https://solidity.readthedocs.io/en/latest/solidity-by-example.html */

pragma solidity >=0.4.22 <0.7.0;

/// @title Voting with delegation.
contract Ballot {
    // This declares a new complex type which will
    // be used for variables later.
    // It will represent a single voter.
    struct Voter {
        uint weight; // weight is accumulated by delegation
        bool voted;  // if true, that person already voted
        address delegate; // person delegated to
        uint vote;   // index of the voted proposal
    }

    // This is a type for a single proposal.
    struct Proposal {
        bytes32 name;   // short name (up to 32 bytes)
        uint voteCount; // number of accumulated votes
    }

    address public chairperson;

    // This declares a state variable that
    // stores a `Voter` struct for each possible address.
    mapping(address => Voter) public voters;

    // A dynamically-sized array of `Proposal` structs.
    Proposal[] public proposals;

    /// Create a new ballot to choose one of `proposalNames`.
    constructor(bytes32[] memory proposalNames) public {
        chairperson = msg.sender;
        voters[chairperson].weight = 1;

        // For each of the provided proposal names,
        // create a new proposal object and add it
        // to the end of the array.
        for (uint i = 0; i < proposalNames.length; i++) {
            // `Proposal({...})` creates a temporary
            // Proposal object and `proposals.push(...)`
            // appends it to the end of `proposals`.
            proposals.push(Proposal({
                name: proposalNames[i],
                voteCount: 0
            }));
        }
    }

    // Give `voter` the right to vote on this ballot.
    // May only be called by `chairperson`.
    function giveRightToVote(address voter) public {
        // If the first argument of `require` evaluates
        // to `false`, execution terminates and all
        // changes to the state and to Ether balances
        // are reverted.
        // This used to consume all gas in old EVM versions, but
        // not anymore.
        // It is often a good idea to use `require` to check if
        // functions are called correctly.
        // As a second argument, you can also provide an
        // explanation about what went wrong.
        require(
            msg.sender == chairperson,
            "Only chairperson can give right to vote."
        );
        require(
            !voters[voter].voted,
            "The voter already voted."
        );
        require(voters[voter].weight == 0);
        voters[voter].weight = 1;
    }

    /// Delegate your vote to the voter `to`.
    function delegate(address to) public {
        // assigns reference
        Voter storage sender = voters[msg.sender];
        require(!sender.voted, "You already voted.");

        require(to != msg.sender, "Self-delegation is disallowed.");

        // Forward the delegation as long as
        // `to` also delegated.
        // In general, such loops are very dangerous,
        // because if they run too long, they might
        // need more gas than is available in a block.
        // In this case, the delegation will not be executed,
        // but in other situations, such loops might
        // cause a contract to get "stuck" completely.
        while (voters[to].delegate != address(0)) {
            to = voters[to].delegate;

            // We found a loop in the delegation, not allowed.
            require(to != msg.sender, "Found loop in delegation.");
        }

        // Since `sender` is a reference, this
        // modifies `voters[msg.sender].voted`
        sender.voted = true;
        sender.delegate = to;
        Voter storage delegate_ = voters[to];
        if (delegate_.voted) {
            // If the delegate already voted,
            // directly add to the number of votes
            proposals[delegate_.vote].voteCount += sender.weight;
        } else {
            // If the delegate did not vote yet,
            // add to her weight.
            delegate_.weight += sender.weight;
        }
    }

    /// Give your vote (including votes delegated to you)
    /// to proposal `proposals[proposal].name`.
    function vote(uint proposal) public {
        Voter storage sender = voters[msg.sender];
        require(sender.weight != 0, "Has no right to vote");
        require(!sender.voted, "Already voted.");
        sender.voted = true;
        sender.vote = proposal;

        // If `proposal` is out of the range of the array,
        // this will throw automatically and revert all
        // changes.
        proposals[proposal].voteCount += sender.weight;
    }

    /// @dev Computes the winning proposal taking all
    /// previous votes into account.
    function winningProposal() public view
            returns (uint winningProposal_)
    {
        uint winningVoteCount = 0;
        for (uint p = 0; p < proposals.length; p++) {
            if (proposals[p].voteCount > winningVoteCount) {
                winningVoteCount = proposals[p].voteCount;
                winningProposal_ = p;
            }
        }
    }

    // Calls winningProposal() function to get the index
    // of the winner contained in the proposals array and then
    // returns the name of the winner
    function winnerName() public view
            returns (bytes32 winnerName_)
    {
        winnerName_ = proposals[winningProposal()].name;
    }
}
</pre>
</details>

I first saw these messages:
>File mode specification error: (error Solidity Mode Configuration error. Requested solium flycheck integration but can’t find solium at: solium)
Error during redisplay: (jit-lock-function 1) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 1001) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 1501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")

I assumed that I was missing the solidity executable.
And found this command:
```
npm install -g solc
```
https://solidity.readthedocs.io/en/latest/installing-solidity.html#npm-node-js

It seems to have worked:
```
C:\Users\username>npm install -g solc
C:\Users\username\AppData\Roaming\npm\solcjs -> C:\Users\username\AppData\Roaming\npm\node_modules\solc\solcjs
+ solc@0.5.12
added 50 packages from 22 contributors in 4.702s
```

I added it's path to the Windows 10 PATH Environment variable:
```
C:\Users\username\AppData\Roaming\npm\node_modules\solc\
```

And Spacemacs is able to find it:
```elisp
(executable-find "solcjs")
```
outputs:
>"c:/Users/username/AppData/Roaming/npm/solcjs.cmd"

But the same error messages appeared:
```
File mode specification error: (error Solidity Mode Configuration error. Requested solium flycheck integration but can’t find solium at: solium)
Error during redisplay: (jit-lock-function 1) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 1001) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 1501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
```

I searched for `solium` in the `solidity.readthedocs.io` page, and found this page:
https://github.com/duaraghav8/Ethlint

where it says that it's been renamed:
>Ethlint (Formerly Solium) analyzes your Solidity code for style & security issues and fixes them.

And it should be installed with:
```
npm install -g ethlint
```

It seems to have been installed, but with a warning about a deprecated package:
```
C:\Users\username>npm install -g ethlint
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
C:\Users\username\AppData\Roaming\npm\solium -> C:\Users\username\AppData\Roaming\npm\node_modules\ethlint\bin\solium.js
npm WARN solium-plugin-security@0.1.1 requires a peer of solium@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\ethlint\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ ethlint@1.2.5
added 262 packages from 400 contributors in 19.487s
```

In Spacemacs, I closed and reopened the test `.sol` file
```
File mode specification error: (error Solidity Mode Configuration error. Requested solc flycheck integration but can’t find solc at: solc)
Error during redisplay: (jit-lock-function 1) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 1001) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 1501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
```

```
(executable-find "ethlint")
```
Returned: `nil`

I added:
```
C:\Users\username\AppData\Roaming\npm\node_modules\ethlint\bin\
```
to the Win 10 PATH environment variable

```elisp
(executable-find "ethlint")
```
still showed: `nil`
but:
```elisp
(executable-find "solium")
```
showed:
>"c:/Users/username/AppData/Roaming/npm/solium.cmd"

When the `.sol` file is opened, the messages buffer shows:
>File mode specification error: (error Solidity Mode Configuration error. Requested solc flycheck integration but can’t find solc at: solc)
Error during redisplay: (jit-lock-function 1) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 1001) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 1501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")

I found the "interface with linters" section:
https://github.com/ethereum/emacs-solidity#interface-with-linters

After adding:
```elisp
  (setq solidity-solc-path "c:/Users/username/AppData/Roaming/npm/solcjs")
  (setq solidity-solium-path "c:/Users/username/AppData/Roaming/npm/solium")
```
to the `dotspacemacs/user-init` section of `.spacemacs`.

Now the messages buffer shows:
>Error during redisplay: (jit-lock-function 1) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 1001) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Error during redisplay: (jit-lock-function 1501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
Suspicious state from syntax checker solidity-checker: Flycheck checker solidity-checker returned non-zero exit code 1, but its output contained no errors: Invalid option selected, must specify either --bin or --abi
>
>Try installing a more recent version of solidity-checker, and please open a bug report if the issue persists in the latest release.  Thanks!


While testing, I saw a popup at the top of the `.sol` file, that said:
>Couldn't find .soliumrc.json in the current directory.

solidity cant find soliumrc

But I'm not sure what I changed, because it doesn't appear anymore.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 07e2da04c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(solidity autohotkey auto-completion elixir emacs-lisp git ivy latex markdown multiple-cursors
          (org :variables org-agenda-files
               '("~/org/notes.org"))
          python spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by sei40kr** [comment]
@duianto 
> I'm seeing the same/similar error message as in the original PR: Solidity Layer #11907

Seems like `flycheck-solidity` throws an error when the executable doesn't exist.
https://github.com/ethereum/emacs-solidity/blob/master/solidity-flycheck.el#L127
-> I'll add `solidity-flycheck-solc-checker-active`, `solidity-flycheck-solium-checker-active` as layer options, instead of setting them to t in layer initialization.

> But the same error messages appeared:

NPM package `solc` installs `solcjs` executable, this is not fully compatible with `solc`.
https://solidity.readthedocs.io/en/v0.5.3/installing-solidity.html
I should have noted in the layer README.
-> I'll update the layer README.

> While testing, I saw a popup at the top of the .sol file, that said:
> > Couldn't find .soliumrc.json in the current directory.

This is a correct behavior of Ethlint.
You need to make sure `.soliumrc.json`. e.g. `solium --init`

**Comment by sei40kr** [comment]
@duianto I've just updated the PR. Please review.

**Comment by duianto** [comment]
Thank you for contributing to Spacemacs. It's safe to delete your branch.
The PRs changes have been cherry picked into the `develop` branch. https://github.com/syl20bnr/spacemacs/commit/df34916300356744e7febda8f91da177b7e09e3e

It seems to be working with both checkers, at least in Linux.

In Linux with these snaps installed:
```
sudo snap install solc
sudo snap install --edge solium
```
I'm just getting these errors:
```
    Error during redisplay: (jit-lock-function 1) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
    Error during redisplay: (jit-lock-function 501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
    Error during redisplay: (jit-lock-function 1001) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
    Error during redisplay: (jit-lock-function 1501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
```

I pretty sure that they are unrelated to the PR, because there has been similar error messages before from other packages.

Here's a merged PR in the `julia-repl` repository that seems to have been a regex error:
Silence "error during redisplay" warnings https://github.com/tpapp/julia-repl/pull/54
Maybe there's a similar error in the `solidity-mode` or `solidity-flycheck` packages.

In Windows
```
npm list -g --depth 0
```
shows that solc is installed:
`solc@0.5.12`

But I get these error messages:
>    File mode specification error: (error Solidity Mode Configuration error. Requested solc flycheck integration but can’t find solc at: C:/Users/username/AppData/Roaming/npm/node_modules/solc/)
    Error during redisplay: (jit-lock-function 1) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
    Error during redisplay: (jit-lock-function 501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
    Error during redisplay: (jit-lock-function 1001) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")
    Error during redisplay: (jit-lock-function 1501) signaled (error "No match 4 in highlight (4 font-lock-variable-name-face)")

I have a `solc` directory in that location:
>C:/Users/username/AppData/Roaming/npm/node_modules/solc/

but it doesn't seem to contain a `solc` executable.
>abi.js       
index.js     
LICENSE      
linker.js    
node_modules 
package.json 
README.md    
smtchecker.js
smtsolver.js 
solcjs       
soljson.js   
translate.js 
wrapper.js   

I downloaded: `solidity-windows.zip`
from: https://github.com/ethereum/solidity/releases

and it contains: `solc.exe`

I extracted the zip and added the path to it's directory to my OS PATH and to the `PATH=` entry in `.spacemacs.env`.

But it still seems to be looking for `solc` in:
>File mode specification error: (error Solidity Mode Configuration error. Requested solc flycheck integration but can’t find solc at: C:/Users/username/AppData/Roaming/npm/node_modules/solc/)

I even tried copying the `solidity-windows` directories files:
>soltest.exe
solc.exe
msvcp140_2.dll
msvcp140_1.dll
msvcp140.dll

into the `node_modules/solc directory` but there was no change.

It's working in Linux, so it's probably just a configuration issue in Windows.

**Comment by duianto** [comment]
I forgot to include your name in changelog.develop, Fixed: https://github.com/syl20bnr/spacemacs/commit/471feb2e00af799585b4c47d507643ebf4952ce1

**Comment by duianto** [comment]
I had:
```
  (setq solidity-solc-path "C:/Users/username/AppData/Roaming/npm/node_modules/solc/")
```
in my `dotspacemacs/user-init` section since the last time I tested the PR 😆 

With it commented out, there's no error about it not finding `solc`.

**Pull request closed without merging**
