### PR TITLE
holy-mode: fix #3876

### LINKED ISSUE #3876: spacemacs-core-evilified-state--modes
After pulling `develop` and updating packages this morning, I repeatedly get the following error.  Might be a typo (see the double dash between `state` and `modes`

```
Error (use-package): holy-mode :init: Symbol's value as variable is void: spacemacs-core-evilified-state--modes
```

I also notice that every buffer switch pops me into VIM mode instead of my default emacs mode.  Might be related.

I checked out commit 7c160e8 and the problem is gone, so whatever is causing it came later than 7c160e8.

### PR DESCRIPTION
**Pull request by kr5x**

### CODE REVIEW

**Comment by justbur** [comment]
Looks right to me @TheBB

**Comment by StreakyCobra** [comment]
It seems fine for me too. I tried it and it works here. I'll merge it as it's an annoying one for holy-mode users.

**Comment by StreakyCobra** [comment]
:+1: Thanks! Cherry-picked in develop. You can safely delete your branch.

**Comment by syl20bnr** [comment]
Thank you for the hotfix :purple_heart:

**Pull request closed without merging**
