### PR TITLE
fix spacemacs buffer for -nw and --batch

### PR DESCRIPTION
**Pull request by ksjogo**
The new spacemacs buffer functionality broke -nw and --batch, fixed this.

### CODE REVIEW

**Comment by siddharthist** [comment]
In what way are they broken?

**Comment by ksjogo** [comment]
-nw had/has problems with the graphics as the option is t as it is compiled into the binary, but the console will not display the image.
--batch was not working with the new progress bar as it will calculate negative values. I think another patch already fixed that, but this way it is still improving performance as there is no bar displayed anyway.

**Comment by siddharthist** [comment]
@ksjogo I think you accidentally checked in a commit labeled "proportional layer" BTW

**Comment by ksjogo** [comment]
Oh, yeah, it was tracking my develop branch.

**Pull request closed without merging**
