### PR TITLE
ess: fix company-mode

### PR DESCRIPTION
**Pull request by michelk**

### CODE REVIEW

**Comment by StreakyCobra** [comment]
Why is this change needed? Just curious…

**Comment by michelk** [comment]
I thought this would fix

    File mode specification error: (void-function company-mode-on)

**Comment by StreakyCobra** [comment]
I have the `company-mode-on` function… but it seems this function is not autoloaded, so indeed it's problematic if company is not loaded when this code is run.

So yes it should be fixed :+1: :smiley:

**Comment by syl20bnr** [comment]
Thank you!
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
