### PR TITLE
Improve idris support

### PR DESCRIPTION
**Pull request by bixuanzju**
+ add doc for various prefix
+ add `SPC m l` keybinding for extracting lemma
+ add basic auto-completion
+ rebind `SPC m c` to `idris-case-dwim`

### CODE REVIEW

**Comment by StreakyCobra** [comment]
Thanks for the PR. You may need to document the new keybinding in the layer's README (I haven't checked though). Also it would be nice to add the idris repl to `SPC a '` :-)

**Comment by bixuanzju** [comment]
@StreakyCobra I didn't add new keybindings, those are well-documented in the README already.

>Also it would be nice to add the idris repl to SPC a '

That's a good idea, will update later :)

**Comment by StreakyCobra** [comment]
> those are well-documented in the README already

:+1:

**Comment by bixuanzju** [comment]
@StreakyCobra Hi, can this be merged as I will have a Idris talk next week. Many thanks :)

**Comment by StreakyCobra** [comment]
I'll try to have a look, but no promise.

**Comment by bixuanzju** [comment]
@StreakyCobra Thank you very much

**Comment by StreakyCobra** [comment]
Thank you :+1: Cherry-picked into `develop`, you can safely delete your branch.

I squashed your commits in ec9c18b832306965c10cef83090320ad96b72d70, added back `SPC m s i` binding in 247d7cc5bd632f70f50113c02ef3acacf34430b7 as per [`CONVENTIONS.org`](https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org#send-code) and guarded the load of `company` to the use of the `auto-completion` layer in f2f23e6aa13bdcc37d2c27e880595a988fbd6086.

**Comment by bixuanzju** [comment]
Thank you very much!

**Comment by StreakyCobra** [comment]
:+1:

**Pull request closed without merging**
