### PR TITLE
LaTeX-mode -> latex-mode

### PR DESCRIPTION
**Pull request by ljli**
`LaTeX-mode` doesn't work for me, but `latex-mode` does.

### CODE REVIEW

**Comment by sdwolfz** [comment]
@ljli can you please give a small example where this fails so I can try it out locally before merging? I am not familiar with latex mode at all :crying_cat_face: ...

**Comment by ljli** [comment]
Sure, so the problem is just that the major-mode for latex is named `latex-mode` not `LaTeX-mode`. You can open any `.tex` file (can be empty) and inspect the variable `major-mode`. You can also see that the variable `flycheck-enabled-checkers` is nil, with the current code. If we give the correct mode name flycheck will be enabled and the variable will contain something like `'(tex-chktex)`.

**Comment by ljli** [comment]
Or maybe that is just me, I'm using the standard latex layer, though. Confusingly there seems to be a `LaTeX-mode` and `latex-mode` the former belonging to the AUCTeX package and the later being part of emacs. The layer seems to use AUCTeX, though, and both mode names are referenced in the layer code e.g. packages.el. Color me confused. All I can say is that flycheck works for me with this commit and does not without. So indeed it probably good if someones investigates further. This tex code should give an error like `Solo document found`.
```
\documentclass{article}
begin{document}
\end{document}
```

**Comment by smile13241324** [comment]
Tested this with the latest version on develop and the change seems to be not longer necessary. Whether I am selecting `latex-mode` or `LaTeX-mode` the result is always `LaTeX-mode` in my `.tex` file.

**Pull request closed without merging**
