### PR TITLE
helm should always be fuzzy by default

### PR DESCRIPTION
**Pull request by bling**

### CODE REVIEW

**Comment by bmag** [comment]
1. What's wrong with the current setting?

**Comment by bling** [comment]
nothing wrong -- it's just an incomplete list.  there's a couple sources that don't have fuzzy matching turned on.  this patch ensures that any source, old and new, will have fuzzy turned on.

**Comment by syl20bnr** [comment]
Thank you, nice trick :+1: 
Let's see how it goes.
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by bmag** [comment]
Apparently, this change causes #9631. @bling do you think you can investigate and fix it? seems that `helm--fuzzy-regexp-cache` can be empty during `SPC f f` when following the repro steps in the linked issue, causing an error in `helm-fuzzy-match`.

**Pull request closed without merging**
