### PR TITLE
Add evil-easymotion to the features in the README

### PR DESCRIPTION
**Pull request by robbyoconnor**
Just just adds the fact that evil-easymotion is integrated into the spacemacs-editing layer

### CODE REVIEW

**Comment by robbyoconnor** [comment]
CI failure isn't my fault.

**Comment by robbyoconnor** [comment]
@smile13241324

**Review by smile13241324 — APPROVED** [review]
Ups, forgot this, thanks for adding @robbyoconnor.

**Comment by robbyoconnor** [comment]
@smile13241324 when it's a FOSS community, we all got each other's back!

**Pull request merged**
