### PR TITLE
layers/+lang/perl5

### PR DESCRIPTION
**Pull request by abelew**
perl5 layer using Joseph Brenner's perlnow:
http://obsidianrook.com/perlnow/
along with some minor mmm-mode tweaks for mason, and
bioperl-mode with some minor changes because it has not been maintained very much since 2008.
https://github.com/bioperl/bioperl-live/tree/master/ide/bioperl-mode

This does still use template as it is used by perlnow and I did not wish to mess with that too much.

### CODE REVIEW

**Comment by syl20bnr** [comment]
This PR is busted 😄 
You should create a new branch "perl5" on top of develop branch and create a new pull request from it.

**Comment by abelew** [comment]
Greetings,
  I am sorry for the trouble.  I suspect it is due to my stupidity with
github, but I was reasonably certain that I did my merge on the develop
branch.  If I understand your statement correctly, you would prefer that
I do the following:

1.  Do my fork/clone
2.  Set the remote:
 > git remote add upstream https://github.com/syl20bnr/spacemacs.git
3.  Make sure I have the newest repository state:
 > git fetch upstream
4.  Switch to develop
 > git checkout upstream/develop
5.  Put my putative layer in place and make a new branch
 > git branch perl5
6.  Commit my changes
 > git commit -a && git push
7.  Submit a pull request via the website.

 yesno?

  Sorry again for your time,
 atb

**Comment by robbert-vdh** [comment]
You should rebase your branch onto `upstream/develop`. So assuming the changes you've made are on your perl5 branch but not on your local develop branch, you should run:
```sh
$ git rebase --onto upstream/develop develop perl5
```

Instead of develop you could also use first commit hash before you've made the Perl5 layer, and you might have to run the rebase `--interactive`ly to make sure you don't include commits you didn't mean to include.

**Comment by abelew** [comment]
One last reply before I waste your time with another defunct PR:

 I did the following in an attempt to make everything as clean as
possible, as I might have confused the branches locally.

1.  Reset --hard to the most recent tree
 > git reset c17722ba96048d3d88419a0d812b2214f3c05d30 --hard

2.  Checked that the branches were clean, and found that they were not
 > git branch

3.  Cleared out the repository and cloned it from a fresh fork.
 > rm -rf spacemacs && git clone ...

4.  Re-set up the upstream repository
 > git remote add upstream https://github.com/syl20bnr/spacemacs.git q

5.  Make certain I didn't miss anything
 > git fetch upstream && git checkout upstream develop

6.  Moved into my own branch
 > git checkout -b perl5

7.  Create my layer's directory
 > mkdir layers/+lang/perl5

8. Make 100% certain that I am sitting on upstream develop instead of
master:
 > git rebase --onto upstream/develop perl5

9. rsync my stuff and take a test run with emacs using cwd in case I
messed anything up...

> rsync -av \
~/.emacs.d/layers/+lang/perl5/ layers/+lang/perl5/

10.  add my stuff
 > git add layers/+lang/perl5

12. Do my commit and push to my forked repository
 > git commit -a && git push --set-upstream origin perl5

13. Reread the CONTRIBUTING.org file, the beginner's guide, and
CONVENTIONS.org.  Be sad that I am still not comfortable with magit.

  I presume that if I am correct, I will go to my fork on
https://github.com and click the 'Branch: develop', then 'Compare & pull
request', which takes me to the PR page, where I make sure 'base fork:'
is upstream and the branch is 'base: develop' and that my own branch is
'perl5'.

  yesno?

**Comment by TheBB** [comment]
Closing this since we have a more usable one at https://github.com/syl20bnr/spacemacs/pull/9046

**Pull request closed without merging**
