### PR TITLE
Add YAPF for Python buffer formatting

### PR DESCRIPTION
**Pull request by kennethlove**
[YAPF](https://github.com/google/yapf) is a handy tool from Google for automatically reformatting code to fit Python standards and style guides.

This PR loads the plugin and adds a `SPC mcf` keybinding to format the current Python buffer.

### CODE REVIEW

**Comment by syl20bnr** [comment]
You can remove the copy of the GPLv3 and modify the header of the `.el` file to specify the licence.
For the key binding you can use `SPC m r` which is reserved for refactoring bindings. The other alternative is to put it on `SPC m =` since `=` is for reformat in `Vim`. I would go for `SPC m =`.

**Comment by Funnnny** [comment]
I think you should have a configurable variable for automatic yapf on save.

**Comment by kennethlove** [comment]
I’m extremely new to elisp, so if you’d like to contribute that bit, I’d be extremely grateful.

On April 14, 2015 at 01:14:02 AM, Cong Nguyen (notifications@github.com) wrote:

I think you should have a configurable variable for automatic yapf on save.

**Comment by person808** [comment]
Adding a variable to config.el and adding a hook if the variable is true that runs yapf before save would work.

**Comment by person808** [comment]
In contrib/lang/python/config.el:

```elisp
(defvar yapf-format-on-save nil
  "If non-nil automatically format code when saving using yapf.")
```

And in the `:config` part of yapfs `use-package` declaration:

```elisp
(if yapf-format-on-save
   (add-hook 'python-mode-hook 'py-yapf-enable-on-save))
```

**Comment by louy2** [comment]
@person808 Why not sending a pull request to @kennethlove 's fork?

**Comment by syl20bnr** [comment]
Nice PR ! :+1: 
I renamed the layer variable from `yapf-format-on-save` to `python-enable-yapf-format-on-save` to be more consistent with the other variables. Related commit: a4e47cfc6b46891c49c680e3886d4ce87b7a6a1e

Thank you !
Cherry-picked into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
