### PR TITLE
Revert "fix: helm-display-header-line must be set when helm-echo-inpu…

### PR DESCRIPTION
**Pull request by lebensterben**
This reverts commit 290d873f916d5d0a030342ffb91a4ccb06bb9f26.

### CODE REVIEW

**Comment by lebensterben** [comment]
@kassick Unfortunately after your last PR helm is not working at all for me.

There's no completion candidates showing up.

**Comment by kassick** [comment]
I'll try to reproduce here with a vanilla spacemacs

Do you have any customizations to helm?
What helm version did you have installed ?

**Comment by kassick** [comment]
I could not reproduce with a fresh `spacemacs.el` . I've tried with `helm` and `helm-core` at `20230101.1922`  and at `20221120.1949`

I'm using emacs-29 (currently compiled at 92f753dc19010cf4075db5e6bcedcc5ac0fc2e41)

**Comment by lebensterben** [comment]
@kassick 
This issue goes away. Not sure what caused it in the first place.

**Pull request closed without merging**
