### PR TITLE
[ess] add keybinding for ess-quit

### PR DESCRIPTION
**Pull request by benswift**
Add a keybinding (alongside all the other `SPC m s` ones) to quit the current inferior process REPL.

### CODE REVIEW

**Comment by benswift** [comment]
Hmm, looking at the log for that particular action, it doesn't look like the issue is in the PR. Do you want me to re-run the actions?

**Comment by lebensterben** [comment]
It's too easy to hit `, q` by accident. The REPL very often has unsaved results which could be expensive to get. `, Q` is safer.

**Comment by benswift** [comment]
Yeah, ok, fair enough. R at least does give a `Save workspace image? [y/n/c]:` prompt (so that if you hit it accidentally you wouldn't necessarily lose the workspace) but I think that <kbd>,</kbd> <kbd>Q</kbd> is a good option anyway. I've updated the PR.

**Comment by lebensterben** [comment]
By default yes. But there are a few ways to disable this prompt.

**Comment by benswift** [comment]
Any idea why the CI checks are failing just for `macos-latest, 27.1, layers/+distribution/spacemacs-base`? To my eyes it looks like the issue is in the boilerplate rather than in my PR, but I could be wrong about that---I don't understand the details of how it all works.

**Comment by lebensterben** [comment]
I don't think it's caused by your PR.

**Comment by benswift** [comment]
Yep, ok. Well, my updated PR has the requested change from <kbd>,</kbd> <kbd>q</kbd> to <kbd></kbd>, <kbd>Q</kbd>. Does that look ok?

**Review by smile13241324 — APPROVED** [review]
Nice addition, will be merged soon. Yeah CI has some issues lately, I will post a comment on the maintainer chat about this.

**Pull request merged**
