### PR TITLE
add tab size to modeline

### PR DESCRIPTION
**Pull request by zilongshanren**
qq20150806-1 2x

Here is the screenshot of Sublime Text3, I think it could be the better defaults.

### CODE REVIEW

**Comment by syl20bnr** [comment]
Is this reliable ? Major modes tend to have their own variable to define the sized of the tabs, are they all correctly reflected in this variable ?

**Comment by zilongshanren** [comment]
@syl20bnr I have tried it in a python file.
The default settings are `python-indent` and `tab-width` both equal to 4.
When I change `python-indent` to 8 the tab-width is still 4...  failed...

**Comment by sooheon** [comment]
I don't agree with putting this in the modeline by default. While some languages like python or js have pretty variable indentation, other languages like lisps have pretty set indentation, and this wouldn't convey any useful information. I can see this being added to specific layers for languages which need it.

**Comment by syl20bnr** [comment]
Tabs are a pain point in Emacs :-(

**Comment by sooheon** [comment]
Maybe, but having something so visually apparent (you can look at your code) always take up space on the mode line...doesn't make sense to me. We also have indent-guide. Just my personal objection. It could be much better on a per-mode setting (for example only having it show up on js, python, etc. on an opt-in basis).

**Comment by felipe-barros** [comment]
Although I am of the unclutter philosophy, I believe people coming from other editors have grown to expect this information displayed somewhere at the bottom right corner.

Since, as mentioned, it's such a paint point of Emacs, even though the information is "visible" by looking at the code, a reference in the modeline would, I believe, smooth the transition for a lot of people.

If it could be toggled like the battery information, that would be awesome.

**Comment by TheBB** [comment]
*Indentation* is a pain point. It's mode-specific, which opens up a huge rabbit hole if we want to support something like that. Some languages, like elisp, don't even have well-defined indentation offsets.

What this PR does is that it shows the *tab width*, which has nothing whatsoever to do with indentation... it's the displayed width of literal tab characters. I'm not sure that deserves to take up space in the modeline—at least not by default.

What I would like is a more uniform interface to control offsets, which I kind of started [here](https://github.com/TheBB/spacemacs-layers/blob/master/evil-shift-width/config.el) for configuring `evil-shift-width` on a mode-specific-basis, but it's far from complete and I don't use every major mode myself, so…

**Pull request closed without merging**
