### PR TITLE
ensime folder added to gitignore

### PR DESCRIPTION
**Pull request by cyrillk**
Ensime-server for emacs generates a folder `~/.emacs.d/ensime/` which should be ignored.

### CODE REVIEW

**Comment by syl20bnr** [comment]
Is it possible to configure the folder and put it in `.cache` ?

**Comment by cyrillk** [comment]
May be.. I'll check.

**Comment by cyrillk** [comment]
It doesn't seem to be possible, unfortunately. It is hardcoded in "ensime-emacs" project. 
https://github.com/ensime/ensime-emacs/blob/master/ensime-startup.el#L182

**Comment by tuhdo** [comment]
If that is the case, you should report upstream if it can't be fixed. Meanwhile, we can merge this as a workaround with a comment reference to your reported issue waiting to be fixed, so one day someone may check and see if it is fixed, we can change it.

**Comment by syl20bnr** [comment]
As another work-around we can temporarily redefine the function.

**Comment by cyrillk** [comment]
I suggested a pull request to the ensime-emacs project https://github.com/ensime/ensime-emacs/pull/135 . It will be possible to configure the classpath folder as the change is merged and released.

Where to put `(setq user-emacs-ensime-directory ".cache/ensime")` in scala layer https://github.com/syl20bnr/spacemacs/tree/master/contrib/lang/scala ?

**Comment by cyrillk** [comment]
Ok. The new version of "emacs-ensime" is on melpa. So, I updated the scala layer with a configuration parameter.

**Pull request closed without merging**
