### PR TITLE
Update FAQ.org

### PR DESCRIPTION
**Pull request by bio**
Set link for OSX install section.

### CODE REVIEW

**Comment by TheBB** [comment]
Thanks, but this is an org file, please use [org link syntax](http://orgmode.org/manual/External-links.html#External-links).

**Comment by TheBB** [comment]
Something that works both in Emacs and after exporting would be nice. I note that this link is broken on spacemacs.org in its current state. :-(

**Comment by StreakyCobra** [comment]
Oh, I tested the link on github and it was working :persevere:

**Comment by bio** [comment]
Github uses `org-ruby` gem to convert org files to html, Org Export Dispatcher exports links `[[file:../README.md#os-x][README]]` in right format `<a href="../README.md#os-x">README</a>` but it's impossible to open external file from org buffer.

I tried to use org links `[[file:../README.md::#os-x][README]]`, `[[file:../README.md::#os-x][README]]` but with no luck, org-ruby doesn't understand it and removes '#os-x' part.

**Comment by StreakyCobra** [comment]
@JAremko Any advice on how we should handle such links?

**Comment by JAremko** [comment]
@StreakyCobra  If it was an org file then something like this should work `[[https://github.com/syl20bnr/spacemacs/blob/master/README.org#os-x][OS X]]`
But it's an md file :confused: 
I think we can modify the [https link  protocol handler](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bemacs/org/local/space-doc/space-doc.el#L92) and implement `spacemacs/view-md-file` - it will navigate to headlines.  This way Spacemacs will open mds like this `[[https://github.com/syl20bnr/spacemacs/blob/master/README.md#os-x][OS X]]` in a buffer.

But doing all this for a single md file...  Why can't we use org everywhere?

**Comment by nixmaniack** [comment]
> Why can't we use org everywhere?

I thought we're already using org everywhere, just convert it if it's not the case. :)

**Comment by JAremko** [comment]
@nixmaniack   It's somewhat complex document(with html stuff in it) https://github.com/syl20bnr/spacemacs/blob/develop/README.md I think we can use wider logo to center it or add some white spaces.  But it also have a ton of other stuff going on. We need the org mode god to do it properly :confused:

**Comment by d12frosted** [comment]
This section was moved to README file, so this PR is invalid by now. Sorry about that!

**Pull request closed without merging**
