### PR TITLE
add kill ring to savehist variables.

### PR DESCRIPTION
**Pull request by ralesi**
We weren't saving the kill-ring between sessions.

### CODE REVIEW

**Comment by tuhdo** [comment]
It was removed because of an issue on OSX that causes Emacs freezing. You should look at this PR as it links to the issue: https://github.com/syl20bnr/spacemacs/pull/1843

**Comment by ralesi** [comment]
@tuhdo, I have never had an issue with this on Windows. If this is an os specific issue, shouldn't we just have an unless check  for OSX since this seems to be a saner default?

**Comment by tuhdo** [comment]
If we do that, then there will be inconsistency and I'm not sure if @syl20bnr is ok with that. Large kill ring can also degrade startup time since it takes longer to load all the content. Probably it's doable by limiting history length to a very small size, by following this post's suggestion: http://emacs.stackexchange.com/a/12116. But then, I think it's safer to let users decide it themselves on this to avoid potential problems.

**Comment by ralesi** [comment]
I understand the position, but it seems there have been a lot of regressions in features because of isolated instances of issues in the code with the different platforms used.  We have also disabled persistent `undo-tree` support because of a bug some people saw as well.

**Comment by nwolfe** [comment]
:+1: for trying to make this work again. Who knows - it's been 6 months, maybe the OSX behavior is better now? :smile:

**Pull request closed without merging**
