### PR TITLE
evil-matchit has no way to load

### PR DESCRIPTION
**Pull request by ralesi**
Just add mapping to allow it to load.

### CODE REVIEW

**Comment by syl20bnr** [comment]
This is intended, evil-matchit is enabled in html and auctex only.

I still have to see the benefit of evil-matchit, this plugin is a mystery for me. It is also buggy in python mode where pressing `%` at the module scope hangs emacs, the user has to press `C-g`. I reported the bug long time ago but it has never been fixed.

**Comment by ralesi** [comment]
Should we even include it in the base Spacemacs layer then?

**Comment by syl20bnr** [comment]
That's a good question. Since I'm not convinced about the usefulness of it in some languages it could be removed. Obviously it was not activated and nobody complained about it.

**Comment by syl20bnr** [comment]
I'll let it in spacemacs for now. I will consider removing it later.
Thank you for the PR.

**Pull request closed without merging**
