### PR TITLE
Option for displaying the currently clocked in org-task in mode-line

### PR DESCRIPTION
**Pull request by luxbock**

### CODE REVIEW

**Comment by syl20bnr** [comment]
Once you fix the copy/paste typo, can you squash the commits into one commit ?

**Comment by luxbock** [comment]
Whops. Sorry about the typo! Did I get the rebase right this time?

**Comment by syl20bnr** [comment]
I don't use this so I cannot test :-(
Can you prodive me a repro step or mini tutorial to be able to display the clock ? If it is too much then ignore my request, it will only delay the merge since I have to grab a tutorial or something to be able to test the PR.

**Comment by bjarkevad** [comment]
I get `Symbol's function definition is void: spacemacs/mode-line-org-org-clock-current-task-toggle` when trying to use `SPC t m c` in an org-mode buffer. I like the idea though!

**Comment by luxbock** [comment]
Sorry, I should have checked this with a clean slate Spacemacs first. 

To try this, create a new TODO-item in an org-mode file and use `SPC m i` to clock-in the item. This should bring up the clock in the mode-line, provided that you have set `spacemacs-mode-line-org-clock-current-taskp` to `t`. 

The default face looks a bit out of place in the mode-line at the moment, as its using the `org-clock-overlay` face. I thought about using one of the mode-line faces inside `spacemacs/mode-line-prepare-left`, but this wouldn't automatically highlight a clocked item that has run over the estimate, so I thought it's better to let the user to choose between using a custom function for rendering the clock string, or to just customize the face themselves.

**Comment by syl20bnr** [comment]
Cool ! :+1: 
I will tweak the function and faces when I have time.

Cherry-picked in `develop`, you can safely delete your branch.

**Pull request closed without merging**
