### PR TITLE
Setup some ruby-tools bindings

### PR DESCRIPTION
**Pull request by chrismcg**
Not doing ruby-tools-clear-string as evil/vim has that covered

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Uhm...evil-surround can do this -- and is included in spacemacs...

**Comment by chrismcg** [comment]
Not everyone who uses spacemacs uses it in evil mode so that's why I put those in too. Thy symbol thing is something I use all the time.

**Comment by robbyoconnor** [comment]
Ah, I forgot about that! Carry on then :smile_cat:

**Comment by robbyoconnor** [comment]
In addition to the above comments, you should update the README to show the new keybindings you just added ;)

**Comment by chrismcg** [comment]
Ah, good call! I'll get that done at some point today. Thanks.

**Comment by chrismcg** [comment]
Docs updated. `SPC m x '` and `SPC m x "` are still useful even in evil mode as they'll change a symbol to a string. Pretty sure surround can't do that so there's still use for these in evil mode.

**Comment by robbyoconnor** [comment]
@chrismcg not sure but <kbd> SPC m</kbd> is namespaced to the current major-mode -- sooo

**Comment by robbyoconnor** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by syl20bnr** [comment]
Thank you !
Cherry-picked into `develop` branch, you can safely delete your branch.

Just for my information, can you provide some examples of the functionality ?

**Comment by robbyoconnor** [comment]
Change single quoted strings to double quoted and vice versa; and change a string to a symbol -- based on what I read. It's a good functionality to have...I been using evil-surround for that

**Comment by chrismcg** [comment]
@syl20bnr so if you have `:foo` then `SPC m x '` will turn it into `'foo'` and then `SPC m x :` would turn that back into `:foo`. If you use `SPC m x '` on `"foo"` then it just does what `cs"'` from surround does already but the symbol stuff is really handy day to day.

**Pull request closed without merging**
