### PR TITLE
Add key binding to toggle clojure-enlighten-mode.

### PR DESCRIPTION
**Pull request by mahinshaw**
Add a keybinding to the clojure layer to toggle `cider-enlighten-mode`.

### CODE REVIEW

**Comment by thenonameguy** [comment]
:+1:

**Comment by agzam** [comment]
what do you guys think if we also add a shortcut for `'cider-repl-handle-shortcut` (in non-evil mode is `,` in cider-repl) as well? Can be done easily by adding `",," 'cider-repl-handle-shortcut` at: line:266 in packages.el? Then cider-repl's native menu would be available by pressing comma twice?

**Comment by mahinshaw** [comment]
@agzam I like it.  I need to rebase this PR with what is currently on develop.  The cider-repl-mode bindings got merged with all the other mode bindings, and `cider-repl-handle-shortcut` is only relevant to cider mode.

**Comment by mahinshaw** [comment]
Rebased patch so that changes in 63e1db9 are incorporated.  Added @agzam's suggestion, as well as `SPC m s d` to run `cider-repl-clear-buffer`, which was lost in the aforementioned commit (only for `cider-repl-mode`).

**Comment by agzam** [comment]
What is the status of this PR? Will it ever be merged? Can we also expose clojure-mode bindings for "Cider scratch" (Clojure Interaction) mode? It requires an extremely small change, I think it totally can be part of this PR.

**Comment by mahinshaw** [comment]
@agzam I am game for that. Any opinion on the binding? Maybe ~SPC m S~?

**Comment by agzam** [comment]
@mahinshaw this is what I mean, 
here: https://github.com/syl20bnr/spacemacs/blob/dfad604faaa542080d252902babfdd392e354eea/layers/%2Blang/clojure/packages.el#L89

we just need to add `cider-clojure-interaction-mode` then major mode bindings would work in cider-scratch window

**Comment by mahinshaw** [comment]
@agzam Good call. Thanks

**Comment by mahinshaw** [comment]
Squashed into one commit

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Pull request closed without merging**
