### PR TITLE
Adjust which-key config to match commands

### PR DESCRIPTION
**Pull request by justbur**
Instead of key sequences, because the user might change the bindings.

See https://github.com/justbur/emacs-which-key/issues/51

### CODE REVIEW

**Comment by justbur** [comment]
Note which-key will need to be updated to the most recent version for this to work. The relevant version is not quite on MELPA yet, but it should be there soon.

**Comment by justbur** [comment]
Added a new paging feature to which-key, which now uses `C-h` by default replacing `describe-prefix-bindings`. I updated the config to make use of this feature, which is kind of awesome if I don't say so myself.

**Comment by syl20bnr** [comment]
Amazing ! You guys rocks :+1: 
Well done for the paging, which-key is THE new package for Emacs :100: 

Cherry-picked into `develop` branch, you can safely delete your branch.

**Comment by justbur** [comment]
Thanks! Glad you like it

**Comment by syl20bnr** [comment]
C-h has some bad side effect though :-( we have to find another one I
think.

Le lundi 27 juillet 2015, Justin Burkett <notifications@github.com> a
écrit :

> Thanks! Glad you like it
> On Mon, Jul 27, 2015 at 12:00 AM Sylvain Benner <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Closed #2393 <https://github.com/syl20bnr/spacemacs/pull/2393>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/syl20bnr/spacemacs/pull/2393#event-365708496>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/pull/2393#issuecomment-125268755>.
>


-- 
-syl20bnr-

**Comment by justbur** [comment]
Like what exactly?

**Comment by justbur** [comment]
Please turn it off if you are experiencing problems. I put the variable in
there that needs to be changed.

C-h is special, but any key sequence can be bound to
which-key-show-next-page.

**Comment by syl20bnr** [comment]
Sorry, the issue is here: https://github.com/syl20bnr/spacemacs/issues/2429
Sure I can bind it to another key but it is not obvious which one to take, I liked C-h idea but it seems to be pretty handy (invoke a helm-descbind buffer).

**Comment by syl20bnr** [comment]
I realize that the shadowing was intended and you wrote about it, my bad :-)

**Comment by justbur** [comment]
No worries. I just want the most natural setup. To me having which key take
the role of the old C-h works well but I understand if it's confusing to
people and maybe deciding on a different key binding is the right way to
go.

**Pull request closed without merging**
