### PR TITLE
 Add slim-mode to ruby layer

### PR DESCRIPTION
**Pull request by robbyoconnor**
This is a more robust version of #1627.

### CODE REVIEW

**Comment by syl20bnr** [comment]
Is `slim-mode` intended to replaced `haml-mode` ?

**Comment by robbyoconnor** [comment]
It could -- it could also add to it...for example some projects use slim whereas others use erb or haml...so I can conditionally enable and disable it...

**Comment by robbyoconnor** [comment]
@syl20bnr  what is the status of this?

**Comment by syl20bnr** [comment]
Thank you ! :+1: 
I decided to put RoR in its own layer in `!frameworks` folder, I also moved Django there.

Cherry-picked in `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
