### PR TITLE
elixir: fix smartparens hook

### LINKED ISSUE #6660: REGRESSION: "elixir: fix smartparens setup" broke smartparens for elixir
#### Description :octocat:
Elixir smartparens broken by commit ironically titled ["elixir: fix smartparens setup"](https://github.com/syl20bnr/spacemacs/commit/5af1e453c6725241681dcd4130b65d37c6257552).

If you eval smartparens.el, it will get fixed, which makes me think that the
hook being added is not firing on startup. 

#### Reproduction guide :beetle:
- Start Emacs
- Open an elixir file
- Type `defmodule Foo do` and press RET

*Observed behaviour:* :eyes: :broken_heart:
- `end` is not inserted automatically

*Expected behaviour:* :heart: :smile:
- `end` is inserted automatically

#### System Info :computer:
- OS: darwin
- Emacs: 25.0.95.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 1b5bc13)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(better-defaults spacemacs-layouts helm emacs-lisp markdown
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 (auto-completion :variables auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup nil)
                 erlang elixir git dash html clojure
                 (org :variables org-enable-github-support t)
                 colors osx github javascript react deft floobits ruby
                 (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
                 spell-checking ranger version-control rcirc tmux yaml docker elm evil-little-word auto-correct frame-geometry cleverparens-lispy)
```

### PR DESCRIPTION
**Pull request by aaronjensen**
Fixes #6660

Thanks to @bmag for suggested fix

### CODE REVIEW

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

**Comment by aaronjensen** [comment]
@TheBB Thanks! btw, is there a reason you guys can't use "Merge and Squash" github feature? It ends up looking the same on develop but it marks the pull request as merged.

**Comment by TheBB** [comment]
I don't think it's the same? We like having our git history linear when possible. The merge button produces merge commits.

**Comment by aaronjensen** [comment]
@TheBB squash and merge does not create merge commits from what I have seen. Give it a shot in the next merge. It does pretty much exactly what you want. It also means people don't need to squash their own commits, so you don't lose history in the pull request but don't introduce it in the main line.

**Pull request closed without merging**
