### PR TITLE
adding magic-latex-buffer package to latex layer

### PR DESCRIPTION
**Pull request by benquebec**
the package allows some customization of font locking particularly useful with symbols

### CODE REVIEW

**Comment by StreakyCobra** [comment]
No luck again :-) When you created your `magic` branch, you did it from the `aucreftex` one and not from `develop`, so `magic` have herited all `aucreftex` commits. So if you look at this PR, you have both the changes of this one, plus the changes of #4153. At they are both `latex` related and concerning the same file, we will keep this commit and review both changes at the same time :relaxed:. I'll close the other PR then :wink:

**Comment by benquebec** [comment]
still learning ;)

**Comment by yilihong** [comment]
any updates on this one?

**Comment by benquebec** [comment]
I ended up installing the package on my .spacemacs 
 Worked fine for my use.

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

I ended up just picking the magic-latex-buffer commit. Unfortunately this PR is too old for me to resolve any conflicts originating from a major overhaul of keybindings. Therefore please resubmit such changes if you like.

From experience such a package will be controversial so I made it optional and not default. I also turned off some of the more egregious effects by default (alignment and inline images).

**Pull request closed without merging**
