### PR TITLE
Tip regarding option on international keyboards

### PR DESCRIPTION
**Pull request by marcopaga**
This is a follow up for: https://github.com/syl20bnr/spacemacs/issues/5188

More config information regarding option on international keyboards.

### CODE REVIEW

**Comment by syl20bnr** [comment]
:+1:

**Comment by d12frosted** [comment]
Another good solution is using `cmd` as `meta`:

```
(setq mac-command-modifier 'meta
      mac-option-modifier  'none)
```

The only caveat is when you use GNU Emacs (25?) and want to `cmd-h`. You could think that `(bind-key "M-h" 'ns-do-hide-emacs)` is enough to solve this problem, but some modes define `M-h`. That's why I use following function:

```
(defun d12/setup-M-h ()
  "Setup M-h key binding on OS X in GUI."
  (when (and (spacemacs/system-is-mac)
             (display-graphic-p))
    (bind-key "M-h" 'ns-do-hide-emacs)
    (-map (lambda (mode)
            (add-hook (intern (concat (symbol-name mode) "-hook"))
                      `(lambda ()
                         (define-key
                           (symbol-value (intern ,(concat (symbol-name mode) "-map")))
                           (kbd "M-h")
                           nil))))
          '(org-mode
            company-quickhelp-mode))))
```

This is far from ideal, but I believe that some people could find it useful.

**Comment by TheBB** [comment]
Thank you! Cherry-picked in develop. You can safely delete your branch.

We break long lines around these here parts so I went ahead and did that for you in https://github.com/syl20bnr/spacemacs/commit/9ccad9c2c1da21301fffc126a5beaf785de9a0d7. Also formatted the rest of the file to match Spacemacs conventions.

**Comment by Akii** [comment]
As an additional note: You need the emacs-mac-port, not the default emacs installed by homebrew for this setting to work.

To check if the setting is available:

```
SPC h d v mac-right
```

should output

```
mac-right-option-modifier is a variable defined in ‘C source code’.
Its value is nil
Original value was left

Documentation:
Modifier key assumed when the Mac right option key is pressed.
The value is of the form either SYMBOL or ‘(:ordinary SYMBOL :function
SYMBOL :mouse SYMBOL)’.  The latter allows us to specify different
behaviors among ordinary keys, function keys, and mouse operations.
```

**Pull request closed without merging**
