### PR TITLE
Text line commands

### PR DESCRIPTION
**Pull request by oppenlander**
Added "sort" and "uniquify" commands

### CODE REVIEW

**Comment by syl20bnr** [comment]
Funny I had to use these functions a few days ago, but I used stock evil/Vim to do it with `:sort u`. Having these commands available would have been handy as well :-)
As a side note Evil is really impressive, lots of ex commands are implemented, I was surprised to be able to use these commands: http://vim.wikia.com/wiki/Delete_all_lines_containing_a_pattern

**Comment by oppenlander** [comment]
Ah. I haven't delved into the many of the evil/vim ex commands.  
`:sort` is probably something I'll be using, even if this gets merged.

**Comment by jb55** [comment]
Yeah also `:!` which passes your buffer to arbitrary commands. eg: visual mode select something, then `:!sort | unic -c`

Usually most vi emulators forget about this stuff but it seems to work great!

**Comment by syl20bnr** [comment]
Thank you !
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
