### PR TITLE
Remove special theme handling

### PR DESCRIPTION
**Pull request by TheBB**
I'm not sure about this. Apparently the fork we use has some modifications. The modeline looks worse after this PR at least. Then again, I don't think it's a good idea to keep it around.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
NOOO!!!!!!!! I use solarized0-dark myself :(

**Comment by robbyoconnor** [comment]
***NOT*** in support of this move, NO!

**Comment by TheBB** [comment]
Solarized still works, obviously. You'll just get it from MELPA instead of the Spacemacs repository.

**Comment by robbyoconnor** [comment]
So why not do this...add **SOME** middle-ground  other than "let's remove it completely"

**Comment by person808** [comment]
@robbyoconnor Whats wrong with installing solarized from MELPA? Thats what happens with all other themes except spacemacs-theme.

**Comment by TheBB** [comment]
I don't understand what you're saying. What middle ground are you envisioning? This PR makes solarized work like every other theme.

**Comment by robbyoconnor** [comment]
I think solarized is included in the `themes-megapack`... so I think nevermind :)

**Comment by TheBB** [comment]
I'm just saying, it doesn't matter if it's part of a layer or not. *All* themes are automatically downloaded from MELPA. When you declare a theme, Spacemacs finds the right package and downloads it transparently, regardless of layers or additional packages.

**Comment by robbyoconnor** [comment]
Ah, that's a behavior I didn't know about.

**Comment by TheBB** [comment]
Still though, there are apparently some differences between our solarized and upstream solarized, so I'll leave this up to @syl20bnr.

**Comment by robbyoconnor** [comment]
I noticed you just closed #3241 as "won't fix" -- does this leave this PR in a state of weird limbo?

**Comment by nashamri** [comment]
@person808 even `spacemacs-theme` is installed from MELPA

**Comment by TheBB** [comment]
No, as far as I'm concerned this should be done regardless. But like I said, @syl20bnr will know.

**Comment by robbyoconnor** [comment]
Ultimately, I don't have the decision-making power -- I can only voice my concerns -- which in this case is the unknown

**Comment by TheBB** [comment]
For that matter, @nashamri @syl20bnr is there a reason why [this](https://github.com/syl20bnr/spacemacs/blob/master/core/core-themes-support.el#L174-L182) is still there? Why does the Spacemacs theme need special code?

**Comment by TheBB** [comment]
I tested and doesn't seem like it's needed so I deleted that, too.

**Comment by nashamri** [comment]
@TheBB :+1: yeah there's probably no need for that too.

**Comment by syl20bnr** [comment]
Nice cleanup, I'm more comfortable with solarized being now the official MELPA one.
Thank you :+1: 
Cherry-picked into develop, you can safely delete your branch.

**Pull request closed without merging**
