### PR TITLE
init: Get more info from debug-init

### PR DESCRIPTION
**Pull request by justbur**
1. Make sure debug-on-error stays on
2. Force verbose loading
3. Detect long requires and loads

I think this will be useful to detect more problems in startup.

### CODE REVIEW

**Comment by syl20bnr** [comment]
Do we really need this ? There are instrumentalisation tooling in Emacs already, we should check them and see how we can integrate them.

**Comment by justbur** [comment]
Maybe not the timing stuff but the verbose loading is specific to Spacemacs
and just convenient to be triggered by debug-init imo. The fact that
deferred loads don't get caught by debug-init has always annoyed me. The
default is to turn debug-on-error off after the init file has "loaded".

**Comment by justbur** [comment]
I'm sure this can be made better. I just thought it would be nice to have a command line switch to turn on all spacemacs logging and using debug-init seemed natural.

**Comment by justbur** [comment]
@syl20bnr I looked around some and most of what I found is focused on adding timing overlays to a single .emacs file. 

For fun, I start the profiler in the current version of the code and display the result after an idle time-out. I also dumped all of the load times in a new buffer, so they don't get mixed up in the messages buffer.

Definitely a work in progress for now..

**Comment by justbur** [comment]
Cleaned up and put in new file. Also added command line switches to turn on timed requires and the profiler

**Comment by syl20bnr** [comment]
`dotspacemacs-verbose-loading-override` is very confusing and to "hackish" for my taste, there must be a better way to do this without it, for instance you already have the info you need with `init-file-debug` variable.

**Comment by justbur** [comment]
Ok, no problem. It's removed now

**Comment by syl20bnr** [comment]
Thank you for the PR :+1: 
As you probably saw it I removed `dotspacemacs-verbose-loading` since there was overlap and it is more natural to activate it at the command line level.

**Comment by justbur** [comment]
Good idea, I agree

**Pull request closed without merging**
