### PR TITLE
Fixes #5190 - core: Add :packages keyword for layers

### LINKED ISSUE #5190: Proposal to add :use keyword to layer declaration
In the spirit of being explicit about what you would like to use, rather than excluding what you don't want, a `:use` keyword for the `dotspacemacs-configuration-layers` list would be useful.

Specifically for adding on to `spacemacs-base`, currently the layers like `spacemacs-ui` `spacemacs-evil` etc. still come whole hog, and you end up adding most of `spacemacs` default back if you want something in the layers. This would allow you to be more selective, more easily.

```
'(better-defaults
  (spacemacs-ui :use '(info+ window-numbering))
  clojure)
```

### PR DESCRIPTION
**Pull request by justbur**
This implements my proposal in #5190.

To restrict layer to only use pkg1 and pkg2 use
(layer
  :packages (pkg1 pkg2))

To load all packages in a layer except pkg1 use
(layer
  :packages (not pkg1))

### CODE REVIEW

**Comment by justbur** [comment]
This is breaking the help facility for some reason

**Comment by syl20bnr** [comment]
Which help facility does it break ?
Is this PR fixable ?

**Comment by justbur** [comment]
I was getting nil packages in ivy-spacemacs-help. You can use it. I just
didn't want to spend the time digging into what was wrong.

**Comment by syl20bnr** [comment]
Ok no problem, I'll look at it, thank you.

**Comment by ralesi** [comment]
@syl20bnr , @justbur.  I can confirm the presence of nil layers in the `helm-spacemacs-help` and `ivy-spacemacs-help` variants; however this is found in the current develop branch, and is not tied to this PR.  I applied the changes in this PR to the current head and it seems to be working fine.   I did find a bug in `ivy-spacemacs-help`, but nothing pertaining to the `:packages` property implementation.

**Pull request closed without merging**
