### PR TITLE
New org-mode leader keys for narrowing

### PR DESCRIPTION
**Pull request by mattly**
Really though, I'm finding that I don't use any of the built-in major-mode leader keys in org, but lots of other org functions. Perhaps some of the functionality (clocking, scheduling, todo management, etc) should be put under subleaders?

### CODE REVIEW

**Comment by syl20bnr** [comment]
Spacemacs lacks a good key binding design for `org`, this is something I want to work on soon.

**Comment by syl20bnr** [comment]
To be clear I will merge this PR but we will have to work on a better design for org. I confess that I merged the PRs for org as they went so the result cannot be consistent. I'm not an advanced org user but I plan to dig into it.

**Comment by syl20bnr** [comment]
Thank you !
Cherry-picked into `develop`, you can safely delete your branch.

**Comment by mattly** [comment]
Thanks! I'm still learning org-mode myself, but would be happy to open a ticket about org-mode keybinding design to get a discussion going.

**Pull request closed without merging**
