### PR TITLE
Refine typography layer

### PR DESCRIPTION
**Pull request by lunaryorn**
- Move vi tilde fringe from `SPC t ~` to `SPC T ~` to free the former.
- Move tildify toggle from `SPC t T d` to `SPC t ~`.  
- Move tildify region from `SPC x T T` to `SPC x ~`
- Use `~` as mode line indicator for tildify mode
- Move typography toggle from `SPC t T y` to `SPC t Y`
- Use circled capital Y `Ⓨ` as mode line indicator for typo mode

See https://github.com/syl20bnr/spacemacs/pull/3554#issuecomment-156491394

### CODE REVIEW

**Comment by TheBB** [comment]
Thank you! Cherry-picked in develop. You can safely delete your branch.

I changed the non-unicode diminish for typo-mode as well: https://github.com/syl20bnr/spacemacs/commit/fdc221a3830c5c500baf957a387c4e2abe3a74bd

**Comment by lunaryorn** [comment]
Did you also update the docs? I think I forgot them in this PR. I wanted to update it but can I still now that it's merged?

**Comment by TheBB** [comment]
Oh *those* docs. No, I'll do them now.

**Comment by lunaryorn** [comment]
Sorry, my bad 😥

**Comment by TheBB** [comment]
No problem :+1: https://github.com/syl20bnr/spacemacs/commit/acce2e84bd8272dbcc23255a5e0c548b13093bd1

**Comment by syl20bnr** [comment]
@lunaryorn @TheBB Since `SPC t T` is free, I found it more natural to move `SPC t Y` to `SPC t T`, see commit https://github.com/syl20bnr/spacemacs/commit/28097d8

**Comment by lunaryorn** [comment]
@syl20bnr Well, I had [a reason for taking Y](https://github.com/syl20bnr/spacemacs/pull/3554#issuecomment-156840172) :relaxed:: The circled capital T is already taken by Tagedit Mode.

**Pull request closed without merging**
