### PR TITLE
evilify: Add dotspacemacs-evilify-blacklist

### PR DESCRIPTION
**Pull request by justbur**
This is a list of modes that are prevented from entering evilified state
by default.

One possible solution for #3022

### CODE REVIEW

**Comment by justbur** [comment]
@mbertheau try this and see if it works for you

**Comment by mbertheau** [comment]
@justbur that works as advertised.

**Comment by person808** [comment]
This would need tests.

**Comment by mbertheau** [comment]
I tried `dotspacemacs-evilify-blacklist` for a while and I found it really irritating that <kbd>SPC</kbd> doesn't work, which is the universal way out (for example to another buffer). I realize that that probably means that in a final solution we could still deviate from on-screen docs for <kbd>SPC</kbd>.

Will try `dotspacemacs-dont-evilify` now.

**Comment by mbertheau** [comment]
<kbd>SPC</kbd> doesn't work with `dont-evilify` either, but my understanding improved greatly :)

I'm running with light evilification now https://github.com/mbertheau/spacemacs/commit/11e9c5675a5d931559cf7b550cecf936917b2f9e.

**Comment by justbur** [comment]
Answered the last part about `SPC` [here](https://github.com/syl20bnr/spacemacs/issues/3022#issuecomment-141453965)

**Comment by justbur** [comment]
Not needed for magit after #3578

**Pull request closed without merging**
