### PR TITLE
[ietf layer] Add RFC files to the auto-mode-alist to use irfc-mode

### PR DESCRIPTION
**Pull request by robbyoconnor**
the pattern for RFC files from the ietf wasn't setting up the irfc-mode, set it up so it did.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@smile13241324

**Comment by robbyoconnor** [comment]
@JAremko seems like the Validate PR job is issuing a false negative in this case..

**Comment by JAremko** [comment]
@robbyoconnor 

https://api.github.com/repos/syl20bnr/spacemacs/pulls/12170
``` json
  "base": {
    "label": "syl20bnr:master",
    "ref": "master",
    "sha": "c7a103a772d808101d7635ec10f292ab9202d9ee",
    "user": {
      "login": "syl20bnr",
      "id": 1243537,
      "node_id": "MDQ6VXNlcjEyNDM1Mzc=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1243537?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/syl20bnr",
      "html_url": "https://github.com/syl20bnr",
      "followers_url": "https://api.github.com/users/syl20bnr/followers",
      "following_url": "https://api.github.com/users/syl20bnr/following{/other_user}",
      "gists_url": "https://api.github.com/users/syl20bnr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/syl20bnr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/syl20bnr/subscriptions",
      "organizations_url": "https://api.github.com/users/syl20bnr/orgs",
      "repos_url": "https://api.github.com/users/syl20bnr/repos",
      "events_url": "https://api.github.com/users/syl20bnr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/syl20bnr/received_events",
      "type": "User",
      "site_admin": false
    }
```

Have no idea :thinking:

**Comment by robbyoconnor** [comment]
Yeah something is weird with Circle CI

**Comment by smile13241324** [comment]
Thank you for contributing to Spacemacs! :+1:
The PR has been cherry-picked into develop, you can safely delete your branch.

**Pull request closed without merging**
