### PR TITLE
Make pylookup use helm for completion

### PR DESCRIPTION
**Pull request by darkfeline**
Make pylookup use helm for completion

### CODE REVIEW

**Comment by TheBB** [comment]
Is it possible to just set it to the value of `completing-read-function` to have it work with ivy as well?

**Comment by darkfeline** [comment]
`pylookup-completing-read` is `ido-completing-read` for me.

In pylookup:

~~~ emacs-lisp
(defvar pylookup-completing-read 
  (if (null ido-mode) 'completing-read 'ido-completing-read)
  "Ido support with convenience")
~~~

I guess the right way would be to set it to `completing-read`?

**Comment by darkfeline** [comment]
While we're at it, might as well fix this: https://github.com/syl20bnr/spacemacs/pull/5328

**Comment by TheBB** [comment]
Yes, I think so. Thanks! :+1:

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

I took the liberty of changing the commit message since it's no longer about helm.

**Pull request closed without merging**
