### PR TITLE
Add Fortran layer using the fortpy package

### PR DESCRIPTION
**Pull request by halvorlu**
This layer provides auto-completion and intellisense for Fortran 90 and 2003 using the fortpy package.

### CODE REVIEW

**Comment by halvorlu** [comment]
Any plans on merging this?

**Comment by d12frosted** [comment]
Calling upon the might and wisdom of @syl20bnr.

P. S. Sorry for silence 😶

**Comment by TheBB** [comment]
The main problem with this is that the auto-completion is only defined for ac, not company, and everything else in Spacemacs uses company. It appears there's no package currently for wrapping an ac source as a company backend, but it looks like a very solvable problem, so I'll give it a shot.

**Comment by halvorlu** [comment]
Closing this since I don't have a need for this Fortran layer anymore.

**Pull request closed without merging**
