### PR TITLE
Introduces pkgbuild-mode

### PR DESCRIPTION
**Pull request by Nimamoh**
Introduction of pkgbuild-mode.

### CODE REVIEW

**Comment by real-or-random** [comment]
I'd love to see this merged. Anything left to do here?

**Comment by duianto** [comment]
The Spacemacs `major-mode` layer:
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/major-modes/README.org

includes the `pkgbuild-mode` package: https://github.com/juergenhoetzel/pkgbuild-mode

It has more and different key bindings than this PR suggests:

`major-modes` layer:

Key binding | Description
-- | --
SPC m b | Run makepkg
SPC m r | Increase the pkgrel number
SPC m u | Browse URL
SPC m m | Update package sums
SPC m e | Build ETAGS file
SPC m a | Make a source tarball

source: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/major-modes/README.org#arch-linux-pkgbuilds

This PR:

Key Binding | Description
-- | --
SPC m b | Builds using makepkg
SPC m s | Udpate sums line
SPC m t | Creates a tarball of the package including all the sources
SPC m i | Increases the pkgrel release tag

What should the key bindings be in this new layer?

**Comment by duianto** [comment]
Here are the changes that were implemented with the previous PR, it also included lazy loading of `PKGBUILD` files.
https://github.com/syl20bnr/spacemacs/pull/8322/files

**Comment by real-or-random** [comment]
> The Spacemacs `major-mode` layer:
> https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/major-modes/README.org
> 
> includes the `pkgbuild-mode` package: https://github.com/juergenhoetzel/pkgbuild-mode

Oh I had seen the PR which added the major-modes layer but I assumed it has been removed because it could not find it in the current tree. But the reason is that it's not merged into the master  branch yet.

**Comment by smile13241324** [comment]
The requested feature has already been merged into develop.

**Pull request closed without merging**
