### PR TITLE
Fix the badge –- the github CDN cache is stale in the "How to support spacemacs" section

### PR DESCRIPTION
**Pull request by robbyoconnor**
The github CDN needs to refresh its cache but until it does, this fixes it.

### CODE REVIEW

**Comment by syl20bnr** [comment]
How long is it for the CDN cache to be updated ?
I don't like the idea to tell people to reference the specific version of a commit since they won't be able to get updates.
I'm OK to wait for the cache invalidation and keep the real link.

**Comment by syl20bnr** [comment]
Or at last we should use a link to the master version, in any case not a specific commit.

**Comment by robbyoconnor** [comment]
I'm not sure actually, but for now it's not in `master`  -- we fixed it in the README -- a few lines down from where I changed.

**Comment by syl20bnr** [comment]
OK, my mistake, I was really aware of rawgit, I should have read the FAQ sooner. :-)
Using the commit or whatever has no impact since the file will be stored forever for this specific path which is OK in the end, even if we update it then old sites with old address will still have the old file served from the CDN.

**Comment by StreakyCobra** [comment]
Thank you :+1: Cherry-picked into develop, you can safely delete your branch.

I removed the superfluous empty line (42d1135438fb5ae1ff25978d4b67a7b2bf7266fb)

**Pull request closed without merging**
