### PR TITLE
Modularize and add quickhelp button

### PR DESCRIPTION
**Pull request by tuhdo**
Split the current hardcoded release note display functions into smaller
reusable functions. Then reuse it for creating quickhelp button.

### CODE REVIEW

**Comment by tuhdo** [comment]
Here is a demo:

quickhelp-demo

As you see, when `Release Notes` content is visible, pressing `[?]`  switches to its content immediately and vice versa. If the same button is pressed in succession, simply hide the content.

**Comment by tuhdo** [comment]
@syl20bnr hope that you haven't wokred on this, so we don't duplicate each other.

**Comment by syl20bnr** [comment]
Nope no conflict here :-) And this is awesome, can't wait to merge it tonight :+1:

**Comment by tuhdo** [comment]
In the quickhelp section, I will add two button: one for evil tutor and want for emacs tutor.

**Comment by tuhdo** [comment]
@syl20bnr I added Evil and Emacs tutorial buttons to quickhelp.

**Comment by tuhdo** [comment]
@syl20bnr In the future, I will write a Spacemacs tutorial on how to use basic features (i.e. file navigation with `SPC f` group, buffer management with `SPC b`, search with `SPC s`, how to use `guide-key` and `helm-descbinds` etc..) to be comfortable with Spacemacs in a few hours playing.

But that will be in another PR, and another button will be added under quick help.

**Comment by syl20bnr** [comment]
Awesome PR ! :heart: 
Thank you !!

I had to remove a `recenter` that was scrolling the buffer and hiding the spacemacs logo.

Cherry-picked into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
