### PR TITLE
Correct s-v keybinding with `yank`

### PR DESCRIPTION
**Pull request by sooheon**
Correction to https://github.com/syl20bnr/spacemacs/pull/1972#issuecomment-111796588. Sorry for the mistake!

### CODE REVIEW

**Comment by andyque** [comment]
@sooheon  why close this PR? I think currently the "s-v" on OSX is wrong.

**Comment by sooheon** [comment]
I'm a magit newb, I think deleting my branch in magit accidentally closed the PR ;;

**Comment by andyque** [comment]
@syl20bnr  This PR should be merged. The current behavior of "s-v" on MacOS X is wrong.

**Comment by syl20bnr** [comment]
Merged ! :-)

Thank you !
Cherry-picked into `develop` branch, you can safely delete your branch.

**Pull request closed without merging**
