### PR TITLE
Fix issues in VIMUSERS.org.

### PR DESCRIPTION
**Pull request by person808**
1. Fix broken links.
2. Make spacing consistent with other documentation.
3. Use a better function example. The previous one did not work for some
common use cases.

### CODE REVIEW

**Comment by tuhdo** [comment]
You should also update the pictures. Instead of link to external links, it should be stored somewhere in Spacemacs and link to the file, so Emacs can display it inline.

Current, the picture resolution is too big on my 13'' laptop screen. You should test it with low resolutions.

Also, I think the pictures should be wrapped inside a `#+BEGIN_QUOTE` .... `#+END_QUOTE` block, so when a user has a color theme that just happens to have the same background color as the pictures, he won't be confused.

**Comment by syl20bnr** [comment]
> Make spacing consistent with other documentation.

Actually it was the other way around :-D I don't like empty lines all over the place, you cannot see the structure if they are too much. I'll add the rules to the conventions, here they are:
- an empty line at the end of a node
- no empty line after a node title except if the first content is a table

See my commit here: https://github.com/syl20bnr/spacemacs/commit/920f01a776b1f200c726dda6a7cc9cb602a99fd8

**Comment by person808** [comment]
> Actually it was the other way around

0.0 wat. I swore it was the other way. Reverted those changes back to how they were.

@tuhdo I'm not sure `BEGIN_QUOTE` and `END_QUOTE` made any difference when I tested it using the same colorscheme as the screenshots. I added the files but did not add the quotes yet.

**Comment by syl20bnr** [comment]
I saw that this "convention" is not really applied in the READMEs... well I may fix then when I encounter them. Fact is sometime leaving an empty line feels better, it depends on the size of the paragraphs, but well let stick with what I wrote above.

Thank you ! :+1: 
Cherry-picked to develop branch, you can safely delete your branch.

**Pull request closed without merging**
