### PR TITLE
Fix Magit manual link

### PR DESCRIPTION
**Pull request by jdelStrother**
Hi there - the current link to the magit manual is broken.   I think it should be http://magit.vc/manual/magit/Status-buffer.html#Status-buffer ?

### CODE REVIEW

**Comment by person808** [comment]
Already fixed in the `develop` branch

**Comment by robbyoconnor** [comment]
ALWAYS do PRs Against `develop` -- the state of `master` is irrelevant when contributing.

**Comment by syl20bnr** [comment]
Thank you, I was able to merge your PR since the provided link was a bit different and I think it makes sense to redirect on the help for the status buffer.
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by jdelStrother** [comment]
Thanks @syl20bnr

**Pull request closed without merging**
