### PR TITLE
Add a gentoo/ebuild layer

### PR DESCRIPTION
**Pull request by kwohlfahrt**
This adds an ebuild-mode for developing gentoo ebuilds, as requested in #6606.

This is the first layer I've made, so let me know if I've done anything wrong!

### CODE REVIEW

**Comment by bmag** [comment]
Not sure what the comment of the second commit is supposed to mean. If there's a problem with the PR, please explain it in this thread. In any case, we prefer a single commit for simple PRs like this one, so please squash.

**Comment by kwohlfahrt** [comment]
Squashed. There was a warning along those lines in `*Messages*` when I first loaded the layer. I can't reproduce now though.

**Comment by bmag** [comment]
> There was a warning along those lines in `*Messages*` when I first loaded the layer. I can't reproduce now though.

OK, we can probably ignore that.

**Comment by robbyoconnor** [comment]
SVGs also dont work -- use a PNG?

**Comment by kwohlfahrt** [comment]
Converted SVG to PNG.

**Comment by TheBB** [comment]
Thanks! Cherry-picked in develop. You can safely delete your branch.

I moved it to the new `major-modes` layer since it was so small.

**Pull request closed without merging**
