### PR TITLE
Better copywriting in Introduction section of README

### PR DESCRIPTION
**Pull request by purcell**
Spacemacs is getting really popular, and this section doesn't read very naturally to native English speakers, so here's a better version which will be clearer and convince more people to try Spacemacs. :-)

### CODE REVIEW

**Comment by nashamri** [comment]
Hey @purcell it's good to see you here :smile: and I like the changes you made in the README. A tiny note, I think the convention is to send PRs agains the `develop` branch.

[just leaving this here](https://github.com/syl20bnr/spacemacs/blob/master/doc/CONTRIBUTE.org)

**Comment by purcell** [comment]
Oops, thanks. There, that should be fixed.

**Comment by TheBB** [comment]
@purcell I believe you just rebased your branch on the develop branch, which is good. The PR is still against master, however, so now it's proposing to merge all of develop's 100+ commits into master.

If you can close this and open a new PR, and make sure you choose `syl20bnr/develop` as the target branch. Thanks! :+1:

**Comment by TheBB** [comment]
For that matter, we can still merge this manually, so it's not a big deal.

**Comment by purcell** [comment]
Done, thanks: #3332. No need to merge manually.

**Pull request closed without merging**
