### PR TITLE
fix url jump error

### PR DESCRIPTION
**Pull request by TinySong**
fix url jump error in comments

### CODE REVIEW

**Comment by bmag** [comment]
Not sure what the error is. Please explain the issue (or link to an existing issue).

**Comment by sdwolf** [comment]
The closing paranthesis is considered part of the url. I confirm this bug and 👍 the fix.

**Comment by bmag** [comment]
> ... is considered part ...

Considered by what? When using `SPC x o` it tries to open a URL that contains the closing parenthesis, or is it something else?

**Comment by duianto** [comment]
Confirmed. With the cursor on the url, if one presses `SPC x o` then the default browser opens a github 404 page, and the address bar includes the closing parenthesis.

**Comment by sdwolf** [comment]
The following link:
```emacs-lisp
;; (see https://github.com/syl20bnr/spacemacs/pull/8065)
```
Opens `https://github.com/syl20bnr/spacemacs/pull/8065)` in a browser, which is 404.

The fixed link:
```emacs-lisp
;; (see https://github.com/syl20bnr/spacemacs/pull/8065 )
```
Opens the expected `https://github.com/syl20bnr/spacemacs/pull/8065` in a browser.

**Comment by bmag** [comment]
Possibly an upstream bug in [link-hint](https://github.com/noctuid/link-hint.el) (unless it's an intended behavior or a known issue). Can someone ask them please?

**Comment by duianto** [comment]
It has been reported upstream: https://github.com/noctuid/link-hint.el/issues/15

**Comment by noctuid** [comment]
Just to clarify, this is a bug in emacs' url libraries (see my post at the above link). Org mode doesn't have this problem though. I can look into alternatives, but I'm not personally familiar with rules related to parens in urls and am not the right person to solve this.

**Comment by syl20bnr** [comment]
Thank you ! 👍 
I removed the parenthesis in an additional commit.
Cherry-picked into develop branch, you can safely delete your branch.

**Pull request closed without merging**
