### PR TITLE
Fix vim-powerline 

### LINKED ISSUE #3216: vim-powerline is not working after the change from mode-line to spaceline
After the commit `6757ce7` which changed mode-line to spaceline, if I include `vim-powerline` in `dotspacemacs-configuration-layers`, the initialization process of emacs will not be complete, though there seems to be no error message shown. I'm on OS X 10.10

### PR DESCRIPTION
**Pull request by robbyoconnor**
Not sure why this works but it does. 

Resolves #3216

### CODE REVIEW

**Comment by robbyoconnor** [comment]
An alternative idea is to remove `vim-powerline` altogether.

**Comment by TheBB** [comment]
Thanks! Since the package included by the spacemacs layer is now spaceline, and not powerline, excluding powerline won't do anything. Cherry-picked in develop.

**Comment by TheBB** [comment]
That is to say, excluding packages doesn't work with dependencies.

**Comment by robbyoconnor** [comment]
I'm not sure what the problem was...it was me trying it out and it seemed to fix the problem...pure shot in the dark

**Pull request closed without merging**
