### PR TITLE
[WIP] add snippets directory to purescript layer

### PR DESCRIPTION
**Pull request by kRITZCREEK**
This stops yasnippet initialization from erroring on purescript-mode
startup

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
darned. I just got the error again...

```
[yas] Loading snippet files from /home/creek/.emacs.d/elpa/haskell-snippets-20160121.1458/snippets/haskell-mode
File mode specification error: (file-error "Opening directory" "datei oder Verzeichnis nicht gefunden" "/home/creek/Documents/chromacannon/src/snippets") [2 times]
```

This is the error I'm getting when I try to open `/home/creek/Documents/chromacannon/src/Main.purs`

Does someone have an idea on how to fix this?

**Comment by TheBB** [comment]
I also have this error.

**Comment by TheBB** [comment]
See #5373

**Comment by kRITZCREEK** [comment]
I'll close this then since it solves nothing. Thanks for your investigations

**Pull request closed without merging**
