### PR TITLE
* core/core-configuration-layer.el: support package-quickstart

### PR DESCRIPTION
**Pull request by sunlin7**
A draft to support `package-quickstart`. 
Request the MR https://github.com/syl20bnr/spacemacs/pull/16650 to be merged first, then this MR will works.

### CODE REVIEW

**Comment by smile13241324** [comment]
The related MR has been merged @sunlin7

**Comment by smile13241324** [comment]
The change looks good, though I would like to make another review when its state has been changed to ready.

**Comment by sunlin7** [comment]
Thank you, I'm adding some document to show how it works, will update later.

**Comment by sunlin7** [comment]
@smile13241324  I had finished the `package-quickstart` support.  The document is in another PR: #16661.
Please help review the changes, thank you!

**Review by smile13241324 — APPROVED** [review]

**Comment by bcc32** [comment]
This PR causes the same problem as #16615 w.r.t. themes that the user installed through `dotspacemacs-additional-packages`.  If the theme package is installed, it will at least be applied correctly after all packages have been installed and after layer loading, etc.

But the code to apply the theme immediately at startup is now broken.  See `spacemacs/load-default-theme`.

If `package-quickstart` and `dotspacemacs-enable-package-quickstart` are nil, you still need to manually call `package-initialize` during startup, because `early-init.el` sets `package-enable-on-startup` to nil.

**Pull request merged**
